[properties]
root_delivery="/scor/scoromega/delivery/3G_DEV/"
url_itk="http://dcvprdsvn/refsvn/OMEGA-2/branches/3G_DELIVERY/OM2.DELIVERY/OM2.3G_DELIVERY_ITK.csv"
csvFile="/scor/scoromega/delivery/3G_DEV/OM2.DELIVERY/OM2.3G_DEV_DEV.csv"
