[properties]
root_delivery="/scor/scoromega/delivery/3G_DELIVERY/"
listComponentsFile="/scor/scoromega/delivery/3G_DELIVERY/OM2.DELIVERY/OM2.3G_DELIVERY_ITK.csv"
branches=http://dcvprdsvn/refsvn/OMEGA-2/branches/3G_DEV/omega2-sql/global/
branches2=http://dcvprdsvn.eu.scor.local/refsvn/OMEGA-2/branches/3G_DEV/omega2-sql/global/
