[properties]
root_delivery="/scor/scoromega/delivery/3H_DELIVERY/"
listComponentsFile="/scor/scoromega/delivery/3H_DELIVERY/OM2.DELIVERY/OM2.3H_DELIVERY_ITK.csv"
branches=http://dcvprdsvn/refsvn/OMEGA-2/branches/3H_DEV/omega2-sql/global/
branches2=http://dcvprdsvn.eu.scor.local/refsvn/OMEGA-2/branches/3H_DEV/omega2-sql/global/
status=TBC
