--
-- TABLE INSERT STATEMENTS
--

DELETE FROM BREF..TPRSMAP WHERE ACMTRS_NT = 2090 AND PRS_CF = 751

INSERT INTO BREF..TPRSMAP ( PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10 ) 
        VALUES ( 751, 2090, 'PR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL )
go
