USE BEST
go

--[001] 07/04/2020 Roger : SPIRA 76698 : Nouveau mapping pour fichier ESL_DLOPNGTAALO

-----------------------------------------------------------------------------------------------------------
print '------>>>>  [76698] ESL_DLOPNGTAALO' 

delete BEST..TI17PERMFIL
where PERMFIL_CT in ('ESL_DLREJGTAALO','ESL_DLREJGTAALO_CUR','ESL_DLREJGTAALO_CURNEW','ESL_DLREJGTARLO','ESL_DLREJGTARLO_CUR',
                     'ESL_DLREJGTARLO_CURNEW','ESL_DLREJGTRLO','ESL_DLREJGTRLO_CUR','ESL_DLREJGTRLO_CURNEW',
                     'ESL_DLOPNGTAALO','ESL_DLOPNGTARLO','ESL_DLOPNGTRLO')
and IDF_CT in ('ESLD2900')

insert into BEST..TI17PERMFIL values ('ESLD2900', 'ESL_DLOPNGTAALO','${DFILP}/${ENV_PREFIX}_ESLD2900_DLOPNGTAALO.dat','O','')
insert into BEST..TI17PERMFIL values ('ESLD2900', 'ESL_DLOPNGTARLO','${DFILP}/${ENV_PREFIX}_ESLD2900_DLOPNGTARLO.dat','O','')
insert into BEST..TI17PERMFIL values ('ESLD2900', 'ESL_DLOPNGTRLO', '${DFILP}/${ENV_PREFIX}_ESLD2900_DLOPNGTRLO.dat','O','')
insert into BEST..TI17PERMFIL values ('ESLD2900', 'ESL_DLREJGTAALO', '${DFILP}/${ENV_PREFIX}_ESLD1900_DLREJGTAALO.dat','O','')
insert into BEST..TI17PERMFIL values ('ESLD2900', 'ESL_DLREJGTAALO_CUR', '${DFILP}/${ENV_PREFIX}_ESLD1900_DLREJGTAALO_CUR.dat','I','')
insert into BEST..TI17PERMFIL values ('ESLD2900', 'ESL_DLREJGTAALO_CURNEW', '${DFILP}/${ENV_PREFIX}_ESLD1900_DLREJGTAALO_CURNEW.dat','O','')
insert into BEST..TI17PERMFIL values ('ESLD2900', 'ESL_DLREJGTARLO', '${DFILP}/${ENV_PREFIX}_ESLD1900_DLREJGTARLO.dat','O','')
insert into BEST..TI17PERMFIL values ('ESLD2900', 'ESL_DLREJGTARLO_CUR', '${DFILP}/${ENV_PREFIX}_ESLD1900_DLREJGTARLO_CUR.dat','I','')
insert into BEST..TI17PERMFIL values ('ESLD2900', 'ESL_DLREJGTARLO_CURNEW', '${DFILP}/${ENV_PREFIX}_ESLD1900_DLREJGTARLO_CURNEW.dat','O','')
insert into BEST..TI17PERMFIL values ('ESLD2900', 'ESL_DLREJGTRLO', '${DFILP}/${ENV_PREFIX}_ESLD1900_DLREJGTRLO.dat','O','')
insert into BEST..TI17PERMFIL values ('ESLD2900', 'ESL_DLREJGTRLO_CUR', '${DFILP}/${ENV_PREFIX}_ESLD1900_DLREJGTRLO_CUR.dat','I','')
insert into BEST..TI17PERMFIL values ('ESLD2900', 'ESL_DLREJGTRLO_CURNEW', '${DFILP}/${ENV_PREFIX}_ESLD1900_DLREJGTRLO_CURNEW.dat','O','')

print '------>>>>  [76698] End ESL_DLOPNGTAALO' 

go
----------------------------------------------------------------

