USE BEST
go

--[001] 22/04/2020 Roger : SPIRA 86503-86536 : Nouveau mapping pour fichier EPO_FCTREST


-----------------------------------------------------------------------------------------------------------
print '------>>>>  [86503] EPO_FCTREST' 

-- Supprime ancien mapping plus valable
delete BEST..TI17PERMFIL
where PERMFIL_CT = 'EPO_FCTREST_LOADCTL'

-- Supprime ancien mapping plus valable
delete BEST..TI17PERMFIL
where PERMFIL_CT = 'EPO_FCTREST'

delete BEST..TI17PERMFIL
where PERMFIL_CT in ('EPO_FCTRESTA','EPO_FCTRESTF','EPO_FCTRESTF0','EPO_FCTREST0')
and IDF_CT in ('ESPD8000_POSE', 'ESPD8000_POCE', 'ESPD8000_BookingPOSE', 'ESPD8000_BookingPOCE', 'ESPD8000_BookingPOSEAnnuel', 'ESPD8000_BookingPOCEAnnuel',
               'ESID2210_POSE', 'ESID2210_POCE', 'ESID2210_BookingPOSE', 'ESID2210_BookingPOCE', 'ESID2210_BookingPOSEAnnuel', 'ESID2210_BookingPOCEAnnuel','ESPD0060')

insert into BEST..TI17PERMFIL values ('ESPD0060',  'EPO_FCTRESTA','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTRESTASIISO.dat','O','')
insert into BEST..TI17PERMFIL values ('ESPD0060',  'EPO_FCTRESTF','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTRESTFSIISO.dat','O','')
insert into BEST..TI17PERMFIL values ('ESPD0060',  'EPO_FCTRESTF0','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTRESTF0SIISO.dat','O','')
insert into BEST..TI17PERMFIL values ('ESPD0060',  'EPO_FCTREST0','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTREST0SIISO.dat','O','')

insert into BEST..TI17PERMFIL values ('ESPD8000_POSE',  'EPO_FCTRESTA','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTRESTASIISO.dat','I','')
insert into BEST..TI17PERMFIL values ('ESPD8000_POCE',  'EPO_FCTRESTA','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTRESTASIICO.dat','I','')
insert into BEST..TI17PERMFIL values ('ESPD8000_BookingPOSE',  'EPO_FCTRESTA','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTRESTASIISO.dat','I','')
insert into BEST..TI17PERMFIL values ('ESPD8000_BookingPOCE',  'EPO_FCTRESTA','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTRESTASIICO.dat','I','')
insert into BEST..TI17PERMFIL values ('ESPD8000_BookingPOSEAnnuel',  'EPO_FCTRESTA','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTRESTASIISO.dat','I','')
insert into BEST..TI17PERMFIL values ('ESPD8000_BookingPOCEAnnuel',  'EPO_FCTRESTA','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTRESTASIICO.dat','I','')
insert into BEST..TI17PERMFIL values ('ESID2210_POSE',  'EPO_FCTRESTA','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTRESTASIISO.dat','I','')
insert into BEST..TI17PERMFIL values ('ESID2210_POCE',  'EPO_FCTRESTA','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTRESTASIICO.dat','I','')
insert into BEST..TI17PERMFIL values ('ESID2210_BookingPOSE',  'EPO_FCTRESTA','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTRESTASIISO.dat','I','')
insert into BEST..TI17PERMFIL values ('ESID2210_BookingPOCE',  'EPO_FCTRESTA','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTRESTASIICO.dat','I','')
insert into BEST..TI17PERMFIL values ('ESID2210_BookingPOSEAnnuel',  'EPO_FCTRESTA','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTRESTASIISO.dat','I','')
insert into BEST..TI17PERMFIL values ('ESID2210_BookingPOCEAnnuel',  'EPO_FCTRESTA','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTRESTASIICO.dat','I','')

insert into BEST..TI17PERMFIL values ('ESPD8000_POSE',  'EPO_FCTRESTF','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTRESTFSIISO.dat','I','')
insert into BEST..TI17PERMFIL values ('ESPD8000_POCE',  'EPO_FCTRESTF','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTRESTFSIICO.dat','I','')
insert into BEST..TI17PERMFIL values ('ESPD8000_BookingPOSE',  'EPO_FCTRESTF','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTRESTFSIISO.dat','I','')
insert into BEST..TI17PERMFIL values ('ESPD8000_BookingPOCE',  'EPO_FCTRESTF','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTRESTFSIICO.dat','I','')
insert into BEST..TI17PERMFIL values ('ESPD8000_BookingPOSEAnnuel',  'EPO_FCTRESTF','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTRESTFSIISO.dat','I','')
insert into BEST..TI17PERMFIL values ('ESPD8000_BookingPOCEAnnuel',  'EPO_FCTRESTF','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTRESTFSIICO.dat','I','')
insert into BEST..TI17PERMFIL values ('ESID2210_POSE',  'EPO_FCTRESTF','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTRESTFSIISO.dat','I','')
insert into BEST..TI17PERMFIL values ('ESID2210_POCE',  'EPO_FCTRESTF','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTRESTFSIICO.dat','I','')
insert into BEST..TI17PERMFIL values ('ESID2210_BookingPOSE',  'EPO_FCTRESTF','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTRESTFSIISO.dat','I','')
insert into BEST..TI17PERMFIL values ('ESID2210_BookingPOCE',  'EPO_FCTRESTF','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTRESTFSIICO.dat','I','')
insert into BEST..TI17PERMFIL values ('ESID2210_BookingPOSEAnnuel',  'EPO_FCTRESTF','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTRESTFSIISO.dat','I','')
insert into BEST..TI17PERMFIL values ('ESID2210_BookingPOCEAnnuel',  'EPO_FCTRESTF','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTRESTFSIICO.dat','I','')

insert into BEST..TI17PERMFIL values ('ESPD8000_POSE',  'EPO_FCTRESTF0','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTRESTF0SIISO.dat','I','')
insert into BEST..TI17PERMFIL values ('ESPD8000_POCE',  'EPO_FCTRESTF0','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTRESTF0SIICO.dat','I','')
insert into BEST..TI17PERMFIL values ('ESPD8000_BookingPOSE',  'EPO_FCTRESTF0','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTRESTF0SIISO.dat','I','')
insert into BEST..TI17PERMFIL values ('ESPD8000_BookingPOCE',  'EPO_FCTRESTF0','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTRESTF0SIICO.dat','I','')
insert into BEST..TI17PERMFIL values ('ESPD8000_BookingPOSEAnnuel',  'EPO_FCTRESTF0','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTRESTF0SIISO.dat','I','')
insert into BEST..TI17PERMFIL values ('ESPD8000_BookingPOCEAnnuel',  'EPO_FCTRESTF0','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTRESTF0SIICO.dat','I','')
insert into BEST..TI17PERMFIL values ('ESID2210_POSE',  'EPO_FCTRESTF0','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTRESTF0SIISO.dat','I','')
insert into BEST..TI17PERMFIL values ('ESID2210_POCE',  'EPO_FCTRESTF0','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTRESTF0SIICO.dat','I','')
insert into BEST..TI17PERMFIL values ('ESID2210_BookingPOSE',  'EPO_FCTRESTF0','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTRESTF0SIISO.dat','I','')
insert into BEST..TI17PERMFIL values ('ESID2210_BookingPOCE',  'EPO_FCTRESTF0','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTRESTF0SIICO.dat','I','')
insert into BEST..TI17PERMFIL values ('ESID2210_BookingPOSEAnnuel',  'EPO_FCTRESTF0','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTRESTF0SIISO.dat','I','')
insert into BEST..TI17PERMFIL values ('ESID2210_BookingPOCEAnnuel',  'EPO_FCTRESTF0','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTRESTF0SIICO.dat','I','')

insert into BEST..TI17PERMFIL values ('ESPD8000_POSE',  'EPO_FCTREST0','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTREST0SIISO.dat','I','')
insert into BEST..TI17PERMFIL values ('ESPD8000_POCE',  'EPO_FCTREST0','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTREST0SIICO.dat','I','')
insert into BEST..TI17PERMFIL values ('ESPD8000_BookingPOSE',  'EPO_FCTREST0','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTREST0SIISO.dat','I','')
insert into BEST..TI17PERMFIL values ('ESPD8000_BookingPOCE',  'EPO_FCTREST0','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTREST0SIICO.dat','I','')
insert into BEST..TI17PERMFIL values ('ESPD8000_BookingPOSEAnnuel',  'EPO_FCTREST0','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTREST0SIISO.dat','I','')
insert into BEST..TI17PERMFIL values ('ESPD8000_BookingPOCEAnnuel',  'EPO_FCTREST0','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTREST0SIICO.dat','I','')
insert into BEST..TI17PERMFIL values ('ESID2210_POSE',  'EPO_FCTREST0','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTREST0SIISO.dat','I','')
insert into BEST..TI17PERMFIL values ('ESID2210_POCE',  'EPO_FCTREST0','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTREST0SIICO.dat','I','')
insert into BEST..TI17PERMFIL values ('ESID2210_BookingPOSE',  'EPO_FCTREST0','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTREST0SIISO.dat','I','')
insert into BEST..TI17PERMFIL values ('ESID2210_BookingPOCE',  'EPO_FCTREST0','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTREST0SIICO.dat','I','')
insert into BEST..TI17PERMFIL values ('ESID2210_BookingPOSEAnnuel',  'EPO_FCTREST0','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTREST0SIISO.dat','I','')
insert into BEST..TI17PERMFIL values ('ESID2210_BookingPOCEAnnuel',  'EPO_FCTREST0','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTREST0SIICO.dat','I','')

print '------>>>>  [86503] End EPO_FCTREST' 
go
----------------------------------------------------------------



