
USE BEST
go

if not exists (select 1 from syscolumns
    where id = object_id("dbo.TCTRGRO")
        and name = "UWY_NF")
begin
	alter table TCTRGRO add UWY_NF UUWY_NF NULL

	  IF EXISTS (SELECT * FROM sysindexes WHERE id=OBJECT_ID('dbo.TCTRGRO') AND name='ICTRGRO_00')
	  BEGIN
			  DROP INDEX TCTRGRO.ICTRGRO_00
			  IF EXISTS (SELECT * FROM sysindexes WHERE id=OBJECT_ID('dbo.TCTRGRO') AND name='ICTRGRO_00')
					PRINT '<<< FAILED DROPPING INDEX dbo.TCTRGRO.ICTRGRO_00 >>>'
			ELSE
					PRINT '<<< DROPPED INDEX dbo.TCTRGRO.ICTRGRO_00 >>>'
	END

	  CREATE UNIQUE CLUSTERED INDEX ICTRGRO_00
			  ON dbo.TCTRGRO(CTR_NF,END_NT,SEC_NF,VRS_NF,SSD_CF,SEGTYP_CT,SEG_NF,UWY_NF)
	  LOCAL INDEX ICTRGRO_00_1017051628

	  IF EXISTS (SELECT * FROM sysindexes WHERE id=OBJECT_ID('dbo.TCTRGRO') AND name='ICTRGRO_00')
			  PRINT '<<< CREATED INDEX dbo.TCTRGRO.ICTRGRO_00 >>>'
	  ELSE
			  PRINT '<<< FAILED CREATING INDEX dbo.TCTRGRO.ICTRGRO_00 >>>'
end
else
	alter table TCTRGRO MODIFY  UWY_NF UUWY_NF NULL
go

