USE BEST
go
/*==============================================================*/
/* DBMS name:      Sybase AS Enterprise 15.7                    */
/* Created on:     18/04/2019 15:02:36                          */
/*==============================================================*/


grant SELECT on TI17CHN to GCONSULT
go

grant SELECT,INSERT,DELETE,UPDATE,REFERENCES on TI17CHN to GDBBATCH
go

grant SELECT,INSERT,DELETE,UPDATE,REFERENCES on TI17CHN to GOMEGA
go

grant SELECT on TI17FNC to GCONSULT
go

grant SELECT,INSERT,DELETE,UPDATE,REFERENCES on TI17FNC to GDBBATCH
go

grant SELECT,INSERT,DELETE,UPDATE,REFERENCES on TI17FNC to GOMEGA
go

grant SELECT on TI17PERMFIL to GCONSULT
go

grant UPDATE,REFERENCES,DELETE,SELECT,INSERT on TI17PERMFIL to GDBBATCH
go

grant SELECT,INSERT,DELETE,UPDATE,REFERENCES on TI17PERMFIL to GOMEGA
go

grant SELECT on TI17REQ to GCONSULT
go

grant SELECT,INSERT,DELETE,UPDATE,REFERENCES on TI17REQ to GDBBATCH
go

grant SELECT,INSERT,DELETE,UPDATE,REFERENCES on TI17REQ to GOMEGA
go

grant SELECT on TI17REQCHN to GCONSULT
go

grant REFERENCES,UPDATE,DELETE,INSERT,SELECT on TI17REQCHN to GDBBATCH
go

grant SELECT,INSERT,DELETE,UPDATE,REFERENCES on TI17REQCHN to GOMEGA
go

grant SELECT on dbo.TI17REQJOB to GCONSULT
go

grant SELECT,INSERT,DELETE,UPDATE,REFERENCES on dbo.TI17REQJOB to GDBBATCH
go

grant REFERENCES,DELETE,UPDATE,INSERT,SELECT on dbo.TI17REQJOB to GOMEGA
go

grant SELECT on dbo.TI17REQJOBPLAN to GCONSULT
go

grant SELECT,INSERT,DELETE,UPDATE,REFERENCES on dbo.TI17REQJOBPLAN to GDBBATCH
go

grant SELECT,INSERT,DELETE,UPDATE,REFERENCES on dbo.TI17REQJOBPLAN to GOMEGA
go

