USE BEST
go

----------------------------------------------------------------------------------------------------------
-- [001] 05/05/2020 LEL : SPIRA 86487/86487/84496  : Set up new chain ESFT0000
-- [002] 12/05/2020 JYP : SPIRA 82719: RA files for transition
-- [003] 14/05/2020 JYP : SPIRA 82719: add ICR patterne file
-- [004] 19/05/2020 JYP : SPIRA 82719: add RARAT and CTRGRO file for transition
-- [005] 26/05/2020 JYP : SPIRA 82719: bugfix pattern file ICR
-- [006] 27/05/2020 JYP : SPIRA 82719: bugfix mapping ESFT0000
-- [007] 29/05/2020 LEL : SPIRA 82720: comment ESF_FSEGPATTERN_ICR ( not used )
-- [008] 04/06/2020 LEL : SPIRA 82718: Set up RETRO NP Chain ESFD2570
-- [008] 05/06/2020 LEL : SPIRA 82718: Set up RETRO P Chain ESFD2550
-- [009] 15/06/2020 LEL : SPIRA 82714: prepare DSC/LKI files
-- [010] 18/06/2020 LEL : SPIRA 84240: SSET UP CSF preparation
-- [011] 05/10/2020 LEL/JYP : SPIRA 84240: new file transition dat
-- [012] 05/10/2020 LEL/JYP : SPIRA 84240: new version with all transition mapping
-- [013] 20/10/2020 LEL/JYP : SPIRA 86487: new mapping for transition
-- [014] 21/10/2020 LEL : SPIRA 84240: transition cashflow
-- [015] 28/10/2020 JYP : SPIRA 83609 : microAOC, DSC now with date
-- [016] 16/11/2020 LEL : SPIRA 85404 : Initialisation mapping transition
-- [017] 18/11/2020 AGD : SPIRA 84457 : Set up mapping for transition of ESFD3720 and ESFD3750
-- [018] 23/11/2020 ART : SPIRA 84457 : Set up mapping for transition of ESFT0010 and ESFT0020
-- [019] 15/12/2020 LEL : SPIRA 90446 ADD new input files chain ESFD3690
-- [020] 21/12/2020 NLD : SPIRA 91536 : Pericase INI, Parent/Local 
-- [021] 08/01/2021 LEL : SPIRA 92596 : INPUT FILES NOT USED : EPO_DLDGTR_E & EPO_DLDGTAA
-- [022] 18/01/2021	CAS : SPIRA 91843 : Transition : Run Off Contracts
----------------------------------------------------------------------------------------------------------


----------------------------------------------------------------------------------------------------------
--
-- CHAIN ESFT0000
--
----------------------------------------------------------------------------------------------------------
print '------>>>>  ESFT0000 I17G_TRN_ALL_INI' 

delete 	BEST..TI17TRAPERMFIL where IDF_CT = 'I17G_TRN_ALL_INI'
delete  BEST..TI17REQCHN where IDF_CT = 'I17G_TRN_ALL_INI'
delete  BEST..TI17CHN  where CHAIN_CT="ESFT0000"

insert into BEST..TI17CHN values ("ESFT0000","Data TRANSITION extraction")

delete  BEST..TI17FNC  where IDF_CT in ( 'I17G_TRN_ALL_INI'  )
insert into BEST..TI17FNC values ("I17G_TRN_ALL_INI","Get data IFRS 17 GROUP")

insert into BEST..TI17REQCHN values ('I17GMINV',  "ESFT0000","I17G_TRN_ALL_INI","")
insert into BEST..TI17REQCHN values ('I17GMINVB', "ESFT0000","I17G_TRN_ALL_INI","")
insert into BEST..TI17REQCHN values ('I17GQINV',  "ESFT0000","I17G_TRN_ALL_INI","")
insert into BEST..TI17REQCHN values ('I17GQINVB', "ESFT0000","I17G_TRN_ALL_INI","")
insert into BEST..TI17REQCHN values ('I17GQPOS',  "ESFT0000","I17G_TRN_ALL_INI","")
insert into BEST..TI17REQCHN values ('I17GQPOSB', "ESFT0000","I17G_TRN_ALL_INI","")
insert into BEST..TI17REQCHN values ('I17GQPOC',  "ESFT0000","I17G_TRN_ALL_INI","")
insert into BEST..TI17REQCHN values ('I17GQPOCB', "ESFT0000","I17G_TRN_ALL_INI","")
insert into BEST..TI17REQCHN values ('I17GYINV',  "ESFT0000","I17G_TRN_ALL_INI","")
insert into BEST..TI17REQCHN values ('I17GYINVB', "ESFT0000","I17G_TRN_ALL_INI","")
insert into BEST..TI17REQCHN values ('I17GYPOS',  "ESFT0000","I17G_TRN_ALL_INI","")
insert into BEST..TI17REQCHN values ('I17GYPOSB', "ESFT0000","I17G_TRN_ALL_INI","")
insert into BEST..TI17REQCHN values ('I17GYPOC',  "ESFT0000","I17G_TRN_ALL_INI","")
insert into BEST..TI17REQCHN values ('I17GYPOCB', "ESFT0000","I17G_TRN_ALL_INI","")


DELETE FROM  BEST..TI17TRAPERMFIL where IDF_CT IN ('I17G_TRN_ALL_INI')

INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_TRN_ALL_INI', 'TRANSITION_DATA', '${DFILP}/${PCH}ESFT0020_I17G_OMG_ALL_TRA_TRANSITION_FILE.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_TRN_ALL_INI', 'EPO_IRDPERICASE0', '${DFILP}/${PCH}ESEH1100_IRDPERICASE_I17G_NP_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_TRN_ALL_INI', 'EPO_IRDPERICASE0_EBS','${DFILP}/${PCH}ESPT0000_IRDPERICASE0.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_TRN_ALL_INI', 'EPO_IADPERICASE', '${DFILP}/${PCH}ESPT0000_IADPERICASE_${PARM_ICLODAT_D}.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_TRN_ALL_INI', 'ESF_FMARKET_STD', '${DFILP}/${PCH}ESFD0060_FMARKET_${PARM_ICLODAT_D}.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_TRN_ALL_INI', 'ESF_FCTRGRO_STD', '${DFILP}/${PCH}ESPT0000_FCTRGRO.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_TRN_ALL_INI', 'ESF_FRERETFACCTR_INI', '${DFILP}/${PCH}ESFD1130_TRERETFACCTR.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_TRN_ALL_INI', 'ESF_FSEGPATTERN_CSF_TRN', '${DFILP}/${PCH}ESFT0000_I17G_TRN_ALL_INI_FSEGPATTERN_CSF_${PARM_ICLODAT_D}.dat', 'O', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_TRN_ALL_INI', 'ESF_FSEGPATTERN_ICR_TRN', '${DFILP}/${PCH}ESFT0000_I17G_TRN_ALL_INI_FSEGPATTERN_ICR_${PARM_ICLODAT_D}.dat', 'O', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_TRN_ALL_INI', 'ESF_IADPERICASE_TRN', '${DFILP}/${PCH}ESFT0000_I17G_TRN_ALL_INI_IADPERICASE_${PARM_ICLODAT_D}.dat', 'O', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_TRN_ALL_INI', 'ESF_IRDPERICASE0_TRN', '${DFILP}/${PCH}ESFT0000_I17G_TRN_ALL_INI_IRDPERICASE_NP.dat', 'O', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_TRN_ALL_INI', 'ESF_IRDPERICASE0_PNP_TRN', '${DFILP}/${PCH}ESFT0000_I17G_TRN_ALL_INI_IRDPERICASE0_PNP.dat', 'O', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_TRN_ALL_INI', 'ESF_FMARKET_TRN', '${DFILP}/${PCH}ESFT0000_I17G_TRN_ALL_INI_FMARKET_${PARM_ICLODAT_D}.dat', 'O', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_TRN_ALL_INI', 'ESF_FUWRETSEC_TRN', '${DFILP}/${PCH}ESFT0000_I17G_TRN_ALL_INI_FUWRETSEC.dat', 'O', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_TRN_ALL_INI', 'ESF_FRARAT_TRN', '${DFILP}/${PCH}ESFT0000_I17G_TRN_ALL_INI_RARAT_${param_Context_id}_${PARM_ICLODAT_D}.dat', 'O', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_TRN_ALL_INI', 'ESF_FCTRGRO_TRN', '${DFILP}/${PCH}ESFT0000_I17G_TRN_ALL_INI_FCTRGRO.dat', 'O', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_TRN_ALL_INI', 'ESF_FCTRGRO_SEGNF_TRN', '${DFILP}/${PCH}ESFT0000_I17G_TRN_ALL_INI_FCTRGRO_SEGNF.dat', 'O', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_TRN_ALL_INI', 'ESF_FRERETFACCTR_INI_TRN', '${DFILP}/${PCH}ESFT0000_I17G_TRN_ALL_INI_FRERETFACCTR_TRN.dat', 'O', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_TRN_ALL_INI', 'ESF_FSEGEST_TRN', '${DFILP}/${PCH}ESFT0000_I17G_TRN_ALL_INI_FSEGEST_TRN_${PARM_ICLODAT_D}.dat', 'O', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_TRN_ALL_INI', 'ESF_IADVPERICASE_P', '${DFILP}/${PCH}ESEH1100_IADVPERICASE_P_INI.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_TRN_ALL_INI', 'ESF_IRDPERICASE0_P_TRN', '${DFILP}/${PCH}ESFT0000_I17G_TRN_ALL_INI_IADVPERICASE_P_TRN.dat', 'O', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_TRN_ALL_INI', 'PARM_IS_TRN', 'YES', ' ', ' ' )

   
print '------>>>> End ESFT0000  ' 
go


-----------------------------------------------------------------------------------
--
-- CHAIN ESFD3630 : I17G_IEX_ALL_INI
--
-----------------------------------------------------------------------------------
print '------>>>> Lahcen request : 82720 : ESFD3630 I17G_IEX_ALL_INI ' 

DELETE FROM  BEST..TI17TRAPERMFIL where IDF_CT IN ('I17G_IEX_ALL_INI')

INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_IEX_ALL_INI', 'EPO_DLGTAAPRE', '${DFILP}/empty.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_IEX_ALL_INI', 'EPO_FCTRGRO', '${DFILP}/${PCH}ESPT0000_FCTRGRO.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_IEX_ALL_INI', 'EPO_FCURQUOT', '${DFILP}/${PCH}ESPT0000_FCURQUOT.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_IEX_ALL_INI', 'EPO_FTECLEDA', '${DFILP}/empty.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_IEX_ALL_INI', 'EPO_GTSII_GLOBAL_CASHFLOW', '${DFILP}/${PCH}ESFD3610_I17G_CSF_ALL_INI_GTSII_GLOBAL_CASHFLOW${TYPEINV0}_${PARM_ICLODAT_D}.dat', 'I', ' ' ) 
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_IEX_ALL_INI', 'EPO_IADPERICASE', '${DFILP}/${PCH}ESFT0000_I17G_TRN_ALL_INI_IADPERICASE_${PARM_ICLODAT_D}.dat', 'I', ' ' ) 
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_IEX_ALL_INI', 'EPO_IRDPERICASE0', '${DFILP}/${PCH}ESFT0000_I17G_TRN_ALL_INI_IRDPERICASE0.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_IEX_ALL_INI', 'ESF_EXPENSES', '${DFILP}/${PCH}ESFD3630_I17G_IEX_ALL_INI_EXPENSES_${PARM_ICLODAT_D}.dat', 'O', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_IEX_ALL_INI', 'ESF_FEXPRAT', '${DFILP}/${PCH}ESFD0060_I17G____EXPRAT_${TYPEINV}_${PARM_ICLODAT_D}.dat', 'I', ' ' ) 
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_IEX_ALL_INI', 'ESF_FEXPRAT_PREVQ', '${DFILP}/${PCH}ESFD0060_I17G____EXPRAT_${TYPEINV}_${PARM_PREV_ICLODAT_D}.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_IEX_ALL_INI', 'ESF_FMARKET', '${DFILP}/${PCH}ESFT0000_I17G_TRN_ALL_INI_FMARKET_${PARM_ICLODAT_D}.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_IEX_ALL_INI', 'ESF_FPRSMAP_TXT', '${DFILP}/${PCH}ESFD0060_I17G____FPRSMAP_TXT_${PARM_ICLODAT_D}.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_IEX_ALL_INI', 'ESF_GTSII_GLOBAL_CASHFLOW', '${DFILP}/${PCH}ESFD3630_I17G_IEX_ALL_INI_GTSII_GLOBAL_CASHFLOW_${PARM_ICLODAT_D}.dat', 'O', ' ' ) 
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_IEX_ALL_INI', 'ESF_RET_FEXPRAT', '${DFILP}/${ENV_PREFIX}_ESFD0060_I17G____RET_FEXPRAT_${PARM_ICLODAT_D}.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_IEX_ALL_INI', 'ESF_RET_FEXPRAT_PREVQ', '${DFILP}/${ENV_PREFIX}_ESFD0060_I17G____RET_FEXPRAT_${PARM_PREV_ICLODAT_D}.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_IEX_ALL_INI', 'ESF_RETRO_ITDPREMIUM', '${DFILP}/empty.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_IEX_ALL_INI', 'ESF_RETRO_UPR', '${DFILP}/empty.dat', 'I', '  ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_IEX_ALL_INI', 'EST_FBOPRSLNK_TXT', '${DFILP}/${PCH}ESPT0000_FBOPRSLNK_TXT_${PARM_ICLODAT_D}.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_IEX_ALL_INI', 'EST_FCLIENT_TXT', '${DFILP}/${PCH}ESPT0000_FCLIENT_TXT_${PARM_ICLODAT_D}.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_IEX_ALL_INI', 'EST_FCURQUOT_TXT', '${DFILP}/${PCH}ESPT0000_FCURQUOT_TXT_${PARM_ICLODAT_D}.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_IEX_ALL_INI', 'EST_FPLACEMT22', '${DFILI}/${PCH}ESPD0060_FPLACEMT22.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_IEX_ALL_INI', 'EST_FSEGPATTERN_CSF', '${DFILP}/${PCH}ESFT0000_I17G_TRN_ALL_INI_FSEGPATTERN_CSF_${PARM_ICLODAT_D}.dat', 'I', ' ' ) 
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_IEX_ALL_INI', 'EST_FULAERAT', '${DFILP}/${PCH}ESPD0060_FULAERAT${TYPEINV0}_${PARM_ICLODAT_D}.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_IEX_ALL_INI', 'EST_IGTAA0', '${DFILP}/empty.dat', 'I', ' ' )


print '------>>>> End Lahcen request : 82720 : ESFD3630 I17G_IEX_ALL_INI ' 
go



-----------------------------------------------------------------------------------
--
-- CHAIN ESFD3650 : I17G_RAD_CKI_INI
--
-----------------------------------------------------------------------------------
print '------>>>> ESFD3650 : I17G_RAD_CKI_INI  ' 


DELETE FROM  BEST..TI17TRAPERMFIL where IDF_CT IN ('I17G_RAD_CKI_INI')


insert into BEST..TI17TRAPERMFIL values ('I17G_RAD_CKI_INI',  'EPO_FCTRGRO','${DFILP}/${PCH}ESFT0000_I17G_TRN_ALL_INI_FCTRGRO.dat','I','')
insert into BEST..TI17TRAPERMFIL values ('I17G_RAD_CKI_INI',  'ESF_FMARKET','${DFILP}/${PCH}ESFT0000_I17G_TRN_ALL_INI_FMARKET_${PARM_ICLODAT_D}.dat','I','')
insert into BEST..TI17TRAPERMFIL values ('I17G_RAD_CKI_INI',  'ESF_FUWRETSEC','${DFILP}/${PCH}ESFT0000_I17G_TRN_ALL_INI_FUWRETSEC.dat','I','')
insert into BEST..TI17TRAPERMFIL values ('I17G_RAD_CKI_INI',  'EPO_IADPERICASE','${DFILP}/${PCH}ESFT0000_I17G_TRN_ALL_INI_IADPERICASE_${PARM_ICLODAT_D}.dat','I','')
insert into BEST..TI17TRAPERMFIL values ('I17G_RAD_CKI_INI',  'EPO_FSEGPATTERN_ICR','${DFILP}/${PCH}ESFT0000_I17G_TRN_ALL_INI_FSEGPATTERN_ICR_${PARM_ICLODAT_D}.dat','I','')
insert into BEST..TI17TRAPERMFIL values ('I17G_RAD_CKI_INI',  'ESF_FRARAT','${DFILP}/${PCH}ESFT0000_I17G_TRN_ALL_INI_RARAT_${param_Context_id}_${PARM_ICLODAT_D}.dat','I','')
insert into BEST..TI17TRAPERMFIL values ('I17G_RAD_CKI_INI',  'ESF_GTSII_ESCOMPTE','${DFILP}/${PCH}ESFD3620_I17G_DSC_LKI_INI_GTSII_ESCOMPTE_${PARM_ICLODAT_D}.dat','I','')
insert into BEST..TI17TRAPERMFIL values ('I17G_RAD_CKI_INI',  'ESF_GTSII_RMTP_ULAE','${DFILI}/${PCH}ESFD3650_I17G_RAD_CKI_INI_GTSII_RMTP_ULAE.dat','O','')
insert into BEST..TI17TRAPERMFIL values ('I17G_RAD_CKI_INI',  'ESF_GTSII_CASHFLOW_WK','${DFILI}/${PCH}ESFD3650_I17G_RAD_CKI_INI_GTSII_CASHFLOW_WK.dat','O','')
insert into BEST..TI17TRAPERMFIL values ('I17G_RAD_CKI_INI',  'ESF_GTSII_RMTP_ULAEINF','${DFILI}/${PCH}ESFD3650_I17G_RAD_CKI_INI_GTSII_RMTP_ULAEINF.dat','O','')
insert into BEST..TI17TRAPERMFIL values ('I17G_RAD_CKI_INI',  'ESF_GTSII_CASHFLOW','${DFILP}/${PCH}ESFD3650_I17G_RAD_CKI_INI_GTSII_CASHFLOW_${PARM_ICLODAT_D}.dat','O','')

insert into BEST..TI17TRAPERMFIL values ('I17G_RAD_CKI_INI',  'ESF_IADVPERICASE_P','${DFILP}/empty.dat','I','')
insert into BEST..TI17TRAPERMFIL values ('I17G_RAD_CKI_INI',  'ESF_IRDPERICASE_NP','${DFILP}/empty.dat','I','')
insert into BEST..TI17TRAPERMFIL values ('I17G_RAD_CKI_INI',  'EPO_IRDPERICASE0','${DFILP}/${PCH}ESFT0000_I17G_TRN_ALL_INI_IRDPERICASE0_PNP.dat','I','')


print '------>>>> End ESFD3650 : I17G_RAD_CKI_INI  ' 

GO

-----------------------------------------------------------------------------------
print '------>>>> Transition CHAIN ESFD2550 : I17G_FUT_RPO_INI   ' 
go
DELETE FROM  BEST..TI17TRAPERMFIL where IDF_CT IN ('I17G_FUT_RPO_INI')
insert into BEST..TI17TRAPERMFIL values ('I17G_FUT_RPO_INI',  'EPO_IADVPERICASE','${DFILP}/${PCH}ESFT0000_I17G_TRN_ALL_INI_IADPERICASE_${PARM_ICLODAT_D}.dat','I','')

print '------>>>> End Transition CHAIN ESFD2550 : I17G_FUT_RPO_INI   ' 
GO
-----------------------------------------------------------------------------------


----------------------------------------------------------------------------------------------------------
--
-- CHAIN ESFD2570 : I17G_FUT_RNP_INI
--
----------------------------------------------------------------------------------------------------------
print '------>>>>  START ESFD2570 SET UP  ' 

DELETE FROM  BEST..TI17TRAPERMFIL where IDF_CT IN ('I17G_FUT_RNP_INI')

INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_FUT_RNP_INI', 'EPO_FTECLEDR', '${DFILP}/empty.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_FUT_RNP_INI', 'EPO_FTECLEDRCO', '${DFILP}/empty.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_FUT_RNP_INI', 'EPO_FTECLEDRSO', '${DFILP}/empty.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_FUT_RNP_INI', 'EST_FTRSLNK', '${DFILP}/${PCH}ESPT0000_FTRSLNK.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_FUT_RNP_INI', 'EPO_FBOPRSLNK', '${DFILP}/${PCH}ESPT0000_FBOPRSLNK.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_FUT_RNP_INI', 'EPO_FCURQUOT', '${DFILP}/${PCH}ESPT0000_FCURQUOT.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_FUT_RNP_INI', 'EPO_FPLACEMT22', '${DFILI}/${PCH}ESPD0060_FPLACEMT22.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_FUT_RNP_INI', 'EPO_IRDPERICASE0', '${DFILP}/${PCH}ESFT0000_I17G_TRN_ALL_INI_IRDPERICASE_NP.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_FUT_RNP_INI', 'EPO_RETITDPRM_UPR_ACT', '${DFILP}/empty.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_FUT_RNP_INI', 'EPO_DLDGTAR_E', '${DFILP}/${PCH}ESFD2570_DLDGTARSII${TYPEINV0}_E.dat', 'O', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_FUT_RNP_INI', 'EPO_DLDGTR_E', '${DFILP}/${PCH}ESFD2570_DLDGTRSII${TYPEINV0}_E.dat', 'O', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_FUT_RNP_INI', 'EPO_DLDGTRCO', '${DFILP}/${PCH}ESFD2570_DLDGTRSIICO.dat', 'O', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_FUT_RNP_INI', 'EPO_DLDGTRSO', '${DFILP}/${PCH}ESFD2570_DLDGTRSIISO.dat', 'O', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_FUT_RNP_INI', 'EPO_FUTURE_RETRO_EBS', '${DFILP}/${PCH}ESFD2570_FUTURE_RETRO_EBS_INI.dat', 'O', ' ' )

print '------>>>> End ESFD2570 : I17G_FUT_RNP_INI  ' 
go


print '------>>>> 82718 : JYP : ESFD2220 FUTURES Assumed Transition  ' 
DELETE FROM  BEST..TI17TRAPERMFIL where IDF_CT IN ('I17G_FUT_ALL_INI')
INSERT INTO BEST..TI17TRAPERMFIL (IDF_CT,PERMFIL_CT,PATHPATTRN_LL,IO,PERM_LL) VALUES ('I17G_FUT_ALL_INI', 'EST_FSEGEST_SOLVENCY', '${DFILP}/${PCH}ESFT0000_I17G_TRN_ALL_INI_FSEGEST_TRN_${PARM_ICLODAT_D}.dat','I','' )
INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_FUT_ALL_INI', 'EST_IADPERICASE', '${DFILP}/${PCH}ESFT0000_I17G_TRN_ALL_INI_IADPERICASE_${PARM_ICLODAT_D}.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_FUT_ALL_INI', 'EST_FCTRGRO', '${DFILP}/${PCH}ESFT0000_I17G_TRN_ALL_INI_FCTRGRO.dat', 'I', ' ' )

print '------>>>> End 82718 : JYP : ESFD2220 FUTURES Assumed Transition  ' 
GO
---------------------------------------------------------------



----------------------------------------------------------------------------------------------------------
--
-- CHAIN ESFD3620 : I17G_DSC_LKI_INI, I17G_RAD_LKI_INI
--
----------------------------------------------------------------------------------------------------------
print '------>>>>  START ESFD3620 SET UP  ' 

DELETE FROM  BEST..TI17TRAPERMFIL where IDF_CT IN ('I17G_DSC_LKI_INI', 'I17G_RAD_LKI_INI')

INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_DSC_LKI_INI', 'EPO_FCURSII', '${DFILP}/${PCH}ESPT0000_FCURSII.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_DSC_LKI_INI', 'ESF_FPRSMAP_TXT', '${DFILP}/${PCH}ESFD0060_I17G____FPRSMAP_TXT_${PARM_ICLODAT_D}.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_DSC_LKI_INI', 'ESF_FSEGPATTERNDSCf17', '${DFILP}/${PCH}ESFD1130_FSEGPATTERNDSCf17_${PARM_ICLODAT_D}.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_DSC_LKI_INI', 'ESF_GTSII_GLOBAL_CASHFLOW', '${DFILP}/${PCH}ESFD3630_I17G_IEX_ALL_INI_GTSII_GLOBAL_CASHFLOW_${PARM_ICLODAT_D}.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_DSC_LKI_INI', 'ESF_TRERETFACCTR', '${DFILP}/${PCH}ESFT0000_I17G_TRN_ALL_INI_FRERETFACCTR_TRN.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_DSC_LKI_INI', 'ESF_GTSII_ESCOMPTE', '${DFILP}/${PCH}ESFD3620_I17G_DSC_LKI_INI_GTSII_ESCOMPTE_${PARM_ICLODAT_D}.dat', 'O', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_DSC_LKI_INI', 'ESF_GTSII_ESCOMPTE_RMNTP', '${DFILP}/${PCH}ESFD3620_I17G_DSC_LKI_INI_GTSII_ESCOMPTE_RMNTP.dat', 'O', ' ' )

print '------>>>> End ESFD3620 : I17G_DSC_LKI_INI  ' 
go

INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_RAD_LKI_INI', 'EPO_FCURSII', '${DFILP}/${PCH}ESPT0000_FCURSII.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_RAD_LKI_INI', 'ESF_FPRSMAP_TXT', '${DFILP}/${PCH}ESFD0060_I17G____FPRSMAP_TXT_${PARM_ICLODAT_D}.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_RAD_LKI_INI', 'ESF_FSEGPATTERNDSCf17', '${DFILP}/${PCH}ESFD1130_FSEGPATTERNDSCf17_${PARM_ICLODAT_D}.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_RAD_LKI_INI', 'ESF_GTSII_GLOBAL_CASHFLOW', '${DFILP}/${PCH}ESFD3650_I17G_RAD_CKI_INI_GTSII_CASHFLOW_${PARM_ICLODAT_D}.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_RAD_LKI_INI', 'ESF_TRERETFACCTR', '${DFILP}/${PCH}ESFT0000_I17G_TRN_ALL_INI_FRERETFACCTR_TRN.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_RAD_LKI_INI', 'ESF_GTSII_ESCOMPTE', '${DFILP}/${PCH}ESFD3620_I17G_RAD_LKI_INI_GTSII_ESCOMPTE_${PARM_ICLODAT_D}.dat', 'O', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_RAD_LKI_INI', 'ESF_GTSII_ESCOMPTE_RMNTP', '${DFILP}/${PCH}ESFD3620_I17G_RAD_LKI_INI_GTSII_ESCOMPTE_RMNTP.dat', 'O', ' ' )

print '------>>>> End ESFD3620 :  I17G_RAD_LKI_INI  ' 
go


----------------------------------------------------------------------------------------------------------
--
-- CHAIN ESFD3610 : I17G_CSF_ALL_INI
--
----------------------------------------------------------------------------------------------------------
print '------>>>>  Lahcen request : START ESFD3610 SET UP  ' 
GO
DELETE FROM  BEST..TI17TRAPERMFIL where IDF_CT IN ('I17G_CSF_ALL_INI')

INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_CSF_ALL_INI', 'DLCUMGTAA', '${DFILP}/empty.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_CSF_ALL_INI', 'EPO_DLDGTAR_E', '${DFILP}/empty.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_CSF_ALL_INI', 'EST_DLREGTAR', '${DFILP}/empty.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_CSF_ALL_INI', 'EST_DLREMAJGTAR', '${DFILP}/empty.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_CSF_ALL_INI', 'EST_DLRGTAA', '${DFILP}/empty.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_CSF_ALL_INI', 'EST_DLSGTAA', '${DFILP}/empty.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_CSF_ALL_INI', 'EST_DLSGTAR', '${DFILP}/empty.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_CSF_ALL_INI', 'EST_FLIBEL2', '${DFILP}/empty.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_CSF_ALL_INI', 'EST_FTECLEDASII', '${DFILP}/empty.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_CSF_ALL_INI', 'EST_CURGTA', '${DFILP}/empty.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_CSF_ALL_INI', 'EST_FWHGTA', '${DFILP}/empty.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_CSF_ALL_INI', 'EST_FWHGTR', '${DFILP}/empty.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_CSF_ALL_INI', 'EST_IRDPERICASE0', '${DFILP}/${PCH}ESPT0000_IRDPERICASE0.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_CSF_ALL_INI', 'EST_FULAERAT', '${DFILP}/${PCH}ESPD0060_FULAERAT${TYPEINV0}_${PARM_ICLODAT_D}.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_CSF_ALL_INI', 'EST_FTRSLNK', '${DFILP}/${PCH}ESPT0000_FTRSLNK.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_CSF_ALL_INI', 'EST_FPRSMAP', '${DFILP}/${PCH}ESPT0000_FPRSMAP_${PARM_ICLODAT_D}.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_CSF_ALL_INI', 'EST_FPRSMAP_TXT', '${DFILP}/${PCH}ESPT0000_FPRSMAP_TXT_${PARM_ICLODAT_D}.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_CSF_ALL_INI', 'EST_FBOPRSLNK', '${DFILP}/${PCH}ESPT0000_FBOPRSLNK.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_CSF_ALL_INI', 'EST_FBOPRSLNK_TXT', '${DFILP}/${PCH}ESPT0000_FBOPRSLNK_TXT_${PARM_ICLODAT_D}.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_CSF_ALL_INI', 'EST_FTRSLNK_TXT', '${DFILP}/${PCH}ESPT0000_FTRSLNK_TXT_${PARM_ICLODAT_D}.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_CSF_ALL_INI', 'EST_FCURQUOT_TXT', '${DFILP}/${PCH}ESPT0000_FCURQUOT_TXT_${PARM_ICLODAT_D}.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_CSF_ALL_INI', 'EST_FCURSII', '${DFILP}/${PCH}ESPT0000_FCURSII.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_CSF_ALL_INI', 'EST_FCTRFWH', '${DFILP}/${PCH}ESPD0060_FCTRFWH.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_CSF_ALL_INI', 'EST_FCTRGRO', '${DFILP}/${PCH}ESPT0000_FCTRGRO.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_CSF_ALL_INI', 'EST_FSEGPATTERN_BDT', '${DFILP}/${PCH}ESPD0060_FSEGPATTERN_BDT.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_CSF_ALL_INI', 'EST_FSEGPATTERN_INF', '${DFILP}/${PCH}ESPD0060_FSEGPATTERN_INF.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_CSF_ALL_INI', 'EST_FDETTRS', '${DFILP}/${PCH}ESPT0000_FDETTRS.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_CSF_ALL_INI', 'EST_FSEGPATTERNFWH', '${DFILP}/${PCH}ESPD0060_FSEGPATTERNFWH.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_CSF_ALL_INI', 'EST_FPLATXCUMALL', '${DFILP}/${PCH}ESPT0000_FPLATXCUMALL.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_CSF_ALL_INI', 'EST_FRATINGRTO', '${DFILP}/${PCH}ESPT0000_FRATINGRTO.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_CSF_ALL_INI', 'EST_FSEGPATTERN_CSF', '${DFILP}/${PCH}ESFT0000_I17G_TRN_ALL_INI_FSEGPATTERN_CSF_${PARM_ICLODAT_D}.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_CSF_ALL_INI', 'EST_FSEGPATTERN_ICR', '${DFILP}/${PCH}ESFT0000_I17G_TRN_ALL_INI_FSEGPATTERN_ICR_${PARM_ICLODAT_D}.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_CSF_ALL_INI', 'EST_DLDGTAA', '${DFILP}/${PCH}ESFD2220_I17G_FUT_ALL_INI_DLDGTAASII${TYPEINV0}.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_CSF_ALL_INI', 'ESF_DLDGTR_NP', '${DFILP}/${PCH}ESFD2570_DLDGTRSII${TYPEINV0}.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_CSF_ALL_INI', 'ESF_DLDGTR_P', '${DFILP}/${PCH}ESFD2550_DLREGTARSIISO.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_CSF_ALL_INI', 'EST_IADPERICASE', '${DFILP}/${PCH}ESFT0000_I17G_TRN_ALL_INI_IADPERICASE_${PARM_ICLODAT_D}.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_CSF_ALL_INI', 'EST_IADPERICASE_STD', '${DFILP}/${PCH}ESFT0000_I17G_TRN_ALL_INI_IADPERICASE_${PARM_ICLODAT_D}.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_CSF_ALL_INI', 'ESF_IADVPERICASE_P', '${DFILP}/${PCH}ESEH1100_IADVPERICASE_P_INI.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_CSF_ALL_INI', 'ESF_IRDPERICASE_NP', '${DFILP}/${PCH}ESFT0000_I17G_TRN_ALL_INI_IRDPERICASE.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_CSF_ALL_INI', 'EST_FTECLEDSII', '${DFILI}/${PCH}ESFD3610_I17G_CSF_ALL_INI_FTECLEDSII.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_CSF_ALL_INI', 'EST_DLDSIIGTAA', '${DFILI}/${PCH}ESFD3610_I17G_CSF_ALL_INI_DLDSIIGTAA.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_CSF_ALL_INI', 'EST_DLDSIIGTAR', '${DFILI}/${PCH}ESFD3610_I17G_CSF_ALL_INI_DLDSIIGTAR.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_CSF_ALL_INI', 'EST_DLDSIIGTR', '${DFILI}/${PCH}ESFD3610_I17G_CSF_ALL_INI_DLDSIIGTR.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_CSF_ALL_INI', 'EST_DLCUMGTAAR', '${DFILI}/${PCH}ESFD3610_I17G_CSF_ALL_INI_DLCUMGTAAR.dat', 'O', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_CSF_ALL_INI', 'EST_DLCUMGTAAR_IBNR_FUTCLAIMS', '${DFILP}/${PCH}ESFD3610_I17G_CSF_ALL_INI_DLCUMGTAAR_IBNR_FUTCLAIMS.dat', 'O', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_CSF_ALL_INI', 'EST_GTSII_CASHFLOW', '${DFILP}/${PCH}ESFD3610_I17G_CSF_ALL_INI_GTSII_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat', 'O', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_CSF_ALL_INI', 'EST_GTSII_CLACC_CASHFLOW', '${DFILP}/${ENV_PREFIX}_ESFD3610_I17G_CSF_ALL_INI_GTSII_CLACC_CASHFLOW.dat', 'O', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_CSF_ALL_INI', 'EST_GTSII_GLOBAL_CASHFLOW', '${DFILP}/${PCH}ESFD3610_I17G_CSF_ALL_INI_GTSII_GLOBAL_CASHFLOW${TYPEINV0}_${PARM_ICLODAT_D}.dat', 'O', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_CSF_ALL_INI', 'EST_GTSII_REMAINTOPAY_ULAE', '${DFILP}/${PCH}ESFD3610_I17G_CSF_ALL_INI_GTSII_RMTP_ULAE_SII${TYPEINV0}.dat', 'O', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_CSF_ALL_INI', 'EST_GTSII_REMAINTOPAY_ULAEINF', '${DFILP}/${PCH}ESFD3610_I17G_CSF_ALL_INI_GTSII_RMTP_ULAEINF_SII${TYPEINV0}.dat', 'O', ' ' )


print '------>>>>  End Lahcen request : START ESFD3610 SET UP  ' 
go
----------------------------------------------------------------------------------------------------------



delete from BEST..TI17TRAPERMFIL where idf_ct = 'I17G_IEX_ALL_INI' and permfil_ct = 'PARM_IS_TRN'
delete from BEST..TI17TRAPERMFIL where idf_ct = 'I17G_IEX_ALL_INI' and permfil_ct = 'EST_IADPERICASE_STD'





-- INI && TRANSITION : I17G_IEX_ALL_INI
delete from BEST..TI17TRAPERMFIL where idf_ct = 'I17G_IEX_ALL_INI' and permfil_ct = 'ESF_GTESTCUMUL_ACCRET_TRN'
delete from BEST..TI17TRAPERMFIL where idf_ct = 'I17G_IEX_ALL_INI' and permfil_ct = 'ESF_GTESTCUMUL_ACCRET'
delete from BEST..TI17TRAPERMFIL where idf_ct = 'I17G_IEX_ALL_INI' and permfil_ct = 'EPO_IADPERICASE_TRN'
delete from BEST..TI17TRAPERMFIL where idf_ct = 'I17G_IEX_ALL_INI' and permfil_ct = 'ESF_GTESTCUMUL_ACCRET_NOT_TRN'
delete from BEST..TI17TRAPERMFIL where idf_ct = 'I17G_IEX_ALL_INI' and permfil_ct = 'ESF_GTESTCUMUL_RET_TRN'
delete from BEST..TI17TRAPERMFIL where idf_ct = 'I17G_IEX_ALL_INI' and permfil_ct = 'ESF_GTESTCUMUL_RET'
delete from BEST..TI17TRAPERMFIL where idf_ct = 'I17G_IEX_ALL_INI' and permfil_ct = 'EPO_IRDPERICASE0_TRN'
delete from BEST..TI17TRAPERMFIL where idf_ct = 'I17G_IEX_ALL_INI' and permfil_ct = 'ESF_GTESTCUMUL_RET_NOT_TRN'


insert into BEST..TI17TRAPERMFIL values ('I17G_IEX_ALL_INI', 'ESF_GTESTCUMUL_ACCRET_TRN','${DFILI}/${ENV_PREFIX}_ESFD3671_${IDF_CT}_GTESTCUMUL_ACCRET_TRN.dat','O',' ')
insert into BEST..TI17TRAPERMFIL values ('I17G_IEX_ALL_INI', 'ESF_GTESTCUMUL_ACCRET_NOT_TRN','${DFILI}/${ENV_PREFIX}_ESFD3671_${IDF_CT}_GTESTCUMUL_ACCRET_NOT_TRN.dat','O',' ')
insert into BEST..TI17TRAPERMFIL values ('I17G_IEX_ALL_INI', 'ESF_GTESTCUMUL_RET_TRN','${DFILI}/${ENV_PREFIX}_ESFD3672_${IDF_CT}_GTESTCUMUL_RET_TRN.dat','O',' ')
insert into BEST..TI17TRAPERMFIL values ('I17G_IEX_ALL_INI', 'ESF_GTESTCUMUL_RET_NOT_TRN','${DFILI}/${ENV_PREFIX}_ESFD3672_${IDF_CT}_GTESTCUMUL_RET_NOT_TRN.dat','O',' ')

--Mapping Transition :
insert into BEST..TI17TRAPERMFIL values ('I17G_IEX_ALL_INI', 'ESF_GTESTCUMUL_ACCRET','${DFILI}/${ENV_PREFIX}_ESFD3671_${IDF_CT}_GTESTCUMUL_ACCRET_TRN.dat','O',' ')
insert into BEST..TI17TRAPERMFIL values ('I17G_IEX_ALL_INI', 'EPO_IADPERICASE_TRN','${DFILP}/${ENV_PREFIX}_ESFT0000_I17G_TRN_ALL_INI_IADPERICASE_${PARM_ICLODAT_D}.dat','I',' ') 
insert into BEST..TI17TRAPERMFIL values ('I17G_IEX_ALL_INI', 'ESF_GTESTCUMUL_RET','${DFILI}/${ENV_PREFIX}_ESFD3672_${IDF_CT}_GTESTCUMUL_RET_TRN.dat','O',' ')
insert into BEST..TI17TRAPERMFIL values ('I17G_IEX_ALL_INI', 'EPO_IRDPERICASE0_TRN','${DFILP}/${ENV_PREFIX}_ESFT0000_I17G_TRN_ALL_INI_IRDPERICASE_NP.dat','I',' ') 

INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_IEX_ALL_INI', 'PARM_IS_TRN', 'YES', ' ', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_IEX_ALL_INI', 'EST_IADPERICASE_STD', '${DFILP}/empty.dat', 'I', ' ' )

UPDATE BEST..TI17TRAPERMFIL SET PATHPATTRN_LL = '${DFILP}/${PCH}ESFT0000_I17G_TRN_ALL_INI_IRDPERICASE_NP.dat' 
WHERE IDF_CT = 'I17G_IEX_ALL_INI' AND PERMFIL_CT = 'EPO_IRDPERICASE0'



print '------>>>> End Lahcen request : spira 84240 ' 
GO

UPDATE BEST..TI17TRAPERMFIL SET PATHPATTRN_LL = '${DFILP}/${PCH}ESFT0000_I17G_TRN_ALL_INI_IRDPERICASE_NP.dat'
WHERE idf_ct = 'I17G_CSF_ALL_INI' AND PERMFIL_CT = 'ESF_IRDPERICASE_NP'

delete from BEST..TI17TRAPERMFIL where idf_ct = 'I17G_CSF_ALL_INI' and permfil_ct = 'PARM_IS_TRN'

INSERT INTO BEST..TI17TRAPERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) VALUES ( 'I17G_CSF_ALL_INI', 'PARM_IS_TRN', 'YES', ' ', ' ' )

print '------>>>> End Lahcen request : spira 84240 ' 
GO
----------------------------------------------------------------------------------------------------------


print '------>>>> Lahcen request : spira 88830 : NDIC input amount' 
GO

delete from BEST..TI17TRAPERMFIL where idf_ct in ('I17G_IEX_ALL_INI') and permfil_ct = 'EST_CSF_NDIC_AMOUNT'  

--TRANSITION treatment
insert into BEST..TI17TRAPERMFIL values ('I17G_IEX_ALL_INI', 'EST_CSF_NDIC_AMOUNT', '${DFILP}/empty.dat','I',' ')


print '------>>>> End Lahcen request : spira 88830 : NDIC input amount' 
GO
----------------------------------------------------------------------------------------------------------

-----------------------------------------------------------------------------------
--
-- CHAIN ESFD3690 : I17G_IRV_ALL_STD
--
-----------------------------------------------------------------------------------
print '------>>>> Lahcen request : 85404 : ESFD3690 I17G_IRV_ALL_STD ' 

DELETE FROM  BEST..TI17TRAPERMFIL where IDF_CT IN ('I17G_IRV_ALL_STD')

insert into BEST..TI17TRAPERMFIL values ('I17G_IRV_ALL_STD',  'EST_FCURQUOT','${DFILP}/${PCH}ESCJ0060_FCURQUOT.dat','I','')
insert into BEST..TI17TRAPERMFIL values ('I17G_IRV_ALL_STD',  'EST_FBOPRSLNK_TXT','${DFILP}/${PCH}ESPT0000_FBOPRSLNK_TXT_${PARM_ICLODAT_D}.dat','I','')
insert into BEST..TI17TRAPERMFIL values ('I17G_IRV_ALL_STD',  'EST_IRDPERICASE0','${DFILP}/${PCH}ESPT0000_IRDPERICASE0.dat','I','')
insert into BEST..TI17TRAPERMFIL values ('I17G_IRV_ALL_STD',  'EST_IADPERICASE','${DFILP}/${PCH}ESPT0000_IADPERICASE_${PARM_ICLODAT_D}.dat','I','')
insert into BEST..TI17TRAPERMFIL values ('I17G_IRV_ALL_STD',  'ESF_GTSII_CASHFLOW_INI','${DFILP}/${PCH}ESFD3610_I17G_CSF_ALL_INI_GTSII_GLOBAL_CASHFLOW${TYPEINV0}_${PARM_ICLODAT_D}.dat','I','')
insert into BEST..TI17TRAPERMFIL values ('I17G_IRV_ALL_STD',  'EPO_GTSII_GLOBAL_CASHFLOW','${DFILP}/${PCH}ESPD3610_GTSII_GLOBAL_CASHFLOW${TYPEINV0}_${PARM_ICLODAT_D}.dat','I','')
insert into BEST..TI17TRAPERMFIL values ('I17G_IRV_ALL_STD',  'EPO_GTSII_GLOBAL_CASHFLOW_PREV','${DFILP}/${PCH}ESPD3610_GTSII_GLOBAL_CASHFLOW${TYPEINV0}_${PARM_PREV_ICLODAT_D}.dat','I','')
insert into BEST..TI17TRAPERMFIL values ('I17G_IRV_ALL_STD',  'ESF_GTSII_DSC_LKI_ESCOMPTE','${DFILP}/${PCH}ESFD3620_I17G_DSC_LKI_STD_GTSII_ESCOMPTE_${PARM_ICLODAT_D}.dat','I','')
insert into BEST..TI17TRAPERMFIL values ('I17G_IRV_ALL_STD',  'ESF_GTSII_RAD_LKI_ESCOMPTE','${DFILP}/${PCH}ESFD3620_I17G_RAD_LKI_STD_GTSII_ESCOMPTE_${PARM_ICLODAT_D}.dat','I','')
insert into BEST..TI17TRAPERMFIL values ('I17G_IRV_ALL_STD',  'ESF_GTSII_DSC_FWD_ESCOMPTE','${DFILP}/${PCH}ESFD3660_I17G_UWD_ALL_STD_GTSII_ESCOMPTE_FWD_${PARM_ICLODAT_D}.dat','I','')
insert into BEST..TI17TRAPERMFIL values ('I17G_IRV_ALL_STD',  'EPO_FTECLEDA','${DFILP}/${PCH}ESPD3800_FTECLEDA${TYPEINV0}_EBS.dat','I','')
insert into BEST..TI17TRAPERMFIL values ('I17G_IRV_ALL_STD',  'EPO_FTECLEDR','${DFILP}/${PCH}ESPD3800_FTECLEDR${TYPEINV0}.dat','I','')
insert into BEST..TI17TRAPERMFIL values ('I17G_IRV_ALL_STD',  'EST_DLCUMGTAAR_ITD','${DFILP}/${PCH}ESFD4020_DLCUMGTAAR_ITD_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
insert into BEST..TI17TRAPERMFIL values ('I17G_IRV_ALL_STD',  'ESF_UPR','${DFILP}/${PCH}ESFD3690_I17G_IRV_ALL_STD_UPR_${PARM_ICLODAT_D}.dat','O','')
insert into BEST..TI17TRAPERMFIL values ('I17G_IRV_ALL_STD',  'ESF_RETRO_UPR','${DFILP}/${PCH}ESFD3690_I17G_IRV_ALL_STD_RETRO_UPR_${PARM_ICLODAT_D}.dat','O','')
insert into BEST..TI17TRAPERMFIL values ('I17G_IRV_ALL_STD',  'ESF_GTSII_IFRS17_CSM','${DFILP}/${PCH}ESFD3690_I17G_IRV_ALL_STD_GTSII_IFRS17_CSM${TYPEINV0}_${PARM_ICLODAT_D}.dat','O','')
insert into BEST..TI17TRAPERMFIL values ('I17G_IRV_ALL_STD',  'ESF_GTSII_IFRS17_REVENUE','${DFILP}/${PCH}ESFD3690_I17G_IRV_ALL_STD_GTSII_IFRS17_REVENUE${TYPEINV0}_${PARM_ICLODAT_D}.dat','O','')
insert into BEST..TI17TRAPERMFIL values ('I17G_IRV_ALL_STD',  'ESF_GTSII_DAC_LKI','${DFILP}/${PCH}ESFD3690_I17G_IRV_ALL_STD_DAC_LKI_CASHFLOW_${PARM_ICLODAT_D}.dat','O','')
insert into BEST..TI17TRAPERMFIL values ('I17G_IRV_ALL_STD',  'ESF_GTSII_DAC_FWD','${DFILP}/${PCH}ESFD3690_I17G_IRV_ALL_STD_DAC_FWD_CASHFLOW_${PARM_ICLODAT_D}.dat','O','')
insert into BEST..TI17TRAPERMFIL values ('I17G_IRV_ALL_STD',  'PARM_IS_TRN', 'YES', ' ', ' ' )
insert into BEST..TI17TRAPERMFIL values ('I17G_IRV_ALL_STD',  'ESF_GTSII_DSC_BDT_FWD', '${DFILP}/${PCH}ESFD3690_I17G_IRV_ALL_STD_GTSII_ESCOMPTE_FWD_${PARM_ICLODAT_D}.dat', 'O', ' ' )
insert into BEST..TI17TRAPERMFIL values ('I17G_IRV_ALL_STD',  'ESF_GTSII_DSC_BDT_LKI', '${DFILP}/${PCH}ESFD3690_I17G_IRV_ALL_STD_GTSII_ESCOMPTE_${PARM_ICLODAT_D}.dat', 'O', ' ' )
insert into BEST..TI17TRAPERMFIL VALUES ('I17G_IRV_ALL_STD',  'ESF_TRERETFACCTR', '${DFILP}/${PCH}ESFD1130_TRERETFACCTR_${NORME_CF}_${PARM_ICLODAT_D}.dat', 'I', ' ' )
insert into BEST..TI17TRAPERMFIL VALUES ('I17G_IRV_ALL_STD',  'ESF_GTSII_DAC_LKI_PREV', '${DFILP}/${PCH}ESFD3690_I17G_IRV_ALL_STD_DAC_LKI_CASHFLOW_${PARM_PREV_ICLODAT_D}.dat', 'I', ' ' )

 
print '------>>>> End Lahcen request : 85404 : ESFD3690 I17G_IRV_ALL_STD ' 
go
----------------------------------------------------------------------------------------------------------

-----------------------------------------------------------------------------------
--
-- CHAIN ESFD3720 : I17G_CSM_CRE_INI
--
-----------------------------------------------------------------------------------
print '------>>>> AGD request : 84457 : ESFD3720 I17G_CSM_CRE_INI ' 

DELETE FROM  BEST..TI17TRAPERMFIL where IDF_CT IN ('I17G_CSM_CRE_INI')

insert into BEST..TI17TRAPERMFIL values ('I17G_CSM_CRE_INI',  'ESF_IADPERICASE_INI','${DFILI}/${PCH}ESEH1100_IADPERICASE_INI.dat','I','')
insert into BEST..TI17TRAPERMFIL values ('I17G_CSM_CRE_INI',  'ESF_FRERETFACCTR_INI','${DFILP}/${PCH}ESFT0000_I17G_TRN_ALL_INI_FRERETFACCTR_TRN.dat','I','')
insert into BEST..TI17TRAPERMFIL values ('I17G_CSM_CRE_INI',  'EPO_FCURQUOT_TXT','${DFILP}/${PCH}ESPT0000_FCURQUOT_TXT_${PARM_ICLODAT_D}.dat','I','')
insert into BEST..TI17TRAPERMFIL values ('I17G_CSM_CRE_INI',  'ESF_FUOASII','${DFILI}/${ENV_PREFIX}_ESFD0060_I17G___TUOASII_${PARM_ICLODAT_D}.dat','I','')
insert into BEST..TI17TRAPERMFIL values ('I17G_CSM_CRE_INI',  'ESF_GTSII_CSM','${DFILP}/${PCH}ESFD3710_I17G_CSM_CSU_INI_GTSII_${PARM_ICLODAT_D}.dat','I','')
insert into BEST..TI17TRAPERMFIL values ('I17G_CSM_CRE_INI',  'ESF_GTSII_GLOBAL_CASHFLOW','${DFILP}/${PCH}ESFD3630_I17G_IEX_ALL_INI_GTSII_GLOBAL_CASHFLOW_${PARM_ICLODAT_D}.dat','I','')
insert into BEST..TI17TRAPERMFIL values ('I17G_CSM_CRE_INI',  'ESF_FRETIFRS','${DFILP}/${ENV_PREFIX}_ESFD3720_I17G_CSM_CRE_INI_FRETIFRS.dat','O','')
insert into BEST..TI17TRAPERMFIL values ('I17G_CSM_CRE_INI',  'ESF_FSECIFRS','${DFILP}/${ENV_PREFIX}_ESFD3720_I17G_CSM_CRE_INI_FSECIFRS.dat','O','')
insert into BEST..TI17TRAPERMFIL values ('I17G_CSM_CRE_INI',  'ESF_FSEGPROF','${DFILP}/${PCH}ESFD3720_I17G_CSM_CRE_INI_FSEGPROF_${PARM_ICLODAT_D}.dat','O','')
insert into BEST..TI17TRAPERMFIL values ('I17G_CSM_CRE_INI',  'PARM_IS_TRN', 'YES', ' ', ' ' )
 
print '------>>>> End AGD request : 84457 : ESFD3720 I17G_CSM_CRE_INI ' 
go
----------------------------------------------------------------------------------------------------------

-----------------------------------------------------------------------------------
--
-- CHAIN ESFD3750 : I17G_CSM_ALL_STD
--
-----------------------------------------------------------------------------------
print '------>>>> AGD request : 84457 : ESFD3750 I17G_CSM_ALL_STD ' 

DELETE FROM  BEST..TI17TRAPERMFIL where IDF_CT IN ('I17G_CSM_ALL_STD')

insert into BEST..TI17TRAPERMFIL values ('I17G_CSM_ALL_STD',  'ESF_TRANSITION_FILE','${DFILP}/${PCH}ESFT0020_I17G_OMG_ALL_TRA_TRANSITION_FILE.dat','I','')
insert into BEST..TI17TRAPERMFIL values ('I17G_CSM_ALL_STD',  'EPO_FCURSII','${DFILP}/${ENV_PREFIX}_ESPT0000_FCURSII.dat','I','')
insert into BEST..TI17TRAPERMFIL values ('I17G_CSM_ALL_STD',  'ESF_TRERETFACCTR','${DFILP}/${PCH}ESFD1130_TRERETFACCTR_${PARM_ICLODAT_D}.dat','I','')
insert into BEST..TI17TRAPERMFIL values ('I17G_CSM_ALL_STD',  'EST_FSEGPATTERN_DSC_f17','${DFILP}/${PCH}ESFD1130_FSEGPATTERNDSCf17_${PARM_ICLODAT_D}.dat','I','')
insert into BEST..TI17TRAPERMFIL values ('I17G_CSM_ALL_STD',  'EST_IADPERICASE_STD','${DFILI}/${ENV_PREFIX}_ESEH1100_IADPERICASE_STD.dat','I','')
insert into BEST..TI17TRAPERMFIL values ('I17G_CSM_ALL_STD',  'ESF_GTSII_CSM','${DFILP}/${PCH}ESFD3710_I17G_CSM_CSU_INI_GTSII_${PARM_ICLODAT_D}.dat','I','')
insert into BEST..TI17TRAPERMFIL values ('I17G_CSM_ALL_STD',  'ESF_FSEGPROF_INI','${DFILP}/${ENV_PREFIX}_ESFD3720_I17G_CSM_CRE_INI_FSEGPROF_${PARM_ICLODAT_D}.dat','I','')
insert into BEST..TI17TRAPERMFIL values ('I17G_CSM_ALL_STD',  'ESF_GTSII_ESCOMPTE','${DFILP}/${PCH}ESFD3690_I17G_IRV_ALL_STD_GTSII_ESCOMPTE_${PARM_ICLODAT_D}.dat','I','')
insert into BEST..TI17TRAPERMFIL values ('I17G_CSM_ALL_STD',  'ESF_GTSII_ESCOMPTE_RAD','${DFILP}/${PCH}ESFD3620_I17G_RAD_LKI_STD_GTSII_ESCOMPTE_${PARM_ICLODAT_D}.dat','I','')
insert into BEST..TI17TRAPERMFIL values ('I17G_CSM_ALL_STD',  'ESF_FSEGPROF_STD_PREVIOUS','${DFILP}/${PCH}ESFD3760_I17G_UOA_PRO_STD_FSEGPROF_${PARM_PREV_ICLODAT_D}.dat','I','')
insert into BEST..TI17TRAPERMFIL values ('I17G_CSM_ALL_STD',  'ESF_GTSII_ESCOMPTE_FWD','${DFILP}/${PCH}ESFD3690_I17G_IRV_ALL_STD_GTSII_ESCOMPTE_FWD_${PARM_ICLODAT_D}.dat','I','')
insert into BEST..TI17TRAPERMFIL values ('I17G_CSM_ALL_STD',  'ESF_GTSII_IFRS17_CSM','${DFILP}/${PCH}ESFD3690_I17G_IRV_ALL_STD_GTSII_IFRS17_CSM${TYPEINV0}_${PARM_ICLODAT_D}.dat','I','')
insert into BEST..TI17TRAPERMFIL values ('I17G_CSM_ALL_STD',  'ESF_CSM_LC_AMORT_PATTERN','${DFILP}/${ENV_PREFIX}_ESFD3770_I17G_CSM_AMR_STD_CSM_LC_AMORT_PATTERN_${PARM_ICLODAT_D}.dat','I','')
insert into BEST..TI17TRAPERMFIL values ('I17G_CSM_ALL_STD',  'ESF_GTSII_CSM_CASHFLOW_PREV','${DFILP}/${ENV_PREFIX}_ESFD3760_I17G_UOA_PRO_STD_GTSII_CSM_CASHFLOW_${PARM_PREV_ICLODAT_D}.dat','I','')
insert into BEST..TI17TRAPERMFIL values ('I17G_CSM_ALL_STD',  'ESF_CSM_LC_AMORT_PATTERN_PREV','${DFILP}/${ENV_PREFIX}_ESFD3770_I17G_CSM_AMR_STD_CSM_LC_AMORT_PATTERN_${PARM_PREV_ICLODAT_D}.dat','I','')
insert into BEST..TI17TRAPERMFIL values ('I17G_CSM_ALL_STD',  'ESF_CSM_PROF','${DFILP}/${ENV_PREFIX}_ESFD3750_I17G_CSM_ALL_STD_PROF_BY_CTR_${PARM_ICLODAT_D}.dat','O','')
insert into BEST..TI17TRAPERMFIL values ('I17G_CSM_ALL_STD',  'ESF_GTSII_CSM_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESFD3750_I17G_CSM_ALL_STD_GTSII_CSM_CASHFLOW_${PARM_ICLODAT_D}.dat','O','')
insert into BEST..TI17TRAPERMFIL values ('I17G_CSM_ALL_STD',  'ESF_GTSII_CSM_TMP_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESFD3750_I17G_CSM_ALL_STD_GTSII_CSM_TMP_CASHFLOW_${PARM_ICLODAT_D}.dat','O','')		
insert into BEST..TI17TRAPERMFIL values ('I17G_CSM_ALL_STD',  'PARM_IS_TRN', 'YES', ' ', ' ' )
 
print '------>>>> End AGD request : 84457 : ESFD3750 I17G_CSM_ALL_STD ' 
go
----------------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------------
--
-- CHAIN ESFT0010 : I17G_OMG_CSU_TRA 
--
----------------------------------------------------------------------------------------------------------
print '------>>>>  ESFT0010 I17G_OMG_CSU_TRA ' 

delete 	BEST..TI17TRAPERMFIL where IDF_CT = 'I17G_OMG_CSU_TRA'

insert into BEST..TI17TRAPERMFIL values ('I17G_OMG_CSU_TRA','OMEGA_EXTRACT_TRN','${DFILP}/${ENV_PREFIX}_ESFT0010_I17G_OMG_CSU_TRA_OMEGA_EXTRACT.dat','O',' ')
insert into BEST..TI17TRAPERMFIL values ('I17G_OMG_CSU_TRA',  'PARM_IS_TRN', 'YES', ' ', ' ' )

   
print '------>>>> End ART request : 84457 : ESFT0010 I17G_OMG_CSU_TRA ' 
go
----------------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------------
--
-- CHAIN ESFT0020 : I17G_OMG_ALL_TRA 
--
----------------------------------------------------------------------------------------------------------
print '------>>>>  ESFT0020 I17G_OMG_ALL_TRA ' 

delete 	BEST..TI17TRAPERMFIL where IDF_CT = 'I17G_OMG_ALL_TRA'

insert into BEST..TI17TRAPERMFIL values ('I17G_OMG_ALL_TRA','OMEGA_EXTRACT_TRN','${DFILP}/${ENV_PREFIX}_ESFT0010_I17G_OMG_CSU_TRA_OMEGA_EXTRACT.dat','I','')
insert into BEST..TI17TRAPERMFIL values ('I17G_OMG_ALL_TRA','EPO_FCURSII','${DFILP}/${ENV_PREFIX}_ESPT0000_FCURSII.dat','I','')
insert into BEST..TI17TRAPERMFIL values ('I17G_OMG_ALL_TRA','RA_EGPI_TRN','${DFILP}/${ENV_PREFIX}_ESFT0020_RA_EGPI_TRN.dat','I','')
insert into BEST..TI17TRAPERMFIL values ('I17G_OMG_ALL_TRA','CSM_FACTOR_TRN','${DFILP}/${ENV_PREFIX}_ESFT0020_CSM_FACTOR_TRN.dat','I','')
insert into BEST..TI17TRAPERMFIL values ('I17G_OMG_ALL_TRA','SEG_ACT_TRN','${DFILP}/${ENV_PREFIX}_ESFT0020_SEG_ACT_TRN.dat','I','')
insert into BEST..TI17TRAPERMFIL values ('I17G_OMG_ALL_TRA','RA_RATIO_TRN','${DFILP}/${ENV_PREFIX}_ESFT0020_RA_RATIO_TRN.dat','I','')
insert into BEST..TI17TRAPERMFIL values ('I17G_OMG_ALL_TRA','LOB_N1_TRN','${DFILP}/${ENV_PREFIX}_ESFT0020_LOB_N1_TRN.dat','I','')
insert into BEST..TI17TRAPERMFIL values ('I17G_OMG_ALL_TRA','LOSS_RATIO_TRN','${DFILP}/${ENV_PREFIX}_ESFT0020_LOSS_RATIO_TRN.dat','I','')
insert into BEST..TI17TRAPERMFIL values ('I17G_OMG_ALL_TRA','TRANSITION_FILE','${DFILP}/${ENV_PREFIX}_ESFT0020_I17G_OMG_ALL_TRA_TRANSITION_FILE.dat','O','')
insert into BEST..TI17TRAPERMFIL values ('I17G_OMG_ALL_TRA',  'PARM_IS_TRN', 'YES', ' ', ' ' )

   
print '------>>>> End ART request : 84457 : ESFT0020 I17G_OMG_ALL_TRA ' 
go

----------------------------------------------------------------------------------------------------------
--
-- CHAIN ESFT0030
--
-- [022]
----------------------------------------------------------------------------------------------------------
print '------>>>>  ESFT0030 I17G_OMG_ROC_TRA' 

delete 	BEST..TI17TRAPERMFIL where IDF_CT = 'I17G_OMG_ROC_TRA'
delete  BEST..TI17REQCHN where IDF_CT = 'I17G_OMG_ROC_TRA'
delete  BEST..TI17CHN  where CHAIN_CT="ESFT0030"

insert into BEST..TI17CHN values ("ESFT0030","Data TRANSITION extraction")

delete  BEST..TI17FNC  where IDF_CT in ( 'I17G_OMG_ROC_TRA'  )
insert into BEST..TI17FNC values ("I17G_OMG_ROC_TRA","Get data IFRS 17 GROUP")

insert into BEST..TI17REQCHN values ('I17GMINV',  "ESFT0030","I17G_OMG_ROC_TRA","")
insert into BEST..TI17REQCHN values ('I17GMINVB', "ESFT0030","I17G_OMG_ROC_TRA","")
insert into BEST..TI17REQCHN values ('I17GQINV',  "ESFT0030","I17G_OMG_ROC_TRA","")
insert into BEST..TI17REQCHN values ('I17GQINVB', "ESFT0030","I17G_OMG_ROC_TRA","")
insert into BEST..TI17REQCHN values ('I17GQPOS',  "ESFT0030","I17G_OMG_ROC_TRA","")
insert into BEST..TI17REQCHN values ('I17GQPOSB', "ESFT0030","I17G_OMG_ROC_TRA","")
insert into BEST..TI17REQCHN values ('I17GQPOC',  "ESFT0030","I17G_OMG_ROC_TRA","")
insert into BEST..TI17REQCHN values ('I17GQPOCB', "ESFT0030","I17G_OMG_ROC_TRA","")
insert into BEST..TI17REQCHN values ('I17GYINV',  "ESFT0030","I17G_OMG_ROC_TRA","")
insert into BEST..TI17REQCHN values ('I17GYINVB', "ESFT0030","I17G_OMG_ROC_TRA","")
insert into BEST..TI17REQCHN values ('I17GYPOS',  "ESFT0030","I17G_OMG_ROC_TRA","")
insert into BEST..TI17REQCHN values ('I17GYPOSB', "ESFT0030","I17G_OMG_ROC_TRA","")
insert into BEST..TI17REQCHN values ('I17GYPOC',  "ESFT0030","I17G_OMG_ROC_TRA","")
insert into BEST..TI17REQCHN values ('I17GYPOCB', "ESFT0030","I17G_OMG_ROC_TRA","")


DELETE FROM  BEST..TI17TRAPERMFIL where IDF_CT IN ('I17G_OMG_ROC_TRA')

INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_OMG_ROC_TRA', 'EST_IADPERICASE_I17G_STD', '${DFILP}/${ENV_PREFIX}_ESFT0020_I17G_OMG_ALL_TRA_TRANSITION_FILE.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_OMG_ROC_TRA', 'ESF_IADPERICASE_TRN', '${DFILP}/${ENV_PREFIX}_ESEH1100_IADPERICASE_I17G_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat', 'I', ' ' )
INSERT INTO BEST..TI17TRAPERMFIL VALUES ( 'I17G_OMG_ROC_TRA', 'PARM_IS_TRN', 'YES', ' ', ' ' )

   
print '------>>>> End ESFT0030  ' 
go

