Use BEST
Go

ALTER TABLE BEST..TPATSEGSII
ADD RATEINDEX_CT varchar(32) null
go

IF EXISTS (SELECT * FROM sysindexes WHERE id=OBJECT_ID('dbo.TPATSEGSII') AND name='IPATSEG_00')
BEGIN
    DROP INDEX TPATSEGSII.IPATSEG_00
    IF EXISTS (SELECT * FROM sysindexes WHERE id=OBJECT_ID('dbo.TPATSEGSII') AND name='IPATSEG_00')
        PRINT '<<< FAILED DROPPING INDEX TPATSEGSII.IPATSEG_00 >>>'
    ELSE
        PRINT '<<< DROPPED INDEX TPATSEGSII.IPATSEG_00 >>>'
END
go

CREATE UNIQUE CLUSTERED INDEX IPATSEG_00
    ON dbo.TPATSEGSII(PATCAT_CT,PATTYP_CT,PATTERN_ID,CLODAT_D,PER_CF,SSD_CF,SEG_NF,LOB_CF,CUR_CF,NORME_CF,SEGNAT_CT,ORIPATCAT_CT,ORIPATTYP_CT, RATEINDEX_CT)
LOCAL INDEX IPATSEG_00_245572882
go
IF EXISTS (SELECT * FROM sysindexes WHERE id=OBJECT_ID('dbo.TPATSEGSII') AND name='IPATSEG_00')
    PRINT '<<< CREATED INDEX dbo.TPATSEGSII.IPATSEG_00 >>>'
ELSE
    PRINT '<<< FAILED CREATING INDEX dbo.TPATSEGSII.IPATSEG_00 >>>'
go