USE BEST
go





	
		----------   Reqs of chain   ---------------------
go


-------------------------------
print	"--	Init  ESID0560"
-------------------------------

	
	--  ESID0560: : fonctional id of P&C execution   

	delete BEST..TI17PERMFIL where  IDF_CT = 'ESID0560' and PERMFIL_CT in ('EST_FCES','EST_FCES_NEW','EST_FPLC','EST_FPLCCOM' )
	
	-- input
	insert into BEST..TI17PERMFIL values ('ESID0560',  'EST_FCES','${DFILP}/${ENV_PREFIX}_ESID2500_FCES_${ICLODAT2}.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESID0560',  'EST_FCES_NEW','${DFILP}/${ENV_PREFIX}_ESID2500_FCES_NEW_${ICLODAT2}.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESID0560',  'EST_FPLC','${DFILP}/${ENV_PREFIX}_ESID2500_FPLC_${ICLODAT2}.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESID0560',  'EST_FPLCCOM','${DFILP}/${ENV_PREFIX}_ESID25000_FPLCCOM_${CLODAT}.dat','O','')
                
go


	
		----------   Reqs of chain   ---------------------
go
-------------------------------
print	"--	Init  ESID2500"
-------------------------------

	
	--  ESID2500: : fonctional id of P&C execution   

	delete BEST..TI17PERMFIL where  IDF_CT = 'ESID2500' and PERMFIL_CT in ('EST_FCES','EST_FCES_NEW','EST_FPLC','EST_DLREMAJGTR_PC','EST_DLREGTR_PC','EST_DLRGTAA_PC')
	
	-- input
		
	insert into BEST..TI17PERMFIL values ('ESID2500',  'EST_FPLC','${DFILP}/${ENV_PREFIX}_ESID2500_FPLC_${ICLODAT}.dat','O','')
    insert into BEST..TI17PERMFIL values ('ESID2500',  'EST_FCES','${DFILP}/${ENV_PREFIX}_ESID2500_FCES_${ICLODAT2}.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESID2500',  'EST_FCES_NEW','${DFILP}/${ENV_PREFIX}_ESID2500_FCES_NEW_${ICLODAT2}.dat','O','')

	insert into BEST..TI17PERMFIL values ('ESID2500',  'EST_DLREMAJGTR_PC','${DFILP}/${ENV_PREFIX}_ESID2500_I4_PC___DLREMAJGTR_${PARM0_ICLODAT_D}.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESID2500',  'EST_DLREGTR_PC','${DFILP}/${ENV_PREFIX}_ESID2500_I4_PC___DLREGTR_${PARM0_ICLODAT_D}.dat','IO','') 
	insert into BEST..TI17PERMFIL values ('ESID2500',  'EST_DLRGTAA_PC','${DFILI}/${ENV_PREFIX}_ESID2050_I4_PC___DLRGTAA_${PARM0_ICLODAT_D}.dat','IO','')

 	         
go


	


-------------------------------
print	"--	Init  ESID2550"
-------------------------------

	
	--  ESID2550_I4_PC___: : fonctional id of P&C execution   

	delete BEST..TI17PERMFIL where  IDF_CT like 'ESID2550_I4_PC__%'
	IF NOT EXISTS (SELECT * FROM BEST..TI17FNC where IDF_CT = 'ESID2550_I4_PC__' ) insert into BEST..TI17FNC values ( 'ESID2550_I4_PC__','')



	-- input
		insert into BEST..TI17PERMFIL values ('ESID2550_I4_PC__',  'EST_GTEP','${DFILP}/${ENV_PREFIX}_ESCJ0060_GTEP.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESID2550_I4_PC__',  'EST_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURQUOT.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESID2550_I4_PC__',  'EST_FCES','${DFILP}/${ENV_PREFIX}_ESID2500_FCES_${PARM0_ICLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESID2550_I4_PC__',  'EST_FPLC','${DFILP}/${ENV_PREFIX}_ESID2500_FPLC_${PARM0_ICLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESID2550_I4_PC__',  'EST_DLSGTR','${DFILI}/${ENV_PREFIX}_ESID1800_DLSGTR_${PARM0_ICLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESID2550_I4_PC__',  'EST_SUBTRS','${DFILI}/${ENV_PREFIX}_ESCJ0060_FSUBTRS_${PARM_CLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESID2550_I4_PC__',  'EST_FDETTRS','${DFILP}/${ENV_PREFIX}_ESCJ0060_FDETTRS_${PARM_CLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESID2550_I4_PC__',  'EST_FRETTRF','${DFILP}/${ENV_PREFIX}_ESCJ0060_FRETTRF_${PARM_CLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESID2550_I4_PC__',  'EST_FTRSLNK','${DFILI}/${ENV_PREFIX}_ESCJ0060_FTRSLNK_${PARM_CLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESID2550_I4_PC__',  'EST_DLDGTAA','${DFILP}/${ENV_PREFIX}_ESID2000_DLDGTAA_${PARM0_ICLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESID2550_I4_PC__',  'EST_DLRPGTR','${DFILP}/${ENV_PREFIX}_ESID2500_DLRPGTR_${PARM0_ICLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESID2550_I4_PC__',  'EST_DLRTGTR','${DFILP}/${ENV_PREFIX}_ESID2500_DLRTGTR_${PARM0_ICLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESID2550_I4_PC__',  'EST_DLVGTR','${DFILP}/empty.dat','I','')                                            
		insert into BEST..TI17PERMFIL values ('ESID2550_I4_PC__',  'EST_FCURCVSN','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURCVSN_${PARM_CLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESID2550_I4_PC__',  'EST_FSSDACTR','${DFILI}/${ENV_PREFIX}_ESCJ0060_FSSDACTR_${PARM_CLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESID2550_I4_PC__',  'EST_DLRNPGTR','${DFILP}/${ENV_PREFIX}_ESID1550_DLRNPGTR_${PARM0_ICLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESID2550_I4_PC__',  'EST_DLRTCGTR','${DFILP}/${ENV_PREFIX}_ESID2500_DLRTCGTR_${PARM0_ICLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESID2550_I4_PC__',  'EST_DLRTFGTR','${DFILP}/${ENV_PREFIX}_ESID2500_DLRTFGTR_${PARM0_ICLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESID2550_I4_PC__',  'EST_FCURCVSNI','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURCVSNI_${PARM_CLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESID2550_I4_PC__',  'EST_FPLACEMT0','${DFILI}/${ENV_PREFIX}_ESEH1110_FPLACEMT0_${PARM_CLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESID2550_I4_PC__',  'EST_DLGTRSNEM','${DFILI}/${ENV_PREFIX}_ESID2100_DLGTRSNEM_${PARM0_ICLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESID2550_I4_PC__',  'EST_FTRANSCODE','${DFILI}/${ENV_PREFIX}_ESCJ0060_FTRANSCODE_${PARM_CLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESID2550_I4_PC__',  'EST_IADVPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_IADVPERICASE_${PARM0_ICLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESID2550_I4_PC__',  'EST_IRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_IRDVPERICASE_${PARM0_ICLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESID2550_I4_PC__',  'EST_IADVPERICASE0','${DFILI}/${ENV_PREFIX}_ESID1000_IADVPERICASE0_${PARM_CLODAT_D}.dat','I','')


--		insert into BEST..TI17PERMFIL values ('ESID2550_I4_PC__',  'EST_DLREGTR0','${DFILP}/${ENV_PREFIX}_ESID2500_DLREGTR_${PARM0_ICLODAT_D}.dat','IO','') 
--		insert into BEST..TI17PERMFIL values ('ESID2550_I4_PC__',  'EST_DLRGTAA0','${DFILI}/${ENV_PREFIX}_ESID2050_DLRGTAA_${PARM0_ICLODAT_D}.datt','IO','')
--		insert into BEST..TI17PERMFIL values ('ESID2550_I4_PC__',  'EST_DLREMAJGTR0','${DFILP}/${ENV_PREFIX}_ESID2500_DLREMAJGTR_${PARM0_ICLODAT_D}.dat','IO','')

	-- output 
		insert into BEST..TI17PERMFIL values ('ESID2550_I4_PC__',  'EST_DLREGTR','${DFILP}/${ENV_PREFIX}_ESID2500_I4_PC___DLREGTR_${PARM0_ICLODAT_D}.dat','IO','') 
		insert into BEST..TI17PERMFIL values ('ESID2550_I4_PC__',  'EST_DLRGTAA','${DFILI}/${ENV_PREFIX}_ESID2050_I4_PC___DLRGTAA_${PARM0_ICLODAT_D}.dat','IO','')
		insert into BEST..TI17PERMFIL values ('ESID2550_I4_PC__',  'EST_DLREMAJGTR','${DFILP}/${ENV_PREFIX}_ESID2500_I4_PC___DLREMAJGTR_${PARM0_ICLODAT_D}.dat','IO','')
		
		insert into BEST..TI17PERMFIL values ('ESID2550_I4_PC__',  'EST_DLRIGTAA','${DFILP}/${ENV_PREFIX}_ESID0560_I4_PC___DLRIGTAA_${PARM0_ICLODAT_D}.dat','O','')
		insert into BEST..TI17PERMFIL values ('ESID2550_I4_PC__',  'EST_DLREMAJGTAR','${DFILP}/${ENV_PREFIX}_ESID2500_I4_PC___DLREMAJGTAR_${PARM0_ICLODAT_D}.dat','O','')
		insert into BEST..TI17PERMFIL values ('ESID2550_I4_PC__',  'EST_DLDVGTR','${DFILI}/${ENV_PREFIX}_ESID2550_I4_PC___DLDVGTR_${PARM0_ICLODAT_D}.dat','O','')
		insert into BEST..TI17PERMFIL values ('ESID2550_I4_PC__',  'EST_DLEIGTAA','${DFILI}/${ENV_PREFIX}_ESID2550_I4_PC___DLEIGTAA_${PARM0_ICLODAT_D}.dat','O','')
		insert into BEST..TI17PERMFIL values ('ESID2550_I4_PC__',  'EST_DLREGTAR','${DFILP}/${ENV_PREFIX}_ESID2500_I4_PC___DLREGTAR_${PARM0_ICLODAT_D}.dat', 'O', ' ' )
		insert into BEST..TI17PERMFIL values ('ESID2550_I4_PC__',  'EST_DLRIGTAANOS','${DFILI}/${ENV_PREFIX}_ESID2550_I4_PC___DLRIGTAANOS_${PARM0_ICLODAT_D}.dat','O','')
		
go

	
	--  ESID2550_I4_LIFE___ : fonctional id of Life execution 

	delete BEST..TI17PERMFIL where  IDF_CT like 'ESID2550_I4_LIFE__%'
	--IF NOT EXISTS (SELECT * FROM BEST..TI17FNC where IDF_CT = 'ESID2550_I4_LIFE__' ) insert into BEST..TI17FNC values ( 'ESID2550_I4_LIFE__','')
	---- npout 
	--	insert into BEST..TI17PERMFIL values ('ESID2550_I4_LIFE__',  'EST_GTEP','${DFILP}/${ENV_PREFIX}_ESCJ0060_GTEP.dat','I','')
	--	insert into BEST..TI17PERMFIL values ('ESID2550_I4_LIFE__',  'EST_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURQUOT.dat','I','')
	--	insert into BEST..TI17PERMFIL values ('ESID2550_I4_LIFE__',  'EST_FCES','${DFILP}/${ENV_PREFIX}_ESID2500_FCES_${PARM0_ICLODAT_D}.dat','I','')
	--	insert into BEST..TI17PERMFIL values ('ESID2550_I4_LIFE__',  'EST_FPLC','${DFILP}/${ENV_PREFIX}_ESID2500_FPLC_${PARM0_ICLODAT_D}.dat','I','')
	--	insert into BEST..TI17PERMFIL values ('ESID2550_I4_LIFE__',  'EST_DLSGTR','${DFILI}/${ENV_PREFIX}_ESID1800_DLSGTR_${PARM0_ICLODAT_D}.dat','I','')
	--	insert into BEST..TI17PERMFIL values ('ESID2550_I4_LIFE__',  'EST_SUBTRS','${DFILI}/${ENV_PREFIX}_ESCJ0060_FSUBTRS_${PARM_CLODAT_D}.dat','I','')
	--	insert into BEST..TI17PERMFIL values ('ESID2550_I4_LIFE__',  'EST_FDETTRS','${DFILP}/${ENV_PREFIX}_ESCJ0060_FDETTRS_${PARM_CLODAT_D}.dat','I','')
	--	insert into BEST..TI17PERMFIL values ('ESID2550_I4_LIFE__',  'EST_FRETTRF','${DFILP}/${ENV_PREFIX}_ESCJ0060_FRETTRF_${PARM_CLODAT_D}.dat','I','')
	--	insert into BEST..TI17PERMFIL values ('ESID2550_I4_LIFE__',  'EST_FTRSLNK','${DFILI}/${ENV_PREFIX}_ESCJ0060_FTRSLNK_${PARM_CLODAT_D}.dat','I','')
	--	insert into BEST..TI17PERMFIL values ('ESID2550_I4_LIFE__',  'EST_DLDGTAA','${DFILP}/empty.dat','I','')  ---
	--	insert into BEST..TI17PERMFIL values ('ESID2550_I4_LIFE__',  'EST_DLRPGTR','${DFILP}/empty.dat','I','')
	--	insert into BEST..TI17PERMFIL values ('ESID2550_I4_LIFE__',  'EST_DLRTGTR','${DFILP}/empty.dat','I','')
	--	insert into BEST..TI17PERMFIL values ('ESID2550_I4_LIFE__',  'EST_DLVGTR','${DFILP}/${ENV_PREFIX}_ESID2040_DLVGTR_PC_${PARM0_ICLODAT_D}.dat','I','')
	--	insert into BEST..TI17PERMFIL values ('ESID2550_I4_LIFE__',  'EST_FCURCVSN','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURCVSN_${PARM_CLODAT_D}.dat','I','')
	--	insert into BEST..TI17PERMFIL values ('ESID2550_I4_LIFE__',  'EST_FSSDACTR','${DFILI}/${ENV_PREFIX}_ESCJ0060_FSSDACTR_${PARM_CLODAT_D}.dat','I','')
	--	insert into BEST..TI17PERMFIL values ('ESID2550_I4_LIFE__',  'EST_DLRNPGTR','${DFILP}/empty.dat','I','')
	--	insert into BEST..TI17PERMFIL values ('ESID2550_I4_LIFE__',  'EST_DLRTCGTR','${DFILP}/empty.dat','I','')
	--	insert into BEST..TI17PERMFIL values ('ESID2550_I4_LIFE__',  'EST_DLRTFGTR','${DFILP}/empty.dat','I','')
	--	insert into BEST..TI17PERMFIL values ('ESID2550_I4_LIFE__',  'EST_FCURCVSNI','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURCVSNI_${PARM_CLODAT_D}.dat','I','')
	--	insert into BEST..TI17PERMFIL values ('ESID2550_I4_LIFE__',  'EST_FPLACEMT0','${DFILI}/${ENV_PREFIX}_ESEH1110_FPLACEMT0_${PARM_CLODAT_D}.dat','I','')
	--	insert into BEST..TI17PERMFIL values ('ESID2550_I4_LIFE__',  'EST_DLGTRSNEM','${DFILP}/empty.dat','I','')
	--	insert into BEST..TI17PERMFIL values ('ESID2550_I4_LIFE__',  'EST_FTRANSCODE','${DFILI}/${ENV_PREFIX}_ESCJ0060_FTRANSCODE_${PARM_CLODAT_D}.dat','I','')
	--	insert into BEST..TI17PERMFIL values ('ESID2550_I4_LIFE__',  'EST_IADVPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_IAVPERICASE_${PARM0_ICLODAT_D}.dat','I','')
	--	insert into BEST..TI17PERMFIL values ('ESID2550_I4_LIFE__',  'EST_IRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_IRVPERICASE_${PARM0_ICLODAT_D}.dat','I','')
	--	insert into BEST..TI17PERMFIL values ('ESID2550_I4_LIFE__',  'EST_IADVPERICASE0','${DFILI}/${ENV_PREFIX}_ESDJ1010_IAVPERICASE0_${PARM_CLODAT_D}.dat','I','')
	--	insert into BEST..TI17PERMFIL values ('ESID2550_I4_LIFE__',  'EST_DLREGTR0','${DFILP}/empty.dat','I','') 
	--	insert into BEST..TI17PERMFIL values ('ESID2550_I4_LIFE__',  'EST_DLRGTAA0','${DFILP}/empty.dat','I','')
	--	insert into BEST..TI17PERMFIL values ('ESID2550_I4_LIFE__',  'EST_DLREMAJGTR0','${DFILP}/${ENV_PREFIX}_ESID2500_DLREMAJGTR_${PARM0_ICLODAT_D}.dat','IO','')
	---- output                                                    
	--	insert into BEST..TI17PERMFIL values ('ESID2550_I4_LIFE__',  'EST_DLRIGTAA','${DFILP}/${ENV_PREFIX}_ESID0560_I4_LIFE___DLRIGTAA_${PARM0_ICLODAT_D}.dat','O','')
	--	insert into BEST..TI17PERMFIL values ('ESID2550_I4_LIFE__',  'EST_DLREMAJGTAR','${DFILP}/${ENV_PREFIX}_ESID2500_I4_LIFE___DLREMAJGTAR_${PARM0_ICLODAT_D}.dat','O','')
	--	insert into BEST..TI17PERMFIL values ('ESID2550_I4_LIFE__',  'EST_DLREMAJGTR','${DFILP}/${ENV_PREFIX}_ESID2500_I4_LIFE___DLREMAJGTR_${PARM0_ICLODAT_D}.dat','IO','')
	--	insert into BEST..TI17PERMFIL values ('ESID2550_I4_LIFE__',  'EST_DLREGTR','${DFILP}/${ENV_PREFIX}_ESID2500_I4_LIFE___DLREGTR_${PARM0_ICLODAT_D}.dat','IO','')
	--	insert into BEST..TI17PERMFIL values ('ESID2550_I4_LIFE__',  'EST_DLDVGTR','${DFILI}/${ENV_PREFIX}_ESID2550_I4_LIFE___DLDVGTR_${PARM0_ICLODAT_D}.dat','O','')
	--	insert into BEST..TI17PERMFIL values ('ESID2550_I4_LIFE__',  'EST_DLEIGTAA','${DFILI}/${ENV_PREFIX}_ESID2550_I4_LIFE___DLEIGTAA_${PARM0_ICLODAT_D}.dat','O','')
	--	insert into BEST..TI17PERMFIL values ('ESID2550_I4_LIFE__',  'EST_DLREGTAR','${DFILP}/${ENV_PREFIX}_ESID2500_I4_LIFE___DLREGTAR_${PARM0_ICLODAT_D}.dat', 'O', ' ' )
	--	insert into BEST..TI17PERMFIL values ('ESID2550_I4_LIFE__',  'EST_DLRIGTAANOS','${DFILI}/${ENV_PREFIX}_ESID2550_I4_LIFE___DLRIGTAANOS_${PARM0_ICLODAT_D}.dat','O','')
	--	insert into BEST..TI17PERMFIL values ('ESID2550_I4_LIFE__',  'EST_DLRGTAA','${DFILI}/${ENV_PREFIX}_ESID2050_I4_LIFE___DLRGTAA_${PARM0_ICLODAT_D}.dat','O','')
	
		----------   Reqs of chain   ---------------------
go

	delete BEST..TI17PERMFIL where  IDF_CT = 'ESID2550'
	IF NOT EXISTS (SELECT * FROM BEST..TI17FNC where IDF_CT = 'ESID2550_I4_PC___' ) insert into BEST..TI17FNC values ( 'ESID2550','')

	-- input
		insert into BEST..TI17PERMFIL values ('ESID2550',  'EST_GTEP','${DFILP}/${ENV_PREFIX}_ESCJ0060_GTEP.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESID2550',  'EST_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURQUOT.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESID2550',  'EST_FCES','${DFILP}/${ENV_PREFIX}_ESID2500_FCES_${PARM0_ICLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESID2550',  'EST_FPLC','${DFILP}/${ENV_PREFIX}_ESID2500_FPLC_${PARM0_ICLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESID2550',  'EST_DLSGTR','${DFILI}/${ENV_PREFIX}_ESID1800_DLSGTR_${PARM0_ICLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESID2550',  'EST_SUBTRS','${DFILI}/${ENV_PREFIX}_ESCJ0060_FSUBTRS_${PARM_CLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESID2550',  'EST_FDETTRS','${DFILP}/${ENV_PREFIX}_ESCJ0060_FDETTRS_${PARM_CLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESID2550',  'EST_FRETTRF','${DFILP}/${ENV_PREFIX}_ESCJ0060_FRETTRF_${PARM_CLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESID2550',  'EST_FTRSLNK','${DFILI}/${ENV_PREFIX}_ESCJ0060_FTRSLNK_${PARM_CLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESID2550',  'EST_DLDGTAA','${DFILP}/${ENV_PREFIX}_ESID2000_DLDGTAA_${PARM0_ICLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESID2550',  'EST_DLRPGTR','${DFILP}/${ENV_PREFIX}_ESID2500_DLRPGTR_${PARM0_ICLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESID2550',  'EST_DLRTGTR','${DFILP}/${ENV_PREFIX}_ESID2500_DLRTGTR_${PARM0_ICLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESID2550',  'EST_DLVGTR','${DFILP}/${ENV_PREFIX}_ESID2040_DLVGTR_PC_${PARM0_ICLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESID2550',  'EST_FCURCVSN','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURCVSN_${PARM_CLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESID2550',  'EST_FSSDACTR','${DFILI}/${ENV_PREFIX}_ESCJ0060_FSSDACTR_${PARM_CLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESID2550',  'EST_DLRNPGTR','${DFILP}/${ENV_PREFIX}_ESID1550_DLRNPGTR_${PARM0_ICLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESID2550',  'EST_DLRTCGTR','${DFILP}/${ENV_PREFIX}_ESID2500_DLRTCGTR_${PARM0_ICLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESID2550',  'EST_DLRTFGTR','${DFILP}/${ENV_PREFIX}_ESID2500_DLRTFGTR_${PARM0_ICLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESID2550',  'EST_FCURCVSNI','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURCVSNI_${PARM_CLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESID2550',  'EST_FPLACEMT0','${DFILI}/${ENV_PREFIX}_ESEH1110_FPLACEMT0_${PARM_CLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESID2550',  'EST_DLGTRSNEM','${DFILI}/${ENV_PREFIX}_ESID2100_DLGTRSNEM_${PARM0_ICLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESID2550',  'EST_FTRANSCODE','${DFILI}/${ENV_PREFIX}_ESCJ0060_FTRANSCODE_${PARM_CLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESID2550',  'EST_IADVPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_IADVPERICASE_${PARM0_ICLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESID2550',  'EST_IRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_IRDVPERICASE_${PARM0_ICLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESID2550',  'EST_IADVPERICASE0','${DFILI}/${ENV_PREFIX}_ESID1000_IADVPERICASE0_${PARM_CLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESID2550',  'EST_DLREGTR','${DFILP}/${ENV_PREFIX}_ESID2500_DLREGTR_${PARM0_ICLODAT_D}.dat','IO','') 
		insert into BEST..TI17PERMFIL values ('ESID2550',  'EST_DLRGTAA','${DFILI}/${ENV_PREFIX}_ESID2050_DLRGTAA_${PARM0_ICLODAT_D}.dat','IO','')
		insert into BEST..TI17PERMFIL values ('ESID2550',  'EST_DLREMAJGTR','${DFILP}/${ENV_PREFIX}_ESID2500_DLREMAJGTR_${PARM0_ICLODAT_D}.dat','IO','')
	-- output 
		insert into BEST..TI17PERMFIL values ('ESID2550',  'EST_DLRIGTAA','${DFILP}/${ENV_PREFIX}_ESID0560_DLRIGTAA_${PARM0_ICLODAT_D}.dat','O','')
		insert into BEST..TI17PERMFIL values ('ESID2550',  'EST_DLREMAJGTAR','${DFILP}/${ENV_PREFIX}_ESID2500_DLREMAJGTAR_${PARM0_ICLODAT_D}.dat','O','')
		insert into BEST..TI17PERMFIL values ('ESID2550',  'EST_DLDVGTR','${DFILI}/${ENV_PREFIX}_ESID2550_DLDVGTR_${PARM0_ICLODAT_D}.dat','O','')
		insert into BEST..TI17PERMFIL values ('ESID2550',  'EST_DLEIGTAA','${DFILI}/${ENV_PREFIX}_ESID2550_DLEIGTAA_${PARM0_ICLODAT_D}.dat','O','')
		insert into BEST..TI17PERMFIL values ('ESID2550',  'EST_DLREGTAR','${DFILP}/${ENV_PREFIX}_ESID2500_DLREGTAR_${PARM0_ICLODAT_D}.dat', 'O', ' ' )
		insert into BEST..TI17PERMFIL values ('ESID2550',  'EST_DLRIGTAANOS','${DFILI}/${ENV_PREFIX}_ESID2550_DLRIGTAANOS_${PARM0_ICLODAT_D}.dat','O','')

-------------------------------
print	"--	Init  ESID2100"
-------------------------------


	----------  IDF_CT = 'ESID2100_I4_PC___'  ---------------------

	delete BEST..TI17PERMFIL where  IDF_CT = 'ESID2100_I4_PC___'
	IF NOT EXISTS (SELECT * FROM BEST..TI17FNC where IDF_CT = 'ESID2100_I4_PC___' ) insert into BEST..TI17FNC values ( 'ESID2100_I4_PC___','')

--	-- input
--	insert into BEST..TI17PERMFIL values ('ESID2100_I4_PC___',  'EST_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURQUOT.dat','I','')
--	insert into BEST..TI17PERMFIL values ('ESID2100_I4_PC___',  'EST_FCES','${DFILP}/${ENV_PREFIX}_ESID2500_FCES_${PARM0_ICLODAT_D}.dat','I','')
--	insert into BEST..TI17PERMFIL values ('ESID2100_I4_PC___',  'EST_FPLC','${DFILP}/${ENV_PREFIX}_ESID2500_FPLC_${PARM0_ICLODAT_D}.dat','I','')
--	insert into BEST..TI17PERMFIL values ('ESID2100_I4_PC___',  'EST_FDETTRS','${DFILP}/${ENV_PREFIX}_ESCJ0060_FDETTRS_${PARM_CLODAT_D}.dat','I','')
--	insert into BEST..TI17PERMFIL values ('ESID2100_I4_PC___',  'EST_FTRSLNK','${DFILI}/${ENV_PREFIX}_ESCJ0060_FTRSLNK_${PARM_CLODAT_D}.dat','I','')
--	insert into BEST..TI17PERMFIL values ('ESID2100_I4_PC___',  'EST_DLDGTAA','${DFILP}/${ENV_PREFIX}_ESID2000_DLDGTAA_${PARM0_ICLODAT_D}.dat','I','')
--	insert into BEST..TI17PERMFIL values ('ESID2100_I4_PC___',  'EST_DLRGTAA','${DFILI}/${ENV_PREFIX}_ESID2050_I4_PC___DLRGTAA_${PARM0_ICLODAT_D}.dat','I','')  -- [01]
--	insert into BEST..TI17PERMFIL values ('ESID2100_I4_PC___',  'EST_FCURCVSN','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURCVSN_${PARM_CLODAT_D}.dat','I','')
--	insert into BEST..TI17PERMFIL values ('ESID2100_I4_PC___',  'EST_FCURCVSNI','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURCVSNI_${PARM_CLODAT_D}.dat','I','')
--	insert into BEST..TI17PERMFIL values ('ESID2100_I4_PC___',  'EST_FSNEMHIST','${DFILP}/${ENV_PREFIX}_ESID0560_FSNEMHIST_${PARM0_ICLODAT_D}.dat','I','')
--	insert into BEST..TI17PERMFIL values ('ESID2100_I4_PC___',  'EST_FTRANSCODE','${DFILI}/${ENV_PREFIX}_ESCJ0060_FTRANSCODE_${PARM_CLODAT_D}.dat','I','')
--	insert into BEST..TI17PERMFIL values ('ESID2100_I4_PC___',  'EST_FLOARATSNEM','${DFILP}/${ENV_PREFIX}_ESID2000_FLOARATSNEM_${PARM0_ICLODAT_D}.dat','I','')
--	insert into BEST..TI17PERMFIL values ('ESID2100_I4_PC___',  'EST_DSUMGTAASNEM','${DFILP}/${ENV_PREFIX}_ESID2000_DSUMGTAASNEM_${PARM0_ICLODAT_D}.dat','I','')
--	insert into BEST..TI17PERMFIL values ('ESID2100_I4_PC___',  'EST_IADVPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_IADVPERICASE_${PARM0_ICLODAT_D}.dat','I','')
--	insert into BEST..TI17PERMFIL values ('ESID2100_I4_PC___',  'EST_PERICASESNEM','${DFILP}/${ENV_PREFIX}_ESID2000_PERICASESNEM_${PARM0_ICLODAT_D}.dat','I','')
--	-- output
--	insert into BEST..TI17PERMFIL values ('ESID2100_I4_PC___',  'EST_DLGTRSNEM','${DFILI}/${ENV_PREFIX}_ESID2100_I4_PC___DLGTRSNEM_${PARM0_ICLODAT_D}.dat','O','')
--	insert into BEST..TI17PERMFIL values ('ESID2100_I4_PC___',  'EST_DLGTAASNEM','${DFILI}/${ENV_PREFIX}_ESID2100_I4_PC___DLGTAASNEM_${PARM0_ICLODAT_D}.dat','O','')
--	insert into BEST..TI17PERMFIL values ('ESID2100_I4_PC___',  'EST_DLGTARSNEM','${DFILI}/${ENV_PREFIX}_ESID2100_I4_PC___DLGTARSNEM_${PARM0_ICLODAT_D}.dat','O','')
--	insert into BEST..TI17PERMFIL values ('ESID2100_I4_PC___',  'EST_DLFTSNEMHIST','${DFILI}/${ENV_PREFIX}_ESID2100_I4_PC___DLFTSNEMHIST_${PARM0_ICLODAT_D}.dat','O','')
--
--	----------   Reqs of chain   ---------------------


go


-------------------------------
print "--	Init  ESID2060"
-------------------------------



	----------  IDF_CT = '²'  ---------------------
	delete BEST..TI17PERMFIL where  IDF_CT = 'ESID2060_I4_PC___'
	delete BEST..TI17PERMFIL where  IDF_CT = 'ESID2060_I4_PC__'
	IF NOT EXISTS (SELECT * FROM BEST..TI17FNC where IDF_CT = 'ESID2060_I4_PC__' ) insert into BEST..TI17FNC values ( 'ESID2060_I4_PC__','')



	-- input
	insert into BEST..TI17PERMFIL values ('ESID2060_I4_PC__',  'EST_GTA','${DFILP}/${ENV_PREFIX}_ESIX7000_GTA.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2060_I4_PC__',  'EST_MGTAA','${DFILP}/${ENV_PREFIX}_ESIX7000_MGTAA.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2060_I4_PC__',  'EST_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURQUOT.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2060_I4_PC__',  'EST_FCES','${DFILP}/${ENV_PREFIX}_ESID2500_FCES_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2060_I4_PC__',  'EST_FPLC','${DFILP}/${ENV_PREFIX}_ESID2500_FPLC_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2060_I4_PC__',  'EST_IGTAAF','${DFILI}/${ENV_PREFIX}_ESID0560_IGTAAF_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2060_I4_PC__',  'EST_FDETTRS','${DFILP}/${ENV_PREFIX}_ESCJ0060_FDETTRS_${PARM_CLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2060_I4_PC__',  'EST_FTRSLNK','${DFILI}/${ENV_PREFIX}_ESCJ0060_FTRSLNK_${PARM_CLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2060_I4_PC__',  'EST_DLAGTAA','${DFILP}/${ENV_PREFIX}_ESID0560_DLAGTAA_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2060_I4_PC__',  'EST_DLDGTAA','${DFILP}/${ENV_PREFIX}_ESID2000_DLDGTAA_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2060_I4_PC__',  'EST_DLRGTAA','${DFILI}/${ENV_PREFIX}_ESID2050_I4_PC___DLRGTAA_${PARM0_ICLODAT_D}.dat','I','')   -- [01]
	insert into BEST..TI17PERMFIL values ('ESID2060_I4_PC__',  'EST_DLSGTAA','${DFILI}/${ENV_PREFIX}_ESID1800_DLSGTAA_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2060_I4_PC__',  'EST_MVTPNAC','${DFILI}/${ENV_PREFIX}_ESID0560_MVTPNAC_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2060_I4_PC__',  'EST_FCURCVSN','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURCVSN_${PARM_CLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2060_I4_PC__',  'EST_FCURCVSNI','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURCVSNI_${PARM_CLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2060_I4_PC__',  'EST_FTRANSCODE','${DFILI}/${ENV_PREFIX}_ESCJ0060_FTRANSCODE_${PARM_CLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2060_I4_PC__',  'EST_DLASIIGTAA','${DFILI}/${ENV_PREFIX}_ESID3600_DLASIIGTAA_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2060_I4_PC__',  'EST_DLDSIIGTAA','${DFILI}/${ENV_PREFIX}_ESID3700_DLDSIIGTAA_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2060_I4_PC__',  'EST_DLGTAASNEM','${DFILI}/${ENV_PREFIX}_ESID2100_DLGTAASNEM_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2060_I4_PC__',  'EST_IADVPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_IADVPERICASE_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2060_I4_PC__',  'EST_DLVGTAA','${DFILP}/empty.dat','I','')                                              ---- [01]
	-- output
	insert into BEST..TI17PERMFIL values ('ESID2060_I4_PC__',  'EST_TOTGTAA','${DFILI}/${ENV_PREFIX}_ESID2060_I4_PC___TOTGTAA_${PARM0_ICLODAT_D}.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESID2060_I4_PC__',  'EST_DLTOTGTAA','${DFILI}/${ENV_PREFIX}_ESID2060_I4_PC___DLTOTGTAA_${PARM0_ICLODAT_D}.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESID2060_I4_PC__',  'EST_DLTOTITGTAR','${DFILI}/${ENV_PREFIX}_ESID2060_I4_PC___DLTOTITGTAR_${PARM0_ICLODAT_D}.dat','O','')

	----------  IDF_CT = 'ESID2060_I4_LIFE___'  ---------------------
	delete BEST..TI17PERMFIL where  IDF_CT = 'ESID2060_I4_LIFE___'
	IF NOT EXISTS (SELECT * FROM BEST..TI17FNC where IDF_CT = 'ESID2060_I4_LIFE___' ) insert into BEST..TI17FNC values ( 'ESID2060_I4_LIFE___','')
	
--insert into BEST..TI17PERMFIL
--SELECT "ESID2060_I4_LIFE___" IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL 
--FROM BEST..TI17PERMFIL 
--where  IDF_CT = 'ESID2060'
	
	---- input
	--insert into BEST..TI17PERMFIL values ('ESID2060_I4_LIFE___',  'EST_GTA','${DFILP}/${ENV_PREFIX}_ESIX7000_GTA.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2060_I4_LIFE___',  'EST_MGTAA','${DFILP}/${ENV_PREFIX}_ESIX7000_MGTAA.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2060_I4_LIFE___',  'EST_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURQUOT.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2060_I4_LIFE___',  'EST_FCES','${DFILP}/${ENV_PREFIX}_ESID2500_FCES_${PARM0_ICLODAT_D}.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2060_I4_LIFE___',  'EST_FPLC','${DFILP}/${ENV_PREFIX}_ESID2500_FPLC_${PARM0_ICLODAT_D}.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2060_I4_LIFE___',  'EST_IGTAAF','${DFILI}/${ENV_PREFIX}_ESID0560_IGTAAF_${PARM0_ICLODAT_D}.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2060_I4_LIFE___',  'EST_FDETTRS','${DFILP}/${ENV_PREFIX}_ESCJ0060_FDETTRS_${PARM_CLODAT_D}.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2060_I4_LIFE___',  'EST_FTRSLNK','${DFILI}/${ENV_PREFIX}_ESCJ0060_FTRSLNK_${PARM_CLODAT_D}.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2060_I4_LIFE___',  'EST_DLAGTAA','${DFILP}/${ENV_PREFIX}_ESID0560_DLAGTAA_${PARM0_ICLODAT_D}.dat','I','')                                                -- [01]
	--insert into BEST..TI17PERMFIL values ('ESID2060_I4_LIFE___',  'EST_DLDGTAA','${DFILP}/empty.dat','I','')                                                -- [01]
	--insert into BEST..TI17PERMFIL values ('ESID2060_I4_LIFE___',  'EST_DLRGTAA','${DFILI}/${ENV_PREFIX}_ESID2050_I4_LIFE___DLRGTAA_${PARM0_ICLODAT_D}.dat','I','')  -- [01]                                             -- [01]
	--insert into BEST..TI17PERMFIL values ('ESID2060_I4_LIFE___',  'EST_DLSGTAA','${DFILP}/empty.dat','I','')                                                -- [01]
	--insert into BEST..TI17PERMFIL values ('ESID2060_I4_LIFE___',  'EST_MVTPNAC','${DFILI}/${ENV_PREFIX}_ESID0560_MVTPNAC_${PARM0_ICLODAT_D}.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2060_I4_LIFE___',  'EST_FCURCVSN','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURCVSN_${PARM_CLODAT_D}.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2060_I4_LIFE___',  'EST_FCURCVSNI','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURCVSNI_${PARM_CLODAT_D}.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2060_I4_LIFE___',  'EST_FTRANSCODE','${DFILI}/${ENV_PREFIX}_ESCJ0060_FTRANSCODE_${PARM_CLODAT_D}.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2060_I4_LIFE___',  'EST_DLASIIGTAA','${DFILP}/empty.dat','I','')                                               -- [01]
	--insert into BEST..TI17PERMFIL values ('ESID2060_I4_LIFE___',  'EST_DLDSIIGTAA','${DFILP}/empty.dat','I','')                                               -- [01]
	--insert into BEST..TI17PERMFIL values ('ESID2060_I4_LIFE___',  'EST_DLGTAASNEM','${DFILP}/empty.dat','I','')                                               -- [01]
	--insert into BEST..TI17PERMFIL values ('ESID2060_I4_LIFE___',  'EST_IADVPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_IADVPERICASE_${PARM0_ICLODAT_D}.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2060_I4_LIFE___',  'EST_DLVGTAA',"`ls -rt ${DFILP}/${ENV_PREFIX}_ESID2080_DLVGTAA_PC_${PARM0_ICLODAT_D}*.dat | tail -1 `",'I','')
	--																			
	---- output 
	--insert into BEST..TI17PERMFIL values ('ESID2060_I4_LIFE___',  'EST_TOTGTAA','${DFILI}/${ENV_PREFIX}_ESID2060_I4_LIFE___TOTGTAA_${PARM0_ICLODAT_D}.dat','O','')
	--insert into BEST..TI17PERMFIL values ('ESID2060_I4_LIFE___',  'EST_DLTOTGTAA','${DFILI}/${ENV_PREFIX}_ESID2060_I4_LIFE___DLTOTGTAA_${PARM0_ICLODAT_D}.dat','O','')
	--insert into BEST..TI17PERMFIL values ('ESID2060_I4_LIFE___',  'EST_DLTOTITGTAR','${DFILI}/${ENV_PREFIX}_ESID2060_I4_LIFE___DLTOTITGTAR_${PARM0_ICLODAT_D}.dat','O','')

	
	delete BEST..TI17PERMFIL where  IDF_CT = 'ESID2060' and PERMFIL_CT ='EST_DLVGTAA'
	insert into BEST..TI17PERMFIL values ('ESID2060',  'EST_DLVGTAA',"`ls -rt ${DFILP}/${ENV_PREFIX}_ESID2080_DLVGTAA_PC_${PARM0_ICLODAT_D}*.dat | tail -1 `",'I','')


----------   Reqs of chain   ---------------------


go





-------------------------------
print	"--	Init  ESID2560"
-------------------------------


	----------  IDF_CT = 'ESID2560_I4_PC___'  ---------------------

	delete BEST..TI17PERMFIL where  IDF_CT = 'ESID2560_I4_PC__'
	IF NOT EXISTS (SELECT * FROM BEST..TI17FNC where IDF_CT = 'ESID2560_I4_PC__' ) insert into BEST..TI17FNC values ( 'ESID2560_I4_PC__','')


	insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC__',  'EST_GTA','${DFILP}/${ENV_PREFIX}_ESIX7000_GTA.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC__',  'EST_GTR','${DFILP}/${ENV_PREFIX}_ESIX7000_GTR.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC__',  'EST_MGTR','${DFILP}/${ENV_PREFIX}_ESIX7000_MGTR.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC__',  'EST_IGTAR','${DFILP}/${ENV_PREFIX}_ESID0560_IGTAR.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC__',  'EST_MGTAR','${DFILP}/${ENV_PREFIX}_ESIX7000_MGTAR.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC__',  'EST_IGTR','${DFILP}/${ENV_PREFIX}_ESID0560_IGTR_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC__',  'EST_FVENTNPANT','${DFILP}/${ENV_PREFIX}_ESIX7000_FVENTNPANT.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC__',  'EST_DLAGTR','${DFILP}/${ENV_PREFIX}_ESID0560_DLAGTR_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC__',  'EST_DLSGTR','${DFILI}/${ENV_PREFIX}_ESID1800_DLSGTR_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC__',  'EST_FDETTRS','${DFILP}/${ENV_PREFIX}_ESCJ0060_FDETTRS_${PARM_CLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC__',  'EST_FLIBEL2','${DFILP}/${ENV_PREFIX}_ESCJ0060_FLIBEL2_${PARM_CLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC__',  'EST_DLAGTAR','${DFILP}/${ENV_PREFIX}_ESID0560_DLAGTAR_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC__',  'EST_DLDVGTR','${DFILI}/${ENV_PREFIX}_ESID2550_I4_PC___DLDVGTR_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC__',  'EST_DLREGTR','${DFILP}/${ENV_PREFIX}_ESID2500_I4_PC___DLREGTR_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC__',  'EST_DLRPGTR','${DFILP}/${ENV_PREFIX}_ESID2500_DLRPGTR_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC__',  'EST_DLRTGTR','${DFILP}/${ENV_PREFIX}_ESID2500_DLRTGTR_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC__',  'EST_DLSGTAR','${DFILI}/${ENV_PREFIX}_ESID1800_DLSGTAR_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC__',  'EST_DLVGTR','${DFILP}/empty.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC__',  'EST_FTRSLNK7','${DFILI}/${ENV_PREFIX}_ESCJ0060_FTRSLNK7_${PARM_CLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC__',  'EST_FTVENTNP','${DFILP}/${ENV_PREFIX}_ESID0060_FTVENTNP_${PARM_CLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC__',  'EST_DLREGTAR','${DFILP}/${ENV_PREFIX}_ESID2500_DLREGTAR_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC__',  'EST_DLRNPGTR','${DFILP}/${ENV_PREFIX}_ESID1550_DLRNPGTR_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC__',  'EST_DLRPGTAR','${DFILP}/${ENV_PREFIX}_ESID2500_DLRPGTAR_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC__',  'EST_DLRTCGTR','${DFILP}/${ENV_PREFIX}_ESID2500_DLRTCGTR_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC__',  'EST_DLRTFGTR','${DFILP}/${ENV_PREFIX}_ESID2500_DLRTFGTR_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC__',  'EST_DLRTGTAR','${DFILP}/${ENV_PREFIX}_ESID2500_DLRTGTAR_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC__',  'EST_VENTNP_TRIMCUR','${DFILP}/${ENV_PREFIX}_ESIX7000_VENTNP_TRIMCUR.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC__',  'EST_DLRNPGTAR','${DFILP}/${ENV_PREFIX}_ESID1550_DLRNPGTAR_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC__',  'EST_DLRTCGTAR','${DFILP}/${ENV_PREFIX}_ESID2500_DLRTCGTAR_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC__',  'EST_DLRTFGTAR','${DFILP}/${ENV_PREFIX}_ESID2500_DLRTFGTAR_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC__',  'EST_FPLATXCUM','${DFILI}/${ENV_PREFIX}_ESID0560_FPLATXCUM_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC__',  'EST_VENTNP_TRIMPREV','${DFILP}/${ENV_PREFIX}_ESIX7000_VENTNP_TRIMPREV.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC__',  'EST_DLASIIGTAR','${DFILI}/${ENV_PREFIX}_ESID3600_DLASIIGTAR_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC__',  'EST_DLDSIIGTAR','${DFILI}/${ENV_PREFIX}_ESID3700_DLDSIIGTAR_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC__',  'EST_DLGTARSNEM','${DFILI}/${ENV_PREFIX}_ESID2100_DLGTARSNEM_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC__',  'EST_DLREMAJGTR','${DFILP}/${ENV_PREFIX}_ESID2500_I4_PC___DLREMAJGTR_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC__',  'EST_DLREMAJGTAR','${DFILP}/${ENV_PREFIX}_ESID2500_DLREMAJGTAR_${PARM0_ICLODAT_D}.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2560',  'EST_DLTOTITGTAR','${DFILI}/${ENV_PREFIX}_ESID2060_DLTOTITGTAR_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC__',  'EST_CADVPERIESB0','${DFILI}/${ENV_PREFIX}_ESID0060_CADVPERIESB0_${PARM_CLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC__',  'EST_IADVPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_IADVPERICASE_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC__',  'EST_IRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_IRDVPERICASE_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC__',  'EST_DLVGTAR','${DFILP}/empty.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC__',  'EST_OIRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_OIRDVPERICASE_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC__',  'EST_IADVPERICASE_ENTIER','${DFILP}/${ENV_PREFIX}_ESID0560_IADVPERICASE_ENTIER_${PARM0_ICLODAT_D}.dat','I','')
	--Output
	insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC__',  'EST_TOTGTR','${DFILI}/${ENV_PREFIX}_ESID2560_I4_PC___TOTGTR_${PARM0_ICLODAT_D}.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC__',  'EST_TOTGTAR','${DFILI}/${ENV_PREFIX}_ESID2560_I4_PC___TOTGTAR_${PARM0_ICLODAT_D}.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC__',  'EST_DLDVGTAR','${DFILI}/${ENV_PREFIX}_ESID2560_I4_PC___DLDVGTAR_${PARM0_ICLODAT_D}.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC__',  'EST_DLTOTGTR','${DFILI}/${ENV_PREFIX}_ESID2560_I4_PC___DLTOTGTR_${PARM0_ICLODAT_D}.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC__',  'EST_DLTOTGTAR','${DFILI}/${ENV_PREFIX}_ESID2560_I4_PC___DLTOTGTAR_${PARM0_ICLODAT_D}.dat','O','')

	delete BEST..TI17PERMFIL where  IDF_CT = 'ESID2560_I4_LIFE___'
	IF NOT EXISTS (SELECT * FROM BEST..TI17FNC where IDF_CT = 'ESID2560_I4_LIFE___' ) insert into BEST..TI17FNC values ( 'ESID2560_I4_LIFE___','')


	----------  IDF_CT = 'ESID2560_I4_LIFE___'  ---------------------

	--insert into BEST..TI17PERMFIL
	--SELECT "ESID2560_I4_LIFE___" IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL 
	--FROM BEST..TI17PERMFIL 
	--where  IDF_CT = 'ESID2560'


	--insert into BEST..TI17PERMFIL values ('ESID2560_I4_LIFE___',  'EST_GTA','${DFILP}/${ENV_PREFIX}_ESIX7000_GTA.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2560_I4_LIFE___',  'EST_GTR','${DFILP}/${ENV_PREFIX}_ESIX7000_GTR.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2560_I4_LIFE___',  'EST_MGTR','${DFILP}/${ENV_PREFIX}_ESIX7000_MGTR.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2560_I4_LIFE___',  'EST_IGTAR','${DFILP}/${ENV_PREFIX}_ESID0560_IGTAR.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2560_I4_LIFE___',  'EST_MGTAR','${DFILP}/${ENV_PREFIX}_ESIX7000_MGTAR.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2560_I4_LIFE___',  'EST_IGTR','${DFILP}/${ENV_PREFIX}_ESID0560_IGTR_${PARM0_ICLODAT_D}.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2560_I4_LIFE___',  'EST_FVENTNPANT','${DFILP}/${ENV_PREFIX}_ESIX7000_FVENTNPANT.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2560_I4_LIFE___',  'EST_DLAGTR','${DFILP}/${ENV_PREFIX}_ESID0560_DLAGTR_${PARM0_ICLODAT_D}.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2560_I4_LIFE___',  'EST_DLSGTR','${DFILI}/${ENV_PREFIX}_ESID1800_DLSGTR_${PARM0_ICLODAT_D}.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2560_I4_LIFE___',  'EST_FDETTRS','${DFILP}/${ENV_PREFIX}_ESCJ0060_FDETTRS_${PARM_CLODAT_D}.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2560_I4_LIFE___',  'EST_FLIBEL2','${DFILP}/${ENV_PREFIX}_ESCJ0060_FLIBEL2_${PARM_CLODAT_D}.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2560_I4_LIFE___',  'EST_DLAGTAR','${DFILP}/${ENV_PREFIX}_ESID0560_DLAGTAR_${PARM0_ICLODAT_D}.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2560_I4_LIFE___',  'EST_DLDVGTR','${DFILI}/${ENV_PREFIX}_ESID2550_I4_LIFE___DLDVGTR_${PARM0_ICLODAT_D}.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2560_I4_LIFE___',  'EST_DLREGTR','${DFILP}/empty.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2560_I4_LIFE___',  'EST_DLRPGTR','${DFILP}/empty.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2560_I4_LIFE___',  'EST_DLRTGTR','${DFILP}/empty.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2560_I4_LIFE___',  'EST_DLSGTAR','${DFILI}/${ENV_PREFIX}_ESID1800_DLSGTAR_${PARM0_ICLODAT_D}.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2560_I4_LIFE___',  'EST_DLVGTR','${DFILP}/${ENV_PREFIX}_ESID2040_DLVGTR_PC_${PARM0_ICLODAT_D}.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2560_I4_LIFE___',  'EST_FTRSLNK7','${DFILI}/${ENV_PREFIX}_ESCJ0060_FTRSLNK7_${PARM_CLODAT_D}.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2560_I4_LIFE___',  'EST_FTVENTNP','${DFILP}/${ENV_PREFIX}_ESID0060_FTVENTNP_${PARM_CLODAT_D}.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2560_I4_LIFE___',  'EST_DLREGTAR','${DFILP}/empty.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2560_I4_LIFE___',  'EST_DLRNPGTR','${DFILP}/${ENV_PREFIX}_ESID1550_DLRNPGTR_${PARM0_ICLODAT_D}.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2560_I4_LIFE___',  'EST_DLRPGTAR','${DFILP}/empty.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2560_I4_LIFE___',  'EST_DLRTCGTR','${DFILP}/empty.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2560_I4_LIFE___',  'EST_DLRTFGTR','${DFILP}/empty.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2560_I4_LIFE___',  'EST_DLRTGTAR','${DFILP}/empty.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2560_I4_LIFE___',  'EST_VENTNP_TRIMCUR','${DFILP}/${ENV_PREFIX}_ESIX7000_VENTNP_TRIMCUR.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2560_I4_LIFE___',  'EST_DLRNPGTAR','${DFILP}/${ENV_PREFIX}_ESID1550_DLRNPGTAR_${PARM0_ICLODAT_D}.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2560_I4_LIFE___',  'EST_DLRTCGTAR','${DFILP}/empty.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2560_I4_LIFE___',  'EST_DLRTFGTAR','${DFILP}/empty.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2560_I4_LIFE___',  'EST_FPLATXCUM','${DFILI}/${ENV_PREFIX}_ESID0560_FPLATXCUM_${PARM0_ICLODAT_D}.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2560_I4_LIFE___',  'EST_VENTNP_TRIMPREV','${DFILP}/${ENV_PREFIX}_ESIX7000_VENTNP_TRIMPREV.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2560_I4_LIFE___',  'EST_DLASIIGTAR','${DFILI}/${ENV_PREFIX}_ESID3600_DLASIIGTAR_${PARM0_ICLODAT_D}.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2560_I4_LIFE___',  'EST_DLDSIIGTAR','${DFILI}/${ENV_PREFIX}_ESID3700_DLDSIIGTAR_${PARM0_ICLODAT_D}.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2560_I4_LIFE___',  'EST_DLGTARSNEM','${DFILP}/empty.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2560_I4_LIFE___',  'EST_DLREMAJGTR','${DFILP}/${ENV_PREFIX}_ESID2500_I4_LIFE___DLREMAJGTR_${PARM0_ICLODAT_D}.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2560_I4_LIFE___',  'EST_DLREMAJGTAR','${DFILP}/empty.dat','I','')
	----insert into BEST..TI17PERMFIL values ('ESID2560',  'EST_DLTOTITGTAR','${DFILP}/empty.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2560_I4_LIFE___',  'EST_CADVPERIESB0','${DFILI}/${ENV_PREFIX}_ESID0060_CADVPERIESB0_${PARM_CLODAT_D}.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2560_I4_LIFE___',  'EST_IADVPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_IADVPERICASE_${PARM0_ICLODAT_D}.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2560_I4_LIFE___',  'EST_IRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_IRDVPERICASE_${PARM0_ICLODAT_D}.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2560_I4_LIFE___',  'EST_DLVGTAR','${DFILP}/${ENV_PREFIX}_ESID2040_DLVGTAR_PC_${PARM0_ICLODAT_D}_${CRE_D}.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2560_I4_LIFE___',  'EST_OIRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_OIRDVPERICASE_${PARM0_ICLODAT_D}.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID2560_I4_LIFE___',  'EST_IADVPERICASE_ENTIER','${DFILP}/${ENV_PREFIX}_ESID0560_IADVPERICASE_ENTIER_${PARM0_ICLODAT_D}.dat','I','')
	---- Output
	--insert into BEST..TI17PERMFIL values ('ESID2560_I4_LIFE___',  'EST_TOTGTR','${DFILI}/${ENV_PREFIX}_ESID2560_I4_LIFE___TOTGTR_${PARM0_ICLODAT_D}.dat','O','')
	--insert into BEST..TI17PERMFIL values ('ESID2560_I4_LIFE___',  'EST_TOTGTAR','${DFILI}/${ENV_PREFIX}_ESID2560_I4_LIFE___TOTGTAR_${PARM0_ICLODAT_D}.dat','O','')
	--insert into BEST..TI17PERMFIL values ('ESID2560_I4_LIFE___',  'EST_DLDVGTAR','${DFILI}/${ENV_PREFIX}_ESID2560_I4_LIFE___DLDVGTAR_${PARM0_ICLODAT_D}.dat','O','')
	--insert into BEST..TI17PERMFIL values ('ESID2560_I4_LIFE___',  'EST_DLTOTGTR','${DFILI}/${ENV_PREFIX}_ESID2560_I4_LIFE___DLTOTGTR_${PARM0_ICLODAT_D}.dat','O','')
	--insert into BEST..TI17PERMFIL values ('ESID2560_I4_LIFE___',  'EST_DLTOTGTAR','${DFILI}/${ENV_PREFIX}_ESID2560_I4_LIFE___DLTOTGTAR_${PARM0_ICLODAT_D}.dat','O','')




go





-------------------------------
print	"--	Init  ESID3800"
-------------------------------


	----------  IDF_CT = 'ESID3800_I4_PC_M__'  ---------------------

	delete BEST..TI17PERMFIL where  IDF_CT = 'ESID3800_I4_PC_M__'
	IF NOT EXISTS (SELECT * FROM BEST..TI17FNC where IDF_CT = 'ESID3800_I4_PC_M__' ) insert into BEST..TI17FNC values ( 'ESID3800_I4_PC_M__','')




	-- input
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_M__',  'EST_DLREJGTR','${DFILP}/empty.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_M__',  'EST_DLREJGTAA','${DFILP}/empty.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_M__',  'EST_DLREJGTAR','${DFILP}/empty.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_M__',  'EST_GTA','${DFILP}/${ENV_PREFIX}_ESIX7000_GTA.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_M__',  'EST_GTR','${DFILP}/${ENV_PREFIX}_ESIX7000_GTR.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_M__',  'EST_IGTAR','${DFILP}/${ENV_PREFIX}_ESID0560_IGTAR.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_M__',  'EST_CURGTA','${DFILP}/${ENV_PREFIX}_ESIX7000_CURGTA.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_M__',  'EST_CURGTR','${DFILP}/${ENV_PREFIX}_ESIX7000_CURGTR.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_M__',  'EST_SUBTRS','${DFILI}/${ENV_PREFIX}_ESCJ0060_FSUBTRS_${PARM_CLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_M__',  'EST_FCLIENT','${DFILI}/${ENV_PREFIX}_ESCJ0060_FCLIENT_${PARM_CLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_M__',  'EST_FCPLACC','${DFILP}/${ENV_PREFIX}_ESID0560_FCPLACC_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_M__',  'EST_FCTRGRO','${DFILP}/${ENV_PREFIX}_ESID0560_FCTRGRO_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_M__',  'EST_FCPLACC0','${DFILI}/${ENV_PREFIX}_ESEH1110_FCPLACC0_${PARM_CLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_M__',  'EST_FCTRGRO0','${DFILI}/${ENV_PREFIX}_ESEH1110_FCTRGRO0_${PARM_CLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_M__',  'EST_FSOBBLOB','${DFILI}/${ENV_PREFIX}_ESCJ0060_FSOBBLOB_${PARM_CLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_M__',  'EST_FSSDACTR','${DFILI}/${ENV_PREFIX}_ESCJ0060_FSSDACTR_${PARM_CLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_M__',  'EST_DLTOTGTR','${DFILI}/${ENV_PREFIX}_ESID2560_I4_PC___DLTOTGTR_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_M__',  'EST_FPLACEMT2','${DFILI}/${ENV_PREFIX}_ESEH1110_FPLACEMT2_${PARM_CLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_M__',  'EST_DLTOTGTAA','${DFILI}/${ENV_PREFIX}_ESID2060_I4_PC___DLTOTGTAA_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_M__',  'EST_DLTOTGTAR','${DFILI}/${ENV_PREFIX}_ESID2560_I4_PC___DLTOTGTAR_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_M__',  'EST_DLGTAASNEM','${DFILI}/${ENV_PREFIX}_ESID2100_DLGTAASNEM_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_M__',  'EST_IADVPERICASE0','${DFILI}/${ENV_PREFIX}_ESID1000_IADVPERICASE0_${PARM_CLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_M__',  'EST_IRDVPERICASE0','${DFILP}/${ENV_PREFIX}_ESID1500_IRDVPERICASE0_${PARM_CLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_M__',  'EST_OADVPERICASE0','${DFILI}/${ENV_PREFIX}_ESID1000_OADVPERICASE0_${PARM_CLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_M__',  'EST_ORDVPERICASE0','${DFILI}/${ENV_PREFIX}_ESID1500_ORDVPERICASE0_${PARM_CLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_M__',  'EST_OIADVPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_OIADVPERICASE_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_M__',  'EST_OIRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_OIRDVPERICASE_${PARM0_ICLODAT_D}.dat','I','')
	-- output 
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_M__',  'EST_FSNEMHIST0','${DFILP}/${ENV_PREFIX}_ESID3800_I4_PC___FSNEMHIST0.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_M__',  'EST_FTECLEDASNEM','${DFILP}/${ENV_PREFIX}_ESID3800_I4_PC___FTECLEDASNEM.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_M__',  'EST_FTECLEDA_MTH','${DFILP}/${ENV_PREFIX}_ESID3800_I4_PC___FTECLEDA_MTH.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_M__',  'EST_FTECLEDA_MVT','${DFILP}/${ENV_PREFIX}_ESID3800_I4_PC___FTECLEDA_MVT.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_M__',  'EST_FTECLEDA_REP','${DFILP}/${ENV_PREFIX}_ESID3800_I4_PC___FTECLEDA_REP.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_M__',  'EST_FTECLEDRSNEM','${DFILP}/${ENV_PREFIX}_ESID3800_I4_PC___FTECLEDRSNEM.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_M__',  'EST_FTECLEDR_MVT','${DFILP}/${ENV_PREFIX}_ESID3800_I4_PC___FTECLEDR_MVT.dat','O','')
	--insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_M__',  'EST_FTECLEDA_CUR','${DFILP}/${ENV_PREFIX}_ESID3800_I4_PC_M__FTECLEDA_CUR.dat','O','')
	--insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_M__',  'EST_FTECLEDR_CUR','${DFILP}/${ENV_PREFIX}_ESID3800_I4_PC_M__FTECLEDR_CUR.dat','O','')
	
	----------  IDF_CT = 'ESID3800_I4_LIFE_M__'  ---------------------

	delete BEST..TI17PERMFIL where  IDF_CT = 'ESID3800_I4_LIFE_M__'
	IF NOT EXISTS (SELECT * FROM BEST..TI17FNC where IDF_CT = 'ESID3800_I4_LIFE_M__' ) insert into BEST..TI17FNC values ( 'ESID3800_I4_LIFE_M__','')


	insert into BEST..TI17PERMFIL values ('ESID3800_I4_LIFE_M__',  'EST_DLREJGTR','${DFILP}/empty.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_LIFE_M__',  'EST_DLREJGTAA','${DFILP}/empty.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_LIFE_M__',  'EST_DLREJGTAR','${DFILP}/empty.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_LIFE_M__',  'EST_GTA','${DFILP}/${ENV_PREFIX}_ESIX7000_GTA.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_LIFE_M__',  'EST_GTR','${DFILP}/${ENV_PREFIX}_ESIX7000_GTR.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_LIFE_M__',  'EST_IGTAR','${DFILP}/${ENV_PREFIX}_ESID0560_IGTAR.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_LIFE_M__',  'EST_CURGTA','${DFILP}/${ENV_PREFIX}_ESIX7000_CURGTA.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_LIFE_M__',  'EST_CURGTR','${DFILP}/${ENV_PREFIX}_ESIX7000_CURGTR.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_LIFE_M__',  'EST_SUBTRS','${DFILI}/${ENV_PREFIX}_ESCJ0060_FSUBTRS_${PARM_CLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_LIFE_M__',  'EST_FCLIENT','${DFILI}/${ENV_PREFIX}_ESCJ0060_FCLIENT_${PARM_CLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_LIFE_M__',  'EST_FCPLACC','${DFILP}/${ENV_PREFIX}_ESID0560_FCPLACC_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_LIFE_M__',  'EST_FCTRGRO','${DFILP}/${ENV_PREFIX}_ESID0560_FCTRGRO_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_LIFE_M__',  'EST_FCPLACC0','${DFILI}/${ENV_PREFIX}_ESEH1110_FCPLACC0_${PARM_CLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_LIFE_M__',  'EST_FCTRGRO0','${DFILI}/${ENV_PREFIX}_ESEH1110_FCTRGRO0_${PARM_CLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_LIFE_M__',  'EST_FSOBBLOB','${DFILI}/${ENV_PREFIX}_ESCJ0060_FSOBBLOB_${PARM_CLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_LIFE_M__',  'EST_FSSDACTR','${DFILI}/${ENV_PREFIX}_ESCJ0060_FSSDACTR_${PARM_CLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_LIFE_M__',  'EST_DLTOTGTR','${DFILI}/${ENV_PREFIX}_ESID2560_I4_LIFE___DLTOTGTR_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_LIFE_M__',  'EST_FPLACEMT2','${DFILI}/${ENV_PREFIX}_ESEH1110_FPLACEMT2_${PARM_CLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_LIFE_M__',  'EST_DLTOTGTAA','${DFILI}/${ENV_PREFIX}_ESID2060_I4_LIFE___DLTOTGTAA_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_LIFE_M__',  'EST_DLTOTGTAR','${DFILI}/${ENV_PREFIX}_ESID2560_I4_LIFE___DLTOTGTAR_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_LIFE_M__',  'EST_DLGTAASNEM','${DFILP}/empty.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_LIFE_M__',  'EST_IADVPERICASE0','${DFILI}/${ENV_PREFIX}_ESID1000_IADVPERICASE0_${PARM_CLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_LIFE_M__',  'EST_IRDVPERICASE0','${DFILP}/${ENV_PREFIX}_ESID1500_IRDVPERICASE0_${PARM_CLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_LIFE_M__',  'EST_OADVPERICASE0','${DFILI}/${ENV_PREFIX}_ESID1000_OADVPERICASE0_${PARM_CLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_LIFE_M__',  'EST_ORDVPERICASE0','${DFILI}/${ENV_PREFIX}_ESID1500_ORDVPERICASE0_${PARM_CLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_LIFE_M__',  'EST_OIADVPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_OIADVPERICASE_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_LIFE_M__',  'EST_OIRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_OIRDVPERICASE_${PARM0_ICLODAT_D}.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESID3800_I4_LIFE_M__',  'EST_FTECLEDA','${DFILP}/${ENV_PREFIX}_ESID3800_I4_LIFE___FTECLEDA.dat','O','')
	--insert into BEST..TI17PERMFIL values ('ESID3800_I4_LIFE_M__',  'EST_FTECLEDR','${DFILP}/${ENV_PREFIX}_ESID3800_I4_LIFE___FTECLEDR.dat','O','')
	                                                        
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_LIFE_M__',  'EST_FSNEMHIST0','${DFILP}/${ENV_PREFIX}_ESID3800_I4_LIFE___FSNEMHIST0.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_LIFE_M__',  'EST_FTECLEDASNEM','${DFILP}/${ENV_PREFIX}_ESID3800_I4_LIFE___FTECLEDASNEM.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_LIFE_M__',  'EST_FTECLEDA_MTH','${DFILP}/${ENV_PREFIX}_ESID3800_I4_LIFE___FTECLEDA_MTH.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_LIFE_M__',  'EST_FTECLEDA_MVT','${DFILP}/${ENV_PREFIX}_ESID3800_I4_LIFE___FTECLEDA_MVT.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_LIFE_M__',  'EST_FTECLEDA_REP','${DFILP}/${ENV_PREFIX}_ESID3800_I4_LIFE___FTECLEDA_REP.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_LIFE_M__',  'EST_FTECLEDRSNEM','${DFILP}/${ENV_PREFIX}_ESID3800_I4_LIFE___FTECLEDRSNEM.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_LIFE_M__',  'EST_FTECLEDR_MVT','${DFILP}/${ENV_PREFIX}_ESID3800_I4_LIFE___FTECLEDR_MVT.dat','O','')
	--insert into BEST..TI17PERMFIL values ('ESID3800_I4_LIFE_M__',  'EST_FTECLEDA_CUR','${DFILP}/${ENV_PREFIX}_ESID3800_I4_LIFE_M__FTECLEDA_CUR.dat','O','')
	--insert into BEST..TI17PERMFIL values ('ESID3800_I4_LIFE_M__',  'EST_FTECLEDR_CUR','${DFILP}/${ENV_PREFIX}_ESID3800_I4_LIFE_M__FTECLEDR_CUR.dat','O','')
                                                                                                                               

	----------   C  ---------------------
	----------  IDF_CT = 'ESID3800_I4_PC_C__'  ---------------------

	delete BEST..TI17PERMFIL where  IDF_CT = 'ESID3800_I4_PC_C__'
	IF NOT EXISTS (SELECT * FROM BEST..TI17FNC where IDF_CT = 'ESID3800_I4_PC_C__' ) insert into BEST..TI17FNC values ( 'ESID3800_I4_PC_C__','')


	-- input
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_C__',  'EST_DLREJGTR','${DFILP}/empty.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_C__',  'EST_DLREJGTAA','${DFILP}/empty.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_C__',  'EST_DLREJGTAR','${DFILP}/empty.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_C__',  'EST_GTA','${DFILP}/${ENV_PREFIX}_ESIX7000_GTA.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_C__',  'EST_GTR','${DFILP}/${ENV_PREFIX}_ESIX7000_GTR.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_C__',  'EST_IGTAR','${DFILP}/${ENV_PREFIX}_ESID0560_IGTAR.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_C__',  'EST_CURGTA','${DFILP}/${ENV_PREFIX}_ESIX7000_CURGTA.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_C__',  'EST_CURGTR','${DFILP}/${ENV_PREFIX}_ESIX7000_CURGTR.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_C__',  'EST_SUBTRS','${DFILI}/${ENV_PREFIX}_ESCJ0060_FSUBTRS_${PARM_CLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_C__',  'EST_FCLIENT','${DFILI}/${ENV_PREFIX}_ESCJ0060_FCLIENT_${PARM_CLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_C__',  'EST_FCPLACC','${DFILP}/${ENV_PREFIX}_ESID0560_FCPLACC_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_C__',  'EST_FCTRGRO','${DFILP}/${ENV_PREFIX}_ESID0560_FCTRGRO_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_C__',  'EST_FCPLACC0','${DFILI}/${ENV_PREFIX}_ESEH1110_FCPLACC0_${PARM_CLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_C__',  'EST_FCTRGRO0','${DFILI}/${ENV_PREFIX}_ESEH1110_FCTRGRO0_${PARM_CLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_C__',  'EST_FSOBBLOB','${DFILI}/${ENV_PREFIX}_ESCJ0060_FSOBBLOB_${PARM_CLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_C__',  'EST_FSSDACTR','${DFILI}/${ENV_PREFIX}_ESCJ0060_FSSDACTR_${PARM_CLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_C__',  'EST_DLTOTGTR','${DFILI}/${ENV_PREFIX}_ESID2560_I4_PC___DLTOTGTR_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_C__',  'EST_FPLACEMT2','${DFILI}/${ENV_PREFIX}_ESEH1110_FPLACEMT2_${PARM_CLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_C__',  'EST_DLTOTGTAA','${DFILI}/${ENV_PREFIX}_ESID2060_I4_PC___DLTOTGTAA_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_C__',  'EST_DLTOTGTAR','${DFILI}/${ENV_PREFIX}_ESID2560_I4_PC___DLTOTGTAR_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_C__',  'EST_DLGTAASNEM','${DFILI}/${ENV_PREFIX}_ESID2100_DLGTAASNEM_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_C__',  'EST_IADVPERICASE0','${DFILI}/${ENV_PREFIX}_ESID1000_IADVPERICASE0_${PARM_CLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_C__',  'EST_IRDVPERICASE0','${DFILP}/${ENV_PREFIX}_ESID1500_IRDVPERICASE0_${PARM_CLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_C__',  'EST_OADVPERICASE0','${DFILI}/${ENV_PREFIX}_ESID1000_OADVPERICASE0_${PARM_CLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_C__',  'EST_ORDVPERICASE0','${DFILI}/${ENV_PREFIX}_ESID1500_ORDVPERICASE0_${PARM_CLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_C__',  'EST_OIADVPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_OIADVPERICASE_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_C__',  'EST_OIRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_OIRDVPERICASE_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_C__',  'EST_FTECLEDA','${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDA.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_C__',  'EST_FTECLEDR','${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDR.dat','O','')

	-- output                                             
	--insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_C__',  'EST_FSNEMHIST0','${DFILP}/${ENV_PREFIX}_ESID3800_I4_PC___FSNEMHIST0.dat','O','')
	--insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_C__',  'EST_FTECLEDASNEM','${DFILP}/${ENV_PREFIX}_ESID3800_I4_PC___FTECLEDASNEM.dat','O','')
	--insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_C__',  'EST_FTECLEDA_MTH','${DFILP}/${ENV_PREFIX}_ESID3800_I4_PC___FTECLEDA_MTH.dat','O','')
	--insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_C__',  'EST_FTECLEDA_MVT','${DFILP}/${ENV_PREFIX}_ESID3800_I4_PC___FTECLEDA_MVT.dat','O','')
	--insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_C__',  'EST_FTECLEDA_REP','${DFILP}/${ENV_PREFIX}_ESID3800_I4_PC___FTECLEDA_REP.dat','O','')
	--insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_C__',  'EST_FTECLEDRSNEM','${DFILP}/${ENV_PREFIX}_ESID3800_I4_PC___FTECLEDRSNEM.dat','O','')
	--insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_C__',  'EST_FTECLEDR_MVT','${DFILP}/${ENV_PREFIX}_ESID3800_I4_PC___FTECLEDR_MVT.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_C__',  'EST_FTECLEDA_CUR','${DFILP}/${ENV_PREFIX}_ESID3800_I4_PC___FTECLEDA_CUR.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESID3800_I4_PC_C__',  'EST_FTECLEDR_CUR','${DFILP}/${ENV_PREFIX}_ESID3800_I4_PC___FTECLEDR_CUR.dat','O','')

go



-------------------------------
print	"--      Init  ESID8700"
-------------------------------


	----------  IDF_CT = 'ESID8700_I4_PC___'  ---------------------

	delete BEST..TI17PERMFIL where  IDF_CT = 'ESID8700_I4_PC__'
	IF NOT EXISTS (SELECT * FROM BEST..TI17FNC where IDF_CT = 'ESID8700_I4_PC__' ) insert into BEST..TI17FNC values ( 'ESID8700_I4_PC__','')

-- Input	                                                        
	insert into BEST..TI17PERMFIL values ('ESID8700_I4_PC__',  'EST_FTECLEDA_CUR','${DFILP}/${ENV_PREFIX}_ESID3800_I4_PC___FTECLEDA_CUR.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID8700_I4_PC__',  'EST_FTECLEDA_MTH','${DFILP}/${ENV_PREFIX}_ESID3800_I4_PC___FTECLEDA_MTH.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID8700_I4_PC__',  'EST_FTECLEDA_MVT','${DFILP}/${ENV_PREFIX}_ESID3800_I4_PC___FTECLEDA_MVT.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID8700_I4_PC__',  'EST_FTECLEDA_REP','${DFILP}/${ENV_PREFIX}_ESID3800_I4_PC___FTECLEDA_REP.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID8700_I4_PC__',  'EST_FTECLEDR_CUR','${DFILP}/${ENV_PREFIX}_ESID3800_I4_PC___FTECLEDR_CUR.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID8700_I4_PC__',  'EST_FTECLEDR_MVT','${DFILP}/${ENV_PREFIX}_ESID3800_I4_PC___FTECLEDR_MVT.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID8700_I4_PC__',  'EST_SUBTRS_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FSUBTRS_TXT_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID8700_I4_PC__',  'EST_SUBTRSESBPROP_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_SUBTRSESBPROP_TXT_${PARM0_ICLODAT_D}.dat','I','')
-- Output	                                                       
	insert into BEST..TI17PERMFIL values ('ESID8700_I4_PC__',  'EST_FTECLEDA','${DFILP}/${ENV_PREFIX}_ESID8700_I4_PC___FTECLEDA.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESID8700_I4_PC__',  'EST_FTECLEDR','${DFILP}/${ENV_PREFIX}_ESID8700_I4_PC___FTECLEDR.dat','O','')


	----------  IDF_CT = 'ESID8700_I4_LIFE___'  ---------------------

	delete BEST..TI17PERMFIL where  IDF_CT = 'ESID8700_I4_LIFE___'
	IF NOT EXISTS (SELECT * FROM BEST..TI17FNC where IDF_CT = 'ESID8700_I4_LIFE___' ) insert into BEST..TI17FNC values ( 'ESID8700_I4_LIFE___','')



---- Input	                                                        
--	insert into BEST..TI17PERMFIL values ('ESID8700_I4_LIFE___',  'EST_FTECLEDA_CUR','${DFILP}/empty.dat','I','')
--	insert into BEST..TI17PERMFIL values ('ESID8700_I4_LIFE___',  'EST_FTECLEDA_MTH','${DFILP}/${ENV_PREFIX}_ESID3800_I4_LIFE___FTECLEDA_MTH.dat','I','')
--	insert into BEST..TI17PERMFIL values ('ESID8700_I4_LIFE___',  'EST_FTECLEDA_MVT','${DFILP}/${ENV_PREFIX}_ESID3800_I4_LIFE___FTECLEDA_MVT.dat','I','')
--	insert into BEST..TI17PERMFIL values ('ESID8700_I4_LIFE___',  'EST_FTECLEDA_REP','${DFILP}/${ENV_PREFIX}_ESID3800_I4_LIFE___FTECLEDA_REP.dat','I','')
--	insert into BEST..TI17PERMFIL values ('ESID8700_I4_LIFE___',  'EST_FTECLEDR_CUR','${DFILP}/empty.dat','I','')
--	insert into BEST..TI17PERMFIL values ('ESID8700_I4_LIFE___',  'EST_FTECLEDR_MVT','${DFILP}/${ENV_PREFIX}_ESID3800_I4_LIFE___FTECLEDR_MVT.dat','I','')
--	insert into BEST..TI17PERMFIL values ('ESID8700_I4_LIFE___',  'EST_SUBTRS_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FSUBTRS_TXT_${PARM0_ICLODAT_D}.dat','I','')
--	insert into BEST..TI17PERMFIL values ('ESID8700_I4_LIFE___',  'EST_SUBTRSESBPROP_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_SUBTRSESBPROP_TXT_${PARM0_ICLODAT_D}.dat','I','')
---- Output	                                                        
--	insert into BEST..TI17PERMFIL values ('ESID8700_I4_LIFE___',  'EST_FTECLEDA','${DFILP}/${ENV_PREFIX}_ESID8700_I4_LIFE___FTECLEDA.dat','O','')
--	insert into BEST..TI17PERMFIL values ('ESID8700_I4_LIFE___',  'EST_FTECLEDR','${DFILP}/${ENV_PREFIX}_ESID8700_I4_LIFE___FTECLEDR.dat','O','')


go

-- /scordata_dcvcnvobbatch/ubeu/perm/C_ESID2500_DLREGTR_20200331.dat
-----------------------------------
--print	"--      Init  ESID3870"
-----------------------------------

	delete BEST..TI17PERMFIL where  IDF_CT = 'ESID2660'
	IF NOT EXISTS (SELECT * FROM BEST..TI17FNC where IDF_CT = 'ESID2660' ) insert into BEST..TI17FNC values ( 'ESID2660','')


	
	insert into BEST..TI17PERMFIL values ('ESID2660',  'EST_DLREGTR','${DFILP}/${ENV_PREFIXO}_ESID2500_DLREGTR_${PARM0_ICLODAT_D}.dat','IO','')
	insert into BEST..TI17PERMFIL values ('ESID2660',  'EST_DLREGTR_LIFE','${DFILP}/${ENV_PREFIX}_ESID2500_I4_LIFE___DLREGTR_${PARM0_ICLODAT_D}.dat','IO','')
	insert into BEST..TI17PERMFIL values ('ESID2660',  'EST_DLREGTR_PC','${DFILP}/${ENV_PREFIX}_ESID2500_I4_PC___DLREGTR_${PARM0_ICLODAT_D}.dat','IO','')


	insert into BEST..TI17PERMFIL values ('ESID2660',  'EST_DLRIGTAA','${DFILP}/${ENV_PREFIXO}_ESID0560_DLRIGTAA_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2660',  'EST_DLRIGTAA_LIFE','${DFILP}/${ENV_PREFIX}_ESID0560_I4_LIFE___DLRIGTAA_${PARM0_ICLODAT_D}.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESID2660',  'EST_DLRIGTAA_PC','${DFILP}/${ENV_PREFIX}_ESID0560_I4_PC___DLRIGTAA_${PARM0_ICLODAT_D}.dat','O','')

	insert into BEST..TI17PERMFIL values ('ESID2660',  'EST_DLREMAJGTR','${DFILP}/${ENV_PREFIXO}_ESID2500_DLREMAJGTR_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2660',  'EST_DLREMAJGTR_LIFE','${DFILP}/${ENV_PREFIX}_ESID2500_I4_LIFE___DLREMAJGTR_${PARM0_ICLODAT_D}.dat','IO','')
	insert into BEST..TI17PERMFIL values ('ESID2660',  'EST_DLREMAJGTR_PC','${DFILP}/${ENV_PREFIX}_ESID2500_I4_PC___DLREMAJGTR_${PARM0_ICLODAT_D}.dat','IO','')

	insert into BEST..TI17PERMFIL values ('ESID2660',  'EST_DLDVGTR','${DFILI}/${ENV_PREFIXO}_ESID2550_DLDVGTR_${ICLODAT}.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESID2660',  'EST_DLDVGTR_LIFE','${DFILI}/${ENV_PREFIX}_ESID2550_I4_LIFE___DLDVGTR_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2660',  'EST_DLDVGTR_PC','${DFILI}/${ENV_PREFIX}_ESID2550_I4_PC___DLDVGTR_${PARM0_ICLODAT_D}.dat','I','')

	insert into BEST..TI17PERMFIL values ('ESID2660',  'EST_DLEIGTAA','${DFILI}/${ENV_PREFIXO}_ESID2550_DLEIGTAA_${ICLODAT}.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESID2660',  'EST_DLEIGTAA_LIFE','${DFILI}/${ENV_PREFIX}_ESID2550_I4_LIFE___DLEIGTAA_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2660',  'EST_DLEIGTAA_PC','${DFILI}/${ENV_PREFIX}_ESID2550_I4_PC___DLEIGTAA_${PARM0_ICLODAT_D}.dat','I','')

	insert into BEST..TI17PERMFIL values ('ESID2660',  'EST_DLRGTAA','${DFILI}/${ENV_PREFIXO}_ESID2050_DLRGTAA_${ICLODAT}.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESID2660',  'EST_DLRGTAA_LIFE','${DFILI}/${ENV_PREFIX}_ESID2050_I4_LIFE___DLRGTAA_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2660',  'EST_DLRGTAA_PC','${DFILI}/${ENV_PREFIX}_ESID2050_I4_PC___DLRGTAA_${PARM0_ICLODAT_D}.dat','I','')

	insert into BEST..TI17PERMFIL values ('ESID2660',  'EST_DLRIGTAANOS','${DFILI}/${ENV_PREFIXO}_ESID2550_DLRIGTAANOS_${ICLODAT}.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESID2660',  'EST_DLRIGTAANOS_LIFE','${DFILI}/${ENV_PREFIX}_ESID2550_I4_LIFE___DLRIGTAANOS_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2660',  'EST_DLRIGTAANOS_PC','${DFILI}/${ENV_PREFIX}_ESID2550_I4_PC___DLRIGTAANOS_${PARM0_ICLODAT_D}.dat','I','')

	insert into BEST..TI17PERMFIL values ('ESID2660',  'EST_DLREMAJGTAR','${DFILP}/${ENV_PREFIXO}_ESID2500_DLREMAJGTAR_${PARM0_ICLODAT_D}.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESID2660',  'EST_DLREMAJGTAR_LIFE','${DFILP}/${ENV_PREFIX}_ESID2500_I4_LIFE___DLREMAJGTAR_${PARM0_ICLODAT_D}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESID2660',  'EST_DLREMAJGTAR_PC','${DFILP}/${ENV_PREFIX}_ESID2500_I4_PC___DLREMAJGTAR_${PARM0_ICLODAT_D}.dat','I','')


	insert into BEST..TI17PERMFIL values ('ESID2660',  'EST_DLREGTAR','${DFILP}/${ENV_PREFIXO}_ESID2500_DLREGTAR_${PARM0_ICLODAT_D}.dat', 'O', ' ' )
	insert into BEST..TI17PERMFIL values ('ESID2660',  'EST_DLREGTAR_LIFE','${DFILP}/${ENV_PREFIX}_ESID2500_I4_LIFE___DLREGTAR_${PARM0_ICLODAT_D}.dat', 'I', ' ' )
	insert into BEST..TI17PERMFIL values ('ESID2660',  'EST_DLREGTAR_PC','${DFILP}/${ENV_PREFIX}_ESID2500_I4_PC___DLREGTAR_${PARM0_ICLODAT_D}.dat', 'I', ' ' )

				
--insert into BEST..TI17PERMFIL values ('ESID2660',  'EST_DLDVGTAR','${DFILI}/${ENV_PREFIXO}_ESID2560_DLDVGTAR_${ICLODAT}.dat','O','')
--insert into BEST..TI17PERMFIL values ('ESID2660',  'EST_DLDVGTAR_LIFE','${DFILI}/${ENV_PREFIX}_ESID2560_I4_LIFE___DLDVGTAR_${PARM0_ICLODAT_D}.dat','I','')
--insert into BEST..TI17PERMFIL values ('ESID2660',  'EST_DLDVGTAR_PC','${DFILI}/${ENV_PREFIX}_ESID2560_I4_PC___DLDVGTAR_${PARM0_ICLODAT_D}.dat','I','')

--insert into BEST..TI17PERMFIL values ('ESID2660',  'EST_DLTOTGTAA','${DFILI}/${ENV_PREFIXO}_ESID2060_DLTOTGTAA_${PARM0_ICLODAT_D}.dat','O','')
--insert into BEST..TI17PERMFIL values ('ESID2660',  'EST_DLTOTGTAA_LIFE','${DFILI}/${ENV_PREFIX}_ESID2060_I4_LIFE___DLTOTGTAA_${PARM0_ICLODAT_D}.dat','I','')
--insert into BEST..TI17PERMFIL values ('ESID2660',  'EST_DLTOTGTAA_PC','${DFILI}/${ENV_PREFIX}_ESID2060_I4_PC___DLTOTGTAA_${PARM0_ICLODAT_D}.dat','I','')

--insert into BEST..TI17PERMFIL values ('ESID2660',  'EST_DLTOTGTAR','${DFILI}/${ENV_PREFIXO}_ESID2560_DLTOTGTAR_${PARM0_ICLODAT_D}.dat','O','')
--insert into BEST..TI17PERMFIL values ('ESID2660',  'EST_DLTOTGTAR_LIFE','${DFILI}/${ENV_PREFIX}_ESID2560_I4_LIFE___DLTOTGTAR_${PARM0_ICLODAT_D}.dat','I','')
--insert into BEST..TI17PERMFIL values ('ESID2660',  'EST_DLTOTGTAR_PC','${DFILI}/${ENV_PREFIX}_ESID2560_I4_PC___DLTOTGTAR_${PARM0_ICLODAT_D}.dat','I','')

--insert into BEST..TI17PERMFIL values ('ESID2660',  'EST_DLTOTGTR','${DFILI}/${ENV_PREFIXO}_ESID2560_DLTOTGTR_${PARM0_ICLODAT_D}.dat','O','')
--insert into BEST..TI17PERMFIL values ('ESID2660',  'EST_DLTOTGTR_LIFE','${DFILI}/${ENV_PREFIX}_ESID2560_I4_LIFE___DLTOTGTR_${PARM0_ICLODAT_D}.dat','I','')
--insert into BEST..TI17PERMFIL values ('ESID2660',  'EST_DLTOTGTR_PC','${DFILI}/${ENV_PREFIX}_ESID2560_I4_PC___DLTOTGTR_${PARM0_ICLODAT_D}.dat','I','')

--insert into BEST..TI17PERMFIL values ('ESID2660',  'EST_DLTOTITGTAR','${DFILI}/${ENV_PREFIXO}_ESID2060_DLTOTITGTAR_${ICLODAT}.dat','O','')
--insert into BEST..TI17PERMFIL values ('ESID2660',  'EST_DLTOTITGTAR_LIFE','${DFILI}/${ENV_PREFIX}_ESID2060_I4_LIFE___DLTOTITGTAR_${PARM0_ICLODAT_D}.dat','I','')
--insert into BEST..TI17PERMFIL values ('ESID2660',  'EST_DLTOTITGTAR_PC','${DFILI}/${ENV_PREFIX}_ESID2060_I4_PC___DLTOTITGTAR_${PARM0_ICLODAT_D}.dat','I','')

--insert into BEST..TI17PERMFIL values ('ESID2660',  'EST_TOTGTAA','${DFILI}/${ENV_PREFIXO}_ESID2060_TOTGTAA_${ICLODAT}.dat','O','')
--insert into BEST..TI17PERMFIL values ('ESID2660',  'EST_TOTGTAA_LIFE','${DFILI}/${ENV_PREFIX}_ESID2060_I4_LIFE___TOTGTAA_${PARM0_ICLODAT_D}.dat','I','')
--insert into BEST..TI17PERMFIL values ('ESID2660',  'EST_TOTGTAA_PC','${DFILI}/${ENV_PREFIX}_ESID2060_I4_PC___TOTGTAA_${PARM0_ICLODAT_D}.dat','I','')

--insert into BEST..TI17PERMFIL values ('ESID2660',  'EST_TOTGTAR','${DFILI}/${ENV_PREFIXO}_ESID2560_TOTGTAR_${ICLODAT}.dat','O','')
--insert into BEST..TI17PERMFIL values ('ESID2660',  'EST_TOTGTAR_LIFE','${DFILI}/${ENV_PREFIX}_ESID2560_I4_LIFE___TOTGTAR_${PARM0_ICLODAT_D}.dat','I','')
--insert into BEST..TI17PERMFIL values ('ESID2660',  'EST_TOTGTAR_PC','${DFILI}/${ENV_PREFIX}_ESID2560_I4_PC___TOTGTAR_${PARM0_ICLODAT_D}.dat','I','')

--insert into BEST..TI17PERMFIL values ('ESID2660',  'EST_TOTGTR','${DFILI}/${ENV_PREFIXO}_ESID2560_TOTGTR_${ICLODAT}.dat','O','')
--insert into BEST..TI17PERMFIL values ('ESID2660',  'EST_TOTGTR_LIFE','${DFILI}/${ENV_PREFIX}_ESID2560_I4_LIFE___TOTGTR_${PARM0_ICLODAT_D}.dat','I','')
--insert into BEST..TI17PERMFIL values ('ESID2660',  'EST_TOTGTR_PC','${DFILI}/${ENV_PREFIX}_ESID2560_I4_PC___TOTGTR_${PARM0_ICLODAT_D}.dat','I','') 


go

----
---- TABLE INSERT STATEMENTS
----
--delete BEST..TI17PERMFIL where  PERMFIL_CT = 'EST_SUBTRS_TXT' and IDF_CT in (  'ESID8700',  'ESPT0000' , 'ESCJ0060')
--
--INSERT INTO BEST..TI17PERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) 
--        VALUES ( 'ESCJ0060', 'EST_SUBTRS_TXT', '${DFILP}/${PCH}ESCJ0060_FSUBTRS_TXT_${PARM0_ICLODAT_D}.dat', 'O', ' ' )
--go
--INSERT INTO BEST..TI17PERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) 
--        VALUES ( 'ESPT0000', 'EST_SUBTRS_TXT', '${DFILP}/${ENV_PREFIX}_ESCJ0060_FSUBTRS_TXT_${PARM_ICLODAT_D}.dat', 'I', ' ' )
--go
--INSERT INTO BEST..TI17PERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) 
--        VALUES ( 'ESID8700', 'EST_SUBTRS_TXT', '${DFILP}/${ENV_PREFIX}_ESCJ0060_FSUBTRS_TXT_${PARM0_ICLODAT_D}.dat', 'I', ' ' )
--go
--
--
--delete BEST..TI17PERMFIL where  PERMFIL_CT = 'EST_SUBTRSESBPROP_TXT' and IDF_CT in (  'ESID8700',  'ESPT0000' , 'ESCJ0060')
--
--
--INSERT INTO BEST..TI17PERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) 
--        VALUES ( 'ESCJ0060', 'EST_SUBTRSESBPROP_TXT', '${DFILP}/${PCH}ESCJ0060_SUBTRSESBPROP_TXT_${PARM0_ICLODAT_D}.dat', 'O', ' ' )
--go
--INSERT INTO BEST..TI17PERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) 
--        VALUES ( 'ESPT0000', 'EST_SUBTRSESBPROP_TXT', '${DFILP}/${ENV_PREFIX}_ESCJ0060_SUBTRSESBPROP_TXT_${PARM_ICLODAT_D}.dat', 'I', ' ' )
--go
--INSERT INTO BEST..TI17PERMFIL ( IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL ) 
--        VALUES ( 'ESID8700', 'EST_SUBTRSESBPROP_TXT', '${DFILP}/${ENV_PREFIX}_ESCJ0060_SUBTRSESBPROP_TXT_${PARM0_ICLODAT_D}.dat', 'I', ' ' )
--go
--
--update BEST..TI17PERMFIL 
--set PATHPATTRN_LL = str_replace(PATHPATTRN_LL,'${ICLODAT}','${PARM0_ICLODAT_D}')
--where    IDF_CT like 'ESID3800'
--
--go

