-------------------------------
--      Init  ESFD2040
-------------------------------


	delete BEST..TI17PErMFIL Where IDF_CT ='ESFD2040'
	delete BEST..TI17REQCHN Where   IDF_CT = 'ESFD2040'
	delete BEST..TI17CHN  Where CHAIN_CT='ESFD2040'
	delete BEST..TI17FNC Where IDF_CT  ='ESFD2040'
	insert into BEST..TI17CHN values ('ESFD2040',  '')
	insert into BEST..TI17FNC values ('ESFD2040',  '')

				 

--Input files

	insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_FGRP','${DFILI}/${ENV_PREFIX}_ESCJ0060_FGRP_${CLODAT}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_FACMTRSH','${DFILI}/${ENV_PREFIX}_ESCJ0060_FACMTRSH_${CLODAT}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_SEGRATANO','${DFILI}/${ENV_PREFIX}_ESFD2070_SEGRATANO_${CLODAT}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_SUBTRSASSO','${DFILI}/${ENV_PREFIX}_ESCJ0060_FSUBTRSASSO_${CLODAT}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_IARVPERICASE0','${DFILI}/${ENV_PREFIX}_ESFD2070_IARVPERICASE0${IT}_${CLODAT}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_SUBTRSESBPROP','${DFILI}/${ENV_PREFIX}_ESCJ0060_FSUBTRSESBPROP_${CLODAT}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_SUBTRS','${DFILI}/${ENV_PREFIX}_ESCJ0060_FSUBTRS_${CLODAT}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_FACCPAR0','${DFILI}/${ENV_PREFIX}_ESID0060_FACCPAR0_${CLODAT}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_IARVPERICASE4','${DFILI}/${ENV_PREFIX}_ESFD2070_IARVPERICASE4${IT}_${CLODAT}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_FTRSLNK','${DFILI}/${ENV_PREFIX}_ESCJ0060_FTRSLNK_${CLODAT}.dat','I','')
	

	insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_SRGTC','${DFILI}/${ENV_PREFIX}_ESFD2030_SRGTC${IT}_${CLODAT}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_IAVPERICASE','${DFILI}/${ENV_PREFIX}_ESID0560_IAVPERICASE_${ICLODAT2}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_IRVPERICASE','${DFILI}/${ENV_PREFIX}_ESID0560_IRVPERICASE_${ICLODAT2}.dat','I','')

	insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_CPLIFDRI','${DFILI}/${ENV_PREFIX}_ESFD2030_CPLIFDRI${IT}_${CLODAT}.dat','O','')

	insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURQUOT.dat','I','')
	--insert into BEST..TI17PErMFIL values ('ESFD2040',  'EST_FGP','${DFILI}/${ENV_PREFIX}_ESCJ0060_FGP_${CLODAT}.dat','I','')
	insert into BEST..TI17PErMFIL values ('ESFD2040',  'EST_SUBTS','${DFILI}/${ENV_PREFIX}_ESCJ0060_FSUBTS_${CLODAT}.dat','I','')
	insert into BEST..TI17PErMFIL values ('ESFD2040',  'EST_FSUBSID','${DFILI}/${ENV_PREFIX}_ESCJ0060_FSUBSID_${CLODAT}.dat','I','')
	insert into BEST..TI17PErMFIL values ('ESFD2040',  'EST_FTSLNK','${DFILI}/${ENV_PREFIX}_ESCJ0060_FTSLNK_${CLODAT}.dat','I','')
	insert into BEST..TI17PErMFIL values ('ESFD2040',  'EST_FACCPA0','${DFILI}/${ENV_PREFIX}_ESID0060_FACCPA0_${CLODAT}.dat','I','')
	--insert into BEST..TI17PErMFIL values ('ESFD2040',  'EST_FACMTSH','${DFILI}/${ENV_PREFIX}_ESCJ0060_FACMTSH_${CLODAT}.dat','I','')
	insert into BEST..TI17PErMFIL values ('ESFD2040',  'EST_FBANTECL','${DFILI}/${ENV_PREFIX}_ESCJ0060_FBANTECL_${CLODAT}.dat','I','')
	insert into BEST..TI17PErMFIL values ('ESFD2040',  'EST_FCPLACC','${DFILP}/${ENV_PREFIX}_ESID0560_FCPLACC_${ICLODAT2}.dat','I','')
	--insert into BEST..TI17PErMFIL values ('ESFD2040',  'EST_SEGATANO','${DFILI}/${ENV_PREFIX}_ESFD2070_SEGATANO_${CLODAT}.dat','I','')
	insert into BEST..TI17PErMFIL values ('ESFD2040',  'EST_CPLIFDI','${DFILI}/${ENV_PREFIX}_ESFD2030_CPLIFDI${IT}_${CLODAT}.dat','I','')
	insert into BEST..TI17PErMFIL values ('ESFD2040',  'EST_SUBTSASSO','${DFILI}/${ENV_PREFIX}_ESCJ0060_FSUBTSASSO_${CLODAT}.dat','I','')
	--insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_CRIBLEANO','${DFILI}/${ENV_PREFIX}_ESFD2070_CRIBLEANO${IT}_${CLODAT}.dat','I','')
	insert into BEST..TI17PErMFIL values ('ESFD2040',  'EST_FVPLACEMT','${DFILI}/${ENV_PREFIX}_ESFD2070_FVPLACEMT${IT}_${CLODAT}.dat','I','')
	--insert into BEST..TI17PErMFIL values ('ESFD2040',  'EST_LIFENDCPT','${DFILI}/${ENV_PREFIX}_ESFD2070_LIFENDCPT${IT}_${CLODAT}.dat','I','')
	--insert into BEST..TI17PErMFIL values ('ESFD2040',  'EST_LIFTANSF','${DFILI}/${ENV_PREFIX}_ESFD2030_LIFTANSF${IT}_${CLODAT}.dat','I','')
	insert into BEST..TI17PErMFIL values ('ESFD2040',  'EST_VLIFEST195','${DFILI}/${ENV_PREFIX}_ESFD2030_VLIFEST195${IT}_${CLODAT}.dat','I','')
	insert into BEST..TI17PErMFIL values ('ESFD2040',  'EST_LIFESTNOACC','${DFILI}/${ENV_PREFIX}_ESFD2070_LIFESTNOACC${IT}_${CLODAT}.dat','I','')
	insert into BEST..TI17PErMFIL values ('ESFD2040',  'EST_SUBTSESBPOP','${DFILI}/${ENV_PREFIX}_ESCJ0060_FSUBTSESBPOP_${CLODAT}.dat','I','')
	insert into BEST..TI17PErMFIL values ('ESFD2040',  'EST_IAVPEICASE0','${DFILI}/${ENV_PREFIX}_ESFD2070_IAVPEICASE0${IT}_${CLODAT}.dat','I','')
	insert into BEST..TI17PErMFIL values ('ESFD2040',  'EST_IAVPEICASE4','${DFILI}/${ENV_PREFIX}_ESFD2070_IAVPEICASE4${IT}_${CLODAT}.dat','I','')

--Output files
	--insert into BEST..TI17PErMFIL values ('ESFD2040',  'EST_SGT_VENTIL','${DFILI}/${ENV_PREFIX}_ESFD2040_SGT_VENTIL${IT}_${ICLODAT2}.dat','O','')
	--insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_LIFTRANSFR','${DFILI}/${ENV_PREFIX}_ESFD2030_LIFTRANSFR${IT}_${CLODAT}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_SRGTR_VENTIL','${DFILI}/${ENV_PREFIX}_ESFD2040_SRGTR_VENTIL${IT}_${ICLODAT2}.dat','O','')
	--insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_DLVGTAR_PC','${DFILP}/${ENV_PREFIX}_ESFD2040_DLVGTAR_PC${IT}_${ICLODAT2}_${CRE_D}.dat','O','')
	--insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_DLVGTAR','${DFILP}/${ENV_PREFIX}_ESFD2040_DLVGTAR_PC_${ICLODAT}_${CRE_D}.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_SRGTEF_SRV','${DFILI}/${ENV_PREFIX}_ESFD2040_SRGTEF_SRV_${MODE}${IT}_${BALSHTYEA}1231.dat','O','')


	--insert into BEST..TI17PErMFIL values ('ESFD2040',  'EST_SIGNANO','${DFILI}/${ENV_PREFIX}_ESFD2040_SIGNANO${IT}_${ICLODAT2}.dat','O','')
	insert into BEST..TI17PErMFIL values ('ESFD2040',  'EST_SIGNANO','${DFILI}/${ENV_PREFIX}_ESFD2040_SIGNANO_${MODE}${IT}_${ICLODAT2}.dat','O','')

	--insert into BEST..TI17PErMFIL values ('ESFD2040',  'EST_SGTE_PC','${DFILI}/${ENV_PREFIX}_ESFD2040_SGTE_PC${IT}_${ICLODAT2}.dat','O','')
	--insert into BEST..TI17PErMFIL values ('ESFD2040',  'EST_SGTE_PA','${DFILI}/${ENV_PREFIX}_ESFD2040_SGTE_PA${IT}_${BALSHTYEA}1231.dat','O','')
	insert into BEST..TI17PErMFIL values ('ESFD2040',  'EST_SRGTE','${DFILI}/${ENV_PREFIX}_ESFD2040_SRGTE_${MODE}${IT}_${ICLODAT2}.dat','O','')

	--insert into BEST..TI17PErMFIL values ('ESFD2040',  'EST_DLVGT_PC','${DFILP}/${ENV_PREFIX}_ESFD2040_DLVGT_PC${IT}_${ICLODAT2}.dat','O','')
	--insert into BEST..TI17PErMFIL values ('ESFD2040',  'EST_DLVGT_PA','${DFILP}/${ENV_PREFIX}_ESFD2040_DLVGT_PA${IT}_${BALSHTYEA}1231.dat','O','')
	insert into BEST..TI17PErMFIL values ('ESFD2040',  'EST_DLVGTR','${DFILP}/${ENV_PREFIX}_ESFD2040_DLVGTR_${MODE}${IT}_${ICLODAT2}.dat','O','')

	--insert into BEST..TI17PErMFIL values ('ESFD2040',  'EST_SGTEF_PC','${DFILI}/${ENV_PREFIX}_ESFD2040_SGTEF_PC${IT}_${ICLODAT2}.dat','O','')
	--insert into BEST..TI17PErMFIL values ('ESFD2040',  'EST_SGTEF_PA','${DFILI}/${ENV_PREFIX}_ESFD2040_SGTEF_PA${IT}_${BALSHTYEA}1231.dat','O','')
	insert into BEST..TI17PErMFIL values ('ESFD2040',  'EST_SRGTEF','${DFILI}/${ENV_PREFIX}_ESFD2040_SRGTEF_${MODE}${IT}_${ICLODAT2}.dat','O','')

	--insert into BEST..TI17PErMFIL values ('ESFD2040',  'EST_CMPCALC_PC','${DFILI}/${ENV_PREFIX}_ESFD2040_CMPCALC_PC${IT}_${ICLODAT2}.dat','O','')
	--insert into BEST..TI17PErMFIL values ('ESFD2040',  'EST_CMPCALC_PA','${DFILI}/${ENV_PREFIX}_ESFD2040_CMPCALC_PA${IT}_${BALSHTYEA}1231.dat','O','')
	insert into BEST..TI17PErMFIL values ('ESFD2040',  'EST_CMPCALC','${DFILI}/${ENV_PREFIX}_ESFD2040_CMPCALC_${MODE}${IT}_${ICLODAT2}.dat','O','')

	--insert into BEST..TI17PErMFIL values ('ESFD2040',  'EST_SGTEF_SRV_PC','${DFILI}/${ENV_PREFIX}_ESFD2040_SGTEF_SRV_PC${IT}_${ICLODAT2}.dat','O','')
	--insert into BEST..TI17PErMFIL values ('ESFD2040',  'EST_SGTEF_SRV_PA','${DFILI}/${ENV_PREFIX}_ESFD2040_SGTEF_SRV_PA${IT}_${BALSHTYEA}1231.dat','O','')
	insert into BEST..TI17PErMFIL values ('ESFD2040',  'EST_SGTEF_SRV','${DFILI}/${ENV_PREFIX}_ESFD2040_SGTEF_SRV_${MODE}${IT}_${ICLODAT2}.dat','O','')

	--insert into BEST..TI17PErMFIL values ('ESFD2040',  'EST_SGTE_SRV_PC','${DFILI}/${ENV_PREFIX}_ESFD2040_SGTE_SRV_PC${IT}_${ICLODAT2}.dat','O','')
	--insert into BEST..TI17PErMFIL values ('ESFD2040',  'EST_SGTE_SRV_PA','${DFILI}/${ENV_PREFIX}_ESFD2040_SGTE_SRV_PA${IT}_${BALSHTYEA}1231.dat','O','')
	insert into BEST..TI17PErMFIL values ('ESFD2040',  'EST_SGTE_SRV','${DFILI}/${ENV_PREFIX}_ESFD2040_SGTE_SRV_${MODE}${IT}_${ICLODAT2}.dat','O','')

	insert into BEST..TI17PErMFIL values ('ESFD2040',  'EST_DLVGTAA_PC','${DFILP}/${ENV_PREFIX}_ESFD2040_DLVGTAA_PC${IT}_${ICLODAT}.dat','O','')
	--insert into BEST..TI17PErMFIL values ('ESFD2040',  'EST_DLVGTAA_PA','${DFILP}/${ENV_PREFIX}_ESFD2040_DLVGTAA_PA${IT}_${BALSHTYEA}1231.dat','O','')
	insert into BEST..TI17PErMFIL values ('ESFD2040',  'EST_DLVGTAA','${DFILP}/${ENV_PREFIX}_ESFD2040_DLVGTAA_${MODE}${IT}_${ICLODAT2}.dat','O','')

	insert into BEST..TI17PErMFIL values ('ESFD2040',  'EST_DLVGTAR_PC','${DFILP}/${ENV_PREFIX}_ESFD2040_DLVGTAR_PC${IT}_${ICLODAT}.dat','O','')
	--insert into BEST..TI17PErMFIL values ('ESFD2040',  'EST_DLVGTA_PA','${DFILP}/${ENV_PREFIX}_ESFD2040_DLVGTA_PA${IT}_${BALSHTYEA}1231.dat','O','')
	insert into BEST..TI17PErMFIL values ('ESFD2040',  'EST_DLVGTAR','${DFILP}/${ENV_PREFIX}_ESFD2040_DLVGTAR_${MODE}${IT}_${ICLODAT2}.dat','O','')


	--insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_SRGTE_SRV_PC','${DFILI}/${ENV_PREFIX}_ESFD2040_SRGTE_SRV_PC${IT}_${ICLODAT2}.dat','O','')
	--insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_SRGTE_SRV_PA','${DFILI}/${ENV_PREFIX}_ESFD2040_SRGTE_SRV_PA${IT}_${BALSHTYEA}1231.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_SRGTE_SRV','${DFILI}/${ENV_PREFIX}_ESFD2040_SRGTE_SRV_${MODE}${IT}_${BALSHTYEA}1231.dat','O','')

--Input files
	--	EST_FGRP
	--	EST_FACMTRSH
	--	EST_SEGRATANO
	--	EST_FTRSLNK
	--	EST_FBANTECL
	--	EST_FCURQUOT
	--  EST_SUBTRSASSO
	--  EST_IARVPERICASE0
	--  EST_IARVPERICASE4
	--  EST_SUBTRSESBPROP
	--  EST_SUBTRS
	--  EST_FACCPAR0
	--  EST_CPLIFDRI
	--	EST_CPLIFDI       DFILI
	--	EST_FCPLACC        DFILP
	--	EST_FVPLACEMT      DFILI
	--	EST_IAVPEICASE    DFILI
	--	EST_IVPEICASE    DFILI
	--	EST_SRGTC          DFILI
	--	EST_VLIFEST195     DFILI
	--	EST_IAVPEICASE0
	--	EST_SUBTS
	--	EST_SUBTSASSO
	--	EST_FTSLNK
	--	EST_SUBTSESBPOP
	--	EST_IAVPEICASE4
	--	EST_FACCPA0
	--  EST_FSUBSID
	--  EST_LIFESTNOACC

-- Output file
	-- 	EST_SIGNANO
	--	EST_CMPCALC
	--	EST_SRGTE	823 if [ ${MODE} == "PA" ] 
	--	EST_SRGTEF  825 if [ ${MODE} == "PA" ] 
	--	EST_SRGTE   842 if [ ${MODE} != "PA" ] 
	--	EST_SRGTEF  845 if [ ${MODE} != "PA" ] 
	--	EST_DLVGTA
	--	EST_DLVGT
	--	EST_DLVGTAA
	--  EST_FBANTECL
	--  EST_SRGTR_VENTIL
	--  EST_SRGTEF_SRV
	--  EST_SRGTE_SRV
	

	if @@servername = "DEV_TPO2"
	   UPDATE BEST..TI17PErMFIL  SET   PATHPATTRN_LL = str_replace(PATHPATTRN_LL,"${DFIL","${XDFIL") Where IO in ("I") and IDF_CT = 'ESFD2040'
	   -- select * from BEST..TI17PErMFIL where IDF_CT = 'ESFD2040'
	   
go


