
-------------------------------
--	Init  ESPP3620 
-------------------------------

	delete BEST..TI17PERMFIL where IDF_CT ="ESPD3620_POSE" 
	delete BEST..TI17REQCHN where   IDF_CT = 'ESPD3620_POSE' 
	delete BEST..TI17CHN  where CHAIN_CT='ESPD3620'
    delete BEST..TI17FNC  where IDF_CT='ESPD3620_POSE'

	insert into BEST..TI17CHN values ('ESPD3620',  'Discount calcultion job ESID3703B')

		--  ESPD3620_POSE 

	insert into BEST..TI17FNC values ('ESPD3620_POSE',  'IFRS4 Post omega social EBS')

	----------  Perms---------------------

	--- input
	insert into BEST..TI17PERMFIL values ('ESPD3620_POSE',  'EST_FPLC','${DFILP}/${PCH}ESPT0000_FPLC.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESPD3620_POSE',  'EST_FCLIENT','${DFILP}/${PCH}ESPT0000_FCLIENT.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESPD3620_POSE',  'EST_FDETTRS','${DFILP}/${PCH}ESPT0000_FDETTRS.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESPD3620_POSE',  'EST_FTRSLNK','${DFILP}/${PCH}ESPT0000_FTRSLNK.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESPD3620_POSE',  'EST_FSSDACTR','${DFILP}/${PCH}ESPT0000_FSSDACTR.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESPD3620_POSE',  'EST_FSEGPATTERN_ICR','${DFILP}/${PCH}ESPD0060_FSEGPATTERN_ICR.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESPD3620_POSE',  'EST_DLEIFTECLEDSIIEP','${DFILP}/${PCH}ESPD4000_DLEIFTECLEDSIIEPSO.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESPD3620_POSE',  'EST_IADPERICASE','${DFILP}/${PCH}ESPT0000_IADPERICASE_${PARM_ICLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESPD3620_POSE',  'EST_GTSII_REMAINTOPAY_ULAE','${DFILP}/${PCH}ESPD3610_GTSII_REMAINTOPAY_ULAE_SIISO_${PARM_ICLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESPD3620_POSE',  'EST_GTSII_REMAINTOPAY_ULAEINF','${DFILP}/${PCH}ESPD3610_GTSII_REMAINTOPAY_ULAEINF_SIISO_${PARM_ICLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESPD3620_POSE',  'EST_GTSII_CASHFLOW','${DFILP}/${PCH}ESPD3610_GTSII_CASHFLOW_POSE_${PARM_ICLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESPD3620_POSE',  'EST_DLCUMGTAAR_IBNR_FUTCLAIMS','${DFILP}/${PCH}ESPD3610_DLCUMGTAAR_IBNR_FUTCLAIMS_POSE.dat','I','')
		insert into BEST..TI17PERMFIL values ('ESPD3620_POSE',  'ESF_GTSII_ESCOMPTE','${DFILP}/${ENV_PREFIX}_ESPD3700_GTSII_ESCOMPTE_CLM_IFRS17.dat','I','')

	--output
		insert into BEST..TI17PERMFIL values ('ESPD3620_POSE',  'EST_DLDSIIGTR','${DFILP}/${PCH}ESPD3620_DLDSIIGTRSO.dat',' O','')
		insert into BEST..TI17PERMFIL values ('ESPD3620_POSE',  'EST_DLDSIIGTAA','${DFILP}/${PCH}ESPD3620_DLDSIIGTAASO.dat','O','')
		insert into BEST..TI17PERMFIL values ('ESPD3620_POSE',  'EST_DLDSIIGTAR','${DFILP}/${PCH}ESPD3620_DLDSIIGTARSO.dat','O','')
		insert into BEST..TI17PERMFIL values ('ESPD3620_POSE',  'EST_FTECLEDSII','${DFILP}/${PCH}ESPD3620_FTECLEDSIISO.dat','O','')
		insert into BEST..TI17PERMFIL values ('ESPD3620_POSE',  'EST_DLEIFTECLEDSIIEI','${DFILP}/${PCH}ESPD3620_DLEIFTECLEDSIIEI_POSE.dat','O','')
		insert into BEST..TI17PERMFIL values ('ESPD3620_POSE',  'EST_GTSII_ESCOMPTE_CLM','${DFILP}/${PCH}ESPD3620_GTSII_ESCOMPTE_CLM.dat','O','')

	----------   Reqs of chain   ---------------------

		insert into BEST..TI17REQCHN values ('POSE',  'ESPD3620','ESPD3620_POSE','POSE')


go
