

-------------------------------
--      Init  ESFD2070
-------------------------------

delete BEST..TI17PERMFIL where IDF_CT  ='ESFD2070'
delete BEST..TI17REQCHN where   IDF_CT  ='ESFD2070'
delete BEST..TI17CHN  where CHAIN_CT='ESFD2070'
delete BEST..TI17FNC where IDF_CT   ='ESFD2070'

insert into BEST..TI17CHN values ('ESFD2070',  '')

		--  ESFD2070 ESFD2070

insert into BEST..TI17FNC values ('ESFD2070',  '')

----------  Perms---------------------
--Input
	insert into BEST..TI17PERMFIL values ('ESFD2070',  'EST_IGTR00','${DFILP}/${ENV_PREFIX}_ESIJ7000_IGTR00.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESFD2070',  'EST_IGTAA00','${DFILP}/${ENV_PREFIX}_ESIJ7000_IGTAA00.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESFD2070',  'EST_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURQUOT.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESFD2070',  'EST_ARCSTATGTR','${DFILP}/${ENV_PREFIX}_ESIX7000_ARCSTATGTR.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESFD2070',  'EST_SUBTRS','${DFILI}/${ENV_PREFIX}_ESCJ0060_FSUBTRS_${CLODAT}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESFD2070',  'EST_FCTRFIC','${DFILI}/${ENV_PREFIX}_ESCJ0060_FCTRFIC_${CLODAT}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESFD2070',  'EST_FINTWIT','${DFILI}/${ENV_PREFIX}_ESID0060_FINTWIT_${CLODAT}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESFD2070',  'EST_FLSTMTH','${DFILI}/${ENV_PREFIX}_ESID0060_FLSTMTH_${CLODAT}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESFD2070',  'EST_FSEGPAR','${DFILI}/${ENV_PREFIX}_ESCJ0060_FSEGPAR_${CLODAT}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESFD2070',  'EST_FTRSLNK','${DFILI}/${ENV_PREFIX}_ESCJ0060_FTRSLNK_${CLODAT}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESFD2070',  'EST_FCPLACC0','${DFILI}/${ENV_PREFIX}_ESEH1110_FCPLACC0_${CLODAT}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESFD2070',  'EST_FVCTRGRO','${DFILI}/${ENV_PREFIX}_ESEH1110_FVCTRGRO_${CLODAT}.dat','I','')
  --insert into BEST..TI17PERMFIL values ('ESFD2070',  'EST_FCESSION0','${DFILI}/${ENV_PREFIX}_ESEH1110_FCESSION0_${CLODAT}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESFD2070',  'EST_FCESSION1','${DFILI}/${ENV_PREFIX}_ESEH1110_FCESSION1_${CLODAT}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESFD2070',  'EST_FDEPOSIT0','${DFILI}/${ENV_PREFIX}_ESID0060_FDEPOSIT0_${CLODAT}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESFD2070',  'EST_FPFUNWIT0','${DFILI}/${ENV_PREFIX}_ESID0060_FPFUNWIT0_${CLODAT}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESFD2070',  'EST_FPINTWIT0','${DFILI}/${ENV_PREFIX}_ESID0060_FPINTWIT0_${CLODAT}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESFD2070',  'EST_FPLACEMT0','${DFILI}/${ENV_PREFIX}_ESEH1110_FPLACEMT0_${CLODAT}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESFD2070',  'EST_FPLACEMT1','${DFILI}/${ENV_PREFIX}_ESEH1110_FPLACEMT1_${CLODAT}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESFD2070',  'EST_VTSTATGTA0','${DFILI}/${ENV_PREFIX}_ESID1010_VTSTATGTA0_${CLODAT}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESFD2070',  'EST_FLIFDRI','${DFILI}/${ENV_PREFIX}_ESCJ0060_FLIFDRI${IT}_ALL_${CLODAT}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESFD2070',  'EST_IAVPERICASE0','${DFILI}/${ENV_PREFIX}_ESEH1100_IAVPERICASE0_${CLODAT}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESFD2070',  'EST_IRVPERICASE0','${DFILI}/${ENV_PREFIX}_ESID0060_IRVPERICASE0_${CLODAT}.dat','I','')
	insert into BEST..TI17PERMFIL values ('ESFD2070',  'EST_SUBTRSESBPROP','${DFILI}/${ENV_PREFIX}_ESCJ0060_FSUBTRSESBPROP_${CLODAT}.dat','I','')
  insert into BEST..TI17PERMFIL values ('ESFD2070',  'EST_FLIFEST0','`if [ "${IT}" = "Q" ];then CH="2";else CH="3";fi;echo "${DFILI}/${ENV_PREFIX}_ESID01${CH}0_FLIFEST${IT}0_${CLODAT}.dat";`','I','')
	--insert into BEST..TI17PERMFIL values ('ESFD2070',  'EST_FLIFEST0','${DFILI}/${ENV_PREFIX}_ESID0120${CH}0_FLIFEST${IT}0_${CLODAT}.dat','I','')
--Output
	insert into BEST..TI17PERMFIL values ('ESFD2070',  'EST_SEGRATANO','${DFILI}/${ENV_PREFIX}_ESFD2070_SEGRATANO_${CLODAT}.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESFD2070',  'EST_CRIBLEANO','${DFILI}/${ENV_PREFIX}_ESFD2070_CRIBLEANO${IT}_${CLODAT}.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESFD2070',  'EST_FVPLACEMT','${DFILI}/${ENV_PREFIX}_ESFD2070_FVPLACEMT${IT}_${CLODAT}.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESFD2070',  'EST_LIFENDCPT','${DFILI}/${ENV_PREFIX}_ESFD2070_LIFENDCPT${IT}_${CLODAT}.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESFD2070',  'EST_LIFESTANA','${DFILI}/${ENV_PREFIX}_ESFD2070_LIFESTANA${IT}_${CLODAT}.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESFD2070',  'EST_LIFESTLIB','${DFILI}/${ENV_PREFIX}_ESFD2070_LIFESTLIB${IT}_${CLODAT}.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESFD2070',  'EST_FVPLACEMT1','${DFILI}/${ENV_PREFIX}_ESFD2070_FVPLACEMT1${IT}_${CLODAT}.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESFD2070',  'EST_FVPLACEMT2','${DFILI}/${ENV_PREFIX}_ESFD2070_FVPLACEMT2${IT}_${CLODAT}.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESFD2070',  'EST_ERRUPDBATCH','${DFILI}/${ENV_PREFIX}_ESFD2070_ERRUPDBATCH${IT}_${CLODAT}.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESFD2070',  'EST_LIFESTNOACC','${DFILI}/${ENV_PREFIX}_ESFD2070_LIFESTNOACC${IT}_${CLODAT}.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESFD2070',  'EST_VLIFEST2070','${DFILI}/${ENV_PREFIX}_ESFD2070_VLIFEST2070${IT}_${CLODAT}.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESFD2070',  'EST_FRATTACHEVOL','${DFILI}/${ENV_PREFIX}_ESFD2070_FRATTACHEVOL${IT}_${CLODAT}.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESFD2070',  'EST_310_SORT_GT_O','${DFILI}/${ENV_PREFIX}_ESFD2070_310_SORT_GT${IT}_O_${CLODAT}.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESFD2070',  'EST_430_SORT_GT_O','${DFILI}/${ENV_PREFIX}_ESFD2070_430_SORT_GT${IT}_O_${CLODAT}.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESFD2070',  'EST_470_SORT_GT_O','${DFILI}/${ENV_PREFIX}_ESFD2070_470_SORT_GT${IT}_O_${CLODAT}.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESFD2070',  'EST_IARVPERICASE0','${DFILI}/${ENV_PREFIX}_ESFD2070_IARVPERICASE0${IT}_${CLODAT}.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESFD2070',  'EST_IARVPERICASE4','${DFILI}/${ENV_PREFIX}_ESFD2070_IARVPERICASE4${IT}_${CLODAT}.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESFD2070',  'EST_160_SORT_CPLACC_O','${DFILI}/${ENV_PREFIX}_ESFD2070_160_SORT_CPLACC${IT}_O_${CLODAT}.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESFD2070',  'EST_180_SORT_LSTMTH_O','${DFILI}/${ENV_PREFIX}_ESFD2070_180_SORT_LSTMTH${IT}_O_${CLODAT}.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESFD2070',  'EST_ESTC2035_LIFDRI_O1','${DFILI}/${ENV_PREFIX}_ESFD2070_ESTC2035_LIFDRI${IT}_O1_${CLODAT}.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESFD2070',  'EST_200_ESTC2034_GTB1_O','${DFILI}/${ENV_PREFIX}_ESFD2070_200_ESTC2034_GTB1${IT}_O_${CLODAT}.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESFD2070',  'EST_31_SORT_R_IAVPERICASE_O','${DFILI}/${ENV_PREFIX}_ESFD2070_31_SORT_R_IAVPERICASE${IT}_O_${CLODAT}.dat','O','')
	insert into BEST..TI17PERMFIL values ('ESFD2070',  'EST_180_ESTC2040_OLD_LIFEST_O2','${DFILI}/${ENV_PREFIX}_ESFD2070_180_ESTC2040_OLD_LIFEST${IT}_O2_${CLODAT}.dat','O','')

 
--if @@servername = "DEV_TPO2"
  -- UPDATE BEST..TI17PERMFIL  SET   PATHPATTRN_LL = str_replace(PATHPATTRN_LL,"${DFIL","${XDFIL") WHERE IO="I" and IDF_CT = 'ESFD2070'
   ---select * from BEST..TI17PERMFIL where IDF_CT  ='ESFD2070'

go


---- input -----
--       EST_ARCSTATGTR
--       EST_FCESSION1
--       EST_FCPLACC0
--       EST_FCTRFIC
--       EST_FCURQUOT
--       EST_FDEPOSIT0
--       EST_FINTWIT
--       EST_FLIFDRI
--       EST_FLIFEST0
--       EST_FLSTMTH
--       EST_FPFUNWIT0
--       EST_FPINTWIT0
--       EST_FPLACEMT0
--       EST_FPLACEMT1
--       EST_FSEGPAR
--       EST_FTRSLNK
--       EST_FVCTRGRO
--       EST_IAVPERICASE0
--       EST_IGTAA00
--       EST_IGTR00
--       EST_IRVPERICASE0
--       EST_SUBTRS
--       EST_SUBTRSESBPROP
--       EST_VTSTATGTA0
---- output -----
--       EST_160_SORT_CPLACC_O
--       EST_180_SORT_LSTMTH_O
--       EST_200_ESTC2034_GTB1_O
--       EST_310_SORT_GT_O
--       EST_31_SORT_R_IAVPERICASE_O
--       EST_430_SORT_GT_O
--       EST_470_SORT_GT_O
--       EST_CRIBLEANO
--       EST_180_ESTC2040_OLD_LIFEST_O2
--       EST_ERRUPDBATCH
--       EST_ESTC2035_LIFDRI_O1
--       EST_FRATTACHEVOL
--       EST_FVPLACEMT
--       EST_FVPLACEMT1
--       EST_IARVPERICASE0
--       EST_IARVPERICASE4
--       EST_LIFENDCPT
--       EST_LIFESTANA
--       EST_LIFESTLIB
--       EST_LIFESTNOACC
--       EST_SEGRATANO
--       EST_VLIFEST2070

