delete BEST..TI17PERMFIL where IDF_CT ='ESFD2040'
delete BEST..TI17REQCHN where   IDF_CT = 'ESFD2040'
delete BEST..TI17CHN  where CHAIN_CT='ESFD2040'
delete BEST..TI17FNC where IDF_CT  ='ESFD2040'
insert into BEST..TI17CHN values ('ESFD2040',  '')
insert into BEST..TI17FNC values ('ESFD2040',  '')
insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURQUOT.dat','I','')
insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_FGRP','${DFILI}/${ENV_PREFIX}_ESCJ0060_FGRP_${CLODAT}.dat','I','')
insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_SUBTRS','${DFILI}/${ENV_PREFIX}_ESCJ0060_FSUBTRS_${CLODAT}.dat','I','')
insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_FSUBSID','${DFILI}/${ENV_PREFIX}_ESCJ0060_FSUBSID_${CLODAT}.dat','I','')
insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_FTRSLNK','${DFILI}/${ENV_PREFIX}_ESCJ0060_FTRSLNK_${CLODAT}.dat','I','')
insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_SRGTC','${DFILI}/${ENV_PREFIX}_ESID2030_SRGTC${IT}_${CLODAT}.dat','I','')
insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_FACCPAR0','${DFILI}/${ENV_PREFIX}_ESID0060_FACCPAR0_${CLODAT}.dat','I','')
insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_FACMTRSH','${DFILI}/${ENV_PREFIX}_ESCJ0060_FACMTRSH_${CLODAT}.dat','I','')
insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_FBANTECL','${DFILI}/${ENV_PREFIX}_ESCJ0060_FBANTECL_${CLODAT}.dat','I','')
insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_FCPLACC','${DFILP}/${ENV_PREFIX}_ESID0560_FCPLACC_${ICLODAT2}.dat','I','')
insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_SEGRATANO','${DFILI}/${ENV_PREFIX}_ESID2070_SEGRATANO_${CLODAT}.dat','I','')
insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_CPLIFDRI','${DFILI}/${ENV_PREFIX}_ESID2030_CPLIFDRI${IT}_${CLODAT}.dat','I','')
insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_SUBTRSASSO','${DFILI}/${ENV_PREFIX}_ESCJ0060_FSUBTRSASSO_${CLODAT}.dat','I','')
insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_CRIBLEANO','${DFILI}/${ENV_PREFIX}_ESID2070_CRIBLEANO${IT}_${CLODAT}.dat','I','')
insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_FVPLACEMT','${DFILI}/${ENV_PREFIX}_ESID2070_FVPLACEMT${IT}_${CLODAT}.dat','I','')
insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_LIFENDCPT','${DFILI}/${ENV_PREFIX}_ESID2070_LIFENDCPT${IT}_${CLODAT}.dat','I','')
insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_IAVPERICASE','${DFILI}/${ENV_PREFIX}_ESID0560_IAVPERICASE_${ICLODAT2}.dat','I','')
insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_IRVPERICASE','${DFILI}/${ENV_PREFIX}_ESID0560_IRVPERICASE_${ICLODAT2}.dat','I','')
insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_LIFTRANSFR','${DFILI}/${ENV_PREFIX}_ESID2030_LIFTRANSFR${IT}_${CLODAT}.dat','I','')
insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_VLIFEST195','${DFILI}/${ENV_PREFIX}_ESID2030_VLIFEST195${IT}_${CLODAT}.dat','I','')
insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_LIFESTNOACC','${DFILI}/${ENV_PREFIX}_ESID2070_LIFESTNOACC${IT}_${CLODAT}.dat','I','')
insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_SUBTRSESBPROP','${DFILI}/${ENV_PREFIX}_ESCJ0060_FSUBTRSESBPROP_${CLODAT}.dat','I','')
insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_IARVPERICASE0','${DFILI}/${ENV_PREFIX}_ESID2070_IARVPERICASE0${IT}_${CLODAT}.dat','I','')
insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_IARVPERICASE4','${DFILI}/${ENV_PREFIX}_ESID2070_IARVPERICASE4${IT}_${CLODAT}.dat','I','')

insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_SRGTR_VENTIL','${DFILI}/${ENV_PREFIX}_ESFD2040_SRGTR_VENTIL${IT}_${ICLODAT2}.dat','O','')


--insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_SIGNANO','${DFILI}/${ENV_PREFIX}_ESFD2040_SIGNANO${IT}_${ICLODAT2}.dat','O','')
insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_SIGNANO','${DFILI}/${ENV_PREFIX}_ESFD2040_SIGNANO_${MODE}${IT}_${ICLODAT2}.dat','O','')

--insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_SRGTE_PC','${DFILI}/${ENV_PREFIX}_ESFD2040_SRGTE_PC${IT}_${ICLODAT2}.dat','O','')
--insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_SRGTE_PA','${DFILI}/${ENV_PREFIX}_ESFD2040_SRGTE_PA${IT}_${BALSHTYEA}1231.dat','O','')
insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_SRGTE','${DFILI}/${ENV_PREFIX}_ESFD2040_SRGTE_${MODE}${IT}_${ICLODAT2}.dat','O','')

--insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_DLVGTR_PC','${DFILP}/${ENV_PREFIX}_ESFD2040_DLVGTR_PC${IT}_${ICLODAT2}.dat','O','')
--insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_DLVGTR_PA','${DFILP}/${ENV_PREFIX}_ESFD2040_DLVGTR_PA${IT}_${BALSHTYEA}1231.dat','O','')
insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_DLVGTR','${DFILP}/${ENV_PREFIX}_ESFD2040_DLVGTR_${MODE}${IT}_${ICLODAT2}.dat','O','')

--insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_SRGTEF_PC','${DFILI}/${ENV_PREFIX}_ESFD2040_SRGTEF_PC${IT}_${ICLODAT2}.dat','O','')
--insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_SRGTEF_PA','${DFILI}/${ENV_PREFIX}_ESFD2040_SRGTEF_PA${IT}_${BALSHTYEA}1231.dat','O','')
insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_SRGTEF','${DFILI}/${ENV_PREFIX}_ESFD2040_SRGTEF_${MODE}${IT}_${ICLODAT2}.dat','O','')

--insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_CMPCALC_PC','${DFILI}/${ENV_PREFIX}_ESFD2040_CMPCALC_PC${IT}_${ICLODAT2}.dat','O','')
--insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_CMPCALC_PA','${DFILI}/${ENV_PREFIX}_ESFD2040_CMPCALC_PA${IT}_${BALSHTYEA}1231.dat','O','')
insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_CMPCALC','${DFILI}/${ENV_PREFIX}_ESFD2040_CMPCALC_${MODE}${IT}_${ICLODAT2}.dat','O','')

--insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_SRGTEF_SRV_PC','${DFILI}/${ENV_PREFIX}_ESFD2040_SRGTEF_SRV_PC${IT}_${ICLODAT2}.dat','O','')
--insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_SRGTEF_SRV_PA','${DFILI}/${ENV_PREFIX}_ESFD2040_SRGTEF_SRV_PA${IT}_${BALSHTYEA}1231.dat','O','')
insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_SRGTEF_SRV','${DFILI}/${ENV_PREFIX}_ESFD2040_SRGTEF_SRV_${MODE}${IT}_${ICLODAT2}.dat','O','')

--insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_SRGTE_SRV_PC','${DFILI}/${ENV_PREFIX}_ESFD2040_SRGTE_SRV_PC${IT}_${ICLODAT2}.dat','O','')
--insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_SRGTE_SRV_PA','${DFILI}/${ENV_PREFIX}_ESFD2040_SRGTE_SRV_PA${IT}_${BALSHTYEA}1231.dat','O','')
insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_SRGTE_SRV','${DFILI}/${ENV_PREFIX}_ESFD2040_SRGTE_SRV_${MODE}${IT}_${ICLODAT2}.dat','O','')

--insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_DLVGTAA_PC','${DFILP}/${ENV_PREFIX}_ESFD2040_DLVGTAA_PC${IT}_${ICLODAT2}_${CRE_D}.dat','O','')
--insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_DLVGTAA_PA','${DFILP}/${ENV_PREFIX}_ESFD2040_DLVGTAA_PA${IT}_${BALSHTYEA}1231.dat','O','')
insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_DLVGTAA','${DFILP}/${ENV_PREFIX}_ESFD2040_DLVGTAA_${MODE}${IT}_${ICLODAT2}.dat','O','')

--insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_DLVGTAR_PC','${DFILP}/${ENV_PREFIX}_ESFD2040_DLVGTAR_PC${IT}_${ICLODAT2}_${CRE_D}.dat','O','')
--insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_DLVGTAR_PA','${DFILP}/${ENV_PREFIX}_ESFD2040_DLVGTAR_PA${IT}_${BALSHTYEA}1231.dat','O','')
insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_DLVGTAR','${DFILP}/${ENV_PREFIX}_ESFD2040_DLVGTAR_${MODE}${IT}_${ICLODAT2}.dat','O','')


--Input files
--	EST_CPLIFDRI       DFILI
--	EST_FCPLACC        DFILP
--	EST_FCURQUOT       DFILP
--	EST_FVPLACEMT      DFILI
--	EST_IAVPERICASE    DFILI
--	EST_IRVPERICASE    DFILI
--	EST_SRGTC          DFILI
--	EST_VLIFEST195     DFILI
--	EST_IARVPERICASE0
--	EST_SUBTRS
--	EST_SUBTRSASSO
--	EST_FTRSLNK
--	EST_SUBTRSESBPROP
--	EST_IARVPERICASE4
--	EST_FACCPAR0
--
-- Output file
-- 	EST_SIGNANO
--	EST_CMPCALC
--	EST_SRGTE	823 if [ ${MODE} == "PA" ] 
--	EST_SRGTEF  825 if [ ${MODE} == "PA" ] 
--	EST_SRGTE   842 if [ ${MODE} != "PA" ] 
--	EST_SRGTEF  845 if [ ${MODE} != "PA" ] 
--	EST_DLVGTAR
--	EST_DLVGTR
--	EST_DLVGTAA
--


if @@servername = "DEV_TPO2"
   UPDATE BEST..TI17PERMFIL  SET   PATHPATTRN_LL = str_replace(PATHPATTRN_LL,"${DFIL","${XDFIL") WHERE IO="I" and IDF_CT = 'ESFD2040'


go



