USE BTRT
GO

SET NOCOUNT ON

-- ######################################################################################################################################
-- Script           			: TRT_SPIRA_TEMPLATE_UPDATE_LOC_IFRS_DATA.sql
-- Domain             			: TRT
-- Base Principle    			: BTRT - PARIS
-- Author           			: OLIVIER
-- Date of Creation     		: 10/11/2022
--
-- ######################################################################################################################################

CREATE TABLE #TSECIFRS
(
    NORM				VARCHAR(24),
	CTR_TYP				VARCHAR(3)		NULL,
	CTR_NF				UCTR_NF,
	UWY_NF				UUWY_NF,
	UW_NT        		UUW_NT     		NOT NULL,
    END_NT       		UEND_NT    		NOT NULL,
    SEC_NF				USEC_NF,
	CR_NF				CHAR(10)		NULL,
	CRUWY_NF			UUWY_NF			NULL,
	UPDCR_B				TINYINT			NULL,
	LOCIFRSSEG_CT		USEG_NF    		NULL,
	UPDIFRSSEG_B		TINYINT			NULL,
	LOCINIPRO_CF		UBANVAL_CT 		NULL,
	UPDINIPRO_B			TINYINT			NULL,
	LOCRATEINDEX_CT		UL32       		NULL,
	UPDRATEINDEX_B		TINYINT			NULL,
	LOCFIRCLO_D			DATETIME   		NULL,
	UPDFIRCLO_B			TINYINT			NULL,
	LOCINISTS_CT		TINYINT			NULL,
	UPDINISTS_B			TINYINT			NULL
)

CREATE TABLE #COUNTCHECK
(
	STEP 			int,
	STEP_LBL		VARCHAR(64),
	TMPSELECTCOUNT	int NULL,
	SELECTCOUNT 	int,
	UPDATECOUNT 	int DEFAULT 0
)
GO

DECLARE CR_REALIGN_TRT CURSOR FOR 
	SELECT 	CTR_NF, UWY_NF, UW_NT, END_NT, CR_NF, CRUWY_NF
	FROM	#TSECIFRS T
	WHERE 	CTR_TYP = 'TRT'
	AND		T.UPDCR_B = 1
GO

DECLARE CR_REALIGN_FAC CURSOR FOR 
	SELECT 	CTR_NF, UWY_NF, UW_NT, END_NT, CR_NF, CRUWY_NF
	FROM	#TSECIFRS T
	WHERE 	CTR_TYP = 'FAC'
	AND		T.UPDCR_B = 1
GO

-- ------------------------------------------------ --
-- VARIABLES
-- ------------------------------------------------- --
declare @gCommit 			VARCHAR (01)
declare @gToday				Datetime
declare @gUsrCf				VARCHAR(4)
declare @gUpdateControl		INTEGER

declare @lRowsInter			INTEGER
declare @lMaxCrUwyNf		INTEGER
declare @lCtrNf				UCTR_NF
declare @lUwyNf				UUWY_NF
declare @lUwNt				UUW_NT
declare @lEndNt				UEND_NT
declare @lCrNf				CHAR(10)
declare @lCrUWYNf			UUWY_NF
declare @lNbUpdatedCr		INTEGER

-- --------------------------- --
-- INITIALIZATION OF VARIABLES --
-- --------------------------- --
SELECT @gCommit 	= 'O'
SELECT @gToday 		= getdate()
SELECT @gUsrCf		= 'INF7'
SELECT @lNbUpdatedCr = 0

-- #########################################################################
-- 			SELECTIONS AVANT UPDATE
-- #########################################################################

-- INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'GROUP', '
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0130093', 2025, 1, 0, 1, 'CRF0469861', 2025, 1, '1', 1, NULL, 0, NULL, 0, NULL, 0, NULL, 0
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0130094', 2025, 1, 0, 1, 'CRF0469862', 2025, 1, '1', 1, NULL, 0, NULL, 0, NULL, 0, NULL, 0
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0130095', 2025, 1, 0, 1, 'CRF0469863', 2025, 1, '1', 1, NULL, 0, NULL, 0, NULL, 0, NULL, 0
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0130096', 2025, 1, 0, 1, 'CRF0469864', 2025, 1, '1', 1, NULL, 0, NULL, 0, NULL, 0, NULL, 0
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0130097', 2025, 1, 0, 1, 'CRF0469865', 2025, 1, '1', 1, NULL, 0, NULL, 0, NULL, 0, NULL, 0
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0130098', 2025, 1, 0, 1, 'CRF0469866', 2025, 1, '1', 1, NULL, 0, NULL, 0, NULL, 0, NULL, 0
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0130099', 2025, 1, 0, 1, 'CRF0469867', 2025, 1, '1', 1, NULL, 0, NULL, 0, NULL, 0, NULL, 0
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0130100', 2025, 1, 0, 1, 'CRF0469868', 2025, 1, '1', 1, NULL, 0, NULL, 0, NULL, 0, NULL, 0
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0130101', 2025, 1, 0, 1, 'CRF0469869', 2025, 1, '1', 1, NULL, 0, NULL, 0, NULL, 0, NULL, 0
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0130102', 2025, 1, 0, 1, 'CRF0469870', 2025, 1, '1', 1, NULL, 0, NULL, 0, NULL, 0, NULL, 0
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0130103', 2025, 1, 0, 1, 'CRF0469871', 2025, 1, '1', 1, NULL, 0, NULL, 0, NULL, 0, NULL, 0
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0130104', 2025, 1, 0, 1, 'CRF0469872', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0130179', 2025, 1, 0, 1, 'CRF0469947', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0130180', 2025, 1, 0, 1, 'CRF0469948', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0130181', 2025, 1, 0, 1, 'CRF0469949', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0130182', 2025, 1, 0, 1, 'CRF0469950', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0130183', 2025, 1, 0, 1, 'CRF0469951', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0130184', 2025, 1, 0, 1, 'CRF0469952', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0130185', 2025, 1, 0, 1, 'CRF0469953', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0130186', 2025, 1, 0, 1, 'CRF0469954', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0130187', 2025, 1, 0, 1, 'CRF0469955', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0130188', 2025, 1, 0, 1, 'CRF0469956', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0130189', 2025, 1, 0, 1, 'CRF0469957', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0130190', 2025, 1, 0, 1, 'CRF0469958', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0130256', 2025, 1, 0, 1, 'CRF0470024', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0130257', 2025, 1, 0, 1, 'CRF0470025', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0130258', 2025, 1, 0, 1, 'CRF0470026', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0130259', 2025, 1, 0, 1, 'CRF0470027', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0130260', 2025, 1, 0, 1, 'CRF0470028', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0130261', 2025, 1, 0, 1, 'CRF0470029', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0130262', 2025, 1, 0, 1, 'CRF0470030', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0130263', 2025, 1, 0, 1, 'CRF0470031', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0129894', 2025, 1, 0, 1, 'CRF0469661', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0129895', 2025, 1, 0, 1, 'CRF0469662', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0129896', 2025, 1, 0, 1, 'CRF0469663', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0129897', 2025, 1, 0, 1, 'CRF0469664', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0129917', 2025, 1, 0, 1, 'CRF0469684', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0129918', 2025, 1, 0, 1, 'CRF0469685', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0129919', 2025, 1, 0, 1, 'CRF0469686', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0129920', 2025, 1, 0, 1, 'CRF0469687', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0129938', 2025, 1, 0, 1, 'CRF0469705', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0129939', 2025, 1, 0, 1, 'CRF0469706', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0129940', 2025, 1, 0, 1, 'CRF0469707', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0129909', 2025, 1, 0, 1, 'CRF0469676', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0129910', 2025, 1, 0, 1, 'CRF0469677', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0129930', 2025, 1, 0, 1, 'CRF0469697', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0129943', 2025, 1, 0, 1, 'CRF0469710', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0129943', 2025, 1, 0, 1, 'CRF0469710', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0129943', 2025, 1, 0, 1, 'CRF0469710', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0129943', 2025, 1, 0, 1, 'CRF0469710', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0129943', 2025, 1, 0, 1, 'CRF0469710', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0129943', 2025, 1, 0, 1, 'CRF0469710', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0129943', 2025, 1, 0, 1, 'CRF0469710', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0129943', 2025, 1, 0, 1, 'CRF0469710', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0129943', 2025, 1, 0, 1, 'CRF0469710', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0129943', 2025, 1, 0, 1, 'CRF0469710', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0129943', 2025, 1, 0, 1, 'CRF0469710', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0129943', 2025, 1, 0, 1, 'CRF0469710', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0129943', 2025, 1, 0, 1, 'CRF0469710', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0129943', 2025, 1, 0, 1, 'CRF0469710', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0129943', 2025, 1, 0, 1, 'CRF0469710', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0129943', 2025, 1, 0, 1, 'CRF0469710', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0129943', 2025, 1, 0, 1, 'CRF0469710', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0129943', 2025, 1, 0, 1, 'CRF0469710', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0129943', 2025, 1, 0, 1, 'CRF0469710', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0129943', 2025, 1, 0, 1, 'CRF0469710', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0129943', 2025, 1, 0, 1, 'CRF0469710', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0129943', 2025, 1, 0, 1, 'CRF0469710', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0129943', 2025, 1, 0, 1, 'CRF0469710', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0129943', 2025, 1, 0, 1, 'CRF0469710', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0129943', 2025, 1, 0, 1, 'CRF0469710', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0129943', 2025, 1, 0, 1, 'CRF0469710', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0129943', 2025, 1, 0, 1, 'CRF0469710', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0129943', 2025, 1, 0, 1, 'CRF0469710', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0129943', 2025, 1, 0, 1, 'CRF0469710', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0129943', 2025, 1, 0, 1, 'CRF0469710', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0129943', 2025, 1, 0, 1, 'CRF0469710', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1
INSERT INTO #TSECIFRS (NORM, CTR_NF, UWY_NF, UW_NT, END_NT, SEC_NF, CR_NF, CRUWY_NF, UPDCR_B, LOCIFRSSEG_CT, UPDIFRSSEG_B, LOCINIPRO_CF, UPDINIPRO_B, LOCRATEINDEX_CT, UPDRATEINDEX_B, LOCFIRCLO_D, UPDFIRCLO_B, LOCINISTS_CT, UPDINISTS_B ) SELECT 'LOCAL', 'FA0129943', 2025, 1, 0, 1, 'CRF0469710', 2025, 1, '1', 1, NULL, 1, NULL, 1, NULL, 1, NULL, 1



UPDATE 	#TSECIFRS
SET 	CTR_TYP = 'TRT'
FROM	BTRT..TCONTR C,
		#TSECIFRS S
WHERE 	C.CTR_NF = S.CTR_NF 
AND 	C.UWY_NF = S.UWY_NF 
AND 	C.UW_NT  = S.UW_NT 
AND 	C.END_NT = S.END_NT

UPDATE 	#TSECIFRS
SET 	CTR_TYP = 'FAC'
FROM	BFAC..TCONTR C,
		#TSECIFRS S
WHERE 	C.CTR_NF = S.CTR_NF 
AND 	C.UWY_NF = S.UWY_NF 
AND 	C.UW_NT  = S.UW_NT 
AND 	C.END_NT = S.END_NT

UPDATE 	#TSECIFRS
SET 	CTR_TYP = '???'
WHERE	CTR_TYP IS NULL

INSERT INTO #COUNTCHECK (STEP, STEP_LBL, SELECTCOUNT) SELECT 1, 'CR TRT a modifier', Count(1) FROM #TSECIFRS T, BTRT..TCONTR S WHERE T.CTR_NF = S.CTR_NF AND T.UWY_NF = S.UWY_NF AND T.UW_NT = S.UW_NT AND T.END_NT = S.END_NT AND UPDCR_B = 1
INSERT INTO #COUNTCHECK (STEP, STEP_LBL, SELECTCOUNT) SELECT 2, 'Portfolios TRT a modifier', Count(1) FROM #TSECIFRS T, BTRT..TSECIFRS S WHERE T.CTR_NF = S.CTR_NF AND T.UWY_NF = S.UWY_NF AND T.SEC_NF = S.SEC_NF AND T.UW_NT = S.UW_NT AND T.END_NT = S.END_NT AND UPDIFRSSEG_B = 1
INSERT INTO #COUNTCHECK (STEP, STEP_LBL, SELECTCOUNT) SELECT 3, 'Profitabilites TRT a modifier', Count(1) FROM #TSECIFRS T, BTRT..TSECIFRS S WHERE T.CTR_NF = S.CTR_NF AND T.UWY_NF = S.UWY_NF AND T.SEC_NF = S.SEC_NF AND T.UW_NT = S.UW_NT AND T.END_NT = S.END_NT AND UPDINIPRO_B = 1
INSERT INTO #COUNTCHECK (STEP, STEP_LBL, SELECTCOUNT) SELECT 4, 'Index Rates TRT a modifier', Count(1) FROM #TSECIFRS T, BTRT..TSECIFRS S WHERE T.CTR_NF = S.CTR_NF AND T.UWY_NF = S.UWY_NF AND T.SEC_NF = S.SEC_NF AND T.UW_NT = S.UW_NT AND T.END_NT = S.END_NT AND UPDRATEINDEX_B = 1
INSERT INTO #COUNTCHECK (STEP, STEP_LBL, SELECTCOUNT) SELECT 5, 'Closing TRT Dates a modifier', Count(1) FROM #TSECIFRS T, BTRT..TSECIFRS S WHERE T.CTR_NF = S.CTR_NF AND T.UWY_NF = S.UWY_NF AND T.SEC_NF = S.SEC_NF AND T.UW_NT = S.UW_NT AND T.END_NT = S.END_NT AND UPDFIRCLO_B = 1
INSERT INTO #COUNTCHECK (STEP, STEP_LBL, SELECTCOUNT) SELECT 6, 'Statuts TRT a modifier', Count(1) FROM #TSECIFRS T, BTRT..TSECIFRS S WHERE T.CTR_NF = S.CTR_NF AND T.UWY_NF = S.UWY_NF AND T.SEC_NF = S.SEC_NF AND T.UW_NT = S.UW_NT AND T.END_NT = S.END_NT AND UPDINISTS_B = 1

INSERT INTO #COUNTCHECK (STEP, STEP_LBL, SELECTCOUNT) SELECT 7, 'CR Facs a modifier', Count(1) FROM #TSECIFRS T, BFAC..TCONTR S WHERE T.CTR_NF = S.CTR_NF AND T.UWY_NF = S.UWY_NF AND T.UW_NT = S.UW_NT AND T.END_NT = S.END_NT AND UPDCR_B = 1
INSERT INTO #COUNTCHECK (STEP, STEP_LBL, SELECTCOUNT) SELECT 8, 'Portfolios Facs a modifier', Count(1) FROM #TSECIFRS T, BFAC..TSECIFRS S WHERE T.CTR_NF = S.CTR_NF AND T.UWY_NF = S.UWY_NF AND T.SEC_NF = S.SEC_NF AND T.UW_NT = S.UW_NT AND T.END_NT = S.END_NT AND UPDIFRSSEG_B = 1
INSERT INTO #COUNTCHECK (STEP, STEP_LBL, SELECTCOUNT) SELECT 9, 'Profitabilites Facs a modifier', Count(1) FROM #TSECIFRS T, BFAC..TSECIFRS S WHERE T.CTR_NF = S.CTR_NF AND T.UWY_NF = S.UWY_NF AND T.SEC_NF = S.SEC_NF AND T.UW_NT = S.UW_NT AND T.END_NT = S.END_NT AND UPDINIPRO_B = 1
INSERT INTO #COUNTCHECK (STEP, STEP_LBL, SELECTCOUNT) SELECT 10, 'Index Rates Facs a modifier', Count(1) FROM #TSECIFRS T, BFAC..TSECIFRS S WHERE T.CTR_NF = S.CTR_NF AND T.UWY_NF = S.UWY_NF AND T.SEC_NF = S.SEC_NF AND T.UW_NT = S.UW_NT AND T.END_NT = S.END_NT AND UPDRATEINDEX_B = 1
INSERT INTO #COUNTCHECK (STEP, STEP_LBL, SELECTCOUNT) SELECT 11, 'Closing Facs Dates a modifier', Count(1) FROM #TSECIFRS T, BFAC..TSECIFRS S WHERE T.CTR_NF = S.CTR_NF AND T.UWY_NF = S.UWY_NF AND T.SEC_NF = S.SEC_NF AND T.UW_NT = S.UW_NT AND T.END_NT = S.END_NT AND UPDFIRCLO_B = 1
INSERT INTO #COUNTCHECK (STEP, STEP_LBL, SELECTCOUNT) SELECT 12, 'Statuts Facs a modifier', Count(1) FROM #TSECIFRS T, BFAC..TSECIFRS S WHERE T.CTR_NF = S.CTR_NF AND T.UWY_NF = S.UWY_NF AND T.SEC_NF = S.SEC_NF AND T.UW_NT = S.UW_NT AND T.END_NT = S.END_NT AND UPDINISTS_B = 1

UPDATE #COUNTCHECK SET TMPSELECTCOUNT = (SELECT Count(1) FROM #TSECIFRS WHERE CTR_TYP = 'TRT' AND UPDCR_B = 1) 			WHERE STEP = 1
UPDATE #COUNTCHECK SET TMPSELECTCOUNT = (SELECT Count(1) FROM #TSECIFRS WHERE CTR_TYP = 'TRT' AND UPDIFRSSEG_B = 1) 	WHERE STEP = 2
UPDATE #COUNTCHECK SET TMPSELECTCOUNT = (SELECT Count(1) FROM #TSECIFRS WHERE CTR_TYP = 'TRT' AND UPDINIPRO_B = 1) 		WHERE STEP = 3
UPDATE #COUNTCHECK SET TMPSELECTCOUNT = (SELECT Count(1) FROM #TSECIFRS WHERE CTR_TYP = 'TRT' AND UPDRATEINDEX_B = 1) 	WHERE STEP = 4
UPDATE #COUNTCHECK SET TMPSELECTCOUNT = (SELECT Count(1) FROM #TSECIFRS WHERE CTR_TYP = 'TRT' AND UPDFIRCLO_B = 1) 		WHERE STEP = 5
UPDATE #COUNTCHECK SET TMPSELECTCOUNT = (SELECT Count(1) FROM #TSECIFRS WHERE CTR_TYP = 'TRT' AND UPDINISTS_B = 1) 		WHERE STEP = 6
UPDATE #COUNTCHECK SET TMPSELECTCOUNT = (SELECT Count(1) FROM #TSECIFRS WHERE CTR_TYP = 'FAC' AND UPDCR_B = 1) 			WHERE STEP = 7
UPDATE #COUNTCHECK SET TMPSELECTCOUNT = (SELECT Count(1) FROM #TSECIFRS WHERE CTR_TYP = 'FAC' AND UPDIFRSSEG_B = 1) 	WHERE STEP = 8
UPDATE #COUNTCHECK SET TMPSELECTCOUNT = (SELECT Count(1) FROM #TSECIFRS WHERE CTR_TYP = 'FAC' AND UPDINIPRO_B = 1) 		WHERE STEP = 9
UPDATE #COUNTCHECK SET TMPSELECTCOUNT = (SELECT Count(1) FROM #TSECIFRS WHERE CTR_TYP = 'FAC' AND UPDRATEINDEX_B = 1) 	WHERE STEP = 10
UPDATE #COUNTCHECK SET TMPSELECTCOUNT = (SELECT Count(1) FROM #TSECIFRS WHERE CTR_TYP = 'FAC' AND UPDFIRCLO_B = 1) 		WHERE STEP = 11
UPDATE #COUNTCHECK SET TMPSELECTCOUNT = (SELECT Count(1) FROM #TSECIFRS WHERE CTR_TYP = 'FAC' AND UPDINISTS_B = 1) 		WHERE STEP = 12

BEGIN TRAN

-- #########################################################################
-- 			UPDATEs
-- #########################################################################
-- 	UPDATE 1 : CR TRT
OPEN CR_REALIGN_TRT
FETCH CR_REALIGN_TRT INTO @lCtrNf, @lUwyNf, @lUwNt, @lEndNt, @lCrNf, @lCrUWYNf

WHILE @@SQLSTATUS != 2
begin
	-- LOCTIE TCR
	SELECT @lRowsInter = Count(1) FROM BTRT..TCR WHERE CR_NF = @lCrNf AND CRUWY_NF = @lCrUWYNf AND CRUW_NT = 1
	
	if @lRowsInter = 0
	begin
		SELECT @lMaxCrUwyNf = MAX(CRUWY_NF) FROM BTRT..TCR WHERE CR_NF = @lCrNf
		
		if @lMaxCrUwyNf is null
		begin
			-- Il faut recréer une CR de toute pièces
			INSERT INTO BTRT..TCR (CR_NF, CRUWY_NF, CRTYP_CT, SSD_CF, ESB_CF, CR_LM, LSTUPD_D, LSTUPDUSR_CF, CRUW_NT)
			SELECT @lCrNf, @lCrUWYNf, '1', C.SSD_CF, C.ACCESB_CF, Isnull(C.PRG_NF, C.CTR_NF), @gToday, @gUsrCf, 1
			FROM 	BTRT..TCONTR C
			WHERE	C.CTR_NF = @lCtrNf
			AND		C.UWY_NF = @lUwyNf
		end
		else
		begin
			-- Il faut recréer un nouvel exercice de la CR à LOCtir de celui trouvé
			INSERT INTO BTRT..TCR (CR_NF, CRUWY_NF, CRTYP_CT, SSD_CF, ESB_CF, CR_LM, LSTUPD_D, LSTUPDUSR_CF, CRUW_NT)
			SELECT 	@lCrNf, @lCrUWYNf, '1', C.SSD_CF, C.ESB_CF, C.CR_LM, @gToday, @gUsrCf, 1
			FROM 	BTRT..TCR C
			WHERE	C.CR_NF = @lCrNf
			AND		C.CRUWY_NF = @lMaxCrUwyNf
		end
	end
	
	-- LOCTIE TCRCONTR
	SELECT @lRowsInter = Count(1) FROM BTRT..TCRCONTR WHERE CTR_NF = @lCtrNf AND UWY_NF = @lUwyNf AND CR_NF = @lCrNf AND CRUWY_NF = @lCrUWYNf AND CRUW_NT = 1
	
	if @lRowsInter = 0
	begin
		DELETE BTRT..TCRCONTR WHERE CTR_NF = @lCtrNf AND UWY_NF = @lUwyNf
		
		INSERT 	INTO BTRT..TCRCONTR (CTR_NF, UWY_NF, UW_NT, END_NT, CR_NF, CRUWY_NF, CRUW_NT, LNKTYP_CT, CRE_D, CREUSR_CF, LSTUPD_D, LSTUPDUSR_CF)
		SELECT	@lCtrNf, @lUwyNf, @lUwNt, @lEndNt, @lCrNf, @lCrUWYNf, 1, 'A', @gToday, @gUsrCf, @gToday, @gUsrCf 
	end
	
	SELECT @lNbUpdatedCr = @lNbUpdatedCr + 1
	FETCH CR_REALIGN_TRT INTO @lCtrNf, @lUwyNf, @lUwNt, @lEndNt, @lCrNf, @lCrUWYNf
end

CLOSE CR_REALIGN_TRT
DEALLOCATE CURSOR CR_REALIGN_TRT

UPDATE	#COUNTCHECK SET UPDATECOUNT = @lNbUpdatedCr WHERE STEP = 1

-- 	UPDATE 2 : Portfolios
UPDATE 	BTRT..TSECIFRS
SET		LOCIFRSSEG_CT 	= T.LOCIFRSSEG_CT,
		LSTUPD_D		= @gToday,
		LSTUPDUSR_CF 	= @gUsrCf
FROM	#TSECIFRS T,
		BTRT..TSECIFRS S
WHERE	T.CTR_NF  	= S.CTR_NF
AND		T.UWY_NF  	= S.UWY_NF
AND		T.SEC_NF 	= S.SEC_NF
AND		T.UPDIFRSSEG_B = 1

UPDATE	#COUNTCHECK SET UPDATECOUNT = @@Rowcount WHERE STEP = 2

-- 	UPDATE 3 : Initial Profitability
UPDATE 	BTRT..TSECIFRS
SET		LOCINIPRO_CF 	= T.LOCINIPRO_CF,
		LSTUPD_D		= @gToday,
		LSTUPDUSR_CF 	= @gUsrCf
FROM	#TSECIFRS T,
		BTRT..TSECIFRS S
WHERE	T.CTR_NF  	= S.CTR_NF
AND		T.UWY_NF  	= S.UWY_NF
AND		T.SEC_NF 	= S.SEC_NF
AND		T.UPDINIPRO_B = 1

UPDATE	#COUNTCHECK SET UPDATECOUNT = @@Rowcount WHERE STEP = 3

-- 	UPDATE 4 : Index Rate
UPDATE 	BTRT..TSECIFRS
SET		LOCRATEINDEX_CT = T.LOCRATEINDEX_CT,
		LSTUPD_D		= @gToday,
		LSTUPDUSR_CF 	= @gUsrCf
FROM	#TSECIFRS T,
		BTRT..TSECIFRS S
WHERE	T.CTR_NF  	= S.CTR_NF
AND		T.UWY_NF  	= S.UWY_NF
AND		T.SEC_NF 	= S.SEC_NF
AND		T.UPDRATEINDEX_B = 1

UPDATE	#COUNTCHECK SET UPDATECOUNT = @@Rowcount WHERE STEP = 4

-- 	UPDATE 5 : Closing Date
UPDATE 	BTRT..TSECIFRS
SET		LOCFIRCLO_D 	= T.LOCFIRCLO_D,
		LSTUPD_D		= @gToday,
		LSTUPDUSR_CF 	= @gUsrCf
FROM	#TSECIFRS T,
		BTRT..TSECIFRS S
WHERE	T.CTR_NF  	= S.CTR_NF
AND		T.UWY_NF  	= S.UWY_NF
AND		T.SEC_NF 	= S.SEC_NF
AND		T.UPDFIRCLO_B = 1

UPDATE	#COUNTCHECK SET UPDATECOUNT = @@Rowcount WHERE STEP = 5

-- 	UPDATE 6 : Inception status
UPDATE 	BTRT..TSECIFRS
SET		LOCINISTS_CT 	= T.LOCINISTS_CT,
		LSTUPD_D		= @gToday,
		LSTUPDUSR_CF 	= @gUsrCf
FROM	#TSECIFRS T,
		BTRT..TSECIFRS S
WHERE	T.CTR_NF  	= S.CTR_NF
AND		T.UWY_NF  	= S.UWY_NF
AND		T.SEC_NF 	= S.SEC_NF
AND		T.UPDINISTS_B = 1

UPDATE	#COUNTCHECK SET UPDATECOUNT = @@Rowcount WHERE STEP = 6

-- 	UPDATE 7 : CR FAC
SELECT @lNbUpdatedCr = 0

OPEN CR_REALIGN_FAC
FETCH CR_REALIGN_FAC INTO @lCtrNf, @lUwyNf, @lUwNt, @lEndNt, @lCrNf, @lCrUWYNf

WHILE @@SQLSTATUS != 2
begin
	-- LOCTIE TCR
	SELECT @lRowsInter = Count(1) FROM BFAC..TCR WHERE CR_NF = @lCrNf AND CRUWY_NF = @lCrUWYNf AND CRUW_NT = 1
	
	if @lRowsInter = 0
	begin
		SELECT @lMaxCrUwyNf = MAX(CRUWY_NF) FROM BFAC..TCR WHERE CR_NF = @lCrNf
		
		if @lMaxCrUwyNf is null
		begin
			-- Il faut recréer une CR de toute pièces
			INSERT INTO BFAC..TCR (CR_NF, CRUWY_NF, CRTYP_CT, SSD_CF, ESB_CF, CR_LM, LSTUPD_D, LSTUPDUSR_CF, CRUW_NT)
			SELECT @lCrNf, @lCrUWYNf, '1', C.SSD_CF, C.ACCESB_CF, Isnull(C.PRG_NF, C.CTR_NF), @gToday, @gUsrCf, 1
			FROM 	BFAC..TCONTR C
			WHERE	C.CTR_NF = @lCtrNf
			AND		C.UWY_NF = @lUwyNf
		end
		else
		begin
			-- Il faut recréer un nouvel exercice de la CR à LOCtir de celui trouvé
			INSERT INTO BFAC..TCR (CR_NF, CRUWY_NF, CRTYP_CT, SSD_CF, ESB_CF, CR_LM, LSTUPD_D, LSTUPDUSR_CF, CRUW_NT)
			SELECT 	@lCrNf, @lCrUWYNf, '1', C.SSD_CF, C.ESB_CF, C.CR_LM, @gToday, @gUsrCf, 1
			FROM 	BFAC..TCR C
			WHERE	C.CR_NF = @lCrNf
			AND		C.CRUWY_NF = @lMaxCrUwyNf
		end
	end
	
	-- LOCTIE TCRCONTR
	SELECT @lRowsInter = Count(1) FROM BFAC..TCRCONTR WHERE CTR_NF = @lCtrNf AND UWY_NF = @lUwyNf AND CR_NF = @lCrNf AND CRUWY_NF = @lCrUWYNf AND CRUW_NT = 1
	
	if @lRowsInter = 0
	begin
		DELETE BFAC..TCRCONTR WHERE CTR_NF = @lCtrNf AND UWY_NF = @lUwyNf
		
		INSERT 	INTO BFAC..TCRCONTR (CTR_NF, UWY_NF, UW_NT, END_NT, CR_NF, CRUWY_NF, CRUW_NT, LNKTYP_CT, CRE_D, CREUSR_CF, LSTUPD_D, LSTUPDUSR_CF)
		SELECT	@lCtrNf, @lUwyNf, @lUwNt, @lEndNt, @lCrNf, @lCrUWYNf, 1, 'A', @gToday, @gUsrCf, @gToday, @gUsrCf 
	end
	
	SELECT @lNbUpdatedCr = @lNbUpdatedCr + 1
	FETCH CR_REALIGN_FAC INTO @lCtrNf, @lUwyNf, @lUwNt, @lEndNt, @lCrNf, @lCrUWYNf
end

CLOSE CR_REALIGN_FAC
DEALLOCATE CURSOR CR_REALIGN_FAC

UPDATE	#COUNTCHECK SET UPDATECOUNT = @lNbUpdatedCr WHERE STEP = 7

-- 	UPDATE 8 : Portfolios
UPDATE 	BFAC..TSECIFRS
SET		LOCIFRSSEG_CT 	= T.LOCIFRSSEG_CT,
		LSTUPD_D		= @gToday,
		LSTUPDUSR_CF 	= @gUsrCf
FROM	#TSECIFRS T,
		BFAC..TSECIFRS S
WHERE	T.CTR_NF  	= S.CTR_NF
AND		T.UWY_NF  	= S.UWY_NF
AND 	T.UW_NT 	= S.UW_NT 
AND 	T.END_NT 	= S.END_NT
AND		T.SEC_NF 	= S.SEC_NF
AND		T.UPDIFRSSEG_B = 1

UPDATE	#COUNTCHECK SET UPDATECOUNT = @@Rowcount WHERE STEP = 8

-- 	UPDATE 9 : Initial Profitability
UPDATE 	BFAC..TSECIFRS
SET		LOCINIPRO_CF 	= T.LOCINIPRO_CF,
		LSTUPD_D		= @gToday,
		LSTUPDUSR_CF 	= @gUsrCf
FROM	#TSECIFRS T,
		BFAC..TSECIFRS S
WHERE	T.CTR_NF  	= S.CTR_NF
AND		T.UWY_NF  	= S.UWY_NF
AND 	T.UW_NT 	= S.UW_NT 
AND 	T.END_NT 	= S.END_NT
AND		T.SEC_NF 	= S.SEC_NF
AND		T.UPDINIPRO_B = 1

UPDATE	#COUNTCHECK SET UPDATECOUNT = @@Rowcount WHERE STEP = 9

-- 	UPDATE 10 : Index Rate
UPDATE 	BFAC..TSECIFRS
SET		LOCRATEINDEX_CT = T.LOCRATEINDEX_CT,
		LSTUPD_D		= @gToday,
		LSTUPDUSR_CF 	= @gUsrCf
FROM	#TSECIFRS T,
		BFAC..TSECIFRS S
WHERE	T.CTR_NF  	= S.CTR_NF
AND		T.UWY_NF  	= S.UWY_NF
AND 	T.UW_NT 	= S.UW_NT 
AND 	T.END_NT 	= S.END_NT
AND		T.SEC_NF 	= S.SEC_NF
AND		T.UPDRATEINDEX_B = 1

UPDATE	#COUNTCHECK SET UPDATECOUNT = @@Rowcount WHERE STEP = 10

-- 	UPDATE 11 : Closing Date
UPDATE 	BFAC..TSECIFRS
SET		LOCFIRCLO_D 	= T.LOCFIRCLO_D,
		LSTUPD_D		= @gToday,
		LSTUPDUSR_CF 	= @gUsrCf
FROM	#TSECIFRS T,
		BFAC..TSECIFRS S
WHERE	T.CTR_NF  	= S.CTR_NF
AND		T.UWY_NF  	= S.UWY_NF
AND 	T.UW_NT 	= S.UW_NT 
AND 	T.END_NT 	= S.END_NT
AND		T.SEC_NF 	= S.SEC_NF
AND		T.UPDFIRCLO_B = 1

UPDATE	#COUNTCHECK SET UPDATECOUNT = @@Rowcount WHERE STEP = 11

-- 	UPDATE 12 : Inception status
UPDATE 	BFAC..TSECIFRS
SET		LOCINISTS_CT 	= T.LOCINISTS_CT,
		LSTUPD_D		= @gToday,
		LSTUPDUSR_CF 	= @gUsrCf
FROM	#TSECIFRS T,
		BFAC..TSECIFRS S
WHERE	T.CTR_NF  	= S.CTR_NF
AND		T.UWY_NF  	= S.UWY_NF
AND 	T.UW_NT 	= S.UW_NT 
AND 	T.END_NT 	= S.END_NT
AND		T.SEC_NF 	= S.SEC_NF
AND		T.UPDINISTS_B = 1

UPDATE	#COUNTCHECK SET UPDATECOUNT = @@Rowcount WHERE STEP = 12

-- #########################################################################
-- 			SELECTIONS APRES UPDATE
-- #########################################################################

SELECT STEP, STEP_LBL, TMPSELECTCOUNT TABLETEMPO, SELECTCOUNT ATTENDU, TMPSELECTCOUNT - SELECTCOUNT DIFF_ATTENDU, UPDATECOUNT EFFECTUE FROM #COUNTCHECK

PRINT " ------------------ WARNING !!!!"
SELECT 	'Sections IFRS TRT inexistantes pour modification Portfolios', Count(1) FROM #TSECIFRS T WHERE T.UPDIFRSSEG_B = 1 AND T.CTR_TYP = 'TRT' 
AND		NOT EXISTS (SELECT 1 FROM BTRT..TSECIFRS S WHERE T.CTR_NF = S.CTR_NF AND T.UWY_NF = S.UWY_NF AND T.UW_NT = S.UW_NT AND T.END_NT = S.END_NT AND T.SEC_NF = S.SEC_NF)
UNION
SELECT 	'Sections IFRS TRT inexistantes pour modification Profitabilité Initiale', Count(1) FROM #TSECIFRS T WHERE T.UPDINIPRO_B = 1  AND T.CTR_TYP = 'TRT' 
AND		NOT EXISTS (SELECT 1 FROM BTRT..TSECIFRS S WHERE T.CTR_NF = S.CTR_NF AND T.UWY_NF = S.UWY_NF AND T.UW_NT = S.UW_NT AND T.END_NT = S.END_NT AND T.SEC_NF = S.SEC_NF)
UNION
SELECT 	'Sections IFRS TRT inexistantes pour modification Index Rate', Count(1) FROM #TSECIFRS T WHERE T.UPDRATEINDEX_B = 1  AND T.CTR_TYP = 'TRT' 
AND		NOT EXISTS (SELECT 1 FROM BTRT..TSECIFRS S WHERE T.CTR_NF = S.CTR_NF AND T.UWY_NF = S.UWY_NF AND T.UW_NT = S.UW_NT AND T.END_NT = S.END_NT AND T.SEC_NF = S.SEC_NF)
UNION
SELECT 	'Sections IFRS TRT inexistantes pour modification Closing Date', Count(1) FROM #TSECIFRS T WHERE T.UPDFIRCLO_B = 1  AND T.CTR_TYP = 'TRT' 
AND		NOT EXISTS (SELECT 1 FROM BTRT..TSECIFRS S WHERE T.CTR_NF = S.CTR_NF AND T.UWY_NF = S.UWY_NF AND T.UW_NT = S.UW_NT AND T.END_NT = S.END_NT AND T.SEC_NF = S.SEC_NF)
UNION
SELECT 	'Sections IFRS TRT inexistantes pour modification Statut', Count(1) FROM #TSECIFRS T WHERE T.UPDINISTS_B = 1  AND T.CTR_TYP = 'TRT' 
AND		NOT EXISTS (SELECT 1 FROM BTRT..TSECIFRS S WHERE T.CTR_NF = S.CTR_NF AND T.UWY_NF = S.UWY_NF AND T.UW_NT = S.UW_NT AND T.END_NT = S.END_NT AND T.SEC_NF = S.SEC_NF)
UNION
SELECT 	'Sections IFRS FAC inexistantes pour modification Portfolios', Count(1) FROM #TSECIFRS T WHERE T.UPDIFRSSEG_B = 1 AND T.CTR_TYP = 'FAC' 
AND		NOT EXISTS (SELECT 1 FROM BFAC..TSECIFRS S WHERE T.CTR_NF = S.CTR_NF AND T.UWY_NF = S.UWY_NF AND T.UW_NT = S.UW_NT AND T.END_NT = S.END_NT AND T.SEC_NF = S.SEC_NF)
UNION
SELECT 	'Sections IFRS FAC inexistantes pour modification Profitabilité Initiale', Count(1) FROM #TSECIFRS T WHERE T.UPDINIPRO_B = 1  AND T.CTR_TYP = 'FAC' 
AND		NOT EXISTS (SELECT 1 FROM BFAC..TSECIFRS S WHERE T.CTR_NF = S.CTR_NF AND T.UWY_NF = S.UWY_NF AND T.UW_NT = S.UW_NT AND T.END_NT = S.END_NT AND T.SEC_NF = S.SEC_NF)
UNION
SELECT 	'Sections IFRS FAC inexistantes pour modification Index Rate', Count(1) FROM #TSECIFRS T WHERE T.UPDRATEINDEX_B = 1  AND T.CTR_TYP = 'FAC' 
AND		NOT EXISTS (SELECT 1 FROM BFAC..TSECIFRS S WHERE T.CTR_NF = S.CTR_NF AND T.UWY_NF = S.UWY_NF AND T.UW_NT = S.UW_NT AND T.END_NT = S.END_NT AND T.SEC_NF = S.SEC_NF)
UNION
SELECT 	'Sections IFRS FAC inexistantes pour modification Closing Date', Count(1) FROM #TSECIFRS T WHERE T.UPDFIRCLO_B = 1  AND T.CTR_TYP = 'FAC' 
AND		NOT EXISTS (SELECT 1 FROM BFAC..TSECIFRS S WHERE T.CTR_NF = S.CTR_NF AND T.UWY_NF = S.UWY_NF AND T.UW_NT = S.UW_NT AND T.END_NT = S.END_NT AND T.SEC_NF = S.SEC_NF)
UNION
SELECT 	'Sections IFRS FAC inexistantes pour modification Statut', Count(1) FROM #TSECIFRS T WHERE T.UPDINISTS_B = 1  AND T.CTR_TYP = 'FAC' 
AND		NOT EXISTS (SELECT 1 FROM BFAC..TSECIFRS S WHERE T.CTR_NF = S.CTR_NF AND T.UWY_NF = S.UWY_NF AND T.UW_NT = S.UW_NT AND T.END_NT = S.END_NT AND T.SEC_NF = S.SEC_NF)

-- SELECT CTR_NF, UWY_NF, SEC_NF FROM #TSECIFRS T WHERE T.UPDIFRSSEG_B = 1 
-- AND		NOT EXISTS (SELECT 1 FROM BTRT..TSECIFRS S WHERE T.CTR_NF = S.CTR_NF AND T.UWY_NF = S.UWY_NF AND T.UW_NT = S.UW_NT AND T.END_NT = S.END_NT AND T.SEC_NF = S.SEC_NF)

SELECT 	@gUpdateControl = Count(1)
FROM	#COUNTCHECK
WHERE	SELECTCOUNT != UPDATECOUNT 

IF @gUpdateControl > 0
begin
	PRINT '****************************************************************************************'
	PRINT 'ISSUE : NUMBER OF UPDATED ROWS DIFFERENT FROM NUMBER OF ROWS TO UPDATE : PROCESS ABORTED'
	PRINT '****************************************************************************************'
	
	ROLLBACK TRAN
	GOTO FIN
end

IF @gCommit = 'O'
BEGIN
	COMMIT TRAN
	PRINT 'BTRT COMMIT SUCCESSFUL'
END
ELSE
BEGIN
	ROLLBACK TRAN
	PRINT 'BTRT ROLLBACK SUCCESSFUL'
END

fin:
SET NOCOUNT OFF

GO



