/* UBGL_ON */

USE BTRAV
go


IF OBJECT_ID('ESFD8000_TSECEBSINI') IS NOT NULL
BEGIN
    DROP TABLE ESFD8000_TSECEBSINI
    IF OBJECT_ID('ESFD8000_TSECEBSINI') IS NOT NULL
        PRINT '<<< FAILED DROPPING TABLE ESFD8000_TSECEBSINI >>>'
    ELSE
        PRINT '<<< DROPPED TABLE ESFD8000_TSECEBSINI >>>'
END
go
use BTRAV
go

create table ESFD8000_TSECEBSINI (
  CTR_NF UCTR_NF not null,
  UWY_NF UUWY_NF not null,
  UW_NT UUW_NT not null,
  END_NT UEND_NT not null,
  SEC_NF USEC_NF not null,
  LSTUPD_D UUPD_D null,
  LSTUPDUSR_CF UUPDUSR_CF null,
  SIIFIRCLO_D datetime null,  
  SIIINISTS_CT tinyint null  
)


go
GRANT SELECT ON ESFD8000_TSECEBSINI TO GCONSULT
go
GRANT DELETE ON ESFD8000_TSECEBSINI TO GOMEGA
go
GRANT INSERT ON ESFD8000_TSECEBSINI TO GOMEGA
go
GRANT SELECT ON ESFD8000_TSECEBSINI TO GOMEGA
go
GRANT UPDATE ON ESFD8000_TSECEBSINI TO GOMEGA
go
IF OBJECT_ID('ESFD8000_TSECEBSINI') IS NOT NULL
    PRINT '<<< CREATED TABLE ESFD8000_TSECEBSINI >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE ESFD8000_TSECEBSINI >>>'
go



/* UBGL_ON */

USE BTRAV
go


IF OBJECT_ID('ESFD8000_TRETEBSINI') IS NOT NULL
BEGIN
    DROP TABLE ESFD8000_TRETEBSINI
    IF OBJECT_ID('ESFD8000_TRETEBSINI') IS NOT NULL
        PRINT '<<< FAILED DROPPING TABLE ESFD8000_TRETEBSINI >>>'
    ELSE
        PRINT '<<< DROPPED TABLE ESFD8000_TRETEBSINI >>>'
END
go
use BTRAV
go


create table ESFD8000_TRETEBSINI (
  RETCTR_NF URETCTR_NF not null,
  RTY_NF UUWY_NF not null,
  LSTUPD_D datetime null,
  LSTUPDUSR_CF char(4) null,
  SIIFSTCLO_D datetime null, 
  SIIINISTS_CT tinyint null
)


go
GRANT SELECT ON ESFD8000_TRETEBSINI TO GCONSULT
go
GRANT DELETE ON ESFD8000_TRETEBSINI TO GOMEGA
go
GRANT INSERT ON ESFD8000_TRETEBSINI TO GOMEGA
go
GRANT SELECT ON ESFD8000_TRETEBSINI TO GOMEGA
go
GRANT UPDATE ON ESFD8000_TRETEBSINI TO GOMEGA
go
IF OBJECT_ID('ESFD8000_TRETEBSINI') IS NOT NULL
    PRINT '<<< CREATED TABLE ESFD8000_TRETEBSINI >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE ESFD8000_TRETEBSINI >>>'
go

