/* UBGL_ON */

USE BTRAV
go


IF OBJECT_ID('ESFD8000_TSECIFRS') IS NOT NULL
BEGIN
    DROP TABLE ESFD8000_TSECIFRS
    IF OBJECT_ID('ESFD8000_TSECIFRS') IS NOT NULL
        PRINT '<<< FAILED DROPPING TABLE ESFD8000_TSECIFRS >>>'
    ELSE
        PRINT '<<< DROPPED TABLE ESFD8000_TSECIFRS >>>'
END
go
use BTRAV
go

create table ESFD8000_TSECIFRS (
  CTR_NF UCTR_NF not null,
  UWY_NF UUWY_NF not null,
  UW_NT UUW_NT not null,
  END_NT UEND_NT not null,
  SEC_NF USEC_NF not null,
  PRISRC_CT UBANVAL_CT null,
  CTRPRI_B UBOOLEAN_B null,
  PRILR_R decimal(9, 8) null,
  EGPCUR_CF UCUR_CF null,
  PSTEGP_M decimal(18, 3) null,
  CUREGP_M decimal(18, 3) null,
  CANEGP_M decimal(18, 3) null,
  TTLEGP_M decimal(18, 3) null,
  GRPRATEINDEX_CT UL32 null,
  GRPFIRCLO_D datetime null,
  GRPIFRSSEG_CT USEG_NF null,
  GRPIFRSSEG_LL UL64 null,
  GRPINIPRO_CF UBANVAL_CT null,
  PARRATEINDEX_CT UL32 null,
  PARFIRCLO_D datetime null,
  PARIFRSSEG_CT USEG_NF null,
  PARIFRSSEG_LL UL64 null,
  PARINIPRO_CF UBANVAL_CT null,
  LOCRATEINDEX_CT UL32 null,
  LOCFIRCLO_D datetime null,
  LOCIFRSSEG_CT USEG_NF null,
  LOCIFRSSEG_LL UL64 null,
  LOCINIPRO_CF UBANVAL_CT null,
  CMT_NT UCMT_NT null,
  LSTUPD_D UUPD_D null,
  LSTUPDUSR_CF UUPDUSR_CF null,
  DIV_NT UDIV_NT null,
  GRPINISTS_CT tinyint null,
  PARINISTS_CT tinyint null,
  LOCINISTS_CT tinyint null,
  CTRTYP_CT varchar(4) null,
  RECOD_D UUPD_D null,
  GRPIFRSTRA_CT UBANVAL_CT null,
  PARIFRSTRA_CT UBANVAL_CT null,
  LOCIFRSTRA_CT UBANVAL_CT null
)


go
GRANT SELECT ON ESFD8000_TSECIFRS TO GCONSULT
go
GRANT DELETE ON ESFD8000_TSECIFRS TO GOMEGA
go
GRANT INSERT ON ESFD8000_TSECIFRS TO GOMEGA
go
GRANT SELECT ON ESFD8000_TSECIFRS TO GOMEGA
go
GRANT UPDATE ON ESFD8000_TSECIFRS TO GOMEGA
go
IF OBJECT_ID('ESFD8000_TSECIFRS') IS NOT NULL
    PRINT '<<< CREATED TABLE ESFD8000_TSECIFRS >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE ESFD8000_TSECIFRS >>>'
go



/* UBGL_ON */

USE BTRAV
go


IF OBJECT_ID('ESFD8000_TRETIFRS') IS NOT NULL
BEGIN
    DROP TABLE ESFD8000_TRETIFRS
    IF OBJECT_ID('ESFD8000_TRETIFRS') IS NOT NULL
        PRINT '<<< FAILED DROPPING TABLE ESFD8000_TRETIFRS >>>'
    ELSE
        PRINT '<<< DROPPED TABLE ESFD8000_TRETIFRS >>>'
END
go
use BTRAV
go


create table ESFD8000_TRETIFRS (
  RETCTR_NF URETCTR_NF not null,
  RTY_NF UUWY_NF not null,
  PRICEDCTR_B tinyint null,
  FOREWRITERLCK tinyint null,
  PRICINGTOOL_CT char(5) null,
  PRICEDLR_R decimal(9, 6) null,
  GRPRATEINDEX_CT char(32) null,
  GRPFSTCLO_D datetime null,
  PARRATEINDEX_CT char(32) null,
  PARFSTCLO_D datetime null,
  LCLRATEINDEX_CT char(32) null,
  LCLFSTCLO_D datetime null,
  CRE_D datetime null,
  CREUSR_CF char(4) null,
  RETVALIDIFRS_D datetime null,
  LSTUPD_D datetime null,
  LSTUPDUSR_CF char(4) null,
  GRPINISTS_CT tinyint null,
  PARINISTS_CT tinyint null,
  LOCINISTS_CT tinyint null,
  RETRECOD_D datetime null,
  RECOD_D UUPD_D null,
  GRPIFRSTRA_CT UBANVAL_CT null,
  PARIFRSTRA_CT UBANVAL_CT null,
  LOCIFRSTRA_CT UBANVAL_CT null
)


go
GRANT SELECT ON ESFD8000_TRETIFRS TO GCONSULT
go
GRANT DELETE ON ESFD8000_TRETIFRS TO GOMEGA
go
GRANT INSERT ON ESFD8000_TRETIFRS TO GOMEGA
go
GRANT SELECT ON ESFD8000_TRETIFRS TO GOMEGA
go
GRANT UPDATE ON ESFD8000_TRETIFRS TO GOMEGA
go
IF OBJECT_ID('ESFD8000_TRETIFRS') IS NOT NULL
    PRINT '<<< CREATED TABLE ESFD8000_TRETIFRS >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE ESFD8000_TRETIFRS >>>'
go


