USE BEST
GO

IF OBJECT_ID('dbo.PsSECIFRS_CR_01') IS NOT NULL
BEGIN
    DROP PROCEDURE dbo.PsSECIFRS_CR_01
    IF OBJECT_ID('dbo.PsSECIFRS_CR_01') IS NOT NULL
        PRINT '<<< FAILED DROPPING PROCEDURE dbo.PsSECIFRS_CR_01>>>'
    ELSE
        PRINT '<<< DROPPED PROCEDURE dbo.PsSECIFRS_CR_01>>>'
END
GO

create procedure dbo.PsSECIFRS_CR_01( 
@p_norme_cf char(4)
) with execute as caller as

/***************************************************
Domaine:                    Estimations
Base principale:            BEST
Version:                    1
Auteur:                     CAS
Date de creation:           08/02/2021
Description du programme:   Extract standard closing perimeter EST_IADPERICASE_STD with table Cloper by Norm
Conditions d'execution:        
Commentaires:               Spira 84719

Parametres:
    @p_norme_cf char(4)
				
_________________
MODIFICATIONS
[001] ART spira 102521 I17P/I17L- Pericase INI check on TI17CLOPER
*****************************************************/

DECLARE @erreur int
SELECT @erreur = 0


IF(@p_norme_cf = 'I17G')
BEGIN
-----------------------------
-- Périmètre pour les traités
-----------------------------
	SELECT 
	  SECIFRS.CTR_NF,
	  SECIFRS.END_NT,
	  SECIFRS.SEC_NF,
	  SECIFRS.UWY_NF,
	  SECIFRS.UW_NT,
	  SECIFRS.PRISRC_CT,
	  SECIFRS.CTRPRI_B,
	  SECIFRS.PRILR_R,
	  SECIFRS.EGPCUR_CF,
	  SECIFRS.PSTEGP_M,
	  SECIFRS.CUREGP_M,
	  SECIFRS.CANEGP_M,
	  SECIFRS.TTLEGP_M,
	  SECIFRS.GRPRATEINDEX_CT,
	  SECIFRS.GRPFIRCLO_D,
	  SECIFRS.GRPIFRSSEG_CT,
	  SECIFRS.GRPINIPRO_CF,
	  SECIFRS.PARRATEINDEX_CT,
	  SECIFRS.PARFIRCLO_D,
	  SECIFRS.PARIFRSSEG_CT,
	  SECIFRS.PARINIPRO_CF,
	  SECIFRS.LOCRATEINDEX_CT,
	  SECIFRS.LOCFIRCLO_D,
	  SECIFRS.LOCIFRSSEG_CT,
	  SECIFRS.LOCINIPRO_CF,
	  SECIFRS.DIV_NT UDIV_NT,
	  SECIFRS.GRPINISTS_CT,
	  SECIFRS.PARINISTS_CT,
	  SECIFRS.LOCINISTS_CT,
	  CR.CR_NF,
	  CR.CRTYP_CT,
	  CR.SSD_CF,
	  CR.ESB_CF,
	  CR.CROBJ_NF,
	  CR.IFRSLOB_CF,
	  CR.IFRSLOBEGP_R,
	  CR.GRPFIRCLO_D,
	  CR.PARFIRCLO_D,
	  CR.LOCFIRCLO_D,
	  CR.GRPIFRSLOBEGP_R,
	  CR.PARIFRSLOBEGP_R,
	  CR.LOCIFRSLOBEGP_R,
	  CR.GRPIFRSLOB_CF,
	  CR.PARIFRSLOB_CF,
	  CR.LOCIFRSLOB_CF,
	  CR.CRUW_NT,
	  CR.CRUWY_NF,
	  CONTR.MULTUWY_NF,
	  NULL,
	  NULL,
	  NULL  
	from BTRT..TSECIFRS SECIFRS
	JOIN BTRT..TSECTION SEC
	  on  SECIFRS.CTR_NF=SEC.CTR_NF
	  and SECIFRS.END_NT=SEC.END_NT
	  and SECIFRS.UWY_NF=SEC.UWY_NF
	  and SECIFRS.UW_NT=SEC.UW_NT
	  and SECIFRS.SEC_NF=SEC.SEC_NF
	JOIN BREF..TBATCHSSD BATCHSSD
	  on  SEC.SSD_CF=BATCHSSD.SSD_CF
	  and BATCHSSD.BATCHUSER_CF=suser_name()
	LEFT OUTER JOIN BTRT..TCRCONTR CRCONTR
	  on  SECIFRS.CTR_NF=CRCONTR.CTR_NF
	  and SECIFRS.END_NT=CRCONTR.END_NT
	  and SECIFRS.UWY_NF=CRCONTR.UWY_NF
	  and SECIFRS.UW_NT=CRCONTR.UW_NT
	LEFT OUTER JOIN BTRT..TCR CR
	  on  CRCONTR.CR_NF=CR.CR_NF
	  and CRCONTR.CRUWY_NF=CR.CRUWY_NF
	  and CRCONTR.CRUW_NT=CR.CRUW_NT
	JOIN BTRT..TCONTR CONTR
	  on  SECIFRS.CTR_NF=CONTR.CTR_NF
	  and SECIFRS.END_NT=CONTR.END_NT
	  and SECIFRS.UWY_NF=CONTR.UWY_NF
	  and SECIFRS.UW_NT=CONTR.UW_NT

	UNION
-----------------------------
-- Périmètre pour les facs
-----------------------------
	SELECT 
	  SECIFRS.CTR_NF,
	  SECIFRS.END_NT,
	  SECIFRS.SEC_NF,
	  SECIFRS.UWY_NF,
	  SECIFRS.UW_NT,
	  SECIFRS.PRISRC_CT,
	  SECIFRS.CTRPRI_B,
	  SECIFRS.PRILR_R,
	  SECIFRS.EGPCUR_CF,
	  SECIFRS.PSTEGP_M,
	  SECIFRS.CUREGP_M,
	  SECIFRS.CANEGP_M,
	  SECIFRS.TTLEGP_M,
	  SECIFRS.GRPRATEINDEX_CT,
	  SECIFRS.GRPFIRCLO_D,
	  SECIFRS.GRPIFRSSEG_CT,
	  SECIFRS.GRPINIPRO_CF,
	  SECIFRS.PARRATEINDEX_CT,
	  SECIFRS.PARFIRCLO_D,
	  SECIFRS.PARIFRSSEG_CT,
	  SECIFRS.PARINIPRO_CF,
	  SECIFRS.LOCRATEINDEX_CT,
	  SECIFRS.LOCFIRCLO_D,
	  SECIFRS.LOCIFRSSEG_CT,
	  SECIFRS.LOCINIPRO_CF,
	  SECIFRS.DIV_NT UDIV_NT,
	  SECIFRS.GRPINISTS_CT,
	  SECIFRS.PARINISTS_CT,
	  SECIFRS.LOCINISTS_CT,
	  CR.CR_NF,
	  CR.CRTYP_CT,
	  CR.SSD_CF,
	  CR.ESB_CF,
	  CR.CROBJ_NF,
	  CR.IFRSLOB_CF,
	  CR.IFRSLOBEGP_R,
	  CR.GRPFIRCLO_D,
	  CR.PARFIRCLO_D,
	  CR.LOCFIRCLO_D,
	  CR.GRPIFRSLOBEGP_R,
	  CR.PARIFRSLOBEGP_R,
	  CR.LOCIFRSLOBEGP_R,
	  CR.GRPIFRSLOB_CF,
	  CR.PARIFRSLOB_CF,
	  CR.LOCIFRSLOB_CF,
	  CR.CRUW_NT,
	  CR.CRUWY_NF,
	  NULL,
	  NULL,
	  NULL,
	  NULL
	from BFAC..TSECIFRS SECIFRS
	JOIN BFAC..TSECTION SEC
	  on  SECIFRS.CTR_NF=SEC.CTR_NF
	  and SECIFRS.END_NT=SEC.END_NT
	  and SECIFRS.UWY_NF=SEC.UWY_NF
	  and SECIFRS.UW_NT=SEC.UW_NT
	  and SECIFRS.SEC_NF=SEC.SEC_NF
	JOIN BREF..TBATCHSSD BATCHSSD
	  on  SEC.SSD_CF=BATCHSSD.SSD_CF
	  and BATCHSSD.BATCHUSER_CF=suser_name()
	LEFT OUTER JOIN BFAC..TCRCONTR CRCONTR
	  on  SECIFRS.CTR_NF=CRCONTR.CTR_NF
	  and SECIFRS.END_NT=CRCONTR.END_NT
	  and SECIFRS.UWY_NF=CRCONTR.UWY_NF
	  and SECIFRS.UW_NT=CRCONTR.UW_NT
	LEFT OUTER JOIN BFAC..TCR CR
	  on  CRCONTR.CR_NF=CR.CR_NF
	  and CRCONTR.CRUWY_NF=CR.CRUWY_NF
	  and CRCONTR.CRUW_NT=CR.CRUW_NT
END

IF(@p_norme_cf = 'I17P')
BEGIN
-----------------------------
-- Périmètre pour les traités
-----------------------------
	SELECT 
	  SECIFRS.CTR_NF,
	  SECIFRS.END_NT,
	  SECIFRS.SEC_NF,
	  SECIFRS.UWY_NF,
	  SECIFRS.UW_NT,
	  SECIFRS.PRISRC_CT,
	  SECIFRS.CTRPRI_B,
	  SECIFRS.PRILR_R,
	  SECIFRS.EGPCUR_CF,
	  SECIFRS.PSTEGP_M,
	  SECIFRS.CUREGP_M,
	  SECIFRS.CANEGP_M,
	  SECIFRS.TTLEGP_M,
	  SECIFRS.GRPRATEINDEX_CT,
	  SECIFRS.GRPFIRCLO_D,
	  SECIFRS.GRPIFRSSEG_CT,
	  SECIFRS.GRPINIPRO_CF,
	  SECIFRS.PARRATEINDEX_CT,
	  SECIFRS.PARFIRCLO_D,
	  SECIFRS.PARIFRSSEG_CT,
	  SECIFRS.PARINIPRO_CF,
	  SECIFRS.LOCRATEINDEX_CT,
	  SECIFRS.LOCFIRCLO_D,
	  SECIFRS.LOCIFRSSEG_CT,
	  SECIFRS.LOCINIPRO_CF,
	  SECIFRS.DIV_NT UDIV_NT,
	  SECIFRS.GRPINISTS_CT,
	  SECIFRS.PARINISTS_CT,
	  SECIFRS.LOCINISTS_CT,
	  CR.CR_NF,
	  CR.CRTYP_CT,
	  CR.SSD_CF,
	  CR.ESB_CF,
	  CR.CROBJ_NF,
	  CR.IFRSLOB_CF,
	  CR.IFRSLOBEGP_R,
	  CR.GRPFIRCLO_D,
	  CR.PARFIRCLO_D,
	  CR.LOCFIRCLO_D,
	  CR.GRPIFRSLOBEGP_R,
	  CR.PARIFRSLOBEGP_R,
	  CR.LOCIFRSLOBEGP_R,
	  CR.GRPIFRSLOB_CF,
	  CR.PARIFRSLOB_CF,
	  CR.LOCIFRSLOB_CF,
	  CR.CRUW_NT,
	  CR.CRUWY_NF,
	  CONTR.MULTUWY_NF,
	  NULL,
	  NULL,
	  NULL  
	from BTRT..TSECIFRS SECIFRS
	JOIN BTRT..TSECTION SEC
	  on  SECIFRS.CTR_NF=SEC.CTR_NF
	  and SECIFRS.END_NT=SEC.END_NT
	  and SECIFRS.UWY_NF=SEC.UWY_NF
	  and SECIFRS.UW_NT=SEC.UW_NT
	  and SECIFRS.SEC_NF=SEC.SEC_NF
	JOIN BREF..TBATCHSSD BATCHSSD
	  on  SEC.SSD_CF=BATCHSSD.SSD_CF
	  and BATCHSSD.BATCHUSER_CF=suser_name()
	LEFT OUTER JOIN BTRT..TCRCONTR CRCONTR
	  on  SECIFRS.CTR_NF=CRCONTR.CTR_NF
	  and SECIFRS.END_NT=CRCONTR.END_NT
	  and SECIFRS.UWY_NF=CRCONTR.UWY_NF
	  and SECIFRS.UW_NT=CRCONTR.UW_NT
	LEFT OUTER JOIN BTRT..TCR CR
	  on  CRCONTR.CR_NF=CR.CR_NF
	  and CRCONTR.CRUWY_NF=CR.CRUWY_NF
	  and CRCONTR.CRUW_NT=CR.CRUW_NT
	JOIN BTRT..TCONTR CONTR
		on  SECIFRS.CTR_NF=CONTR.CTR_NF
		and SECIFRS.END_NT=CONTR.END_NT
		and SECIFRS.UWY_NF=CONTR.UWY_NF
		and SECIFRS.UW_NT=CONTR.UW_NT
	JOIN BEST..TI17CLOPER CLO
		on SEC.SSD_CF = CLO.SSD_CF  --[001]
		and CONTR.ACCESB_CF = CLO.ESB_CF
	WHERE CLO.PARM1 = '1'

	UNION
-----------------------------
-- Périmètre pour les facs
-----------------------------
	SELECT 
	  SECIFRS.CTR_NF,
	  SECIFRS.END_NT,
	  SECIFRS.SEC_NF,
	  SECIFRS.UWY_NF,
	  SECIFRS.UW_NT,
	  SECIFRS.PRISRC_CT,
	  SECIFRS.CTRPRI_B,
	  SECIFRS.PRILR_R,
	  SECIFRS.EGPCUR_CF,
	  SECIFRS.PSTEGP_M,
	  SECIFRS.CUREGP_M,
	  SECIFRS.CANEGP_M,
	  SECIFRS.TTLEGP_M,
	  SECIFRS.GRPRATEINDEX_CT,
	  SECIFRS.GRPFIRCLO_D,
	  SECIFRS.GRPIFRSSEG_CT,
	  SECIFRS.GRPINIPRO_CF,
	  SECIFRS.PARRATEINDEX_CT,
	  SECIFRS.PARFIRCLO_D,
	  SECIFRS.PARIFRSSEG_CT,
	  SECIFRS.PARINIPRO_CF,
	  SECIFRS.LOCRATEINDEX_CT,
	  SECIFRS.LOCFIRCLO_D,
	  SECIFRS.LOCIFRSSEG_CT,
	  SECIFRS.LOCINIPRO_CF,
	  SECIFRS.DIV_NT UDIV_NT,
	  SECIFRS.GRPINISTS_CT,
	  SECIFRS.PARINISTS_CT,
	  SECIFRS.LOCINISTS_CT,
	  CR.CR_NF,
	  CR.CRTYP_CT,
	  CR.SSD_CF,
	  CR.ESB_CF,
	  CR.CROBJ_NF,
	  CR.IFRSLOB_CF,
	  CR.IFRSLOBEGP_R,
	  CR.GRPFIRCLO_D,
	  CR.PARFIRCLO_D,
	  CR.LOCFIRCLO_D,
	  CR.GRPIFRSLOBEGP_R,
	  CR.PARIFRSLOBEGP_R,
	  CR.LOCIFRSLOBEGP_R,
	  CR.GRPIFRSLOB_CF,
	  CR.PARIFRSLOB_CF,
	  CR.LOCIFRSLOB_CF,
	  CR.CRUW_NT,
	  CR.CRUWY_NF,
	  NULL,
	  NULL,
	  NULL,
	  NULL
	from BFAC..TSECIFRS SECIFRS
	JOIN BFAC..TSECTION SEC
	  on  SECIFRS.CTR_NF=SEC.CTR_NF
	  and SECIFRS.END_NT=SEC.END_NT
	  and SECIFRS.UWY_NF=SEC.UWY_NF
	  and SECIFRS.UW_NT=SEC.UW_NT
	  and SECIFRS.SEC_NF=SEC.SEC_NF
	JOIN BREF..TBATCHSSD BATCHSSD
	  on  SEC.SSD_CF=BATCHSSD.SSD_CF
	  and BATCHSSD.BATCHUSER_CF=suser_name()
	LEFT OUTER JOIN BFAC..TCRCONTR CRCONTR
	  on  SECIFRS.CTR_NF=CRCONTR.CTR_NF
	  and SECIFRS.END_NT=CRCONTR.END_NT
	  and SECIFRS.UWY_NF=CRCONTR.UWY_NF
	  and SECIFRS.UW_NT=CRCONTR.UW_NT
	LEFT OUTER JOIN BFAC..TCR CR
	  on  CRCONTR.CR_NF=CR.CR_NF
	  and CRCONTR.CRUWY_NF=CR.CRUWY_NF
	  and CRCONTR.CRUW_NT=CR.CRUW_NT
	JOIN BFAC..TCONTR CONTR
	  on  SECIFRS.CTR_NF=CONTR.CTR_NF
	  and SECIFRS.END_NT=CONTR.END_NT
	  and SECIFRS.UWY_NF=CONTR.UWY_NF
	  and SECIFRS.UW_NT=CONTR.UW_NT
	JOIN BEST..TI17CLOPER CLO
	  on SEC.SSD_CF = CLO.SSD_CF --[001]
	  and CONTR.ACCESB_CF = CLO.ESB_CF
	WHERE CLO.PARM1 = '1'
END

IF(@p_norme_cf = 'I17L')
BEGIN
-----------------------------
-- Périmètre pour les traités
-----------------------------
	SELECT 
	  SECIFRS.CTR_NF,
	  SECIFRS.END_NT,
	  SECIFRS.SEC_NF,
	  SECIFRS.UWY_NF,
	  SECIFRS.UW_NT,
	  SECIFRS.PRISRC_CT,
	  SECIFRS.CTRPRI_B,
	  SECIFRS.PRILR_R,
	  SECIFRS.EGPCUR_CF,
	  SECIFRS.PSTEGP_M,
	  SECIFRS.CUREGP_M,
	  SECIFRS.CANEGP_M,
	  SECIFRS.TTLEGP_M,
	  SECIFRS.GRPRATEINDEX_CT,
	  SECIFRS.GRPFIRCLO_D,
	  SECIFRS.GRPIFRSSEG_CT,
	  SECIFRS.GRPINIPRO_CF,
	  SECIFRS.PARRATEINDEX_CT,
	  SECIFRS.PARFIRCLO_D,
	  SECIFRS.PARIFRSSEG_CT,
	  SECIFRS.PARINIPRO_CF,
	  SECIFRS.LOCRATEINDEX_CT,
	  SECIFRS.LOCFIRCLO_D,
	  SECIFRS.LOCIFRSSEG_CT,
	  SECIFRS.LOCINIPRO_CF,
	  SECIFRS.DIV_NT UDIV_NT,
	  SECIFRS.GRPINISTS_CT,
	  SECIFRS.PARINISTS_CT,
	  SECIFRS.LOCINISTS_CT,
	  CR.CR_NF,
	  CR.CRTYP_CT,
	  CR.SSD_CF,
	  CR.ESB_CF,
	  CR.CROBJ_NF,
	  CR.IFRSLOB_CF,
	  CR.IFRSLOBEGP_R,
	  CR.GRPFIRCLO_D,
	  CR.PARFIRCLO_D,
	  CR.LOCFIRCLO_D,
	  CR.GRPIFRSLOBEGP_R,
	  CR.PARIFRSLOBEGP_R,
	  CR.LOCIFRSLOBEGP_R,
	  CR.GRPIFRSLOB_CF,
	  CR.PARIFRSLOB_CF,
	  CR.LOCIFRSLOB_CF,
	  CR.CRUW_NT,
	  CR.CRUWY_NF,
	  CONTR.MULTUWY_NF,
	  NULL,
	  NULL,
	  NULL  
	from BTRT..TSECIFRS SECIFRS
	JOIN BTRT..TSECTION SEC
	  on  SECIFRS.CTR_NF=SEC.CTR_NF
	  and SECIFRS.END_NT=SEC.END_NT
	  and SECIFRS.UWY_NF=SEC.UWY_NF
	  and SECIFRS.UW_NT=SEC.UW_NT
	  and SECIFRS.SEC_NF=SEC.SEC_NF
	JOIN BREF..TBATCHSSD BATCHSSD
	  on  SEC.SSD_CF=BATCHSSD.SSD_CF
	  and BATCHSSD.BATCHUSER_CF=suser_name()
	LEFT OUTER JOIN BTRT..TCRCONTR CRCONTR
	  on  SECIFRS.CTR_NF=CRCONTR.CTR_NF
	  and SECIFRS.END_NT=CRCONTR.END_NT
	  and SECIFRS.UWY_NF=CRCONTR.UWY_NF
	  and SECIFRS.UW_NT=CRCONTR.UW_NT
	LEFT OUTER JOIN BTRT..TCR CR
	  on  CRCONTR.CR_NF=CR.CR_NF
	  and CRCONTR.CRUWY_NF=CR.CRUWY_NF
	  and CRCONTR.CRUW_NT=CR.CRUW_NT
	JOIN BTRT..TCONTR CONTR
	  on  SECIFRS.CTR_NF=CONTR.CTR_NF
	  and SECIFRS.END_NT=CONTR.END_NT
	  and SECIFRS.UWY_NF=CONTR.UWY_NF
	  and SECIFRS.UW_NT=CONTR.UW_NT
	JOIN BEST..TI17CLOPER CLO
	  on SEC.SSD_CF = CLO.SSD_CF --[001]
	  and CONTR.ACCESB_CF = CLO.ESB_CF
	WHERE CLO.PARM2 = '1'

	UNION
-----------------------------
-- Périmètre pour les facs
-----------------------------
	SELECT 
	  SECIFRS.CTR_NF,
	  SECIFRS.END_NT,
	  SECIFRS.SEC_NF,
	  SECIFRS.UWY_NF,
	  SECIFRS.UW_NT,
	  SECIFRS.PRISRC_CT,
	  SECIFRS.CTRPRI_B,
	  SECIFRS.PRILR_R,
	  SECIFRS.EGPCUR_CF,
	  SECIFRS.PSTEGP_M,
	  SECIFRS.CUREGP_M,
	  SECIFRS.CANEGP_M,
	  SECIFRS.TTLEGP_M,
	  SECIFRS.GRPRATEINDEX_CT,
	  SECIFRS.GRPFIRCLO_D,
	  SECIFRS.GRPIFRSSEG_CT,
	  SECIFRS.GRPINIPRO_CF,
	  SECIFRS.PARRATEINDEX_CT,
	  SECIFRS.PARFIRCLO_D,
	  SECIFRS.PARIFRSSEG_CT,
	  SECIFRS.PARINIPRO_CF,
	  SECIFRS.LOCRATEINDEX_CT,
	  SECIFRS.LOCFIRCLO_D,
	  SECIFRS.LOCIFRSSEG_CT,
	  SECIFRS.LOCINIPRO_CF,
	  SECIFRS.DIV_NT UDIV_NT,
	  SECIFRS.GRPINISTS_CT,
	  SECIFRS.PARINISTS_CT,
	  SECIFRS.LOCINISTS_CT,
	  CR.CR_NF,
	  CR.CRTYP_CT,
	  CR.SSD_CF,
	  CR.ESB_CF,
	  CR.CROBJ_NF,
	  CR.IFRSLOB_CF,
	  CR.IFRSLOBEGP_R,
	  CR.GRPFIRCLO_D,
	  CR.PARFIRCLO_D,
	  CR.LOCFIRCLO_D,
	  CR.GRPIFRSLOBEGP_R,
	  CR.PARIFRSLOBEGP_R,
	  CR.LOCIFRSLOBEGP_R,
	  CR.GRPIFRSLOB_CF,
	  CR.PARIFRSLOB_CF,
	  CR.LOCIFRSLOB_CF,
	  CR.CRUW_NT,
	  CR.CRUWY_NF,
	  NULL,
	  NULL,
	  NULL,
	  NULL
	from BFAC..TSECIFRS SECIFRS
	JOIN BFAC..TSECTION SEC
	  on  SECIFRS.CTR_NF=SEC.CTR_NF
	  and SECIFRS.END_NT=SEC.END_NT
	  and SECIFRS.UWY_NF=SEC.UWY_NF
	  and SECIFRS.UW_NT=SEC.UW_NT
	  and SECIFRS.SEC_NF=SEC.SEC_NF
	JOIN BREF..TBATCHSSD BATCHSSD
	  on  SEC.SSD_CF=BATCHSSD.SSD_CF
	  and BATCHSSD.BATCHUSER_CF=suser_name()
	LEFT OUTER JOIN BFAC..TCRCONTR CRCONTR
	  on  SECIFRS.CTR_NF=CRCONTR.CTR_NF
	  and SECIFRS.END_NT=CRCONTR.END_NT
	  and SECIFRS.UWY_NF=CRCONTR.UWY_NF
	  and SECIFRS.UW_NT=CRCONTR.UW_NT
	LEFT OUTER JOIN BFAC..TCR CR
	  on  CRCONTR.CR_NF=CR.CR_NF
	  and CRCONTR.CRUWY_NF=CR.CRUWY_NF
	  and CRCONTR.CRUW_NT=CR.CRUW_NT
		JOIN BFAC..TCONTR CONTR
	  on  SECIFRS.CTR_NF=CONTR.CTR_NF
	  and SECIFRS.END_NT=CONTR.END_NT
	  and SECIFRS.UWY_NF=CONTR.UWY_NF
	  and SECIFRS.UW_NT=CONTR.UW_NT
	JOIN BEST..TI17CLOPER CLO
	  on SEC.SSD_CF = CLO.SSD_CF --[001]
	  and CONTR.ACCESB_CF = CLO.ESB_CF
	WHERE CLO.PARM2 = '1'
END

SELECT @erreur = @@error
IF @erreur != 0
BEGIN
    RETURN @erreur
END

RETURN 0
GO

IF OBJECT_ID('dbo.PsSECIFRS_CR_01') IS NOT NULL
    PRINT '<<< CREATED PROCEDURE dbo.PsSECIFRS_CR_01 >>>'
ELSE
    PRINT '<<< FAILED CREATING PROCEDURE dbo.PsSECIFRS_CR_01 >>>'
GO

GRANT EXECUTE ON dbo.PsSECIFRS_CR_01 TO GOMEGA
GO

GRANT EXECUTE ON dbo.PsSECIFRS_CR_01 TO GDBBATCH
GO
