#!/bin/ksh
#---------------------------------------------------------------
# Fichier :   LOAD.ksh
# Log     :   
# Auteur  :   G.Defendini
# Date    :   26.10.2009
# Modif   :   
# But     :  load data from flat file to database 
# Usage   :  
#
#LOAD_I: Path and name of Input File
#LOAD_SCHEMA: destination schema
#LOAD_TABLE: Name of table to fill up
#LOAD_MODE : truncate or append (default append, optional)
#LOAD_CTL: if set, will use the defined control file (optional)
#LOAD_BAD: file wich contains all bad rows (optional) 
#LOAD_DIRECT: if set, will use the direct load functionality (optionnal)
#LOAD_FS: field separator of the input file (default: '~', optionnal)
#LOAD_RS: row separator of the infout file (default: '\n', optionnal)
#
# Modifications
# [01] Charbel 24/11/2014 :spot:27422 migration Linux, modif EORUN_SQL utilisation de $Var_var à la place de l'echo
#--------------------------------------------------------------

LOAD ()
{
if [ "${RP}" = ""  -o "${RP}" = "${NSTEP}" -o "${ADT}" != "" ]
then

    ADT="${NSTEP}"
    STEP_PRG=LOAD
    STEPSTART

   [ "${FCT_DEBUG}" = "YES" ] && set -x

    # Set date format
    if [ -z "$NLS_DATE_FORMAT" ]
    then
        export NLS_DATE_FORMAT='YYYY-MM-DD HH24:MI:SS'
    fi

    # define ANO filename
    LOAD_LOG=${DFILT}/${NSTEP}_${IB}_LOAD.log
    LOAD_ANO=${DFILT}/${NSTEP}_${IB}_LOAD.ano

    export PRGANO=${NSTEP}_${IB}_LOAD.ano
    export PRGLOG=${NSTEP}_${IB}_LOAD.log

   [ "${FCT_DEBUG}" = "YES" ] && set -x

    # Check input parameters
    if [ -z "${LOAD_I}" ]
    then
        echo "# ERROR: LOAD_I variable must be set"
        STEPEND 99
    fi 

    if [ -z "${LOAD_SCHEMA}" ]
    then
        echo "# ERROR: LOAD_SCHEMA variable must be set"
        STEPEND 99
    fi
    if [ -z "${LOAD_TABLE}" ]
    then
        echo "# ERROR: LOAD_TABLE variable must be set"
        STEPEND 99
    fi 

    if [ -z "${LOAD_MODE}" -o "${LOAD_MODE}" != "TRUNCATE" ]
    then
        LOAD_MODE="APPEND"
    fi

    if [ -z "${LOAD_DATE_FORMAT}" -a -n "${NLS_DATE_FORMAT}" ]
    then
        LOAD_DATE_FORMAT="${NLS_DATE_FORMAT}"
    fi

    export LOAD_DATE_FORMAT

    if [ -z "${LOAD_FS}" ]
    then
        LOAD_FS="~"
    fi 

    # Generate control file
    if [  -z  "${LOAD_CTL}" ]
    then
        # Control file
        LOAD_CTL=`CFTMP`

        # generate ctl file
        SQLPLUS_I=-
        SQLPLUS_SCHEMA=${LOAD_SCHEMA}
        SQLPLUS_SPOOL=YES
        SQLPLUS_O=${LOAD_CTL}
   
		if [ "${LOAD_DATE_FORMAT}" = "SYBASE" ]
		then
	  	 Var_Var=`echo "decode (a.data_type,'DATE','my_to_date(:'||(a.column_name) ||')') ||"`
		else
		   Var_Var=`echo "decode (a.data_type,'DATE','DATE \"${LOAD_DATE_FORMAT}\"' ) ||"`
		fi
		

        RUN_SQL <<-EORUN_SQL
		alter session set current_schema=${LOAD_SCHEMA};

		select 
		'load data 
		infile '||'''${LOAD_I}'''||' 
		${LOAD_MODE}
		into table ' || upper('${LOAD_SCHEMA}') || '.' || upper('${LOAD_TABLE}') || '
		fields terminated by ''${LOAD_FS}''' || '
		trailing nullcols' 
		from all_tables where owner = upper('${LOAD_SCHEMA}') and table_name = upper('${LOAD_TABLE}')
		;

		select decode(a.column_id, '1', '(') || a.column_name ||' '||
                $Var_Var
		' NULLIF '|| a.column_name||'=BLANKS '||
		(case when a.column_id < max(b.column_id) then ',' else ')' END)
		from all_tab_columns a, all_tab_columns b
		where a.owner = upper('${LOAD_SCHEMA}') and a.table_name = upper('${LOAD_TABLE}') and
		b.owner = upper('${LOAD_SCHEMA}') and b.table_name = upper('${LOAD_TABLE}')
		group by a.column_name, a.column_id,a.data_type
		order by a.column_id
		;
		EORUN_SQL
        RUN_SQL_ERR=$?

        [ "${FCT_DEBUG}" = "YES" ] && cat $LOAD_CTL >&2

        if [ ${RUN_SQL_ERR}  -ne 0 ]
        then
            echo "# ERROR: control file generation failed"
            unset LOAD_I LOAD_SCHEMA LOAD_TABLE LOAD_MODE LOAD_DATE_FORMAT  LOAD_CTL LOAD_DIRECT LOAD_ARGS
            STEPEND ${RUN_SQL_ERR}
        fi
    fi

    #conventional load or direct path load
    if [ "${LOAD_DIRECT}" = "YES" ]
    then
        LOAD_ARGS="direct='TRUE'"
    fi

    # Bad file??
    if [ -n "${LOAD_BAD}" ]
    then
        LOAD_ARGS="${LOAD_ARGS} badfile=${LOAD_BAD}"
    fi
    cat ${LOAD_CTL} >&2
    ${ORACLE_HOME}/bin/sqlldr ${ORA_USR}/${ORA_PSWD}@${ORA} \
        control=${LOAD_CTL} ${LOAD_ARGS} log=${LOAD_LOG} silent='all' 2> ${LOAD_ANO}
    RC=$?

    if [ ${RC} != 0 ]
    then
        echo "# "`grep "Elapsed time was:" ${LOAD_LOG}`
        cat ${LOAD_LOG} >> ${DFILT}/${PRGANO}
        rm ${LOAD_LOG} >/dev/null 2>&1
    else
        echo "# "`grep "Rows successfully loaded." ${LOAD_LOG}`
        echo "# "`grep "Elapsed time was:" ${LOAD_LOG}`
        rm ${LOAD_LOG}
    fi

    # Cleanup
    [ -s "${DFILT}/${PRGANO}" ] || rm ${DFILT}/${PRGANO} 2>/dev/null

    unset LOAD_I LOAD_SCHEMA LOAD_TABLE LOAD_MODE LOAD_DATE_FORMAT LOAD_CTL LOAD_DIRECT LOAD_ARGS
    STEPEND ${RC}

fi

}

