[properties]
root_delivery="/scor/scoromega/delivery/3I_DELIVERY/"
root_dev="/scor/scoromega/delivery/3I_DEV/"
listComponentsFile="/scor/scoromega/delivery/3I_DELIVERY/OM2.DELIVERY/OM2.3I_ListOfJAVACommit.csv"
branches=http://dcvprdsvn/refsvn/OMEGA-2/branches/3I_DELIVERY/
branches2=http://dcvprdsvn.eu.scor.local/refsvn/OMEGA-2/branches/3I_DELIVERY/
status=TBC
