[properties]
root_delivery="/scor/scoromega/delivery/4D_DELIVERY/"
listComponentsFile="/scor/scoromega/delivery/4D_DELIVERY/OM2.DELIVERY/OM2.4D_DELIVERY_AZCNV.csv"
branches=http://dcvprdsvn/refsvn/OMEGA-2/branches/4D_DEV/omega2-sql/global/
branches2=http://dcvprdsvn.eu.scor.local/refsvn/OMEGA-2/branches/4D_DEV/omega2-sql/global/
status=TBC
