[properties]
root_delivery="/scor/scoromega/delivery/3I_DELIVERY/"
root_dev="/scor/scoromega/delivery/3I_DEV/"
listComponentsFile="/scor/scoromega/delivery/3I_DEV/OM2.DELIVERY/OM2.3I_DEV_DEV.csv"
branches=http://dcvprdsvn/refsvn/OMEGA-2/branches/3I_DEV/omega2-sql/global/
branches2=http://dcvprdsvn.eu.scor.local/refsvn/OMEGA-2/branches/3I_DEV/omega2-sql/global/
status=TBC
