###########################################
# Copie fichiers perimetre pour inventaire Local
# :spira:66334
###########################################

trim=20180331
DFILP2=${DFILP}
#DFILI=/scordata_dcvprdobbatch/ubeu/interm
#DFILP=/scordata_dcvprdobbatch/ubeu/perm

EST_CRVPERICASE0=`ls -rt ${DFILI}/*_CRVPERICASE0_*.dat | tail -1`
EST_FCES=`ls -rt ${DFILI}/*_FCES_*.dat | tail -1`
EST_FCLIENT=`ls -rt ${DFILI}/*_FCLIENT_*.dat | tail -1`
EST_FCPLACC=`ls -rt ${DFILP}/*_ESID0560_FCPLACC_*.dat | tail -1`
EST_FCTRGRO=`ls -rt ${DFILP}/*_ESID0560_FCTRGRO_*.dat | tail -1`
EST_FCURCVSN=`ls -rt ${DFILP}/*_ESCJ0060_FCURCVSN_*.dat | tail -1`
EST_FCURCVSNI=`ls -rt ${DFILP}/*_ESCJ0060_FCURCVSNI_*.dat | tail -1`
EST_FCURQUOT=`ls -rt ${DFILP}/*_ESCJ0060_FCURQUOT*.dat | tail -1`
EST_FDETTRS=`ls -rt ${DFILP}/*_ESCJ0060_FDETTRS_*.dat | tail -1`
EST_FPLACEMT2=`ls -rt ${DFILI}/*_ESEH1110_FPLACEMT2_*.dat | tail -1`
EST_FPLATXCUM=`ls -rt ${DFILI}/*_ESID0560_FPLATXCUM_*.dat | tail -1`
#EST_FPLC=`ls -rt /scordata_dcvintobbatch/ubeu/interm/*_ESID1520_FPLC_${trim}_*.dat | tail -1`
EST_FPLC=`ls -rt ${DFILI}/*_ESID1520_FPLC_${trim}_*.dat | tail -1`
EST_FSOBBLOB=`ls -rt ${DFILI}/*_ESCJ0060_FSOBBLOB_*.dat | tail -1`
EST_FSSDACTR=`ls -rt ${DFILI}/*_ESCJ0060_FSSDACTR_*.dat | tail -1`
EST_FTRANSCODE=`ls -rt ${DFILI}/*_ESCJ0060_FTRANSCODE_*.dat | tail -1`
EST_FTRSLNK=`ls -rt ${DFILI}/*_ESCJ0060_FTRSLNK_*.dat | tail -1`
#EST_IADVPERICASE=`ls -rt /scordata_dcvintobbatch/ubeu/perm/*_ESID0560_IADVPERICASE_${trim}_*.dat | tail -1`
EST_IADVPERICASE=`ls -rt ${DFILP}/*_ESID0560_IADVPERICASE_${trim}_*.dat | tail -1`
EST_OIADVPERICASE=`ls -rt ${DFILP}/*_ESID0560_OIADVPERICASE_*.dat | tail -1`
EST_OIRDVPERICASE=`ls -rt ${DFILP}/*_ESID0560_OIRDVPERICASE_*.dat | tail -1`
EST_FSUBTRS=`ls -rt ${DFILI}/*_ESCJ0060_FSUBTRS_*.dat | tail -1`

ESL_CRVPERICASE0=${DFILP2}/${ENV_PREFIX}_ESID7000_CRVPERICASE0.dat
ESL_FCES=${DFILP2}/${ENV_PREFIX}_ESID7000_FCES.dat
ESL_FCLIENT=${DFILP2}/${ENV_PREFIX}_ESID7000_FCLIENT.dat
ESL_FCPLACC=${DFILP2}/${ENV_PREFIX}_ESID7000_FCPLACC.dat
ESL_FCTRGRO=${DFILP2}/${ENV_PREFIX}_ESID7000_FCTRGRO.dat
ESL_FCURCVSN=${DFILP2}/${ENV_PREFIX}_ESID7000_FCURCVSN.dat
ESL_FCURCVSNI=${DFILP2}/${ENV_PREFIX}_ESID7000_FCURCVSNI.dat
ESL_FCURQUOT=${DFILP2}/${ENV_PREFIX}_ESID7000_FCURQUOT.dat
ESL_FDETTRS=${DFILP2}/${ENV_PREFIX}_ESID7000_FDETTRS.dat
ESL_FPLACEMT2=${DFILP2}/${ENV_PREFIX}_ESID7000_FPLACEMT2.dat
ESL_FPLATXCUM=${DFILP2}/${ENV_PREFIX}_ESID7000_FPLATXCUM.dat
ESL_FPLC=${DFILP2}/${ENV_PREFIX}_ESID7000_FPLC.dat
ESL_FSOBBLOB=${DFILP2}/${ENV_PREFIX}_ESID7000_FSOBBLOB.dat
ESL_FSSDACTR=${DFILP2}/${ENV_PREFIX}_ESID7000_FSSDACTR.dat
ESL_FTRANSCODE=${DFILP2}/${ENV_PREFIX}_ESID7000_FTRANSCODE.dat
ESL_FTRSLNK=${DFILP2}/${ENV_PREFIX}_ESID7000_FTRSLNK.dat
ESL_IADVPERICASE=${DFILP2}/${ENV_PREFIX}_ESID7000_IADVPERICASE.dat
ESL_OIADVPERICASE=${DFILP2}/${ENV_PREFIX}_ESID7000_OIADVPERICASE.dat
ESL_OIRDVPERICASE=${DFILP2}/${ENV_PREFIX}_ESID7000_OIRDVPERICASE.dat
ESL_FSUBTRS=${DFILP2}/${ENV_PREFIX}_ESID7000_FSUBTRS.dat

cp ${EST_CRVPERICASE0}  ${ESL_CRVPERICASE0} 
cp ${EST_FCES}          ${ESL_FCES}         
cp ${EST_FCLIENT}       ${ESL_FCLIENT}      
cp ${EST_FCPLACC}       ${ESL_FCPLACC}      
cp ${EST_FCTRGRO}       ${ESL_FCTRGRO}      
cp ${EST_FCURCVSN}      ${ESL_FCURCVSN}     
cp ${EST_FCURCVSNI}     ${ESL_FCURCVSNI}    
cp ${EST_FCURQUOT}      ${ESL_FCURQUOT}     
cp ${EST_FDETTRS}       ${ESL_FDETTRS}      
cp ${EST_FPLACEMT2}     ${ESL_FPLACEMT2}    
cp ${EST_FPLATXCUM}     ${ESL_FPLATXCUM}    
cp ${EST_FPLC}          ${ESL_FPLC}         
cp ${EST_FSOBBLOB}      ${ESL_FSOBBLOB}     
cp ${EST_FSSDACTR}      ${ESL_FSSDACTR}     
cp ${EST_FTRANSCODE}    ${ESL_FTRANSCODE}   
cp ${EST_FTRSLNK}       ${ESL_FTRSLNK}      
cp ${EST_IADVPERICASE}  ${ESL_IADVPERICASE} 
cp ${EST_OIADVPERICASE} ${ESL_OIADVPERICASE}
cp ${EST_OIRDVPERICASE} ${ESL_OIRDVPERICASE}
cp ${EST_FSUBTRS}       ${ESL_FSUBTRS}      
