/******************************************************************************
**                                                                           **
**  Application name : ESTC2045 header                                       **
**  Date de creation : 15/03/2019                                            **
**  Author           : B.LAGHA                                               **
**  Description      : definition de la structure de pericase apres l'ajout  **
**                     des nouveaux champs utiles pour les nouveaux calculs  **
**                     definie dans la spec EST41 SPIRA : 64222.             **
**  Spira            : 64222 - EST41 : Mettre le batch au niveau du GUI      **
**                                                                           **
*******************************************************************************/


#ifndef PER_STRUCT
#define PER_STRUCT

/* Position des champs dans le perimetre */
#define SEPARATEUR             '~'
#define PER_SSD_CF              0
#define PER_SEGTYP_CT           1
#define PER_CTR_NF              2
#define PER_END_NT              3
#define PER_SEC_NF              4
#define PER_UWY_NF              5
#define PER_UW_NT               6
#define PER_ACCESB_CF           7
#define PER_ADMMODPRM_CT        8
#define PER_ANLCTY_CF           9
#define PER_CAN_DT             10
#define PER_CED_NF             11
#define PER_CLICTY_CF          12
#define PER_CLINAT_CF          13
#define PER_CLMACT_M           14
#define PER_COMTYP_CT          15
#define PER_CTBGENFEE_R        16
#define PER_CTBTYP_CT          17
#define PER_CTRINC_D           18
#define PER_CTRRET_B           19
#define PER_CUTSHA_R           20
#define PER_DIV_NT             21
#define PER_EGPCUR_CF          22
#define PER_ESTCRB_CT          23
#define PER_ESTCTR_NF          24
#define PER_ESTEND_B           25
#define PER_ESTSEC_NF          26
#define PER_EXP_D              27
#define PER_FIXCOM_R           28
#define PER_FRSUWY_NF          29
#define PER_GANPAYORD_NT       30
#define PER_GAR_CF             31
#define PER_GENPRMPAY_NF       32
#define PER_GENPRMSEN_NF       33
#define PER_INSPOL_R           34
#define PER_LAYCAP_M           35
#define PER_LIFTRTTYP_CF       36
#define PER_LOB_CF             37
#define PER_LOSCOREXI_B        38
#define PER_LOSCORHIG_R        39
#define PER_LOSCORLOW_R        40
#define PER_LOSCORRAT_R        41
#define PER_LOSCTB_R           42
#define PER_LOSCTBEXI_B        43
#define PER_MAXCOM_R           44
#define PER_MAXRATCLP_R        45
#define PER_MINCOM_R           46
#define PER_MINRATCLP_R        47
#define PER_NAT_CF             48
#define PER_ORDNBR_NT          49
#define PER_PCPCUR_CF          50
#define PER_PCPRSKTRY_CF       51
#define PER_POLDURMTH_NF       52
#define PER_PRD_NF             53
#define PER_PRFCOM_R           54
#define PER_PRFCOMEXI_B        55
#define PER_PRMEFFLOA_M        56
#define PER_PRMEFFLOA_R        57
#define PER_PRMFIXEFF_R        58
#define PER_PRMFLCRAT_B        59
#define PER_PRMMAXEFF_R        60
#define PER_PRMMINEFF_R        61
#define PER_PRMNETCOM_B        62
#define PER_PRMPRTSCL_B        63
#define PER_REIEXI_B           64
#define PER_REIFRE_B           65
#define PER_REINBR_N           66
#define PER_REIUNL_B           67
#define PER_RESTRFDUR_N        68
#define PER_RESTRFTYP_CF       69
#define PER_SBJCPTDEF_B        70
#define PER_SBJPRM_M           71
#define PER_SCLCOMEXI_B        72
#define PER_SCLCTBEXI_B        73
#define PER_SCOEGP_M           74
#define PER_SCOINC_D           75
#define PER_SECACCSTS_CT       76
#define PER_SECINC_D           77
#define PER_SECSTS_CT          78
#define PER_SEG_NF             79
#define PER_SOB_CF             80
#define PER_SUBNAT_CF          81
#define PER_SUPLOATYP_CT       82
#define PER_TOP_CF             83
#define PER_CTRNAT_CT          84
#define PER_UWGRP_CF           85
#define PER_ACCFRQ_CT          86
#define PER_WRKCAT_CT          87
#define PER_ORGINC_D           88
#define PER_LIARIDSHA_B        89
#define PER_FLAPRM_B           90
#define PER_RIDSHA_R           91
#define PER_CTBCALLVL_CF       92
#define PER_CTBCOM_B           93
#define PER_PRMPRT_M           94
#define PER_PRMPRTCUR_CF       95
#define PER_ACCADMTYP_CT       96
#define PER_SBJPRMCUR_CF       97
#define PER_CTRSTS_CT          98
#define PER_OVRCOM_R           99
#define PER_OVRCOMTYP_CT      100
#define PER_TAXCNDEXI_B       101
#define PER_PRDBRK_R          102
#define PER_ACCBRK_R          103
#define PER_LIACUR_CF         104
#define PER_ERNPRMADM_B       105
#define PER_RETCTRCAT_CF      106
#define PER_CLECUTPER_B       107
#define PER_CLECUTPER_NB      108
#define PER_ORICUR_B          109
#define PER_RETACCADM_B       110
#define PER_SSDRTO_B          111
#define PER_RAICOM_B          112
#define PER_DIFMTH_NF         113
#define PER_USRCRTCOD_CT      114
#define PER_USRCRTVAL_LM      115
#define PER_PRDBRKTYP_CT      116
#define PER_ACCBRKTYP_CT      117
#define PER_UWORG_CF          118
#define PER_SECQUA_CF         119
#define PER_SECQUA2_CF        120
#define PER_SECQUA3_CF        121
#define PER_SECQUA4_CF        122
#define PER_SECQUA5_CF        123
#define PER_ADMGRP_CF         124
#define PER_ORGCED_NF         125
#define PER_REITYP_CF         126
#define PER_PRMMINACT_R       127
#define PER_PRMFIXACT_R       128
#define PER_PRMMAXACT_R       129
#define PER_CLMPRMACT_R       130
#define PER_FLAPRM1_M         131
#define PER_FLAPRMCU1_CF      132
#define PER_FLAPRM2_M         133
#define PER_FLAPRMCU2_CF      134
#define PER_FLAPRM3_M         135
#define PER_FLAPRMCU3_CF      136
#define PER_MINPRVPR1_M       137
#define PER_PRVPRMCU1_CF      138
#define PER_MINPRVPR2_M       139
#define PER_PRVPRMCU2_CF      140
#define PER_MINPRVPR3_M       141
#define PER_PRVPRMCU3_CF      142
#define PER_PRTCUR_CF         143
#define PER_PRVPRM_B          144
#define PER_DEFSBJPRM_M       145
#define PER_ESTSBJPRM_M       146
#define PER_SBJPRMCPT_M       147
#define PER_CTRACCSTS_CT      148
#define PER_CTRACCYEA_NF      149
#define PER_PMLRAT_R          150
#define PER_CEDHORDNBR_NT     151
#define PER_CEDSORDNBR_NT     152
#define PER_ORGCEDHORDNBR_NT  153
#define PER_ORGCEDSORDNBR_NT  154
#define PER_BRKHORDNBR_NT     155
#define PER_BRKSORDNBR_NT     156
#define PER_FACADMTYP_B       157
#define PER_CRTVRSINC_D       158
#define PER_RECBRK_B          159
#define PER_RECBRK_R          160
#define PER_CNATYP_CT         161
#define PER_CLMCUTOFF_B       162 
#define PER_PRMCUTOFF_B       163 
#define PER_CLMRUNOFF_B       164 
#define PER_PRMRUNOFF_B       165 
#define PER_ASSFINANCE_CT     166 
#define PER_FLAPRM4_M         167
#define PER_FLAPRMCU4_CF      168
#define PER_FLAPRM5_M         169
#define PER_FLAPRMCU5_CF      170
#define PER_MINPRVPR4_M       171
#define PER_PRVPRMCU4_CF      172
#define PER_MINPRVPR5_M       173
#define PER_PRVPRMCU5_CF      174
#define PER_ESTLOSCORTYP_CT   175
#define PER_SEGSA_B           176
#define PER_USGAAP_CT         177    
#define PER_URRCAL_R          178    
#define PER_CLMFUN_R          179    
#define PER_CLMFUNCAS_R       180    
#define PER_CLMFUNINT_R       181    
#define PER_URRFUN_R          182    
#define PER_URRFUNCAS_R       183
#define PER_URRFUNINT_R       184
#define PER_ANNFUNINT_R       185
#define PER_PAYTIME_NF        186
#define PER_CTRTYP_CT         187
#define PER_CTRINCUWY_D       188
#define PER_PARENT_FLAG       189
#define PER_LOCAL_FLAG        190
#define PER_TERCTR_B          191
#define PER_COMBAS_CF         192
#define PER_PAYFRQ_CT         193
#define PER_FIRPAYDUE_D       194
#define PER_CLOFAM_CT         195
#define PER_ACCFAM_CT         196
#define PER_ESTV2C_COL_22     197
#define PER_PRMINCEST_CT      198
#define PER_PRMWITEST_CT      199
#define PER_PRC_FLG_CT        200
#define PER_IPLR_R            201
#define PER_FLAPROPRM_M       202
#define PER_ESTV2C_COL_28     203
#define PER_ESTV2C_COL_29     204
#define PER_ESTV2C_COL_30     205
#define PER_CLMFUNVARINT_B    206
#define PER_CLMFUNESTINT_R    207
#define PER_URRFUNVARINT_B    208
#define PER_URRFUNESTINT_R    209
#define PER_ANNFUNVARINT_B    210
#define PER_ANNFUNCAS_R       211
#define PER_ANNFUNESTINT_R    212
#define PER_LIFRESVARINT_B    213
#define PER_LIFRESCAS_R       214
#define PER_LIFRESINT_R       215
#define PER_LIFRESESTINT_R    216
#define PER_ANNFUN_R          217
#define PER_LIFRES_R          218
#undef  PER_NBCOL
#define PER_NBCOL             219

#endif
