/*==============================================================================
[000] 26/04/2012 Roger Cassis   :spot:23802 - Nouveau .h pour Solvency
------------------------------------------------------------------------------
historique des modifications :
[001] jj/mm/aaaa prog name      :spot:xxxxx
================================================================================*/

#ifndef __ESTC1052
#define __ESTC1052

/*
** Objet  : FPLATXCUM (Maitre)
** Entree : RETM0532_I1
** Cle    : (RETCTR_NF, RETSEC_NF, RTY_NF) (3 champs) */
#define PLA_RETCTR_NF       0
#define PLA_RETSEC_NF       1
#define PLA_RTY_NF          2
#define PLA_PLC_NT          3
#define PLA_RETSIGSHA_TOT_R 4
#define PLA_RETSIGSHA_INT_R 5
#define PLA_RETSIGSHA_QOT_R 6
#define PLA_RTO_NF          7       //[001]
#define PLA_NBLIGNES        8       //[001]

T_RUPTURE_VAR Kbd_ruptFPLATXCUM;

int n_InitFPLATXCUM(T_RUPTURE_VAR *pbd_Rupt);
int n_ActionLigneFPLATXCUM(char **pbd_InRec_Cur);


#define FTTECLEDA_SSD_CF 0
#define FTTECLEDA_ESB_CF 1
#define FTTECLEDA_BALSHEY_NF 2
#define FTTECLEDA_BALSHRMTH_NF 3
#define FTTECLEDA_BALSHRDAY_NF 4
#define FTTECLEDA_TRNCOD_CF 5
#define FTTECLEDA_DBLTRNCOD_CF 6
#define FTTECLEDA_CTR_NF 7
#define FTTECLEDA_END_NT 8
#define FTTECLEDA_SEC_NF 9
#define FTTECLEDA_UWY_NF 10
#define FTTECLEDA_UW_NT 11
#define FTTECLEDA_OCCYEA_NF 12
#define FTTECLEDA_ACY_NF 13
#define FTTECLEDA_SCOSTRMTH_NF 14
#define FTTECLEDA_SCOENDMTH_NF 15
#define FTTECLEDA_CLM_NF 16
#define FTTECLEDA_CUR_CF 17
#define FTTECLEDA_AMT_M 18
#define FTTECLEDA_CED_NF 19
#define FTTECLEDA_BRK_NF 20
#define FTTECLEDA_PAY_NF 21
#define FTTECLEDA_KEY_NF 22
#define FTTECLEDA_RETCTR_NF 23
#define FTTECLEDA_RETEND_NT 24
#define FTTECLEDA_RETSEC_NF 25
#define FTTECLEDA_RTY_NF 26
#define FTTECLEDA_RETUW_NT 27
#define FTTECLEDA_RETOCCYEA_NF 28
#define FTTECLEDA_RETACY_NF 29
#define FTTECLEDA_RETSCOSTRMTH_NF 30
#define FTTECLEDA_RETSCOENDMTH_NF 31
#define FTTECLEDA_RCL_NF 32
#define FTTECLEDA_RETCUR_CF 33
#define FTTECLEDA_RETAMT_M 34
#define FTTECLEDA_PLC_NT 35
#define FTTECLEDA_RTO_NF 36
#define FTTECLEDA_INT_NF 37
#define FTTECLEDA_RETPAY_NF 29
#define FTTECLEDA_RETKEY_CF 39
#define FTTECLEDA_CRE_D 40
#define FTTECLEDA_CREUSR_CF 41
#define FTTECLEDA_LSTUPD_D 42
#define FTTECLEDA_LSTUPDUSR_CF 43
#define FTTECLEDA_LOBACC_CF 44
#define FTTECLEDA_LOBRET_CF 45
#define FTTECLEDA_SOBACC_CF 46
#define FTTECLEDA_SOBRET_CF 47
#define FTTECLEDA_TOPACC_CF 48
#define FTTECLEDA_TOPRET_CF 49
#define FTTECLEDA_NATACC_CF 50
#define FTTECLEDA_NATRET_CF 51
#define FTTECLEDA_GARACC_CF 52
#define FTTECLEDA_GARRET_CF 53
#define FTTECLEDA_PCPRSKTRYACC_CF 54
#define FTTECLEDA_PCPRSKTRYRET_CF 55
#define FTTECLEDA_USRCRTCODACC_CT 56
#define FTTECLEDA_USRCRTCODRET_CT 57
#define FTTECLEDA_USRCRTVALACC_LM 58
#define FTTECLEDA_USRCRTVALRET_LM 59
#define FTTECLEDA_CTRNAT_CT 60
#define FTTECLEDA_RETCTRCAT_CF 61
#define FTTECLEDA_WRKCAT_CT 62
#define FTTECLEDA_PRDCOD_CT 63
#define FTTECLEDA_ANLCTY_CF 64
#define FTTECLEDA_ACCADMTYP_CT 65
#define FTTECLEDA_RETACCTYP_CT 66
#define FTTECLEDA_COMACC_B 67
#define FTTECLEDA_CPLACCUPD_D 68
#define FTTECLEDA_CTRRET_B 69
#define FTTECLEDA_UWGRP_CF 70
#define FTTECLEDA_VRS_NF 71
#define FTTECLEDA_SEG_NF 72
#define FTTECLEDA_UWORG_CF 73
#define FTTECLEDA_ESTCRB_CT 74
#define FTTECLEDA_ESTCTR_NF 75
#define FTTECLEDA_ESBACC_NF 76
#define FTTECLEDA_ORGCED_NF 77
#define FTTECLEDA_CEDHORDNBR_NT 78
#define FTTECLEDA_CEDSORDNBR_NT 79
#define FTTECLEDA_ORGCEDHORDNBR_NT 80
#define FTTECLEDA_ORGCEDSORDNBR_NT 81
#define FTTECLEDA_BRKHORDNBR_NT 82
#define FTTECLEDA_BRKSORDNBR_NT 83
#define FTTECLEDA_FACADMTYP_CT 84
#define FTTECLEDA_CLIIND_NF 85
#define FTTECLEDA_HORDNBR_NT 86
#define FTTECLEDA_RETINTAMT_M 87
#define FTTECLEDA_BUKRS_CF 88        //les 14 colonnes du ONEGL de SAP
#define FTTECLEDA_RCOMP_CF 89
#define FTTECLEDA_LDGRP_CF 90
#define FTTECLEDA_HKONT_CF 91
#define FTTECLEDA_DBLHKONT_CF 92
#define FTTECLEDA_GJAHR_NF 93
#define FTTECLEDA_MONAT_NF 94
#define FTTECLEDA_VBUND_CF 95
#define FTTECLEDA_ZZCED_NF 96
#define FTTECLEDA_SEGMENT_CF 97
#define FTTECLEDA_BEWAR_CF 98
#define FTTECLEDA_ZZGAAPDIF_CF 99
#define FTTECLEDA_BLART_CF 100
#define FTTECLEDA_ZZRECONKEY_CF 101
#define FTTECLEDA_TRN_NT 102          //ajout des nouvelles colonnes du GT: 16 colonnes
#define FTTECLEDA_ORICOD_LS 103
#define FTTECLEDA_RETROAUTO_B 104
#define FTTECLEDA_SPEENTNAT_CF 105
#define FTTECLEDA_EVT_CF 106
#define FTTECLEDA_REVT_CF 107
#define FTTECLEDA_RETARDRETINT_B 108
#define FTTECLEDA_NEWCOLS1_NF 109
#define FTTECLEDA_GAAPCOD_NT 110
#define FTTECLEDA_I17PRDCOD_CT 111
#define FTTECLEDA_NEWCOLS4_NF 112
#define FTTECLEDA_NEWCOLS5_NF 113
#define FTTECLEDA_NEWCOLS6_NF 114
#define FTTECLEDA_NEWCOLS7_NF 115
#define FTTECLEDA_NEWCOLS8_NF 116
#define FTTECLEDA_NEWCOLS9_NF 117
#define FTTECLEDA_NB_COL 118

T_RUPTURE_SYNC_VAR Kbd_ruptFACCTRTGT;

int n_InitSyncFACCTRTGT         (T_RUPTURE_SYNC_VAR *);
int n_ConditionSyncFACCTRTGT    (char **, char **);
int n_InitFACCTRTGT             (T_RUPTURE_SYNC_VAR  *);
int n_ActionLigneSyncFACCTRTGT  (char **, char **);
int n_ActionFsPFACCTRTGT        (char **);


/*
** Objet  : GT
** Sortie : RETM0532_O1 */
FILE *Kp_OutputFileGT;


#endif /* __RETM0532 */

