
 /* definition de la position des champs du fichier GT enrichi */

#define TECLEDA_SSD_CF 0
#define TECLEDA_ESB_CF 1
#define TECLEDA_BALSHEY_NF 2
#define TECLEDA_BALSHRMTH_NF 3
#define TECLEDA_BALSHRDAY_NF 4
#define TECLEDA_TRNCOD_CF 5
#define TECLEDA_DBLTRNCOD_CF 6
#define TECLEDA_CTR_NF 7
#define TECLEDA_END_NT 8
#define TECLEDA_SEC_NF 9
#define TECLEDA_UWY_NF 10
#define TECLEDA_UW_NT 11
#define TECLEDA_OCCYEA_NF 12
#define TECLEDA_ACY_NF 13
#define TECLEDA_SCOSTRMTH_NF 14
#define TECLEDA_SCOENDMTH_NF 15
#define TECLEDA_CLM_NF 16
#define TECLEDA_CUR_CF 17
#define TECLEDA_AMT_M 18
#define TECLEDA_CED_NF 19
#define TECLEDA_BRK_NF 20
#define TECLEDA_PAY_NF 21
#define TECLEDA_KEY_NF 22
#define TECLEDA_RETCTR_NF 23
#define TECLEDA_RETEND_NT 24
#define TECLEDA_RETSEC_NF 25
#define TECLEDA_RTY_NF 26
#define TECLEDA_RETUW_NT 27
#define TECLEDA_RETOCCYEA_NF 28
#define TECLEDA_RETACY_NF 29
#define TECLEDA_RETSCOSTRMTH_NF 30
#define TECLEDA_RETSCOENDMTH_NF 31
#define TECLEDA_RCL_NF 32
#define TECLEDA_RETCUR_CF 33
#define TECLEDA_RETAMT_M 34
#define TECLEDA_PLC_NT 35
#define TECLEDA_RTO_NF 36
#define TECLEDA_INT_NF 37
#define TECLEDA_RETPAY_NF 38
#define TECLEDA_RETKEY_CF 39
#define TECLEDA_CRE_D 40
#define TECLEDA_CREUSR_CF 41
#define TECLEDA_LSTUPD_D 42
#define TECLEDA_LSTUPDUSR_CF 43
#define TECLEDA_LOBACC_CF 44
#define TECLEDA_LOBRET_CF 45
#define TECLEDA_SOBACC_CF 46
#define TECLEDA_SOBRET_CF 47
#define TECLEDA_TOPACC_CF 48
#define TECLEDA_TOPRET_CF 49
#define TECLEDA_NATACC_CF 50
#define TECLEDA_NATRET_CF 51
#define TECLEDA_GARACC_CF 52
#define TECLEDA_GARRET_CF 53
#define TECLEDA_PCPRSKTRYACC_CF 54
#define TECLEDA_PCPRSKTRYRET_CF 55
#define TECLEDA_USRCRTCODACC_CT 56
#define TECLEDA_USRCRTCODRET_CT 57
#define TECLEDA_USRCRTVALACC_LM 58
#define TECLEDA_USRCRTVALRET_LM 59
#define TECLEDA_CTRNAT_CT 60
#define TECLEDA_RETCTRCAT_CF 61
#define TECLEDA_WRKCAT_CT 62
#define TECLEDA_PRDCOD_CT 63
#define TECLEDA_ANLCTY_CF 64
#define TECLEDA_ACCADMTYP_CT 65
#define TECLEDA_RETACCTYP_CT 66
#define TECLEDA_COMACC_B 67
#define TECLEDA_CPLACCUPD_D 68
#define TECLEDA_CTRRET_B 69
#define TECLEDA_UWGRP_CF 70
#define TECLEDA_VRS_NF 71
#define TECLEDA_SEG_NF 72
#define TECLEDA_UWORG_CF 73


 /* nombre de colonnes de la table TTECLEDA */

#define NB_COL_TECLEDA	74


