[properties]
root_delivery="/scor/scoromega/delivery/4H_DELIVERY/"
listComponentsFile="/scor/scoromega/delivery/4H_DELIVERY/OM2.DELIVERY/OM2.4H_DELIVERY_AZIN2.csv"
branches=http://dcvprdsvn/refsvn/OMEGA-2/branches/4H_DEV/omega2-sql/global/
branches2=http://dcvprdsvn.eu.scor.local/refsvn/OMEGA-2/branches/4H_DEV/omega2-sql/global/
status=TBC
