USE BTRAV
GO

if exists (select 1
            from  sysobjects
            where id = object_id('TREQJOB')
            and   type = 'U')
   drop table TREQJOB
go

/*==============================================================*/
/* Table: TREQJOB                                               */
/*==============================================================*/
CREATE TABLE TREQJOB
(
    SSD_CF USSD_CF NOT NULL,
    BALSHEYEA_NF SMALLINT NOT NULL,
    BALSHTMTH_NF TINYINT NOT NULL,
    CLODAT_D DATETIME NOT NULL,
    REQCOD_CT CHAR (1) NOT NULL,
    CRE_D UUPD_D DEFAULT GETDATE () NOT NULL,
    DBCLO_D UUPD_D DEFAULT GETDATE () NOT NULL,
    LAUNCH_D UUPD_D NULL,
    CLOPER_LS UL64 NULL,
    VRS_NF NUMERIC (10, 0) NULL,
    UPDUSR_CF UUSR_CF DEFAULT '' NOT NULL,
    START_D UUPD_D NULL,
    END_D UUPD_D NULL,
    SITE_CF CHAR (4) DEFAULT 'ALL' NOT NULL,
    ID_NF INT DEFAULT 0 NOT NULL
)
LOCK DATAROWS
go
IF OBJECT_ID('dbo.TREQJOB') IS NOT NULL
    PRINT '<<< CREATED TABLE BTRAV..TREQJOB >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE BTRAV..TREQJOB >>>'
go
GRANT DELETE ON dbo.TREQJOB TO GOMEGA
go
GRANT DELETE ON dbo.TREQJOB TO GDBBATCH
go
GRANT DELETE STATISTICS ON dbo.TREQJOB TO GDBBATCH
go
GRANT INSERT ON dbo.TREQJOB TO GOMEGA
go
GRANT INSERT ON dbo.TREQJOB TO GDBBATCH
go
GRANT REFERENCES ON dbo.TREQJOB TO GDBBATCH
go
GRANT SELECT ON dbo.TREQJOB TO GCONSULT
go
GRANT SELECT ON dbo.TREQJOB TO GOMEGA
go
GRANT SELECT ON dbo.TREQJOB TO GDBBATCH
go
GRANT TRANSFER TABLE ON dbo.TREQJOB TO GDBBATCH
go
GRANT TRUNCATE TABLE ON dbo.TREQJOB TO GDBBATCH
go
GRANT UPDATE ON dbo.TREQJOB TO GOMEGA
go
GRANT UPDATE ON dbo.TREQJOB TO GDBBATCH
go
GRANT UPDATE STATISTICS ON dbo.TREQJOB TO GDBBATCH
go

USE BTRAV
GO
print 'INSERT INTO BTRAV..TREQJOB'
INSERT INTO BTRAV..TREQJOB 
SELECT SSD_CF, BALSHEYEA_NF, BALSHTMTH_NF, CLODAT_D, REQCOD_CT, CRE_D, DBCLO_D, LAUNCH_D, CLOPER_LS, VRS_NF, UPDUSR_CF, NULL, DATEADD(DD, 7, DBCLO_D), SITE_CF, ID_NF
FROM BEST..TREQJOB
WHERE REQCOD_CT = 'A'
GO

USE BTRAV
GO
INSERT INTO BTRAV..TREQJOB
SELECT SSD_CF, BALSHEYEA_NF, BALSHTMTH_NF, CLODAT_D, REQCOD_CT, CRE_D, DBCLO_D, LAUNCH_D, CLOPER_LS, VRS_NF, UPDUSR_CF, NULL, NULL, SITE_CF, ID_NF
FROM BEST..TREQJOB
WHERE REQCOD_CT <> 'A'
GO

print 'UPDATE INTO BTRAV..TREQJOB'
USE BTRAV
GO
UPDATE TREQJOB
SET VRS_NF = BALSHEYEA_NF
FROM TREQJOB
WHERE REQCOD_CT = 'A' 
AND VRS_NF = NULL
GO

USE BTRAV
GO
UPDATE TREQJOB
SET VRS_NF = BALSHEYEA_NF
FROM TREQJOB
WHERE REQCOD_CT = 'A' 
AND VRS_NF = 0

USE BTRAV
GO
UPDATE TREQJOB
SET CLOPER_LS = CONVERT (CHAR (4),BALSHEYEA_NF) + "/" + CONVERT (CHAR (2),BALSHTMTH_NF)
WHERE REQCOD_CT = 'A' 
AND CLOPER_LS IS NULL

GO

USE BEST
go

if exists (select 1
            from  sysobjects
            where id = object_id('TREQJOB')
            and   type = 'U')
   drop table TREQJOB
go

/*==============================================================*/
/* Table: TREQJOB                                               */
/*==============================================================*/
CREATE TABLE TREQJOB
(
    SSD_CF       USSD_CF       NOT NULL,
    BALSHEYEA_NF smallint      NOT NULL,
    BALSHTMTH_NF tinyint       NOT NULL,
    CLODAT_D     datetime      NOT NULL,
    REQCOD_CT    char(1)       NOT NULL,
    CRE_D        UUPD_D        DEFAULT getdate() NOT NULL,
    DBCLO_D      UUPD_D        DEFAULT getdate() NOT NULL,
    LAUNCH_D     UUPD_D        NULL,
    CLOPER_LS    UL64          NULL,
    VRS_NF       numeric(10,0) NULL,
    UPDUSR_CF    UUSR_CF       DEFAULT ''        NOT NULL,
	START_D      UUPD_D        NULL,								--EST48
    END_D        UUPD_D        NULL,								--EST48
    SITE_CF      char(4)       DEFAULT 'ALL'     NOT NULL,
    ID_NF        int           DEFAULT 0         NOT NULL
)
LOCK DATAROWS
go
IF OBJECT_ID('dbo.TREQJOB') IS NOT NULL
    PRINT '<<< CREATED TABLE BEST..TREQJOB >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE BEST..TREQJOB >>>'
go
GRANT DELETE ON dbo.TREQJOB TO GOMEGA
go
GRANT DELETE ON dbo.TREQJOB TO GDBBATCH
go
GRANT DELETE STATISTICS ON dbo.TREQJOB TO GDBBATCH
go
GRANT INSERT ON dbo.TREQJOB TO GOMEGA
go
GRANT INSERT ON dbo.TREQJOB TO GDBBATCH
go
GRANT REFERENCES ON dbo.TREQJOB TO GDBBATCH
go
GRANT SELECT ON dbo.TREQJOB TO GCONSULT
go
GRANT SELECT ON dbo.TREQJOB TO GOMEGA
go
GRANT SELECT ON dbo.TREQJOB TO GDBBATCH
go
GRANT TRANSFER TABLE ON dbo.TREQJOB TO GDBBATCH
go
GRANT TRUNCATE TABLE ON dbo.TREQJOB TO GDBBATCH
go
GRANT UPDATE ON dbo.TREQJOB TO GOMEGA
go
GRANT UPDATE ON dbo.TREQJOB TO GDBBATCH
go
GRANT UPDATE STATISTICS ON dbo.TREQJOB TO GDBBATCH
go


/*==============================================================*/
/* Index: IREQJOB_00                                            */
/*==============================================================*/
USE BEST
go
SETUSER 'dbo'
go
IF EXISTS (SELECT * FROM sysindexes WHERE id=OBJECT_ID('dbo.TREQJOB') AND name='IREQJOB_00')
BEGIN
    DROP INDEX TREQJOB.IREQJOB_00
    IF EXISTS (SELECT * FROM sysindexes WHERE id=OBJECT_ID('dbo.TREQJOB') AND name='IREQJOB_00')
        PRINT '<<< FAILED DROPPING INDEX BEST..TREQJOB.IREQJOB_00 >>>'
    ELSE
        PRINT '<<< DROPPED INDEX BEST..TREQJOB.IREQJOB_00 >>>'
END
go
SETUSER
go
CREATE UNIQUE NONCLUSTERED INDEX IREQJOB_00
    ON dbo.TREQJOB(SSD_CF,BALSHEYEA_NF,BALSHTMTH_NF,CLODAT_D,REQCOD_CT,CRE_D,SITE_CF)
go
IF EXISTS (SELECT * FROM sysindexes WHERE id=OBJECT_ID('dbo.TREQJOB') AND name='IREQJOB_00')
    PRINT '<<< CREATED INDEX BEST..TREQJOB.IREQJOB_00 >>>'
ELSE
    PRINT '<<< FAILED CREATING INDEX BEST..TREQJOB.IREQJOB_00 >>>'
go

/*==============================================================*/
/* Index: IREQJOB_01                                            */
/*==============================================================*/
USE BEST
go
SETUSER 'dbo'
go
IF EXISTS (SELECT * FROM sysindexes WHERE id=OBJECT_ID('dbo.TREQJOB') AND name='IREQJOB_01')
BEGIN
    DROP INDEX TREQJOB.IREQJOB_01
    IF EXISTS (SELECT * FROM sysindexes WHERE id=OBJECT_ID('dbo.TREQJOB') AND name='IREQJOB_01')
        PRINT '<<< FAILED DROPPING INDEX BEST..TREQJOB.IREQJOB_01 >>>'
    ELSE
        PRINT '<<< DROPPED INDEX BEST..TREQJOB.IREQJOB_01 >>>'
END
go
SETUSER
go
CREATE NONCLUSTERED INDEX IREQJOB_01
    ON dbo.TREQJOB(ID_NF)
go
IF EXISTS (SELECT * FROM sysindexes WHERE id=OBJECT_ID('dbo.TREQJOB') AND name='IREQJOB_01')
    PRINT '<<< CREATED INDEX BEST..TREQJOB.IREQJOB_01 >>>'
ELSE
    PRINT '<<< FAILED CREATING INDEX BEST..TREQJOB.IREQJOB_01 >>>'
go

print 'INSERT INTO BEST..TREQJOB FROM BTRAV..TREQJOB'
USE BEST
GO
INSERT INTO TREQJOB 
SELECT SSD_CF, BALSHEYEA_NF, BALSHTMTH_NF, CLODAT_D, REQCOD_CT, CRE_D, DBCLO_D, LAUNCH_D, CLOPER_LS, VRS_NF, UPDUSR_CF, START_D, END_D, SITE_CF, ID_NF
FROM BTRAV..TREQJOB

GO

USE BTRAV
GO
IF EXISTS (SELECT 1
           FROM  SYSOBJECTS
           WHERE ID = OBJECT_ID('TREQJOB')
           AND   TYPE = 'U')
   DROP TABLE TREQJOB
GO

IF OBJECT_ID('TREQJOB') IS NOT NULL
    PRINT '<<< FAILED DROPPING TABLE BTRAV..TREQJOB >>>'
ELSE
    PRINT '<<< DROPPED TABLE BTRAV..TREQJOB >>>'
GO
