
USE BEST
go


CREATE TABLE #TCLOPER_TEMP
(
SSD_CF USSD_CF NOT NULL,
ESB_CF UESB_CF NOT NULL,
PARM_1 varchar(32) NOT NULL,
PARM_2 varchar(32) NOT NULL

)



INSERT #TCLOPER_TEMP (SSD_CF, ESB_CF, PARM_1, PARM_2) select 20,6,'1','1'
INSERT #TCLOPER_TEMP (SSD_CF, ESB_CF, PARM_1, PARM_2) select 4,2,'0','1'
INSERT #TCLOPER_TEMP (SSD_CF, ESB_CF, PARM_1, PARM_2) select 4,6,'0','1'
INSERT #TCLOPER_TEMP (SSD_CF, ESB_CF, PARM_1, PARM_2) select 4,7,'0','1'
INSERT #TCLOPER_TEMP (SSD_CF, ESB_CF, PARM_1, PARM_2) select 4,14,'0','1'
INSERT #TCLOPER_TEMP (SSD_CF, ESB_CF, PARM_1, PARM_2) select 4,19,'0','1'
INSERT #TCLOPER_TEMP (SSD_CF, ESB_CF, PARM_1, PARM_2) select 4,20,'0','1'
INSERT #TCLOPER_TEMP (SSD_CF, ESB_CF, PARM_1, PARM_2) select 4,23,'0','1'
INSERT #TCLOPER_TEMP (SSD_CF, ESB_CF, PARM_1, PARM_2) select 19,2,'0','1'
INSERT #TCLOPER_TEMP (SSD_CF, ESB_CF, PARM_1, PARM_2) select 20,9,'0','1'
INSERT #TCLOPER_TEMP (SSD_CF, ESB_CF, PARM_1, PARM_2) select 20,14,'0','1'
INSERT #TCLOPER_TEMP (SSD_CF, ESB_CF, PARM_1, PARM_2) select 20,17,'0','1'
INSERT #TCLOPER_TEMP (SSD_CF, ESB_CF, PARM_1, PARM_2) select 24,1,'0','1'
INSERT #TCLOPER_TEMP (SSD_CF, ESB_CF, PARM_1, PARM_2) select 27,8,'0','1'
INSERT #TCLOPER_TEMP (SSD_CF, ESB_CF, PARM_1, PARM_2) select 27,10,'0','1'



    insert into BEST..TI17CLOPER (SSD_CF,ESB_CF,PARM1,PARM2,PARM3,PARM4,PARM5,PARM6,PARM7,PARM8,PARM9,PARM10) 

    select C.SSD_CF, C.ESB_CF,'0' ,'0',null ,null ,null , null, null, null, null, null 
	FROM #TCLOPER_TEMP C 

	WHERE NOT EXISTS (
	SELECT 1
	FROM BEST..TI17CLOPER S
	WHERE S.SSD_CF = C.SSD_CF
	AND S.ESB_CF = C.ESB_CF
	AND S.PARM1 = C.PARM_1
	AND S.PARM2 = C.PARM_2
	)


update BEST..TI17CLOPER SET PARM1 = B.PARM_1, PARM2 = B.PARM_2 FROM BEST..TI17CLOPER A ,#TCLOPER_TEMP B
where A.SSD_CF = B.SSD_CF AND A.ESB_CF = B.ESB_CF


DROP TABLE #TCLOPER_TEMP

go



select * from best..TI17CLOPER