-- TABLE INSERT STATEMENTS dans TPRSMAP


DELETE FROM BREF..TPRSMAP WHERE ACMTRS_NT = 3202 AND PRS_CF = 751

INSERT INTO BREF..TPRSMAP ( PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10 ) 
        VALUES ( 751, 3202, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL )
        
DELETE FROM BREF..TPRSMAP WHERE ACMTRS_NT = 3222 AND PRS_CF = 751

INSERT INTO BREF..TPRSMAP ( PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10 ) 
        VALUES ( 751, 3222, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL )