USE BREF
GO
DELETE FROM BREF..TPRSMAP WHERE ACMTRS_NT = 2010 AND PRS_CF = 751
GO
INSERT INTO BREF..TPRSMAP ( PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10 ) 
VALUES ( 751, 2010, 'PR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL )
GO        
DELETE FROM BREF..TPRSMAP WHERE ACMTRS_NT = 2014 AND PRS_CF = 751
GO
INSERT INTO BREF..TPRSMAP ( PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10 ) 
VALUES ( 751, 2014, 'PR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL )
GO        
DELETE FROM BREF..TPRSMAP WHERE ACMTRS_NT = 2035 AND PRS_CF = 751
GO
INSERT INTO BREF..TPRSMAP ( PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10 ) 
VALUES ( 751, 2035, 'PR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL )
GO        
DELETE FROM BREF..TPRSMAP WHERE ACMTRS_NT = 2055 AND PRS_CF = 751
GO
INSERT INTO BREF..TPRSMAP ( PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10 ) 
VALUES ( 751, 2055, 'PR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL )
GO        
DELETE FROM BREF..TPRSMAP WHERE ACMTRS_NT = 2057 AND PRS_CF = 751
GO
INSERT INTO BREF..TPRSMAP ( PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10 ) 
VALUES ( 751, 2057, 'PR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL )
GO