-- TABLE INSERT STATEMENTS dans TPRSMAP 9.6

USE BREF
go

-- TABLE INSERT STATEMENTS dans TPRSMAP
DELETE FROM BREF..TPRSMAP WHERE ACMTRS_NT = 2035 AND PRS_CF = 751
go

INSERT INTO BREF..TPRSMAP ( PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10 ) 
        VALUES ( 751, 2035, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL )
go
        
