-------------------------------------------------------------------------------
-- Spira 73382 - Update estimation table for contract type 1 with uwy <> acy --
-------------------------------------------------------------------------------

USE BEST
GO

SET NOCOUNT ON
GO

DECLARE @erreur int , @nbline int
SELECT  @erreur = 0 , @nbline = 0

CREATE TABLE #SCOPE_TYP1_A (
  CTR_NF UCTR_NF not null,
  SEC_NF USEC_NF not null,
  BALSHEY_NF smallint not null,
  UWY_NF UUWY_NF not null,
  ACY_NF smallint not null,
  DETTRNCOD_CF varchar(5) not null,
  ACMTRS_NT smallint not null, 
  GAAP_NT tinyint not null, 
  MAX_CRE_D UUPD_D not null
)
SELECT  @erreur = @@error
IF @erreur != 0
BEGIN
  PRINT 'CREAT TEMPORARY TABLE FAILED - ERROR : %1!', @erreur
  GOTO fin
END

CREATE INDEX ISCOPE_TYP1_A on #SCOPE_TYP1_A (CTR_NF, SEC_NF, BALSHEY_NF, UWY_NF, ACY_NF, DETTRNCOD_CF)     -- modif [005] Optimisation ajout index.
SELECT  @erreur = @@error
IF @erreur != 0
BEGIN
  PRINT 'creat index for temporary table failed - ERROR : %1!', @erreur
  GOTO fin
END

CREATE TABLE #SCOPE_TYP1_R (
  CTR_NF UCTR_NF not null,
  SEC_NF USEC_NF not null,
  BALSHEY_NF smallint not null,
  UWY_NF UUWY_NF not null,
  ACY_NF smallint not null,
  DETTRNCOD_CF varchar(5) not null,
  ACMTRS_NT smallint not null, 
  GAAP_NT tinyint not null, 
  MAX_CRE_D UUPD_D not null
)
SELECT  @erreur = @@error
IF @erreur != 0
BEGIN
  PRINT 'CREAT TEMPORARY TABLE FAILED - ERROR : %1!', @erreur
  GOTO fin
END

CREATE INDEX ISCOPE_TYP1_R on #SCOPE_TYP1_R (CTR_NF, SEC_NF, BALSHEY_NF, UWY_NF, ACY_NF, DETTRNCOD_CF)     -- modif [005] Optimisation ajout index.
SELECT  @erreur = @@error
IF @erreur != 0
BEGIN
  PRINT 'creat index for temporary table failed - ERROR : %1!', @erreur
  GOTO fin
END

-- Tempory table identifying the transaction codes concerns by the issue (ACY <> UWY)
-- 1 - SCOP ACCEPTE
INSERT INTO #SCOPE_TYP1_A (CTR_NF, SEC_NF, BALSHEY_NF, UWY_NF, ACY_NF, DETTRNCOD_CF, ACMTRS_NT, GAAP_NT, MAX_CRE_D)
SELECT DISTINCT 
LIFEST.CTR_NF, LIFEST.SEC_NF, LIFEST.BALSHEY_NF, LIFEST.UWY_NF, LIFEST.ACY_NF, LIFEST.DETTRNCOD_CF, LIFEST.ACMTRS_NT, LIFEST.GAAP_NT, MAX(LIFEST.CRE_D)
FROM BEST..TLIFEST LIFEST, BTRT..TSECTION TSEC
WHERE LIFEST.CTR_NF = TSEC.CTR_NF
  and LIFEST.SEC_NF = TSEC.SEC_NF
  and LIFEST.UWY_NF = TSEC.UWY_NF
  and TSEC.ACCADMTYP_CT = 1  -- type 1 
  and TSEC.SECSTS_CT   != 19 -- not canceled
  and LIFEST.UWY_NF != LIFEST.ACY_NF
  and LIFEST.ACMTRS_NT not in (1303,1323,1304,1324)
  group by LIFEST.CTR_NF, LIFEST.SEC_NF, LIFEST.BALSHEY_NF, LIFEST.UWY_NF, LIFEST.ACY_NF, LIFEST.DETTRNCOD_CF, LIFEST.ACMTRS_NT, LIFEST.GAAP_NT
  order by LIFEST.CTR_NF, LIFEST.SEC_NF, LIFEST.BALSHEY_NF, LIFEST.UWY_NF, LIFEST.ACY_NF, LIFEST.DETTRNCOD_CF, LIFEST.ACMTRS_NT, LIFEST.GAAP_NT

SELECT  @erreur = @@error
IF @erreur != 0
BEGIN
  PRINT 'SELECT SCOP ACCEPTE - ERROR : %1!', @erreur
  GOTO fin
END


-- 2 - SCOP RETRO
INSERT INTO #SCOPE_TYP1_R (CTR_NF, SEC_NF, BALSHEY_NF, UWY_NF, ACY_NF, DETTRNCOD_CF, ACMTRS_NT, GAAP_NT, MAX_CRE_D)
SELECT DISTINCT 
LIFEST.CTR_NF, LIFEST.SEC_NF, LIFEST.BALSHEY_NF, LIFEST.UWY_NF, LIFEST.ACY_NF, LIFEST.DETTRNCOD_CF, LIFEST.ACMTRS_NT, LIFEST.GAAP_NT, MAX(LIFEST.CRE_D)
FROM BEST..TLIFEST LIFEST, BRET..TRETCTR TRETCTR
WHERE LIFEST.CTR_NF = TRETCTR.RETCTR_NF
  and LIFEST.UWY_NF = TRETCTR.RTY_NF
  and TRETCTR.RETACCTYP_CT  = 1  -- type 1 
  and TRETCTR.RETCTRSTS_CT != 19 -- not canceled
  and LIFEST.UWY_NF != LIFEST.ACY_NF
  and LIFEST.ACMTRS_NT not in (2303,2323,2304,2324)
  group by LIFEST.CTR_NF, LIFEST.SEC_NF, LIFEST.BALSHEY_NF, LIFEST.UWY_NF, LIFEST.ACY_NF, LIFEST.DETTRNCOD_CF, LIFEST.ACMTRS_NT, LIFEST.GAAP_NT
  order by LIFEST.CTR_NF, LIFEST.SEC_NF, LIFEST.BALSHEY_NF, LIFEST.UWY_NF, LIFEST.ACY_NF, LIFEST.DETTRNCOD_CF, LIFEST.ACMTRS_NT, LIFEST.GAAP_NT

SELECT  @erreur = @@error
IF @erreur != 0
BEGIN
  PRINT 'SELECT SCOP RETRO - ERROR : %1!', @erreur
  GOTO fin
END

---------------------
-- ACCEPTE 
---------------------
BEGIN TRAN

-- Updating to 0 lines where ACY <> UWY
INSERT INTO BEST..TLIFEST
(CTR_NF, END_NT, SEC_NF, UWY_NF, UW_NT, CRE_D, BALSHEY_NF, BALSHTMTH_NF, ACY_NF, GAAP_NT,
 DETTRNCOD_CF, ACM_NF, PRS_CF, ACMTRS_NT, SSD_CF, CUR_CF, ESTMNT_M, INDSUP_B, ORICOD_LS,
 CREUSR_CF, LSTUPD_D, LSTUPDUSR_CF, ORICTR_NF, ORISEC_NF, ORIUWY_NF, DIFF_M, PROPAGATION_B,
 CALCULATED_B, BATCH_B)
SELECT
 LIFEST.CTR_NF, END_NT, LIFEST.SEC_NF, LIFEST.UWY_NF, UW_NT, getdate(), LIFEST.BALSHEY_NF, 
 BALSHTMTH_NF, LIFEST.ACY_NF, LIFEST.GAAP_NT, LIFEST.DETTRNCOD_CF, ACM_NF, PRS_CF, LIFEST.ACMTRS_NT, 
 SSD_CF, CUR_CF, 0.000, INDSUP_B, 'Spira 73382', CREUSR_CF, getdate(), LSTUPDUSR_CF, ORICTR_NF, 
 ORISEC_NF, ORIUWY_NF, 0.000, PROPAGATION_B,
 CALCULATED_B, BATCH_B
FROM
    BEST..TLIFEST LIFEST,
    #SCOPE_TYP1_A SCOPE_TYP1_A
WHERE
        LIFEST.CTR_NF       = SCOPE_TYP1_A.CTR_NF
AND     LIFEST.SEC_NF       = SCOPE_TYP1_A.SEC_NF
AND     LIFEST.BALSHEY_NF   = SCOPE_TYP1_A.BALSHEY_NF
AND     LIFEST.UWY_NF       = SCOPE_TYP1_A.UWY_NF
AND     LIFEST.ACY_NF       = SCOPE_TYP1_A.ACY_NF
AND     LIFEST.DETTRNCOD_CF = SCOPE_TYP1_A.DETTRNCOD_CF
AND     LIFEST.ACMTRS_NT    = SCOPE_TYP1_A.ACMTRS_NT
AND     LIFEST.GAAP_NT      = SCOPE_TYP1_A.GAAP_NT
AND     LIFEST.CRE_D        = SCOPE_TYP1_A.MAX_CRE_D
AND     LIFEST.ESTMNT_M    != 0

SELECT  @erreur = @@error , @nbline = @@rowcount 
IF @erreur != 0
BEGIN
  PRINT 'UPDATE TO 0 ACY <> UWY : %1!', @@ERROR
  ROLLBACK TRAN
END
ELSE
BEGIN
  COMMIT TRAN
  PRINT 'END OF SCRIPT - COMMIT - NB-LINE AFFECTED ACCEPTE : %1!', @nbline
END


---------------------
-- RETRO 
---------------------
BEGIN TRAN

-- Updating to 0 lines where ACY <> UWY
INSERT INTO BEST..TLIFEST
(CTR_NF, END_NT, SEC_NF, UWY_NF, UW_NT, CRE_D, BALSHEY_NF, BALSHTMTH_NF, ACY_NF, GAAP_NT,
 DETTRNCOD_CF, ACM_NF, PRS_CF, ACMTRS_NT, SSD_CF, CUR_CF, ESTMNT_M, INDSUP_B, ORICOD_LS,
 CREUSR_CF, LSTUPD_D, LSTUPDUSR_CF, ORICTR_NF, ORISEC_NF, ORIUWY_NF, DIFF_M, PROPAGATION_B,
 CALCULATED_B, BATCH_B)
SELECT
 LIFEST.CTR_NF, END_NT, LIFEST.SEC_NF, LIFEST.UWY_NF, UW_NT, getdate(), LIFEST.BALSHEY_NF, 
 BALSHTMTH_NF, LIFEST.ACY_NF, LIFEST.GAAP_NT, LIFEST.DETTRNCOD_CF, ACM_NF, PRS_CF, LIFEST.ACMTRS_NT, 
 SSD_CF, CUR_CF, 0.000, INDSUP_B, 'Spira 73382', CREUSR_CF, getdate(), LSTUPDUSR_CF, ORICTR_NF, 
 ORISEC_NF, ORIUWY_NF, 0.000, PROPAGATION_B,
 CALCULATED_B, BATCH_B
FROM
    BEST..TLIFEST LIFEST,
    #SCOPE_TYP1_R SCOPE_TYP1_R
WHERE
        LIFEST.CTR_NF       = SCOPE_TYP1_R.CTR_NF
AND     LIFEST.SEC_NF       = SCOPE_TYP1_R.SEC_NF
AND     LIFEST.BALSHEY_NF   = SCOPE_TYP1_R.BALSHEY_NF
AND     LIFEST.UWY_NF       = SCOPE_TYP1_R.UWY_NF
AND     LIFEST.ACY_NF       = SCOPE_TYP1_R.ACY_NF
AND     LIFEST.DETTRNCOD_CF = SCOPE_TYP1_R.DETTRNCOD_CF
AND     LIFEST.ACMTRS_NT    = SCOPE_TYP1_R.ACMTRS_NT
AND     LIFEST.GAAP_NT      = SCOPE_TYP1_R.GAAP_NT
AND     LIFEST.CRE_D        = SCOPE_TYP1_R.MAX_CRE_D
AND     LIFEST.ESTMNT_M    != 0

SELECT  @erreur = @@error , @nbline = @@rowcount 
IF @erreur != 0
BEGIN
  PRINT 'UPDATE TO 0 ACY <> UWY : %1!', @@ERROR
  ROLLBACK TRAN
END
ELSE
BEGIN
  COMMIT TRAN
  PRINT 'END OF SCRIPT - COMMIT - NB-LINE AFFECTED RETRO : %1!', @nbline
END


fin:
IF EXISTS (SELECT * FROM sysindexes WHERE id=OBJECT_ID('#SCOPE_TYP1_A') AND name='ISCOPE_TYP1_A')
BEGIN
	DROP INDEX #SCOPE_TYP1_A.ISCOPE_TYP1_A
END
IF EXISTS (SELECT OBJECT_ID('#SCOPE_TYP1_A'))
BEGIN
	DROP TABLE #SCOPE_TYP1_A 
END
IF EXISTS (SELECT * FROM sysindexes WHERE id=OBJECT_ID('#SCOPE_TYP1_R') AND name='ISCOPE_TYP1_R')
BEGIN
	DROP INDEX #SCOPE_TYP1_R.ISCOPE_TYP1_R
END
IF EXISTS (SELECT OBJECT_ID('#SCOPE_TYP1_R'))
BEGIN
	DROP TABLE #SCOPE_TYP1_R 
END


GO
-------------------
-- END OF SCRIPT --
-------------------
