-- --------------------------------------------------------------------------------------------- --
-- Script						: EST_87213_INSERT_STS_TBANTECL.sql
-- Domain						: EST
-- Database					: BREF    
-- Author						: L. Wernert
-- Creation date		: 14/08/2020
-- Description      : Inserting new file loading status for automatic estimates upload (TBANTEC, TBANTECL, TBANCOD, TBANCODL)
-- --------------------------------------------------------------------------------------------- --
USE BREF
go

BEGIN TRAN

-- Delete BREF..TBANTECL --
-- EN
DELETE FROM TBANTECL WHERE LAG_CF = 'E' AND COL_LS = 'ESTUPLDSTS_CT' AND COLVAL_CT = '0'
DELETE FROM TBANTECL WHERE LAG_CF = 'E' AND COL_LS = 'ESTUPLDSTS_CT' AND COLVAL_CT = '1'
DELETE FROM TBANTECL WHERE LAG_CF = 'E' AND COL_LS = 'ESTUPLDSTS_CT' AND COLVAL_CT = '2'
DELETE FROM TBANTECL WHERE LAG_CF = 'E' AND COL_LS = 'ESTUPLDSTS_CT' AND COLVAL_CT = '5'
DELETE FROM TBANTECL WHERE LAG_CF = 'E' AND COL_LS = 'ESTUPLDSTS_CT' AND COLVAL_CT = '10'

-- FR
DELETE FROM TBANTECL WHERE LAG_CF = 'F' AND COL_LS = 'ESTUPLDSTS_CT' AND COLVAL_CT = '0'
DELETE FROM TBANTECL WHERE LAG_CF = 'F' AND COL_LS = 'ESTUPLDSTS_CT' AND COLVAL_CT = '1'
DELETE FROM TBANTECL WHERE LAG_CF = 'F' AND COL_LS = 'ESTUPLDSTS_CT' AND COLVAL_CT = '2'
DELETE FROM TBANTECL WHERE LAG_CF = 'F' AND COL_LS = 'ESTUPLDSTS_CT' AND COLVAL_CT = '5'
DELETE FROM TBANTECL WHERE LAG_CF = 'F' AND COL_LS = 'ESTUPLDSTS_CT' AND COLVAL_CT = '10'

-- Delete TBANTEC --
DELETE FROM TBANTEC WHERE COL_LS = 'ESTUPLDSTS_CT' AND COLVAL_CT = '0'
DELETE FROM TBANTEC WHERE COL_LS = 'ESTUPLDSTS_CT' AND COLVAL_CT = '1'
DELETE FROM TBANTEC WHERE COL_LS = 'ESTUPLDSTS_CT' AND COLVAL_CT = '2'
DELETE FROM TBANTEC WHERE COL_LS = 'ESTUPLDSTS_CT' AND COLVAL_CT = '5'
DELETE FROM TBANTEC WHERE COL_LS = 'ESTUPLDSTS_CT' AND COLVAL_CT = '10'


-- Insertion dans TBANTEC --
INSERT INTO TBANTEC (COL_LS, COLVAL_CT, ACTCOD_B, CODVALSSD_CF, LSTUPDUSR_CF, GRP_B) 
VALUES ('ESTUPLDSTS_CT', '0', 1, NULL, 'sa', 1)
	
INSERT INTO TBANTEC (COL_LS, COLVAL_CT, ACTCOD_B, CODVALSSD_CF, LSTUPDUSR_CF, GRP_B) 
VALUES ('ESTUPLDSTS_CT', '1', 1, NULL, 'sa', 1)
	
INSERT INTO TBANTEC (COL_LS, COLVAL_CT, ACTCOD_B, CODVALSSD_CF, LSTUPDUSR_CF, GRP_B) 
VALUES ('ESTUPLDSTS_CT', '2', 1, NULL, 'sa', 1)
	
INSERT INTO TBANTEC (COL_LS, COLVAL_CT, ACTCOD_B, CODVALSSD_CF, LSTUPDUSR_CF, GRP_B) 
VALUES ('ESTUPLDSTS_CT', '5', 1, NULL, 'sa', 1)
	
INSERT INTO TBANTEC (COL_LS, COLVAL_CT, ACTCOD_B, CODVALSSD_CF, LSTUPDUSR_CF, GRP_B) 
VALUES ('ESTUPLDSTS_CT', '10', 1, NULL, 'sa', 1)


-- Insertion dans TBANTECL --
-- EN
INSERT INTO TBANTECL (LAG_CF, COL_LS, COLVAL_CT, COLVAL_LM, COLVAL_LS, CODVALSSD_CF, LSTUPDUSR_CF) 
VALUES ('E', 'ESTUPLDSTS_CT', '0', 'Waiting', 'Waiting', NULL, 'sa')

INSERT INTO TBANTECL (LAG_CF, COL_LS, COLVAL_CT, COLVAL_LM, COLVAL_LS, CODVALSSD_CF, LSTUPDUSR_CF) 
VALUES ('E', 'ESTUPLDSTS_CT', '1', 'In force', 'In force', NULL, 'sa')
	
INSERT INTO TBANTECL (LAG_CF, COL_LS, COLVAL_CT, COLVAL_LM, COLVAL_LS, CODVALSSD_CF, LSTUPDUSR_CF) 
VALUES ('E', 'ESTUPLDSTS_CT', '2', 'Closed', 'Closed', NULL, 'sa')
	
INSERT INTO TBANTECL (LAG_CF, COL_LS, COLVAL_CT, COLVAL_LM, COLVAL_LS, CODVALSSD_CF, LSTUPDUSR_CF) 
VALUES ('E', 'ESTUPLDSTS_CT', '5', 'Failed', 'Failed', NULL, 'sa')
	
INSERT INTO TBANTECL (LAG_CF, COL_LS, COLVAL_CT, COLVAL_LM, COLVAL_LS, CODVALSSD_CF, LSTUPDUSR_CF) 
VALUES ('E', 'ESTUPLDSTS_CT', '10', 'Closed with abnormalities', 'Abnormal Closed', NULL, 'sa')
	
-- FR
INSERT INTO TBANTECL (LAG_CF, COL_LS, COLVAL_CT, COLVAL_LM, COLVAL_LS, CODVALSSD_CF, LSTUPDUSR_CF) 
VALUES ('F', 'ESTUPLDSTS_CT', '0', 'En attente', 'En attente', NULL, 'sa')

INSERT INTO TBANTECL (LAG_CF, COL_LS, COLVAL_CT, COLVAL_LM, COLVAL_LS, CODVALSSD_CF, LSTUPDUSR_CF) 
VALUES ('F', 'ESTUPLDSTS_CT', '1', 'En cours', 'En cours', NULL, 'sa')
	
INSERT INTO TBANTECL (LAG_CF, COL_LS, COLVAL_CT, COLVAL_LM, COLVAL_LS, CODVALSSD_CF, LSTUPDUSR_CF) 
VALUES ('F', 'ESTUPLDSTS_CT', '2', 'Termine', 'Termine', NULL, 'sa')
	
INSERT INTO TBANTECL (LAG_CF, COL_LS, COLVAL_CT, COLVAL_LM, COLVAL_LS, CODVALSSD_CF, LSTUPDUSR_CF) 
VALUES ('F', 'ESTUPLDSTS_CT', '5', 'Echec', 'Echec', NULL, 'sa')
	
INSERT INTO TBANTECL (LAG_CF, COL_LS, COLVAL_CT, COLVAL_LM, COLVAL_LS, CODVALSSD_CF, LSTUPDUSR_CF) 
VALUES ('F', 'ESTUPLDSTS_CT', '10', 'Termine avec anomalies', 'Anomalie Termine', NULL, 'sa')




-- Delete TBANCODL --
DELETE FROM BREF..TBANCODL WHERE COL_LS = 'ESTUPLDSTS_CT' and LAG_CF in ('E','F','G','I','O','S')

-- Delete TBANCOD --
DELETE FROM BREF..TBANCOD WHERE COL_LS = 'ESTUPLDSTS_CT' 


-- Insertion dans TBANCOD --
INSERT INTO BREF..TBANCOD (COL_LS, TECCOD_B, CODFMT_CT, CODLNG_N, CODNAT_CT, LSTUPDUSR_CF, timestamp, CODDMN_CT) 
VALUES ('ESTUPLDSTS_CT', 1, 1, 0, 0, 'sa', null, '15')

-- Insertion dans TBANCODL --
INSERT INTO BREF..TBANCODL(LAG_CF, COL_LS, COLLNG_LS, LSTUPDUSR_CF, timestamp) 
VALUES ('E', 'ESTUPLDSTS_CT', 'Status batch', 'sa', null)

INSERT INTO BREF..TBANCODL(LAG_CF, COL_LS, COLLNG_LS, LSTUPDUSR_CF, timestamp) 
VALUES ('F', 'ESTUPLDSTS_CT', 'Statut batch', 'sa', null)

INSERT INTO BREF..TBANCODL(LAG_CF, COL_LS, COLLNG_LS, LSTUPDUSR_CF, timestamp) 
VALUES ('G', 'ESTUPLDSTS_CT', 'Status batch', 'sa', null)

INSERT INTO BREF..TBANCODL(LAG_CF, COL_LS, COLLNG_LS, LSTUPDUSR_CF, timestamp) 
VALUES ('I', 'ESTUPLDSTS_CT', 'Status batch', 'sa', null)

INSERT INTO BREF..TBANCODL(LAG_CF, COL_LS, COLLNG_LS, LSTUPDUSR_CF, timestamp) 
VALUES ('O', 'ESTUPLDSTS_CT', 'Status batch', 'sa', null)

INSERT INTO BREF..TBANCODL(LAG_CF, COL_LS, COLLNG_LS, LSTUPDUSR_CF, timestamp) 
VALUES ('S', 'ESTUPLDSTS_CT', 'Status batch', 'sa', null)


-- ------------------- --
-- Transaction end     --
-- ------------------- --	
COMMIT TRAN
-- ROLLBACK TRAN

fin:
PRINT 'END   - SPIRA : %1!', 87213

GO