USE BREF
GO

-- ######################################################################################################################################
-- Description fonctionnelle    : REQ10.03 BREF..TPRSMAP init script  3000 
-- ######################################################################################################################################


begin tran



INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 1010, 'PR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 1011, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 1012, 'PR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 1013, 'PR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 1014, 'PR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 1015, 'PR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 1016, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 1018, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 1019, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 1030, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 1031, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 1032, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 1033, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 1051, 'PR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 1052, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 1053, 'PR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 2010, 'PR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 2011, 'PR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 2012, 'PR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 2013, 'PR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 2014, 'PR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 2015, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 2016, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 2017, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 2018, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 2019, 'PR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 2030, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 2031, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 2032, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 2051, 'PR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 2052, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 2053, 'PR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 2054, 'PR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 2060, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 2070, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 3010, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 3011, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 3012, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 3013, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 3014, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 3015, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 3017, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 3020, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 3021, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 3022, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 3030, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 3031, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 3032, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 3040, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 3050, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 3070, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 3080, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 3082, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 3085, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 3088, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 3090, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 3091, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 3092, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 3093, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 3094, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 3095, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 3096, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 3097, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 3098, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 3099, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 3110, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 3111, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 3112, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 3113, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 3114, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 3115, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 3121, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 3160, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 3171, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 3201, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 7015, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 7016, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 7020, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 7021, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 7025, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 7026, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 7027, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 7028, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 9023, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 9024, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 9025, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 9026, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO BREF.dbo.TPRSMAP
(PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10)
VALUES(751, 9027, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)


commit tran

go

print "Data inserted"