USE BREF
GO

-- TABLE INSERT STATEMENTS dans TPRSMAP  10.13

/* BREF.dbo.TPRSMAP  10.13 */
--SELECT top 100 * 
--FROM BREF.dbo.TPRSMAP
--where ACMTRS_NT in (2055,2057,2056,2010,2014,2018)
--and PRS_CF = 751



-- TABLE INSERT STATEMENTS dans TPRSMAP
DELETE FROM BREF..TPRSMAP WHERE ACMTRS_NT = 2010 AND PRS_CF = 751
GO
INSERT INTO BREF..TPRSMAP ( PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10 ) 
        VALUES ( 751, 2010, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL )
GO        
DELETE FROM BREF..TPRSMAP WHERE ACMTRS_NT = 2014 AND PRS_CF = 751
GO
INSERT INTO BREF..TPRSMAP ( PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10 ) 
        VALUES ( 751, 2014, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL )
GO        
DELETE FROM BREF..TPRSMAP WHERE ACMTRS_NT = 2055 AND PRS_CF = 751
GO
INSERT INTO BREF..TPRSMAP ( PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10 ) 
        VALUES ( 751, 2055, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL )
GO        
DELETE FROM BREF..TPRSMAP WHERE ACMTRS_NT = 2056 AND PRS_CF = 751
GO
INSERT INTO BREF..TPRSMAP ( PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10 ) 
        VALUES ( 751, 2056, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL )
GO        
DELETE FROM BREF..TPRSMAP WHERE ACMTRS_NT = 2057 AND PRS_CF = 751
GO
INSERT INTO BREF..TPRSMAP ( PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10 ) 
        VALUES ( 751, 2057, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL )
GO        
DELETE FROM BREF..TPRSMAP WHERE ACMTRS_NT = 2018 AND PRS_CF = 751
GO
INSERT INTO BREF..TPRSMAP ( PRS_CF, ACMTRS_NT, PARM1, PARM2, PARM3, PARM4, PARM5, PARM6, PARM7, PARM8, PARM9, PARM10 ) 
VALUES ( 751, 2018, 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL )
GO