-- script d'update global pour 

if not exists ( select 1 from BEST..TI17CHN where CHAIN_CT='ESFDMRG0')  
	insert into BEST..TI17CHN values ('ESFDMRG0',  '')

--
-- TABLE TI17FNC
--

if not exists ( select 1 from BEST..TI17FNC where idf_ct ='I17L_EXTENDED'  ) 
	insert into BEST..TI17FNC values ('I17L_EXTENDED','',  'ESFDMRG0',0) 

if not exists ( select 1 from BEST..TI17FNC where idf_ct ='I17P_EXTENDED'  ) 
	insert into BEST..TI17FNC values ('I17P_EXTENDED', '', 'ESFDMRG0', 0)

--
--- TABLE TI17REQ
--
if not exists ( select 1 from BEST..TI17REQ where REQCOD_CT='I17LQPOSX') 
	INSERT INTO  BEST..TI17REQ  VALUES ( 'I17LQPOSX', 'Quarterly POS IFRS 17 Local EXTENDED Closing', 'N', 'K' )

if not exists ( select 1 from BEST..TI17REQ where REQCOD_CT='I17PQPOSX') 
	INSERT INTO BEST..TI17REQ   VALUES ( 'I17PQPOSX', 'Quarterly POS IFRS 17 Local EXTENDED Closing', 'N', 'K' )

if not exists ( select 1 from BEST..TI17REQ where REQCOD_CT='I17LYPOSX') 
	INSERT INTO BEST..TI17REQ   VALUES ( 'I17LYPOSX', 'Annual POS IFRS 17 Parent EXTENDED Closing', 'N', 'H' )

if not exists ( select 1 from BEST..TI17REQ where REQCOD_CT='I17PYPOSX') 
	INSERT INTO BEST..TI17REQ VALUES ( 'I17PYPOSX', 'Annual POS IFRS 17 Parent EXTENDED Closing', 'N', 'H' )

--
-- TABLE TI17REQFNC
--

--select * from BEST..TI17REQFNC where REQCOD_CT like "I17[LP][QY]POSX" 
/*
select distinct Chain_ct , idf_ct
from BEST..TI17FNC 
where IDF_CT in (select distinct IDF_CT from BEST..TI17REQFNC where IDF_CT not like '%INI%' and (REQCOD_CT like 'I17L%POS' or REQCOD_CT like 'I17P%POS') )
*/

delete BEST..TI17REQFNC where REQCOD_CT like "I17[LP][QY]POSX" 

INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'EXTJ0010', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LQPOSX', 'EXTJ0010', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PQPOSX', 'EXTJ0010', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PYPOSX', 'EXTJ0010', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LQPOSX', 'I17G_RA_SAP_CHK', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PYPOSX', 'I17G_RA_SAP_CHK', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PQPOSX', 'I17G_RA_SAP_CHK', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'I17G_RA_SAP_CHK', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'I17L___', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LQPOSX', 'I17L___', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LQPOSX', 'I17L_AEE_RPO_I17', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'I17L_AEE_RPO_I17', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'I17L_AET_RPO_I17', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LQPOSX', 'I17L_AET_RPO_I17', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'I17L_CSM_ACC_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LQPOSX', 'I17L_CSM_ACC_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'I17L_CSM_ALL_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LQPOSX', 'I17L_CSM_ALL_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LQPOSX', 'I17L_DLT_SAP_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'I17L_DLT_SAP_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LQPOSX', 'I17L_DSC_ALL_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'I17L_DSC_ALL_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'I17L_DSC_DSI_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LQPOSX', 'I17L_DSC_DSI_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LQPOSX', 'I17L_DSC_LKI_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'I17L_DSC_LKI_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LQPOSX', 'I17L_EXT_PER_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'I17L_EXT_PER_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LQPOSX', 'I17L_EXTENDED', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'I17L_EXTENDED', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'I17L_GLT_AOC_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LQPOSX', 'I17L_GLT_AOC_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LQPOSX', 'I17L_GLT_GAP_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'I17L_GLT_GAP_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LQPOSX', 'I17L_GLT_MRG_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'I17L_GLT_MRG_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'I17L_GRN_UPD_ALL', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LQPOSX', 'I17L_GRN_UPD_ALL', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LQPOSX', 'I17L_IEX_ALL_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'I17L_IEX_ALL_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LQPOSX', 'I17L_IRV_ALL_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'I17L_IRV_ALL_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LQPOSX', 'I17L_LCC_RPO_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'I17L_LCC_RPO_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LQPOSX', 'I17L_MVT_MRG_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'I17L_MVT_MRG_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'I17L_MVT_SPL_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LQPOSX', 'I17L_MVT_SPL_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LQPOSX', 'I17L_OMG_ALL_TRA', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'I17L_OMG_ALL_TRA', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'I17L_OMG_CES_LIF', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LQPOSX', 'I17L_OMG_CES_LIF', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'I17L_OMG_CLO_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LQPOSX', 'I17L_OMG_CLO_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LQPOSX', 'I17L_OMG_EX_LIF', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'I17L_OMG_EX_LIF', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'I17L_OMG_OPNG_SIM', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LQPOSX', 'I17L_OMG_RA_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'I17L_OMG_RA_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LQPOSX', 'I17L_OMG_RET_LIF', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'I17L_OMG_RET_LIF', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'I17L_OMG_ROC_TRA', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LQPOSX', 'I17L_OMG_ROC_TRA', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'I17L_OMG_SAP_LIF', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LQPOSX', 'I17L_OMG_SAP_LIF', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'I17L_OMG_TP_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LQPOSX', 'I17L_OMG_TP_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'I17L_PAA_ALL_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LQPOSX', 'I17L_PAA_ALL_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LQPOSX', 'I17L_PRO_INT_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'I17L_PRO_INT_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'I17L_RAD_CKI_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LQPOSX', 'I17L_RAD_CKI_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LQPOSX', 'I17L_RAD_CUR_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'I17L_RAD_CUR_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'I17L_RAD_DSI_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LQPOSX', 'I17L_RAD_DSI_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LQPOSX', 'I17L_RAD_LKI_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'I17L_RAD_LKI_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LQPOSX', 'I17L_SAP_CHK_SIMU', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'I17L_SAP_CHK_SIMU', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LQPOSX', 'I17L_SAP_OMG_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'I17L_SAP_OMG_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'I17L_SEC_UPD_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LQPOSX', 'I17L_SEC_UPD_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'I17L_SEG_PRO_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LQPOSX', 'I17L_SEG_PRO_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'I17L_SII_ALL_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LQPOSX', 'I17L_SII_ALL_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LQPOSX', 'I17L_SII_GLT_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'I17L_SII_GLT_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'I17L_SII_IOR_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LQPOSX', 'I17L_SII_IOR_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LQPOSX', 'I17L_SII_MRG_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'I17L_SII_MRG_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LQPOSX', 'I17L_TMP_PER_FUT', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'I17L_TMP_PER_FUT', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'I17L_UOA_PRO_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LQPOSX', 'I17L_UOA_PRO_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'I17L_UWD_ALL_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LQPOSX', 'I17L_UWD_ALL_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PYPOSX', 'I17P___', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PQPOSX', 'I17P___', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PQPOSX', 'I17P_AEE_RPO_I17', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PYPOSX', 'I17P_AEE_RPO_I17', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PQPOSX', 'I17P_AET_RPO_I17', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PYPOSX', 'I17P_AET_RPO_I17', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PYPOSX', 'I17P_CSM_ACC_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PQPOSX', 'I17P_CSM_ACC_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PYPOSX', 'I17P_CSM_ALL_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PQPOSX', 'I17P_CSM_ALL_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PQPOSX', 'I17P_DLT_SAP_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PYPOSX', 'I17P_DLT_SAP_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PQPOSX', 'I17P_DSC_ALL_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PYPOSX', 'I17P_DSC_ALL_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PYPOSX', 'I17P_DSC_DSI_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PQPOSX', 'I17P_DSC_DSI_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PYPOSX', 'I17P_DSC_LKI_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PQPOSX', 'I17P_DSC_LKI_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PQPOSX', 'I17P_EXT_PER_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PYPOSX', 'I17P_EXT_PER_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PQPOSX', 'I17P_EXTENDED', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PYPOSX', 'I17P_EXTENDED', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PQPOSX', 'I17P_GLT_AOC_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PYPOSX', 'I17P_GLT_AOC_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PYPOSX', 'I17P_GLT_GAP_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PQPOSX', 'I17P_GLT_GAP_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PQPOSX', 'I17P_GLT_MRG_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PYPOSX', 'I17P_GLT_MRG_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PYPOSX', 'I17P_GRN_UPD_ALL', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PQPOSX', 'I17P_GRN_UPD_ALL', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PQPOSX', 'I17P_IEX_ALL_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PYPOSX', 'I17P_IEX_ALL_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PQPOSX', 'I17P_IRV_ALL_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PYPOSX', 'I17P_IRV_ALL_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PQPOSX', 'I17P_LCC_RPO_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PYPOSX', 'I17P_LCC_RPO_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PQPOSX', 'I17P_MVT_MRG_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PYPOSX', 'I17P_MVT_MRG_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PYPOSX', 'I17P_MVT_SPL_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PQPOSX', 'I17P_MVT_SPL_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PYPOSX', 'I17P_OMG_ALL_TRA', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PQPOSX', 'I17P_OMG_ALL_TRA', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PQPOSX', 'I17P_OMG_CES_LIF', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PYPOSX', 'I17P_OMG_CES_LIF', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PYPOSX', 'I17P_OMG_CLO_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PQPOSX', 'I17P_OMG_CLO_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PYPOSX', 'I17P_OMG_EX_LIF', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PQPOSX', 'I17P_OMG_EX_LIF', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PYPOSX', 'I17P_OMG_OPNG_SIM', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PQPOSX', 'I17P_OMG_RA_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PYPOSX', 'I17P_OMG_RA_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PQPOSX', 'I17P_OMG_RET_LIF', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PYPOSX', 'I17P_OMG_RET_LIF', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PYPOSX', 'I17P_OMG_ROC_TRA', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PQPOSX', 'I17P_OMG_ROC_TRA', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PYPOSX', 'I17P_OMG_SAP_LIF', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PQPOSX', 'I17P_OMG_SAP_LIF', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PQPOSX', 'I17P_OMG_TP_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PYPOSX', 'I17P_OMG_TP_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PYPOSX', 'I17P_PRO_INT_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PQPOSX', 'I17P_PRO_INT_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PYPOSX', 'I17P_RAD_CKI_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PQPOSX', 'I17P_RAD_CKI_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PQPOSX', 'I17P_RAD_CUR_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PYPOSX', 'I17P_RAD_CUR_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PYPOSX', 'I17P_RAD_DSI_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PQPOSX', 'I17P_RAD_DSI_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PQPOSX', 'I17P_RAD_LKI_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PYPOSX', 'I17P_RAD_LKI_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PQPOSX', 'I17P_SAP_CHK_SIMU', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PYPOSX', 'I17P_SAP_CHK_SIMU', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PQPOSX', 'I17P_SAP_OMG_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PYPOSX', 'I17P_SAP_OMG_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PQPOSX', 'I17P_SEC_UPD_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PYPOSX', 'I17P_SEC_UPD_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PYPOSX', 'I17P_SEG_PRO_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PQPOSX', 'I17P_SEG_PRO_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PQPOSX', 'I17P_SII_ALL_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PYPOSX', 'I17P_SII_ALL_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PYPOSX', 'I17P_SII_GLT_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PQPOSX', 'I17P_SII_GLT_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PQPOSX', 'I17P_SII_IOR_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PYPOSX', 'I17P_SII_IOR_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PYPOSX', 'I17P_SII_MRG_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PQPOSX', 'I17P_SII_MRG_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PQPOSX', 'I17P_TMP_PER_FUT', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PYPOSX', 'I17P_TMP_PER_FUT', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PQPOSX', 'I17P_UOA_PRO_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PYPOSX', 'I17P_UOA_PRO_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PYPOSX', 'I17P_UWD_ALL_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PQPOSX', 'I17P_UWD_ALL_STD', ' ' )
 
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PQPOSX', 'I17P_IVR_CHR_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LQPOSX', 'I17L_IVR_CHR_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PYPOSX', 'I17P_IVR_CHR_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'I17L_IVR_CHR_STD', ' ' )
 
 
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PQPOSX', 'I17P_GLT_ALL_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LQPOSX', 'I17L_GLT_ALL_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PYPOSX', 'I17P_GLT_ALL_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'I17L_GLT_ALL_STD', ' ' )
 
 
--INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PQPOSX', 'I17P_RAD_CUR_STD', ' ' ) 
--INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LQPOSX', 'I17L_RAD_CUR_STD', ' ' )
--INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PYPOSX', 'I17P_RAD_CUR_STD', ' ' )
--INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'I17L_RAD_CUR_STD', ' ' )
 
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PQPOSX', 'I17P_GAP_MAP_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LQPOSX', 'I17L_GAP_MAP_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PYPOSX', 'I17P_GAP_MAP_STD', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'I17L_GAP_MAP_STD', ' ' )
 
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PQPOSX', 'I17P_GAP_MAP_LIF', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LQPOSX', 'I17L_GAP_MAP_LIF', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17PYPOSX', 'I17P_GAP_MAP_LIF', ' ' )
INSERT INTO BEST..TI17REQFNC  VALUES ( 'I17LYPOSX', 'I17L_GAP_MAP_LIF', ' ' )
 
 
-- clean POSX in TI17PERMFIL 

update   BEST..TI17PERMFIL  set PATHPATTRN_LL = str_replace(PATHPATTRN_LL,"${PARM_POSX}","") 
go

-- update file POSX 


UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD1130_FSEGPATTERNDSCf17_I17L_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17L_CSM_ALL_STD' AND PERMFIL_CT ='EST_FSEGPATTERN_DSC_f17'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD1130_FSEGPATTERNDSCf17_I17L_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17L_DSC_ALL_STD' AND PERMFIL_CT ='ESF_FSEGPATTERNDSCf17'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD1130_FSEGPATTERNDSCf17_I17L_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17L_DSC_DSI_STD' AND PERMFIL_CT ='ESF_FSEGPATTERNDSCf17'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD1130_FSEGPATTERNDSCf17_I17L_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17L_DSC_LKI_STD' AND PERMFIL_CT ='ESF_FSEGPATTERNDSCf17'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD1130_FSEGPATTERNDSCf17_I17L_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17L_RAD_DSI_STD' AND PERMFIL_CT ='ESF_FSEGPATTERNDSCf17'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD1130_FSEGPATTERNDSCf17_I17L_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17L_RAD_LKI_STD' AND PERMFIL_CT ='ESF_FSEGPATTERNDSCf17'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD1130_FSEGPATTERNDSCf17_I17L_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17L_UWD_ALL_STD' AND PERMFIL_CT ='ESF_FSEGPATTERNDSCf17'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD1130_FSEGPATTERNDSCf17_I17P_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17P_CSM_ALL_STD' AND PERMFIL_CT ='EST_FSEGPATTERN_DSC_f17'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD1130_FSEGPATTERNDSCf17_I17P_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17P_DSC_ALL_STD' AND PERMFIL_CT ='ESF_FSEGPATTERNDSCf17'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD1130_FSEGPATTERNDSCf17_I17P_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17P_DSC_DSI_STD' AND PERMFIL_CT ='ESF_FSEGPATTERNDSCf17'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD1130_FSEGPATTERNDSCf17_I17P_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17P_DSC_LKI_STD' AND PERMFIL_CT ='ESF_FSEGPATTERNDSCf17'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD1130_FSEGPATTERNDSCf17_I17P_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17P_RAD_DSI_STD' AND PERMFIL_CT ='ESF_FSEGPATTERNDSCf17'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD1130_FSEGPATTERNDSCf17_I17P_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17P_RAD_LKI_STD' AND PERMFIL_CT ='ESF_FSEGPATTERNDSCf17'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD1130_FSEGPATTERNDSCf17_I17P_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17P_UWD_ALL_STD' AND PERMFIL_CT ='ESF_FSEGPATTERNDSCf17'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3620_I17L_DSC_LKI_STD_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17L_DSC_LKI_STD' AND PERMFIL_CT ='ESF_GTSII_ESCOMPTE'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3620_I17L_DSC_LKI_STD_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17L_IRV_ALL_STD' AND PERMFIL_CT ='ESF_GTSII_DSC_LKI_ESCOMPTE'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3620_I17L_DSC_LKI_STD_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17L_RAD_CKI_STD' AND PERMFIL_CT ='ESF_GTSII_ESCOMPTE'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3620_I17L_DSC_LKI_STD_GTSII_ESCOMPTE_RMNTP${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17L_DSC_LKI_STD' AND PERMFIL_CT ='ESF_GTSII_ESCOMPTE_RMNTP'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3620_I17L_RAD_LKI_STD_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17L_CSM_ALL_STD' AND PERMFIL_CT ='ESF_GTSII_ESCOMPTE_RAD'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3620_I17L_RAD_LKI_STD_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17L_IRV_ALL_STD' AND PERMFIL_CT ='ESF_GTSII_RAD_LKI_ESCOMPTE'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3620_I17L_RAD_LKI_STD_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17L_RAD_LKI_STD' AND PERMFIL_CT ='ESF_GTSII_ESCOMPTE'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3620_I17L_RAD_LKI_STD_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17L_SII_MRG_STD' AND PERMFIL_CT ='ESF_GTSII_ESCOMPTE_RAD_LKI'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3620_I17L_RAD_LKI_STD_GTSII_ESCOMPTE_RMNTP${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17L_RAD_LKI_STD' AND PERMFIL_CT ='ESF_GTSII_ESCOMPTE_RMNTP'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3620_I17P_DSC_LKI_STD_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17P_DSC_LKI_STD' AND PERMFIL_CT ='ESF_GTSII_ESCOMPTE'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3620_I17P_DSC_LKI_STD_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17P_IRV_ALL_STD' AND PERMFIL_CT ='ESF_GTSII_DSC_LKI_ESCOMPTE'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3620_I17P_DSC_LKI_STD_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17P_RAD_CKI_STD' AND PERMFIL_CT ='ESF_GTSII_ESCOMPTE'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3620_I17P_DSC_LKI_STD_GTSII_ESCOMPTE_RMNTP${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17P_DSC_LKI_STD' AND PERMFIL_CT ='ESF_GTSII_ESCOMPTE_RMNTP'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3620_I17P_RAD_LKI_STD_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17P_CSM_ALL_STD' AND PERMFIL_CT ='ESF_GTSII_ESCOMPTE_RAD'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3620_I17P_RAD_LKI_STD_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17P_IRV_ALL_STD' AND PERMFIL_CT ='ESF_GTSII_RAD_LKI_ESCOMPTE'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3620_I17P_RAD_LKI_STD_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17P_RAD_LKI_STD' AND PERMFIL_CT ='ESF_GTSII_ESCOMPTE'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3620_I17P_RAD_LKI_STD_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17P_SII_MRG_STD' AND PERMFIL_CT ='ESF_GTSII_ESCOMPTE_RAD_LKI'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3620_I17P_RAD_LKI_STD_GTSII_ESCOMPTE_RMNTP${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17P_RAD_LKI_STD' AND PERMFIL_CT ='ESF_GTSII_ESCOMPTE_RMNTP'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3630_I17L_IEX_ALL_STD_GTSII_GLOBAL_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17L_DSC_DSI_STD' AND PERMFIL_CT ='ESF_GTSII_GLOBAL_CASHFLOW'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3630_I17L_IEX_ALL_STD_GTSII_GLOBAL_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17L_DSC_LKI_STD' AND PERMFIL_CT ='ESF_GTSII_GLOBAL_CASHFLOW'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3630_I17L_IEX_ALL_STD_GTSII_GLOBAL_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17L_IEX_ALL_STD' AND PERMFIL_CT ='ESF_GTSII_GLOBAL_CASHFLOW'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3630_I17L_IEX_ALL_STD_GTSII_GLOBAL_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17L_SII_GLT_STD' AND PERMFIL_CT ='ESF_GTSII_FWH'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3630_I17L_IEX_ALL_STD_GTSII_GLOBAL_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17L_SII_MRG_STD' AND PERMFIL_CT ='ESF_GTSII_GLOBAL_CASHFLOW'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3630_I17P_IEX_ALL_STD_GTSII_GLOBAL_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17P_DSC_DSI_STD' AND PERMFIL_CT ='ESF_GTSII_GLOBAL_CASHFLOW'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3630_I17P_IEX_ALL_STD_GTSII_GLOBAL_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17P_DSC_LKI_STD' AND PERMFIL_CT ='ESF_GTSII_GLOBAL_CASHFLOW'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3630_I17P_IEX_ALL_STD_GTSII_GLOBAL_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17P_IEX_ALL_STD' AND PERMFIL_CT ='ESF_GTSII_GLOBAL_CASHFLOW'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3630_I17P_IEX_ALL_STD_GTSII_GLOBAL_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17P_SII_GLT_STD' AND PERMFIL_CT ='ESF_GTSII_FWH'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3630_I17P_IEX_ALL_STD_GTSII_GLOBAL_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17P_SII_MRG_STD' AND PERMFIL_CT ='ESF_GTSII_GLOBAL_CASHFLOW'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3640_I17L_IVR_CHR_STD_DAC_LKI_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17L_IRV_ALL_STD' AND PERMFIL_CT ='ESF_GTSII_DAC_LKI'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3640_I17L_IVR_CHR_STD_DAC_LKI_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17L_IVR_CHR_STD' AND PERMFIL_CT ='ESF_GTSII_DAC_LKI'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3640_I17P_IVR_CHR_STD_DAC_LKI_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17P_IRV_ALL_STD' AND PERMFIL_CT ='ESF_GTSII_DAC_LKI'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3640_I17P_IVR_CHR_STD_DAC_LKI_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17P_IVR_CHR_STD' AND PERMFIL_CT ='ESF_GTSII_DAC_LKI'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3650_I17L_RAD_CKI_STD_GTSII_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17L_RAD_CKI_STD' AND PERMFIL_CT ='ESF_GTSII_CASHFLOW'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3650_I17L_RAD_CKI_STD_GTSII_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17L_RAD_LKI_STD' AND PERMFIL_CT ='ESF_GTSII_GLOBAL_CASHFLOW'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3650_I17L_RAD_CKI_STD_GTSII_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17L_SII_MRG_STD' AND PERMFIL_CT ='ESF_GTSII_CASHFLOW_RAD_CKI'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3650_I17L_RAD_CKI_STD_GTSII_CASHFLOW_WK${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17L_RAD_CKI_STD' AND PERMFIL_CT ='ESF_GTSII_CASHFLOW_WK'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3650_I17P_RAD_CKI_STD_GTSII_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17P_RAD_CKI_STD' AND PERMFIL_CT ='ESF_GTSII_CASHFLOW'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3650_I17P_RAD_CKI_STD_GTSII_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17P_RAD_LKI_STD' AND PERMFIL_CT ='ESF_GTSII_GLOBAL_CASHFLOW'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3650_I17P_RAD_CKI_STD_GTSII_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17P_SII_MRG_STD' AND PERMFIL_CT ='ESF_GTSII_CASHFLOW_RAD_CKI'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3650_I17P_RAD_CKI_STD_GTSII_CASHFLOW_WK${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17P_RAD_CKI_STD' AND PERMFIL_CT ='ESF_GTSII_CASHFLOW_WK'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3760_I17L_UOA_PRO_STD_FSEGPROF_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17L_OMG_TP_STD' AND PERMFIL_CT ='ESF_FSEGPROF_STD'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3760_I17L_UOA_PRO_STD_FSEGPROF_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17L_UOA_PRO_STD' AND PERMFIL_CT ='/'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3760_I17L_UOA_PRO_STD_GTSII_CSM_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17L_CSM_ACC_STD' AND PERMFIL_CT ='ESF_GTSII_CSM_CASHFLOW'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3760_I17L_UOA_PRO_STD_GTSII_CSM_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17L_SII_MRG_STD' AND PERMFIL_CT ='ESF_GTSII_CSM_CASHFLOW'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3760_I17L_UOA_PRO_STD_GTSII_CSM_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17L_UOA_PRO_STD' AND PERMFIL_CT ='ESF_GTSII_CSM_CASHFLOW'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3760_I17P_UOA_PRO_STD_FSEGPROF_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17P_OMG_TP_STD' AND PERMFIL_CT ='ESF_FSEGPROF_STD'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3760_I17P_UOA_PRO_STD_FSEGPROF_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17P_UOA_PRO_STD' AND PERMFIL_CT ='ESF_FSEGPROF_STD'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3760_I17P_UOA_PRO_STD_GTSII_CSM_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17P_CSM_ACC_STD' AND PERMFIL_CT ='ESF_GTSII_CSM_CASHFLOW'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3760_I17P_UOA_PRO_STD_GTSII_CSM_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17P_SII_MRG_STD' AND PERMFIL_CT ='ESF_GTSII_CSM_CASHFLOW'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3760_I17P_UOA_PRO_STD_GTSII_CSM_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17P_UOA_PRO_STD' AND PERMFIL_CT ='ESF_GTSII_CSM_CASHFLOW'
--UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3770_CSM_LC_AMORT_PATTERN_EBS_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17L_CSM_ALL_STD' AND PERMFIL_CT ='ESF_CSM_LC_AMORT_PATTERN'
--UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3770_CSM_LC_AMORT_PATTERN_EBS_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17L_GAP_MAP_STD' AND PERMFIL_CT ='ESF_CSM_LC_AMORT_PATTERN'
--UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3770_CSM_LC_AMORT_PATTERN_EBS_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17L_IVR_CHR_STD' AND PERMFIL_CT ='ESF_CSM_LC_AMORT_PATTERN'
--UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3770_CSM_LC_AMORT_PATTERN_EBS_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17L_SII_GLT_INI' AND PERMFIL_CT ='ESF_CSM_LC_AMORT_PATTERN'
--UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3770_CSM_LC_AMORT_PATTERN_EBS_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17L_SII_GLT_STD' AND PERMFIL_CT ='ESF_CSM_LC_AMORT_PATTERN'
--UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3770_CSM_LC_AMORT_PATTERN_EBS_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17L_UOA_PRO_STD' AND PERMFIL_CT ='ESF_CSM_LC_AMORT_PATTERN'
--UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3770_CSM_LC_AMORT_PATTERN_EBS_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17P_CSM_ALL_STD' AND PERMFIL_CT ='ESF_CSM_LC_AMORT_PATTERN'
--UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3770_CSM_LC_AMORT_PATTERN_EBS_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17P_GAP_MAP_STD' AND PERMFIL_CT ='ESF_CSM_LC_AMORT_PATTERN'
--UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3770_CSM_LC_AMORT_PATTERN_EBS_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17P_IVR_CHR_STD' AND PERMFIL_CT ='ESF_CSM_LC_AMORT_PATTERN'
--UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3770_CSM_LC_AMORT_PATTERN_EBS_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17P_SII_GLT_INI' AND PERMFIL_CT ='ESF_CSM_LC_AMORT_PATTERN'
--UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3770_CSM_LC_AMORT_PATTERN_EBS_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17P_SII_GLT_STD' AND PERMFIL_CT ='ESF_CSM_LC_AMORT_PATTERN'
--UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3770_CSM_LC_AMORT_PATTERN_EBS_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17P_UOA_PRO_STD' AND PERMFIL_CT ='ESF_CSM_LC_AMORT_PATTERN'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3840_I17L_GLT_MRG_STD_FTECLEDA_MVT_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17L_GLT_MRG_STD' AND PERMFIL_CT ='ESF_FTECLEDA_MVT'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3840_I17L_GLT_MRG_STD_FTECLEDA_MVT_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17L_MVT_SPL_STD' AND PERMFIL_CT ='EPO_FTECLEDASO_MVT'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3840_I17P_GLT_MRG_STD_FTECLEDA_MVT_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17P_GLT_MRG_STD' AND PERMFIL_CT ='ESF_FTECLEDA_MVT'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3840_I17P_GLT_MRG_STD_FTECLEDA_MVT_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17P_MVT_SPL_STD' AND PERMFIL_CT ='EPO_FTECLEDASO_MVT'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3840_I17P_GLT_MRG_STD_FTECLEDR_MVT_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17P_GLT_MRG_STD' AND PERMFIL_CT ='ESF_FTECLEDR_MVT'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3840_I17P_GLT_MRG_STD_FTECLEDR_MVT_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17P_OMG_BOOK_STD' AND PERMFIL_CT ='ESF_FTECLEDR_POSTING'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3840_I17P_GLT_MRG_STD_FTECLEDR_MVT_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17P_OMG_OPNG_SIM' AND PERMFIL_CT ='ESF_FTECLEDR_POSTING'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3840_I17P_GLT_MRG_STD_FTECLEDR_MVT_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17P_OMG_RA_STD' AND PERMFIL_CT ='ESF_FTECLEDR'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3870_I17L_GLT_ALL_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17L_GLT_ALL_STD' AND PERMFIL_CT ='ESF_FTECLEDA'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3870_I17L_GLT_ALL_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17L_GLT_ALL_STD' AND PERMFIL_CT ='ESF_FTECLEDA_3870'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3870_I17L_GLT_ALL_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17L_PAA_ALL_STD' AND PERMFIL_CT ='ESF_FTECLEDA'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3870_I17P_GLT_ALL_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17P_GAP_MAP_STD' AND PERMFIL_CT ='ESF_FTECLEDA'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3870_I17P_GLT_ALL_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17P_GLT_ALL_STD' AND PERMFIL_CT ='ESF_FTECLEDA'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD3870_I17P_GLT_ALL_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17P_GLT_ALL_STD' AND PERMFIL_CT ='ESF_FTECLEDA_3870'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD4020_DLCUMGTAAR_ITD_EBS_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17L_IVR_CHR_STD' AND PERMFIL_CT ='EST_DLCUMGTAAR_ITD'
UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD4020_DLCUMGTAAR_ITD_EBS_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat' WHERE IDF_CT='I17P_IVR_CHR_STD' AND PERMFIL_CT ='EST_DLCUMGTAAR_ITD'

go 
 