-------------------------------
--mapping of  ESID7000

	----------   Clean tables   ---------------------

	delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESID7000')
	delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESID7000')
	delete BEST..TI17FNC where CHAIN_CT='ESID7000'
	delete BEST..TI17CHN  where CHAIN_CT='ESID7000'

	insert into BEST..TI17CHN values ('ESID7000',  '')

	----------IDF_CT:   ESID7000 ------------------

		insert into BEST..TI17FNC values ('ESID7000',' ','ESID7000',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('ESID7000',  'EST_GTA','${DFILP}/${ENV_PREFIX}_ESIX7000_GTA.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'EST_GTR','${DFILP}/${ENV_PREFIX}_ESIX7000_GTR.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'EST_CURGTA','${DFILP}/${ENV_PREFIX}_ESIX7000_CURGTA.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'EST_CURGTR','${DFILP}/${ENV_PREFIX}_ESIX7000_CURGTR.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'EST_SUBTRS','${DFILP}/${ENV_PREFIX}_ESCJ0060_FSUBTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'EST_FCESANT','${DFILP}/${ENV_PREFIX}_ESIX7000_FCESANT.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'EST_FDETTRS','${DFILP}/${ENV_PREFIX}_ESCJ0060_FDETTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'EST_FPLCANT','${DFILP}/${ENV_PREFIX}_ESIX7000_FPLCANT.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'EST_FTRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'EST_STATGTA','${DFILP}/${ENV_PREFIX}_ESIX7000_STATGTA.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'EST_STATGTR','${DFILP}/${ENV_PREFIX}_ESIX7000_STATGTR.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'EST_FCURCVSN','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURCVSN.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'EST_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'EST_FCURCVSNI','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURCVSNI.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'EST_ARCSTATGTA','${DFILP}/${ENV_PREFIX}_ESIX7000_ARCSTATGTA.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'EST_ARCSTATGTR','${DFILP}/${ENV_PREFIX}_ESIX7000_ARCSTATGTR.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'EST_FTRANSCODE','${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRANSCODE.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'EST_STATGTACTL','${DFILP}/${ENV_PREFIX}_ESIX7000_STATGTACTL.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'EST_VENTNP_TRIMCUR','${DFILP}/${ENV_PREFIX}_ESIX7000_VENTNP_TRIMCUR.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'EST_FCES','${DFILP}/${ENV_PREFIX}_ESID2500_FCES_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'EST_FPLC','${DFILP}/${ENV_PREFIX}_ESID2500_FPLC_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'EST_VENTNP_TRIMPREV','${DFILP}/${ENV_PREFIX}_ESIX7000_VENTNP_TRIMPREV.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'EST_FCLIENT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCLIENT_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'EST_FCPLACC','${DFILP}/${ENV_PREFIX}_ESID0560_FCPLACC_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'EST_FCTRGRO','${DFILP}/${ENV_PREFIX}_ESID0560_FCTRGRO_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'EST_FSOBBLOB','${DFILP}/${ENV_PREFIX}_ESCJ0060_FSOBBLOB_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'EST_FSSDACTR','${DFILP}/${ENV_PREFIX}_ESCJ0060_FSSDACTR_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'EST_FTVENTNP','${DFILP}/${ENV_PREFIX}_ESID0060_FTVENTNP_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'EST_FPLACEMT2','${DFILP}/${ENV_PREFIX}_ESEH1110_FPLACEMT2_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'EST_FPLATXCUM','${DFILP}/${ENV_PREFIX}_ESID0560_FPLATXCUM_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'EST_GTACTL','${DFILP}/${ENV_PREFIX}_ESIX7000_GTACTL${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'EST_GTRANO','${DFILP}/${ENV_PREFIX}_ESIX7000_GTRANO${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'EST_FVENTNPANT','${DFILP}/${ENV_PREFIX}_ESIX7000_FVENTNPANT_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'EST_DLREJGTR','${DFILP}/${ENV_PREFIX}_ESID2900_DLREJGTR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'EST_DLTOTGTR','${DFILP}/${ENV_PREFIX}_ESID2560_DLTOTGTR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'EST_CURGTACTL','${DFILP}/${ENV_PREFIX}_ESIX7000_CURGTACTL${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'EST_IADVPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_IADVPERICASE_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'EST_DLREJGTAA','${DFILP}/${ENV_PREFIX}_ESID2900_DLREJGTAA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'EST_DLREJGTAR','${DFILP}/${ENV_PREFIX}_ESID2900_DLREJGTAR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'EST_DLTOTGTAA','${DFILP}/${ENV_PREFIX}_ESID2060_DLTOTGTAA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'EST_DLTOTGTAR','${DFILP}/${ENV_PREFIX}_ESID2560_DLTOTGTAR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'EST_OIADVPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_OIADVPERICASE_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'EST_OIRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_OIRDVPERICASE_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'EST_FTVENTNPHIS','${DFILP}/${ENV_PREFIX}_ESID0060_FTVENTNPHIS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'EST_CRVPERICASE0','${DFILP}/${ENV_PREFIX}_ESID0060_CRVPERICASE0_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'EST_FTECLEDA_MTH','${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDA_MTH_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'EST_FTECLEDA_MVT','${DFILP}/${ENV_PREFIX}_ESPD3970_I4I_MVT_MRG_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'ESL_FCES','${DFILP}/${ENV_PREFIX}_ESID7000_FCES.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'ESL_FPLC','${DFILP}/${ENV_PREFIX}_ESID7000_FPLC.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'ESL_FCLIENT','${DFILP}/${ENV_PREFIX}_ESID7000_FCLIENT.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'ESL_FCPLACC','${DFILP}/${ENV_PREFIX}_ESID7000_FCPLACC.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'ESL_FCTRGRO','${DFILP}/${ENV_PREFIX}_ESID7000_FCTRGRO.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'ESL_FDETTRS','${DFILP}/${ENV_PREFIX}_ESID7000_FDETTRS.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'ESL_FSUBTRS','${DFILP}/${ENV_PREFIX}_ESID7000_FSUBTRS.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'ESL_FTRSLNK','${DFILP}/${ENV_PREFIX}_ESID7000_FTRSLNK.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'ESL_FCURCVSN','${DFILP}/${ENV_PREFIX}_ESID7000_FCURCVSN.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'ESL_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESID7000_FCURQUOT.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'ESL_FSOBBLOB','${DFILP}/${ENV_PREFIX}_ESID7000_FSOBBLOB.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'ESL_FSSDACTR','${DFILP}/${ENV_PREFIX}_ESID7000_FSSDACTR.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'ESL_FCURCVSNI','${DFILP}/${ENV_PREFIX}_ESID7000_FCURCVSNI.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'ESL_FPLACEMT2','${DFILP}/${ENV_PREFIX}_ESID7000_FPLACEMT2.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'ESL_FPLATXCUM','${DFILP}/${ENV_PREFIX}_ESID7000_FPLATXCUM.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'ESL_FTRANSCODE','${DFILP}/${ENV_PREFIX}_ESID7000_FTRANSCODE.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'EST_ARCSTATGTAR','${DFILP}/${ENV_PREFIX}_ESIX7000_ARCSTATGTAR.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'ESL_IADVPERICASE','${DFILP}/${ENV_PREFIX}_ESID7000_IADVPERICASE.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'ESL_OIADVPERICASE','${DFILP}/${ENV_PREFIX}_ESID7000_OIADVPERICASE.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'ESL_OIRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESID7000_OIRDVPERICASE.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'EST_DLTOTGTRC','${DFILP}/${ENV_PREFIX}_ESID7000_DLTOTGTRC_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'EST_DLTOTGTAAC','${DFILP}/${ENV_PREFIX}_ESID7000_DLTOTGTAAC_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'EST_DLTOTGTARC','${DFILP}/${ENV_PREFIX}_ESID7000_DLTOTGTARC_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'ESL_CRVPERICASE0','${DFILP}/${ENV_PREFIX}_ESID7000_CRVPERICASE0${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID7000',  'EST_ANOBALSHEYGT','${DFILP}/${ENV_PREFIX}_ESID7000_ANOBALSHEYGT_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I4IMINVB',  'ESID7000','')
			insert into BEST..TI17REQFNC values ('I4IQINVB',  'ESID7000','')
			insert into BEST..TI17REQFNC values ('I4IYINVB',  'ESID7000','')
go

