-------------------------------
--mapping of  ESLD8700

	----------   Clean tables   ---------------------

	delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESLD8700')
	delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESLD8700')
	delete BEST..TI17FNC where CHAIN_CT='ESLD8700'
	delete BEST..TI17CHN  where CHAIN_CT='ESLD8700'

	insert into BEST..TI17CHN values ('ESLD8700',  '')

	----------IDF_CT:   ESLD8700 ------------------

		insert into BEST..TI17FNC values ('ESLD8700',' ','ESLD8700',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('ESLD8700',  'ESL_FTECLEDALO','${DFILP}/${ENV_PREFIX}_ESLD3800_FTECLEDA_I4I_LOC.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESLD8700',  'ESL_EPOSOCLO_CUR','${DFILP}/${ENV_PREFIX}_ESLJ0090_EPOSOCLO_CUR_LOC.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESLD8700',  'ESL_DLREJGTRLO_CUR','${DFILP}/${ENV_PREFIX}_ESLD1900_DLREJGTRLO_CUR_LOC.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESLD8700',  'ESL_DLREJGTAALO_CUR','${DFILP}/${ENV_PREFIX}_ESLD1900_DLREJGTAALO_CUR_LOC.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESLD8700',  'ESL_DLREJGTARLO_CUR','${DFILP}/${ENV_PREFIX}_ESLD1900_DLREJGTARLO_CUR_LOC.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESLD8700',  'ESL_EPOSOCLO_CURNEW','${DFILP}/${ENV_PREFIX}_ESLJ0090_EPOSOCLO_CURNEW_LOC.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESLD8700',  'ESL_FTECLEDALO_MTH','${DFILP}/${ENV_PREFIX}_ESLD3800_FTECLEDA_MTH_I4I_LOC.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESLD8700',  'ESL_FTECLEDALO_MVT','${DFILP}/${ENV_PREFIX}_ESPD3970_FTECLEDA_MVT_I4I_LOC.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESLD8700',  'ESL_DLREJGTRLO_CURNEW','${DFILP}/${ENV_PREFIX}_ESLD1900_DLREJGTRLO_CURNEW_LOC.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESLD8700',  'ESL_DLREJGTAALO_CURNEW','${DFILP}/${ENV_PREFIX}_ESLD1900_DLREJGTAALO_CURNEW_LOC.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESLD8700',  'ESL_DLREJGTARLO_CURNEW','${DFILP}/${ENV_PREFIX}_ESLD1900_DLREJGTARLO_CURNEW_LOC.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESLD8700',  'EST_FTECLEDR','${DFILP}/${ENV_PREFIX}_ESLD3800_FTECLEDR_I4I_LOC.dat','I','')
			
			--- output files by site
			insert into BEST..TI17PERMFIL values ('ESLD8700',  'ESF_FTECLEDR_TOAS',    '${ENV_PREFIX}_ESLD8700_FTECLEDR_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOAS}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESLD8700',  'ESF_FTECLEDR_TOEU',    '${ENV_PREFIX}_ESLD8700_FTECLEDR_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOEU}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESLD8700',  'ESF_FTECLEDR_TOAM',    '${ENV_PREFIX}_ESLD8700_FTECLEDR_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOAM}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESLD8700',  'ESF_FTECLEDA_TOAS',    '${ENV_PREFIX}_ESLD8700_FTECLEDA_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOAS}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESLD8700',  'ESF_FTECLEDA_TOEU',    '${ENV_PREFIX}_ESLD8700_FTECLEDA_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOEU}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESLD8700',  'ESF_FTECLEDA_TOAM',    '${ENV_PREFIX}_ESLD8700_FTECLEDA_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOAM}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESLD8700',  'ESF_FTECLEDR_LOCAL',    '$DFILP/${ENV_PREFIX}_ESLD8700_FTECLEDR_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESLD8700',  'ESF_FTECLEDA_LOCAL',    '$DFILP/${ENV_PREFIX}_ESLD8700_FTECLEDA_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','O','')

			--- input files by site
			insert into BEST..TI17PERMFIL values ('ESLD8700',  'ESF_FTECLEDR_FROMAS',    '${DFILP}/${ENV_PREFIX}_ESLD8700_FTECLEDR_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_ASTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESLD8700',  'ESF_FTECLEDR_FROMEU',    '${DFILP}/${ENV_PREFIX}_ESLD8700_FTECLEDR_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_EUTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESLD8700',  'ESF_FTECLEDR_FROMAM',    '${DFILP}/${ENV_PREFIX}_ESLD8700_FTECLEDR_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_AMTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESLD8700',  'ESF_FTECLEDA_FROMAS',    '${DFILP}/${ENV_PREFIX}_ESLD8700_FTECLEDA_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_ASTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESLD8700',  'ESF_FTECLEDA_FROMEU',    '${DFILP}/${ENV_PREFIX}_ESLD8700_FTECLEDA_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_EUTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESLD8700',  'ESF_FTECLEDA_FROMAM',    '${DFILP}/${ENV_PREFIX}_ESLD8700_FTECLEDA_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_AMTOLOCAL}.dat','I','')
            --- input product gaap code 
			insert into BEST..TI17PERMFIL values ('ESLD8700',  'ESF_FCTRI17PRD_FROMAS','${DFILP}/${ENV_PREFIX}_ESFD0040_FCTRI17PRD_${PARAM_ASTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESLD8700',  'EPO_GAAPCOD_MAPPING_FROMAS','${DFILP}/${ENV_PREFIX}_ESCJ0060_GAAPCOD_MAPPING_${PARAM_ASTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESLD8700',  'ESF_FCTRI17PRD_FROMEU','${DFILP}/${ENV_PREFIX}_ESFD0040_FCTRI17PRD_${PARAM_EUTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESLD8700',  'EPO_GAAPCOD_MAPPING_FROMEU','${DFILP}/${ENV_PREFIX}_ESCJ0060_GAAPCOD_MAPPING_${PARAM_EUTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESLD8700',  'ESF_FCTRI17PRD_FROMAM','${DFILP}/${ENV_PREFIX}_ESFD0040_FCTRI17PRD_${PARAM_AMTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESLD8700',  'EPO_GAAPCOD_MAPPING_FROMAM','${DFILP}/${ENV_PREFIX}_ESCJ0060_GAAPCOD_MAPPING_${PARAM_AMTOLOCAL}.dat','I','')		
			
			
		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('Y',  'ESLD8700','')
go

