-------------------------------
--mapping of  ESFD5060

	----------   Clean tables   ---------------------

	delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD5060')
	delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD5060')
	delete BEST..TI17FNC where CHAIN_CT='ESFD5060'
	delete BEST..TI17CHN  where CHAIN_CT='ESFD5060'

	insert into BEST..TI17CHN values ('ESFD5060',  'Daily extract')

	----------IDF_CT:   EBS_ESFD5060 ------------------

		insert into BEST..TI17FNC values ('EBS_ESFD5060','Daily extract','ESFD5060',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('EBS_ESFD5060',  'ESF_EPOSOCI','${DFILP}/${ENV_PREFIX}_ESPD0060_EPO_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','U','')
			
			insert into BEST..TI17PERMFIL values ('EBS_ESFD5060',  'EST_IADVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5010_IADVPERICASE_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')	
			
			insert into BEST..TI17PERMFIL values ('EBS_ESFD5060',  'ESF_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK_TXT.dat','I','')	
			insert into BEST..TI17PERMFIL values ('EBS_ESFD5060',  'EPO_OIADVPERICASE','${DFILP}/${ENV_PREFIX}_ESCJ0660_OIADVPERICASE.dat','I','')	



			insert into BEST..TI17PERMFIL values ('EBS_ESFD5060',  'ESF_EPOSOCI_BBNI','${DFILP}/${ENV_PREFIX}_ESFD5060_EPO_BBNI_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD5060',  'ESF_IADPERIFCI_BBNI','${DFILP}/${ENV_PREFIX}_ESFD5060_IADPERIFCI_BBNI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD5060',  'ESF_IADPERIFCT_BBNI','${DFILP}/${ENV_PREFIX}_ESFD5060_IADPERIFCT_BBNI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
 			insert into BEST..TI17PERMFIL values ('EBS_ESFD5060',  'ESF_IADPERIFR_BBNI','${DFILP}/${ENV_PREFIX}_ESFD5060_IADPERIFR_BBNI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','') 
			insert into BEST..TI17PERMFIL values ('EBS_ESFD5060',  'ESF_IADPERIFCT0_BBNI','${DFILP}/${ENV_PREFIX}_ESFD5060_IADPERIFCT0_BBNI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD5060',  'ESF_IADPERICASE_BBNI','${DFILP}/${ENV_PREFIX}_ESFD5060_IADPERICASE_BBNI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')	
			insert into BEST..TI17PERMFIL values ('EBS_ESFD5060',  'ESF_IRDPERICASE_BBNI','${DFILP}/${ENV_PREFIX}_ESFD5060_IRDPERICASE_BBNI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')	
			insert into BEST..TI17PERMFIL values ('EBS_ESFD5060',  'ESF_IADPERICASE_MRG','${DFILP}/${ENV_PREFIX}_ESFD5060_IADPERICASE_MRG_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')	

			insert into BEST..TI17PERMFIL values ('EBS_ESFD5060',  'ESF_IADPERIFACACCEPT_BBNI','${DFILP}/${ENV_PREFIX}_ESFD5060_IADPERIFACACCEPT_BBNI_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD5060',  'ESF_OIADVPERICASE_MRG','${DFILP}/${ENV_PREFIX}_ESFD5060_ESCJ0660_OIADVPERICASE.dat','O','')			

			insert into BEST..TI17PERMFIL values ('EBS_ESFD5060',  'ESF_EPOSOCI_INI','${DFILP}/${ENV_PREFIX}_ESFD5060_EPO_INI_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD5060',  'ESF_IADPERIFCI_INI','${DFILP}/${ENV_PREFIX}_ESFD5060_IADPERIFCI_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD5060',  'ESF_IADPERIFCT_INI','${DFILP}/${ENV_PREFIX}_ESFD5060_IADPERIFCT_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
 			insert into BEST..TI17PERMFIL values ('EBS_ESFD5060',  'ESF_IADPERIFR_INI','${DFILP}/${ENV_PREFIX}_ESFD5060_IADPERIFR_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','') 
			insert into BEST..TI17PERMFIL values ('EBS_ESFD5060',  'ESF_IADPERIFCT0_INI','${DFILP}/${ENV_PREFIX}_ESFD5060_IADPERIFCT0_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD5060',  'ESF_IADPERICASE_INI','${DFILP}/${ENV_PREFIX}_ESFD5060_IADPERICASE_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')	
			insert into BEST..TI17PERMFIL values ('EBS_ESFD5060',  'ESF_IRDPERICASE_INI','${DFILP}/${ENV_PREFIX}_ESFD5060_IRDPERICASE_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')	
			insert into BEST..TI17PERMFIL values ('EBS_ESFD5060',  'ESF_IADPERICASE_MRG_INI','${DFILP}/${ENV_PREFIX}_ESFD5060_IADPERICASE_MRG_INI_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')					
            insert into BEST..TI17PERMFIL values ('EBS_ESFD5060',  'ESF_IADPERIFACACCEPT_INI','${DFILP}/${ENV_PREFIX}_ESFD5060_IADPERIFACACCEPT_INI_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD5060',  'ESF_OIADVPERICASE_MRG_INI','${DFILP}/${ENV_PREFIX}_ESFD5060_ESCJ0660_OIADVPERICASE_INI.dat','O','')			
			insert into BEST..TI17PERMFIL values ('EBS_ESFD5060',  'ESF_FLORETFACTOR_INI','${DFILP}/${ENV_PREFIX}_ESFD5060_EBS_INI_FLORETFACTOR_INI_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','O','')		


		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('EBSEYPOC',  'EBS_ESFD5060','')
			insert into BEST..TI17REQFNC values ('EBSEQPOC',  'EBS_ESFD5060','')
			insert into BEST..TI17REQFNC values ('EBSEMINV',  'EBS_ESFD5060','')
			insert into BEST..TI17REQFNC values ('EBSEMINVB',  'EBS_ESFD5060','')
			insert into BEST..TI17REQFNC values ('EBSEQINV',  'EBS_ESFD5060','')
			insert into BEST..TI17REQFNC values ('EBSEQPOCB',  'EBS_ESFD5060','')
			insert into BEST..TI17REQFNC values ('EBSEQPOS',  'EBS_ESFD5060','')
			insert into BEST..TI17REQFNC values ('EBSEYINV',  'EBS_ESFD5060','')
			insert into BEST..TI17REQFNC values ('EBSEYPOCB',  'EBS_ESFD5060','')
			insert into BEST..TI17REQFNC values ('EBSEYPOS',  'EBS_ESFD5060','')


go

