-------------------------------
--mapping of  ESFD2230 

	----------   Clean tables   ---------------------

	delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD2230')
	delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD2230')
	delete BEST..TI17FNC where CHAIN_CT='ESFD2230'
	delete BEST..TI17CHN  where CHAIN_CT='ESFD2230'

	insert into BEST..TI17CHN values ('ESFD2230',  'Future at inception')

	----------IDF_CT:   EBS_ESFD2230 ------------------

		insert into BEST..TI17FNC values ('EBS_ESFD2230','IFRS4 Post omega  EBS','ESFD2230',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230',  'EST_FCLIENT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCLIENT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230',  'EST_FCPLACC','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCPLACC.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230',  'EST_FDETTRS','${DFILP}/${ENV_PREFIX}_ESCJ0660_FDETTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230',  'EST_FTRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230',  'EPO_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230',  'EST_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230',  'EPO_FBOPRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230',  'EST_FTHRHLDUWY','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTHRHLDUWY.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230',  'EST_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230',  'EST_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230',  'ESF_FTECLEDA_REJ','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDA_REJ_EBS.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230',  'EST_DLGTAAPA','${DFILP}/${ENV_PREFIX}_ESID2000_DLGTAAPA_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230',  'EST_DLCUMGTAA','${DFILP}/${ENV_PREFIX}_ESID2000_DLCUMGTAA_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230',  'EST_DLDGTAA','${DFILP}/${ENV_PREFIX}_ESID2210_DLDGTAA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230',  'EST_DLA_DSI_GTAA','${DFILP}/${ENV_PREFIX}_DLA_DSI_GTAA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230',  'ESF_DLSGTAA','${DFILP}/${ENV_PREFIX}_ESPD1800_DLSGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230',  'EST_DLDGTAA_PREC','${DFILP}/${ENV_PREFIX}_ESID2210_DLDGTAA_PREC_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230',  'EST_FCTRGRO','${DFILP}/${ENV_PREFIX}_ESFD5010_FCTRGRO_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230',  'EST_DLCUMGTAATOT','${DFILP}/${ENV_PREFIX}_ESID2210_DLCUMGTAATOT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230',  'EST_IADPERIFR','${DFILP}/${ENV_PREFIX}_ESFD5010_IADPERIFR_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230',  'EST_DLDGTAA_CUMULS_COUR','${DFILP}/${ENV_PREFIX}_ESID2210_DLDGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230',  'EST_DLDGTAA_UPR_DAC','${DFILP}/${ENV_PREFIX}_ESID2210_DLDGTAA_UPR_DAC_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230',  'EST_IADPERIFCI','${DFILP}/${ENV_PREFIX}_ESFD5010_IADPERIFCI_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230',  'EST_IADPERIFCT','${DFILP}/${ENV_PREFIX}_ESFD5010_IADPERIFCT_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230',  'EST_CTRESTLOSPBPAP','${DFILP}/${ENV_PREFIX}_ESID2210_CTRESTLOSPBPAP_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230',  'EST_FSTAT','${DFILP}/${ENV_PREFIX}_ESFD2200_I17G_FUT_ALL_INI_FSTAT_INI_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230',  'EST_FSEGEST_SOLVENCY','${DFILP}/${ENV_PREFIX}_ESPD0060_FSEGEST_SOLVENCY_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230',  'EST_IADPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5040_IADPERICASE_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230',  'ESF_IADPERICASE_FAC_ACCEPTED','${DFILP}/${ENV_PREFIX}_ESFD5030_IADPERICASE_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')			
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230',  'EPO_FTECLEDACO','`if [ "${TYPEINV}" = "POC" ];then echo ${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_I4I_POC_${PARM_ICLODAT_D}.dat;else echo ${DFILP}/empty.dat;fi;`','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230',  'EPO_FTECLEDASIISO','`if [ "${TYPEINV}" = "POC" ];then echo ${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_EBS_POS_${PARM_ICLODAT_D}.dat;else echo ${DFILP}/empty.dat;fi;`','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230',  'ESF_IADPERICASE_DELTA_POS','`if [ "${TYPEINV}" = "INV" ] || [ "${PARM_SEQ_MODE}" = "1" ] ;then echo ${DFILP}/empty.dat;else echo ${DFILI}/${ENV_PREFIX}_ESCJ0660_IADPERICASE_DELTA_POS.dat;fi;`','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230',  'EST_FUTURE_EBS','${DFILP}/${ENV_PREFIX}_ESFD2220_FUTURE_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230',  'EST_DLGTAUPUC','${DFILP}/${ENV_PREFIX}_ESFD2220_DLGTAUPUC_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230',  'EST_NDIC_FLOARAT','${DFILP}/${ENV_PREFIX}_ESFD2220_NDIC_FLOARAT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230',  'EST_DLDGTAA_E_TRNCODEBS','${DFILP}/${ENV_PREFIX}_ESFD2230_DLDGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230',  'ESF_FUTURE_FLOARAT','${DFILP}/${ENV_PREFIX}_ESFD2220_FUTURE_FLOARAT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230',  'EST_DLDGTAA_E_TRNCODINI','${DFILP}/${ENV_PREFIX}_ESFD2230_I17G_FUT_ALL_INI_DLDGTAA_INI_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('EBSEMINV',  'EBS_ESFD2230','')
			insert into BEST..TI17REQFNC values ('EBSEQINV',  'EBS_ESFD2230','')
			insert into BEST..TI17REQFNC values ('EBSEQPOC',  'EBS_ESFD2230','')
			insert into BEST..TI17REQFNC values ('EBSEQPOS',  'EBS_ESFD2230','')
			insert into BEST..TI17REQFNC values ('EBSEYINV',  'EBS_ESFD2230','')
			insert into BEST..TI17REQFNC values ('EBSEYPOC',  'EBS_ESFD2230','')
			insert into BEST..TI17REQFNC values ('EBSEYPOS',  'EBS_ESFD2230','')
			insert into BEST..TI17REQFNC values ('EBSEQPOCB',  'EBS_ESFD2230','')
			insert into BEST..TI17REQFNC values ('EBSEYPOCB',  'EBS_ESFD2230','')
			
			
		----------IDF_CT:   EBS_ESFD2230_BBNI ------------------

		insert into BEST..TI17FNC values ('EBS_ESFD2230_BBNI','IFRS4 Post omega  EBS','ESFD2230',0)
					

		----------  Perms---------------------
		

			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_BBNI',  'EST_FCLIENT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCLIENT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_BBNI',  'EST_FCPLACC','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCPLACC.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_BBNI',  'EST_FDETTRS','${DFILP}/${ENV_PREFIX}_ESCJ0660_FDETTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_BBNI',  'EST_FTRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_BBNI',  'EPO_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_BBNI',  'EST_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_BBNI',  'EPO_FBOPRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_BBNI',  'EST_FTHRHLDUWY','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTHRHLDUWY.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_BBNI',  'EST_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_BBNI',  'EST_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_BBNI',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_BBNI',  'ESF_FTECLEDA_REJ','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDA_REJ_EBS.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_BBNI',  'EST_DLGTAAPA','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_BBNI',  'EST_DLCUMGTAA','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_BBNI',  'EST_DLDGTAA','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_BBNI',  'EST_DLA_DSI_GTAA','${DFILP}/${ENV_PREFIX}_DLA_DSI_GTAA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_BBNI',  'ESF_DLSGTAA','${DFILP}/${ENV_PREFIX}_ESPD1800_BBNI_DLSGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_BBNI',  'EST_DLDGTAA_PREC','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_BBNI',  'EST_FCTRGRO','${DFILP}/${ENV_PREFIX}_ESFD5010_FCTRGRO_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_BBNI',  'EST_DLCUMGTAATOT','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_BBNI',  'EST_IADPERIFR','${DFILP}/${ENV_PREFIX}_ESFD5060_IADPERIFR_BBNI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_BBNI',  'EST_DLDGTAA_CUMULS_COUR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_BBNI',  'EST_DLDGTAA_UPR_DAC','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_BBNI',  'EST_IADPERIFCI','${DFILP}/${ENV_PREFIX}_ESFD5060_IADPERIFCI_BBNI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_BBNI',  'EST_IADPERIFCT','${DFILP}/${ENV_PREFIX}_ESFD5060_IADPERIFCT_BBNI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_BBNI',  'EST_CTRESTLOSPBPAP','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_BBNI',  'EST_FSTAT','${DFILP}/${ENV_PREFIX}_ESFD2200_I17G_FUT_ALL_INI_FSTAT_INI_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_BBNI',  'EST_FSEGEST_SOLVENCY','${DFILP}/${ENV_PREFIX}_ESPD0060_FSEGEST_SOLVENCY_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_BBNI',  'EST_IADPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5060_IADPERICASE_BBNI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_BBNI',  'ESF_IADPERICASE_FAC_ACCEPTED','${DFILP}/${ENV_PREFIX}_ESFD5060_IADPERIFACACCEPT_BBNI_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')  ---,'${DFILP}/${ENV_PREFIX}_ESFD5030_IADPERICASE_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')			
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_BBNI',  'EPO_FTECLEDACO','`if [ "${TYPEINV}" = "POC" ];then echo ${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_I4I_POC_${PARM_ICLODAT_D}.dat;else echo ${DFILP}/empty.dat;fi;`','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_BBNI',  'EPO_FTECLEDASIISO','`if [ "${TYPEINV}" = "POC" ];then echo ${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_EBS_POS_${PARM_ICLODAT_D}.dat;else echo ${DFILP}/empty.dat;fi;`','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_BBNI',  'ESF_IADPERICASE_DELTA_POS','${DFILP}/empty.dat','I','')   -- '`if [ "${TYPEINV}" = "INV" ] || [ "${PARM_SEQ_MODE}" = "1" ] ;then echo ${DFILP}/empty.dat;else echo ${DFILI}/${ENV_PREFIX}_ESCJ0660_IADPERICASE_DELTA_POS.dat;fi;`','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_BBNI',  'EST_FUTURE_EBS','${DFILP}/${ENV_PREFIX}_ESFD2230_BBNI_FUTURE_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_BBNI',  'EST_DLGTAUPUC','${DFILP}/${ENV_PREFIX}_ESFD2230_BBNI_DLGTAUPUC_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_BBNI',  'EST_NDIC_FLOARAT','${DFILP}/${ENV_PREFIX}_ESFD2230_BBNI_NDIC_FLOARAT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_BBNI',  'EST_DLDGTAA_E_TRNCODEBS','${DFILP}/${ENV_PREFIX}_ESFD2230_BBNI_DLDGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_BBNI',  'ESF_FUTURE_FLOARAT','${DFILP}/${ENV_PREFIX}_ESFD2230_BBNI_FUTURE_FLOARAT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_BBNI',  'EST_DLDGTAA_E_TRNCODINI','${DFILP}/${ENV_PREFIX}_ESFD2230_BBNI_DLDGTAA_INI_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('EBSEMINV',  'EBS_ESFD2230_BBNI','')
			insert into BEST..TI17REQFNC values ('EBSEQINV',  'EBS_ESFD2230_BBNI','')
			insert into BEST..TI17REQFNC values ('EBSEQPOC',  'EBS_ESFD2230_BBNI','')
			insert into BEST..TI17REQFNC values ('EBSEQPOS',  'EBS_ESFD2230_BBNI','')
			insert into BEST..TI17REQFNC values ('EBSEYINV',  'EBS_ESFD2230_BBNI','')
			insert into BEST..TI17REQFNC values ('EBSEYPOC',  'EBS_ESFD2230_BBNI','')
			insert into BEST..TI17REQFNC values ('EBSEYPOS',  'EBS_ESFD2230_BBNI','')
			insert into BEST..TI17REQFNC values ('EBSEQPOCB',  'EBS_ESFD2230_BBNI','')
			insert into BEST..TI17REQFNC values ('EBSEYPOCB',  'EBS_ESFD2230_BBNI','')		

		----------IDF_CT:   EBS_ESFD2230_INI ------------------

		insert into BEST..TI17FNC values ('EBS_ESFD2230_INI','IFRS4 Post omega  EBS','ESFD2230',0)
					

		----------  Perms---------------------
		

			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_INI',  'EST_FCLIENT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCLIENT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_INI',  'EST_FCPLACC','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCPLACC.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_INI',  'EST_FDETTRS','${DFILP}/${ENV_PREFIX}_ESCJ0660_FDETTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_INI',  'EST_FTRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_INI',  'EPO_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_INI',  'EST_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_INI',  'EPO_FBOPRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_INI',  'EST_FTHRHLDUWY','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTHRHLDUWY.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_INI',  'EST_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_INI',  'EST_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_INI',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_INI',  'ESF_FTECLEDA_REJ','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDA_REJ_EBS.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_INI',  'EST_DLGTAAPA','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_INI',  'EST_DLCUMGTAA','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_INI',  'EST_DLDGTAA','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_INI',  'EST_DLA_DSI_GTAA','${DFILP}/${ENV_PREFIX}_DLA_DSI_GTAA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_INI',  'ESF_DLSGTAA','${DFILP}/${ENV_PREFIX}_ESPD1800_INI_DLSGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_INI',  'EST_DLDGTAA_PREC','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_INI',  'EST_FCTRGRO','${DFILP}/${ENV_PREFIX}_ESFD5010_FCTRGRO_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_INI',  'EST_DLCUMGTAATOT','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_INI',  'EST_IADPERIFR','${DFILP}/${ENV_PREFIX}_ESFD5060_IADPERIFR_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_INI',  'EST_DLDGTAA_CUMULS_COUR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_INI',  'EST_DLDGTAA_UPR_DAC','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_INI',  'EST_IADPERIFCI','${DFILP}/${ENV_PREFIX}_ESFD5060_IADPERIFCI_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_INI',  'EST_IADPERIFCT','${DFILP}/${ENV_PREFIX}_ESFD5060_IADPERIFCT_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_INI',  'EST_CTRESTLOSPBPAP','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_INI',  'EST_FSTAT','${DFILP}/${ENV_PREFIX}_ESFD2200_I17G_FUT_ALL_INI_FSTAT_INI_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_INI',  'EST_FSEGEST_SOLVENCY','${DFILP}/${ENV_PREFIX}_ESPD0060_FSEGEST_SOLVENCY_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_INI',  'EST_IADPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5060_IADPERICASE_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_INI',  'ESF_IADPERICASE_FAC_ACCEPTED','${DFILP}/${ENV_PREFIX}_ESFD5060_IADPERIFACACCEPT_INI_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')  ---,'${DFILP}/${ENV_PREFIX}_ESFD5030_IADPERICASE_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')			
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_INI',  'EPO_FTECLEDACO','`if [ "${TYPEINV}" = "POC" ];then echo ${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_I4I_POC_${PARM_ICLODAT_D}.dat;else echo ${DFILP}/empty.dat;fi;`','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_INI',  'EPO_FTECLEDASIISO','`if [ "${TYPEINV}" = "POC" ];then echo ${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_EBS_POS_${PARM_ICLODAT_D}.dat;else echo ${DFILP}/empty.dat;fi;`','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_INI',  'ESF_IADPERICASE_DELTA_POS','${DFILP}/empty.dat','I','')   -- '`if [ "${TYPEINV}" = "INV" ] || [ "${PARM_SEQ_MODE}" = "1" ] ;then echo ${DFILP}/empty.dat;else echo ${DFILI}/${ENV_PREFIX}_ESCJ0660_IADPERICASE_DELTA_POS.dat;fi;`','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_INI',  'EST_FUTURE_EBS','${DFILP}/${ENV_PREFIX}_ESFD2230_INI_FUTURE_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_INI',  'EST_DLGTAUPUC','${DFILP}/${ENV_PREFIX}_ESFD2230_INI_DLGTAUPUC_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_INI',  'EST_NDIC_FLOARAT','${DFILP}/${ENV_PREFIX}_ESFD2230_INI_NDIC_FLOARAT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_INI',  'EST_DLDGTAA_E_TRNCODEBS','${DFILP}/${ENV_PREFIX}_ESFD2230_INI_DLDGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_INI',  'ESF_FUTURE_FLOARAT','${DFILP}/${ENV_PREFIX}_ESFD2230_INI_FUTURE_FLOARAT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD2230_INI',  'EST_DLDGTAA_E_TRNCODINI','${DFILP}/${ENV_PREFIX}_ESFD2230_INI_DLDGTAA_INI_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------


			insert into BEST..TI17REQFNC values ('EBSEMINV',  'EBS_ESFD2230_INI','')
			insert into BEST..TI17REQFNC values ('EBSEQINV',  'EBS_ESFD2230_INI','')
			insert into BEST..TI17REQFNC values ('EBSEQPOC',  'EBS_ESFD2230_INI','')
			insert into BEST..TI17REQFNC values ('EBSEQPOS',  'EBS_ESFD2230_INI','')
			insert into BEST..TI17REQFNC values ('EBSEYINV',  'EBS_ESFD2230_INI','')
			insert into BEST..TI17REQFNC values ('EBSEYPOC',  'EBS_ESFD2230_INI','')
			insert into BEST..TI17REQFNC values ('EBSEYPOS',  'EBS_ESFD2230_INI','')
			insert into BEST..TI17REQFNC values ('EBSEQPOCB',  'EBS_ESFD2230_INI','')
			insert into BEST..TI17REQFNC values ('EBSEYPOCB',  'EBS_ESFD2230_INI','')		

	----------IDF_CT:   I17G_ESFD2230___AA0 ------------------

		insert into BEST..TI17FNC values ('I17G_ESFD2230___AA0','Micro AOC Future Assumed AA0','ESFD2230',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA0',  'EST_FCLIENT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCLIENT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA0',  'EST_FCPLACC','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCPLACC.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA0',  'EST_FDETTRS','${DFILP}/${ENV_PREFIX}_ESCJ0660_FDETTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA0',  'EST_FTRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA0',  'EPO_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA0',  'EST_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA0',  'EPO_FBOPRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA0',  'EST_FTHRHLDUWY','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTHRHLDUWY.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA0',  'EST_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA0',  'EST_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA0',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA0',  'ESF_FTECLEDA_REJ','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDA_REJ_EBS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA0',  'EST_DLGTAAPA','${DFILP}/${ENV_PREFIX}_ESID2000_DLGTAAPA_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA0',  'EST_DLCUMGTAA','${DFILP}/${ENV_PREFIX}_ESID2000_DLCUMGTAA_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA0',  'EST_DLA_DSI_GTAA','${DFILP}/${ENV_PREFIX}_DLA_DSI_GTAA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA0',  'ESF_DLSGTAA','${DFILP}/${ENV_PREFIX}_ESPD1800_DLSGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA0',  'EST_FCTRGRO','${DFILP}/${ENV_PREFIX}_ESFD5010_FCTRGRO_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA0',  'EST_IADPERIFR','${DFILP}/${ENV_PREFIX}_ESFD5010_IADPERIFR_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA0',  'EST_IADPERIFCI','${DFILP}/${ENV_PREFIX}_ESFD5010_IADPERIFCI_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA0',  'EST_IADPERIFCT','${DFILP}/${ENV_PREFIX}_ESFD5010_IADPERIFCT_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA0',  'EST_DLDGTAA','${DFILP}/${ENV_PREFIX}_ESID2210_I17G_ESID2210___AA0_DLDGTAA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA0',  'EST_FSTAT','${DFILP}/${ENV_PREFIX}_ESFD2200_I17G_FUT_ALL_INI_FSTAT_INI_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA0',  'EST_FSEGEST_SOLVENCY','${DFILP}/${ENV_PREFIX}_ESPD0060_FSEGEST_SOLVENCY_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA0',  'EST_IADPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5040_IADPERICASE_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA0',  'EST_DLDGTAA_PREC','${DFILP}/${ENV_PREFIX}_ESID2210_I17G_ESID2210___AA0_DLDGTAA_PREC_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA0',  'EST_DLCUMGTAATOT','${DFILP}/${ENV_PREFIX}_ESID2210_I17G_ESID2210___AA0_DLCUMGTAATOT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA0',  'EST_DLDGTAA_CUMULS_COUR','${DFILP}/${ENV_PREFIX}_ESID2210_I17G_ESID2210___AA0_DLDGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA0',  'EST_DLDGTAA_UPR_DAC','${DFILP}/${ENV_PREFIX}_ESID2210_I17G_ESID2210___AA0_DLDGTAA_UPR_DAC_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA0',  'EST_CTRESTLOSPBPAP','${DFILP}/${ENV_PREFIX}_ESID2210_I17G_ESID2210___AA0_CTRESTLOSPBPAP_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA0',  'EPO_FTECLEDACO','`if [ "${TYPEINV}" = "POC" ];then echo ${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_I4I_POC_${PARM_ICLODAT_D}.dat;else echo ${DFILP}/empty.dat;fi;`','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA0',  'EPO_FTECLEDASIISO','`if [ "${TYPEINV}" = "POC" ];then echo ${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_EBS_POS_${PARM_ICLODAT_D}.dat;else echo ${DFILP}/empty.dat;fi;`','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA0',  'ESF_IADPERICASE_DELTA_POS','`if [ "${TYPEINV}" = "INV" ] || [ "${PARM_SEQ_MODE}" = "1" ] ;then echo ${DFILP}/empty.dat;else echo ${DFILI}/${ENV_PREFIX}_ESCJ0660_IADPERICASE_DELTA_POS.dat;fi;`','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA0',  'EST_FUTURE_EBS','${DFILP}/${ENV_PREFIX}_ESFD2230_I17G_ESFD2230___AA0_FUTURE_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA0',  'EST_DLGTAUPUC','${DFILP}/${ENV_PREFIX}_ESFD2230_I17G_ESFD2230___AA0_DLGTAUPUC_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA0',  'EST_NDIC_FLOARAT','${DFILP}/${ENV_PREFIX}_ESFD2230_I17G_ESFD2230___AA0_NDIC_FLOARAT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA0',  'EST_DLDGTAA_E_TRNCODEBS','${DFILP}/${ENV_PREFIX}_ESFD2230_I17G_ESFD2230___AA0_DLDGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA0',  'ESF_FUTURE_FLOARAT','${DFILP}/${ENV_PREFIX}_ESFD2230_I17G_ESFD2230___AA0_FUTURE_FLOARAT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA0',  'EST_DLDGTAA_E_TRNCODINI','${DFILP}/${ENV_PREFIX}_ESFD2230_I17G_ESFD2230___AA0_I17G_FUT_ALL_INI_DLDGTAA_INI_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('POCO',  'I17G_ESFD2230___AA0','POCO')
			insert into BEST..TI17REQFNC values ('POSO',  'I17G_ESFD2230___AA0','POSO')
			insert into BEST..TI17REQFNC values ('INVO',  'I17G_ESFD2230___AA0','INVO')

	----------IDF_CT:   I17G_ESFD2230___AA1 ------------------

		insert into BEST..TI17FNC values ('I17G_ESFD2230___AA1','Micro AOC Future Assumed AA1','ESFD2230',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA1',  'EST_FCLIENT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCLIENT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA1',  'EST_FCPLACC','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCPLACC.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA1',  'EST_FDETTRS','${DFILP}/${ENV_PREFIX}_ESCJ0660_FDETTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA1',  'EST_FTRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA1',  'EPO_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA1',  'EST_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA1',  'EPO_FBOPRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA1',  'EST_FTHRHLDUWY','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTHRHLDUWY.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA1',  'EST_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA1',  'EST_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA1',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA1',  'ESF_FTECLEDA_REJ','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDA_REJ_EBS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA1',  'EST_DLGTAAPA','${DFILP}/${ENV_PREFIX}_ESID2000_DLGTAAPA_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA1',  'EST_DLCUMGTAA','${DFILP}/${ENV_PREFIX}_ESID2000_DLCUMGTAA_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA1',  'EST_DLA_DSI_GTAA','${DFILP}/${ENV_PREFIX}_DLA_DSI_GTAA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA1',  'ESF_DLSGTAA','${DFILP}/${ENV_PREFIX}_ESPD1800_DLSGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA1',  'EST_FCTRGRO','${DFILP}/${ENV_PREFIX}_ESFD5010_FCTRGRO_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA1',  'EST_IADPERIFR','${DFILP}/${ENV_PREFIX}_ESFD5010_IADPERIFR_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA1',  'EST_IADPERIFCI','${DFILP}/${ENV_PREFIX}_ESFD5010_IADPERIFCI_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA1',  'EST_IADPERIFCT','${DFILP}/${ENV_PREFIX}_ESFD5010_IADPERIFCT_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA1',  'EST_DLDGTAA','${DFILP}/${ENV_PREFIX}_ESID2210_I17G_ESID2210___AA1_DLDGTAA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA1',  'EST_FSTAT','${DFILP}/${ENV_PREFIX}_ESFD2200_I17G_FUT_ALL_INI_FSTAT_INI_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA1',  'EST_FSEGEST_SOLVENCY','${DFILP}/${ENV_PREFIX}_ESPD0060_FSEGEST_SOLVENCY_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA1',  'EST_IADPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5040_IADPERICASE_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA1',  'EST_DLDGTAA_PREC','${DFILP}/${ENV_PREFIX}_ESID2210_I17G_ESID2210___AA1_DLDGTAA_PREC_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA1',  'EST_DLCUMGTAATOT','${DFILP}/${ENV_PREFIX}_ESID2210_I17G_ESID2210___AA1_DLCUMGTAATOT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA1',  'EST_DLDGTAA_CUMULS_COUR','${DFILP}/${ENV_PREFIX}_ESID2210_I17G_ESID2210___AA1_DLDGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA1',  'EST_DLDGTAA_UPR_DAC','${DFILP}/${ENV_PREFIX}_ESID2210_I17G_ESID2210___AA1_DLDGTAA_UPR_DAC_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA1',  'EST_CTRESTLOSPBPAP','${DFILP}/${ENV_PREFIX}_ESID2210_I17G_ESID2210___AA1_CTRESTLOSPBPAP_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA1',  'EPO_FTECLEDACO','`if [ "${TYPEINV}" = "POC" ];then echo ${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_I4I_POC_${PARM_ICLODAT_D}.dat;else echo ${DFILP}/empty.dat;fi;`','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA1',  'EPO_FTECLEDASIISO','`if [ "${TYPEINV}" = "POC" ];then echo ${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_EBS_POS_${PARM_ICLODAT_D}.dat;else echo ${DFILP}/empty.dat;fi;`','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA1',  'ESF_IADPERICASE_DELTA_POS','`if [ "${TYPEINV}" = "INV" ] || [ "${PARM_SEQ_MODE}" = "1" ] ;then echo ${DFILP}/empty.dat;else echo ${DFILI}/${ENV_PREFIX}_ESCJ0660_IADPERICASE_DELTA_POS.dat;fi;`','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA1',  'EST_FUTURE_EBS','${DFILP}/${ENV_PREFIX}_ESFD2230_I17G_ESFD2230___AA1_FUTURE_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA1',  'EST_DLGTAUPUC','${DFILP}/${ENV_PREFIX}_ESFD2230_I17G_ESFD2230___AA1_DLGTAUPUC_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA1',  'EST_NDIC_FLOARAT','${DFILP}/${ENV_PREFIX}_ESFD2230_I17G_ESFD2230___AA1_NDIC_FLOARAT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA1',  'EST_DLDGTAA_E_TRNCODEBS','${DFILP}/${ENV_PREFIX}_ESFD2230_I17G_ESFD2230___AA1_DLDGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA1',  'ESF_FUTURE_FLOARAT','${DFILP}/${ENV_PREFIX}_ESFD2230_I17G_ESFD2230___AA1_FUTURE_FLOARAT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA1',  'EST_DLDGTAA_E_TRNCODINI','${DFILP}/${ENV_PREFIX}_ESFD2230_I17G_ESFD2230___AA1_I17G_FUT_ALL_INI_DLDGTAA_INI_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('POCO',  'I17G_ESFD2230___AA1','POCO')
			insert into BEST..TI17REQFNC values ('POSO',  'I17G_ESFD2230___AA1','POSO')
			insert into BEST..TI17REQFNC values ('INVO',  'I17G_ESFD2230___AA1','INVO')

	----------IDF_CT:   I17G_ESFD2230___AA2 ------------------

		insert into BEST..TI17FNC values ('I17G_ESFD2230___AA2','Micro AOC Future Assumed AA2','ESFD2230',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA2',  'EST_FCLIENT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCLIENT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA2',  'EST_FCPLACC','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCPLACC.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA2',  'EST_FDETTRS','${DFILP}/${ENV_PREFIX}_ESCJ0660_FDETTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA2',  'EST_FTRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA2',  'EPO_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA2',  'EST_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA2',  'EPO_FBOPRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA2',  'EST_FTHRHLDUWY','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTHRHLDUWY.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA2',  'EST_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA2',  'EST_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA2',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA2',  'ESF_FTECLEDA_REJ','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDA_REJ_EBS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA2',  'EST_DLGTAAPA','${DFILP}/${ENV_PREFIX}_ESID2000_DLGTAAPA_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA2',  'EST_DLCUMGTAA','${DFILP}/${ENV_PREFIX}_ESID2000_DLCUMGTAA_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA2',  'EST_DLA_DSI_GTAA','${DFILP}/${ENV_PREFIX}_DLA_DSI_GTAA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA2',  'ESF_DLSGTAA','${DFILP}/${ENV_PREFIX}_ESPD1800_DLSGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA2',  'EST_FCTRGRO','${DFILP}/${ENV_PREFIX}_ESFD5010_FCTRGRO_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA2',  'EST_IADPERIFR','${DFILP}/${ENV_PREFIX}_ESFD5010_IADPERIFR_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA2',  'EST_IADPERIFCI','${DFILP}/${ENV_PREFIX}_ESFD5010_IADPERIFCI_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA2',  'EST_IADPERIFCT','${DFILP}/${ENV_PREFIX}_ESFD5010_IADPERIFCT_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA2',  'EST_DLDGTAA','${DFILP}/${ENV_PREFIX}_ESID2210_I17G_ESID2210___AA2_DLDGTAA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA2',  'EST_FSTAT','${DFILP}/${ENV_PREFIX}_ESFD2200_I17G_FUT_ALL_INI_FSTAT_INI_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA2',  'EST_FSEGEST_SOLVENCY','${DFILP}/${ENV_PREFIX}_ESPD0060_FSEGEST_SOLVENCY_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA2',  'EST_IADPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5040_IADPERICASE_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA2',  'EST_DLDGTAA_PREC','${DFILP}/${ENV_PREFIX}_ESID2210_I17G_ESID2210___AA2_DLDGTAA_PREC_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA2',  'EST_DLCUMGTAATOT','${DFILP}/${ENV_PREFIX}_ESID2210_I17G_ESID2210___AA2_DLCUMGTAATOT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA2',  'EST_DLDGTAA_CUMULS_COUR','${DFILP}/${ENV_PREFIX}_ESID2210_I17G_ESID2210___AA2_DLDGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA2',  'EST_DLDGTAA_UPR_DAC','${DFILP}/${ENV_PREFIX}_ESID2210_I17G_ESID2210___AA2_DLDGTAA_UPR_DAC_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA2',  'EST_CTRESTLOSPBPAP','${DFILP}/${ENV_PREFIX}_ESID2210_I17G_ESID2210___AA2_CTRESTLOSPBPAP_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA2',  'EPO_FTECLEDACO','`if [ "${TYPEINV}" = "POC" ];then echo ${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_I4I_POC_${PARM_ICLODAT_D}.dat;else echo ${DFILP}/empty.dat;fi;`','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA2',  'EPO_FTECLEDASIISO','`if [ "${TYPEINV}" = "POC" ];then echo ${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_EBS_POS_${PARM_ICLODAT_D}.dat;else echo ${DFILP}/empty.dat;fi;`','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA2',  'ESF_IADPERICASE_DELTA_POS','`if [ "${TYPEINV}" = "INV" ] || [ "${PARM_SEQ_MODE}" = "1" ] ;then echo ${DFILP}/empty.dat;else echo ${DFILI}/${ENV_PREFIX}_ESCJ0660_IADPERICASE_DELTA_POS.dat;fi;`','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA2',  'EST_FUTURE_EBS','${DFILP}/${ENV_PREFIX}_ESFD2230_I17G_ESFD2230___AA2_FUTURE_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA2',  'EST_DLGTAUPUC','${DFILP}/${ENV_PREFIX}_ESFD2230_I17G_ESFD2230___AA2_DLGTAUPUC_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA2',  'EST_NDIC_FLOARAT','${DFILP}/${ENV_PREFIX}_ESFD2230_I17G_ESFD2230___AA2_NDIC_FLOARAT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA2',  'EST_DLDGTAA_E_TRNCODEBS','${DFILP}/${ENV_PREFIX}_ESFD2230_I17G_ESFD2230___AA2_DLDGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA2',  'ESF_FUTURE_FLOARAT','${DFILP}/${ENV_PREFIX}_ESFD2230_I17G_ESFD2230___AA2_FUTURE_FLOARAT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA2',  'EST_DLDGTAA_E_TRNCODINI','${DFILP}/${ENV_PREFIX}_ESFD2230_I17G_ESFD2230___AA2_I17G_FUT_ALL_INI_DLDGTAA_INI_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('POCO',  'I17G_ESFD2230___AA2','POCO')
			insert into BEST..TI17REQFNC values ('POSO',  'I17G_ESFD2230___AA2','POSO')
			insert into BEST..TI17REQFNC values ('INVO',  'I17G_ESFD2230___AA2','INVO')

	----------IDF_CT:   I17G_ESFD2230___AA3 ------------------

		insert into BEST..TI17FNC values ('I17G_ESFD2230___AA3','Micro AOC Future Assumed AA3','ESFD2230',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA3',  'EST_FCLIENT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCLIENT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA3',  'EST_FCPLACC','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCPLACC.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA3',  'EST_FDETTRS','${DFILP}/${ENV_PREFIX}_ESCJ0660_FDETTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA3',  'EST_FTRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA3',  'EPO_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA3',  'EST_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA3',  'EPO_FBOPRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA3',  'EST_FTHRHLDUWY','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTHRHLDUWY.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA3',  'EST_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA3',  'EST_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA3',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA3',  'ESF_FTECLEDA_REJ','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDA_REJ_EBS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA3',  'EST_DLGTAAPA','${DFILP}/${ENV_PREFIX}_ESID2000_DLGTAAPA_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA3',  'EST_DLCUMGTAA','${DFILP}/${ENV_PREFIX}_ESID2000_DLCUMGTAA_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA3',  'EST_DLA_DSI_GTAA','${DFILP}/${ENV_PREFIX}_DLA_DSI_GTAA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA3',  'ESF_DLSGTAA','${DFILP}/${ENV_PREFIX}_ESPD1800_DLSGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA3',  'EST_FCTRGRO','${DFILP}/${ENV_PREFIX}_ESFD5010_FCTRGRO_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA3',  'EST_IADPERIFR','${DFILP}/${ENV_PREFIX}_ESFD5010_IADPERIFR_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA3',  'EST_IADPERIFCI','${DFILP}/${ENV_PREFIX}_ESFD5010_IADPERIFCI_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA3',  'EST_IADPERIFCT','${DFILP}/${ENV_PREFIX}_ESFD5010_IADPERIFCT_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA3',  'EST_DLDGTAA','${DFILP}/${ENV_PREFIX}_ESID2210_I17G_ESID2210___AA3_DLDGTAA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA3',  'EST_FSTAT','${DFILP}/${ENV_PREFIX}_ESFD2200_I17G_FUT_ALL_INI_FSTAT_INI_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA3',  'EST_FSEGEST_SOLVENCY','${DFILP}/${ENV_PREFIX}_ESPD0060_FSEGEST_SOLVENCY_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA3',  'EST_IADPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5040_IADPERICASE_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA3',  'EST_DLDGTAA_PREC','${DFILP}/${ENV_PREFIX}_ESID2210_I17G_ESID2210___AA3_DLDGTAA_PREC_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA3',  'EST_DLCUMGTAATOT','${DFILP}/${ENV_PREFIX}_ESID2210_I17G_ESID2210___AA3_DLCUMGTAATOT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA3',  'EST_DLDGTAA_CUMULS_COUR','${DFILP}/${ENV_PREFIX}_ESID2210_I17G_ESID2210___AA3_DLDGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA3',  'EST_DLDGTAA_UPR_DAC','${DFILP}/${ENV_PREFIX}_ESID2210_I17G_ESID2210___AA3_DLDGTAA_UPR_DAC_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA3',  'EST_CTRESTLOSPBPAP','${DFILP}/${ENV_PREFIX}_ESID2210_I17G_ESID2210___AA3_CTRESTLOSPBPAP_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA3',  'EPO_FTECLEDACO','`if [ "${TYPEINV}" = "POC" ];then echo ${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_I4I_POC_${PARM_ICLODAT_D}.dat;else echo ${DFILP}/empty.dat;fi;`','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA3',  'EPO_FTECLEDASIISO','`if [ "${TYPEINV}" = "POC" ];then echo ${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_EBS_POS_${PARM_ICLODAT_D}.dat;else echo ${DFILP}/empty.dat;fi;`','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA3',  'ESF_IADPERICASE_DELTA_POS','`if [ "${TYPEINV}" = "INV" ] || [ "${PARM_SEQ_MODE}" = "1" ] ;then echo ${DFILP}/empty.dat;else echo ${DFILI}/${ENV_PREFIX}_ESCJ0660_IADPERICASE_DELTA_POS.dat;fi;`','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA3',  'EST_FUTURE_EBS','${DFILP}/${ENV_PREFIX}_ESFD2230_I17G_ESFD2230___AA3_FUTURE_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA3',  'EST_DLGTAUPUC','${DFILP}/${ENV_PREFIX}_ESFD2230_I17G_ESFD2230___AA3_DLGTAUPUC_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA3',  'EST_NDIC_FLOARAT','${DFILP}/${ENV_PREFIX}_ESFD2230_I17G_ESFD2230___AA3_NDIC_FLOARAT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA3',  'EST_DLDGTAA_E_TRNCODEBS','${DFILP}/${ENV_PREFIX}_ESFD2230_I17G_ESFD2230___AA3_DLDGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA3',  'ESF_FUTURE_FLOARAT','${DFILP}/${ENV_PREFIX}_ESFD2230_I17G_ESFD2230___AA3_FUTURE_FLOARAT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2230___AA3',  'EST_DLDGTAA_E_TRNCODINI','${DFILP}/${ENV_PREFIX}_ESFD2230_I17G_ESFD2230___AA3_I17G_FUT_ALL_INI_DLDGTAA_INI_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('POCO',  'I17G_ESFD2230___AA3','POCO')
			insert into BEST..TI17REQFNC values ('POSO',  'I17G_ESFD2230___AA3','POSO')
			insert into BEST..TI17REQFNC values ('INVO',  'I17G_ESFD2230___AA3','INVO')
go

