-------------------------------
--mapping of  ESFD8100
-- [001] 10/11/2023 M.NAJI 	   :spira 110830 I17S- Change in RA interface - Copy

	----------   Clean tables   ---------------------

	delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD8100')
	delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD8100')
	delete BEST..TI17FNC where CHAIN_CT='ESFD8100'
	delete BEST..TI17CHN  where CHAIN_CT='ESFD8100'

	insert into BEST..TI17CHN values ('ESFD8100',  'Generating IFRS 17 Group RA files')

	----------IDF_CT:   I17G_OMG_RA_AOC ------------------

		insert into BEST..TI17FNC values ('I17G_OMG_RA_AOC',' ','ESFD8100',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17G_OMG_RA_AOC',  'ESF_FTECLEDSII','${DFILP}/${ENV_PREFIX}_ESFD3730_I17G_SII_ALL_AOC_FTECLEDSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_RA_AOC',  'ESF_CLS','${ENV_PREFIX}_ESFD8100_BSAR_I17G_OMG_RA_AOC_CLSTYPE_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_RA_AOC',  'ESF_FMETADATA','${ENV_PREFIX}_ESFD8100_BSAR_I17G_OMG_RA_AOC_METADATA_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_RA_AOC',  'ESF_FILE_LIST','${ENV_PREFIX}_ESFD8100_BSAR_I17G_OMG_RA_AOC_FILE_LIST_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_RA_AOC',  'ESF_FTECLEDSIIRA','${ENV_PREFIX}_ESFD8100_BSAR_I17G_OMG_RA_AOC_FTECLEDSIIRA_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')

			--- output files by site
			insert into BEST..TI17PERMFIL values ('I17G_OMG_RA_AOC',  'ESF_FTECLEDSII_TOAS',    '${ENV_PREFIX}_ESFD3730_FTECLEDSIIAOC_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOAS}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_RA_AOC',  'ESF_FTECLEDSII_TOEU',    '${ENV_PREFIX}_ESFD3730_FTECLEDSIIAOC_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOEU}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_RA_AOC',  'ESF_FTECLEDSII_TOAM',    '${ENV_PREFIX}_ESFD3730_FTECLEDSIIAOC_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOAM}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_RA_AOC',  'ESF_FTECLEDSII_LOCAL',    '$DFILP/${ENV_PREFIX}_ESFD3730_FTECLEDSIIAOC_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','O','')

			--- input files by site
			insert into BEST..TI17PERMFIL values ('I17G_OMG_RA_AOC',  'ESF_FTECLEDSII_FROMAS',    '${DFILP}/${ENV_PREFIX}_ESFD3730_FTECLEDSIIAOC_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_ASTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_RA_AOC',  'ESF_FTECLEDSII_FROMEU',    '${DFILP}/${ENV_PREFIX}_ESFD3730_FTECLEDSIIAOC_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_EUTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_RA_AOC',  'ESF_FTECLEDSII_FROMAM',    '${DFILP}/${ENV_PREFIX}_ESFD3730_FTECLEDSIIAOC_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_AMTOLOCAL}.dat','I','')


		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('INVO',  'I17G_OMG_RA_AOC','INVO')
			insert into BEST..TI17REQFNC values ('POCO',  'I17G_OMG_RA_AOC','POCO')
			insert into BEST..TI17REQFNC values ('POSO',  'I17G_OMG_RA_AOC','POSO')

	----------IDF_CT:   I17G_OMG_RA_STD ------------------

		insert into BEST..TI17FNC values ('I17G_OMG_RA_STD',' ','ESFD8100',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17G_OMG_RA_STD',  'ESF_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_RA_STD',  'ESF_GAAPCOD_MAPPING','${DFILP}/${ENV_PREFIX}_ESCJ0060_GAAPCOD_MAPPING.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_RA_STD',  'ESF_FTECLEDA','${DFILP}/${ENV_PREFIX}_ESPD3970_I17G_MVT_MRG_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_RA_STD',  'ESF_FTECLEDR','$DFILP/${ENV_PREFIX}_ESFD3840_${NORME_CF}_GLT_MRG_STD_FTECLEDR_MVT_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_RA_STD',  'ESF_FTECLEDSII','${DFILP}/${ENV_PREFIX}_ESFD3730_I17G_SII_ALL_STD_FTECLEDSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_RA_STD',  'ESF_GTSII_RISKMARGIN','${DFILP}/${ENV_PREFIX}_ESFD3730_I17G_SII_ALL_STD_GTSII_RISKMARGIN${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_RA_STD',  'ESF_FTECLEDACO_ANNULMVT','${DFILP}/${ENV_PREFIX}_ESFD3730_I17G_SII_ALL_STD_FTECLEDACO_ANNULMVT_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_RA_STD',  'ESF_FTECLEDRCO_ANNULMVT','${DFILP}/${ENV_PREFIX}_ESFD3730_I17G_SII_ALL_STD_FTECLEDRCO_ANNULMVT_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_RA_STD',  'ESF_CLS','${ENV_PREFIX}_ESFD8100_BSAR_I17G_OMG_RA_STD_CLSTYPE_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_RA_STD',  'ESF_FILE_LIST','${ENV_PREFIX}_ESFD8100_BSAR_I17G_OMG_RA_STD_FILE_LIST_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_RA_STD',  'ESF_FTECLEDARA','${ENV_PREFIX}_ESFD8100_BSAR_I17G_OMG_RA_STD_FTECLEDARA_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_RA_STD',  'ESF_FTECLEDRRA','${ENV_PREFIX}_ESFD8100_BSAR_I17G_OMG_RA_STD_FTECLEDRRA_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_RA_STD',  'ESF_FTECLEDAYTD','${ENV_PREFIX}_ESFD8100_BSAR_I17G_OMG_RA_STD_FTECLEDAYTD_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_RA_STD',  'ESF_FTECLEDRYTD','${ENV_PREFIX}_ESFD8100_BSAR_I17G_OMG_RA_STD_FTECLEDRYTD_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_RA_STD',  'ESF_FMETADATA','${ENV_PREFIX}_ESFD8100_BSAR_${NORME_CF}_OMG_RA_STD_METADATA_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_RA_STD',  'ESF_FTECLEDSIIRA','${ENV_PREFIX}_ESFD8100_BSAR_I17G_OMG_RA_STD_FTECLEDSIIRA_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_RA_STD',  'ESF_FULTIMATESRA','${ENV_PREFIX}_ESFD8100_BSAR_I17G_OMG_RA_STD_FULTIMATESRA_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_RA_STD',  'ESF_GAAPCOD_RA','${ENV_PREFIX}_ESFD8100_BSAR_I17G_OMG_RA_STD_GAAPCOD_MAPPING_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')

			--- output files by site
			insert into BEST..TI17PERMFIL values ('I17G_OMG_RA_STD',  'ESF_FTECLEDSII_TOAS',    '${ENV_PREFIX}_ESFD3730_FTECLEDSII_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOAS}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_RA_STD',  'ESF_FTECLEDSII_TOEU',    '${ENV_PREFIX}_ESFD3730_FTECLEDSII_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOEU}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_RA_STD',  'ESF_FTECLEDSII_TOAM',    '${ENV_PREFIX}_ESFD3730_FTECLEDSII_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOAM}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_RA_STD',  'ESF_FTECLEDSII_LOCAL',    '$DFILP/${ENV_PREFIX}_ESFD3730_FTECLEDSII_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','O','')

			--- input files by site
			insert into BEST..TI17PERMFIL values ('I17G_OMG_RA_STD',  'ESF_FTECLEDSII_FROMAS',    '${DFILP}/${ENV_PREFIX}_ESFD3730_FTECLEDSII_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_ASTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_RA_STD',  'ESF_FTECLEDSII_FROMEU',    '${DFILP}/${ENV_PREFIX}_ESFD3730_FTECLEDSII_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_EUTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_RA_STD',  'ESF_FTECLEDSII_FROMAM',    '${DFILP}/${ENV_PREFIX}_ESFD3730_FTECLEDSII_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_AMTOLOCAL}.dat','I','')

			--- output files by site
 			insert into BEST..TI17PERMFIL values ('I17G_OMG_RA_STD',  'ESF_SII_RISKMARGIN_TOAS',    '${ENV_PREFIX}_ESFD3730_SII_RISKMARGIN_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOAS}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_RA_STD',  'ESF_SII_RISKMARGIN_TOEU',    '${ENV_PREFIX}_ESFD3730_SII_RISKMARGIN_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOEU}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_RA_STD',  'ESF_SII_RISKMARGIN_TOAM',    '${ENV_PREFIX}_ESFD3730_SII_RISKMARGIN_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOAM}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_RA_STD',  'ESF_SII_RISKMARGIN_LOCAL',    '$DFILP/${ENV_PREFIX}_ESFD3730_SII_RISKMARGIN_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','O','')
			
			--- input files by site
			insert into BEST..TI17PERMFIL values ('I17G_OMG_RA_STD',  'ESF_SII_RISKMARGIN_FROMAS',    '${DFILP}/${ENV_PREFIX}_ESFD3730_SII_RISKMARGIN_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_ASTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_RA_STD',  'ESF_SII_RISKMARGIN_FROMEU',    '${DFILP}/${ENV_PREFIX}_ESFD3730_SII_RISKMARGIN_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_EUTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_RA_STD',  'ESF_SII_RISKMARGIN_FROMAM',    '${DFILP}/${ENV_PREFIX}_ESFD3730_SII_RISKMARGIN_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_AMTOLOCAL}.dat','I','')

	
	
		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17GQINV',  'I17G_OMG_RA_STD','')
			insert into BEST..TI17REQFNC values ('I17GQINVB',  'I17G_OMG_RA_STD','')
			insert into BEST..TI17REQFNC values ('I17GYINV',  'I17G_OMG_RA_STD','')
			insert into BEST..TI17REQFNC values ('I17GYINVB',  'I17G_OMG_RA_STD','')
			insert into BEST..TI17REQFNC values ('I17GQPOS',  'I17G_OMG_RA_STD','')
			insert into BEST..TI17REQFNC values ('I17GQPOSB',  'I17G_OMG_RA_STD','')
			insert into BEST..TI17REQFNC values ('I17GYPOS',  'I17G_OMG_RA_STD','')
			insert into BEST..TI17REQFNC values ('I17GYPOSB',  'I17G_OMG_RA_STD','')
			insert into BEST..TI17REQFNC values ('I17GMINV',  'I17G_OMG_RA_STD','')
			insert into BEST..TI17REQFNC values ('I17GQPOSP',  'I17G_OMG_RA_STD','')
			insert into BEST..TI17REQFNC values ('I17GYPOSP',  'I17G_OMG_RA_STD','')

	----------IDF_CT:   I17L_OMG_RA_STD ------------------

		insert into BEST..TI17FNC values ('I17L_OMG_RA_STD',' ','ESFD8100',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17L_OMG_RA_STD',  'ESF_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_OMG_RA_STD',  'ESF_GAAPCOD_MAPPING','${DFILP}/${ENV_PREFIX}_ESCJ0060_GAAPCOD_MAPPING.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_OMG_RA_STD',  'ESF_FTECLEDA','${DFILP}/${ENV_PREFIX}_ESPD3970_I17L_MVT_MRG_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_OMG_RA_STD',  'ESF_FTECLEDR','$DFILP/${ENV_PREFIX}_ESFD3840_${NORME_CF}_GLT_MRG_STD_FTECLEDR_MVT_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_OMG_RA_STD',  'ESF_FTECLEDSII','${DFILP}/${ENV_PREFIX}_ESFD3730_I17L_SII_ALL_STD_FTECLEDSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_OMG_RA_STD',  'ESF_GTSII_RISKMARGIN','${DFILP}/${ENV_PREFIX}_ESFD3730_I17L_SII_ALL_STD_GTSII_RISKMARGIN${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_OMG_RA_STD',  'ESF_FTECLEDACO_ANNULMVT','${DFILP}/${ENV_PREFIX}_ESFD3730_I17L_SII_ALL_STD_FTECLEDACO_ANNULMVT_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_OMG_RA_STD',  'ESF_FTECLEDRCO_ANNULMVT','${DFILP}/${ENV_PREFIX}_ESFD3730_I17L_SII_ALL_STD_FTECLEDRCO_ANNULMVT_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_OMG_RA_STD',  'ESF_CLS','${ENV_PREFIX}_ESFD8100_BSAR_I17L_OMG_RA_STD_CLSTYPE_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_OMG_RA_STD',  'ESF_FILE_LIST','${ENV_PREFIX}_ESFD8100_BSAR_I17L_OMG_RA_STD_FILE_LIST_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_OMG_RA_STD',  'ESF_FTECLEDARA','${ENV_PREFIX}_ESFD8100_BSAR_I17L_OMG_RA_STD_FTECLEDARA_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_OMG_RA_STD',  'ESF_FTECLEDRRA','${ENV_PREFIX}_ESFD8100_BSAR_I17L_OMG_RA_STD_FTECLEDRRA_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_OMG_RA_STD',  'ESF_FTECLEDAYTD','${ENV_PREFIX}_ESFD8100_BSAR_I17L_OMG_RA_STD_FTECLEDAYTD_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_OMG_RA_STD',  'ESF_FTECLEDRYTD','${ENV_PREFIX}_ESFD8100_BSAR_I17L_OMG_RA_STD_FTECLEDRYTD_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_OMG_RA_STD',  'ESF_FMETADATA','${ENV_PREFIX}_ESFD8100_BSAR_${NORME_CF}_OMG_RA_STD_METADATA_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_OMG_RA_STD',  'ESF_FTECLEDSIIRA','${ENV_PREFIX}_ESFD8100_BSAR_I17L_OMG_RA_STD_FTECLEDSIIRA_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_OMG_RA_STD',  'ESF_FULTIMATESRA','${ENV_PREFIX}_ESFD8100_BSAR_I17L_OMG_RA_STD_FULTIMATESRA_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_OMG_RA_STD',  'ESF_GAAPCOD_RA','${ENV_PREFIX}_ESFD8100_BSAR_I17L_OMG_RA_STD_GAAPCOD_MAPPING_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')

			--- output files by site
			insert into BEST..TI17PERMFIL values ('I17L_OMG_RA_STD',  'ESF_FTECLEDSII_TOAS',    '${ENV_PREFIX}_ESFD3730_FTECLEDSII_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOAS}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_OMG_RA_STD',  'ESF_FTECLEDSII_TOEU',    '${ENV_PREFIX}_ESFD3730_FTECLEDSII_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOEU}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_OMG_RA_STD',  'ESF_FTECLEDSII_TOAM',    '${ENV_PREFIX}_ESFD3730_FTECLEDSII_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOAM}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_OMG_RA_STD',  'ESF_FTECLEDSII_LOCAL',    '$DFILP/${ENV_PREFIX}_ESFD3730_FTECLEDSII_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','O','')

			--- input files by site
			insert into BEST..TI17PERMFIL values ('I17L_OMG_RA_STD',  'ESF_FTECLEDSII_FROMAS',    '${DFILP}/${ENV_PREFIX}_ESFD3730_FTECLEDSII_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_ASTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_OMG_RA_STD',  'ESF_FTECLEDSII_FROMEU',    '${DFILP}/${ENV_PREFIX}_ESFD3730_FTECLEDSII_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_EUTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_OMG_RA_STD',  'ESF_FTECLEDSII_FROMAM',    '${DFILP}/${ENV_PREFIX}_ESFD3730_FTECLEDSII_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_AMTOLOCAL}.dat','I','')

			--- output files by site
 			insert into BEST..TI17PERMFIL values ('I17L_OMG_RA_STD',  'ESF_SII_RISKMARGIN_TOAS',    '${ENV_PREFIX}_ESFD3730_SII_RISKMARGIN_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOAS}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_OMG_RA_STD',  'ESF_SII_RISKMARGIN_TOEU',    '${ENV_PREFIX}_ESFD3730_SII_RISKMARGIN_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOEU}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_OMG_RA_STD',  'ESF_SII_RISKMARGIN_TOAM',    '${ENV_PREFIX}_ESFD3730_SII_RISKMARGIN_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOAM}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_OMG_RA_STD',  'ESF_SII_RISKMARGIN_LOCAL',    '$DFILP/${ENV_PREFIX}_ESFD3730_SII_RISKMARGIN_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','O','')
			
			--- input files by site
			insert into BEST..TI17PERMFIL values ('I17L_OMG_RA_STD',  'ESF_SII_RISKMARGIN_FROMAS',    '${DFILP}/${ENV_PREFIX}_ESFD3730_SII_RISKMARGIN_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_ASTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_OMG_RA_STD',  'ESF_SII_RISKMARGIN_FROMEU',    '${DFILP}/${ENV_PREFIX}_ESFD3730_SII_RISKMARGIN_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_EUTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_OMG_RA_STD',  'ESF_SII_RISKMARGIN_FROMAM',    '${DFILP}/${ENV_PREFIX}_ESFD3730_SII_RISKMARGIN_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_AMTOLOCAL}.dat','I','')

	

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17LQINV',  'I17L_OMG_RA_STD','')
			insert into BEST..TI17REQFNC values ('I17LQINVB',  'I17L_OMG_RA_STD','')
			insert into BEST..TI17REQFNC values ('I17LYINV',  'I17L_OMG_RA_STD','')
			insert into BEST..TI17REQFNC values ('I17LYINVB',  'I17L_OMG_RA_STD','')
			insert into BEST..TI17REQFNC values ('I17LQPOS',  'I17L_OMG_RA_STD','')
			insert into BEST..TI17REQFNC values ('I17LQPOSB',  'I17L_OMG_RA_STD','')
			insert into BEST..TI17REQFNC values ('I17LYPOS',  'I17L_OMG_RA_STD','')
			insert into BEST..TI17REQFNC values ('I17LYPOSB',  'I17L_OMG_RA_STD','')
			insert into BEST..TI17REQFNC values ('I17LMINV',  'I17L_OMG_RA_STD','')
			insert into BEST..TI17REQFNC values ('I17LQPOSP',  'I17L_OMG_RA_STD','')
			insert into BEST..TI17REQFNC values ('I17LYPOSP',  'I17L_OMG_RA_STD','')
			insert into BEST..TI17REQFNC values ('I17LQPOSX',  'I17L_OMG_RA_STD','')
			insert into BEST..TI17REQFNC values ('I17LYPOSX',  'I17L_OMG_RA_STD','')

	----------IDF_CT:   I17P_OMG_RA_STD ------------------

		insert into BEST..TI17FNC values ('I17P_OMG_RA_STD',' ','ESFD8100',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17P_OMG_RA_STD',  'ESF_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_OMG_RA_STD',  'ESF_GAAPCOD_MAPPING','${DFILP}/${ENV_PREFIX}_ESCJ0060_GAAPCOD_MAPPING.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_OMG_RA_STD',  'ESF_FTECLEDA','${DFILP}/${ENV_PREFIX}_ESPD3970_I17P_MVT_MRG_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_OMG_RA_STD',  'ESF_FTECLEDR','$DFILP/${ENV_PREFIX}_ESFD3840_${NORME_CF}_GLT_MRG_STD_FTECLEDR_MVT_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_OMG_RA_STD',  'ESF_FTECLEDSII','${DFILP}/${ENV_PREFIX}_ESFD3730_I17P_SII_ALL_STD_FTECLEDSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_OMG_RA_STD',  'ESF_GTSII_RISKMARGIN','${DFILP}/${ENV_PREFIX}_ESFD3730_I17P_SII_ALL_STD_GTSII_RISKMARGIN${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_OMG_RA_STD',  'ESF_FTECLEDACO_ANNULMVT','${DFILP}/${ENV_PREFIX}_ESFD3730_I17P_SII_ALL_STD_FTECLEDACO_ANNULMVT_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_OMG_RA_STD',  'ESF_FTECLEDRCO_ANNULMVT','${DFILP}/${ENV_PREFIX}_ESFD3730_I17P_SII_ALL_STD_FTECLEDRCO_ANNULMVT_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_OMG_RA_STD',  'ESF_CLS','${ENV_PREFIX}_ESFD8100_BSAR_I17P_OMG_RA_STD_CLSTYPE_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_OMG_RA_STD',  'ESF_FILE_LIST','${ENV_PREFIX}_ESFD8100_BSAR_I17P_OMG_RA_STD_FILE_LIST_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_OMG_RA_STD',  'ESF_FTECLEDARA','${ENV_PREFIX}_ESFD8100_BSAR_I17P_OMG_RA_STD_FTECLEDARA_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_OMG_RA_STD',  'ESF_FTECLEDRRA','${ENV_PREFIX}_ESFD8100_BSAR_I17P_OMG_RA_STD_FTECLEDRRA_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_OMG_RA_STD',  'ESF_FTECLEDAYTD','${ENV_PREFIX}_ESFD8100_BSAR_I17P_OMG_RA_STD_FTECLEDAYTD_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_OMG_RA_STD',  'ESF_FTECLEDRYTD','${ENV_PREFIX}_ESFD8100_BSAR_I17P_OMG_RA_STD_FTECLEDRYTD_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_OMG_RA_STD',  'ESF_FMETADATA','${ENV_PREFIX}_ESFD8100_BSAR_${NORME_CF}_OMG_RA_STD_METADATA_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_OMG_RA_STD',  'ESF_FTECLEDSIIRA','${ENV_PREFIX}_ESFD8100_BSAR_I17P_OMG_RA_STD_FTECLEDSIIRA_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_OMG_RA_STD',  'ESF_FULTIMATESRA','${ENV_PREFIX}_ESFD8100_BSAR_I17P_OMG_RA_STD_FULTIMATESRA_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_OMG_RA_STD',  'ESF_GAAPCOD_RA','${ENV_PREFIX}_ESFD8100_BSAR_I17P_OMG_RA_STD_GAAPCOD_MAPPING_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')

			--- output files by site
			insert into BEST..TI17PERMFIL values ('I17P_OMG_RA_STD',  'ESF_FTECLEDSII_TOAS',    '${ENV_PREFIX}_ESFD3730_FTECLEDSII_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOAS}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_OMG_RA_STD',  'ESF_FTECLEDSII_TOEU',    '${ENV_PREFIX}_ESFD3730_FTECLEDSII_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOEU}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_OMG_RA_STD',  'ESF_FTECLEDSII_TOAM',    '${ENV_PREFIX}_ESFD3730_FTECLEDSII_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOAM}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_OMG_RA_STD',  'ESF_FTECLEDSII_LOCAL',    '$DFILP/${ENV_PREFIX}_ESFD3730_FTECLEDSII_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','O','')

			--- input files by site
			insert into BEST..TI17PERMFIL values ('I17P_OMG_RA_STD',  'ESF_FTECLEDSII_FROMAS',    '${DFILP}/${ENV_PREFIX}_ESFD3730_FTECLEDSII_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_ASTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_OMG_RA_STD',  'ESF_FTECLEDSII_FROMEU',    '${DFILP}/${ENV_PREFIX}_ESFD3730_FTECLEDSII_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_EUTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_OMG_RA_STD',  'ESF_FTECLEDSII_FROMAM',    '${DFILP}/${ENV_PREFIX}_ESFD3730_FTECLEDSII_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_AMTOLOCAL}.dat','I','')

			--- output files by site
 			insert into BEST..TI17PERMFIL values ('I17P_OMG_RA_STD',  'ESF_SII_RISKMARGIN_TOAS',    '${ENV_PREFIX}_ESFD3730_SII_RISKMARGIN_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOAS}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_OMG_RA_STD',  'ESF_SII_RISKMARGIN_TOEU',    '${ENV_PREFIX}_ESFD3730_SII_RISKMARGIN_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOEU}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_OMG_RA_STD',  'ESF_SII_RISKMARGIN_TOAM',    '${ENV_PREFIX}_ESFD3730_SII_RISKMARGIN_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOAM}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_OMG_RA_STD',  'ESF_SII_RISKMARGIN_LOCAL',    '$DFILP/${ENV_PREFIX}_ESFD3730_SII_RISKMARGIN_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','O','')
			
			--- input files by site
			insert into BEST..TI17PERMFIL values ('I17P_OMG_RA_STD',  'ESF_SII_RISKMARGIN_FROMAS',    '${DFILP}/${ENV_PREFIX}_ESFD3730_SII_RISKMARGIN_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_ASTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_OMG_RA_STD',  'ESF_SII_RISKMARGIN_FROMEU',    '${DFILP}/${ENV_PREFIX}_ESFD3730_SII_RISKMARGIN_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_EUTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_OMG_RA_STD',  'ESF_SII_RISKMARGIN_FROMAM',    '${DFILP}/${ENV_PREFIX}_ESFD3730_SII_RISKMARGIN_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_AMTOLOCAL}.dat','I','')

	

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17PQINV',  'I17P_OMG_RA_STD','')
			insert into BEST..TI17REQFNC values ('I17PQINVB',  'I17P_OMG_RA_STD','')
			insert into BEST..TI17REQFNC values ('I17PYINV',  'I17P_OMG_RA_STD','')
			insert into BEST..TI17REQFNC values ('I17PYINVB',  'I17P_OMG_RA_STD','')
			insert into BEST..TI17REQFNC values ('I17PQPOS',  'I17P_OMG_RA_STD','')
			insert into BEST..TI17REQFNC values ('I17PQPOSB',  'I17P_OMG_RA_STD','')
			insert into BEST..TI17REQFNC values ('I17PYPOS',  'I17P_OMG_RA_STD','')
			insert into BEST..TI17REQFNC values ('I17PYPOSB',  'I17P_OMG_RA_STD','')
			insert into BEST..TI17REQFNC values ('I17PMINV',  'I17P_OMG_RA_STD','')
			insert into BEST..TI17REQFNC values ('I17PQPOSP',  'I17P_OMG_RA_STD','')
			insert into BEST..TI17REQFNC values ('I17PYPOSP',  'I17P_OMG_RA_STD','')
			insert into BEST..TI17REQFNC values ('I17PQPOSX',  'I17P_OMG_RA_STD','')
			insert into BEST..TI17REQFNC values ('I17PYPOSX',  'I17P_OMG_RA_STD','')

	----------IDF_CT:   I17S_OMG_RA_AOC ------------------

		insert into BEST..TI17FNC values ('I17S_OMG_RA_AOC',' ','ESFD8100',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_AOC',  'ESF_FTECLEDSII','${DFILP}/${ENV_PREFIX}_ESFD3730_I17S_SII_ALL_AOC_FTECLEDSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_AOC',  'ESF_CLS','${ENV_PREFIX}_ESFD8100_BSAR_I17S_OMG_RA_AOC_CLSTYPE_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_AOC',  'ESF_FMETADATA','${ENV_PREFIX}_ESFD8100_BSAR_I17S_OMG_RA_AOC_METADATA_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_AOC',  'ESF_FILE_LIST','${ENV_PREFIX}_ESFD8100_BSAR_I17S_OMG_RA_AOC_FILE_LIST_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_AOC',  'ESF_FTECLEDSIIRA','${ENV_PREFIX}_ESFD8100_BSAR_I17S_OMG_RA_AOC_FTECLEDSIIRA_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')

			--- output files by site
			insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_AOC',  'ESF_FTECLEDSII_TOAS',    '${ENV_PREFIX}_ESFD3730_FTECLEDSIIAOC_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOAS}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_AOC',  'ESF_FTECLEDSII_TOEU',    '${ENV_PREFIX}_ESFD3730_FTECLEDSIIAOC_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOEU}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_AOC',  'ESF_FTECLEDSII_TOAM',    '${ENV_PREFIX}_ESFD3730_FTECLEDSIIAOC_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOAM}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_AOC',  'ESF_FTECLEDSII_LOCAL',    '$DFILP/${ENV_PREFIX}_ESFD3730_FTECLEDSIIAOC_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','O','')

			--- input files by site
			insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_AOC',  'ESF_FTECLEDSII_FROMAS',    '${DFILP}/${ENV_PREFIX}_ESFD3730_FTECLEDSIIAOC_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_ASTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_AOC',  'ESF_FTECLEDSII_FROMEU',    '${DFILP}/${ENV_PREFIX}_ESFD3730_FTECLEDSIIAOC_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_EUTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_AOC',  'ESF_FTECLEDSII_FROMAM',    '${DFILP}/${ENV_PREFIX}_ESFD3730_FTECLEDSIIAOC_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_AMTOLOCAL}.dat','I','')


		----------   Reqs    ---------------------


	----------IDF_CT:   I17S_OMG_RA_STD ------------------

		insert into BEST..TI17FNC values ('I17S_OMG_RA_STD',' ','ESFD8100',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_STD',  'ESF_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_STD',  'ESF_GAAPCOD_MAPPING','${DFILP}/${ENV_PREFIX}_ESCJ0060_GAAPCOD_MAPPING.dat','I','')
			
			insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_STD',  'ESF_FTECLEDA_CLOSING','${DFILP}/${ENV_PREFIX}_ESPD3970_I17S_MVT_MRG_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_STD',  'ESF_FTECLEDR_CLOSING','$DFILP/${ENV_PREFIX}_ESFD3840_${NORME_CF}_GLT_MRG_STD_FTECLEDR_MVT_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_STD',  'ESF_FTECLEDSII_CLOSING','${DFILP}/${ENV_PREFIX}_ESFD3730_I17S_SII_ALL_STD_FTECLEDSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			--insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_STD',  'ESF_GTSII_RISKMARGIN_CLOSING','${DFILP}/${ENV_PREFIX}_ESFD3730_I17S_SII_ALL_STD_GTSII_RISKMARGIN${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')

			insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_STD',  'EST_FTECLEDA_I4' ,'${DFILP}/${ENV_PREFIX}_ES${PARM_FTECLED}D3800_FTECLEDA_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_STD',  'EST_FTECLEDR_I4' ,'${DFILP}/${ENV_PREFIX}_ES${PARM_FTECLED}D3800_FTECLEDR_I4I_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_STD',  'EST_FTECLEDA_EBS','${DFILP}/${ENV_PREFIX}_ESPD3970_EBS_MVT_MRG_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_STD',  'EST_FTECLEDR_EBS','${DFILP}/${ENV_PREFIX}_ESPD3970_EBS_MVT_MRG_STD_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_STD',  'EST_FTECLEDSII_EBS','${DFILP}/${ENV_PREFIX}_ESPD3700_FTECLED_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
            --insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_STD',  'EST_GTSII_RISKMARGIN_EBS','${DFILP}/${ENV_PREFIX}_ESPD3700_GTSII_RISKMARGIN_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')

			insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_STD',  'ESF_FTECLEDA','${DFILP}/${ENV_PREFIX}_ESFD8100_I17S_MVT_MRG_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_STD',  'ESF_FTECLEDR','${DFILP}/${ENV_PREFIX}_ESFD8100_I17S_GLT_MRG_STD_FTECLEDR_MVT_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_STD',  'ESF_FTECLEDSII','${DFILP}/${ENV_PREFIX}_ESFD8100_I17S_SII_ALL_STD_FTECLEDSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			--insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_STD',  'ESF_GTSII_RISKMARGIN','${DFILP}/${ENV_PREFIX}_ESFD8100_I17S_SII_ALL_STD_GTSII_RISKMARGIN${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

			insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_STD',  'ESF_FTECLEDACO_ANNULMVT','${DFILP}/${ENV_PREFIX}_ESFD3730_I17S_SII_ALL_STD_FTECLEDACO_ANNULMVT_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_STD',  'ESF_FTECLEDRCO_ANNULMVT','${DFILP}/${ENV_PREFIX}_ESFD3730_I17S_SII_ALL_STD_FTECLEDRCO_ANNULMVT_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_STD',  'ESF_CLS','${ENV_PREFIX}_ESFD8100_BSAR_I17S_OMG_RA_STD_CLSTYPE_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_STD',  'ESF_FILE_LIST','${ENV_PREFIX}_ESFD8100_BSAR_I17S_OMG_RA_STD_FILE_LIST_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_STD',  'ESF_FTECLEDARA','${ENV_PREFIX}_ESFD8100_BSAR_I17S_OMG_RA_STD_FTECLEDARA_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_STD',  'ESF_FTECLEDRRA','${ENV_PREFIX}_ESFD8100_BSAR_I17S_OMG_RA_STD_FTECLEDRRA_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_STD',  'ESF_FTECLEDAYTD','${ENV_PREFIX}_ESFD8100_BSAR_I17S_OMG_RA_STD_FTECLEDAYTD_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_STD',  'ESF_FTECLEDRYTD','${ENV_PREFIX}_ESFD8100_BSAR_I17S_OMG_RA_STD_FTECLEDRYTD_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_STD',  'ESF_FMETADATA','${ENV_PREFIX}_ESFD8100_BSAR_${NORME_CF}_OMG_RA_STD_METADATA_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_STD',  'ESF_FTECLEDSIIRA','${ENV_PREFIX}_ESFD8100_BSAR_I17S_OMG_RA_STD_FTECLEDSIIRA_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_STD',  'ESF_FULTIMATESRA','${ENV_PREFIX}_ESFD8100_BSAR_I17S_OMG_RA_STD_FULTIMATESRA_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_STD',  'ESF_GAAPCOD_RA','${ENV_PREFIX}_ESFD8100_BSAR_I17S_OMG_RA_STD_GAAPCOD_MAPPING_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_STD',  'ESF_GTSII_RISKMARGIN','${DFILP}/${ENV_PREFIX}_ESFD3730_I17S_SII_ALL_STD_GTSII_RISKMARGIN${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_STD',  'ESF_FI17CLOPER','${DFILP}/${ENV_PREFIX}_ESFD1130_FI17CLOPER_I17S_DSC_ALL_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
 
			--- output files by site
			insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_STD',  'ESF_FTECLEDSII_TOAS',    '${ENV_PREFIX}_ESFD3730_FTECLEDSII_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOAS}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_STD',  'ESF_FTECLEDSII_TOEU',    '${ENV_PREFIX}_ESFD3730_FTECLEDSII_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOEU}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_STD',  'ESF_FTECLEDSII_TOAM',    '${ENV_PREFIX}_ESFD3730_FTECLEDSII_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOAM}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_STD',  'ESF_FTECLEDSII_LOCAL',    '$DFILP/${ENV_PREFIX}_ESFD3730_FTECLEDSII_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','O','')

			--- input files by site
			insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_STD',  'ESF_FTECLEDSII_FROMAS',    '${DFILP}/${ENV_PREFIX}_ESFD3730_FTECLEDSII_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_ASTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_STD',  'ESF_FTECLEDSII_FROMEU',    '${DFILP}/${ENV_PREFIX}_ESFD3730_FTECLEDSII_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_EUTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_STD',  'ESF_FTECLEDSII_FROMAM',    '${DFILP}/${ENV_PREFIX}_ESFD3730_FTECLEDSII_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_AMTOLOCAL}.dat','I','')

			--- output files by site
 			insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_STD',  'ESF_SII_RISKMARGIN_TOAS',    '${ENV_PREFIX}_ESFD3730_SII_RISKMARGIN_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOAS}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_STD',  'ESF_SII_RISKMARGIN_TOEU',    '${ENV_PREFIX}_ESFD3730_SII_RISKMARGIN_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOEU}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_STD',  'ESF_SII_RISKMARGIN_TOAM',    '${ENV_PREFIX}_ESFD3730_SII_RISKMARGIN_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOAM}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_STD',  'ESF_SII_RISKMARGIN_LOCAL',    '$DFILP/${ENV_PREFIX}_ESFD3730_SII_RISKMARGIN_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','O','')
			
			--- input files by site
			insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_STD',  'ESF_SII_RISKMARGIN_FROMAS',    '${DFILP}/${ENV_PREFIX}_ESFD3730_SII_RISKMARGIN_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_ASTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_STD',  'ESF_SII_RISKMARGIN_FROMEU',    '${DFILP}/${ENV_PREFIX}_ESFD3730_SII_RISKMARGIN_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_EUTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_RA_STD',  'ESF_SII_RISKMARGIN_FROMAM',    '${DFILP}/${ENV_PREFIX}_ESFD3730_SII_RISKMARGIN_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_AMTOLOCAL}.dat','I','')

			
		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17SQINV',  'I17S_OMG_RA_STD','')
			insert into BEST..TI17REQFNC values ('I17SQINVB',  'I17S_OMG_RA_STD','')
			insert into BEST..TI17REQFNC values ('I17SYINV',  'I17S_OMG_RA_STD','')
			insert into BEST..TI17REQFNC values ('I17SYINVB',  'I17S_OMG_RA_STD','')
			insert into BEST..TI17REQFNC values ('I17SQPOS',  'I17S_OMG_RA_STD','')
			insert into BEST..TI17REQFNC values ('I17SQPOSB',  'I17S_OMG_RA_STD','')
			insert into BEST..TI17REQFNC values ('I17SYPOS',  'I17S_OMG_RA_STD','')
			insert into BEST..TI17REQFNC values ('I17SYPOSB',  'I17S_OMG_RA_STD','')
			insert into BEST..TI17REQFNC values ('I17SMINV',  'I17S_OMG_RA_STD','')
			insert into BEST..TI17REQFNC values ('I17SQPOSP',  'I17S_OMG_RA_STD','')
			insert into BEST..TI17REQFNC values ('I17SYPOSP',  'I17S_OMG_RA_STD','')
go

