-------------------------------
--mapping of  ESPD3630 

	----------   Clean tables   ---------------------

	delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESPD3630')
	delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESPD3630')
	delete BEST..TI17FNC where CHAIN_CT='ESPD3630'
	delete BEST..TI17CHN  where CHAIN_CT='ESPD3630'

	insert into BEST..TI17CHN values ('ESPD3630',  'UPR cancellation job ESID3601A')

	----------IDF_CT:   EBS_ESPD3630 ------------------

		insert into BEST..TI17FNC values ('EBS_ESPD3630','Post omega EBS','ESPD3630',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630',  'EST_FDETTRS','${DFILP}/${ENV_PREFIX}_ESCJ0660_FDETTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630',  'EST_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630',  'EST_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630',  'EST_IGTAAF','${DFILP}/${ENV_PREFIX}_ESFD4050_FTECLEDA_I4I_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630',  'EPO_FTECLEDRSO','${DFILP}/${ENV_PREFIX}_ESFD4050_FTECLEDR_I4I_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630',  'EST_FTECLEDASO','${DFILP}/${ENV_PREFIX}_ESFD4050_FTECLEDA_I4I_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630',  'EST_DLSGTR','${DFILP}/${ENV_PREFIX}_ESPD1800_DLSGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630',  'EST_DLDGTAA','${DFILP}/${ENV_PREFIX}_ESFD2230_DLDGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630',  'EST_DLREGTR','${DFILP}/${ENV_PREFIX}_ESPD2550_DLREGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630',  'EST_DLRGTAA','${DFILP}/${ENV_PREFIX}_ESPD2550_DLRGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630',  'EST_DLSGTAA','${DFILP}/${ENV_PREFIX}_ESPD1800_DLSGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630',  'EST_DLSGTAR','${DFILP}/${ENV_PREFIX}_ESPD1800_DLSGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630',  'EST_DLREGTAR','${DFILP}/${ENV_PREFIX}_ESPD2550_DLREGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630',  'EST_DLASIIGTR','${DFILP}/${ENV_PREFIX}_ESPD3630_DLASIIGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630',  'EST_DLREMAJGTR','${DFILP}/${ENV_PREFIX}_ESPD2550_DLREMAJGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630',  'EST_DLREMAJGTAR','${DFILP}/${ENV_PREFIX}_ESPD2550_DLREMAJGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630',  'EST_FPLATXCUM','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLATXCUM_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630',  'EST_IRDPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5010_IRDPERICASE0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630',  'EST_IADPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5040_IADPERICASE_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630',  'EST_FTECLEDASII','`if [ "${TYPEINV}" = "POC" ];then echo ${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_EBS_POS_${PARM_ICLODAT_D}.dat;else echo ${DFILP}/empty.dat;fi;`','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630',  'EST_FTECLEDASIISO','`if [ "${TYPEINV}" = "POC" ];then echo ${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_EBS_POS_${PARM_ICLODAT_D}.dat;else echo ${DFILP}/empty.dat;fi;`','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630',  'EST_DLASIIGTAA','${DFILP}/${ENV_PREFIX}_ESPD3630_DLASIIGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630',  'EST_DLASIIGTAR','${DFILP}/${ENV_PREFIX}_ESPD3630_DLASIIGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('EBSEMINV',  'EBS_ESPD3630','Quarterly')
			insert into BEST..TI17REQFNC values ('EBSEQINV',  'EBS_ESPD3630','Quarterly')
			insert into BEST..TI17REQFNC values ('EBSEQPOC',  'EBS_ESPD3630','	Quarterly')
			insert into BEST..TI17REQFNC values ('EBSEQPOCB',  'EBS_ESPD3630','Quarterly')
			insert into BEST..TI17REQFNC values ('EBSEQPOS',  'EBS_ESPD3630','Quarterly')
			insert into BEST..TI17REQFNC values ('EBSEYINV',  'EBS_ESPD3630','Annual INV')
			insert into BEST..TI17REQFNC values ('EBSEYPOC',  'EBS_ESPD3630','Annual POC')
			insert into BEST..TI17REQFNC values ('EBSEYPOCB',  'EBS_ESPD3630','Annual POC')
			insert into BEST..TI17REQFNC values ('EBSEYPOS',  'EBS_ESPD3630','Annual POS')
			
			
			
----------IDF_CT:   EBS_ESPD3630_BBNI ------------------

		insert into BEST..TI17FNC values ('EBS_ESPD3630_BBNI','Post omega EBS','ESPD3630',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630_BBNI',  'EST_FDETTRS','${DFILP}/${ENV_PREFIX}_ESCJ0660_FDETTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630_BBNI',  'EST_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630_BBNI',  'EST_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630_BBNI',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630_BBNI',  'EST_IGTAAF','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630_BBNI',  'EPO_FTECLEDRSO','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630_BBNI',  'EST_FTECLEDASO','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630_BBNI',  'EST_DLSGTR','${DFILP}/${ENV_PREFIX}_ESPD1800_BBNI_DLSGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630_BBNI',  'EST_DLDGTAA','${DFILP}/${ENV_PREFIX}_ESFD2230_BBNI_DLDGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630_BBNI',  'EST_DLREGTR','${DFILP}/${ENV_PREFIX}_ESPD2550_BBNI_DLREGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630_BBNI',  'EST_DLRGTAA','${DFILP}/${ENV_PREFIX}_ESPD2550_BBNI_DLRGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630_BBNI',  'EST_DLSGTAA','${DFILP}/${ENV_PREFIX}_ESPD1800_BBNI_DLSGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630_BBNI',  'EST_DLSGTAR','${DFILP}/${ENV_PREFIX}_ESPD1800_BBNI_DLSGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630_BBNI',  'EST_DLREGTAR','${DFILP}/${ENV_PREFIX}_ESPD2550_BBNI_DLREGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630_BBNI',  'EST_DLASIIGTR','${DFILP}/${ENV_PREFIX}_ESPD3630_BBNI_DLASIIGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630_BBNI',  'EST_DLREMAJGTR','${DFILP}/${ENV_PREFIX}_ESPD2550_BBNI_DLREMAJGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630_BBNI',  'EST_DLREMAJGTAR','${DFILP}/${ENV_PREFIX}_ESPD2550_BBNI_DLREMAJGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630_BBNI',  'EST_FPLATXCUM','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLATXCUM_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630_BBNI',  'EST_IRDPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5060_IRDPERICASE_BBNI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')	
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630_BBNI',  'EST_IADPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5060_IADPERICASE_BBNI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')	
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630_BBNI',  'EST_FTECLEDASII','`if [ "${TYPEINV}" = "POC" ];then echo ${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_EBS_POS_${PARM_ICLODAT_D}.dat;else echo ${DFILP}/empty.dat;fi;`','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630_BBNI',  'EST_FTECLEDASIISO','`if [ "${TYPEINV}" = "POC" ];then echo ${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_EBS_POS_${PARM_ICLODAT_D}.dat;else echo ${DFILP}/empty.dat;fi;`','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630_BBNI',  'EST_DLASIIGTAA','${DFILP}/${ENV_PREFIX}_ESPD3630_BBNI_DLASIIGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630_BBNI',  'EST_DLASIIGTAR','${DFILP}/${ENV_PREFIX}_ESPD3630_BBNI_DLASIIGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('EBSEMINV',  'EBS_ESPD3630_BBNI','Quarterly')
			insert into BEST..TI17REQFNC values ('EBSEQINV',  'EBS_ESPD3630_BBNI','Quarterly')
			insert into BEST..TI17REQFNC values ('EBSEQPOC',  'EBS_ESPD3630_BBNI','	Quarterly')
			insert into BEST..TI17REQFNC values ('EBSEQPOCB',  'EBS_ESPD3630_BBNI','Quarterly')
			insert into BEST..TI17REQFNC values ('EBSEQPOS',  'EBS_ESPD3630_BBNI','Quarterly')
			insert into BEST..TI17REQFNC values ('EBSEYINV',  'EBS_ESPD3630_BBNI','Annual INV')
			insert into BEST..TI17REQFNC values ('EBSEYPOC',  'EBS_ESPD3630_BBNI','Annual POC')
			insert into BEST..TI17REQFNC values ('EBSEYPOCB',  'EBS_ESPD3630_BBNI','Annual POC')
			insert into BEST..TI17REQFNC values ('EBSEYPOS',  'EBS_ESPD3630_BBNI','Annual POS')  
			
----------IDF_CT:   EBS_ESPD3630_INI ------------------

		insert into BEST..TI17FNC values ('EBS_ESPD3630_INI','Post omega EBS','ESPD3630',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630_INI',  'EST_FDETTRS','${DFILP}/${ENV_PREFIX}_ESCJ0660_FDETTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630_INI',  'EST_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630_INI',  'EST_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630_INI',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630_INI',  'EST_IGTAAF','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630_INI',  'EPO_FTECLEDRSO','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630_INI',  'EST_FTECLEDASO','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630_INI',  'EST_DLSGTR','${DFILP}/${ENV_PREFIX}_ESPD1800_INI_DLSGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630_INI',  'EST_DLDGTAA','${DFILP}/${ENV_PREFIX}_ESFD2230_INI_DLDGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630_INI',  'EST_DLREGTR','${DFILP}/${ENV_PREFIX}_ESPD2550_INI_DLREGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630_INI',  'EST_DLRGTAA','${DFILP}/${ENV_PREFIX}_ESPD2550_INI_DLRGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630_INI',  'EST_DLSGTAA','${DFILP}/${ENV_PREFIX}_ESPD1800_INI_DLSGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630_INI',  'EST_DLSGTAR','${DFILP}/${ENV_PREFIX}_ESPD1800_INI_DLSGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630_INI',  'EST_DLREGTAR','${DFILP}/${ENV_PREFIX}_ESPD2550_INI_DLREGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630_INI',  'EST_DLASIIGTR','${DFILP}/${ENV_PREFIX}_ESPD3630_INI_DLASIIGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630_INI',  'EST_DLREMAJGTR','${DFILP}/${ENV_PREFIX}_ESPD2550_INI_DLREMAJGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630_INI',  'EST_DLREMAJGTAR','${DFILP}/${ENV_PREFIX}_ESPD2550_INI_DLREMAJGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630_INI',  'EST_FPLATXCUM','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLATXCUM_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630_INI',  'EST_IRDPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5060_IRDPERICASE_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')	
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630_INI',  'EST_IADPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5060_IADPERICASE_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')	
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630_INI',  'EST_FTECLEDASII','`if [ "${TYPEINV}" = "POC" ];then echo ${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_EBS_POS_${PARM_ICLODAT_D}.dat;else echo ${DFILP}/empty.dat;fi;`','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630_INI',  'EST_FTECLEDASIISO','`if [ "${TYPEINV}" = "POC" ];then echo ${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_EBS_POS_${PARM_ICLODAT_D}.dat;else echo ${DFILP}/empty.dat;fi;`','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630_INI',  'EST_DLASIIGTAA','${DFILP}/${ENV_PREFIX}_ESPD3630_INI_DLASIIGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3630_INI',  'EST_DLASIIGTAR','${DFILP}/${ENV_PREFIX}_ESPD3630_INI_DLASIIGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('EBSEMINV',  'EBS_ESPD3630_INI','Quarterly')
			insert into BEST..TI17REQFNC values ('EBSEQINV',  'EBS_ESPD3630_INI','Quarterly')
			insert into BEST..TI17REQFNC values ('EBSEQPOC',  'EBS_ESPD3630_INI','	Quarterly')
			insert into BEST..TI17REQFNC values ('EBSEQPOCB',  'EBS_ESPD3630_INI','Quarterly')
			insert into BEST..TI17REQFNC values ('EBSEQPOS',  'EBS_ESPD3630_INI','Quarterly')
			insert into BEST..TI17REQFNC values ('EBSEYINV',  'EBS_ESPD3630_INI','Annual INV')
			insert into BEST..TI17REQFNC values ('EBSEYPOC',  'EBS_ESPD3630_INI','Annual POC')
			insert into BEST..TI17REQFNC values ('EBSEYPOCB',  'EBS_ESPD3630_INI','Annual POC')
			insert into BEST..TI17REQFNC values ('EBSEYPOS',  'EBS_ESPD3630_INI','Annual POS')  
			
go

