-------------------------------
--mapping of  ESID2500

	----------   Clean tables   ---------------------

	delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESID2500')
	delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESID2500')
	delete BEST..TI17FNC where CHAIN_CT='ESID2500'
	delete BEST..TI17CHN  where CHAIN_CT='ESID2500'

	insert into BEST..TI17CHN values ('ESID2500',  '')

	----------IDF_CT:   ESID2500 ------------------

		insert into BEST..TI17FNC values ('ESID2500',' ','ESID2500',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('ESID2500',  'EST_FDETTRS','${DFILP}/${ENV_PREFIX}_ESCJ0060_FDETTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2500',  'EST_FTRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2500',  'EST_FCURCVSN','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURCVSN.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2500',  'EST_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2500',  'EST_FCURCVSNI','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURCVSNI.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2500',  'EST_FTRANSCODE','${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRANSCODE.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2500',  'EST_IGTAAF','${DFILP}/${ENV_PREFIX}_ESID0560_IGTAAF_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2500',  'EST_MVTPNA','${DFILP}/${ENV_PREFIX}_ESID0560_MVTPNA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2500',  'EST_DLDGTAA','${DFILP}/${ENV_PREFIX}_ESID2000_DLDGTAA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2500',  'EST_DLRGTAA','${DFILI}/${ENV_PREFIX}_ESID2050_DLRGTAA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2500',  'EST_FRETPAR','${DFILP}/${ENV_PREFIX}_ESCJ0060_FRETPAR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2500',  'EST_FOUTTRAA','${DFILP}/${ENV_PREFIX}_ESID0560_FOUTTRAA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2500',  'EST_FOUTTRAI','${DFILP}/${ENV_PREFIX}_ESID0560_FOUTTRAI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2500',  'EST_IADVPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_IADVPERICASE_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2500',  'EST_IRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_IRDVPERICASE_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2500',  'EST_DLREGTR_PC','${DFILP}/${ENV_PREFIX}_ESID2500_I4_PC___DLREGTR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2500',  'EST_DLRGTAA_PC','${DFILP}/${ENV_PREFIX}_ESID2050_I4_PC___DLRGTAA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2500',  'EST_FCES','${DFILP}/${ENV_PREFIX}_ESID2500_FCES_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2500',  'EST_FPLC','${DFILP}/${ENV_PREFIX}_ESID2500_FPLC_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2500',  'EST_DLREGTR','${DFILP}/${ENV_PREFIX}_ESID2500_DLREGTR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2500',  'EST_DLRPGTR','${DFILP}/${ENV_PREFIX}_ESID2500_DLRPGTR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2500',  'EST_DLRTGTR','${DFILP}/${ENV_PREFIX}_ESID2500_DLRTGTR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2500',  'EST_DLREGTAR','${DFILP}/${ENV_PREFIX}_ESID2500_DLREGTAR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2500',  'EST_DLRPGTAR','${DFILP}/${ENV_PREFIX}_ESID2500_DLRPGTAR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2500',  'EST_DLRTCGTR','${DFILP}/${ENV_PREFIX}_ESID2500_DLRTCGTR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2500',  'EST_DLRTFGTR','${DFILP}/${ENV_PREFIX}_ESID2500_DLRTFGTR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2500',  'EST_DLRTGTAR','${DFILP}/${ENV_PREFIX}_ESID2500_DLRTGTAR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2500',  'EST_FCES_NEW','${DFILP}/${ENV_PREFIX}_ESID2500_FCES_NEW_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2500',  'EST_DLRTCGTAR','${DFILP}/${ENV_PREFIX}_ESID2500_DLRTCGTAR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2500',  'EST_DLRTFGTAR','${DFILP}/${ENV_PREFIX}_ESID2500_DLRTFGTAR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2500',  'EST_DLREMAJGTR','${DFILP}/${ENV_PREFIX}_ESID2500_DLREMAJGTR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2500',  'EST_DLREMAJGTAR','${DFILP}/${ENV_PREFIX}_ESID2500_DLREMAJGTAR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2500',  'EST_FBESTCONPAR','${DFILP}/${ENV_PREFIX}_ESID2500_FBESTCONPAR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2500',  'EST_FBESTCESSION','${DFILP}/${ENV_PREFIX}_ESID2500_FBESTCESSION_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2500',  'EST_DLREMAJGTR_PC','${DFILP}/${ENV_PREFIX}_ESID2500_I4_PC___DLREMAJGTR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I4IMINV',  'ESID2500','')
			insert into BEST..TI17REQFNC values ('I4IQINV',  'ESID2500','@variante')
			insert into BEST..TI17REQFNC values ('I4IYINV',  'ESID2500','@variante')
go

