-------------------------------
--mapping of  ESFD5050

	----------   Clean tables   ---------------------

	delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD5050')
	delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD5050')
	delete BEST..TI17FNC where CHAIN_CT='ESFD5050'
	delete BEST..TI17CHN  where CHAIN_CT='ESFD5050'

	insert into BEST..TI17CHN values ('ESFD5050',  'Simul')

	----------IDF_CT:   I17S_ESFD5050 ------------------

		insert into BEST..TI17FNC values ('I17S_ESFD5050','Simul','ESFD5050',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'EST_FCES','${DFILP}/${ENV_PREFIX}_ESFD5010_I17G_MRG_PER_INI_FCES_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'EST_FPLC','${DFILP}/${ENV_PREFIX}_ESFD5010_I17G_MRG_PER_INI_FPLC_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'EST_FTECLEDA_REJ_PREV','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDA_REJ_I17S_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'EST_FTECLEDR_REJ_PREV','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDR_REJ_I17S_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'EST_TRERETFACCTR','${DFILP}/${ENV_PREFIX}_ESFD1130_TRERETFACCTR_I17G_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'EST_FCES_5040','${DFILP}/${ENV_PREFIX}_ESFD5040_I17G_MRG_FUT_INI_FCES_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'EST_FTECLEDA_OPNG_PREV','${DFILP}/${ENV_PREFIX}_ESFD2900_FTECLEDA_OPNG_I17S_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'EST_FTECLEDR_OPNG_PREV','${DFILP}/${ENV_PREFIX}_ESFD2900_FTECLEDR_OPNG_I17S_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'EST_FCTRGRO','${DFILP}/${ENV_PREFIX}_ESFD5010_I17G_MRG_PER_INI_FCTRGRO_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'EST_FPLACEMT0','${DFILP}/${ENV_PREFIX}_ESFD5010_I17G_MRG_PER_INI_FPLACEMT0_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'EST_FPLATXCUM','${DFILP}/${ENV_PREFIX}_ESFD5010_I17G_MRG_PER_INI_FPLATXCUM_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'EST_IADPERIFR','${DFILP}/${ENV_PREFIX}_ESFD5010_I17G_MRG_PER_INI_IADPERIFR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'EST_FI17CLOPER','${DFILP}/${ENV_PREFIX}_ESFD1130_FI17CLOPER_I17S_DSC_ALL_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'EST_IADPERIFCI','${DFILP}/${ENV_PREFIX}_ESFD5010_I17G_MRG_PER_INI_IADPERIFCI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'EST_IADPERIFCT','${DFILP}/${ENV_PREFIX}_ESFD5010_I17G_MRG_PER_INI_IADPERIFCT_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'EST_FSEGPATTERNDSCf17','${DFILP}/${ENV_PREFIX}_ESFD1130_FSEGPATTERNDSCf17_I17G_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'EST_IADPERIFR_5040','${DFILP}/${ENV_PREFIX}_ESFD5040_I17G_MRG_FUT_INI_IADPERIFR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'EST_FPLATXCUMALL','${DFILP}/${ENV_PREFIX}_ESFD5010_I17G_MRG_PER_INI_FPLATXCUMALL_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'EST_IADPERIFCI_5040','${DFILP}/${ENV_PREFIX}_ESFD5040_I17G_MRG_FUT_INI_IADPERIFCI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'EST_IADPERIFCT_5040','${DFILP}/${ENV_PREFIX}_ESFD5040_I17G_MRG_FUT_INI_IADPERIFCT_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'EST_FSEGPROF_STD_PREVIOUS','${DFILP}/${ENV_PREFIX}_ESFD3760_I17G_UOA_PRO_STD_FSEGPROF_POS_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'EST_FLORETFACTOR_INI','${DFILP}/${ENV_PREFIX}_ESFD5010_I17G_MRG_PER_INI_FLORETFACTOR_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'EST_GTSII_DAC_LKI_PREV','${DFILP}/${ENV_PREFIX}_ESFD3640_I17G_IVR_CHR_STD_DAC_LKI_CASHFLOW_POS_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'EST_SECIFRS_CR_EXTRACT','${DFILP}/${ENV_PREFIX}_ESFD1130_SECIFRS_CR_EXTRACT_I17G_DSC_ALL_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'EST_GTSII_ESCOMPTE_PREVCLODAT','${DFILP}/${ENV_PREFIX}_ESFD3620_I17G_DSC_LKI_STD_GTSII_ESCOMPTE_POS_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'EST_GTSII_CSM_CASHFLOW_PREV','${DFILP}/${ENV_PREFIX}_ESFD3760_I17G_UOA_PRO_STD_GTSII_CSM_CASHFLOW_POS_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'EST_GTSII_ESCOMPTE_RAD_PREVCLODAT','${DFILP}/${ENV_PREFIX}_ESFD3620_I17G_RAD_DSI_STD_GTSII_ESCOMPTE_POS_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'EST_GTSII_GLOBAL_CASHFLOW_RAD_PREV','${DFILP}/${ENV_PREFIX}_ESFD3650_I17G_RAD_CUR_STD_GTSII_CASHFLOW_POS_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'EST_GTSII_GLOBAL_CASHFLOW_PREV','${DFILP}/${ENV_PREFIX}_ESFD3630_I17G_IEX_ALL_STD_GTSII_GLOBAL_CASHFLOW_POS_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'ESF_FCES','${DFILP}/${ENV_PREFIX}_ESFD5010_I17S_MRG_PER_INI_FCES_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'ESF_FPLC','${DFILP}/${ENV_PREFIX}_ESFD5010_I17S_MRG_PER_INI_FPLC_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'ESF_FTECLEDA_REJ_PREV','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDA_REJ_I17S_${PARM_PREV_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'ESF_FTECLEDR_REJ_PREV','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDR_REJ_I17S_${PARM_PREV_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'ESF_TRERETFACCTR','${DFILP}/${ENV_PREFIX}_ESFD1130_TRERETFACCTR_I17S_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'ESF_FCES_5040','${DFILP}/${ENV_PREFIX}_ESFD5040_I17S_MRG_FUT_INI_FCES_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'ESF_FTECLEDA_OPNG_PREV','${DFILP}/${ENV_PREFIX}_ESFD2900_FTECLEDA_OPNG_I17S_${PARM_PREV_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'ESF_FTECLEDR_OPNG_PREV','${DFILP}/${ENV_PREFIX}_ESFD2900_FTECLEDR_OPNG_I17S_${PARM_PREV_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'ESF_FCTRGRO','${DFILP}/${ENV_PREFIX}_ESFD5010_I17S_MRG_PER_INI_FCTRGRO_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'ESF_FPLACEMT0','${DFILP}/${ENV_PREFIX}_ESFD5010_I17S_MRG_PER_INI_FPLACEMT0_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'ESF_FPLATXCUM','${DFILP}/${ENV_PREFIX}_ESFD5010_I17S_MRG_PER_INI_FPLATXCUM_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'ESF_IADPERIFR','${DFILP}/${ENV_PREFIX}_ESFD5010_I17S_MRG_PER_INI_IADPERIFR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'ESF_IADPERIFCI','${DFILP}/${ENV_PREFIX}_ESFD5010_I17S_MRG_PER_INI_IADPERIFCI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'ESF_IADPERIFCT','${DFILP}/${ENV_PREFIX}_ESFD5010_I17S_MRG_PER_INI_IADPERIFCT_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'ESF_FSEGPATTERNDSCf17','${DFILP}/${ENV_PREFIX}_ESFD1130_FSEGPATTERNDSCf17_I17S_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'ESF_IADPERIFR_5040','${DFILP}/${ENV_PREFIX}_ESFD5040_I17S_MRG_FUT_INI_IADPERIFR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'ESF_FPLATXCUMALL','${DFILP}/${ENV_PREFIX}_ESFD5010_I17S_MRG_PER_INI_FPLATXCUMALL_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'ESF_IADPERIFCI_5040','${DFILP}/${ENV_PREFIX}_ESFD5040_I17S_MRG_FUT_INI_IADPERIFCI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'ESF_IADPERIFCT_5040','${DFILP}/${ENV_PREFIX}_ESFD5040_I17S_MRG_FUT_INI_IADPERIFCT_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'ESF_FSEGPROF_STD_PREVIOUS','${DFILP}/${ENV_PREFIX}_ESFD3760_I17S_UOA_PRO_STD_FSEGPROF_POS_${PARM_PREV_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'ESF_FLORETFACTOR_INI','${DFILP}/${ENV_PREFIX}_ESFD5010_I17S_MRG_PER_INI_FLORETFACTOR_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'ESF_GTSII_DAC_LKI_PREV','${DFILP}/${ENV_PREFIX}_ESFD3640_I17S_IVR_CHR_STD_DAC_LKI_CASHFLOW_POS_${PARM_PREV_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'ESF_SECIFRS_CR_EXTRACT','${DFILP}/${ENV_PREFIX}_ESFD1130_SECIFRS_CR_EXTRACT_I17S_DSC_ALL_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'ESF_GTSII_ESCOMPTE_PREVCLODAT','${DFILP}/${ENV_PREFIX}_ESFD3620_I17S_DSC_LKI_STD_GTSII_ESCOMPTE_POS_${PARM_PREV_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'ESF_GTSII_CSM_CASHFLOW_PREV','${DFILP}/${ENV_PREFIX}_ESFD3760_I17S_UOA_PRO_STD_GTSII_CSM_CASHFLOW_POS_${PARM_PREV_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'ESF_GTSII_ESCOMPTE_RAD_PREVCLODAT','${DFILP}/${ENV_PREFIX}_ESFD3620_I17S_RAD_DSI_STD_GTSII_ESCOMPTE_POS_${PARM_PREV_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'ESF_GTSII_GLOBAL_CASHFLOW_RAD_PREV','${DFILP}/${ENV_PREFIX}_ESFD3650_I17S_RAD_CUR_STD_GTSII_CASHFLOW_POS_${PARM_PREV_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD5050',  'ESF_GTSII_GLOBAL_CASHFLOW_PREV','${DFILP}/${ENV_PREFIX}_ESFD3630_I17S_IEX_ALL_STD_GTSII_GLOBAL_CASHFLOW_POS_${PARM_PREV_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17SMINV',  'I17S_ESFD5050','')
			insert into BEST..TI17REQFNC values ('I17SQINV',  'I17S_ESFD5050','')
			insert into BEST..TI17REQFNC values ('I17SQPOS',  'I17S_ESFD5050','')
			insert into BEST..TI17REQFNC values ('I17SYINV',  'I17S_ESFD5050','')
			insert into BEST..TI17REQFNC values ('I17SYPOS',  'I17S_ESFD5050','')
go

