
use BEST
go

drop table  TI17PERMFIL_3K  
go
select * into  BEST..TI17PERMFIL_3K from BEST..TI17PERMFIL

ALTER TABLE dbo.TI17PERMFIL_3K
    ADD CONSTRAINT FK_FNCT_PERM_3K
    FOREIGN KEY (IDF_CT)
    REFERENCES dbo.TI17FNC (IDF_CT)
go
GRANT REFERENCES ON dbo.TI17PERMFIL_3K TO GOMEGA
go
GRANT REFERENCES ON dbo.TI17PERMFIL_3K TO GDBBATCH
go
GRANT SELECT ON dbo.TI17PERMFIL_3K TO GCONSULT
go
GRANT SELECT ON dbo.TI17PERMFIL_3K TO GOMEGA
go
GRANT SELECT ON dbo.TI17PERMFIL_3K TO GDBBATCH
go
GRANT INSERT ON dbo.TI17PERMFIL_3K TO GOMEGA
go
GRANT INSERT ON dbo.TI17PERMFIL_3K TO GDBBATCH
go
GRANT DELETE ON dbo.TI17PERMFIL_3K TO GOMEGA
go
GRANT DELETE ON dbo.TI17PERMFIL_3K TO GDBBATCH
go
GRANT UPDATE ON dbo.TI17PERMFIL_3K TO GOMEGA
go
GRANT UPDATE ON dbo.TI17PERMFIL_3K TO GDBBATCH
go



select * from BEST..TI17PERMFIL where  PATHPATTRN_LL like '%_ESCJ0060_FBOPRSLNK[_]%' and PATHPATTRN_LL not like  '%ESCJ0060_FBOPRSLNK_TXT%'
update BEST..TI17PERMFIL_3K set PATHPATTRN_LL ="${DFILP}/${ENV_PREFIX}_ESCJ0060_FBOPRSLNK.dat"  where  PATHPATTRN_LL like '%_ESCJ0060_FBOPRSLNK[_]%' and PATHPATTRN_LL not like  '%ESCJ0060_FBOPRSLNK_TXT%'
select * from BEST..TI17PERMFIL_3K where  PATHPATTRN_LL like '%_ESCJ0060_FBOPRSLNK.dat' and PATHPATTRN_LL not like  '%ESCJ0060_FBOPRSLNK_TXT%'

select * from BEST..TI17PERMFIL where  PATHPATTRN_LL like '%ESCJ0060_FBOPRSLNK_TXT[_]%' 
update BEST..TI17PERMFIL_3K set PATHPATTRN_LL ="${DFILP}/${ENV_PREFIX}_ESCJ0060_FBOPRSLNK_TXT.dat"  where  PATHPATTRN_LL like  '%ESCJ0060_FBOPRSLNK_TXT%' 
select * from BEST..TI17PERMFIL_3K where PATHPATTRN_LL like  '%ESCJ0060_FBOPRSLNK_TXT.dat' 


select * from BEST..TI17PERMFIL where  PATHPATTRN_LL like '%_ESCJ0060_FCURCVSN[_]%' 
update BEST..TI17PERMFIL_3K set PATHPATTRN_LL ="${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURCVSN.dat"  where  PATHPATTRN_LL like  '%_ESCJ0060_FCURCVSN[_]%' 
select * from BEST..TI17PERMFIL_3K where PATHPATTRN_LL like  '%_ESCJ0060_FCURCVSN.dat' 



select * from BEST..TI17PERMFIL where  PATHPATTRN_LL like '%_ESCJ0060_FCURCVSNI[_]%' 
update BEST..TI17PERMFIL_3K set PATHPATTRN_LL ="${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURCVSNI.dat"  where  PATHPATTRN_LL like  '%_ESCJ0060_FCURCVSNI[_]%' 
select * from BEST..TI17PERMFIL_3K where PATHPATTRN_LL like  '%_ESCJ0060_FCURCVSNI.dat' 


select * from BEST..TI17PERMFIL where  PATHPATTRN_LL like '%_ESCJ0060_FCURQUOT[_]%' and PATHPATTRN_LL not like  '%_ESCJ0060_FCURQUOT_TXT%'
update BEST..TI17PERMFIL_3K set PATHPATTRN_LL ="${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURQUOT.dat"  where  PATHPATTRN_LL like '%_ESCJ0060_FCURQUOT[_]%' and PATHPATTRN_LL not like  '%_ESCJ0060_FCURQUOT_TXT%'
select * from BEST..TI17PERMFIL_3K where  PATHPATTRN_LL like '%_ESCJ0060_FCURQUOT.dat' and PATHPATTRN_LL not like  '%ESCJ0060_FBOPRSLNK_TXT%'


select * from BEST..TI17PERMFIL where  PATHPATTRN_LL like '%_ESCJ0060_FCURQUOT_TXT[_]%'
update BEST..TI17PERMFIL_3K set PATHPATTRN_LL ="${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURQUOT_TXT.dat"  where  PATHPATTRN_LL like '%_ESCJ0060_FCURQUOT_TXT[_]%' 
select * from BEST..TI17PERMFIL_3K where  PATHPATTRN_LL like '%_ESCJ0060_FCURQUOT_TXT.dat' 


select * from BEST..TI17PERMFIL where  PATHPATTRN_LL like '%_ESCJ0060_FDETTRS[_]%' 
update BEST..TI17PERMFIL_3K set PATHPATTRN_LL ="${DFILP}/${ENV_PREFIX}_ESCJ0060_FDETTRS.dat"  where  PATHPATTRN_LL like  '%_ESCJ0060_FDETTRS[_]%' 
select * from BEST..TI17PERMFIL_3K where PATHPATTRN_LL like  '%_ESCJ0060_FDETTRS.dat' 

select * from BEST..TI17PERMFIL where  PATHPATTRN_LL like '%_ESCJ0060_FLIBEL2[_]%' 
update BEST..TI17PERMFIL_3K set PATHPATTRN_LL ="${DFILP}/${ENV_PREFIX}_ESCJ0060_FLIBEL2.dat"  where  PATHPATTRN_LL like  '%_ESCJ0060_FLIBEL2[_]%' 
select * from BEST..TI17PERMFIL_3K where PATHPATTRN_LL like  '%_ESCJ0060_FLIBEL2.dat' 


select * from BEST..TI17PERMFIL where  PATHPATTRN_LL like '%_ESCJ0060_FPRSMAP[_]%' 
update BEST..TI17PERMFIL_3K set PATHPATTRN_LL ="${DFILP}/${ENV_PREFIX}_ESCJ0060_FPRSMAP.dat"  where  PATHPATTRN_LL like  '%_ESCJ0060_FPRSMAP[_]%' 
select * from BEST..TI17PERMFIL_3K where PATHPATTRN_LL like  '%_ESCJ0060_FPRSMAP.dat' 

select * from BEST..TI17PERMFIL where  PATHPATTRN_LL like '%_ESCJ0060_FSUBTRS[_]%' 
update BEST..TI17PERMFIL_3K set PATHPATTRN_LL ="${DFILP}/${ENV_PREFIX}_ESCJ0060_FSUBTRS.dat"  where  PATHPATTRN_LL like  '%_ESCJ0060_FSUBTRS[_]%' 
select * from BEST..TI17PERMFIL_3K where PATHPATTRN_LL like  '%_ESCJ0060_FSUBTRS.dat' 

select * from BEST..TI17PERMFIL where  PATHPATTRN_LL like '%_ESCJ0060_FTFAMCHG[_]%' 
update BEST..TI17PERMFIL_3K set PATHPATTRN_LL ="${DFILP}/${ENV_PREFIX}_ESCJ0060_FTFAMCHG.dat"  where  PATHPATTRN_LL like  '%_ESCJ0060_FTFAMCHG[_]%' 
select * from BEST..TI17PERMFIL_3K where PATHPATTRN_LL like  '%_ESCJ0060_FTFAMCHG.dat' 


select * from BEST..TI17PERMFIL where  PATHPATTRN_LL like '%_ESCJ0060_FTRANSCODE[_]%' 
update BEST..TI17PERMFIL_3K set PATHPATTRN_LL ="${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRANSCODE.dat"  where  PATHPATTRN_LL like  '%_ESCJ0060_FTRANSCODE[_]%' 
select * from BEST..TI17PERMFIL_3K where PATHPATTRN_LL like  '%_ESCJ0060_FTRANSCODE.dat' 

select * from BEST..TI17PERMFIL where  PATHPATTRN_LL like '%_ESCJ0060_FTRSLNK_TXT[_]%' 
update BEST..TI17PERMFIL_3K set PATHPATTRN_LL ="${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRSLNK_TXT.dat"  where  PATHPATTRN_LL like  '%_ESCJ0060_FTRSLNK_TXT[_]%' 
select * from BEST..TI17PERMFIL_3K where PATHPATTRN_LL like  '%_ESCJ0060_FTRSLNK_TXT.dat' 

select * from BEST..TI17PERMFIL where  PATHPATTRN_LL like '%_ESCJ0060_FTRSLNK[_]%' and    PATHPATTRN_LL not like  '%_ESCJ0060_FTRSLNK_TXT%' 
update BEST..TI17PERMFIL_3K set PATHPATTRN_LL ="${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRSLNK.dat"  where  PATHPATTRN_LL like  '%_ESCJ0060_FTRSLNK[_]%'  and  PATHPATTRN_LL not like  '%_ESCJ0060_FTRSLNK_TXT%'
select * from BEST..TI17PERMFIL_3K where PATHPATTRN_LL like  '%_ESCJ0060_FTRSLNK.dat' and PATHPATTRN_LL not like  '%_ESCJ0060_FTRSLNK_TXT%'

select * from BEST..TI17PERMFIL where  PATHPATTRN_LL like "%ES_D8830_FTECLEDA_I4I%"
update BEST..TI17PERMFIL_3K set PATHPATTRN_LL ="${DFILP}/${ENV_PREFIX}_ES${PARM_FTECLED}D8830_FTECLEDA_I4I_${PARM_ICLODAT_D}.dat"  where  PATHPATTRN_LL like "%ES_D8830_FTECLEDA_I4I%"
select * from BEST..TI17PERMFIL_3K where PATHPATTRN_LL like  '%ES%D8830_FTECLEDA%' 

select * from BEST..TI17PERMFIL  where IDF_CT ="ESID8700_I4_PC___" and PERMFIL_CT ="EST_FTECLEDA_EBS"
delete BEST..TI17PERMFIL_3K where IDF_CT ="ESID8700_I4_PC___" and PERMFIL_CT ="EST_FTECLEDA_EBS"
insert into BEST..TI17PERMFIL_3K values ('ESID8700_I4_PC___',  'EST_FTECLEDA_EBS',"${DFILP}/${ENV_PREFIX}_ESID8700_FTECLEDA_I4I_${PARM_ICLODAT_D}.dat",'O','')
select * from BEST..TI17PERMFIL_3K  where IDF_CT ="ESID8700_I4_PC___" and PERMFIL_CT ="EST_FTECLEDA_EBS"

select * from BEST..TI17PERMFIL where IDF_CT ="ESID8700_I4_PC___" and PERMFIL_CT ="EST_OIADVPERICASE"
delete BEST..TI17PERMFIL_3K where IDF_CT ="ESID8700_I4_PC___" and PERMFIL_CT ="EST_OIADVPERICASE"
insert into BEST..TI17PERMFIL_3K values ('ESID8700_I4_PC___',  'EST_OIADVPERICASE',"${DFILP}/${ENV_PREFIX}_ESID0560_OIADVPERICASE_INV_${PARM_ICLODAT_D}.dat",'O','')
select * from BEST..TI17PERMFIL_3K where IDF_CT ="ESID8700_I4_PC___" and PERMFIL_CT ="EST_OIADVPERICASE"


select * from BEST..TI17PERMFIL_3K where IDF_CT like "%ESPD8700" and PERMFIL_CT ="EPO_FTECLEDASO_EBS"
delete BEST..TI17PERMFIL_3K where IDF_CT ="ESPD8700" and PERMFIL_CT ="EPO_FTECLEDASO_EBS"
insert into BEST..TI17PERMFIL_3K values ('ESPD8700',  'EPO_FTECLEDASO_EBS',"${DFILP}/${ENV_PREFIX}_ES${PARM_FTECLED}D8700_FTECLEDA_I4I_${PARM_ICLODAT_D}.dat" ,'O','')
select * from BEST..TI17PERMFIL_3K where IDF_CT like "%ESPD8700" and PERMFIL_CT ="EPO_FTECLEDASO_EBS"


select * from BEST..TI17PERMFIL_3K where IDF_CT like "%ESPD8700" and PERMFIL_CT ="EPO_OIADVPERICASE"
delete BEST..TI17PERMFIL_3K where IDF_CT ="ESPD8700" and PERMFIL_CT ="EST_OIADVPERICASE"
insert into BEST..TI17PERMFIL_3K values ('ESPD8700',  'EPO_OIADVPERICASE',"${DFILP}/${ENV_PREFIX}_ESID0560_OIADVPERICASE_INV_${PARM_ICLODAT_D}.dat" ,'I','')
select * from BEST..TI17PERMFIL_3K where IDF_CT like "%ESPD8700" and PERMFIL_CT ="EPO_OIADVPERICASE"

select * from BEST..TI17PERMFIL where  PATHPATTRN_LL like "%ES[IP]D3800_FTECLEDR_I4I%${PARM_ICLODAT_D}%" 
update BEST..TI17PERMFIL_3K set PATHPATTRN_LL ="${DFILP}/${ENV_PREFIX}_ES${PARM_FTECLED}D3800_FTECLEDR_I4I_${PARM_ICLODAT_D}.dat"  where  PATHPATTRN_LL like  "%ES[IP]D3800_FTECLEDR_I4I%${PARM_ICLODAT_D}%"
select * from BEST..TI17PERMFIL_3K where PATHPATTRN_LL like  "%ES%D3800_FTECLEDR_I4I%${PARM_ICLODAT_D}%" 


select * from BEST..TI17PERMFIL where  PATHPATTRN_LL like "%ES[IP]D3800_FTECLEDR_I4I%${PARM_PREV_ICLODAT_D}%" 
update BEST..TI17PERMFIL_3K set PATHPATTRN_LL ="${DFILP}/${ENV_PREFIX}_ES${PARM_FTECLED}D3800_FTECLEDR_I4I_${PARM_PREV_ICLODAT_D}.dat"  where  PATHPATTRN_LL like  "%ES[IP]D3800_FTECLEDR_I4I%${PARM_PREV_ICLODAT_D}%"
select * from BEST..TI17PERMFIL_3K where PATHPATTRN_LL like  "%ES%D3800_FTECLEDR_I4I%${PARM_PREV_ICLODAT_D}%" 

select * from BEST..TI17PERMFIL  where  PATHPATTRN_LL like "%ESID2040_DLVGTAR%"  and IDF_CT ="ESID2560"
update BEST..TI17PERMFIL_3K set PATHPATTRN_LL ="`ls -rt ${DFILP}/${ENV_PREFIX}_ESID2040_DLVGTAR_PC_${PARM_ICLODAT_D}_*.dat | tail -1 `"   where  PATHPATTRN_LL like "%ESID2040_DLVGTAR%"  and IDF_CT ="ESID2560"
select * from BEST..TI17PERMFIL_3K  where  PATHPATTRN_LL like "%ESID2040_DLVGTAR%"  and IDF_CT ="ESID2560"

go


 

-- pLANIFICATION EBSEMINV
--select application , job  from  BTRAV..UAT_VTOM_CLOS i where Application like '%EBS%' and application not like "EOMA_MIC%" order by 2 --
--select * from BEST..TI17REQCHN where REQCOD_CT = "EBSEQPOS" and IDF_Ct like "EBS_%" order by chain_ct
--select * from BEST..TI17REQ where REQCOD_CT ='EBSEMINV' 
--select * from BEST..TI17REQCHN where REQCOD_CT = "EBSEMINV"
--select * from BEST..TI17REQCHN where REQCOD_CT like "%POC"
--select * from BEST..TI17REQCHN where REQCOD_CT = "I4IMINV"
--select * from BEST..TI17REQCHN where REQCOD_CT = "I4IQPOS"
--select * from BEST..TI17REQCHN where REQCOD_CT = "I4IQINV"


if not exists ( select 1 from BEST..TI17REQ where REQCOD_CT ='EBSEMINV'  ) insert into BEST..TI17REQ values ('EBSEMINV',  'Monthly INV EBS')

delete  BEST..TI17REQCHN where REQCOD_CT = "EBSEMINV"

insert into  BEST..TI17REQCHN
select "EBSEMINV", CHAIN_CT, IDF_CT,  REQST_CHAIN_LL from BEST..TI17REQCHN where REQCOD_CT = "EBSEQPOS" and IDF_Ct like "EBS_%" order by chain_ct

/*
--- Correction ESPD3711
select * from BEST..TI17PERMFIL_3K   where  PERMFIL_CT=  'EPO_FTRSLNK' and    IDF_CT = 'EBS_ESPD3710'
update BEST..TI17PERMFIL_3K  
set     PERMFIL_CT=  'EPO_FTRSLNK_TXT', 
        PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRSLNK_TXT.dat'
where  PERMFIL_CT=  'EPO_FTRSLNK' 
and    IDF_CT = 'EBS_ESPD3710'
select * from BEST..TI17PERMFIL_3K   where  PERMFIL_CT=  'EPO_FTRSLNK_TXT' and    IDF_CT = 'EBS_ESPD3710'
*/

EBS_ESPD3800	EPO_DLDSIIGTARCO	${DFILP}/${ENV_PREFIX}_ESPD3710_DLDSIIGTAR_EBS_POC_${PARM_ICLODAT_D}.dat	I	 

-- correction ESPD3710
select * from BEST..TI17PERMFIL   where      IDF_CT = 'EBS_ESPD37100' and PATHPATTRN_LL like '%[_]POS[_]%'  
update BEST..TI17PERMFIL_3K  
set       PATHPATTRN_LL =str_replace( PATHPATTRN_LL,"POS","${TYPEINV}")
where      IDF_CT = 'EBS_ESPD3800' and PATHPATTRN_LL like '%[_]POS[_]%'  
select * from BEST..TI17PERMFIL_3K   where      IDF_CT = 'EBS_ESPD3800' and PATHPATTRN_LL like '%[_]POS[_]%'  


-- correction ESPD3800
select * from BEST..TI17PERMFIL   where      IDF_CT = 'EBS_ESPD3800' and PATHPATTRN_LL like '%[_]POS[_]%'  
update BEST..TI17PERMFIL_3K  
set       PATHPATTRN_LL =str_replace( PATHPATTRN_LL,"POS","${TYPEINV}")
where      IDF_CT = 'EBS_ESPD3800' and PATHPATTRN_LL like '%[_]POS[_]%'  
select * from BEST..TI17PERMFIL_3K   where      IDF_CT = 'EBS_ESPD3800' and PATHPATTRN_LL like '%[_]POS[_]%'  

-- correction ESPD8800
select * from BEST..TI17PERMFIL   where      IDF_CT = 'EBS_ESPD8800' and PATHPATTRN_LL like '%[_]POS[_]%'  
update BEST..TI17PERMFIL_3K  
set       PATHPATTRN_LL =str_replace( PATHPATTRN_LL,"POS","${TYPEINV}")
where      IDF_CT = 'EBS_ESPD8800' and PATHPATTRN_LL like '%[_]POS[_]%'  
select * from BEST..TI17PERMFIL_3K   where      IDF_CT = 'EBS_ESPD8800' and PATHPATTRN_LL like '%[_]POS[_]%'  

-- correction ESID2050 EST_DLRGTAA
select * from BEST..TI17PERMFIL  where      IDF_CT = 'ESID2050' and PATHPATTRN_LL like  "%ESID2050_DLRGTAA%"
update BEST..TI17PERMFIL_3K  
set       PATHPATTRN_LL ="${DFILI}/${ENV_PREFIX}_ESID2050_DLRGTAA_${TYPEINV}_${PARM_ICLODAT_D}.dat"
where        IDF_CT = 'ESID2050' and PATHPATTRN_LL like  "%ESID2050_DLRGTAA%"

--select * from BEST..TI17PERMFIL_3K where IDF_CT in (select IDF_CT from BEST..TI17REQCHN where REQCOD_CT = "EBSEMINV" ) and PATHPATTRN_LL like "%ESPD3800_FTECLED%"
--select * from BEST..TI17PERMFIL_3K where IDF_CT in (select IDF_CT from BEST..TI17REQCHN where REQCOD_CT = "EBSEMINV" ) and PATHPATTRN_LL like "%ESPD8830_FTECLED%"
--select * from BEST..TI17PERMFIL_3K where IDF_CT in (select IDF_CT from BEST..TI17REQCHN where REQCOD_CT = "EBSEQPOS" ) and PATHPATTRN_LL like "%ESPD8830_FTECLED%"

-- Evol IBNR Roger
select * from BEST..TI17PERMFIL_3K where IDF_CT ="EBS_ESID2210" and PERMFIL_CT ="EST_DLDGTAA_IFRS"
delete BEST..TI17PERMFIL_3K where IDF_CT ="EBS_ESID2210" and PERMFIL_CT ="EST_DLDGTAA_IFRS"
insert into BEST..TI17PERMFIL_3K values ('EBS_ESID2210',  'EST_DLDGTAA_IFRS','${DFILP}/${ENV_PREFIX}_ESID2000_DLDGTAA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')


select * from BEST..TI17PERMFIL_3K where IDF_CT ="ESID2000" and PERMFIL_CT ="EST_DLDGTAA_IBNRIFRS"
delete BEST..TI17PERMFIL_3K where IDF_CT ="ESID2000" and PERMFIL_CT ="EST_DLDGTAA_IBNRIFRS"
 insert into BEST..TI17PERMFIL_3K values ('ESID2000',  'EST_DLDGTAA_IBNRIFRS','${DFILP}/${ENV_PREFIX}_ESID2000_DLDGTAA_IBNRIFRS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
 
select * from BEST..TI17PERMFIL_3K where IDF_CT ="EBS_ESID2210" and PERMFIL_CT ="EST_DLDGTAA_IBNRIFRS"
delete BEST..TI17PERMFIL_3K where IDF_CT ="EBS_ESID2210" and PERMFIL_CT ="EST_DLDGTAA_IBNRIFRS"
 insert into BEST..TI17PERMFIL_3K values ('EBS_ESID2210',  'EST_DLDGTAA_IBNRIFRS','${DFILP}/${ENV_PREFIX}_ESID2000_DLDGTAA_IBNRIFRS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
 
 --- correction ESID2560 
  
select * from BEST..TI17PERMFIL  where  PATHPATTRN_LL like "%ESID2040_DLVGTAR%"  and IDF_CT ="ESID2560"
update BEST..TI17PERMFIL_3K set PATHPATTRN_LL ="`ls -rt ${DFILP}/${ENV_PREFIX}_ESID2040_DLVGTAR_PC_${PARM_ICLODAT_D}_*.dat | tail -1 `"   where  PATHPATTRN_LL like "%ESID2040_DLVGTAR%"  and IDF_CT ="ESID2560"
select * from BEST..TI17PERMFIL_3K  where  PATHPATTRN_LL like "%ESID2040_DLVGTAR%"  and IDF_CT ="ESID2560"

---NORME_CF REQCOD_CT                        dbclo_d
 -------- -------------------------------- -------------------------------
-- I4I      I4IQINV                                      May 20 2021 12:00AM
 --I17L     I17LQPOS                                     May 20 2021 12:00AM 
-- I17G     I17GQPOS                                     May 20 2021 12:00AM
-- EBSE     EBSEQPOS                                     May 20 2021 12:00AM
 
 ----------- test 
 
 --select  * from BEST..TI17REQJOBplan   where SITE_CF ="USA1" and dbclo_d="20210610"  order by dbclo_d desc  
--update BEST..TI17REQJOBplan   set launch_d =null where SITE_CF ="USA1" and dbclo_d="20210610" 