-------------------------------
--mapping of  ESPD3970

	----------   Clean tables   ---------------------

	delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESPD3970')
	delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESPD3970')
	delete BEST..TI17FNC where CHAIN_CT='ESPD3970'
	delete BEST..TI17CHN  where CHAIN_CT='ESPD3970'

	insert into BEST..TI17CHN values ('ESPD3970',  'Merge GLT EBS Common after SAP Feedback')

	----------IDF_CT:   EBS_MVT_MRG_STD ------------------

		insert into BEST..TI17FNC values ('EBS_MVT_MRG_STD','Merge GLT EBS Common after SAP Feedback','ESPD3970',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('EBS_MVT_MRG_STD',  'ESF_FTECLEDR_REJ','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDR_REJ_EBS.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_MVT_MRG_STD',  'ESF_OPNG_EBS_RET','${DFILP}/${ENV_PREFIX}_ESFD2900_FTECLEDR_OPNG_EBS.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_MVT_MRG_STD',  'ESF_FTECLEDR','${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_MVT_MRG_STD',  'EPO_FTECLEDA_MVT','${DFILP}/${ENV_PREFIX}_ESFD3960_${NORME_CF}_SAP_OMG_STD_FTECLEDA_RA_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_MVT_MRG_STD',  'EPO_FTECLEDA_RMN','${DFILP}/${ENV_PREFIX}_ESPD3910_EBS_MVT_SPL_STD_FTECLEDA_RMN_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_MVT_MRG_STD',  'EPO_FTECLEDA','${DFILP}/${ENV_PREFIX}_ESPD3970_EBS_MVT_MRG_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_MVT_MRG_STD',  'ESF_FTECLEDR_MRG','${DFILP}/${ENV_PREFIX}_ESPD3970_EBS_MVT_MRG_STD_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

			--- output files by site
			insert into BEST..TI17PERMFIL values ('EBS_MVT_MRG_STD',  'ESF_FTECLEDR_TOAS',    '${ENV_PREFIX}_ESPD3970_FTECLEDR_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOAS}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_MVT_MRG_STD',  'ESF_FTECLEDR_TOEU',    '${ENV_PREFIX}_ESPD3970_FTECLEDR_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOEU}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_MVT_MRG_STD',  'ESF_FTECLEDR_TOAM',    '${ENV_PREFIX}_ESPD3970_FTECLEDR_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOAM}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_MVT_MRG_STD',  'ESF_FTECLEDR_LOCAL',    '$DFILP/${ENV_PREFIX}_ESPD3970_FTECLEDR_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','O','')
			--- input files by site
 			insert into BEST..TI17PERMFIL values ('EBS_MVT_MRG_STD',  'ESF_FTECLEDR_FROMAS',    '${DFILP}/${ENV_PREFIX}_ESPD3970_FTECLEDR_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_ASTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_MVT_MRG_STD',  'ESF_FTECLEDR_FROMEU',    '${DFILP}/${ENV_PREFIX}_ESPD3970_FTECLEDR_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_EUTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_MVT_MRG_STD',  'ESF_FTECLEDR_FROMAM',    '${DFILP}/${ENV_PREFIX}_ESPD3970_FTECLEDR_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_AMTOLOCAL}.dat','I','')
			--- input product gaap code 
			insert into BEST..TI17PERMFIL values ('EBS_MVT_MRG_STD',  'ESF_FCTRI17PRD_FROMAS','${DFILP}/${ENV_PREFIX}_ESFD0040_FCTRI17PRD_${PARAM_ASTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_MVT_MRG_STD',  'EPO_GAAPCOD_MAPPING_FROMAS','${DFILP}/${ENV_PREFIX}_ESCJ0060_GAAPCOD_MAPPING_${PARAM_ASTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_MVT_MRG_STD',  'ESF_FCTRI17PRD_FROMEU','${DFILP}/${ENV_PREFIX}_ESFD0040_FCTRI17PRD_${PARAM_EUTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_MVT_MRG_STD',  'EPO_GAAPCOD_MAPPING_FROMEU','${DFILP}/${ENV_PREFIX}_ESCJ0060_GAAPCOD_MAPPING_${PARAM_EUTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_MVT_MRG_STD',  'ESF_FCTRI17PRD_FROMAM','${DFILP}/${ENV_PREFIX}_ESFD0040_FCTRI17PRD_${PARAM_AMTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_MVT_MRG_STD',  'EPO_GAAPCOD_MAPPING_FROMAM','${DFILP}/${ENV_PREFIX}_ESCJ0060_GAAPCOD_MAPPING_${PARAM_AMTOLOCAL}.dat','I','')			

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('EBSEQPOS',  'EBS_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('EBSEQPOSB',  'EBS_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('EBSEYPOC',  'EBS_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('EBSEMINV',  'EBS_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('EBSEQINV',  'EBS_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('EBSEQINVB',  'EBS_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('EBSEYINV',  'EBS_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('EBSEYINVB',  'EBS_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('EBSEQPOC',  'EBS_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('EBSEQPOCB',  'EBS_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('EBSEYPOCB',  'EBS_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('EBSEYPOS',  'EBS_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('EBSEYPOSB',  'EBS_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('EBSEQPOSP',  'EBS_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('EBSEYPOSP',  'EBS_MVT_MRG_STD','')

	----------IDF_CT:   I17G_MVT_MRG_STD ------------------

		insert into BEST..TI17FNC values ('I17G_MVT_MRG_STD','Merge GLT I17G Common after SAP Feedback','ESPD3970',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17G_MVT_MRG_STD',  'ESF_FTECLEDR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_MVT_MRG_STD',  'ESF_FTECLEDR_REJ','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_MVT_MRG_STD',  'ESF_OPNG_EBS_RET','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_MVT_MRG_STD',  'EPO_FTECLEDA_MVT','${DFILP}/${ENV_PREFIX}_ESFD3960_${NORME_CF}_SAP_OMG_STD_FTECLEDA_RA_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_MVT_MRG_STD',  'EPO_FTECLEDA_RMN','${DFILP}/${ENV_PREFIX}_ESPD3910_I17G_MVT_SPL_STD_FTECLEDA_RMN_I17G_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_MVT_MRG_STD',  'ESF_FTECLEDR_MRG','${DFILP}/empty.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_MVT_MRG_STD',  'EPO_FTECLEDA','${DFILP}/${ENV_PREFIX}_ESPD3970_I17G_MVT_MRG_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

			--- output files by site
			insert into BEST..TI17PERMFIL values ('I17G_MVT_MRG_STD',  'ESF_FTECLEDA_TOAS',    '${ENV_PREFIX}_ESPD3970_FTECLEDA_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOAS}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_MVT_MRG_STD',  'ESF_FTECLEDA_TOEU',    '${ENV_PREFIX}_ESPD3970_FTECLEDA_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOEU}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_MVT_MRG_STD',  'ESF_FTECLEDA_TOAM',    '${ENV_PREFIX}_ESPD3970_FTECLEDA_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOAM}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_MVT_MRG_STD',  'ESF_FTECLEDA_LOCAL',    '$DFILP/${ENV_PREFIX}_ESPD3970_FTECLEDA_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_MVT_MRG_STD',  'ESF_FTECLEDR_TOAS',    '${ENV_PREFIX}_ESPD3970_FTECLEDR_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOAS}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_MVT_MRG_STD',  'ESF_FTECLEDR_TOEU',    '${ENV_PREFIX}_ESPD3970_FTECLEDR_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOEU}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_MVT_MRG_STD',  'ESF_FTECLEDR_TOAM',    '${ENV_PREFIX}_ESPD3970_FTECLEDR_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOAM}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_MVT_MRG_STD',  'ESF_FTECLEDR_LOCAL',    '$DFILP/${ENV_PREFIX}_ESPD3970_FTECLEDR_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','O','')
			--- input files by site                 
			insert into BEST..TI17PERMFIL values ('I17G_MVT_MRG_STD',  'ESF_FTECLEDA_FROMAS',    '${DFILP}/${ENV_PREFIX}_ESPD3970_FTECLEDA_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_ASTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_MVT_MRG_STD',  'ESF_FTECLEDA_FROMEU',    '${DFILP}/${ENV_PREFIX}_ESPD3970_FTECLEDA_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_EUTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_MVT_MRG_STD',  'ESF_FTECLEDA_FROMAM',    '${DFILP}/${ENV_PREFIX}_ESPD3970_FTECLEDA_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_AMTOLOCAL}.dat','I','')
 			insert into BEST..TI17PERMFIL values ('I17G_MVT_MRG_STD',  'ESF_FTECLEDR_FROMAS',    '${DFILP}/${ENV_PREFIX}_ESPD3970_FTECLEDR_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_ASTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_MVT_MRG_STD',  'ESF_FTECLEDR_FROMEU',    '${DFILP}/${ENV_PREFIX}_ESPD3970_FTECLEDR_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_EUTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_MVT_MRG_STD',  'ESF_FTECLEDR_FROMAM',    '${DFILP}/${ENV_PREFIX}_ESPD3970_FTECLEDR_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_AMTOLOCAL}.dat','I','')
			--- input product gaap code             
			insert into BEST..TI17PERMFIL values ('I17G_MVT_MRG_STD',  'ESF_FCTRI17PRD_FROMAS','${DFILP}/${ENV_PREFIX}_ESFD0040_FCTRI17PRD_${PARAM_ASTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_MVT_MRG_STD',  'EPO_GAAPCOD_MAPPING_FROMAS','${DFILP}/${ENV_PREFIX}_ESCJ0060_GAAPCOD_MAPPING_${PARAM_ASTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_MVT_MRG_STD',  'ESF_FCTRI17PRD_FROMEU','${DFILP}/${ENV_PREFIX}_ESFD0040_FCTRI17PRD_${PARAM_EUTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_MVT_MRG_STD',  'EPO_GAAPCOD_MAPPING_FROMEU','${DFILP}/${ENV_PREFIX}_ESCJ0060_GAAPCOD_MAPPING_${PARAM_EUTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_MVT_MRG_STD',  'ESF_FCTRI17PRD_FROMAM','${DFILP}/${ENV_PREFIX}_ESFD0040_FCTRI17PRD_${PARAM_AMTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_MVT_MRG_STD',  'EPO_GAAPCOD_MAPPING_FROMAM','${DFILP}/${ENV_PREFIX}_ESCJ0060_GAAPCOD_MAPPING_${PARAM_AMTOLOCAL}.dat','I','')			



		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17GYPOS',  'I17G_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17GYPOSB',  'I17G_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('S',  'I17G_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17GQINV',  'I17G_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17GYINV',  'I17G_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17GMINV',  'I17G_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17GQINVB',  'I17G_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17GQPOS',  'I17G_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17GQPOSB',  'I17G_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17GYINVB',  'I17G_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17GYPOSP',  'I17G_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17GQPOSP',  'I17G_MVT_MRG_STD','')

	----------IDF_CT:   I17L_MVT_MRG_STD ------------------

		insert into BEST..TI17FNC values ('I17L_MVT_MRG_STD','Merge GLT I17L Common after SAP Feedback','ESPD3970',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17L_MVT_MRG_STD',  'ESF_FTECLEDR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_MVT_MRG_STD',  'ESF_FTECLEDR_REJ','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_MVT_MRG_STD',  'ESF_OPNG_EBS_RET','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_MVT_MRG_STD',  'EPO_FTECLEDA_MVT','${DFILP}/${ENV_PREFIX}_ESFD3960_${NORME_CF}_SAP_OMG_STD_FTECLEDA_RA_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_MVT_MRG_STD',  'EPO_FTECLEDA_RMN','${DFILP}/${ENV_PREFIX}_ESPD3910_I17L_MVT_SPL_STD_FTECLEDA_RMN_I17L_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_MVT_MRG_STD',  'ESF_FTECLEDR_MRG','${DFILP}/empty.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_MVT_MRG_STD',  'EPO_FTECLEDA','${DFILP}/${ENV_PREFIX}_ESPD3970_I17L_MVT_MRG_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

			--- output files by site
			insert into BEST..TI17PERMFIL values ('I17L_MVT_MRG_STD',  'ESF_FTECLEDA_TOAS',    '${ENV_PREFIX}_ESPD3970_FTECLEDA_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOAS}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_MVT_MRG_STD',  'ESF_FTECLEDA_TOEU',    '${ENV_PREFIX}_ESPD3970_FTECLEDA_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOEU}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_MVT_MRG_STD',  'ESF_FTECLEDA_TOAM',    '${ENV_PREFIX}_ESPD3970_FTECLEDA_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOAM}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_MVT_MRG_STD',  'ESF_FTECLEDA_LOCAL',    '$DFILP/${ENV_PREFIX}_ESPD3970_FTECLEDA_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_MVT_MRG_STD',  'ESF_FTECLEDR_TOAS',    '${ENV_PREFIX}_ESPD3970_FTECLEDR_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOAS}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_MVT_MRG_STD',  'ESF_FTECLEDR_TOEU',    '${ENV_PREFIX}_ESPD3970_FTECLEDR_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOEU}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_MVT_MRG_STD',  'ESF_FTECLEDR_TOAM',    '${ENV_PREFIX}_ESPD3970_FTECLEDR_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOAM}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_MVT_MRG_STD',  'ESF_FTECLEDR_LOCAL',    '$DFILP/${ENV_PREFIX}_ESPD3970_FTECLEDR_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','O','')
			--- input files by site                   
			insert into BEST..TI17PERMFIL values ('I17L_MVT_MRG_STD',  'ESF_FTECLEDA_FROMAS',    '${DFILP}/${ENV_PREFIX}_ESPD3970_FTECLEDA_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_ASTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_MVT_MRG_STD',  'ESF_FTECLEDA_FROMEU',    '${DFILP}/${ENV_PREFIX}_ESPD3970_FTECLEDA_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_EUTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_MVT_MRG_STD',  'ESF_FTECLEDA_FROMAM',    '${DFILP}/${ENV_PREFIX}_ESPD3970_FTECLEDA_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_AMTOLOCAL}.dat','I','')
 			insert into BEST..TI17PERMFIL values ('I17L_MVT_MRG_STD',  'ESF_FTECLEDR_FROMAS',    '${DFILP}/${ENV_PREFIX}_ESPD3970_FTECLEDR_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_ASTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_MVT_MRG_STD',  'ESF_FTECLEDR_FROMEU',    '${DFILP}/${ENV_PREFIX}_ESPD3970_FTECLEDR_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_EUTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_MVT_MRG_STD',  'ESF_FTECLEDR_FROMAM',    '${DFILP}/${ENV_PREFIX}_ESPD3970_FTECLEDR_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_AMTOLOCAL}.dat','I','')
			--- input product gaap code               
			insert into BEST..TI17PERMFIL values ('I17L_MVT_MRG_STD',  'ESF_FCTRI17PRD_FROMAS','${DFILP}/${ENV_PREFIX}_ESFD0040_FCTRI17PRD_${PARAM_ASTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_MVT_MRG_STD',  'EPO_GAAPCOD_MAPPING_FROMAS','${DFILP}/${ENV_PREFIX}_ESCJ0060_GAAPCOD_MAPPING_${PARAM_ASTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_MVT_MRG_STD',  'ESF_FCTRI17PRD_FROMEU','${DFILP}/${ENV_PREFIX}_ESFD0040_FCTRI17PRD_${PARAM_EUTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_MVT_MRG_STD',  'EPO_GAAPCOD_MAPPING_FROMEU','${DFILP}/${ENV_PREFIX}_ESCJ0060_GAAPCOD_MAPPING_${PARAM_EUTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_MVT_MRG_STD',  'ESF_FCTRI17PRD_FROMAM','${DFILP}/${ENV_PREFIX}_ESFD0040_FCTRI17PRD_${PARAM_AMTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_MVT_MRG_STD',  'EPO_GAAPCOD_MAPPING_FROMAM','${DFILP}/${ENV_PREFIX}_ESCJ0060_GAAPCOD_MAPPING_${PARAM_AMTOLOCAL}.dat','I','')
			
		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('S',  'I17L_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17LMINV',  'I17L_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17LQINVB',  'I17L_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17LQPOS',  'I17L_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17LQPOSB',  'I17L_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17LYINVB',  'I17L_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17LYPOS',  'I17L_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17LYPOSB',  'I17L_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17LQINV',  'I17L_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17LYINV',  'I17L_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17LQPOSP',  'I17L_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17LYPOSP',  'I17L_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17LQPOSX',  'I17L_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17LYPOSX',  'I17L_MVT_MRG_STD','')

	----------IDF_CT:   I17P_MVT_MRG_STD ------------------

		insert into BEST..TI17FNC values ('I17P_MVT_MRG_STD','Merge GLT I17P Common after SAP Feedback','ESPD3970',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17P_MVT_MRG_STD',  'ESF_FTECLEDR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_MVT_MRG_STD',  'ESF_FTECLEDR_REJ','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_MVT_MRG_STD',  'ESF_OPNG_EBS_RET','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_MVT_MRG_STD',  'EPO_FTECLEDA_MVT','${DFILP}/${ENV_PREFIX}_ESFD3960_${NORME_CF}_SAP_OMG_STD_FTECLEDA_RA_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_MVT_MRG_STD',  'EPO_FTECLEDA_RMN','${DFILP}/${ENV_PREFIX}_ESPD3910_I17P_MVT_SPL_STD_FTECLEDA_RMN_I17P_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_MVT_MRG_STD',  'ESF_FTECLEDR_MRG','${DFILP}/empty.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_MVT_MRG_STD',  'EPO_FTECLEDA','${DFILP}/${ENV_PREFIX}_ESPD3970_I17P_MVT_MRG_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')


			--- output files by site
			insert into BEST..TI17PERMFIL values ('I17P_MVT_MRG_STD',  'ESF_FTECLEDA_TOAS',    '${ENV_PREFIX}_ESPD3970_FTECLEDA_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOAS}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_MVT_MRG_STD',  'ESF_FTECLEDA_TOEU',    '${ENV_PREFIX}_ESPD3970_FTECLEDA_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOEU}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_MVT_MRG_STD',  'ESF_FTECLEDA_TOAM',    '${ENV_PREFIX}_ESPD3970_FTECLEDA_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOAM}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_MVT_MRG_STD',  'ESF_FTECLEDA_LOCAL',    '$DFILP/${ENV_PREFIX}_ESPD3970_FTECLEDA_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_MVT_MRG_STD',  'ESF_FTECLEDR_TOAS',    '${ENV_PREFIX}_ESPD3970_FTECLEDR_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOAS}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_MVT_MRG_STD',  'ESF_FTECLEDR_TOEU',    '${ENV_PREFIX}_ESPD3970_FTECLEDR_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOEU}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_MVT_MRG_STD',  'ESF_FTECLEDR_TOAM',    '${ENV_PREFIX}_ESPD3970_FTECLEDR_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOAM}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_MVT_MRG_STD',  'ESF_FTECLEDR_LOCAL',    '$DFILP/${ENV_PREFIX}_ESPD3970_FTECLEDR_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','O','')
			--- input files by site                    
			insert into BEST..TI17PERMFIL values ('I17P_MVT_MRG_STD',  'ESF_FTECLEDA_FROMAS',    '${DFILP}/${ENV_PREFIX}_ESPD3970_FTECLEDA_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_ASTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_MVT_MRG_STD',  'ESF_FTECLEDA_FROMEU',    '${DFILP}/${ENV_PREFIX}_ESPD3970_FTECLEDA_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_EUTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_MVT_MRG_STD',  'ESF_FTECLEDA_FROMAM',    '${DFILP}/${ENV_PREFIX}_ESPD3970_FTECLEDA_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_AMTOLOCAL}.dat','I','')
 			insert into BEST..TI17PERMFIL values ('I17P_MVT_MRG_STD',  'ESF_FTECLEDR_FROMAS',    '${DFILP}/${ENV_PREFIX}_ESPD3970_FTECLEDR_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_ASTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_MVT_MRG_STD',  'ESF_FTECLEDR_FROMEU',    '${DFILP}/${ENV_PREFIX}_ESPD3970_FTECLEDR_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_EUTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_MVT_MRG_STD',  'ESF_FTECLEDR_FROMAM',    '${DFILP}/${ENV_PREFIX}_ESPD3970_FTECLEDR_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_AMTOLOCAL}.dat','I','')
			--- input product gaap code               
			insert into BEST..TI17PERMFIL values ('I17P_MVT_MRG_STD',  'ESF_FCTRI17PRD_FROMAS','${DFILP}/${ENV_PREFIX}_ESFD0040_FCTRI17PRD_${PARAM_ASTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_MVT_MRG_STD',  'EPO_GAAPCOD_MAPPING_FROMAS','${DFILP}/${ENV_PREFIX}_ESCJ0060_GAAPCOD_MAPPING_${PARAM_ASTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_MVT_MRG_STD',  'ESF_FCTRI17PRD_FROMEU','${DFILP}/${ENV_PREFIX}_ESFD0040_FCTRI17PRD_${PARAM_EUTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_MVT_MRG_STD',  'EPO_GAAPCOD_MAPPING_FROMEU','${DFILP}/${ENV_PREFIX}_ESCJ0060_GAAPCOD_MAPPING_${PARAM_EUTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_MVT_MRG_STD',  'ESF_FCTRI17PRD_FROMAM','${DFILP}/${ENV_PREFIX}_ESFD0040_FCTRI17PRD_${PARAM_AMTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_MVT_MRG_STD',  'EPO_GAAPCOD_MAPPING_FROMAM','${DFILP}/${ENV_PREFIX}_ESCJ0060_GAAPCOD_MAPPING_${PARAM_AMTOLOCAL}.dat','I','')
			
		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17PMINV',  'I17P_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17PQINVB',  'I17P_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17PQPOS',  'I17P_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17PQPOSB',  'I17P_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17PYINVB',  'I17P_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17PYPOS',  'I17P_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17PYPOSB',  'I17P_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('S',  'I17P_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17PQINV',  'I17P_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17PYINV',  'I17P_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17PQPOSP',  'I17P_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17PYPOSP',  'I17P_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17PQPOSX',  'I17P_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17PYPOSX',  'I17P_MVT_MRG_STD','')

	----------IDF_CT:   I17S_MVT_MRG_STD ------------------

		insert into BEST..TI17FNC values ('I17S_MVT_MRG_STD','Merge GLT I17S Common after SAP Feedback','ESPD3970',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17S_MVT_MRG_STD',  'ESF_FTECLEDR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_MVT_MRG_STD',  'ESF_FTECLEDR_REJ','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_MVT_MRG_STD',  'ESF_OPNG_EBS_RET','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_MVT_MRG_STD',  'EPO_FTECLEDA_MVT','${DFILP}/${ENV_PREFIX}_ESFD3960_${NORME_CF}_SAP_OMG_STD_FTECLEDA_RA_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_MVT_MRG_STD',  'EPO_FTECLEDA_RMN','${DFILP}/${ENV_PREFIX}_ESPD3910_I17S_MVT_SPL_STD_FTECLEDA_RMN_I17S_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_MVT_MRG_STD',  'ESF_FTECLEDR_MRG','${DFILP}/empty.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_MVT_MRG_STD',  'EPO_FTECLEDA','${DFILP}/${ENV_PREFIX}_ESPD3970_I17S_MVT_MRG_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')


			--- output files by site
			insert into BEST..TI17PERMFIL values ('I17S_MVT_MRG_STD',  'ESF_FTECLEDA_TOAS',    '${ENV_PREFIX}_ESPD3970_FTECLEDA_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOAS}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_MVT_MRG_STD',  'ESF_FTECLEDA_TOEU',    '${ENV_PREFIX}_ESPD3970_FTECLEDA_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOEU}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_MVT_MRG_STD',  'ESF_FTECLEDA_TOAM',    '${ENV_PREFIX}_ESPD3970_FTECLEDA_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOAM}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_MVT_MRG_STD',  'ESF_FTECLEDA_LOCAL',    '$DFILP/${ENV_PREFIX}_ESPD3970_FTECLEDA_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_MVT_MRG_STD',  'ESF_FTECLEDR_TOAS',    '${ENV_PREFIX}_ESPD3970_FTECLEDR_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOAS}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_MVT_MRG_STD',  'ESF_FTECLEDR_TOEU',    '${ENV_PREFIX}_ESPD3970_FTECLEDR_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOEU}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_MVT_MRG_STD',  'ESF_FTECLEDR_TOAM',    '${ENV_PREFIX}_ESPD3970_FTECLEDR_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOAM}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_MVT_MRG_STD',  'ESF_FTECLEDR_LOCAL',    '$DFILP/${ENV_PREFIX}_ESPD3970_FTECLEDR_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','O','')
			--- input files by site                   
			insert into BEST..TI17PERMFIL values ('I17S_MVT_MRG_STD',  'ESF_FTECLEDA_FROMAS',    '${DFILP}/${ENV_PREFIX}_ESPD3970_FTECLEDA_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_ASTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_MVT_MRG_STD',  'ESF_FTECLEDA_FROMEU',    '${DFILP}/${ENV_PREFIX}_ESPD3970_FTECLEDA_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_EUTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_MVT_MRG_STD',  'ESF_FTECLEDA_FROMAM',    '${DFILP}/${ENV_PREFIX}_ESPD3970_FTECLEDA_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_AMTOLOCAL}.dat','I','')
 			insert into BEST..TI17PERMFIL values ('I17S_MVT_MRG_STD',  'ESF_FTECLEDR_FROMAS',    '${DFILP}/${ENV_PREFIX}_ESPD3970_FTECLEDR_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_ASTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_MVT_MRG_STD',  'ESF_FTECLEDR_FROMEU',    '${DFILP}/${ENV_PREFIX}_ESPD3970_FTECLEDR_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_EUTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_MVT_MRG_STD',  'ESF_FTECLEDR_FROMAM',    '${DFILP}/${ENV_PREFIX}_ESPD3970_FTECLEDR_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_AMTOLOCAL}.dat','I','')
			--- input product gaap code               
			insert into BEST..TI17PERMFIL values ('I17S_MVT_MRG_STD',  'ESF_FCTRI17PRD_FROMAS','${DFILP}/${ENV_PREFIX}_ESFD0040_FCTRI17PRD_${PARAM_ASTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_MVT_MRG_STD',  'EPO_GAAPCOD_MAPPING_FROMAS','${DFILP}/${ENV_PREFIX}_ESCJ0060_GAAPCOD_MAPPING_${PARAM_ASTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_MVT_MRG_STD',  'ESF_FCTRI17PRD_FROMEU','${DFILP}/${ENV_PREFIX}_ESFD0040_FCTRI17PRD_${PARAM_EUTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_MVT_MRG_STD',  'EPO_GAAPCOD_MAPPING_FROMEU','${DFILP}/${ENV_PREFIX}_ESCJ0060_GAAPCOD_MAPPING_${PARAM_EUTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_MVT_MRG_STD',  'ESF_FCTRI17PRD_FROMAM','${DFILP}/${ENV_PREFIX}_ESFD0040_FCTRI17PRD_${PARAM_AMTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_MVT_MRG_STD',  'EPO_GAAPCOD_MAPPING_FROMAM','${DFILP}/${ENV_PREFIX}_ESCJ0060_GAAPCOD_MAPPING_${PARAM_AMTOLOCAL}.dat','I','')
			
		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17SQINV',  'I17S_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17SYINV',  'I17S_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17SMINV',  'I17S_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17SQINVB',  'I17S_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17SQPOS',  'I17S_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17SQPOSB',  'I17S_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17SYINVB',  'I17S_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17SYPOS',  'I17S_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17SYPOSB',  'I17S_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17SQPOSP',  'I17S_MVT_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17SYPOSP',  'I17S_MVT_MRG_STD','')

	----------IDF_CT:   I4I_MVT_MRG_INV ------------------

		insert into BEST..TI17FNC values ('I4I_MVT_MRG_INV','Merge GLT I4I Common after SAP Feedback','ESPD3970',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I4I_MVT_MRG_INV',  'ESF_FTECLEDR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_MVT_MRG_INV',  'ESF_FTECLEDR_REJ','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_MVT_MRG_INV',  'ESF_OPNG_EBS_RET','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_MVT_MRG_INV',  'EPO_FTECLEDA_MVT','${DFILP}/${ENV_PREFIX}_ESID3860_FTECLEDA_MVT_${NORME_CF}_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_MVT_MRG_INV',  'EPO_FTECLEDA_RMN','${DFILP}/${ENV_PREFIX}_ESPD3910_I4I_MVT_SPL_STD_FTECLEDA_RMN_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_MVT_MRG_INV',  'ESF_FTECLEDR_MRG','${DFILP}/empty.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_MVT_MRG_INV',  'EPO_FTECLEDA','${DFILP}/${ENV_PREFIX}_ESPD3970_I4I_MVT_MRG_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')


			--- output files by site
			insert into BEST..TI17PERMFIL values ('I4I_MVT_MRG_INV',  'ESF_FTECLEDA_TOAS',    '${ENV_PREFIX}_ESPD3970_FTECLEDA_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOAS}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_MVT_MRG_INV',  'ESF_FTECLEDA_TOEU',    '${ENV_PREFIX}_ESPD3970_FTECLEDA_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOEU}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_MVT_MRG_INV',  'ESF_FTECLEDA_TOAM',    '${ENV_PREFIX}_ESPD3970_FTECLEDA_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOAM}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_MVT_MRG_INV',  'ESF_FTECLEDA_LOCAL',    '$DFILP/${ENV_PREFIX}_ESPD3970_FTECLEDA_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_MVT_MRG_INV',  'ESF_FTECLEDR_TOAS',    '${ENV_PREFIX}_ESPD3970_FTECLEDR_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOAS}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_MVT_MRG_INV',  'ESF_FTECLEDR_TOEU',    '${ENV_PREFIX}_ESPD3970_FTECLEDR_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOEU}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_MVT_MRG_INV',  'ESF_FTECLEDR_TOAM',    '${ENV_PREFIX}_ESPD3970_FTECLEDR_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOAM}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_MVT_MRG_INV',  'ESF_FTECLEDR_LOCAL',    '$DFILP/${ENV_PREFIX}_ESPD3970_FTECLEDR_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','O','')
			--- input files by site                 
			insert into BEST..TI17PERMFIL values ('I4I_MVT_MRG_INV',  'ESF_FTECLEDA_FROMAS',    '${DFILP}/${ENV_PREFIX}_ESPD3970_FTECLEDA_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_ASTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_MVT_MRG_INV',  'ESF_FTECLEDA_FROMEU',    '${DFILP}/${ENV_PREFIX}_ESPD3970_FTECLEDA_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_EUTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_MVT_MRG_INV',  'ESF_FTECLEDA_FROMAM',    '${DFILP}/${ENV_PREFIX}_ESPD3970_FTECLEDA_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_AMTOLOCAL}.dat','I','')
 			insert into BEST..TI17PERMFIL values ('I4I_MVT_MRG_INV',  'ESF_FTECLEDR_FROMAS',    '${DFILP}/${ENV_PREFIX}_ESPD3970_FTECLEDR_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_ASTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_MVT_MRG_INV',  'ESF_FTECLEDR_FROMEU',    '${DFILP}/${ENV_PREFIX}_ESPD3970_FTECLEDR_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_EUTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_MVT_MRG_INV',  'ESF_FTECLEDR_FROMAM',    '${DFILP}/${ENV_PREFIX}_ESPD3970_FTECLEDR_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_AMTOLOCAL}.dat','I','')
			--- input product gaap code             
			insert into BEST..TI17PERMFIL values ('I4I_MVT_MRG_INV',  'ESF_FCTRI17PRD_FROMAS','${DFILP}/${ENV_PREFIX}_ESFD0040_FCTRI17PRD_${PARAM_ASTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_MVT_MRG_INV',  'EPO_GAAPCOD_MAPPING_FROMAS','${DFILP}/${ENV_PREFIX}_ESCJ0060_GAAPCOD_MAPPING_${PARAM_ASTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_MVT_MRG_INV',  'ESF_FCTRI17PRD_FROMEU','${DFILP}/${ENV_PREFIX}_ESFD0040_FCTRI17PRD_${PARAM_EUTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_MVT_MRG_INV',  'EPO_GAAPCOD_MAPPING_FROMEU','${DFILP}/${ENV_PREFIX}_ESCJ0060_GAAPCOD_MAPPING_${PARAM_EUTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_MVT_MRG_INV',  'ESF_FCTRI17PRD_FROMAM','${DFILP}/${ENV_PREFIX}_ESFD0040_FCTRI17PRD_${PARAM_AMTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_MVT_MRG_INV',  'EPO_GAAPCOD_MAPPING_FROMAM','${DFILP}/${ENV_PREFIX}_ESCJ0060_GAAPCOD_MAPPING_${PARAM_AMTOLOCAL}.dat','I','')
			
		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I4IMINV',  'I4I_MVT_MRG_INV','')
			insert into BEST..TI17REQFNC values ('I4IMINVB',  'I4I_MVT_MRG_INV','')
			insert into BEST..TI17REQFNC values ('I4IQINV',  'I4I_MVT_MRG_INV','')
			insert into BEST..TI17REQFNC values ('I4IQINVB',  'I4I_MVT_MRG_INV','')
			insert into BEST..TI17REQFNC values ('I4IYINV',  'I4I_MVT_MRG_INV','')
			insert into BEST..TI17REQFNC values ('I4IYINVB',  'I4I_MVT_MRG_INV','')

	----------IDF_CT:   I4I_MVT_MRG_INVI4I_MVT_MRG_INV ------------------

		insert into BEST..TI17FNC values ('I4I_MVT_MRG_INVI4I_MVT_MRG_INV','Merge GLT I4I Common after SAP Feedback','ESPD3970',0)
					

		----------  Perms---------------------


		----------   Reqs    ---------------------

go

