-------------------------------
--mapping of  STAD1500

	----------   Clean tables   ---------------------

	delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='STAD1500')
	delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='STAD1500')
	delete BEST..TI17FNC where CHAIN_CT='STAD1500'
	delete BEST..TI17CHN  where CHAIN_CT='STAD1500'

	insert into BEST..TI17CHN values ('STAD1500',  '')

	----------IDF_CT:   STAD1500 ------------------

		insert into BEST..TI17FNC values ('STAD1500',' ','STAD1500',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('STAD1500',  'EST_SUBTRS','${DFILP}/${ENV_PREFIX}_ESCJ0060_FSUBTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('STAD1500',  'EST_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('STAD1500',  'EST_SRGTE_PA','${DFILP}/${ENV_PREFIX}_ESID2040_SRGTE_PA_${BALSHTYEA}1231.dat','I','')
			insert into BEST..TI17PERMFIL values ('STAD1500',  'EST_SRGTEF_PA','${DFILP}/${ENV_PREFIX}_ESID2040_SRGTEF_PA_${BALSHTYEA}1231.dat','I','')
			insert into BEST..TI17PERMFIL values ('STAD1500',  'STA_LIFSTAREP_BILANPREC','${DFILP}/${ENV_PREFIX}_STAD1520_LIFSTAREP_BILANPREC.dat','I','')
			insert into BEST..TI17PERMFIL values ('STAD1500',  'STA_LIFSTAREP_TRIMEPREC','${DFILP}/${ENV_PREFIX}_STAD1520_LIFSTAREP_TRIMEPREC.dat','I','')
			insert into BEST..TI17PERMFIL values ('STAD1500',  'EST_SRGTC','${DFILP}/${ENV_PREFIX}_ESID2030_SRGTC_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('STAD1500',  'EST_SRGTCB1','${DFILP}/${ENV_PREFIX}_ESID2030_SRGTCB1_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('STAD1500',  'EST_CPLIFDRI','${DFILP}/${ENV_PREFIX}_ESID2030_CPLIFDRI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('STAD1500',  'EST_SRGTE_PC','${DFILP}/${ENV_PREFIX}_ESID2040_SRGTE_PC_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('STAD1500',  'STA_LIFSTADIF','${DFILP}/${ENV_PREFIX}_STAD1520_LIFSTADIF${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('STAD1500',  'EST_CPLIFDRIN','${DFILP}/${ENV_PREFIX}_ESID2030_CPLIFDRIN_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('STAD1500',  'EST_ECRSRVAPC','${DFILP}/${ENV_PREFIX}_ESID1520_ECRSRVAPC_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('STAD1500',  'EST_ECRSRVRPC','${DFILP}/${ENV_PREFIX}_ESID1520_ECRSRVRPC_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('STAD1500',  'EST_FVPLACEMT','${DFILP}/${ENV_PREFIX}_ESID2030_FVPLACEMT_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('STAD1500',  'EST_LIFENDCPT','${DFILP}/${ENV_PREFIX}_ESID2030_LIFENDCPT_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('STAD1500',  'EST_SRGTEF_PC','${DFILP}/${ENV_PREFIX}_ESID2040_SRGTEF_PC_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('STAD1500',  'EST_ECRSRVACBP','${DFILP}/${ENV_PREFIX}_ESID1520_ECRSRVACBP_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('STAD1500',  'EST_ECRSRVRCBP','${DFILP}/${ENV_PREFIX}_ESID1520_ECRSRVRCBP_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('STAD1500',  'EST_FLIFPLN1','${DFILP}/${ENV_PREFIX}_ESID1520_EST_FLIFPLN1_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('STAD1500',  'EST_FLIFPLN3','${DFILP}/${ENV_PREFIX}_ESID1520_EST_FLIFPLN3_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('STAD1500',  'EST_FVPLACEMT2','${DFILP}/${ENV_PREFIX}_ESID2030_FVPLACEMT2_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('STAD1500',  'EST_VLIFEST195','${DFILP}/${ENV_PREFIX}_ESID2030_VLIFEST195_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('STAD1500',  'EST_SUBTRSASSO','${DFILP}/${ENV_PREFIX}_ESCJ0060_FSUBTRSASSO_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('STAD1500',  'EST_LIFESTNOACC','${DFILP}/${ENV_PREFIX}_ESID2030_LIFESTNOACC_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('STAD1500',  'EST_IARVPERICASE4','${DFILP}/${ENV_PREFIX}_ESID2030_IARVPERICASE4_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('STAD1500',  'EST_SUBTRSESBPROP','${DFILP}/${ENV_PREFIX}_ESCJ0060_FSUBTRSESBPROP_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('STAD1500',  'STA_LIFSTAREP_PLAN','${DFILP}/${ENV_PREFIX}_STAD1520_LIFSTAREP_PLAN${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('STAD1500',  'STA_LIFSTAREP','${DFILP}/${ENV_PREFIX}_STAD1500_LIFSTAREP_INV.dat','O','')
			insert into BEST..TI17PERMFIL values ('STAD1500',  'STA_LIFSTAREP_CBP_RETRO','${DFILP}/${ENV_PREFIX}_STAD1500_LIFSTAREP_CBP_RETRO.dat','O','')
			insert into BEST..TI17PERMFIL values ('STAD1500',  'EST_SRGTEFAR','${DFILP}/${ENV_PREFIX}_STAD1500_SRGTEFAR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('STAD1500',  'EST_LIFNEWBIZ','${DFILP}/${ENV_PREFIX}_STAD1500_FLIFNEWBIZ_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('STAD1500',  'EST_SRGTCB1_RETRO','${DFILP}/${ENV_PREFIX}_STAD1500_SRGTCB1_RETRO_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('STAD1500',  'EST_SRGTEFR_VENTIL','${DFILP}/${ENV_PREFIX}_STAD1500_SRGTEFR_VENTIL_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('STAD1500',  'EST_SRGTEF_BILAN','${DFILP}/${ENV_PREFIX}_STAD1500_EST_SRGTEF_BILAN_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('STAD1500',  'EST_FLIFPLN1_VENTIL','${DFILP}/${ENV_PREFIX}_STAD1500_FLIFPLN1_VENTIL_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('STAD1500',  'STA_LIFSTAREP_BRIDG','${DFILP}/${ENV_PREFIX}_STAD1500_LIFSTAREP_BRIDGE${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('STAD1500',  'EST_ECRSRVRPC_VENTIL','${DFILP}/${ENV_PREFIX}_STAD1500_ECRSRVRPC_VENTIL_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I4IMINV',  'STAD1500','@variante')
			insert into BEST..TI17REQFNC values ('I4IQINV',  'STAD1500','@variante')
			insert into BEST..TI17REQFNC values ('I4IYINV',  'STAD1500','@variante')
			insert into BEST..TI17REQFNC values ('A',  'STAD1500','')
go

