-------------------------------
--mapping of  ESFD3960

	----------   Clean tables   ---------------------

	delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD3960')
	delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD3960')
	delete BEST..TI17FNC where CHAIN_CT='ESFD3960'
	delete BEST..TI17CHN  where CHAIN_CT='ESFD3960'

	insert into BEST..TI17CHN values ('ESFD3960',  'Integrate SAP file feedback to Omega')

	----------IDF_CT:   EBS_SAP_OMG_STD ------------------

		insert into BEST..TI17FNC values ('EBS_SAP_OMG_STD','Integrate SAP file feedback to Omega','ESFD3960',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('EBS_SAP_OMG_STD',  'ESF_FTECLEDA_MVT_PREV','${DFILP}/${ENV_PREFIX}_ESFD3930_${NORME_CF}_DLT_SAP_STD_FTECLEDA_DELTA_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_SAP_OMG_STD',  'ESF_FICFROMONEGL1','OTGL0030_FTECLEDA_${NORME_CF}_MVT_${HOST_PRDSIT}','O','')
			insert into BEST..TI17PERMFIL values ('EBS_SAP_OMG_STD',  'ESF_FICFROMONEGL','OTGL0030_FTECLEDA_${NORME_CF}_MVT_${HOST_PRDSIT}_${PARM_CRE_D}','O','')
			insert into BEST..TI17PERMFIL values ('EBS_SAP_OMG_STD',  'ESF_SAP_RETURN_CHECKS','${DFILI}/${ENV_PREFIX}_ESFD3960_${IDF_CT}_SAP_RETURN_CHECKS.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_SAP_OMG_STD',  'ESF_FTECLEDA_RA','${DFILP}/${ENV_PREFIX}_ESFD3960_${NORME_CF}_SAP_OMG_STD_FTECLEDA_RA_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_SAP_OMG_STD',  'ESF_FICFROMONEGLARC','${ESF_FICFROMONEGL1}_${PARM_INVCONSO_D}_${PARM_CONSOYEA}${PARM_CONSOMTH}_${PARM_CRE_D}','O','')
			insert into BEST..TI17PERMFIL values ('EBS_SAP_OMG_STD',  'ESF_FTECLEDA_POSTING','`if [ "${TYPEINV}" = "POC" ];then echo ${DFILP}/empty.dat;else echo ${DFILP}/${ENV_PREFIX}_ESFD3960_${NORME_CF}_SAP_OMG_STD_FTECLEDA_POSTING_${PARM_ICLODAT_D}.dat;fi;`','O','')
			insert into BEST..TI17PERMFIL values ('EBS_SAP_OMG_STD',  'ESF_FTECLEDA_MVT','${DFILP}/${ENV_PREFIX}_ESFD3960_${NORME_CF}_SAP_OMG_STD_FTECLEDA_MVT_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_SAP_OMG_STD',  'ESF_FTECLEDA_MVT_TMP','${DFILT}/${ENV_PREFIX}_ESFD3960_${IDF_CT}_FTECLEDA_MVT_${TYPEINV}_${PARM_ICLODAT_D}_${PARM_CRE_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_SAP_OMG_STD',  'ESF_FTECLEDA_POSTING_ARC_APRES','${ENV_PREFIX}_ESFD3960_${NORME_CF}_SAP_OMG_STD_FTECLEDA_POSTING_${PARM_ICLODAT_D}_apres_${PARM_CRE_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_SAP_OMG_STD',  'ESF_FTECLEDA_POSTING_ARC_AVANT','${ENV_PREFIX}_ESFD3960_${NORME_CF}_SAP_OMG_STD_FTECLEDA_POSTING_${PARM_ICLODAT_D}_avant_${PARM_CRE_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('EBSEMINV',  'EBS_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('EBSEQINV',  'EBS_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('EBSEQINVB',  'EBS_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('EBSEQPOC',  'EBS_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('EBSEQPOCB',  'EBS_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('EBSEQPOS',  'EBS_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('EBSEQPOSB',  'EBS_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('EBSEYINV',  'EBS_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('EBSEYINVB',  'EBS_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('EBSEYPOC',  'EBS_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('EBSEYPOCB',  'EBS_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('EBSEYPOS',  'EBS_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('EBSEYPOSB',  'EBS_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('EBSEQPOSP',  'EBS_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('EBSEYPOSP',  'EBS_SAP_OMG_STD','')

	----------IDF_CT:   I17G_SAP_OMG_STD ------------------

		insert into BEST..TI17FNC values ('I17G_SAP_OMG_STD','Integrate SAP file feedback to Omega','ESFD3960',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17G_SAP_OMG_STD',  'ESF_FTECLEDA_MVT_PREV','${DFILP}/${ENV_PREFIX}_ESFD3930_${NORME_CF}_DLT_SAP_STD_FTECLEDA_DELTA_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_SAP_OMG_STD',  'ESF_FICFROMONEGL1','OTGL0030_FTECLEDA_${NORME_CF}_MVT_${HOST_PRDSIT}','O','')
			insert into BEST..TI17PERMFIL values ('I17G_SAP_OMG_STD',  'ESF_FICFROMONEGL','OTGL0030_FTECLEDA_${NORME_CF}_MVT_${HOST_PRDSIT}_${PARM_CRE_D}','O','')
			insert into BEST..TI17PERMFIL values ('I17G_SAP_OMG_STD',  'ESF_SAP_RETURN_CHECKS','${DFILI}/${ENV_PREFIX}_ESFD3960_${IDF_CT}_SAP_RETURN_CHECKS.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_SAP_OMG_STD',  'ESF_FTECLEDA_RA','${DFILP}/${ENV_PREFIX}_ESFD3960_${NORME_CF}_SAP_OMG_STD_FTECLEDA_RA_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_SAP_OMG_STD',  'ESF_FICFROMONEGLARC','${ESF_FICFROMONEGL1}_${PARM_INVCONSO_D}_${PARM_CONSOYEA}${PARM_CONSOMTH}_${PARM_CRE_D}','O','')
			insert into BEST..TI17PERMFIL values ('I17G_SAP_OMG_STD',  'ESF_FTECLEDA_POSTING','${DFILP}/${ENV_PREFIX}_ESFD3960_${NORME_CF}_SAP_OMG_STD_FTECLEDA_POSTING_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_SAP_OMG_STD',  'ESF_FTECLEDA_MVT','${DFILP}/${ENV_PREFIX}_ESFD3960_${NORME_CF}_SAP_OMG_STD_FTECLEDA_MVT_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_SAP_OMG_STD',  'ESF_FTECLEDA_MVT_TMP','${DFILT}/${ENV_PREFIX}_ESFD3960_${IDF_CT}_FTECLEDA_MVT_${TYPEINV}_${PARM_ICLODAT_D}_${PARM_CRE_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_SAP_OMG_STD',  'ESF_FTECLEDA_POSTING_ARC_APRES','${ENV_PREFIX}_ESFD3960_${NORME_CF}_SAP_OMG_STD_FTECLEDA_POSTING_${PARM_ICLODAT_D}_apres_${PARM_CRE_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_SAP_OMG_STD',  'ESF_FTECLEDA_POSTING_ARC_AVANT','${ENV_PREFIX}_ESFD3960_${NORME_CF}_SAP_OMG_STD_FTECLEDA_POSTING_${PARM_ICLODAT_D}_avant_${PARM_CRE_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17GMINV',  'I17G_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('I17GQINV',  'I17G_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('I17GQINVB',  'I17G_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('I17GQPOS',  'I17G_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('I17GQPOSB',  'I17G_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('I17GYINV',  'I17G_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('I17GYINVB',  'I17G_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('I17GYPOS',  'I17G_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('I17GYPOSB',  'I17G_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('I17GQPOSP',  'I17G_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('I17GYPOSP',  'I17G_SAP_OMG_STD','')

	----------IDF_CT:   I17L_SAP_OMG_STD ------------------

		insert into BEST..TI17FNC values ('I17L_SAP_OMG_STD','Integrate SAP file feedback to Omega','ESFD3960',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17L_SAP_OMG_STD',  'ESF_FTECLEDA_MVT_PREV','${DFILP}/${ENV_PREFIX}_ESFD3930_${NORME_CF}_DLT_SAP_STD_FTECLEDA_DELTA_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_SAP_OMG_STD',  'ESF_FICFROMONEGL1','OTGL0030_FTECLEDA_${NORME_CF}_MVT_${HOST_PRDSIT}','O','')
			insert into BEST..TI17PERMFIL values ('I17L_SAP_OMG_STD',  'ESF_FICFROMONEGL','OTGL0030_FTECLEDA_${NORME_CF}_MVT_${HOST_PRDSIT}_${PARM_CRE_D}','O','')
			insert into BEST..TI17PERMFIL values ('I17L_SAP_OMG_STD',  'ESF_SAP_RETURN_CHECKS','${DFILI}/${ENV_PREFIX}_ESFD3960_${IDF_CT}_SAP_RETURN_CHECKS.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_SAP_OMG_STD',  'ESF_FTECLEDA_RA','${DFILP}/${ENV_PREFIX}_ESFD3960_${NORME_CF}_SAP_OMG_STD_FTECLEDA_RA_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_SAP_OMG_STD',  'ESF_FICFROMONEGLARC','${ESF_FICFROMONEGL1}_${PARM_INVCONSO_D}_${PARM_CONSOYEA}${PARM_CONSOMTH}_${PARM_CRE_D}','O','')
			insert into BEST..TI17PERMFIL values ('I17L_SAP_OMG_STD',  'ESF_FTECLEDA_POSTING','${DFILP}/${ENV_PREFIX}_ESFD3960_${NORME_CF}_SAP_OMG_STD_FTECLEDA_POSTING_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_SAP_OMG_STD',  'ESF_FTECLEDA_MVT','${DFILP}/${ENV_PREFIX}_ESFD3960_${NORME_CF}_SAP_OMG_STD_FTECLEDA_MVT_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_SAP_OMG_STD',  'ESF_FTECLEDA_MVT_TMP','${DFILT}/${ENV_PREFIX}_ESFD3960_${IDF_CT}_FTECLEDA_MVT_${TYPEINV}_${PARM_ICLODAT_D}_${PARM_CRE_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_SAP_OMG_STD',  'ESF_FTECLEDA_POSTING_ARC_APRES','${ENV_PREFIX}_ESFD3960_${NORME_CF}_SAP_OMG_STD_FTECLEDA_POSTING_${PARM_ICLODAT_D}_apres_${PARM_CRE_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_SAP_OMG_STD',  'ESF_FTECLEDA_POSTING_ARC_AVANT','${ENV_PREFIX}_ESFD3960_${NORME_CF}_SAP_OMG_STD_FTECLEDA_POSTING_${PARM_ICLODAT_D}_avant_${PARM_CRE_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17LMINV',  'I17L_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('I17LQINV',  'I17L_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('I17LQINVB',  'I17L_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('I17LQPOS',  'I17L_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('I17LQPOSB',  'I17L_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('I17LYINV',  'I17L_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('I17LYINVB',  'I17L_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('I17LYPOS',  'I17L_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('I17LYPOSB',  'I17L_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('I17LQPOSP',  'I17L_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('I17LYPOSP',  'I17L_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('I17LQPOSX',  'I17L_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('I17LYPOSX',  'I17L_SAP_OMG_STD','')

	----------IDF_CT:   I17P_SAP_OMG_STD ------------------

		insert into BEST..TI17FNC values ('I17P_SAP_OMG_STD','Integrate SAP file feedback to Omega','ESFD3960',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17P_SAP_OMG_STD',  'ESF_FTECLEDA_MVT_PREV','${DFILP}/${ENV_PREFIX}_ESFD3930_${NORME_CF}_DLT_SAP_STD_FTECLEDA_DELTA_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_SAP_OMG_STD',  'ESF_FICFROMONEGL1','OTGL0030_FTECLEDA_${NORME_CF}_MVT_${HOST_PRDSIT}','O','')
			insert into BEST..TI17PERMFIL values ('I17P_SAP_OMG_STD',  'ESF_FICFROMONEGL','OTGL0030_FTECLEDA_${NORME_CF}_MVT_${HOST_PRDSIT}_${PARM_CRE_D}','O','')
			insert into BEST..TI17PERMFIL values ('I17P_SAP_OMG_STD',  'ESF_SAP_RETURN_CHECKS','${DFILI}/${ENV_PREFIX}_ESFD3960_${IDF_CT}_SAP_RETURN_CHECKS.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_SAP_OMG_STD',  'ESF_FTECLEDA_RA','${DFILP}/${ENV_PREFIX}_ESFD3960_${NORME_CF}_SAP_OMG_STD_FTECLEDA_RA_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_SAP_OMG_STD',  'ESF_FICFROMONEGLARC','${ESF_FICFROMONEGL1}_${PARM_INVCONSO_D}_${PARM_CONSOYEA}${PARM_CONSOMTH}_${PARM_CRE_D}','O','')
			insert into BEST..TI17PERMFIL values ('I17P_SAP_OMG_STD',  'ESF_FTECLEDA_POSTING','${DFILP}/${ENV_PREFIX}_ESFD3960_${NORME_CF}_SAP_OMG_STD_FTECLEDA_POSTING_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_SAP_OMG_STD',  'ESF_FTECLEDA_MVT','${DFILP}/${ENV_PREFIX}_ESFD3960_${NORME_CF}_SAP_OMG_STD_FTECLEDA_MVT_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_SAP_OMG_STD',  'ESF_FTECLEDA_MVT_TMP','${DFILT}/${ENV_PREFIX}_ESFD3960_${IDF_CT}_FTECLEDA_MVT_${TYPEINV}_${PARM_ICLODAT_D}_${PARM_CRE_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_SAP_OMG_STD',  'ESF_FTECLEDA_POSTING_ARC_APRES','${ENV_PREFIX}_ESFD3960_${NORME_CF}_SAP_OMG_STD_FTECLEDA_POSTING_${PARM_ICLODAT_D}_apres_${PARM_CRE_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_SAP_OMG_STD',  'ESF_FTECLEDA_POSTING_ARC_AVANT','${ENV_PREFIX}_ESFD3960_${NORME_CF}_SAP_OMG_STD_FTECLEDA_POSTING_${PARM_ICLODAT_D}_avant_${PARM_CRE_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17PMINV',  'I17P_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('I17PQINV',  'I17P_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('I17PQINVB',  'I17P_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('I17PQPOS',  'I17P_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('I17PQPOSB',  'I17P_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('I17PYINV',  'I17P_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('I17PYINVB',  'I17P_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('I17PYPOS',  'I17P_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('I17PYPOSB',  'I17P_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('I17PQPOSP',  'I17P_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('I17PYPOSP',  'I17P_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('I17PQPOSX',  'I17P_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('I17PYPOSX',  'I17P_SAP_OMG_STD','')

	----------IDF_CT:   I17S_SAP_OMG_STD ------------------

		insert into BEST..TI17FNC values ('I17S_SAP_OMG_STD','Integrate SAP file feedback to Omega','ESFD3960',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17S_SAP_OMG_STD',  'ESF_FTECLEDA_MVT_PREV','${DFILP}/${ENV_PREFIX}_ESFD3930_${NORME_CF}_DLT_SAP_STD_FTECLEDA_DELTA_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_SAP_OMG_STD',  'ESF_FICFROMONEGL1','OTGL0030_FTECLEDA_${NORME_CF}_MVT_${HOST_PRDSIT}','O','')
			insert into BEST..TI17PERMFIL values ('I17S_SAP_OMG_STD',  'ESF_FICFROMONEGL','OTGL0030_FTECLEDA_${NORME_CF}_MVT_${HOST_PRDSIT}_${PARM_CRE_D}','O','')
			insert into BEST..TI17PERMFIL values ('I17S_SAP_OMG_STD',  'ESF_SAP_RETURN_CHECKS','${DFILI}/${ENV_PREFIX}_ESFD3960_${IDF_CT}_SAP_RETURN_CHECKS.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_SAP_OMG_STD',  'ESF_FTECLEDA_RA','${DFILP}/${ENV_PREFIX}_ESFD3960_${NORME_CF}_SAP_OMG_STD_FTECLEDA_RA_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_SAP_OMG_STD',  'ESF_FICFROMONEGLARC','${ESF_FICFROMONEGL1}_${PARM_INVCONSO_D}_${PARM_CONSOYEA}${PARM_CONSOMTH}_${PARM_CRE_D}','O','')
			insert into BEST..TI17PERMFIL values ('I17S_SAP_OMG_STD',  'ESF_FTECLEDA_POSTING','${DFILP}/${ENV_PREFIX}_ESFD3960_${NORME_CF}_SAP_OMG_STD_FTECLEDA_POSTING_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_SAP_OMG_STD',  'ESF_FTECLEDA_MVT','${DFILP}/${ENV_PREFIX}_ESFD3960_${NORME_CF}_SAP_OMG_STD_FTECLEDA_MVT_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_SAP_OMG_STD',  'ESF_FTECLEDA_MVT_TMP','${DFILT}/${ENV_PREFIX}_ESFD3960_${IDF_CT}_FTECLEDA_MVT_${TYPEINV}_${PARM_ICLODAT_D}_${PARM_CRE_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_SAP_OMG_STD',  'ESF_FTECLEDA_POSTING_ARC_APRES','${ENV_PREFIX}_ESFD3960_${NORME_CF}_SAP_OMG_STD_FTECLEDA_POSTING_${PARM_ICLODAT_D}_apres_${PARM_CRE_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_SAP_OMG_STD',  'ESF_FTECLEDA_POSTING_ARC_AVANT','${ENV_PREFIX}_ESFD3960_${NORME_CF}_SAP_OMG_STD_FTECLEDA_POSTING_${PARM_ICLODAT_D}_avant_${PARM_CRE_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17SMINV',  'I17S_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('I17SQINV',  'I17S_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('I17SQINVB',  'I17S_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('I17SQPOS',  'I17S_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('I17SQPOSB',  'I17S_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('I17SYINV',  'I17S_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('I17SYINVB',  'I17S_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('I17SYPOS',  'I17S_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('I17SYPOSB',  'I17S_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('I17SQPOSP',  'I17S_SAP_OMG_STD','')
			insert into BEST..TI17REQFNC values ('I17SYPOSP',  'I17S_SAP_OMG_STD','')
go

