-------------------------------
--mapping of  ESPD0060

	----------   Clean tables   ---------------------

	delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESPD0060')
	delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESPD0060')
	delete BEST..TI17FNC where CHAIN_CT='ESPD0060'
	delete BEST..TI17CHN  where CHAIN_CT='ESPD0060'

	insert into BEST..TI17CHN values ('ESPD0060',  '')

	----------IDF_CT:   EBS_ESPD0060 ------------------

		insert into BEST..TI17FNC values ('EBS_ESPD0060',' ','ESPD0060',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('EBS_ESPD0060',  'ESF_IADPERICASE_BBNI','${DFILP}/${ENV_PREFIX}_ESFD5060_IADPERICASE_BBNI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')	
			insert into BEST..TI17PERMFIL values ('EBS_ESPD0060',  'ESF_IRDPERICASE_BBNI','${DFILP}/${ENV_PREFIX}_ESFD5060_IRDPERICASE_BBNI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')

			insert into BEST..TI17PERMFIL values ('EBS_ESPD0060',  'ESF_IADPERICASE_INI','${DFILP}/${ENV_PREFIX}_ESFD5060_IADPERICASE_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')	
			insert into BEST..TI17PERMFIL values ('EBS_ESPD0060',  'ESF_IRDPERICASE_INI','${DFILP}/${ENV_PREFIX}_ESFD5060_IRDPERICASE_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')			
			insert into BEST..TI17PERMFIL values ('EBS_ESPD0060',  'ESF_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK_TXT.dat','I','')			
			
			insert into BEST..TI17PERMFIL values ('EBS_ESPD0060',  'EPO_FULTIMATES','${DFILP}/${ENV_PREFIX}_ESCJ0660_FULTIMATES.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD0060',  'ESF_GROUPING_TC_TOOMIT','${DFILP}/${ENV_PREFIX}_ESPD0060_GROUPING_TC_TOOMIT.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD0060',  'EPO_EPOSOCI','${DFILP}/${ENV_PREFIX}_ESPD0060_EPO_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			--insert into BEST..TI17PERMFIL values ('EBS_ESPD0060',  'ESF_EPOSOCI_BBNI','${DFILP}/${ENV_PREFIX}_ESPD0060_EPO_BBNI_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			--insert into BEST..TI17PERMFIL values ('EBS_ESPD0060',  'ESF_EPOSOCI_INI','${DFILP}/${ENV_PREFIX}_ESPD0060_EPO_INI_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')			
			insert into BEST..TI17PERMFIL values ('EBS_ESPD0060',  'EPO_FCTRFWH','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTRFWH_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD0060',  'ESF_GAAPMAP','${DFILP}/${ENV_PREFIX}_ESPD0060_GAAPMAP_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD0060',  'EPO_FCTREST0','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTREST0_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD0060',  'EPO_FCTRESTA','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTRESTA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD0060',  'EPO_FCTRESTF','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTRESTF_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD0060',  'EPO_FTRSLNK8','${DFILP}/${ENV_PREFIX}_ESPD0060_FTRSLNK8_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD0060',  'EPO_FULAERAT','${DFILP}/${ENV_PREFIX}_ESPD0060_FULAERAT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD0060',  'ESF_NDIC_NCB','${DFILP}/${ENV_PREFIX}_ESPD0060_NDIC_NCB_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD0060',  'EPO_FCTRESTF0','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTRESTF0_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD0060',  'EPO_FRISKMSII','${DFILP}/${ENV_PREFIX}_ESPD0060_FRISKMSII_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD0060',  'EPO_FPLACEMT22','${DFILP}/${ENV_PREFIX}_ESPD0060_FPLACEMT22_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD0060',  'ESF_TAXRETMGNT','${DFILP}/${ENV_PREFIX}_ESPD0060_TAXRETMGNT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD0060',  'EPO_FCTRGROLESII','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTRGROLE_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD0060',  'EPO_FULTIMATESSII','${DFILP}/${ENV_PREFIX}_ESPD0060_FULTIMATES_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD0060',  'ESF_NDIC_NCB_RET','${DFILP}/${ENV_PREFIX}_ESPD0060_NDIC_NCB_RET_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD0060',  'EPO_FSEGPATTERNFWH','${DFILP}/${ENV_PREFIX}_ESPD0060_FSEGPATTERNFWH_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD0060',  'EPO_FSEGPATTERN_BDT','${DFILP}/${ENV_PREFIX}_ESPD0060_FSEGPATTERN_BDT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD0060',  'EPO_FSEGPATTERN_CSF','${DFILP}/${ENV_PREFIX}_ESPD0060_FSEGPATTERN_CSF_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD0060',  'EPO_FSEGPATTERN_DSC','${DFILP}/${ENV_PREFIX}_ESPD0060_FSEGPATTERN_DSC_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD0060',  'EPO_FSEGPATTERN_ICR','${DFILP}/${ENV_PREFIX}_ESPD0060_FSEGPATTERN_ICR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD0060',  'EPO_FSEGPATTERN_INF','${DFILP}/${ENV_PREFIX}_ESPD0060_FSEGPATTERN_INF_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD0060',  'EPO_FSEGEST_SOLVENCY','${DFILP}/${ENV_PREFIX}_ESPD0060_FSEGEST_SOLVENCY_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD0060',  'EPO_RETITDPRM_UPR_ACT','${DFILP}/${ENV_PREFIX}_ESPD0060_RETITDPRM_UPR_ACT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('EBSEYPOCB',  'EBS_ESPD0060','')
			insert into BEST..TI17REQFNC values ('EBSEYPOS',  'EBS_ESPD0060','')
			insert into BEST..TI17REQFNC values ('EBSEYPOC',  'EBS_ESPD0060','')
			insert into BEST..TI17REQFNC values ('EBSEMINV',  'EBS_ESPD0060','')
			insert into BEST..TI17REQFNC values ('EBSEQINV',  'EBS_ESPD0060','')
			insert into BEST..TI17REQFNC values ('EBSEQPOC',  'EBS_ESPD0060','')
			insert into BEST..TI17REQFNC values ('EBSEQPOCB',  'EBS_ESPD0060','')
			insert into BEST..TI17REQFNC values ('EBSEQPOS',  'EBS_ESPD0060','')
			insert into BEST..TI17REQFNC values ('EBSEYINV',  'EBS_ESPD0060','')

	----------IDF_CT:   I4I_ESPD0060 ------------------

		insert into BEST..TI17FNC values ('I4I_ESPD0060',' ','ESPD0060',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I4I_ESPD0060',  'EPO_FULTIMATES','${DFILP}/${ENV_PREFIX}_ESEH1200_FULTIMATES_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD0060',  'EPO_EPOSOCI','${DFILP}/${ENV_PREFIX}_ESPD0060_EPSOC_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD0060',  'EPO_FCTRFWH','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTRFWH_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD0060',  'ESF_GAAPMAP','${DFILP}/${ENV_PREFIX}_ESPD0060_GAAPMAP_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD0060',  'EPO_FTRSLNK8','${DFILP}/${ENV_PREFIX}_ESPD0060_FTRSLNK8_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD0060',  'EPO_FULAERAT','${DFILP}/${ENV_PREFIX}_ESPD0060_FULAERAT_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD0060',  'EPO_FRISKMSII','${DFILP}/${ENV_PREFIX}_ESPD0060_FRISKMSII_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD0060',  'EPO_FPLACEMT22','${DFILP}/${ENV_PREFIX}_ESPD0060_FPLACEMT22_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD0060',  'ESF_TAXRETMGNT','${DFILP}/${ENV_PREFIX}_ESPD0060_TAXRETMGNT_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD0060',  'EPO_CADVPERIESB0','${DFILP}/${ENV_PREFIX}_ESPD0060_CADVPERIESB0_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD0060',  'EPO_FSEGPATTERNFWH','${DFILP}/${ENV_PREFIX}_ESPD0060_FSEGPATTERNFWH_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD0060',  'EPO_RETITDPRM_UPR_ACT','${DFILP}/${ENV_PREFIX}_ESPD0060_RETITDPRM_UPR_ACT_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I4IQPOC',  'I4I_ESPD0060','')
			insert into BEST..TI17REQFNC values ('I4IQPOCB',  'I4I_ESPD0060','')
			insert into BEST..TI17REQFNC values ('I4IQPOS',  'I4I_ESPD0060','')
			insert into BEST..TI17REQFNC values ('I4IQPOSB',  'I4I_ESPD0060','')
			insert into BEST..TI17REQFNC values ('I4IYPOC',  'I4I_ESPD0060','')
			insert into BEST..TI17REQFNC values ('I4IYPOCB',  'I4I_ESPD0060','')
			insert into BEST..TI17REQFNC values ('I4IYPOS',  'I4I_ESPD0060','')
			insert into BEST..TI17REQFNC values ('I4IYPOSB',  'I4I_ESPD0060','')
go

