-------------------------------
--mapping of  ESFD3690

	----------   Clean tables   ---------------------

	delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD3690')
	delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD3690')
	delete BEST..TI17FNC where CHAIN_CT='ESFD3690'
	delete BEST..TI17CHN  where CHAIN_CT='ESFD3690'

	insert into BEST..TI17CHN values ('ESFD3690',  'Revenue Calculation')

	----------IDF_CT:   I17G_IRV_ALL_STD ------------------

		insert into BEST..TI17FNC values ('I17G_IRV_ALL_STD','revenue calculation','ESFD3690',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17G_IRV_ALL_STD',  'EST_IRDPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE0_I17G_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_IRV_ALL_STD',  'EST_IADPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17G_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_IRV_ALL_STD',  'ESF_RATIO_RET_P','${DFILP}/${ENV_PREFIX}_ESFD3640_I17G_IVR_CHR_STD_RATIO_RET_P_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_IRV_ALL_STD',  'ESF_RATIO_RET_NP','${DFILP}/${ENV_PREFIX}_ESFD3640_I17G_IVR_CHR_STD_RATIO_RET_NP_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_IRV_ALL_STD',  'ESF_RATIO_ASSUMED','${DFILP}/${ENV_PREFIX}_ESFD3640_I17G_IVR_CHR_STD_RATIO_ASSUMED_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_IRV_ALL_STD',  'ESF_GTSII_DAC_FWD','${DFILP}/${ENV_PREFIX}_ESFD3640_I17G_IVR_CHR_STD_DAC_FWD_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_IRV_ALL_STD',  'ESF_GTSII_DAC_LKI','${DFILP}/${ENV_PREFIX}_ESFD3640_I17G_IVR_CHR_STD_DAC_LKI_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_IRV_ALL_STD',  'ESF_GTSII_DSC_LKI_ESCOMPTE','${DFILP}/${ENV_PREFIX}_ESFD3620_I17G_DSC_LKI_STD_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_IRV_ALL_STD',  'ESF_GTSII_RAD_LKI_ESCOMPTE','${DFILP}/${ENV_PREFIX}_ESFD3620_I17G_RAD_LKI_STD_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_IRV_ALL_STD',  'ESF_GTSII_DSC_FWD_ESCOMPTE','${DFILP}/${ENV_PREFIX}_ESFD3660_I17G_UWD_ALL_STD_GTSII_ESCOMPTE_FWD_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_IRV_ALL_STD',  'ESF_GTSII_DSC_BDT_LKI','${DFILP}/${ENV_PREFIX}_ESFD3690_I17G_IRV_ALL_STD_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_IRV_ALL_STD',  'ESF_GTSII_IFRS17_CSM','${DFILP}/${ENV_PREFIX}_ESFD3690_I17G_IRV_ALL_STD_GTSII_IFRS17_CSM${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_IRV_ALL_STD',  'ESF_GTSII_DSC_BDT_FWD','${DFILP}/${ENV_PREFIX}_ESFD3690_I17G_IRV_ALL_STD_GTSII_ESCOMPTE_FWD_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_IRV_ALL_STD',  'ESF_GTSII_IFRS17_REVENUE','${DFILP}/${ENV_PREFIX}_ESFD3690_I17G_IRV_ALL_STD_GTSII_IFRS17_REVENUE${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17GQPOS',  'I17G_IRV_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17GYINV',  'I17G_IRV_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17GYPOS',  'I17G_IRV_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17GMINV',  'I17G_IRV_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17GQINV',  'I17G_IRV_ALL_STD','')

	----------IDF_CT:   I17L_IRV_ALL_STD ------------------

		insert into BEST..TI17FNC values ('I17L_IRV_ALL_STD','revenue calculation','ESFD3690',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17L_IRV_ALL_STD',  'EST_IRDPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE0_I17L_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_IRV_ALL_STD',  'EST_IADPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17L_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_IRV_ALL_STD',  'ESF_RATIO_RET_P','${DFILP}/${ENV_PREFIX}_ESFD3640_I17L_IVR_CHR_STD_RATIO_RET_P_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_IRV_ALL_STD',  'ESF_RATIO_RET_NP','${DFILP}/${ENV_PREFIX}_ESFD3640_I17L_IVR_CHR_STD_RATIO_RET_NP_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_IRV_ALL_STD',  'ESF_RATIO_ASSUMED','${DFILP}/${ENV_PREFIX}_ESFD3640_I17L_IVR_CHR_STD_RATIO_ASSUMED_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_IRV_ALL_STD',  'ESF_GTSII_DAC_FWD','${DFILP}/${ENV_PREFIX}_ESFD3640_I17L_IVR_CHR_STD_DAC_FWD_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_IRV_ALL_STD',  'ESF_GTSII_DSC_FWD_ESCOMPTE','${DFILP}/${ENV_PREFIX}_ESFD3660_I17L_UWD_ALL_STD_GTSII_ESCOMPTE_FWD_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_IRV_ALL_STD',  'ESF_GTSII_DAC_LKI','${DFILP}/${ENV_PREFIX}_ESFD3640_I17L_IVR_CHR_STD_DAC_LKI_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_IRV_ALL_STD',  'ESF_GTSII_DSC_LKI_ESCOMPTE','${DFILP}/${ENV_PREFIX}_ESFD3620_I17L_DSC_LKI_STD_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_IRV_ALL_STD',  'ESF_GTSII_RAD_LKI_ESCOMPTE','${DFILP}/${ENV_PREFIX}_ESFD3620_I17L_RAD_LKI_STD_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_IRV_ALL_STD',  'ESF_GTSII_DSC_BDT_LKI','${DFILP}/${ENV_PREFIX}_ESFD3690_I17L_IRV_ALL_STD_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_IRV_ALL_STD',  'ESF_GTSII_IFRS17_CSM','${DFILP}/${ENV_PREFIX}_ESFD3690_I17L_IRV_ALL_STD_GTSII_IFRS17_CSM${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_IRV_ALL_STD',  'ESF_GTSII_DSC_BDT_FWD','${DFILP}/${ENV_PREFIX}_ESFD3690_I17L_IRV_ALL_STD_GTSII_ESCOMPTE_FWD_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_IRV_ALL_STD',  'ESF_GTSII_IFRS17_REVENUE','${DFILP}/${ENV_PREFIX}_ESFD3690_I17L_IRV_ALL_STD_GTSII_IFRS17_REVENUE${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17LQPOSX',  'I17L_IRV_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17LYPOSX',  'I17L_IRV_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17LMINV',  'I17L_IRV_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17LQINV',  'I17L_IRV_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17LQPOS',  'I17L_IRV_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17LYINV',  'I17L_IRV_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17LYPOS',  'I17L_IRV_ALL_STD','')

	----------IDF_CT:   I17P_IRV_ALL_STD ------------------

		insert into BEST..TI17FNC values ('I17P_IRV_ALL_STD','revenue calculation','ESFD3690',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17P_IRV_ALL_STD',  'EST_IRDPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE0_I17P_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_IRV_ALL_STD',  'EST_IADPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17P_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_IRV_ALL_STD',  'ESF_RATIO_RET_P','${DFILP}/${ENV_PREFIX}_ESFD3640_I17P_IVR_CHR_STD_RATIO_RET_P_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_IRV_ALL_STD',  'ESF_RATIO_RET_NP','${DFILP}/${ENV_PREFIX}_ESFD3640_I17P_IVR_CHR_STD_RATIO_RET_NP_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_IRV_ALL_STD',  'ESF_RATIO_ASSUMED','${DFILP}/${ENV_PREFIX}_ESFD3640_I17P_IVR_CHR_STD_RATIO_ASSUMED_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_IRV_ALL_STD',  'ESF_GTSII_DAC_FWD','${DFILP}/${ENV_PREFIX}_ESFD3640_I17P_IVR_CHR_STD_DAC_FWD_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_IRV_ALL_STD',  'ESF_GTSII_DSC_FWD_ESCOMPTE','${DFILP}/${ENV_PREFIX}_ESFD3660_I17P_UWD_ALL_STD_GTSII_ESCOMPTE_FWD_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_IRV_ALL_STD',  'ESF_GTSII_DAC_LKI','${DFILP}/${ENV_PREFIX}_ESFD3640_I17P_IVR_CHR_STD_DAC_LKI_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_IRV_ALL_STD',  'ESF_GTSII_DSC_LKI_ESCOMPTE','${DFILP}/${ENV_PREFIX}_ESFD3620_I17P_DSC_LKI_STD_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_IRV_ALL_STD',  'ESF_GTSII_RAD_LKI_ESCOMPTE','${DFILP}/${ENV_PREFIX}_ESFD3620_I17P_RAD_LKI_STD_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_IRV_ALL_STD',  'ESF_GTSII_DSC_BDT_LKI','${DFILP}/${ENV_PREFIX}_ESFD3690_I17P_IRV_ALL_STD_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_IRV_ALL_STD',  'ESF_GTSII_IFRS17_CSM','${DFILP}/${ENV_PREFIX}_ESFD3690_I17P_IRV_ALL_STD_GTSII_IFRS17_CSM${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_IRV_ALL_STD',  'ESF_GTSII_DSC_BDT_FWD','${DFILP}/${ENV_PREFIX}_ESFD3690_I17P_IRV_ALL_STD_GTSII_ESCOMPTE_FWD_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_IRV_ALL_STD',  'ESF_GTSII_IFRS17_REVENUE','${DFILP}/${ENV_PREFIX}_ESFD3690_I17P_IRV_ALL_STD_GTSII_IFRS17_REVENUE${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17PMINV',  'I17P_IRV_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17PQINV',  'I17P_IRV_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17PQPOS',  'I17P_IRV_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17PYINV',  'I17P_IRV_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17PYPOS',  'I17P_IRV_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17PQPOSX',  'I17P_IRV_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17PYPOSX',  'I17P_IRV_ALL_STD','')

	----------IDF_CT:   I17S_IRV_ALL_STD ------------------

		insert into BEST..TI17FNC values ('I17S_IRV_ALL_STD','revenue calculation','ESFD3690',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17S_IRV_ALL_STD',  'EST_IRDPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE0_I17S_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_IRV_ALL_STD',  'EST_IADPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17S_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_IRV_ALL_STD',  'ESF_RATIO_RET_P','${DFILP}/${ENV_PREFIX}_ESFD3640_I17S_IVR_CHR_STD_RATIO_RET_P_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_IRV_ALL_STD',  'ESF_RATIO_RET_NP','${DFILP}/${ENV_PREFIX}_ESFD3640_I17S_IVR_CHR_STD_RATIO_RET_NP_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_IRV_ALL_STD',  'ESF_RATIO_ASSUMED','${DFILP}/${ENV_PREFIX}_ESFD3640_I17S_IVR_CHR_STD_RATIO_ASSUMED_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_IRV_ALL_STD',  'ESF_GTSII_DAC_FWD','${DFILP}/${ENV_PREFIX}_ESFD3640_I17S_IVR_CHR_STD_DAC_FWD_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_IRV_ALL_STD',  'ESF_GTSII_DAC_LKI','${DFILP}/${ENV_PREFIX}_ESFD3640_I17S_IVR_CHR_STD_DAC_LKI_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_IRV_ALL_STD',  'ESF_GTSII_DSC_LKI_ESCOMPTE','${DFILP}/${ENV_PREFIX}_ESFD3620_I17S_DSC_LKI_STD_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_IRV_ALL_STD',  'ESF_GTSII_RAD_LKI_ESCOMPTE','${DFILP}/${ENV_PREFIX}_ESFD3620_I17S_RAD_LKI_STD_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_IRV_ALL_STD',  'ESF_GTSII_DSC_FWD_ESCOMPTE','${DFILP}/${ENV_PREFIX}_ESFD3660_I17S_UWD_ALL_STD_GTSII_ESCOMPTE_FWD_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_IRV_ALL_STD',  'ESF_GTSII_DSC_BDT_LKI','${DFILP}/${ENV_PREFIX}_ESFD3690_I17S_IRV_ALL_STD_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_IRV_ALL_STD',  'ESF_GTSII_IFRS17_CSM','${DFILP}/${ENV_PREFIX}_ESFD3690_I17S_IRV_ALL_STD_GTSII_IFRS17_CSM${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_IRV_ALL_STD',  'ESF_GTSII_DSC_BDT_FWD','${DFILP}/${ENV_PREFIX}_ESFD3690_I17S_IRV_ALL_STD_GTSII_ESCOMPTE_FWD_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_IRV_ALL_STD',  'ESF_GTSII_IFRS17_REVENUE','${DFILP}/${ENV_PREFIX}_ESFD3690_I17S_IRV_ALL_STD_GTSII_IFRS17_REVENUE${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17SMINV',  'I17S_IRV_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17SQINV',  'I17S_IRV_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17SQPOS',  'I17S_IRV_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17SYINV',  'I17S_IRV_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17SYPOS',  'I17S_IRV_ALL_STD','')
go

