-------------------------------
--mapping of  ESFD5000

	----------   Clean tables   ---------------------

	delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD5000')
	delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD5000')
	delete BEST..TI17FNC where CHAIN_CT='ESFD5000'
	delete BEST..TI17CHN  where CHAIN_CT='ESFD5000'

	insert into BEST..TI17CHN values ('ESFD5000',  'Proto Pericase Ini Generation')

	----------IDF_CT:   I17G_TMP_PER_INI ------------------

		insert into BEST..TI17FNC values ('I17G_TMP_PER_INI','Group - Proto Pericase Ini Generation','ESFD5000',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17G_TMP_PER_INI',  'EST_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_TMP_PER_INI',  'EST_FSOBBLOB','${DFILP}/${ENV_PREFIX}_ESCJ0660_FSOBBLOB.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_TMP_PER_INI',  'ESF_FCES','${DFILI}/${ENV_PREFIX}_ESFD5000_I17G_TMP_PER_INI_FCES_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_TMP_PER_INI',  'ESF_FPLC','${DFILI}/${ENV_PREFIX}_ESFD5000_I17G_TMP_PER_INI_FPLC_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_TMP_PER_INI',  'ESF_FCTRGRO','${DFILI}/${ENV_PREFIX}_ESFD5000_I17G_TMP_PER_INI_FCTRGRO_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_TMP_PER_INI',  'ESF_FCTRULT','${DFILI}/${ENV_PREFIX}_ESFD5000_I17G_TMP_PER_INI_FCTRULT_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_TMP_PER_INI',  'ESF_FMARKET','${DFILI}/${ENV_PREFIX}_ESFD5000_I17G_TMP_PER_INI_FMARKET_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_TMP_PER_INI',  'ESF_FCTRGRO1','${DFILI}/${ENV_PREFIX}_ESFD5000_I17G_TMP_PER_INI_FCTRGRO1_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_TMP_PER_INI',  'ESF_FPLACEMT0','${DFILI}/${ENV_PREFIX}_ESFD5000_I17G_TMP_PER_INI_FPLACEMT0_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_TMP_PER_INI',  'ESF_FPLACEMT2','${DFILI}/${ENV_PREFIX}_ESFD5000_I17G_TMP_PER_INI_FPLACEMT2_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_TMP_PER_INI',  'ESF_FPLATXCUM','${DFILI}/${ENV_PREFIX}_ESFD5000_I17G_TMP_PER_INI_FPLATXCUM_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_TMP_PER_INI',  'ESF_IADPERIFR','${DFILI}/${ENV_PREFIX}_ESFD5000_I17G_TMP_PER_INI_IADPERIFR_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_TMP_PER_INI',  'ESF_FULTIMATES','${DFILI}/${ENV_PREFIX}_ESFD5000_I17G_TMP_PER_INI_FULTIMATES_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_TMP_PER_INI',  'ESF_IADPERIFCI','${DFILI}/${ENV_PREFIX}_ESFD5000_I17G_TMP_PER_INI_IADPERIFCI_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_TMP_PER_INI',  'ESF_IADPERIFCT','${DFILI}/${ENV_PREFIX}_ESFD5000_I17G_TMP_PER_INI_IADPERIFCT_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_TMP_PER_INI',  'ESF_FCTRGROLESII','${DFILI}/${ENV_PREFIX}_ESFD5000_I17G_TMP_PER_INI_FCTRGROLESII_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_TMP_PER_INI',  'ESF_FPLATXCUMALL','${DFILI}/${ENV_PREFIX}_ESFD5000_I17G_TMP_PER_INI_FPLATXCUMALL_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_TMP_PER_INI',  'EST_IADPERICASE_INI','${DFILI}/${ENV_PREFIX}_ESFD5000_I17G_TMP_PER_INI_IADPERICASE_INI_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_TMP_PER_INI',  'EST_IRDPERICASE_INI','${DFILI}/${ENV_PREFIX}_ESFD5000_I17G_TMP_PER_INI_IRDPERICASE_INI_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_TMP_PER_INI',  'ESF_FLORETFACTOR_INI','${DFILI}/${ENV_PREFIX}_ESFD5000_I17G_TMP_PER_INI_FLORETFACTOR_INI_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_TMP_PER_INI',  'EST_IADPERICASE0_INI','${DFILI}/${ENV_PREFIX}_ESFD5000_I17G_TMP_PER_INI_IADPERICASE0_INI_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_TMP_PER_INI',  'EST_IADPERICASE_DUMMY_INI','${DFILI}/${ENV_PREFIX}_ESFD5000_I17G_TMP_PER_INI_IADPERICASE_DUMMY_INI_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17GMINV',  'I17G_TMP_PER_INI','')
			insert into BEST..TI17REQFNC values ('I17GQINV',  'I17G_TMP_PER_INI','')
			insert into BEST..TI17REQFNC values ('I17GQPOS',  'I17G_TMP_PER_INI','')
			insert into BEST..TI17REQFNC values ('I17GYINV',  'I17G_TMP_PER_INI','')
			insert into BEST..TI17REQFNC values ('I17GYPOS',  'I17G_TMP_PER_INI','')

	----------IDF_CT:   I17L_TMP_PER_INI ------------------

		insert into BEST..TI17FNC values ('I17L_TMP_PER_INI','Local - Proto Pericase Ini Generation','ESFD5000',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17L_TMP_PER_INI',  'EST_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_TMP_PER_INI',  'EST_FSOBBLOB','${DFILP}/${ENV_PREFIX}_ESCJ0660_FSOBBLOB.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_TMP_PER_INI',  'ESF_FCES','${DFILI}/${ENV_PREFIX}_ESFD5000_I17L_TMP_PER_INI_FCES_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_TMP_PER_INI',  'ESF_FPLC','${DFILI}/${ENV_PREFIX}_ESFD5000_I17L_TMP_PER_INI_FPLC_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_TMP_PER_INI',  'ESF_FCTRGRO','${DFILI}/${ENV_PREFIX}_ESFD5000_I17L_TMP_PER_INI_FCTRGRO_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_TMP_PER_INI',  'ESF_FCTRULT','${DFILI}/${ENV_PREFIX}_ESFD5000_I17L_TMP_PER_INI_FCTRULT_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_TMP_PER_INI',  'ESF_FMARKET','${DFILI}/${ENV_PREFIX}_ESFD5000_I17L_TMP_PER_INI_FMARKET_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_TMP_PER_INI',  'ESF_FCTRGRO1','${DFILI}/${ENV_PREFIX}_ESFD5000_I17L_TMP_PER_INI_FCTRGRO1_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_TMP_PER_INI',  'ESF_FPLACEMT0','${DFILI}/${ENV_PREFIX}_ESFD5000_I17L_TMP_PER_INI_FPLACEMT0_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_TMP_PER_INI',  'ESF_FPLACEMT2','${DFILI}/${ENV_PREFIX}_ESFD5000_I17L_TMP_PER_INI_FPLACEMT2_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_TMP_PER_INI',  'ESF_FPLATXCUM','${DFILI}/${ENV_PREFIX}_ESFD5000_I17L_TMP_PER_INI_FPLATXCUM_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_TMP_PER_INI',  'ESF_IADPERIFR','${DFILI}/${ENV_PREFIX}_ESFD5000_I17L_TMP_PER_INI_IADPERIFR_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_TMP_PER_INI',  'ESF_FULTIMATES','${DFILI}/${ENV_PREFIX}_ESFD5000_I17L_TMP_PER_INI_FULTIMATES_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_TMP_PER_INI',  'ESF_IADPERIFCI','${DFILI}/${ENV_PREFIX}_ESFD5000_I17L_TMP_PER_INI_IADPERIFCI_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_TMP_PER_INI',  'ESF_IADPERIFCT','${DFILI}/${ENV_PREFIX}_ESFD5000_I17L_TMP_PER_INI_IADPERIFCT_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_TMP_PER_INI',  'ESF_FCTRGROLESII','${DFILI}/${ENV_PREFIX}_ESFD5000_I17L_TMP_PER_INI_FCTRGROLESII_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_TMP_PER_INI',  'ESF_FPLATXCUMALL','${DFILI}/${ENV_PREFIX}_ESFD5000_I17L_TMP_PER_INI_FPLATXCUMALL_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_TMP_PER_INI',  'EST_IADPERICASE_INI','${DFILI}/${ENV_PREFIX}_ESFD5000_I17L_TMP_PER_INI_IADPERICASE_INI_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_TMP_PER_INI',  'EST_IRDPERICASE_INI','${DFILI}/${ENV_PREFIX}_ESFD5000_I17L_TMP_PER_INI_IRDPERICASE_INI_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_TMP_PER_INI',  'ESF_FLORETFACTOR_INI','${DFILI}/${ENV_PREFIX}_ESFD5000_I17L_TMP_PER_INI_FLORETFACTOR_INI_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_TMP_PER_INI',  'EST_IADPERICASE0_INI','${DFILI}/${ENV_PREFIX}_ESFD5000_I17L_TMP_PER_INI_IADPERICASE0_INI_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_TMP_PER_INI',  'EST_IADPERICASE_DUMMY_INI','${DFILI}/${ENV_PREFIX}_ESFD5000_I17L_TMP_PER_INI_IADPERICASE_DUMMY_INI_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17LMINV',  'I17L_TMP_PER_INI','')
			insert into BEST..TI17REQFNC values ('I17LQINV',  'I17L_TMP_PER_INI','')
			insert into BEST..TI17REQFNC values ('I17LQPOS',  'I17L_TMP_PER_INI','')
			insert into BEST..TI17REQFNC values ('I17LYINV',  'I17L_TMP_PER_INI','')
			insert into BEST..TI17REQFNC values ('I17LYPOS',  'I17L_TMP_PER_INI','')

	----------IDF_CT:   I17P_TMP_PER_INI ------------------

		insert into BEST..TI17FNC values ('I17P_TMP_PER_INI','Parent - Proto Pericase Ini Generation','ESFD5000',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17P_TMP_PER_INI',  'EST_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_TMP_PER_INI',  'EST_FSOBBLOB','${DFILP}/${ENV_PREFIX}_ESCJ0660_FSOBBLOB.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_TMP_PER_INI',  'ESF_FCES','${DFILI}/${ENV_PREFIX}_ESFD5000_I17P_TMP_PER_INI_FCES_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_TMP_PER_INI',  'ESF_FPLC','${DFILI}/${ENV_PREFIX}_ESFD5000_I17P_TMP_PER_INI_FPLC_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_TMP_PER_INI',  'ESF_FCTRGRO','${DFILI}/${ENV_PREFIX}_ESFD5000_I17P_TMP_PER_INI_FCTRGRO_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_TMP_PER_INI',  'ESF_FCTRULT','${DFILI}/${ENV_PREFIX}_ESFD5000_I17P_TMP_PER_INI_FCTRULT_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_TMP_PER_INI',  'ESF_FMARKET','${DFILI}/${ENV_PREFIX}_ESFD5000_I17P_TMP_PER_INI_FMARKET_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_TMP_PER_INI',  'ESF_FCTRGRO1','${DFILI}/${ENV_PREFIX}_ESFD5000_I17P_TMP_PER_INI_FCTRGRO1_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_TMP_PER_INI',  'ESF_FPLACEMT0','${DFILI}/${ENV_PREFIX}_ESFD5000_I17P_TMP_PER_INI_FPLACEMT0_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_TMP_PER_INI',  'ESF_FPLACEMT2','${DFILI}/${ENV_PREFIX}_ESFD5000_I17P_TMP_PER_INI_FPLACEMT2_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_TMP_PER_INI',  'ESF_FPLATXCUM','${DFILI}/${ENV_PREFIX}_ESFD5000_I17P_TMP_PER_INI_FPLATXCUM_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_TMP_PER_INI',  'ESF_IADPERIFR','${DFILI}/${ENV_PREFIX}_ESFD5000_I17P_TMP_PER_INI_IADPERIFR_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_TMP_PER_INI',  'ESF_FULTIMATES','${DFILI}/${ENV_PREFIX}_ESFD5000_I17P_TMP_PER_INI_FULTIMATES_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_TMP_PER_INI',  'ESF_IADPERIFCI','${DFILI}/${ENV_PREFIX}_ESFD5000_I17P_TMP_PER_INI_IADPERIFCI_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_TMP_PER_INI',  'ESF_IADPERIFCT','${DFILI}/${ENV_PREFIX}_ESFD5000_I17P_TMP_PER_INI_IADPERIFCT_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_TMP_PER_INI',  'ESF_FCTRGROLESII','${DFILI}/${ENV_PREFIX}_ESFD5000_I17P_TMP_PER_INI_FCTRGROLESII_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_TMP_PER_INI',  'ESF_FPLATXCUMALL','${DFILI}/${ENV_PREFIX}_ESFD5000_I17P_TMP_PER_INI_FPLATXCUMALL_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_TMP_PER_INI',  'EST_IADPERICASE_INI','${DFILI}/${ENV_PREFIX}_ESFD5000_I17P_TMP_PER_INI_IADPERICASE_INI_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_TMP_PER_INI',  'EST_IRDPERICASE_INI','${DFILI}/${ENV_PREFIX}_ESFD5000_I17P_TMP_PER_INI_IRDPERICASE_INI_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_TMP_PER_INI',  'ESF_FLORETFACTOR_INI','${DFILI}/${ENV_PREFIX}_ESFD5000_I17P_TMP_PER_INI_FLORETFACTOR_INI_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_TMP_PER_INI',  'EST_IADPERICASE0_INI','${DFILI}/${ENV_PREFIX}_ESFD5000_I17P_TMP_PER_INI_IADPERICASE0_INI_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_TMP_PER_INI',  'EST_IADPERICASE_DUMMY_INI','${DFILI}/${ENV_PREFIX}_ESFD5000_I17P_TMP_PER_INI_IADPERICASE_DUMMY_INI_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17PMINV',  'I17P_TMP_PER_INI','')
			insert into BEST..TI17REQFNC values ('I17PQINV',  'I17P_TMP_PER_INI','')
			insert into BEST..TI17REQFNC values ('I17PQPOS',  'I17P_TMP_PER_INI','')
			insert into BEST..TI17REQFNC values ('I17PYINV',  'I17P_TMP_PER_INI','')
			insert into BEST..TI17REQFNC values ('I17PYPOS',  'I17P_TMP_PER_INI','')

	----------IDF_CT:   I17S_TMP_PER_INI ------------------

		insert into BEST..TI17FNC values ('I17S_TMP_PER_INI','Simulation - Proto Pericase Ini Generation','ESFD5000',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17S_TMP_PER_INI',  'EST_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_TMP_PER_INI',  'EST_FSOBBLOB','${DFILP}/${ENV_PREFIX}_ESCJ0660_FSOBBLOB.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_TMP_PER_INI',  'ESF_FCES','${DFILI}/${ENV_PREFIX}_ESFD5000_I17S_TMP_PER_INI_FCES_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_TMP_PER_INI',  'ESF_FPLC','${DFILI}/${ENV_PREFIX}_ESFD5000_I17S_TMP_PER_INI_FPLC_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_TMP_PER_INI',  'ESF_FCTRGRO','${DFILI}/${ENV_PREFIX}_ESFD5000_I17S_TMP_PER_INI_FCTRGRO_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_TMP_PER_INI',  'ESF_FCTRULT','${DFILI}/${ENV_PREFIX}_ESFD5000_I17S_TMP_PER_INI_FCTRULT_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_TMP_PER_INI',  'ESF_FMARKET','${DFILI}/${ENV_PREFIX}_ESFD5000_I17S_TMP_PER_INI_FMARKET_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_TMP_PER_INI',  'ESF_FCTRGRO1','${DFILI}/${ENV_PREFIX}_ESFD5000_I17S_TMP_PER_INI_FCTRGRO1_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_TMP_PER_INI',  'ESF_FPLACEMT0','${DFILI}/${ENV_PREFIX}_ESFD5000_I17S_TMP_PER_INI_FPLACEMT0_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_TMP_PER_INI',  'ESF_FPLACEMT2','${DFILI}/${ENV_PREFIX}_ESFD5000_I17S_TMP_PER_INI_FPLACEMT2_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_TMP_PER_INI',  'ESF_FPLATXCUM','${DFILI}/${ENV_PREFIX}_ESFD5000_I17S_TMP_PER_INI_FPLATXCUM_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_TMP_PER_INI',  'ESF_IADPERIFR','${DFILI}/${ENV_PREFIX}_ESFD5000_I17S_TMP_PER_INI_IADPERIFR_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_TMP_PER_INI',  'ESF_FULTIMATES','${DFILI}/${ENV_PREFIX}_ESFD5000_I17S_TMP_PER_INI_FULTIMATES_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_TMP_PER_INI',  'ESF_IADPERIFCI','${DFILI}/${ENV_PREFIX}_ESFD5000_I17S_TMP_PER_INI_IADPERIFCI_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_TMP_PER_INI',  'ESF_IADPERIFCT','${DFILI}/${ENV_PREFIX}_ESFD5000_I17S_TMP_PER_INI_IADPERIFCT_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_TMP_PER_INI',  'ESF_FCTRGROLESII','${DFILI}/${ENV_PREFIX}_ESFD5000_I17S_TMP_PER_INI_FCTRGROLESII_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_TMP_PER_INI',  'ESF_FPLATXCUMALL','${DFILI}/${ENV_PREFIX}_ESFD5000_I17S_TMP_PER_INI_FPLATXCUMALL_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_TMP_PER_INI',  'EST_IADPERICASE_INI','${DFILI}/${ENV_PREFIX}_ESFD5000_I17S_TMP_PER_INI_IADPERICASE_INI_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_TMP_PER_INI',  'EST_IRDPERICASE_INI','${DFILI}/${ENV_PREFIX}_ESFD5000_I17S_TMP_PER_INI_IRDPERICASE_INI_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_TMP_PER_INI',  'ESF_FLORETFACTOR_INI','${DFILI}/${ENV_PREFIX}_ESFD5000_I17S_TMP_PER_INI_FLORETFACTOR_INI_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_TMP_PER_INI',  'EST_IADPERICASE0_INI','${DFILI}/${ENV_PREFIX}_ESFD5000_I17S_TMP_PER_INI_IADPERICASE0_INI_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_TMP_PER_INI',  'EST_IADPERICASE_DUMMY_INI','${DFILI}/${ENV_PREFIX}_ESFD5000_I17S_TMP_PER_INI_IADPERICASE_DUMMY_INI_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17SMINV',  'I17S_TMP_PER_INI','')
			insert into BEST..TI17REQFNC values ('I17SQINV',  'I17S_TMP_PER_INI','')
			insert into BEST..TI17REQFNC values ('I17SQPOS',  'I17S_TMP_PER_INI','')
			insert into BEST..TI17REQFNC values ('I17SYINV',  'I17S_TMP_PER_INI','')
			insert into BEST..TI17REQFNC values ('I17SYPOS',  'I17S_TMP_PER_INI','')
go

