-------------------------------
--mapping of  ESFD4070

	----------   Clean tables   ---------------------

	delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT ='ESFD4070' )
	delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD4070')
	delete BEST..TI17FNC where CHAIN_CT='ESFD4070' 
 	delete BEST..TI17CHN  where CHAIN_CT='ESFD4070' 

	insert into BEST..TI17CHN values ('ESFD4070',  'GAAPCod BDA to GLT')

	
	----------IDF_CT:   I17G_GAP_MAP_STD_OPT ------------------

		insert into BEST..TI17FNC values ('I17G_GAP_MAP_STD_OPT','GAAPMAP BDA to GTL','ESFD4070',0)  
					

		----------  Perms--------------------- 
	
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD_OPT',  'ESF_FCTRGRO0','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCTRGRO0.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD_OPT',  'ESF_FPLACEMT2','${DFILP}/${ENV_PREFIX}_ESCJ0660_FPLACEMT2.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD_OPT',  'ESF_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD_OPT',  'ESF_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')			
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD_OPT',  'ESF_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT_TXT.dat','I','')				
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD_OPT',  'ESF_FSSDACTR_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FSSDACTR_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD_OPT',  'ESF_FCPLACC','${DFILP}/${ENV_PREFIX}_ESFD0560_I17G_FCPLACC_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD_OPT',  'ESF_GAAPMAP','${DFILP}/${ENV_PREFIX}_ESFD0060_I17G____GAAPMAP_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD_OPT',  'EST_FTECLEDA','${DFILP}/${ENV_PREFIX}_ES${PARM_FTECLED}D8700_FTECLEDA_I4I_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD_OPT',  'EST_FTECLEDR','${DFILP}/${ENV_PREFIX}_ES${PARM_FTECLED}D3800_FTECLEDR_I4I_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD_OPT',  'EST_FPLATXCUM','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLATXCUM_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD_OPT',  'ESF_IRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE0_I17G_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD_OPT',  'EPO_FTECLEDA','${DFILP}/${ENV_PREFIX}_ESPD3970_EBS_MVT_MRG_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD_OPT',  'EPO_FTECLEDR','${DFILP}/${ENV_PREFIX}_ESPD3970_EBS_MVT_MRG_STD_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD_OPT',  'ESF_FTECLEDA','${DFILP}/${ENV_PREFIX}_ESFD3870_I17G_GLT_ALL_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD_OPT',  'ESF_FTECLEDR','${DFILP}/${ENV_PREFIX}_ESFD3870_I17G_GLT_ALL_STD_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD_OPT',  'ESF_FPLATXCUMALL0','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLATXCUMALL0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD_OPT',  'ESF_CSM_LC_AMORT_PATTERN','${DFILP}/${ENV_PREFIX}_ESFD3770_CSM_LC_AMORT_PATTERN_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD_OPT',  'ESF_CSM_LC_AMORT_PATTERN_PREV','${DFILP}/${ENV_PREFIX}_ESFD3770_CSM_LC_AMORT_PATTERN_EBS_POS_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD_OPT',  'ESF_FCSM_ENDING_RNP','${DFILP}/${ENV_PREFIX}_ESFD3870_I17G_GLT_ALL_STD_FCSM_ENDING_RNP_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD_OPT',  'ESF_IADVPERICASE','${DFILP}/${ENV_PREFIX}_ESPD1800_I17G_AET_RPO_I17_IADPERICASE_I17_MERGE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD_OPT',  'ESF_FTECLEDA_70_EBS','${DFILI}/${ENV_PREFIX}_ESFD4070_I17G_GAP_MAP_STD_ESF_FTECLEDA_70_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD_OPT',  'ESF_FCSM_LC_ENDING_ASS','${DFILP}/${ENV_PREFIX}_ESFD3870_I17G_GLT_ALL_STD_FCSM_LC_ENDING_ASS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD_OPT',  'ESF_FTECLEDA_40_IFRS4','${DFILI}/${ENV_PREFIX}_ESFD4070_I17G_GAP_MAP_STD_ESF_FTECLEDA_40_IFRS4_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD_OPT',  'ESF_FTECLEDA_100_IFRS17','${DFILI}/${ENV_PREFIX}_ESFD4070_I17G_GAP_MAP_STD_ESF_FTECLEDA_100_IFRS17_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD_OPT',  'ESF_FTECLEDA_IN','${DFILP}/${ENV_PREFIX}_ESFD4030_I17G_GAP_MAP_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD_OPT',  'ESF_FTECLEDR_IN','${DFILP}/${ENV_PREFIX}_ESFD4030_I17G_GAP_MAP_STD_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD_OPT',  'ESF_FTECLEDA_OUT','${DFILI}/${ENV_PREFIX}_ESFD4070_I17G_GAP_MAP_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD_OPT',  'ESF_FTECLEDR_OUT','${DFILI}/${ENV_PREFIX}_ESFD4070_I17G_GAP_MAP_STD_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD_OPT',  'ESF_FGAAPMAP_RETRO','${DFILP}/${ENV_PREFIX}_ESFD4070_I17G_GAP_MAP_STD_FGAAPMAP_RETRO_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD_OPT',  'ESF_FTECLEDA_DELTA','${DFILP}/${ENV_PREFIX}_ESFD4070_I17G_GAP_MAP_STD_FTECLEDA_DELTA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD_OPT',  'ESF_FTECLEDR_DELTA','${DFILP}/${ENV_PREFIX}_ESFD4070_I17G_GAP_MAP_STD_FTECLEDR_DELTA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD_OPT',  'ESF_FGAAPMAP_ASSUMED','${DFILP}/${ENV_PREFIX}_ESFD4070_I17G_GAP_MAP_STD_FGAAPMAP_ASSUMED_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
	
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD_OPT',  'ESF_FSOBBLOB_TXT','${DFILI}/${ENV_PREFIX}_ESFD4070_I17G_GAP_MAP_STD_FSOBBLOB_TXT.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD_OPT',  'ESF_IADVPERICASE_LIFE_ASSUMED','${DFILI}/${ENV_PREFIX}_ESFD4070_I17G_GAP_MAP_STD_IADPERICASE_LIFE_ASSUMED.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD_OPT',  'ESF_IADVPERICASE_LIFE_RETRO','${DFILI}/${ENV_PREFIX}_ESFD4070_I17G_GAP_MAP_STD_IADPERICASE_LIFE_RETRO.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD_OPT',  'ESF_FCTRGRO0_EMPTY','${DFILP}/${ENV_PREFIX}_ESFD4070_I17G_GAP_MAP_STD_FCTRGRO0_EMPTY.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD_OPT',  'ESF_IADVPERICASE_CPLACC_SEG0_SEG_PRDCOD','${DFILP}/${ENV_PREFIX}_ESFD4070_I17G_GAP_MAP_STD_IADVPERICASE_CPLACC_SEG0_SEG_PRDCOD.dat','O','')

			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD_OPT',  'ESF_CLIEN_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCLIENT_TXT_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
            insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD_OPT',  'ESF_FTECLEDAA','${DFILP}/${ENV_PREFIX}_ESFD4070_I17G_GAP_MAP_STD_FTECLEDAA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
            insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD_OPT',  'ESF_FTECLEDAR','${DFILP}/${ENV_PREFIX}_ESFD4070_I17G_GAP_MAP_STD_FTECLEDAR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD_OPT',  'ESF_FTECLEDA_OUT_ESFD4030','${DFILP}/${ENV_PREFIX}_ESFD4030_I17G_GAP_MAP_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD_OPT',  'ESF_FTECLEDR_OUT_ESFD4030','${DFILP}/${ENV_PREFIX}_ESFD4030_I17G_GAP_MAP_STD_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')



		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17GMINV',  'I17G_GAP_MAP_STD_OPT','')
			insert into BEST..TI17REQFNC values ('I17GQINV',  'I17G_GAP_MAP_STD_OPT','')
			insert into BEST..TI17REQFNC values ('I17GQPOS',  'I17G_GAP_MAP_STD_OPT','')
			insert into BEST..TI17REQFNC values ('I17GYINV',  'I17G_GAP_MAP_STD_OPT','')
			insert into BEST..TI17REQFNC values ('I17GYPOS',  'I17G_GAP_MAP_STD_OPT','')
			insert into BEST..TI17REQFNC values ('I17GQPOSP', 'I17G_GAP_MAP_STD_OPT','')
			insert into BEST..TI17REQFNC values ('I17GYPOSP', 'I17G_GAP_MAP_STD_OPT','')
			
	----------IDF_CT:   I17P_GAP_MAP_STD_OPT ------------------

		insert into BEST..TI17FNC values ('I17P_GAP_MAP_STD_OPT','GAAPMAP BDA to GTL','ESFD4070',0)
					

		----------  Perms---------------------
	
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD_OPT',  'ESF_FCTRGRO0','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCTRGRO0.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD_OPT',  'ESF_FPLACEMT2','${DFILP}/${ENV_PREFIX}_ESCJ0660_FPLACEMT2.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD_OPT',  'ESF_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD_OPT',  'ESF_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')			
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD_OPT',  'ESF_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT_TXT.dat','I','')				
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD_OPT',  'ESF_FSSDACTR_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FSSDACTR_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD_OPT',  'ESF_FCPLACC','${DFILP}/${ENV_PREFIX}_ESFD0560_I17G_FCPLACC_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD_OPT',  'ESF_GAAPMAP','${DFILP}/${ENV_PREFIX}_ESFD0060_I17P____GAAPMAP_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD_OPT',  'EST_FTECLEDA','${DFILP}/${ENV_PREFIX}_ES${PARM_FTECLED}D8700_FTECLEDA_I4I_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD_OPT',  'EST_FTECLEDR','${DFILP}/${ENV_PREFIX}_ES${PARM_FTECLED}D3800_FTECLEDR_I4I_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD_OPT',  'EST_FPLATXCUM','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLATXCUM_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD_OPT',  'ESF_IRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE0_I17P_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD_OPT',  'EPO_FTECLEDA','${DFILP}/${ENV_PREFIX}_ESPD3970_EBS_MVT_MRG_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD_OPT',  'EPO_FTECLEDR','${DFILP}/${ENV_PREFIX}_ESPD3970_EBS_MVT_MRG_STD_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD_OPT',  'ESF_FTECLEDA','${DFILP}/${ENV_PREFIX}_ESFD3870_I17P_GLT_ALL_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD_OPT',  'ESF_FTECLEDR','${DFILP}/${ENV_PREFIX}_ESFD3870_I17P_GLT_ALL_STD_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD_OPT',  'ESF_FPLATXCUMALL0','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLATXCUMALL0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD_OPT',  'ESF_CSM_LC_AMORT_PATTERN','${DFILP}/${ENV_PREFIX}_ESFD3770_CSM_LC_AMORT_PATTERN_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD_OPT',  'ESF_CSM_LC_AMORT_PATTERN_PREV','${DFILP}/${ENV_PREFIX}_ESFD3770_CSM_LC_AMORT_PATTERN_EBS_POS_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD_OPT',  'ESF_FCSM_ENDING_RNP','${DFILP}/${ENV_PREFIX}_ESFD3870_I17P_GLT_ALL_STD_FCSM_ENDING_RNP_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD_OPT',  'ESF_IADVPERICASE','${DFILP}/${ENV_PREFIX}_ESPD1800_I17P_AET_RPO_I17_IADPERICASE_I17_MERGE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD_OPT',  'ESF_FTECLEDA_70_EBS','${DFILI}/${ENV_PREFIX}_ESFD4070_I17P_GAP_MAP_STD_ESF_FTECLEDA_70_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD_OPT',  'ESF_FCSM_LC_ENDING_ASS','${DFILP}/${ENV_PREFIX}_ESFD3870_I17P_GLT_ALL_STD_FCSM_LC_ENDING_ASS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD_OPT',  'ESF_FTECLEDA_40_IFRS4','${DFILI}/${ENV_PREFIX}_ESFD4070_I17P_GAP_MAP_STD_ESF_FTECLEDA_40_IFRS4_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD_OPT',  'ESF_FTECLEDA_100_IFRS17','${DFILI}/${ENV_PREFIX}_ESFD4070_I17P_GAP_MAP_STD_ESF_FTECLEDA_100_IFRS17_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD_OPT',  'ESF_FTECLEDA_IN','${DFILP}/${ENV_PREFIX}_ESFD4030_I17P_GAP_MAP_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD_OPT',  'ESF_FTECLEDR_IN','${DFILP}/${ENV_PREFIX}_ESFD4030_I17P_GAP_MAP_STD_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD_OPT',  'ESF_FTECLEDA_OUT','${DFILI}/${ENV_PREFIX}_ESFD4070_I17P_GAP_MAP_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD_OPT',  'ESF_FTECLEDR_OUT','${DFILI}/${ENV_PREFIX}_ESFD4070_I17P_GAP_MAP_STD_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD_OPT',  'ESF_FGAAPMAP_RETRO','${DFILP}/${ENV_PREFIX}_ESFD4070_I17P_GAP_MAP_STD_FGAAPMAP_RETRO_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD_OPT',  'ESF_FTECLEDA_DELTA','${DFILP}/${ENV_PREFIX}_ESFD4070_I17P_GAP_MAP_STD_FTECLEDA_DELTA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD_OPT',  'ESF_FTECLEDR_DELTA','${DFILP}/${ENV_PREFIX}_ESFD4070_I17P_GAP_MAP_STD_FTECLEDR_DELTA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD_OPT',  'ESF_FGAAPMAP_ASSUMED','${DFILP}/${ENV_PREFIX}_ESFD4070_I17P_GAP_MAP_STD_FGAAPMAP_ASSUMED_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
	
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD_OPT',  'ESF_FSOBBLOB_TXT','${DFILI}/${ENV_PREFIX}_ESFD4070_I17P_GAP_MAP_STD_FSOBBLOB_TXT.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD_OPT',  'ESF_IADVPERICASE_LIFE_ASSUMED','${DFILI}/${ENV_PREFIX}_ESFD4070_I17P_GAP_MAP_STD_IADPERICASE_LIFE_ASSUMED.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD_OPT',  'ESF_IADVPERICASE_LIFE_RETRO','${DFILI}/${ENV_PREFIX}_ESFD4070_I17P_GAP_MAP_STD_IADPERICASE_LIFE_RETRO.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD_OPT',  'ESF_FCTRGRO0_EMPTY','${DFILI}/${ENV_PREFIX}_ESFD4070_I17P_GAP_MAP_STD_FCTRGRO0_EMPTY.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD_OPT',  'ESF_IADVPERICASE_CPLACC_SEG0_SEG_PRDCOD','${DFILI}/${ENV_PREFIX}_ESFD4070_I17P_GAP_MAP_STD_IADVPERICASE_CPLACC_SEG0_SEG_PRDCOD.dat','O','')

			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD_OPT',  'ESF_CLIEN_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCLIENT_TXT_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
            insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD_OPT',  'ESF_FTECLEDAA','${DFILP}/${ENV_PREFIX}_ESFD4070_I17P_GAP_MAP_STD_FTECLEDAA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
            insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD_OPT',  'ESF_FTECLEDAR','${DFILP}/${ENV_PREFIX}_ESFD4070_I17P_GAP_MAP_STD_FTECLEDAR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD_OPT',  'ESF_FTECLEDA_OUT_ESFD4030','${DFILP}/${ENV_PREFIX}_ESFD4030_I17P_GAP_MAP_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD_OPT',  'ESF_FTECLEDR_OUT_ESFD4030','${DFILP}/${ENV_PREFIX}_ESFD4030_I17P_GAP_MAP_STD_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')



		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17PMINV',  'I17P_GAP_MAP_STD_OPT','')
			insert into BEST..TI17REQFNC values ('I17PQINV',  'I17P_GAP_MAP_STD_OPT','')
			insert into BEST..TI17REQFNC values ('I17PQPOS',  'I17P_GAP_MAP_STD_OPT','')
			insert into BEST..TI17REQFNC values ('I17PYINV',  'I17P_GAP_MAP_STD_OPT','')
			insert into BEST..TI17REQFNC values ('I17PYPOS',  'I17P_GAP_MAP_STD_OPT','')
			insert into BEST..TI17REQFNC values ('I17PQPOSP', 'I17P_GAP_MAP_STD_OPT','')
			insert into BEST..TI17REQFNC values ('I17PYPOSP', 'I17P_GAP_MAP_STD_OPT','')
 			insert into BEST..TI17REQFNC values ('I17PQPOSX', 'I17P_GAP_MAP_STD_OPT','')
			insert into BEST..TI17REQFNC values ('I17PYPOSX', 'I17P_GAP_MAP_STD_OPT','')

	----------IDF_CT:   I17L_GAP_MAP_STD_OPT ------------------

		insert into BEST..TI17FNC values ('I17L_GAP_MAP_STD_OPT','GAAPMAP BDA to GTL','ESFD4070',0)
					

		----------  Perms---------------------
	
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD_OPT',  'ESF_FCTRGRO0','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCTRGRO0.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD_OPT',  'ESF_FPLACEMT2','${DFILP}/${ENV_PREFIX}_ESCJ0660_FPLACEMT2.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD_OPT',  'ESF_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD_OPT',  'ESF_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')			
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD_OPT',  'ESF_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT_TXT.dat','I','')			
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD_OPT',  'ESF_FSSDACTR_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FSSDACTR_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD_OPT',  'ESF_FCPLACC','${DFILP}/${ENV_PREFIX}_ESFD0560_I17G_FCPLACC_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD_OPT',  'ESF_GAAPMAP','${DFILP}/${ENV_PREFIX}_ESFD0060_I17L____GAAPMAP_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD_OPT',  'EST_FTECLEDA','${DFILP}/${ENV_PREFIX}_ES${PARM_FTECLED}D8700_FTECLEDA_I4I_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD_OPT',  'EST_FTECLEDR','${DFILP}/${ENV_PREFIX}_ES${PARM_FTECLED}D3800_FTECLEDR_I4I_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD_OPT',  'EST_FPLATXCUM','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLATXCUM_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD_OPT',  'ESF_IRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE0_I17L_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD_OPT',  'EPO_FTECLEDA','${DFILP}/${ENV_PREFIX}_ESPD3970_EBS_MVT_MRG_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD_OPT',  'EPO_FTECLEDR','${DFILP}/${ENV_PREFIX}_ESPD3970_EBS_MVT_MRG_STD_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD_OPT',  'ESF_FTECLEDA','${DFILP}/${ENV_PREFIX}_ESFD3870_I17L_GLT_ALL_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD_OPT',  'ESF_FTECLEDR','${DFILP}/${ENV_PREFIX}_ESFD3870_I17L_GLT_ALL_STD_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD_OPT',  'ESF_FPLATXCUMALL0','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLATXCUMALL0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD_OPT',  'ESF_CSM_LC_AMORT_PATTERN','${DFILP}/${ENV_PREFIX}_ESFD3770_CSM_LC_AMORT_PATTERN_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD_OPT',  'ESF_CSM_LC_AMORT_PATTERN_PREV','${DFILP}/${ENV_PREFIX}_ESFD3770_CSM_LC_AMORT_PATTERN_EBS_POS_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD_OPT',  'ESF_FCSM_ENDING_RNP','${DFILP}/${ENV_PREFIX}_ESFD3870_I17L_GLT_ALL_STD_FCSM_ENDING_RNP_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD_OPT',  'ESF_IADVPERICASE','${DFILP}/${ENV_PREFIX}_ESPD1800_I17L_AET_RPO_I17_IADPERICASE_I17_MERGE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD_OPT',  'ESF_FTECLEDA_70_EBS','${DFILI}/${ENV_PREFIX}_ESFD4070_I17L_GAP_MAP_STD_ESF_FTECLEDA_70_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD_OPT',  'ESF_FCSM_LC_ENDING_ASS','${DFILP}/${ENV_PREFIX}_ESFD3870_I17L_GLT_ALL_STD_FCSM_LC_ENDING_ASS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD_OPT',  'ESF_FTECLEDA_40_IFRS4','${DFILI}/${ENV_PREFIX}_ESFD4070_I17L_GAP_MAP_STD_ESF_FTECLEDA_40_IFRS4_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD_OPT',  'ESF_FTECLEDA_100_IFRS17','${DFILI}/${ENV_PREFIX}_ESFD4070_I17L_GAP_MAP_STD_ESF_FTECLEDA_100_IFRS17_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD_OPT',  'ESF_FTECLEDA_IN','${DFILP}/${ENV_PREFIX}_ESFD4030_I17L_GAP_MAP_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD_OPT',  'ESF_FTECLEDR_IN','${DFILP}/${ENV_PREFIX}_ESFD4030_I17L_GAP_MAP_STD_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD_OPT',  'ESF_FTECLEDA_OUT','${DFILI}/${ENV_PREFIX}_ESFD4070_I17L_GAP_MAP_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD_OPT',  'ESF_FTECLEDR_OUT','${DFILI}/${ENV_PREFIX}_ESFD4070_I17L_GAP_MAP_STD_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD_OPT',  'ESF_FGAAPMAP_RETRO','${DFILP}/${ENV_PREFIX}_ESFD4070_I17L_GAP_MAP_STD_FGAAPMAP_RETRO_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD_OPT',  'ESF_FTECLEDA_DELTA','${DFILP}/${ENV_PREFIX}_ESFD4070_I17L_GAP_MAP_STD_FTECLEDA_DELTA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD_OPT',  'ESF_FTECLEDR_DELTA','${DFILP}/${ENV_PREFIX}_ESFD4070_I17L_GAP_MAP_STD_FTECLEDR_DELTA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD_OPT',  'ESF_FGAAPMAP_ASSUMED','${DFILP}/${ENV_PREFIX}_ESFD4070_I17L_GAP_MAP_STD_FGAAPMAP_ASSUMED_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
	
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD_OPT',  'ESF_FSOBBLOB_TXT','${DFILI}/${ENV_PREFIX}_ESFD4070_I17L_GAP_MAP_STD_FSOBBLOB_TXT.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD_OPT',  'ESF_IADVPERICASE_LIFE_ASSUMED','${DFILI}/${ENV_PREFIX}_ESFD4070_I17L_GAP_MAP_STD_IADPERICASE_LIFE_ASSUMED.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD_OPT',  'ESF_IADVPERICASE_LIFE_RETRO','${DFILI}/${ENV_PREFIX}_ESFD4070_I17L_GAP_MAP_STD_IADPERICASE_LIFE_RETRO.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD_OPT',  'ESF_FCTRGRO0_EMPTY','${DFILI}/${ENV_PREFIX}_ESFD4070_I17L_GAP_MAP_STD_FCTRGRO0_EMPTY.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD_OPT',  'ESF_IADVPERICASE_CPLACC_SEG0_SEG_PRDCOD','${DFILI}/${ENV_PREFIX}_ESFD4070_I17L_GAP_MAP_STD_IADVPERICASE_CPLACC_SEG0_SEG_PRDCOD.dat','O','')

			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD_OPT',  'ESF_CLIEN_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCLIENT_TXT_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
            insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD_OPT',  'ESF_FTECLEDAA','${DFILP}/${ENV_PREFIX}_ESFD4070_I17L_GAP_MAP_STD_FTECLEDAA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
            insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD_OPT',  'ESF_FTECLEDAR','${DFILP}/${ENV_PREFIX}_ESFD4070_I17L_GAP_MAP_STD_FTECLEDAR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD_OPT',  'ESF_FTECLEDA_OUT_ESFD4030','${DFILP}/${ENV_PREFIX}_ESFD4030_I17L_GAP_MAP_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD_OPT',  'ESF_FTECLEDR_OUT_ESFD4030','${DFILP}/${ENV_PREFIX}_ESFD4030_I17L_GAP_MAP_STD_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')



		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17LMINV',  'I17L_GAP_MAP_STD_OPT','')
			insert into BEST..TI17REQFNC values ('I17LQINV',  'I17L_GAP_MAP_STD_OPT','')
			insert into BEST..TI17REQFNC values ('I17LQPOS',  'I17L_GAP_MAP_STD_OPT','')
			insert into BEST..TI17REQFNC values ('I17LYINV',  'I17L_GAP_MAP_STD_OPT','')
			insert into BEST..TI17REQFNC values ('I17LYPOS',  'I17L_GAP_MAP_STD_OPT','')
			insert into BEST..TI17REQFNC values ('I17LQPOSP', 'I17L_GAP_MAP_STD_OPT','')
			insert into BEST..TI17REQFNC values ('I17LYPOSP', 'I17L_GAP_MAP_STD_OPT','')
 			insert into BEST..TI17REQFNC values ('I17LQPOSX', 'I17L_GAP_MAP_STD_OPT','')
			insert into BEST..TI17REQFNC values ('I17LYPOSX', 'I17L_GAP_MAP_STD_OPT','')
 ----------IDF_CT:   I17S_GAP_MAP_STD_OPT ------------------

		insert into BEST..TI17FNC values ('I17S_GAP_MAP_STD_OPT','GAAPMAP BDA to GTL','ESFD4070',0)
					

		----------  Perms---------------------
	
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_STD_OPT',  'ESF_FCTRGRO0','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCTRGRO0.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_STD_OPT',  'ESF_FPLACEMT2','${DFILP}/${ENV_PREFIX}_ESCJ0660_FPLACEMT2.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_STD_OPT',  'ESF_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_STD_OPT',  'ESF_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')			
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_STD_OPT',  'ESF_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT_TXT.dat','I','')				
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_STD_OPT',  'ESF_FSSDACTR_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FSSDACTR_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_STD_OPT',  'ESF_FCPLACC','${DFILP}/${ENV_PREFIX}_ESFD0560_I17G_FCPLACC_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_STD_OPT',  'ESF_GAAPMAP','${DFILP}/${ENV_PREFIX}_ESFD0060_I17S____GAAPMAP_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_STD_OPT',  'EST_FTECLEDA','${DFILP}/${ENV_PREFIX}_ES${PARM_FTECLED}D8700_FTECLEDA_I4I_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_STD_OPT',  'EST_FTECLEDR','${DFILP}/${ENV_PREFIX}_ES${PARM_FTECLED}D3800_FTECLEDR_I4I_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_STD_OPT',  'EST_FPLATXCUM','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLATXCUM_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_STD_OPT',  'ESF_IRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE0_I17S_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_STD_OPT',  'EPO_FTECLEDA','${DFILP}/${ENV_PREFIX}_ESPD3970_EBS_MVT_MRG_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_STD_OPT',  'EPO_FTECLEDR','${DFILP}/${ENV_PREFIX}_ESPD3970_EBS_MVT_MRG_STD_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_STD_OPT',  'ESF_FTECLEDA','${DFILP}/${ENV_PREFIX}_ESFD3870_I17S_GLT_ALL_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_STD_OPT',  'ESF_FTECLEDR','${DFILP}/${ENV_PREFIX}_ESFD3870_I17S_GLT_ALL_STD_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_STD_OPT',  'ESF_FPLATXCUMALL0','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLATXCUMALL0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_STD_OPT',  'ESF_CSM_LC_AMORT_PATTERN','${DFILP}/${ENV_PREFIX}_ESFD3770_CSM_LC_AMORT_PATTERN_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_STD_OPT',  'ESF_CSM_LC_AMORT_PATTERN_PREV','${DFILP}/${ENV_PREFIX}_ESFD3770_CSM_LC_AMORT_PATTERN_EBS_POS_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_STD_OPT',  'ESF_FCSM_ENDING_RNP','${DFILP}/${ENV_PREFIX}_ESFD3870_I17S_GLT_ALL_STD_FCSM_ENDING_RNP_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_STD_OPT',  'ESF_IADVPERICASE','${DFILP}/${ENV_PREFIX}_ESPD1800_I17S_AET_RPO_I17_IADPERICASE_I17_MERGE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_STD_OPT',  'ESF_FTECLEDA_70_EBS','${DFILI}/${ENV_PREFIX}_ESFD4070_I17S_GAP_MAP_STD_ESF_FTECLEDA_70_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_STD_OPT',  'ESF_FCSM_LC_ENDING_ASS','${DFILP}/${ENV_PREFIX}_ESFD3870_I17S_GLT_ALL_STD_FCSM_LC_ENDING_ASS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_STD_OPT',  'ESF_FTECLEDA_40_IFRS4','${DFILI}/${ENV_PREFIX}_ESFD4070_I17S_GAP_MAP_STD_ESF_FTECLEDA_40_IFRS4_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_STD_OPT',  'ESF_FTECLEDA_100_IFRS17','${DFILI}/${ENV_PREFIX}_ESFD4070_I17S_GAP_MAP_STD_ESF_FTECLEDA_100_IFRS17_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_STD_OPT',  'ESF_FTECLEDA_IN','${DFILP}/${ENV_PREFIX}_ESFD4030_I17S_GAP_MAP_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_STD_OPT',  'ESF_FTECLEDR_IN','${DFILP}/${ENV_PREFIX}_ESFD4030_I17S_GAP_MAP_STD_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_STD_OPT',  'ESF_FTECLEDA_OUT','${DFILI}/${ENV_PREFIX}_ESFD4070_I17S_GAP_MAP_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_STD_OPT',  'ESF_FTECLEDR_OUT','${DFILI}/${ENV_PREFIX}_ESFD4070_I17S_GAP_MAP_STD_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_STD_OPT',  'ESF_FGAAPMAP_RETRO','${DFILP}/${ENV_PREFIX}_ESFD4070_I17S_GAP_MAP_STD_FGAAPMAP_RETRO_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_STD_OPT',  'ESF_FTECLEDA_DELTA','${DFILP}/${ENV_PREFIX}_ESFD4070_I17S_GAP_MAP_STD_FTECLEDA_DELTA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_STD_OPT',  'ESF_FTECLEDR_DELTA','${DFILP}/${ENV_PREFIX}_ESFD4070_I17S_GAP_MAP_STD_FTECLEDR_DELTA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_STD_OPT',  'ESF_FGAAPMAP_ASSUMED','${DFILP}/${ENV_PREFIX}_ESFD4070_I17S_GAP_MAP_STD_FGAAPMAP_ASSUMED_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
	
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_STD_OPT',  'ESF_FSOBBLOB_TXT','${DFILI}/${ENV_PREFIX}_ESFD4070_I17S_GAP_MAP_STD_FSOBBLOB_TXT.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_STD_OPT',  'ESF_IADVPERICASE_LIFE_ASSUMED','${DFILI}/${ENV_PREFIX}_ESFD4070_I17S_GAP_MAP_STD_IADPERICASE_LIFE_ASSUMED.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_STD_OPT',  'ESF_IADVPERICASE_LIFE_RETRO','${DFILI}/${ENV_PREFIX}_ESFD4070_I17S_GAP_MAP_STD_IADPERICASE_LIFE_RETRO.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_STD_OPT',  'ESF_FCTRGRO0_EMPTY','${DFILI}/${ENV_PREFIX}_ESFD4070_I17S_GAP_MAP_STD_FCTRGRO0_EMPTY.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_STD_OPT',  'ESF_IADVPERICASE_CPLACC_SEG0_SEG_PRDCOD','${DFILI}/${ENV_PREFIX}_ESFD4070_I17S_GAP_MAP_STD_IADVPERICASE_CPLACC_SEG0_SEG_PRDCOD.dat','O','')

			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_STD_OPT',  'ESF_CLIEN_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCLIENT_TXT_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
            insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_STD_OPT',  'ESF_FTECLEDAA','${DFILP}/${ENV_PREFIX}_ESFD4070_I17S_GAP_MAP_STD_FTECLEDAA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
            insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_STD_OPT',  'ESF_FTECLEDAR','${DFILP}/${ENV_PREFIX}_ESFD4070_I17S_GAP_MAP_STD_FTECLEDAR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_STD_OPT',  'ESF_FTECLEDA_OUT_ESFD4030','${DFILP}/${ENV_PREFIX}_ESFD4030_I17S_GAP_MAP_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_STD_OPT',  'ESF_FTECLEDR_OUT_ESFD4030','${DFILP}/${ENV_PREFIX}_ESFD4030_I17S_GAP_MAP_STD_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')



		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17SMINV',  'I17S_GAP_MAP_STD_OPT','')
			insert into BEST..TI17REQFNC values ('I17SQINV',  'I17S_GAP_MAP_STD_OPT','')
			insert into BEST..TI17REQFNC values ('I17SQPOS',  'I17S_GAP_MAP_STD_OPT','')
			insert into BEST..TI17REQFNC values ('I17SYINV',  'I17S_GAP_MAP_STD_OPT','')
			insert into BEST..TI17REQFNC values ('I17SYPOS',  'I17S_GAP_MAP_STD_OPT','')
			insert into BEST..TI17REQFNC values ('I17SQPOSP', 'I17S_GAP_MAP_STD_OPT','')
			insert into BEST..TI17REQFNC values ('I17SYPOSP', 'I17S_GAP_MAP_STD_OPT','')
 
 
go 


