-------------------------------
--mapping of  ESPD3620 

	----------   Clean tables   ---------------------

	delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESPD3620')
	delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESPD3620')
	delete BEST..TI17FNC where CHAIN_CT='ESPD3620'
	delete BEST..TI17CHN  where CHAIN_CT='ESPD3620'

	insert into BEST..TI17CHN values ('ESPD3620',  'Discount calcultion job ESID3703B')

	----------IDF_CT:   EBS_ESPD3620 ------------------

		insert into BEST..TI17FNC values ('EBS_ESPD3620','IFRS4 Post omega  EBS','ESPD3620',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('EBS_ESPD3620',  'EST_IADPERICASE_STD','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3620',  'EST_FDETTRS','${DFILP}/${ENV_PREFIX}_ESCJ0660_FDETTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3620',  'EST_FTRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3620',  'EST_FSSDACTR','${DFILP}/${ENV_PREFIX}_ESCJ0660_FSSDACTR.dat','I','')
			
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3620',  'EST_IADPERICASE_BBNI','${DFILP}/${ENV_PREFIX}_ESFD5060_IADPERICASE_BBNI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')			
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3620',  'EST_IRDPERICASE0_BBNI','${DFILP}/${ENV_PREFIX}_ESFD5060_IRDPERICASE_BBNI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3620',  'EST_FPLC','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLC_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3620',  'EPO_FPLATXCUM','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLATXCUM_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3620',  'EST_GTSII_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESFD5070_ESPD3610_GTSII_CASHFLOW_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3620',  'EST_FSEGPATTERN_ICR','${DFILP}/${ENV_PREFIX}_ESPD0060_FSEGPATTERN_ICR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3620',  'EST_IRDPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5010_IRDPERICASE0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3620',  'EST_IADPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5040_IADPERICASE_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3620',  'ESF_GTSII_ESCOMPTE','${DFILP}/${ENV_PREFIX}_ESPD3700_GTSII_ESCOMPTE_CLM_IFRS17_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3620',  'EST_DLEIFTECLEDSIIEP','${DFILP}/${ENV_PREFIX}_ESFD5070_ESPD4000_DLEIFTECLEDSIIEP_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','') --			
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3620',  'EST_GTSII_REMAINTOPAY_ULAE','${DFILP}/${ENV_PREFIX}_ESFD5070_ESPD3610_GTSII_REMAINTOPAY_ULAE_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3620',  'EST_DLCUMGTAAR_IBNR_FUTCLAIMS','${DFILP}/${ENV_PREFIX}_ESFD5070_ESPD3610_DLCUMGTAAR_IBNR_FUTCLAIMS_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3620',  'EST_GTSII_REMAINTOPAY_ULAEINF','${DFILP}/${ENV_PREFIX}_ESFD5070_ESPD3610_GTSII_REMAINTOPAY_ULAEINF_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3620',  'EST_FTECLEDSII','${DFILP}/${ENV_PREFIX}_ESPD3700_FTECLED_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3620',  'EST_DLDSIIGTR','${DFILP}/${ENV_PREFIX}_ESPD3620_DLDSIIGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3620',  'EST_DLDSIIGTAA','${DFILP}/${ENV_PREFIX}_ESPD3620_DLDSIIGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3620',  'EST_DLDSIIGTAR','${DFILP}/${ENV_PREFIX}_ESPD3620_DLDSIIGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3620',  'EST_DLEIFTECLEDSIIEI','${DFILP}/${ENV_PREFIX}_ESPD3620_DLEIFTECLEDSIIEI_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3620',  'EST_GTSII_ESCOMPTE_CLM','${DFILP}/${ENV_PREFIX}_ESPD3620_GTSII_ESCOMPTE_CLM_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('EBSEMINV',  'EBS_ESPD3620','Quarterly')
			insert into BEST..TI17REQFNC values ('EBSEQINV',  'EBS_ESPD3620','Quarterly')
			insert into BEST..TI17REQFNC values ('EBSEQPOC',  'EBS_ESPD3620','	Quarterly')
			insert into BEST..TI17REQFNC values ('EBSEQPOCB',  'EBS_ESPD3620','Quarterly')
			insert into BEST..TI17REQFNC values ('EBSEQPOS',  'EBS_ESPD3620','Quarterly')
			insert into BEST..TI17REQFNC values ('EBSEYINV',  'EBS_ESPD3620','Annual INV')
			insert into BEST..TI17REQFNC values ('EBSEYPOC',  'EBS_ESPD3620','Annual POC')
			insert into BEST..TI17REQFNC values ('EBSEYPOCB',  'EBS_ESPD3620','Annual POC')
			insert into BEST..TI17REQFNC values ('EBSEYPOS',  'EBS_ESPD3620','Annual POS')
			
	----------IDF_CT:   EBS_ESPD3620_INI ------------------

		insert into BEST..TI17FNC values ('EBS_ESPD3620_INI','IFRS4 Post omega  EBS INI','ESPD3620',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('EBS_ESPD3620_INI',  'EST_IADPERICASE_STD','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3620_INI',  'EST_FDETTRS','${DFILP}/${ENV_PREFIX}_ESCJ0660_FDETTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3620_INI',  'EST_FTRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3620_INI',  'EST_FSSDACTR','${DFILP}/${ENV_PREFIX}_ESCJ0660_FSSDACTR.dat','I','')
			
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3620_INI',  'EST_IADPERICASE_INI','${DFILP}/${ENV_PREFIX}_ESFD5060_IADPERICASE_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')			
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3620_INI',  'EST_IRDPERICASE0_INI','${DFILP}/${ENV_PREFIX}_ESFD5060_IRDPERICASE_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3620_INI',  'EST_FPLC','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLC_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3620_INI',  'EPO_FPLATXCUM','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLATXCUM_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			--insert into BEST..TI17PERMFIL values ('EBS_ESPD3620_INI',  'EST_GTSII_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESFD5070_ESPD3610_INI_GTSII_CASHFLOW_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3620_INI',  'EST_GTSII_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESPD3610_INI_GTSII_CASHFLOW_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3620_INI',  'EST_FSEGPATTERN_ICR','${DFILP}/${ENV_PREFIX}_ESPD0060_FSEGPATTERN_ICR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')  -- Pas d'effet
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3620_INI',  'EST_IRDPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5010_IRDPERICASE0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')   -- IRD STD EBS
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3620_INI',  'EST_IADPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5060_IADPERICASE_MRG_INI_STD_${PARM_TYPEINV}_${PARM_ICLODAT_D}.dat','I','')    -- MRG INI STD
	
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3620_INI',  'ESF_GTSII_ESCOMPTE','${DFILP}/${ENV_PREFIX}_ESFD3620_EBS_ESFD3620_INI_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			
			--insert into BEST..TI17PERMFIL values ('EBS_ESPD3620_INI',  'EST_DLEIFTECLEDSIIEP','${DFILP}/${ENV_PREFIX}_ESFD5070_ESPD4000_DLEIFTECLEDSIIEP_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','') -- 
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3620_INI',  'EST_DLEIFTECLEDSIIEP','${DFILP}/empty.dat','I','') -- A verifier		
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3620_INI',  'EST_GTSII_REMAINTOPAY_ULAE','${DFILP}/${ENV_PREFIX}_ESPD3610_INI_GTSII_REMAINTOPAY_ULAE_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3620_INI',  'EST_DLCUMGTAAR_IBNR_FUTCLAIMS','${DFILP}/${ENV_PREFIX}_ESPD3610_INI_DLCUMGTAAR_IBNR_FUTCLAIMS_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3620_INI',  'EST_GTSII_REMAINTOPAY_ULAEINF','${DFILP}/${ENV_PREFIX}_ESPD3610_INI_GTSII_REMAINTOPAY_ULAEINF_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')		

			insert into BEST..TI17PERMFIL values ('EBS_ESPD3620_INI',  'EST_FTECLEDSII','${DFILP}/${ENV_PREFIX}_ESPD3620_INI_FTECLED_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3620_INI',  'EST_DLDSIIGTR','${DFILP}/${ENV_PREFIX}_ESPD3620_INI_DLDSIIGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3620_INI',  'EST_DLDSIIGTAA','${DFILP}/${ENV_PREFIX}_ESPD3620_INI_DLDSIIGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3620_INI',  'EST_DLDSIIGTAR','${DFILP}/${ENV_PREFIX}_ESPD3620_INI_DLDSIIGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3620_INI',  'EST_DLEIFTECLEDSIIEI','${DFILP}/${ENV_PREFIX}_ESPD3620_INI_DLEIFTECLEDSIIEI_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3620_INI',  'EST_GTSII_ESCOMPTE_CLM','${DFILP}/${ENV_PREFIX}_ESPD3620_INI_GTSII_ESCOMPTE_CLM_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('EBSEMINV',  'EBS_ESPD3620_INI','Quarterly')
			insert into BEST..TI17REQFNC values ('EBSEQINV',  'EBS_ESPD3620_INI','Quarterly')
			insert into BEST..TI17REQFNC values ('EBSEQPOC',  'EBS_ESPD3620_INI','	Quarterly')
			insert into BEST..TI17REQFNC values ('EBSEQPOCB',  'EBS_ESPD3620_INI','Quarterly')
			insert into BEST..TI17REQFNC values ('EBSEQPOS',  'EBS_ESPD3620_INI','Quarterly')
			insert into BEST..TI17REQFNC values ('EBSEYINV',  'EBS_ESPD3620_INI','Annual INV')
			insert into BEST..TI17REQFNC values ('EBSEYPOC',  'EBS_ESPD3620_INI','Annual POC')
			insert into BEST..TI17REQFNC values ('EBSEYPOCB',  'EBS_ESPD3620_INI','Annual POC')
			insert into BEST..TI17REQFNC values ('EBSEYPOS',  'EBS_ESPD3620_INI','Annual POS')

go

