-------------------------------
--mapping of  ESFD0560

	----------   Clean tables   ---------------------

	delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD0560')
	delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD0560')
	delete BEST..TI17FNC where CHAIN_CT='ESFD0560'
	delete BEST..TI17CHN  where CHAIN_CT='ESFD0560'

	insert into BEST..TI17CHN values ('ESFD0560',  'AE Life placement cession pericase')

	----------IDF_CT:   I17G_OMG_PER_LIF ------------------

		insert into BEST..TI17FNC values ('I17G_OMG_PER_LIF','AE Life placement cession pericase','ESFD0560',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17G_OMG_PER_LIF',  'EST_FCPLACC0','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCPLACC.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_PER_LIF',  'EST_IAVPERICASE0','${DFILP}/${ENV_PREFIX}_ESCJ0660_IAVPERICASE0.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_PER_LIF',  'EST_IRVPERICASE0','${DFILP}/${ENV_PREFIX}_ESCJ0660_IRVPERICASE0.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_PER_LIF',  'EST_FCESSION0','${DFILP}/${ENV_PREFIX}_ESFD5010_FCESSION0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_PER_LIF',  'EST_FPLACEMT0','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLACEMT0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_PER_LIF',  'EST_IADPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5010_IADPERICASE0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_PER_LIF',  'EST_IRDPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5010_IRDPERICASE0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_PER_LIF',  'EST_FCES','${DFILP}/${ENV_PREFIX}_ESFD0560_I17G_FCES_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_PER_LIF',  'EST_FPLC','${DFILP}/${ENV_PREFIX}_ESFD0560_I17G_FPLC_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_PER_LIF',  'EST_FCPLACC','${DFILP}/${ENV_PREFIX}_ESFD0560_I17G_FCPLACC_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_PER_LIF',  'EST_FCESSION','${DFILP}/${ENV_PREFIX}_ESFD0560_I17G_FCESSION_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_PER_LIF',  'EST_FPLACEMT','${DFILP}/${ENV_PREFIX}_ESFD0560_I17G_FPLACEMT_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_PER_LIF',  'EST_IADVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD0560_I17G_IADVPERICASE_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_PER_LIF',  'EST_IRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD0560_I17G_IRDVPERICASE_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
      insert into BEST..TI17PERMFIL values ('I17G_OMG_PER_LIF',  'EST_SHARED_IAVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD0560_I17G_SHARED_IAVPERICASE_${PARM_ICLODAT_D}.dat','O','')
      insert into BEST..TI17PERMFIL values ('I17G_OMG_PER_LIF',  'EST_SHARED_IRVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD0560_I17G_SHARED_IRVPERICASE_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_PER_LIF',  'EST_IRDVPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD0560_I17G_IRDVPERICASE0_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_PER_LIF',  'EST_IADVPERICASE_I17L','${DFILP}/${ENV_PREFIX}_ESFD0560_I17L_IADVPERICASE_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_PER_LIF',  'EST_IADVPERICASE_I17P','${DFILP}/${ENV_PREFIX}_ESFD0560_I17P_IADVPERICASE_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_PER_LIF',  'EST_SHARED_IAVPERICASE_I17L','${DFILP}/${ENV_PREFIX}_ESFD0560_I17L_SHARED_IAVPERICASE_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_PER_LIF',  'EST_SHARED_IAVPERICASE_I17P','${DFILP}/${ENV_PREFIX}_ESFD0560_I17P_SHARED_IAVPERICASE_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_PER_LIF',  'EST_IRDVPERICASE_I17L','${DFILP}/${ENV_PREFIX}_ESFD0560_I17L_IRDVPERICASE_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_PER_LIF',  'EST_IRDVPERICASE_I17P','${DFILP}/${ENV_PREFIX}_ESFD0560_I17P_IRDVPERICASE_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_PER_LIF',  'EST_SHARED_IRVPERICASE_I17L','${DFILP}/${ENV_PREFIX}_ESFD0560_I17L_SHARED_IRVPERICASE_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_PER_LIF',  'EST_SHARED_IRVPERICASE_I17P','${DFILP}/${ENV_PREFIX}_ESFD0560_I17P_SHARED_IRVPERICASE_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_PER_LIF',  'EST_MODELINGTYPE','${DFILP}/${ENV_PREFIX}_ESFD0560_I17G_MODELINGTYPE_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
      insert into BEST..TI17PERMFIL values ('I17G_OMG_PER_LIF',  'EST_FCUR','${DFILP}/${ENV_PREFIX}_ESFD0560_I17G_FCUR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
      insert into BEST..TI17PERMFIL values ('I17G_OMG_PER_LIF',  'EST_FTACCTRNFWH','${DFILP}/${ENV_PREFIX}_ESFD0560_I17G_FTACCTRNFWH_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_PER_LIF',  'EST_SHARED_INI_PERICASE','${DFILP}/${ENV_PREFIX}_ESFD0560_I17G_LIFE_INI_IAVPERICASE_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_PER_LIF',  'EST_SHARED_INI_PERICASE_I17L','${DFILP}/${ENV_PREFIX}_ESFD0560_I17L_LIFE_INI_IAVPERICASE_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_PER_LIF',  'EST_SHARED_INI_PERICASE_I17P','${DFILP}/${ENV_PREFIX}_ESFD0560_I17P_LIFE_INI_IAVPERICASE_${PARM_ICLODAT_D}.dat','O','')


		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17GMINV',  'I17G_OMG_PER_LIF','')
			insert into BEST..TI17REQFNC values ('I17GQINV',  'I17G_OMG_PER_LIF','')
			insert into BEST..TI17REQFNC values ('I17GQPOS',  'I17G_OMG_PER_LIF','')
			insert into BEST..TI17REQFNC values ('I17GYINV',  'I17G_OMG_PER_LIF','')
			insert into BEST..TI17REQFNC values ('I17GYPOS',  'I17G_OMG_PER_LIF','')

	----------IDF_CT:   I17S_OMG_PER_LIF ------------------

		insert into BEST..TI17FNC values ('I17S_OMG_PER_LIF','AE Life placement cession pericase','ESFD0560',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17S_OMG_PER_LIF',  'EST_FCPLACC0','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCPLACC.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_PER_LIF',  'EST_IAVPERICASE0','${DFILP}/${ENV_PREFIX}_ESCJ0660_IAVPERICASE0.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_PER_LIF',  'EST_IRVPERICASE0','${DFILP}/${ENV_PREFIX}_ESCJ0660_IRVPERICASE0.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_PER_LIF',  'EST_FCESSION0','${DFILP}/${ENV_PREFIX}_ESFD5010_FCESSION0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_PER_LIF',  'EST_FPLACEMT0','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLACEMT0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_PER_LIF',  'EST_IADPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5010_IADPERICASE0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_PER_LIF',  'EST_IRDPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5010_IRDPERICASE0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_PER_LIF',  'EST_FCES','${DFILP}/${ENV_PREFIX}_ESFD0560_I17S_FCES_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_PER_LIF',  'EST_FPLC','${DFILP}/${ENV_PREFIX}_ESFD0560_I17S_FPLC_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_PER_LIF',  'EST_FCPLACC','${DFILP}/${ENV_PREFIX}_ESFD0560_I17S_FCPLACC_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_PER_LIF',  'EST_FCESSION','${DFILP}/${ENV_PREFIX}_ESFD0560_I17S_FCESSION_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_PER_LIF',  'EST_FPLACEMT','${DFILP}/${ENV_PREFIX}_ESFD0560_I17S_FPLACEMT_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_PER_LIF',  'EST_IADVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD0560_I17S_IADVPERICASE_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
      insert into BEST..TI17PERMFIL values ('I17S_OMG_PER_LIF',  'EST_SHARED_IAVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD0560_I17S_SHARED_IAVPERICASE_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_PER_LIF',  'EST_IRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD0560_I17S_IRDVPERICASE_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
      insert into BEST..TI17PERMFIL values ('I17S_OMG_PER_LIF',  'EST_SHARED_IRVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD0560_I17S_SHARED_IRVPERICASE_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_PER_LIF',  'EST_IRDVPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD0560_I17S_IRDVPERICASE0_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_PER_LIF',  'EST_IADVPERICASE_I17L','${DFILP}/${ENV_PREFIX}_ESFD0560_I17L_IADVPERICASE_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_PER_LIF',  'EST_IADVPERICASE_I17P','${DFILP}/${ENV_PREFIX}_ESFD0560_I17P_IADVPERICASE_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_PER_LIF',  'EST_SHARED_IAVPERICASE_I17L','${DFILP}/${ENV_PREFIX}_ESFD0560_I17L_SHARED_IAVPERICASE_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_PER_LIF',  'EST_SHARED_IAVPERICASE_I17P','${DFILP}/${ENV_PREFIX}_ESFD0560_I17P_SHARED_IAVPERICASE_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_PER_LIF',  'EST_IRDVPERICASE_I17L','${DFILP}/${ENV_PREFIX}_ESFD0560_I17L_IRDVPERICASE_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_PER_LIF',  'EST_IRDVPERICASE_I17P','${DFILP}/${ENV_PREFIX}_ESFD0560_I17P_IRDVPERICASE_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_PER_LIF',  'EST_SHARED_IRVPERICASE_I17L','${DFILP}/${ENV_PREFIX}_ESFD0560_I17L_SHARED_IRVPERICASE_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_PER_LIF',  'EST_SHARED_IRVPERICASE_I17P','${DFILP}/${ENV_PREFIX}_ESFD0560_I17P_SHARED_IRVPERICASE_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_PER_LIF',  'EST_MODELINGTYPE','${DFILP}/${ENV_PREFIX}_ESFD0560_I17S_MODELINGTYPE_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
      insert into BEST..TI17PERMFIL values ('I17S_OMG_PER_LIF',  'EST_FCUR','${DFILP}/${ENV_PREFIX}_ESFD0560_I17S_FCUR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
      insert into BEST..TI17PERMFIL values ('I17S_OMG_PER_LIF',  'EST_FTACCTRNFWH','${DFILP}/${ENV_PREFIX}_ESFD0560_I17S_FTACCTRNFWH_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
	        insert into BEST..TI17PERMFIL values ('I17S_OMG_PER_LIF',  'EST_SHARED_INI_PERICASE','${DFILP}/${ENV_PREFIX}_ESFD0560_I17S_LIFE_INI_IAVPERICASE_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_PER_LIF',  'EST_SHARED_INI_PERICASE_I17L','${DFILP}/${ENV_PREFIX}_ESFD0560_I17L_LIFE_INI_PER_IAVPERICASE_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_OMG_PER_LIF',  'EST_SHARED_INI_PERICASE_I17P','${DFILP}/${ENV_PREFIX}_ESFD0560_I17P_LIFE_INI_PER_IAVPERICASE_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17SYPOS',  'I17S_OMG_PER_LIF','')
			insert into BEST..TI17REQFNC values ('I17SMINV',  'I17S_OMG_PER_LIF','')
			insert into BEST..TI17REQFNC values ('I17SQINV',  'I17S_OMG_PER_LIF','')
			insert into BEST..TI17REQFNC values ('I17SQPOS',  'I17S_OMG_PER_LIF','')
			insert into BEST..TI17REQFNC values ('I17SYINV',  'I17S_OMG_PER_LIF','')
go

