-------------------------------
--mapping of  ESFD0040

	----------   Clean tables   ---------------------

	delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD0040')
	delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD0040')
	delete BEST..TI17FNC where CHAIN_CT='ESFD0040'
	delete BEST..TI17CHN  where CHAIN_CT='ESFD0040'

	insert into BEST..TI17CHN values ('ESFD0040',  'granularity product codes')

	----------IDF_CT:   ESFD0040 ------------------

		insert into BEST..TI17FNC values ('ESFD0040','granularity product codes','ESFD0040',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('ESFD0040',  'ESF_FCTRI17PRD_OVR_EBS','${DFILP}/${ENV_PREFIX}_ESFD0040_FCTRI17PRD_OVR_EBS.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD0040',  'ESF_FCTRI17PRD_OVR_I4I','${DFILP}/${ENV_PREFIX}_ESFD0040_FCTRI17PRD_OVR_I4I.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD0040',  'ESF_FCTRI17PRD_OVR_I17G','${DFILP}/${ENV_PREFIX}_ESFD0040_FCTRI17PRD_OVR_I17G.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD0040',  'ESF_FCTRI17PRD_OVR_I17L','${DFILP}/${ENV_PREFIX}_ESFD0040_FCTRI17PRD_OVR_I17L.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD0040',  'ESF_FCTRI17PRD_OVR_I17P','${DFILP}/${ENV_PREFIX}_ESFD0040_FCTRI17PRD_OVR_I17P.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD0040',  'ESF_FI17PRODUCT_OVR_EBS','${DFILP}/${ENV_PREFIX}_ESFD0040_FI17PRODUCT_OVR_EBS.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD0040',  'ESF_FI17PRODUCT_OVR_I4I','${DFILP}/${ENV_PREFIX}_ESFD0040_FI17PRODUCT_OVR_I4I.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD0040',  'ESF_FI17PRODUCT_OVR_I17G','${DFILP}/${ENV_PREFIX}_ESFD0040_FI17PRODUCT_OVR_I17G.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD0040',  'ESF_FI17PRODUCT_OVR_I17L','${DFILP}/${ENV_PREFIX}_ESFD0040_FI17PRODUCT_OVR_I17L.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD0040',  'ESF_FI17PRODUCT_OVR_I17P','${DFILP}/${ENV_PREFIX}_ESFD0040_FI17PRODUCT_OVR_I17P.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD0040',  'ESF_FCTRI17PRD_OVR_PC_I4I','${DFILP}/${ENV_PREFIX}_ESFD0040_FCTRI17PRD_OVR_PC_I4I.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD0040',  'ESF_FCTRI17PRD_OVR_MVT_I4I','${DFILP}/${ENV_PREFIX}_ESFD0040_FCTRI17PRD_OVR_MVT_I4I.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD0040',  'ESF_FI17PRODUCT_OVR_PC_I4I','${DFILP}/${ENV_PREFIX}_ESFD0040_FI17PRODUCT_OVR_PC_I4I.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD0040',  'ESF_FI17PRODUCT_MRG','${DFILP}/${ENV_PREFIX}_ESFD0040_FI17PRODUCT_MRG_${HOST_PRDSIT}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD0040',  'ESF_FI17PRODUCT_OVR_MVT_I4I','${DFILP}/${ENV_PREFIX}_ESFD0040_FI17PRODUCT_OVR_MVT_I4I.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD0040',  'ESF_FCTRI17PRD_NEW','${DFILP}/${ENV_PREFIX}_ESFD0040_FCTRI17PRD.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESFD0040',  'ESF_FI17PRODUCT_NEW','${DFILP}/${ENV_PREFIX}_ESFD0040_FI17PRODUCT.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESFD0040',  'ESF_FI17PRODUCT_PREV','${DFILI}/${ENV_PREFIX}_ESFD0040_FI17PRODUCT_PREV.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESFD0040',  'ESF_FCTRI17PRD_AF_PREV','${DFILI}/${ENV_PREFIX}_ESFD0040_FCTRI17PRD_AF_PREV.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESFD0040',  'ESF_FCTRI17PRD_DEFAULT','${DFILI}/${ENV_PREFIX}_ESFD0040_FCTRI17PRD_DEFAULT.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESFD0040',  'ESF_FCTRI17PRD_RET_PREV','${DFILI}/${ENV_PREFIX}_ESFD0040_FCTRI17PRD_RET_PREV.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESFD0040',  'ESF_FCTRI17PRD_SAP','${DFILT}/${ENV_PREFIX}_ESFD0040_FCTRI17PRD_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESFD0040',  'ESF_FI17PRODUCT_SAP','${DFILT}/${ENV_PREFIX}_ESFD0040_FI17PRODUCT_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESFD0040',  'ESF_FCTRI17PRD_MRG','${DFILP}/${ENV_PREFIX}_ESFD0040_FCTRI17PRD_MRG_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESFD0040',  'ESF_FCTRI17PRD_QTD','${DFILP}/${ENV_PREFIX}_ESFD0040_FCTRI17PRD_${PARM_I4I_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESFD0040',  'ESF_FI17PRODUCT_QTD','${DFILP}/${ENV_PREFIX}_ESFD0040_FI17PRODUCT_${PARM_I4I_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESFD0040',  'ESF_FCTRI17PRD_TOAS','${PARAM_DFILPAS}/${ENV_PREFIX}_ESFD0040_FCTRI17PRD_${PARAM_LOCALTOAS}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESFD0040',  'ESF_FCTRI17PRD_TOEU','${PARAM_DFILPEU}/${ENV_PREFIX}_ESFD0040_FCTRI17PRD_${PARAM_LOCALTOEU}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESFD0040',  'ESF_FCTRI17PRD_TOAM','${PARAM_DFILPAM}/${ENV_PREFIX}_ESFD0040_FCTRI17PRD_${PARAM_LOCALTOAM}.dat','O','')
			
			
		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('ALL',  'ESFD0040','')
go

