-------------------------------
--mapping of  ESDJ7010

	----------   Clean tables   ---------------------

	delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESDJ7010')
	delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESDJ7010')
	delete BEST..TI17FNC where CHAIN_CT='ESDJ7010'
	delete BEST..TI17CHN  where CHAIN_CT='ESDJ7010'

	insert into BEST..TI17CHN values ('ESDJ7010',  '')

	----------IDF_CT:   ESDJ7010 ------------------

		insert into BEST..TI17FNC values ('ESDJ7010',' ','ESDJ7010',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('ESDJ7010',  'EST_FTRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESDJ7010',  'EST_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESDJ7010',  'EST_ARCSTATGTR','${DFILP}/${ENV_PREFIX}_ESIX7000_ARCSTATGTR.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESDJ7010',  'EST_SUBTRS','${DFILP}/${ENV_PREFIX}_ESDJ1010_SUBTRS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESDJ7010',  'EST_IGTR00','${DFILP}/${ENV_PREFIX}_ESDJ7000_IGTR00_ID_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESDJ7010',  'EST_FACCPAR0','${DFILP}/${ENV_PREFIX}_ESDJ1010_FACCPAR0_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESDJ7010',  'EST_FCPLACC0','${DFILP}/${ENV_PREFIX}_ESDJ0110_FCPLACC0_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESDJ7010',  'EST_IGTAA00','${DFILP}/${ENV_PREFIX}_ESDJ7000_IGTAA00_ID_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESDJ7010',  'EST_SUBTRSASSO','${DFILP}/${ENV_PREFIX}_ESDJ1010_SUBTRSASSO_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESDJ7010',  'EST_FLIFEST0','${DFILP}/${ENV_PREFIX}_ESDJ0110_FLIFEST${IT}0_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESDJ7010',  'EST_FLIFDRI','${DFILP}/${ENV_PREFIX}_ESDJ1010_FLIFDRI${IT}_ALL_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESDJ7010',  'EST_VTSTATGTA0','${DFILP}/${ENV_PREFIX}_ESDJ7000_VTSTATGTA0_ID_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESDJ7010',  'EST_IAVPERICASE0','${DFILP}/${ENV_PREFIX}_ESDJ1010_IAVPERICASE0_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESDJ7010',  'EST_IRVPERICASE0','${DFILP}/${ENV_PREFIX}_ESDJ1010_IRVPERICASE0_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESDJ7010',  'EST_IARVPERICASE0','${DFILP}/${ENV_PREFIX}_ESDJ1010_IARVPERICASE0_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESDJ7010',  'EST_IARVPERICASE4','${DFILP}/${ENV_PREFIX}_ESDJ1010_IARVPERICASE4_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESDJ7010',  'EST_SUBTRSESBPROP','${DFILP}/${ENV_PREFIX}_ESDJ1010_SUBTRSESBPROP_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESDJ7010',  'EST_31_SORT_R_IAVPERICASE_O','${DFILP}/${ENV_PREFIX}_ESDJ1010_31_SORT_R_IAVPERICASE_O_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESDJ7010',  'EST_SRGTC','${DFILP}/${ENV_PREFIX}_ESDJ7010_SRGTC${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESDJ7010',  'EST_FLSTMTH','${DFILP}/${ENV_PREFIX}_ESDJ7010_FLSTMTH${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESDJ7010',  'EST_SRGTCB1','${DFILP}/${ENV_PREFIX}_ESDJ7010_SRGTCB${IT}1_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESDJ7010',  'ESF_TAXRETMGNT','${DFILP}/${ENV_PREFIX}_ESDJ7010_TAXRETMGNT_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESDJ7010',  'EST_FDATDERCPA','${DFILP}/${ENV_PREFIX}_ESID0060_FDATDERCPA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESDJ7010',  'EST_CPLIFDRI','${DFILP}/${ENV_PREFIX}_ESDJ7010_CPLIFDRI${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESDJ7010',  'EST_CPLIFEST','${DFILP}/${ENV_PREFIX}_ESDJ7010_CPLIFEST${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESDJ7010',  'EST_FLIFEST1','${DFILP}/${ENV_PREFIX}_ESDJ7010_FLIFEST${IT}1_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESDJ7010',  'EST_CPLIFDRIN','${DFILP}/${ENV_PREFIX}_ESDJ7010_CPLIFDRIN${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESDJ7010',  'EST_CRIBLEANO','${DFILP}/${ENV_PREFIX}_ESDJ7010_CRIBLEANO${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESDJ7010',  'EST_LIFENDCPT','${DFILP}/${ENV_PREFIX}_ESDJ7010_LIFENDCPT${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESDJ7010',  'EST_LIFESTANA','${DFILP}/${ENV_PREFIX}_ESDJ7010_LIFESTANA${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESDJ7010',  'EST_LIFESTLIB','${DFILP}/${ENV_PREFIX}_ESDJ7010_LIFESTLIB${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESDJ7010',  'EST_VLIFEST195','${DFILP}/${ENV_PREFIX}_ESDJ7010_VLIFEST195${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESDJ7010',  'EST_CPLIFDRIASC','${DFILP}/${ENV_PREFIX}_ESDJ7010_CPLIFDRIASC${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESDJ7010',  'EST_ERRUPDBATCH','${DFILP}/${ENV_PREFIX}_ESDJ7010_ERRUPDBATCH${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESDJ7010',  'EST_LIFESTNOACC','${DFILP}/${ENV_PREFIX}_ESDJ7010_LIFESTNOACC${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESDJ7010',  'EST_VLIFEST2070','${DFILP}/${ENV_PREFIX}_ESDJ7010_VLIFEST2070${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESDJ7010',  'EST_310_SORT_GT_O','${DFILP}/${ENV_PREFIX}_ESDJ7010_310_SORT_GT${IT}_O_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESDJ7010',  'EST_430_SORT_GT_O','${DFILP}/${ENV_PREFIX}_ESDJ7010_430_SORT_GT${IT}_O_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESDJ7010',  'EST_470_SORT_GT_O','${DFILP}/${ENV_PREFIX}_ESDJ7010_470_SORT_GT${IT}_O_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESDJ7010',  'EST_CPLIFEST_INTERM','${DFILP}/${ENV_PREFIX}_ESDJ7010_CPLIFEST_INTERM${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESDJ7010',  'EST_160_SORT_CPLACC_O','${DFILP}/${ENV_PREFIX}_ESDJ7010_160_SORT_CPLACC${IT}_O_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESDJ7010',  'EST_180_SORT_LSTMTH_O','${DFILP}/${ENV_PREFIX}_ESDJ7010_180_SORT_LSTMTH${IT}_O_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESDJ7010',  'EST_ESTC2035_LIFDRI_O1','${DFILP}/${ENV_PREFIX}_ESDJ7010_ESTC2035_LIFDRI${IT}_O1_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESDJ7010',  'EST_200_ESTC2034_GTB1_O','${DFILP}/${ENV_PREFIX}_ESDJ7010_200_ESTC2034_GTB1${IT}_O_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESDJ7010',  'EST_180_ESTC2040_OLD_LIFEST_O2','${DFILP}/${ENV_PREFIX}_ESDJ7010_180_ESTC2040_OLD_LIFEST${IT}_O2_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESDJ7010',  'EST_205_ESTC2040_OLD_LIFEST_O2','${DFILP}/${ENV_PREFIX}_ESDJ7010_205_ESTC2040_OLD_LIFEST${IT}_O2_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('ALL',  'ESDJ7010','')
go

