-------------------------------
--mapping of  ESFD4050

	----------   Clean tables   ---------------------

	delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD4050')
	delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD4050')
	delete BEST..TI17FNC where CHAIN_CT='ESFD4050'
	delete BEST..TI17CHN  where CHAIN_CT='ESFD4050'

	insert into BEST..TI17CHN values ('ESFD4050',  'ITD FILE AND QUATERLY FILES')

	----------IDF_CT:   EBS_ESFD4050_ARCSTATGTA ------------------

		insert into BEST..TI17FNC values ('EBS_ESFD4050_ARCSTATGTA','IFRS4 Post omega  EBS','ESFD4050',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('EBS_ESFD4050_ARCSTATGTA',  'ESF_CURGTA','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD4050_ARCSTATGTA',  'ESF_CURGTR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD4050_ARCSTATGTA',  'EPO_FTECLEDACO','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD4050_ARCSTATGTA',  'EPO_FTECLEDRCO','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD4050_ARCSTATGTA',  'EPO_FTECLEDRSO','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD4050_ARCSTATGTA',  'ESF_FTECLEDA_REJ','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD4050_ARCSTATGTA',  'ESF_OPNG_EBS_ASS','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD4050_ARCSTATGTA',  'EST_ARCSTATGTA','${DFILP}/${ENV_PREFIX}_ESIX7000_ARCSTATGTA.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD4050_ARCSTATGTA',  'EST_ARCSTATGTAR','${DFILP}/${ENV_PREFIX}_ESIX7000_ARCSTATGTAR.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD4050_ARCSTATGTA',  'EST_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD4050_ARCSTATGTA',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD4050_ARCSTATGTA',  'ESF_FTECLEDR_REJ','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDR_REJ_EBS.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD4050_ARCSTATGTA',  'ESF_OPNG_EBS_RET','${DFILP}/${ENV_PREFIX}_ESFD2900_FTECLEDR_OPNG_EBS.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD4050_ARCSTATGTA',  'EST_GT_A_AR','${DFILP}/${ENV_PREFIX}_ESFD4050_ARCSTATGTA_AR_ACTUAL.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD4050_ARCSTATGTA',  'EST_GT_ACMTRS','${DFILP}/${ENV_PREFIX}_ESFD4050_ARCSTATGTA_AR_ACMTRS.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD4050_ARCSTATGTA',  'EST_GT_A_AR_SUM','${DFILP}/${ENV_PREFIX}_ESFD4050_ARCSTATGTA_AR_ACTUAL_SUM.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD4050_ARCSTATGTA',  'ESF_FTECLEDA_REJ_OPNG','${DFILP}/${ENV_PREFIX}_ESFD4050_ARCSTATGTA_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD4050_ARCSTATGTA',  'ESF_FTECLEDR_REJ_OPNG','${DFILP}/${ENV_PREFIX}_ESFD4050_ARCSTATGTR_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('EBSEQINV',  'EBS_ESFD4050_ARCSTATGTA','')
			insert into BEST..TI17REQFNC values ('EBSEQPOS',  'EBS_ESFD4050_ARCSTATGTA','')
			insert into BEST..TI17REQFNC values ('EBSEYINV',  'EBS_ESFD4050_ARCSTATGTA','')
			insert into BEST..TI17REQFNC values ('EBSEYPOS',  'EBS_ESFD4050_ARCSTATGTA','')
			insert into BEST..TI17REQFNC values ('EBSEMINV',  'EBS_ESFD4050_ARCSTATGTA','')

	----------IDF_CT:   EBS_ESFD4050_TECLEDA ------------------

		insert into BEST..TI17FNC values ('EBS_ESFD4050_TECLEDA','IFRS4 Post omega  EBS','ESFD4050',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('EBS_ESFD4050_TECLEDA',  'ESF_CURGTA','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDA_CUR_EBS.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD4050_TECLEDA',  'ESF_CURGTR','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDR_CUR_EBS.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD4050_TECLEDA',  'EST_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD4050_TECLEDA',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD4050_TECLEDA',  'ESF_FTECLEDA_REJ','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDA_REJ_EBS.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD4050_TECLEDA',  'ESF_FTECLEDR_REJ','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDR_REJ_EBS.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD4050_TECLEDA',  'ESF_OPNG_EBS_ASS','${DFILP}/${ENV_PREFIX}_ESFD2900_FTECLEDA_OPNG_EBS.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD4050_TECLEDA',  'ESF_OPNG_EBS_RET','${DFILP}/${ENV_PREFIX}_ESFD2900_FTECLEDR_OPNG_EBS.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD4050_TECLEDA',  'EST_GT_A_AR','`if [ "${TYPEINV}" = "INV" ];then echo ${DFILP}/${ENV_PREFIX}_ES${PARM_FTECLED}D8700_FTECLEDA_I4I_${PARM_ICLODAT_D}.dat;else echo ${DFILP}/${ENV_PREFIX}_ESPD8700_FTECLEDA_ALL_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat;fi;`','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD4050_TECLEDA',  'EPO_FTECLEDACO','`if [ "${TYPEINV}" = "POC" ];then echo ${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_I4I_POC_${PARM_ICLODAT_D}.dat;else echo ${DFILP}/empty.dat;fi;`','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD4050_TECLEDA',  'EPO_FTECLEDRCO','`if [ "${TYPEINV}" = "POC" ];then echo ${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_I4I_POC_${PARM_ICLODAT_D}.dat;else echo ${DFILP}/empty.dat;fi;`','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD4050_TECLEDA',  'EPO_FTECLEDRSO','`if [ "${TYPEINV}" = "INV" ];then echo ${DFILP}/${ENV_PREFIX}_ESID8700_PC___FTECLEDR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat;else echo ${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_I4I_${PARM_ICLODAT_D}.dat;fi;`','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD4050_TECLEDA',  'EST_GT_A_AR_SUM','${DFILP}/${ENV_PREFIX}_ESFD4050_FTECLEDA_I4I_${PARM_ICLODAT_D}_SUM.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD4050_TECLEDA',  'EST_GT_ACMTRS','${DFILP}/${ENV_PREFIX}_ESFD4050_FTECLEDA_I4I_${PARM_ICLODAT_D}_ACMTRS.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD4050_TECLEDA',  'ESF_FTECLEDA_REJ_OPNG','${DFILP}/${ENV_PREFIX}_ESFD4050_FTECLEDA_I4I_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD4050_TECLEDA',  'ESF_FTECLEDR_REJ_OPNG','${DFILP}/${ENV_PREFIX}_ESFD4050_FTECLEDR_I4I_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('EBSEMINV',  'EBS_ESFD4050_TECLEDA','')
			insert into BEST..TI17REQFNC values ('EBSEQINV',  'EBS_ESFD4050_TECLEDA','')
			insert into BEST..TI17REQFNC values ('EBSEQPOC',  'EBS_ESFD4050_TECLEDA','')
			insert into BEST..TI17REQFNC values ('EBSEQPOS',  'EBS_ESFD4050_TECLEDA','')
			insert into BEST..TI17REQFNC values ('EBSEYINV',  'EBS_ESFD4050_TECLEDA','')
			insert into BEST..TI17REQFNC values ('EBSEYPOC',  'EBS_ESFD4050_TECLEDA','')
			insert into BEST..TI17REQFNC values ('EBSEYPOS',  'EBS_ESFD4050_TECLEDA','')
			insert into BEST..TI17REQFNC values ('EBSEQPOCB',  'EBS_ESFD4050_TECLEDA','')
			insert into BEST..TI17REQFNC values ('EBSEYPOCB',  'EBS_ESFD4050_TECLEDA','')

	----------IDF_CT:   I17G_ESFD4050_ARCSTATGTA ------------------

		insert into BEST..TI17FNC values ('I17G_ESFD4050_ARCSTATGTA','IFRS4 Post omega  EBS','ESFD4050',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17G_ESFD4050_ARCSTATGTA',  'ESF_CURGTA','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD4050_ARCSTATGTA',  'ESF_CURGTR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD4050_ARCSTATGTA',  'EPO_FTECLEDACO','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD4050_ARCSTATGTA',  'EPO_FTECLEDRCO','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD4050_ARCSTATGTA',  'EPO_FTECLEDRSO','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD4050_ARCSTATGTA',  'ESF_FTECLEDA_REJ','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD4050_ARCSTATGTA',  'ESF_OPNG_EBS_ASS','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD4050_ARCSTATGTA',  'EST_ARCSTATGTA','${DFILP}/${ENV_PREFIX}_ESIX7000_ARCSTATGTA.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD4050_ARCSTATGTA',  'EST_ARCSTATGTAR','${DFILP}/${ENV_PREFIX}_ESIX7000_ARCSTATGTAR.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD4050_ARCSTATGTA',  'EST_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD4050_ARCSTATGTA',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD4050_ARCSTATGTA',  'ESF_FTECLEDR_REJ','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDR_REJ_EBS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD4050_ARCSTATGTA',  'ESF_OPNG_EBS_RET','${DFILP}/${ENV_PREFIX}_ESFD2900_FTECLEDR_OPNG_EBS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD4050_ARCSTATGTA',  'EST_GT_A_AR','${DFILP}/${ENV_PREFIX}_ESFD4050_ARCSTATGTA_AR_ACTUAL.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD4050_ARCSTATGTA',  'EST_GT_ACMTRS','${DFILP}/${ENV_PREFIX}_ESFD4050_ARCSTATGTA_AR_ACMTRS.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD4050_ARCSTATGTA',  'EST_GT_A_AR_SUM','${DFILP}/${ENV_PREFIX}_ESFD4050_ARCSTATGTA_AR_ACTUAL_SUM.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD4050_ARCSTATGTA',  'ESF_FTECLEDA_REJ_OPNG','${DFILP}/${ENV_PREFIX}_ESFD4050_ARCSTATGTA_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD4050_ARCSTATGTA',  'ESF_FTECLEDR_REJ_OPNG','${DFILP}/${ENV_PREFIX}_ESFD4050_ARCSTATGTR_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17GYINV',  'I17G_ESFD4050_ARCSTATGTA','')
			insert into BEST..TI17REQFNC values ('I17GYPOS',  'I17G_ESFD4050_ARCSTATGTA','')
			insert into BEST..TI17REQFNC values ('I17GMINV',  'I17G_ESFD4050_ARCSTATGTA','')
			insert into BEST..TI17REQFNC values ('I17GQINV',  'I17G_ESFD4050_ARCSTATGTA','')
			insert into BEST..TI17REQFNC values ('I17GQPOS',  'I17G_ESFD4050_ARCSTATGTA','')

	----------IDF_CT:   I17G_ESFD4050_TECLEDA ------------------

		insert into BEST..TI17FNC values ('I17G_ESFD4050_TECLEDA','IFRS4 Post omega  I17G','ESFD4050',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17G_ESFD4050_TECLEDA',  'ESF_CURGTA','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDA_CUR_EBS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD4050_TECLEDA',  'ESF_CURGTR','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDR_CUR_EBS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD4050_TECLEDA',  'EST_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD4050_TECLEDA',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD4050_TECLEDA',  'ESF_FTECLEDA_REJ','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDA_REJ_EBS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD4050_TECLEDA',  'ESF_FTECLEDR_REJ','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDR_REJ_EBS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD4050_TECLEDA',  'ESF_OPNG_EBS_ASS','${DFILP}/${ENV_PREFIX}_ESFD2900_FTECLEDA_OPNG_EBS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD4050_TECLEDA',  'ESF_OPNG_EBS_RET','${DFILP}/${ENV_PREFIX}_ESFD2900_FTECLEDR_OPNG_EBS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD4050_TECLEDA',  'EST_GT_A_AR','${DFILP}/${ENV_PREFIX}_ES${PARM_FTECLED}D8700_FTECLEDA_I4I_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD4050_TECLEDA',  'EPO_FTECLEDACO','`if [ "${TYPEINV}" = "POC" ];then echo ${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_I4I_POC_${PARM_ICLODAT_D}.dat;else echo ${DFILP}/empty.dat;fi;`','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD4050_TECLEDA',  'EPO_FTECLEDRCO','`if [ "${TYPEINV}" = "POC" ];then echo ${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_I4I_POC_${PARM_ICLODAT_D}.dat;else echo ${DFILP}/empty.dat;fi;`','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD4050_TECLEDA',  'EPO_FTECLEDRSO','`if [ "${TYPEINV}" = "INV" ];then echo ${DFILP}/${ENV_PREFIX}_ESID8700_PC___FTECLEDR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat;else echo ${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_I4I_${PARM_ICLODAT_D}.dat;fi;`','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD4050_TECLEDA',  'EST_GT_A_AR_SUM','${DFILP}/${ENV_PREFIX}_ESFD4050_FTECLEDA_I4I_${PARM_ICLODAT_D}_SUM.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD4050_TECLEDA',  'EST_GT_ACMTRS','${DFILP}/${ENV_PREFIX}_ESFD4050_FTECLEDA_I4I_${PARM_ICLODAT_D}_ACMTRS.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD4050_TECLEDA',  'ESF_FTECLEDA_REJ_OPNG','${DFILP}/${ENV_PREFIX}_ESFD4050_FTECLEDA_I4I_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD4050_TECLEDA',  'ESF_FTECLEDR_REJ_OPNG','${DFILP}/${ENV_PREFIX}_ESFD4050_FTECLEDR_I4I_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17GMINV',  'I17G_ESFD4050_TECLEDA','')
			insert into BEST..TI17REQFNC values ('I17GQINV',  'I17G_ESFD4050_TECLEDA','')
			insert into BEST..TI17REQFNC values ('I17GQPOS',  'I17G_ESFD4050_TECLEDA','')
			insert into BEST..TI17REQFNC values ('I17GYINV',  'I17G_ESFD4050_TECLEDA','')
			insert into BEST..TI17REQFNC values ('I17GYPOS',  'I17G_ESFD4050_TECLEDA','')

	----------IDF_CT:   I17S_ESFD4050_ARCSTATGTA ------------------

		insert into BEST..TI17FNC values ('I17S_ESFD4050_ARCSTATGTA','IFRS4 Post omega  EBS','ESFD4050',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17S_ESFD4050_ARCSTATGTA',  'ESF_CURGTA','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD4050_ARCSTATGTA',  'ESF_CURGTR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD4050_ARCSTATGTA',  'EPO_FTECLEDACO','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD4050_ARCSTATGTA',  'EPO_FTECLEDRCO','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD4050_ARCSTATGTA',  'EPO_FTECLEDRSO','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD4050_ARCSTATGTA',  'ESF_FTECLEDA_REJ','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD4050_ARCSTATGTA',  'ESF_OPNG_EBS_ASS','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD4050_ARCSTATGTA',  'EST_ARCSTATGTA','${DFILP}/${ENV_PREFIX}_ESIX7000_ARCSTATGTA.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD4050_ARCSTATGTA',  'EST_ARCSTATGTAR','${DFILP}/${ENV_PREFIX}_ESIX7000_ARCSTATGTAR.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD4050_ARCSTATGTA',  'EST_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD4050_ARCSTATGTA',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD4050_ARCSTATGTA',  'ESF_FTECLEDR_REJ','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDR_REJ_EBS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD4050_ARCSTATGTA',  'ESF_OPNG_EBS_RET','${DFILP}/${ENV_PREFIX}_ESFD2900_FTECLEDR_OPNG_EBS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD4050_ARCSTATGTA',  'EST_GT_A_AR','${DFILP}/${ENV_PREFIX}_ESFD4050_ARCSTATGTA_AR_ACTUAL.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD4050_ARCSTATGTA',  'EST_GT_ACMTRS','${DFILP}/${ENV_PREFIX}_ESFD4050_ARCSTATGTA_AR_ACMTRS.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD4050_ARCSTATGTA',  'EST_GT_A_AR_SUM','${DFILP}/${ENV_PREFIX}_ESFD4050_ARCSTATGTA_AR_ACTUAL_SUM.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD4050_ARCSTATGTA',  'ESF_FTECLEDA_REJ_OPNG','${DFILP}/${ENV_PREFIX}_ESFD4050_ARCSTATGTA_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD4050_ARCSTATGTA',  'ESF_FTECLEDR_REJ_OPNG','${DFILP}/${ENV_PREFIX}_ESFD4050_ARCSTATGTR_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17SMINV',  'I17S_ESFD4050_ARCSTATGTA','')
			insert into BEST..TI17REQFNC values ('I17SQINV',  'I17S_ESFD4050_ARCSTATGTA','')
			insert into BEST..TI17REQFNC values ('I17SQPOS',  'I17S_ESFD4050_ARCSTATGTA','')
			insert into BEST..TI17REQFNC values ('I17SYINV',  'I17S_ESFD4050_ARCSTATGTA','')
			insert into BEST..TI17REQFNC values ('I17SYPOS',  'I17S_ESFD4050_ARCSTATGTA','')

	----------IDF_CT:   I17S_ESFD4050_TECLEDA ------------------

		insert into BEST..TI17FNC values ('I17S_ESFD4050_TECLEDA','IFRS4 Post omega  I17G','ESFD4050',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17S_ESFD4050_TECLEDA',  'ESF_CURGTA','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDA_CUR_EBS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD4050_TECLEDA',  'ESF_CURGTR','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDR_CUR_EBS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD4050_TECLEDA',  'EST_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD4050_TECLEDA',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD4050_TECLEDA',  'ESF_FTECLEDA_REJ','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDA_REJ_EBS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD4050_TECLEDA',  'ESF_FTECLEDR_REJ','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDR_REJ_EBS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD4050_TECLEDA',  'ESF_OPNG_EBS_ASS','${DFILP}/${ENV_PREFIX}_ESFD2900_FTECLEDA_OPNG_EBS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD4050_TECLEDA',  'ESF_OPNG_EBS_RET','${DFILP}/${ENV_PREFIX}_ESFD2900_FTECLEDR_OPNG_EBS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD4050_TECLEDA',  'EST_GT_A_AR','${DFILP}/${ENV_PREFIX}_ES${PARM_FTECLED}D8700_FTECLEDA_I4I_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD4050_TECLEDA',  'EPO_FTECLEDACO','`if [ "${TYPEINV}" = "POC" ];then echo ${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_I4I_POC_${PARM_ICLODAT_D}.dat;else echo ${DFILP}/empty.dat;fi;`','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD4050_TECLEDA',  'EPO_FTECLEDRCO','`if [ "${TYPEINV}" = "POC" ];then echo ${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_I4I_POC_${PARM_ICLODAT_D}.dat;else echo ${DFILP}/empty.dat;fi;`','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD4050_TECLEDA',  'EPO_FTECLEDRSO','`if [ "${TYPEINV}" = "INV" ];then echo ${DFILP}/${ENV_PREFIX}_ESID8700_PC___FTECLEDR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat;else echo ${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_I4I_${PARM_ICLODAT_D}.dat;fi;`','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD4050_TECLEDA',  'EST_GT_A_AR_SUM','${DFILP}/${ENV_PREFIX}_ESFD4050_FTECLEDA_I4I_${PARM_ICLODAT_D}_SUM.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD4050_TECLEDA',  'EST_GT_ACMTRS','${DFILP}/${ENV_PREFIX}_ESFD4050_FTECLEDA_I4I_${PARM_ICLODAT_D}_ACMTRS.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD4050_TECLEDA',  'ESF_FTECLEDA_REJ_OPNG','${DFILP}/${ENV_PREFIX}_ESFD4050_FTECLEDA_I4I_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD4050_TECLEDA',  'ESF_FTECLEDR_REJ_OPNG','${DFILP}/${ENV_PREFIX}_ESFD4050_FTECLEDR_I4I_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17SMINV',  'I17S_ESFD4050_TECLEDA','')
			insert into BEST..TI17REQFNC values ('I17SQINV',  'I17S_ESFD4050_TECLEDA','')
			insert into BEST..TI17REQFNC values ('I17SQPOC',  'I17S_ESFD4050_TECLEDA','')
			insert into BEST..TI17REQFNC values ('I17SQPOS',  'I17S_ESFD4050_TECLEDA','')
			insert into BEST..TI17REQFNC values ('I17SYINV',  'I17S_ESFD4050_TECLEDA','')
			insert into BEST..TI17REQFNC values ('I17SYPOC',  'I17S_ESFD4050_TECLEDA','')
			insert into BEST..TI17REQFNC values ('I17SYPOS',  'I17S_ESFD4050_TECLEDA','')
			insert into BEST..TI17REQFNC values ('I17SQPOCB',  'I17S_ESFD4050_TECLEDA','')
			insert into BEST..TI17REQFNC values ('I17SYPOCB',  'I17S_ESFD4050_TECLEDA','')
go

