-------------------------------
--mapping of  ESPD1800 

	----------   Clean tables   ---------------------

	delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESPD1800')
	delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESPD1800')
	delete BEST..TI17FNC where CHAIN_CT='ESPD1800'
	delete BEST..TI17CHN  where CHAIN_CT='ESPD1800'

	insert into BEST..TI17CHN values ('ESPD1800',  '')

	----------IDF_CT:   EBS_ESPD1800 ------------------

		insert into BEST..TI17FNC values ('EBS_ESPD1800',' ','ESPD1800',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800',  'ESF_FI17CLOPER','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800',  'ESF_IADVPERICASE_STD','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800',  'EPO_FDETTRS','${DFILP}/${ENV_PREFIX}_ESCJ0660_FDETTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800',  'EPO_FTRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800',  'EPO_FCURCVSN','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURCVSN.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800',  'EPO_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800',  'EPO_FBOPRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800',  'EPO_FCURCVSNI','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURCVSNI.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800',  'EPO_FTRANSCODE','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRANSCODE.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800',  'EPO_EPOSOCI','${DFILP}/${ENV_PREFIX}_ESPD0060_EPO_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800',  'EPO_FCES','${DFILP}/${ENV_PREFIX}_ESFD5040_FCES_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800',  'EPO_FPLC','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLC_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800',  'EPO_FPLATXCUM','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLATXCUM_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800',  'ESF_FLORETFACTOR','${DFILP}/${ENV_PREFIX}_ESPJ0090_FLORETFACTOR_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800',  'EPO_IADVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5040_IADVPERICASE_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800',  'EPO_OIRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5010_OIRDVPERICASE_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800',  'EPO_DLSGTR','${DFILP}/${ENV_PREFIX}_ESPD1800_DLSGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800',  'EPO_DLSGTAA','${DFILP}/${ENV_PREFIX}_ESPD1800_DLSGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800',  'EPO_DLSGTAR','${DFILP}/${ENV_PREFIX}_ESPD1800_DLSGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('EBSEQPOCB',  'EBS_ESPD1800','')
			insert into BEST..TI17REQFNC values ('EBSEQPOS',  'EBS_ESPD1800','')
			insert into BEST..TI17REQFNC values ('EBSEYINV',  'EBS_ESPD1800','')
			insert into BEST..TI17REQFNC values ('EBSEYPOC',  'EBS_ESPD1800','')
			insert into BEST..TI17REQFNC values ('EBSEYPOCB',  'EBS_ESPD1800','')
			insert into BEST..TI17REQFNC values ('EBSEYPOS',  'EBS_ESPD1800','')
			insert into BEST..TI17REQFNC values ('EBSEMINV',  'EBS_ESPD1800','')
			insert into BEST..TI17REQFNC values ('EBSEQINV',  'EBS_ESPD1800','')
			insert into BEST..TI17REQFNC values ('EBSEQPOC',  'EBS_ESPD1800','')
			
			
			
	----------IDF_CT:   EBS_ESPD1800_BBNI ------------------

		insert into BEST..TI17FNC values ('EBS_ESPD1800_BBNI',' ','ESPD1800',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800_BBNI',  'ESF_FI17CLOPER','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800_BBNI',  'ESF_IADVPERICASE_STD','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800_BBNI',  'EPO_FDETTRS','${DFILP}/${ENV_PREFIX}_ESCJ0660_FDETTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800_BBNI',  'EPO_FTRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800_BBNI',  'EPO_FCURCVSN','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURCVSN.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800_BBNI',  'EPO_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800_BBNI',  'EPO_FBOPRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800_BBNI',  'EPO_FCURCVSNI','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURCVSNI.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800_BBNI',  'EPO_FTRANSCODE','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRANSCODE.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800_BBNI',  'EPO_EPOSOCI','${DFILP}/${ENV_PREFIX}_ESFD5060_EPO_BBNI_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800_BBNI',  'EPO_FCES','${DFILP}/${ENV_PREFIX}_ESFD5040_FCES_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800_BBNI',  'EPO_FPLC','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLC_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800_BBNI',  'EPO_FPLATXCUM','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLATXCUM_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800_BBNI',  'ESF_FLORETFACTOR','${DFILP}/${ENV_PREFIX}_ESPJ0090_FLORETFACTOR_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','') 
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800_BBNI',  'EPO_IADVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5060_IADPERICASE_BBNI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')	
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800_BBNI',  'EPO_OIRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5060_IRDPERICASE_BBNI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')	
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800_BBNI',  'EPO_DLSGTR','${DFILP}/${ENV_PREFIX}_ESPD1800_BBNI_DLSGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800_BBNI',  'EPO_DLSGTAA','${DFILP}/${ENV_PREFIX}_ESPD1800_BBNI_DLSGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800_BBNI',  'EPO_DLSGTAR','${DFILP}/${ENV_PREFIX}_ESPD1800_BBNI_DLSGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('EBSEQPOCB',  'EBS_ESPD1800_BBNI','')
			insert into BEST..TI17REQFNC values ('EBSEQPOS',  'EBS_ESPD1800_BBNI','')
			insert into BEST..TI17REQFNC values ('EBSEYINV',  'EBS_ESPD1800_BBNI','')
			insert into BEST..TI17REQFNC values ('EBSEYPOC',  'EBS_ESPD1800_BBNI','')
			insert into BEST..TI17REQFNC values ('EBSEYPOCB',  'EBS_ESPD1800_BBNI','')
			insert into BEST..TI17REQFNC values ('EBSEYPOS',  'EBS_ESPD1800_BBNI','')
			insert into BEST..TI17REQFNC values ('EBSEMINV',  'EBS_ESPD1800_BBNI','')
			insert into BEST..TI17REQFNC values ('EBSEQINV',  'EBS_ESPD1800_BBNI','')
			insert into BEST..TI17REQFNC values ('EBSEQPOC',  'EBS_ESPD1800_BBNI','')
			

	----------IDF_CT:   EBS_ESPD1800_INI ------------------

		insert into BEST..TI17FNC values ('EBS_ESPD1800_INI',' ','ESPD1800',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800_INI',  'ESF_FI17CLOPER','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800_INI',  'ESF_IADVPERICASE_STD','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800_INI',  'EPO_FDETTRS','${DFILP}/${ENV_PREFIX}_ESCJ0660_FDETTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800_INI',  'EPO_FTRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800_INI',  'EPO_FCURCVSN','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURCVSN.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800_INI',  'EPO_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800_INI',  'EPO_FBOPRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800_INI',  'EPO_FCURCVSNI','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURCVSNI.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800_INI',  'EPO_FTRANSCODE','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRANSCODE.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800_INI',  'EPO_EPOSOCI','${DFILP}/${ENV_PREFIX}_ESFD5060_EPO_INI_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800_INI',  'EPO_FCES','${DFILP}/${ENV_PREFIX}_ESFD5040_FCES_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800_INI',  'EPO_FPLC','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLC_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800_INI',  'EPO_FPLATXCUM','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLATXCUM_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800_INI',  'ESF_FLORETFACTOR','${DFILP}/${ENV_PREFIX}_ESFD5060_EBS_INI_FLORETFACTOR_INI_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','') --A voir '${DFILP}/${ENV_PREFIX}_ESPJ0090_I17G_AEE_RPO_I17_FLORETFACTOR_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800_INI',  'EPO_IADVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5060_IADPERICASE_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')	
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800_INI',  'EPO_OIRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5060_IRDPERICASE_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')	
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800_INI',  'EPO_DLSGTR','${DFILP}/${ENV_PREFIX}_ESPD1800_INI_DLSGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800_INI',  'EPO_DLSGTAA','${DFILP}/${ENV_PREFIX}_ESPD1800_INI_DLSGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD1800_INI',  'EPO_DLSGTAR','${DFILP}/${ENV_PREFIX}_ESPD1800_INI_DLSGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('EBSEQPOCB',  'EBS_ESPD1800_INI','')
			insert into BEST..TI17REQFNC values ('EBSEQPOS',  'EBS_ESPD1800_INI','')
			insert into BEST..TI17REQFNC values ('EBSEYINV',  'EBS_ESPD1800_INI','')
			insert into BEST..TI17REQFNC values ('EBSEYPOC',  'EBS_ESPD1800_INI','')
			insert into BEST..TI17REQFNC values ('EBSEYPOCB',  'EBS_ESPD1800_INI','')
			insert into BEST..TI17REQFNC values ('EBSEYPOS',  'EBS_ESPD1800_INI','')
			insert into BEST..TI17REQFNC values ('EBSEMINV',  'EBS_ESPD1800_INI','')
			insert into BEST..TI17REQFNC values ('EBSEQINV',  'EBS_ESPD1800_INI','')
			insert into BEST..TI17REQFNC values ('EBSEQPOC',  'EBS_ESPD1800_INI','')						

	----------IDF_CT:   I17G_AET_RPO_I17 ------------------

		insert into BEST..TI17FNC values ('I17G_AET_RPO_I17',' ','ESPD1800',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17G_AET_RPO_I17',  'EPO_FDETTRS','${DFILP}/${ENV_PREFIX}_ESCJ0660_FDETTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_AET_RPO_I17',  'EPO_FTRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_AET_RPO_I17',  'EPO_FCURCVSN','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURCVSN.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_AET_RPO_I17',  'EPO_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_AET_RPO_I17',  'EPO_FBOPRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_AET_RPO_I17',  'EPO_FCURCVSNI','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURCVSNI.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_AET_RPO_I17',  'EPO_FTRANSCODE','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRANSCODE.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_AET_RPO_I17',  'ESF_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_AET_RPO_I17',  'ESF_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_AET_RPO_I17',  'EPO_FCES','${DFILP}/${ENV_PREFIX}_ESFD5040_FCES_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_AET_RPO_I17',  'EPO_FPLC','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLC_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_AET_RPO_I17',  'EPO_EPOSOCI','${DFILI}/${ENV_PREFIX}_ESFD0060_I17G____EPOSOCI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_AET_RPO_I17',  'EPO_FPLATXCUM','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLATXCUM_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_AET_RPO_I17',  'EPO_IADVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17G_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_AET_RPO_I17',  'ESF_FLORETFACTOR','${DFILP}/${ENV_PREFIX}_ESPJ0090_FLORETFACTOR_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_AET_RPO_I17',  'EPO_OIRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5010_OIRDVPERICASE_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_AET_RPO_I17',  'ESF_FI17CLOPER','${DFILP}/${ENV_PREFIX}_ESFD1130_FI17CLOPER_I17G_DSC_ALL_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_AET_RPO_I17',  'ESF_IADVPERICASE_STD','${DFILP}/${ENV_PREFIX}_ESFD5040_IADPERICASE_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_AET_RPO_I17',  'ESF_FLORETFACTOR_INI','${DFILP}/${ENV_PREFIX}_ESPJ0090_I17G_AEE_RPO_I17_FLORETFACTOR_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_AET_RPO_I17',  'EST_IRDPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE_I17G_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_AET_RPO_I17',  'ESF_IRDPERICASE_STD','${DFILP}/${ENV_PREFIX}_ESCJ0660_IRDPERICASE0.dat','I','')			


			insert into BEST..TI17PERMFIL values ('I17G_AET_RPO_I17',  'EPO_DLSGTR','${DFILP}/${ENV_PREFIX}_ESPD1800_I17G_AET_RPO_I17_DLSGTRSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_AET_RPO_I17',  'EPO_DLSGTAA','${DFILP}/${ENV_PREFIX}_ESPD1800_I17G_AET_RPO_I17_DLSGTAASII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_AET_RPO_I17',  'EPO_DLSGTAR','${DFILP}/${ENV_PREFIX}_ESPD1800_I17G_AET_RPO_I17_DLSGTARSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_AET_RPO_I17',  'ESF_DLSGTR_INI','${DFILP}/${ENV_PREFIX}_ESPD1800_I17G_AET_RPO_I17_DLSGTRSII_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_AET_RPO_I17',  'ESF_DLSGTAA_INI','${DFILP}/${ENV_PREFIX}_ESPD1800_I17G_AET_RPO_I17_DLSGTAASII_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_AET_RPO_I17',  'ESF_DLSGTAR_INI','${DFILP}/${ENV_PREFIX}_ESPD1800_I17G_AET_RPO_I17_DLSGTARSII_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_AET_RPO_I17',  'ESF_IADPERICASE_I17_MERGE','${DFILP}/${ENV_PREFIX}_ESPD1800_I17G_AET_RPO_I17_IADPERICASE_I17_MERGE_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_AET_RPO_I17',  'ESF_IRDPERICASE_I17_MERGE','${DFILP}/${ENV_PREFIX}_ESPD1800_I17G_AET_RPO_I17_IRDPERICASE_I17_MERGE_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')			

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17GMINV',  'I17G_AET_RPO_I17','')
			insert into BEST..TI17REQFNC values ('I17GQINV',  'I17G_AET_RPO_I17','')
			insert into BEST..TI17REQFNC values ('I17GQPOS',  'I17G_AET_RPO_I17','')
			insert into BEST..TI17REQFNC values ('I17GYINV',  'I17G_AET_RPO_I17','')
			insert into BEST..TI17REQFNC values ('I17GYPOS',  'I17G_AET_RPO_I17','')

	----------IDF_CT:   I17L_AET_RPO_I17 ------------------

		insert into BEST..TI17FNC values ('I17L_AET_RPO_I17',' ','ESPD1800',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17L_AET_RPO_I17',  'EPO_FDETTRS','${DFILP}/${ENV_PREFIX}_ESCJ0660_FDETTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_AET_RPO_I17',  'EPO_FTRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_AET_RPO_I17',  'EPO_FCURCVSN','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURCVSN.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_AET_RPO_I17',  'EPO_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_AET_RPO_I17',  'EPO_FBOPRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_AET_RPO_I17',  'EPO_FCURCVSNI','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURCVSNI.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_AET_RPO_I17',  'EPO_FTRANSCODE','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRANSCODE.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_AET_RPO_I17',  'ESF_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_AET_RPO_I17',  'ESF_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_AET_RPO_I17',  'EPO_FCES','${DFILP}/${ENV_PREFIX}_ESFD5040_FCES_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_AET_RPO_I17',  'EPO_FPLC','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLC_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_AET_RPO_I17',  'EPO_EPOSOCI','${DFILI}/${ENV_PREFIX}_ESFD0060_I17L____EPOSOCI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_AET_RPO_I17',  'EPO_FPLATXCUM','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLATXCUM_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_AET_RPO_I17',  'EPO_IADVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17L_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_AET_RPO_I17',  'ESF_FLORETFACTOR','${DFILP}/${ENV_PREFIX}_ESPJ0090_FLORETFACTOR_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_AET_RPO_I17',  'EPO_OIRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5010_OIRDVPERICASE_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_AET_RPO_I17',  'ESF_IADVPERICASE_STD','${DFILP}/${ENV_PREFIX}_ESFD5040_IADPERICASE_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_AET_RPO_I17',  'ESF_FI17CLOPER','${DFILP}/${ENV_PREFIX}_ESFD1130_FI17CLOPER_I17L_DSC_ALL_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_AET_RPO_I17',  'ESF_FLORETFACTOR_INI','${DFILP}/${ENV_PREFIX}_ESPJ0090_I17L_AEE_RPO_I17_FLORETFACTOR_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_AET_RPO_I17',  'EST_IRDPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE_I17L_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_AET_RPO_I17',  'ESF_IRDPERICASE_STD','${DFILP}/${ENV_PREFIX}_ESCJ0660_IRDPERICASE0.dat','I','')			
			
			
			insert into BEST..TI17PERMFIL values ('I17L_AET_RPO_I17',  'EPO_DLSGTR','${DFILP}/${ENV_PREFIX}_ESPD1800_I17L_AET_RPO_I17_DLSGTRSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_AET_RPO_I17',  'EPO_DLSGTAA','${DFILP}/${ENV_PREFIX}_ESPD1800_I17L_AET_RPO_I17_DLSGTAASII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_AET_RPO_I17',  'EPO_DLSGTAR','${DFILP}/${ENV_PREFIX}_ESPD1800_I17L_AET_RPO_I17_DLSGTARSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_AET_RPO_I17',  'ESF_DLSGTR_INI','${DFILP}/${ENV_PREFIX}_ESPD1800_I17L_AET_RPO_I17_DLSGTRSII_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_AET_RPO_I17',  'ESF_DLSGTAA_INI','${DFILP}/${ENV_PREFIX}_ESPD1800_I17L_AET_RPO_I17_DLSGTAASII_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_AET_RPO_I17',  'ESF_DLSGTAR_INI','${DFILP}/${ENV_PREFIX}_ESPD1800_I17L_AET_RPO_I17_DLSGTARSII_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_AET_RPO_I17',  'ESF_IADPERICASE_I17_MERGE','${DFILP}/${ENV_PREFIX}_ESPD1800_I17L_AET_RPO_I17_IADPERICASE_I17_MERGE_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_AET_RPO_I17',  'ESF_IRDPERICASE_I17_MERGE','${DFILP}/${ENV_PREFIX}_ESPD1800_I17L_AET_RPO_I17_IRDPERICASE_I17_MERGE_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')			
		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17LYPOSX',  'I17L_AET_RPO_I17','')
			insert into BEST..TI17REQFNC values ('I17LQPOSX',  'I17L_AET_RPO_I17','')
			insert into BEST..TI17REQFNC values ('I17LMINV',  'I17L_AET_RPO_I17','')
			insert into BEST..TI17REQFNC values ('I17LQINV',  'I17L_AET_RPO_I17','')
			insert into BEST..TI17REQFNC values ('I17LQPOS',  'I17L_AET_RPO_I17','')
			insert into BEST..TI17REQFNC values ('I17LYINV',  'I17L_AET_RPO_I17','')
			insert into BEST..TI17REQFNC values ('I17LYPOS',  'I17L_AET_RPO_I17','')

	----------IDF_CT:   I17P_AET_RPO_I17 ------------------

		insert into BEST..TI17FNC values ('I17P_AET_RPO_I17',' ','ESPD1800',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17P_AET_RPO_I17',  'EPO_FDETTRS','${DFILP}/${ENV_PREFIX}_ESCJ0660_FDETTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_AET_RPO_I17',  'EPO_FTRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_AET_RPO_I17',  'EPO_FCURCVSN','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURCVSN.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_AET_RPO_I17',  'EPO_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_AET_RPO_I17',  'EPO_FBOPRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_AET_RPO_I17',  'EPO_FCURCVSNI','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURCVSNI.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_AET_RPO_I17',  'EPO_FTRANSCODE','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRANSCODE.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_AET_RPO_I17',  'ESF_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_AET_RPO_I17',  'ESF_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_AET_RPO_I17',  'EPO_FCES','${DFILP}/${ENV_PREFIX}_ESFD5040_FCES_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_AET_RPO_I17',  'EPO_FPLC','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLC_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_AET_RPO_I17',  'EPO_EPOSOCI','${DFILI}/${ENV_PREFIX}_ESFD0060_I17P____EPOSOCI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_AET_RPO_I17',  'EPO_FPLATXCUM','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLATXCUM_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_AET_RPO_I17',  'EPO_IADVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17P_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_AET_RPO_I17',  'ESF_FLORETFACTOR','${DFILP}/${ENV_PREFIX}_ESPJ0090_FLORETFACTOR_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_AET_RPO_I17',  'EPO_OIRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5010_OIRDVPERICASE_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_AET_RPO_I17',  'ESF_IADVPERICASE_STD','${DFILP}/${ENV_PREFIX}_ESFD5040_IADPERICASE_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_AET_RPO_I17',  'ESF_FI17CLOPER','${DFILP}/${ENV_PREFIX}_ESFD1130_FI17CLOPER_I17P_DSC_ALL_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_AET_RPO_I17',  'ESF_FLORETFACTOR_INI','${DFILP}/${ENV_PREFIX}_ESPJ0090_I17P_AEE_RPO_I17_FLORETFACTOR_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')

			insert into BEST..TI17PERMFIL values ('I17P_AET_RPO_I17',  'EST_IRDPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE_I17P_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_AET_RPO_I17',  'ESF_IRDPERICASE_STD','${DFILP}/${ENV_PREFIX}_ESCJ0660_IRDPERICASE0.dat','I','')			
			insert into BEST..TI17PERMFIL values ('I17P_AET_RPO_I17',  'EPO_DLSGTR','${DFILP}/${ENV_PREFIX}_ESPD1800_I17P_AET_RPO_I17_DLSGTRSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_AET_RPO_I17',  'EPO_DLSGTAA','${DFILP}/${ENV_PREFIX}_ESPD1800_I17P_AET_RPO_I17_DLSGTAASII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_AET_RPO_I17',  'EPO_DLSGTAR','${DFILP}/${ENV_PREFIX}_ESPD1800_I17P_AET_RPO_I17_DLSGTARSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_AET_RPO_I17',  'ESF_DLSGTR_INI','${DFILP}/${ENV_PREFIX}_ESPD1800_I17P_AET_RPO_I17_DLSGTRSII_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_AET_RPO_I17',  'ESF_DLSGTAA_INI','${DFILP}/${ENV_PREFIX}_ESPD1800_I17P_AET_RPO_I17_DLSGTAASII_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_AET_RPO_I17',  'ESF_DLSGTAR_INI','${DFILP}/${ENV_PREFIX}_ESPD1800_I17P_AET_RPO_I17_DLSGTARSII_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_AET_RPO_I17',  'ESF_IADPERICASE_I17_MERGE','${DFILP}/${ENV_PREFIX}_ESPD1800_I17P_AET_RPO_I17_IADPERICASE_I17_MERGE_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_AET_RPO_I17',  'ESF_IRDPERICASE_I17_MERGE','${DFILP}/${ENV_PREFIX}_ESPD1800_I17P_AET_RPO_I17_IRDPERICASE_I17_MERGE_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')			
		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17PYPOS',  'I17P_AET_RPO_I17','')
			insert into BEST..TI17REQFNC values ('I17PMINV',  'I17P_AET_RPO_I17','')
			insert into BEST..TI17REQFNC values ('I17PQINV',  'I17P_AET_RPO_I17','')
			insert into BEST..TI17REQFNC values ('I17PQPOS',  'I17P_AET_RPO_I17','')
			insert into BEST..TI17REQFNC values ('I17PYINV',  'I17P_AET_RPO_I17','')
			insert into BEST..TI17REQFNC values ('I17PQPOSX',  'I17P_AET_RPO_I17','')
			insert into BEST..TI17REQFNC values ('I17PYPOSX',  'I17P_AET_RPO_I17','')

	----------IDF_CT:   I17S_AET_RPO_I17 ------------------

		insert into BEST..TI17FNC values ('I17S_AET_RPO_I17',' ','ESPD1800',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17S_AET_RPO_I17',  'EPO_EPOSOCI','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_AET_RPO_I17',  'EPO_FDETTRS','${DFILP}/${ENV_PREFIX}_ESCJ0660_FDETTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_AET_RPO_I17',  'EPO_FTRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_AET_RPO_I17',  'EPO_FCURCVSN','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURCVSN.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_AET_RPO_I17',  'EPO_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_AET_RPO_I17',  'EPO_FBOPRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_AET_RPO_I17',  'EPO_FCURCVSNI','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURCVSNI.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_AET_RPO_I17',  'EPO_FTRANSCODE','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRANSCODE.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_AET_RPO_I17',  'ESF_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_AET_RPO_I17',  'ESF_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_AET_RPO_I17',  'EPO_FCES','${DFILP}/${ENV_PREFIX}_ESFD5040_FCES_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_AET_RPO_I17',  'EPO_FPLC','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLC_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_AET_RPO_I17',  'EPO_FPLATXCUM','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLATXCUM_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_AET_RPO_I17',  'EPO_IADVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17S_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_AET_RPO_I17',  'ESF_FLORETFACTOR','${DFILP}/${ENV_PREFIX}_ESPJ0090_FLORETFACTOR_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_AET_RPO_I17',  'EPO_OIRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5010_OIRDVPERICASE_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_AET_RPO_I17',  'ESF_FI17CLOPER','${DFILP}/${ENV_PREFIX}_ESFD1130_FI17CLOPER_I17S_DSC_ALL_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_AET_RPO_I17',  'ESF_IADVPERICASE_STD','${DFILP}/${ENV_PREFIX}_ESFD5040_IADPERICASE_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_AET_RPO_I17',  'ESF_FLORETFACTOR_INI','${DFILP}/${ENV_PREFIX}_ESPJ0090_I17S_AEE_RPO_I17_FLORETFACTOR_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_AET_RPO_I17',  'EST_IRDPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE_I17S_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_AET_RPO_I17',  'ESF_IRDPERICASE_STD','${DFILP}/${ENV_PREFIX}_ESCJ0660_IRDPERICASE0.dat','I','')			

			insert into BEST..TI17PERMFIL values ('I17S_AET_RPO_I17',  'EPO_DLSGTR','${DFILP}/${ENV_PREFIX}_ESPD1800_I17S_AET_RPO_I17_DLSGTRSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_AET_RPO_I17',  'EPO_DLSGTAA','${DFILP}/${ENV_PREFIX}_ESPD1800_I17S_AET_RPO_I17_DLSGTAASII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_AET_RPO_I17',  'EPO_DLSGTAR','${DFILP}/${ENV_PREFIX}_ESPD1800_I17S_AET_RPO_I17_DLSGTARSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_AET_RPO_I17',  'ESF_DLSGTR_INI','${DFILP}/${ENV_PREFIX}_ESPD1800_I17S_AET_RPO_I17_DLSGTRSII_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_AET_RPO_I17',  'ESF_DLSGTAA_INI','${DFILP}/${ENV_PREFIX}_ESPD1800_I17S_AET_RPO_I17_DLSGTAASII_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_AET_RPO_I17',  'ESF_DLSGTAR_INI','${DFILP}/${ENV_PREFIX}_ESPD1800_I17S_AET_RPO_I17_DLSGTARSII_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_AET_RPO_I17',  'ESF_IADPERICASE_I17_MERGE','${DFILP}/${ENV_PREFIX}_ESPD1800_I17S_AET_RPO_I17_IADPERICASE_I17_MERGE_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_AET_RPO_I17',  'ESF_IRDPERICASE_I17_MERGE','${DFILP}/${ENV_PREFIX}_ESPD1800_I17S_AET_RPO_I17_IRDPERICASE_I17_MERGE_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')			
		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17SMINV',  'I17S_AET_RPO_I17','')
			insert into BEST..TI17REQFNC values ('I17SQINV',  'I17S_AET_RPO_I17','')
			insert into BEST..TI17REQFNC values ('I17SQPOS',  'I17S_AET_RPO_I17','')
			insert into BEST..TI17REQFNC values ('I17SYINV',  'I17S_AET_RPO_I17','')
			insert into BEST..TI17REQFNC values ('I17SYPOS',  'I17S_AET_RPO_I17','')

	----------IDF_CT:   I4I_ESPD1800 ------------------

		insert into BEST..TI17FNC values ('I4I_ESPD1800',' ','ESPD1800',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I4I_ESPD1800',  'ESF_FI17CLOPER','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD1800',  'ESF_IADVPERICASE_STD','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD1800',  'EPO_FDETTRS','${DFILP}/${ENV_PREFIX}_ESCJ0060_FDETTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD1800',  'EPO_FTRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD1800',  'EPO_FCURCVSN','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURCVSN.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD1800',  'EPO_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD1800',  'EPO_FBOPRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0060_FBOPRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD1800',  'EPO_FCURCVSNI','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURCVSNI.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD1800',  'EPO_FTRANSCODE','${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRANSCODE.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD1800',  'EPO_FCES','${DFILP}/${ENV_PREFIX}_ESID2500_FCES_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD1800',  'EPO_FPLC','${DFILP}/${ENV_PREFIX}_ESID2500_FPLC_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD1800',  'EPO_FPLATXCUM','${DFILP}/${ENV_PREFIX}_ESID0560_FPLATXCUM_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD1800',  'EPO_EPOSOCI','${DFILP}/${ENV_PREFIX}_ESPD0060_EPSOC_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD1800',  'EPO_IADVPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_IADVPERICASE_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD1800',  'EPO_OIRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_OIRDVPERICASE_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD1800',  'EPO_DLSGTR','${DFILP}/${ENV_PREFIX}_ESPD1800_DLSGTR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD1800',  'EPO_DLSGTAA','${DFILP}/${ENV_PREFIX}_ESPD1800_DLSGTAA_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD1800',  'EPO_DLSGTAR','${DFILP}/${ENV_PREFIX}_ESPD1800_DLSGTAR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD1800',  'EPO_DLSGTRCO','${DFILP}/${ENV_PREFIX}_ESPD1800_DLSGTR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I4IQPOC',  'I4I_ESPD1800','')
			insert into BEST..TI17REQFNC values ('I4IQPOCB',  'I4I_ESPD1800','')
			insert into BEST..TI17REQFNC values ('I4IQPOS',  'I4I_ESPD1800','')
			insert into BEST..TI17REQFNC values ('I4IQPOSB',  'I4I_ESPD1800','')
			insert into BEST..TI17REQFNC values ('I4IYPOC',  'I4I_ESPD1800','')
			insert into BEST..TI17REQFNC values ('I4IYPOCB',  'I4I_ESPD1800','')
			insert into BEST..TI17REQFNC values ('I4IYPOS',  'I4I_ESPD1800','')
			insert into BEST..TI17REQFNC values ('I4IYPOSB',  'I4I_ESPD1800','')
go

