-------------------------------
--mapping of  ESFD4020 

	----------   Clean tables   ---------------------

	delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD4020')
	delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD4020')
	delete BEST..TI17FNC where CHAIN_CT='ESFD4020'
	delete BEST..TI17CHN  where CHAIN_CT='ESFD4020'

	insert into BEST..TI17CHN values ('ESFD4020',  'ITD FILE AND QUATERLY FILES')

	----------IDF_CT:   EBS_ESFD4020 ------------------

		insert into BEST..TI17FNC values ('EBS_ESFD4020','IFRS4 Post omega  EBS','ESFD4020',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('EBS_ESFD4020',  'EST_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD4020',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD4020',  'ESF_DLSGTR','${DFILP}/${ENV_PREFIX}_ESPD1800_DLSGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD4020',  'ESF_DLRGTAA','${DFILP}/${ENV_PREFIX}_ESPD2550_DLRGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD4020',  'ESF_DLSGTAA','${DFILP}/${ENV_PREFIX}_ESPD1800_DLSGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD4020',  'ESF_DLSGTAR','${DFILP}/${ENV_PREFIX}_ESPD1800_DLSGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD4020',  'ESF_ARCSTATGTA_AR_ACTUAL_SUM','${DFILP}/${ENV_PREFIX}_ESFD4050_ARCSTATGTA_AR_ACTUAL_SUM.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD4020',  'ESF_DLDGTR_E','${DFILP}/${ENV_PREFIX}_ESPD2570_DLDGTR_E_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD4020',  'ESF_DLREGTAR','${DFILP}/${ENV_PREFIX}_ESPD2550_DLREGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD4020',  'ESF_FTECLEDA_I4I_SUM','${DFILP}/${ENV_PREFIX}_ESFD4050_FTECLEDA_I4I_${PARM_ICLODAT_D}_SUM.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD4020',  'ESF_DLASIIGTAA','${DFILP}/${ENV_PREFIX}_ESPD3630_DLASIIGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD4020',  'ESF_DLASIIGTAR','${DFILP}/${ENV_PREFIX}_ESPD3630_DLASIIGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD4020',  'EST_FCTRGRO','${DFILP}/${ENV_PREFIX}_ESFD5010_FCTRGRO_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD4020',  'ESF_FTECLEDA_I4I_ACMTRS','${DFILP}/${ENV_PREFIX}_ESFD4050_FTECLEDA_I4I_${PARM_ICLODAT_D}_ACMTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD4020',  'ESF_DLDGTAA_E_TRNCODEBS','${DFILP}/${ENV_PREFIX}_ESFD2230_DLDGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD4020',  'EST_IRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5010_IRDPERICASE0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD4020',  'EST_FPLATXCUMALL','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLATXCUMALL0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD4020',  'EST_IADPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5040_IADPERICASE_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD4020',  'ESF_DLRGTAA_DACI17','${DFILP}/${ENV_PREFIX}_ESPD2550_EBS_ESPD2550_DLRGTAA_DACI17_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD4020',  'ESF_DLREGTAR_DACI17','${DFILP}/${ENV_PREFIX}_ESPD2550_EBS_ESPD2550_DLREGTAR_DACI17_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD4020',  'EST_DLCUMGTAAR_ITD','${DFILP}/${ENV_PREFIX}_ESFD4020_DLCUMGTAAR_ITD_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD4020',  'EST_DLCUMGTAAR_MVT','${DFILP}/${ENV_PREFIX}_ESFD4020_DLCUMGTAAR_MVT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('EBSEMINV',  'EBS_ESFD4020','')
			insert into BEST..TI17REQFNC values ('EBSEQINV',  'EBS_ESFD4020','')
			insert into BEST..TI17REQFNC values ('EBSEQPOS',  'EBS_ESFD4020','')
			insert into BEST..TI17REQFNC values ('EBSEYINV',  'EBS_ESFD4020','')
			insert into BEST..TI17REQFNC values ('EBSEYPOS',  'EBS_ESFD4020','')

	----------IDF_CT:   I17G_ESFD4020 ------------------

		insert into BEST..TI17FNC values ('I17G_ESFD4020','IFRS4 Post omega  I17G','ESFD4020',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17G_ESFD4020',  'EST_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD4020',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD4020',  'ESF_DLSGTR','${DFILP}/${ENV_PREFIX}_ESPD1800_DLSGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD4020',  'ESF_DLRGTAA','${DFILP}/${ENV_PREFIX}_ESPD2550_DLRGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD4020',  'ESF_DLSGTAA','${DFILP}/${ENV_PREFIX}_ESPD1800_DLSGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD4020',  'ESF_DLSGTAR','${DFILP}/${ENV_PREFIX}_ESPD1800_DLSGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD4020',  'ESF_ARCSTATGTA_AR_ACTUAL_SUM','${DFILP}/${ENV_PREFIX}_ESFD4050_ARCSTATGTA_AR_ACTUAL_SUM.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD4020',  'ESF_DLDGTR_E','${DFILP}/${ENV_PREFIX}_ESPD2570_DLDGTR_E_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD4020',  'ESF_DLREGTAR','${DFILP}/${ENV_PREFIX}_ESPD2550_DLREGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD4020',  'ESF_FTECLEDA_I4I_SUM','${DFILP}/${ENV_PREFIX}_ESFD4050_FTECLEDA_I4I_${PARM_ICLODAT_D}_SUM.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD4020',  'ESF_DLASIIGTAA','${DFILP}/${ENV_PREFIX}_ESPD3630_DLASIIGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD4020',  'ESF_DLASIIGTAR','${DFILP}/${ENV_PREFIX}_ESPD3630_DLASIIGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD4020',  'EST_FCTRGRO','${DFILP}/${ENV_PREFIX}_ESFD5010_FCTRGRO_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD4020',  'ESF_FTECLEDA_I4I_ACMTRS','${DFILP}/${ENV_PREFIX}_ESFD4050_FTECLEDA_I4I_${PARM_ICLODAT_D}_ACMTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD4020',  'ESF_DLDGTAA_E_TRNCODEBS','${DFILP}/${ENV_PREFIX}_ESID2220_DLDGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD4020',  'EST_IRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5010_IRDPERICASE0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD4020',  'EST_FPLATXCUMALL','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLATXCUMALL0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD4020',  'EST_IADPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5040_IADPERICASE_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD4020',  'ESF_DLRGTAA_DACI17','${DFILP}/${ENV_PREFIX}_ESPD2550_EBS_ESPD2550_DLRGTAA_DACI17_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD4020',  'ESF_DLREGTAR_DACI17','${DFILP}/${ENV_PREFIX}_ESPD2550_EBS_ESPD2550_DLREGTAR_DACI17_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD4020',  'EST_DLCUMGTAAR_ITD','${DFILP}/${ENV_PREFIX}_ESFD4020_DLCUMGTAAR_ITD_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD4020',  'EST_DLCUMGTAAR_MVT','${DFILP}/${ENV_PREFIX}_ESFD4020_DLCUMGTAAR_MVT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17GMINV',  'I17G_ESFD4020','')
			insert into BEST..TI17REQFNC values ('I17GQINV',  'I17G_ESFD4020','')
			insert into BEST..TI17REQFNC values ('I17GQPOS',  'I17G_ESFD4020','')
			insert into BEST..TI17REQFNC values ('I17GYINV',  'I17G_ESFD4020','')
			insert into BEST..TI17REQFNC values ('I17GYPOS',  'I17G_ESFD4020','')

	----------IDF_CT:   I17S_ESFD4020 ------------------

		insert into BEST..TI17FNC values ('I17S_ESFD4020','IFRS4 Post omega  I17G','ESFD4020',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17S_ESFD4020',  'EST_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD4020',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD4020',  'ESF_DLSGTR','${DFILP}/${ENV_PREFIX}_ESPD1800_DLSGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD4020',  'ESF_DLRGTAA','${DFILP}/${ENV_PREFIX}_ESPD2550_DLRGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD4020',  'ESF_DLSGTAA','${DFILP}/${ENV_PREFIX}_ESPD1800_DLSGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD4020',  'ESF_DLSGTAR','${DFILP}/${ENV_PREFIX}_ESPD1800_DLSGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD4020',  'ESF_ARCSTATGTA_AR_ACTUAL_SUM','${DFILP}/${ENV_PREFIX}_ESFD4050_ARCSTATGTA_AR_ACTUAL_SUM.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD4020',  'ESF_DLDGTR_E','${DFILP}/${ENV_PREFIX}_ESPD2570_DLDGTR_E_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD4020',  'ESF_DLREGTAR','${DFILP}/${ENV_PREFIX}_ESPD2550_DLREGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD4020',  'ESF_FTECLEDA_I4I_SUM','${DFILP}/${ENV_PREFIX}_ESFD4050_FTECLEDA_I4I_${PARM_ICLODAT_D}_SUM.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD4020',  'ESF_DLASIIGTAA','${DFILP}/${ENV_PREFIX}_ESPD3630_DLASIIGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD4020',  'ESF_DLASIIGTAR','${DFILP}/${ENV_PREFIX}_ESPD3630_DLASIIGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD4020',  'EST_FCTRGRO','${DFILP}/${ENV_PREFIX}_ESFD5010_FCTRGRO_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD4020',  'ESF_FTECLEDA_I4I_ACMTRS','${DFILP}/${ENV_PREFIX}_ESFD4050_FTECLEDA_I4I_${PARM_ICLODAT_D}_ACMTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD4020',  'ESF_DLDGTAA_E_TRNCODEBS','${DFILP}/${ENV_PREFIX}_ESID2220_DLDGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD4020',  'EST_IRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5010_IRDPERICASE0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD4020',  'EST_FPLATXCUMALL','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLATXCUMALL0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD4020',  'EST_IADPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5040_IADPERICASE_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD4020',  'ESF_DLRGTAA_DACI17','${DFILP}/${ENV_PREFIX}_ESPD2550_EBS_ESPD2550_DLRGTAA_DACI17_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD4020',  'ESF_DLREGTAR_DACI17','${DFILP}/${ENV_PREFIX}_ESPD2550_EBS_ESPD2550_DLREGTAR_DACI17_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD4020',  'EST_DLCUMGTAAR_ITD','${DFILP}/${ENV_PREFIX}_ESFD4020_DLCUMGTAAR_ITD_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD4020',  'EST_DLCUMGTAAR_MVT','${DFILP}/${ENV_PREFIX}_ESFD4020_DLCUMGTAAR_MVT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17SMINV',  'I17S_ESFD4020','')
			insert into BEST..TI17REQFNC values ('I17SQINV',  'I17S_ESFD4020','')
			insert into BEST..TI17REQFNC values ('I17SQPOS',  'I17S_ESFD4020','')
			insert into BEST..TI17REQFNC values ('I17SYINV',  'I17S_ESFD4020','')
			insert into BEST..TI17REQFNC values ('I17SYPOS',  'I17S_ESFD4020','')
go

