-------------------------------
--mapping of  ESPD3810

	----------   Clean tables   ---------------------

	delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESPD3810')
	delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESPD3810')
	delete BEST..TI17FNC where CHAIN_CT='ESPD3810'
	delete BEST..TI17CHN  where CHAIN_CT='ESPD3810'

	insert into BEST..TI17CHN values ('ESPD3810',  'GAAPCod BDA to GLT')

	----------IDF_CT:   EBS_ESPD3810 ------------------

		insert into BEST..TI17FNC values ('EBS_ESPD3810','IFRS4 Post omega  EBS','ESPD3810',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('EBS_ESPD3810',  'EST_FTECLEDA_MTH','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3810',  'ESF_FCTRI17PRD_NEW','${DFILP}/${ENV_PREFIX}_ESFD0040_FCTRI17PRD.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3810',  'ESF_FI17PRODUCT_CUR','${DFILP}/${ENV_PREFIX}_ESFD0040_FI17PRODUCT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3810',  'EPO_GAAPCOD_MAPPING','${DFILP}/${ENV_PREFIX}_ESCJ0060_GAAPCOD_MAPPING.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3810',  'EPO_FTECLEDACO_ANNULMVT','${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_ANNULMVT_EBS_POC.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3810',  'EPO_FTECLEDA','$DFILP/${ENV_PREFIX}_ESPD3800_FTECLEDA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3810',  'EPO_FTECLEDR','${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3810',  'ESF_FCTRI17PRD_OVR','${DFILP}/${ENV_PREFIX}_ESFD0040_FCTRI17PRD_OVR_EBS.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3810',  'ESF_FI17PRODUCT_OVR','${DFILP}/${ENV_PREFIX}_ESFD0040_FI17PRODUCT_OVR_EBS.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3810',  'ESF_FTECLEDA_MVT_LOCALSIT','$DFILP/${ENV_PREFIX}_ESPD3800_FTECLEDA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('EBSEYPOC',  'EBS_ESPD3810','')
			insert into BEST..TI17REQFNC values ('EBSEQPOC',  'EBS_ESPD3810','')
			insert into BEST..TI17REQFNC values ('EBSEQINVB',  'EBS_ESPD3810','')
			insert into BEST..TI17REQFNC values ('EBSEYINVB',  'EBS_ESPD3810','')
			insert into BEST..TI17REQFNC values ('EBSEQPOSB',  'EBS_ESPD3810','')
			insert into BEST..TI17REQFNC values ('EBSEYPOSB',  'EBS_ESPD3810','')
			insert into BEST..TI17REQFNC values ('EBSEQPOCB',  'EBS_ESPD3810','')
			insert into BEST..TI17REQFNC values ('EBSEYPOCB',  'EBS_ESPD3810','')
			insert into BEST..TI17REQFNC values ('EBSEQPOSP',  'EBS_ESPD3810','')
			insert into BEST..TI17REQFNC values ('EBSEYPOSP',  'EBS_ESPD3810','')
			insert into BEST..TI17REQFNC values ('EBSEMINV',  'EBS_ESPD3810','')
			insert into BEST..TI17REQFNC values ('EBSEQINV',  'EBS_ESPD3810','')
			insert into BEST..TI17REQFNC values ('EBSEQPOS',  'EBS_ESPD3810','')
			insert into BEST..TI17REQFNC values ('EBSEYINV',  'EBS_ESPD3810','')
			insert into BEST..TI17REQFNC values ('EBSEYPOS',  'EBS_ESPD3810','')

	----------IDF_CT:   I4I_ESPD3810 ------------------

		insert into BEST..TI17FNC values ('I4I_ESPD3810','IFRS4 Post omega  IFRS','ESPD3810',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I4I_ESPD3810',  'ESF_FCTRI17PRD_NEW','${DFILP}/${ENV_PREFIX}_ESFD0040_FCTRI17PRD.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3810',  'ESF_FI17PRODUCT_CUR','${DFILP}/${ENV_PREFIX}_ESFD0040_FI17PRODUCT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3810',  'EPO_GAAPCOD_MAPPING','${DFILP}/${ENV_PREFIX}_ESCJ0060_GAAPCOD_MAPPING.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3810',  'EPO_FTECLEDACO_ANNULMVT','${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_ANNULMVT_I4I_POC.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3810',  'EST_FTECLEDA_MTH','${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_MTH_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3810',  'EPO_FTECLEDR','`if [ "${TYPEINV}" = "POC" ];then echo ${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_I4I_POC_${PARM_ICLODAT_D}.dat;else echo ${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_I4I_${PARM_ICLODAT_D}.dat;fi;`','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3810',  'EPO_FTECLEDA','`if [ "${TYPEINV}" = "POC" ];then echo ${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_I4I_POC_${PARM_ICLODAT_D}.dat;else echo ${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_MVT_I4I_POS_${PARM_ICLODAT_D}.dat;fi;`','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3810',  'ESF_FCTRI17PRD_OVR','${DFILP}/${ENV_PREFIX}_ESFD0040_FCTRI17PRD_OVR_MVT_I4I.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3810',  'ESF_FI17PRODUCT_OVR','${DFILP}/${ENV_PREFIX}_ESFD0040_FI17PRODUCT_OVR_MVT_I4I.dat','O','')

			insert into BEST..TI17PERMFIL values ('I4I_ESPD3810',  'ESF_FTECLEDA_MVT_FROMAS','${DFILP}/${ENV_PREFIX}_ESPD3910_EBS_FTECLEDA_MVT_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_ASTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3810',  'ESF_FTECLEDA_MVT_FROMEU','${DFILP}/${ENV_PREFIX}_ESPD3910_EBS_FTECLEDA_MVT_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_EUTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3810',  'ESF_FTECLEDA_MVT_FROMAM','${DFILP}/${ENV_PREFIX}_ESPD3910_EBS_FTECLEDA_MVT_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_AMTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3810',  'ESF_FTECLEDA_MVT_TOAS','${ENV_PREFIX}_ESPD3910_EBS_FTECLEDA_MVT_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOAS}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3810',  'ESF_FTECLEDA_MVT_TOEU','${ENV_PREFIX}_ESPD3910_EBS_FTECLEDA_MVT_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOEU}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3810',  'ESF_FTECLEDA_MVT_TOAM','${ENV_PREFIX}_ESPD3910_EBS_FTECLEDA_MVT_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOAM}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3810',  'ESF_FTECLEDA_MVT_LOCALSIT','`if [ "${TYPEINV}" = "POC" ];then echo ${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_I4I_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat;else echo ${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_MVT_I4I_POS_${PARM_ICLODAT_D}.dat;fi;`','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3810',  'ESF_FCTRI17PRD_FROMAS','${DFILP}/${ENV_PREFIX}_ESFD0040_FCTRI17PRD_${PARAM_ASTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3810',  'EPO_GAAPCOD_MAPPING_FROMAS','${DFILP}/${ENV_PREFIX}_ESCJ0060_GAAPCOD_MAPPING_${PARAM_ASTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3810',  'ESF_FCTRI17PRD_FROMEU','${DFILP}/${ENV_PREFIX}_ESFD0040_FCTRI17PRD_${PARAM_EUTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3810',  'EPO_GAAPCOD_MAPPING_FROMEU','${DFILP}/${ENV_PREFIX}_ESCJ0060_GAAPCOD_MAPPING_${PARAM_EUTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3810',  'ESF_FCTRI17PRD_FROMAM','${DFILP}/${ENV_PREFIX}_ESFD0040_FCTRI17PRD_${PARAM_AMTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3810',  'EPO_GAAPCOD_MAPPING_FROMAM','${DFILP}/${ENV_PREFIX}_ESCJ0060_GAAPCOD_MAPPING_${PARAM_AMTOLOCAL}.dat','I','')			


		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I4IQPOS',  'I4I_ESPD3810','')
			insert into BEST..TI17REQFNC values ('I4IYPOS',  'I4I_ESPD3810','')
			insert into BEST..TI17REQFNC values ('I4IYPOSB',  'I4I_ESPD3810','')
			insert into BEST..TI17REQFNC values ('I4IQPOSB',  'I4I_ESPD3810','')
			insert into BEST..TI17REQFNC values ('I4IQPOC',  'I4I_ESPD3810','')
			insert into BEST..TI17REQFNC values ('I4IYPOC',  'I4I_ESPD3810','')
			insert into BEST..TI17REQFNC values ('I4IYPOCB',  'I4I_ESPD3810','')
			insert into BEST..TI17REQFNC values ('I4IQPOCB',  'I4I_ESPD3810','')
			insert into BEST..TI17REQFNC values ('I4IQPOSP',  'I4I_ESPD3810','')
			insert into BEST..TI17REQFNC values ('I4IYPOSP',  'I4I_ESPD3810','')
go

