-------------------------------
--mapping of  ESFD2900

	----------   Clean tables   ---------------------

	delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD2900')
	delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD2900')
	delete BEST..TI17FNC where CHAIN_CT='ESFD2900'
	delete BEST..TI17CHN  where CHAIN_CT='ESFD2900'

	insert into BEST..TI17CHN values ('ESFD2900',  'Generate Annual opening data for IFRS17')

	----------IDF_CT:   EBS_OMG_OPNG_SIM ------------------

		insert into BEST..TI17FNC values ('EBS_OMG_OPNG_SIM','Generate Annual opening data for EBS','ESFD2900',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('EBS_OMG_OPNG_SIM',  'ESF_FDETTRS','${DFILP}/${ENV_PREFIX}_ESCJ0660_FDETTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_OMG_OPNG_SIM',  'ESF_GROUPING_TC_TOOMIT','${DFILP}/${ENV_PREFIX}_ESPD0060_GROUPING_TC_TOOMIT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_OMG_OPNG_SIM',  'ESF_FTECLEDA_CUR','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDA_CUR_SIM_${NORME_CF}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_OMG_OPNG_SIM',  'ESF_FTECLEDA_CUR_SRC','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDA_CUR_${NORME_CF}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_OMG_OPNG_SIM',  'ESF_FTECLEDR_CUR','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDR_CUR_SIM_${NORME_CF}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_OMG_OPNG_SIM',  'ESF_FTECLEDR_CUR_SRC','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDR_CUR_${NORME_CF}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_OMG_OPNG_SIM',  'ESF_FTECLEDA_POSTING','${DFILP}/${ENV_PREFIX}_ESPD3970_EBS_MVT_MRG_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_OMG_OPNG_SIM',  'ESF_FTECLEDR_POSTING','$DFILP/${ENV_PREFIX}_ESPD3970_FTECLEDR_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_OMG_OPNG_SIM',  'ESF_FTECLEDA_OPNG','${DFILP}/${ENV_PREFIX}_ESFD2900_FTECLEDA_OPNG_SIM_${NORME_CF}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_OMG_OPNG_SIM',  'ESF_FTECLEDR_OPNG','${DFILP}/${ENV_PREFIX}_ESFD2900_FTECLEDR_OPNG_SIM_${NORME_CF}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_OMG_OPNG_SIM',  'ESF_FTECLEDA_OPNG_ARC','${DARCH}/${ENV_PREFIX}_ESFD2900_FTECLEDA_OPNG_SIM_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}.dat.gz','O','')
			insert into BEST..TI17PERMFIL values ('EBS_OMG_OPNG_SIM',  'ESF_FTECLEDR_OPNG_ARC','${DARCH}/${ENV_PREFIX}_ESFD2900_FTECLEDR_OPNG_SIM_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}.dat.gz','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('EBSEYPOS',  'EBS_OMG_OPNG_SIM','')
			insert into BEST..TI17REQFNC values ('EBSEYPOSB',  'EBS_OMG_OPNG_SIM','')
			insert into BEST..TI17REQFNC values ('EBSEYINV',  'EBS_OMG_OPNG_SIM','')
			insert into BEST..TI17REQFNC values ('EBSEYINVB',  'EBS_OMG_OPNG_SIM','')
			insert into BEST..TI17REQFNC values ('EBSEYPOSP',  'EBS_OMG_OPNG_SIM','')

	----------IDF_CT:   EBS_OMG_OPNG_STD ------------------

		insert into BEST..TI17FNC values ('EBS_OMG_OPNG_STD','Generate Annual opening data for EBS','ESFD2900',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('EBS_OMG_OPNG_STD',  'ESF_FDETTRS','${DFILP}/${ENV_PREFIX}_ESCJ0660_FDETTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_OMG_OPNG_STD',  'ESF_FTECLEDA_CUR','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDA_CUR_${NORME_CF}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_OMG_OPNG_STD',  'ESF_FTECLEDR_CUR','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDR_CUR_${NORME_CF}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_OMG_OPNG_STD',  'ESF_GROUPING_TC_TOOMIT','${DFILP}/${ENV_PREFIX}_ESPD0060_GROUPING_TC_TOOMIT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_OMG_OPNG_STD',  'ESF_FTECLEDA_OPNG','${DFILP}/${ENV_PREFIX}_ESFD2900_FTECLEDA_OPNG_${NORME_CF}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_OMG_OPNG_STD',  'ESF_FTECLEDR_OPNG','${DFILP}/${ENV_PREFIX}_ESFD2900_FTECLEDR_OPNG_${NORME_CF}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_OMG_OPNG_STD',  'ESF_FTECLEDA_OPNG_ARC','${DARCH}/${ENV_PREFIX}_ESFD2900_FTECLEDA_OPNG_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}.dat.gz','O','')
			insert into BEST..TI17PERMFIL values ('EBS_OMG_OPNG_STD',  'ESF_FTECLEDR_OPNG_ARC','${DARCH}/${ENV_PREFIX}_ESFD2900_FTECLEDR_OPNG_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}.dat.gz','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('EBSEYPOSB',  'EBS_OMG_OPNG_STD','')

	----------IDF_CT:   I17G_OMG_OPNG_SIM ------------------

		insert into BEST..TI17FNC values ('I17G_OMG_OPNG_SIM','Generate Annual opening data for I17G','ESFD2900',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17G_OMG_OPNG_SIM',  'ESF_FDETTRS','${DFILP}/${ENV_PREFIX}_ESCJ0660_FDETTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_OPNG_SIM',  'ESF_GROUPING_TC_TOOMIT','${DFILP}/${ENV_PREFIX}_ESPD0060_GROUPING_TC_TOOMIT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_OPNG_SIM',  'ESF_FTECLEDA_CUR','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDA_CUR_SIM_${NORME_CF}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_OPNG_SIM',  'ESF_FTECLEDA_CUR_SRC','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDA_CUR_${NORME_CF}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_OPNG_SIM',  'ESF_FTECLEDR_CUR','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDR_CUR_SIM_${NORME_CF}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_OPNG_SIM',  'ESF_FTECLEDR_CUR_SRC','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDR_CUR_${NORME_CF}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_OPNG_SIM',  'ESF_FTECLEDR_POSTING','$DFILP/${ENV_PREFIX}_ESFD3840_${NORME_CF}_GLT_MRG_STD_FTECLEDR_MVT_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_OPNG_SIM',  'ESF_FTECLEDA_POSTING','${DFILP}/${ENV_PREFIX}_ESPD3970_I17G_MVT_MRG_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_OPNG_SIM',  'ESF_FTECLEDA_OPNG','${DFILP}/${ENV_PREFIX}_ESFD2900_FTECLEDA_OPNG_SIM_${NORME_CF}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_OPNG_SIM',  'ESF_FTECLEDR_OPNG','${DFILP}/${ENV_PREFIX}_ESFD2900_FTECLEDR_OPNG_SIM_${NORME_CF}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_OPNG_SIM',  'ESF_FTECLEDA_OPNG_ARC','${DARCH}/${ENV_PREFIX}_ESFD2900_FTECLEDA_OPNG_SIM_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}.dat.gz','O','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_OPNG_SIM',  'ESF_FTECLEDR_OPNG_ARC','${DARCH}/${ENV_PREFIX}_ESFD2900_FTECLEDR_OPNG_SIM_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}.dat.gz','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17GYPOS',  'I17G_OMG_OPNG_SIM','')
			insert into BEST..TI17REQFNC values ('I17GYPOSB',  'I17G_OMG_OPNG_SIM','')
			insert into BEST..TI17REQFNC values ('I17GYINV',  'I17G_OMG_OPNG_SIM','')
			insert into BEST..TI17REQFNC values ('I17GYINVB',  'I17G_OMG_OPNG_SIM','')
			insert into BEST..TI17REQFNC values ('I17GYPOSP',  'I17G_OMG_OPNG_SIM','')

	----------IDF_CT:   I17G_OMG_OPNG_STD ------------------

		insert into BEST..TI17FNC values ('I17G_OMG_OPNG_STD','Generate Annual opening data for I17G','ESFD2900',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17G_OMG_OPNG_STD',  'ESF_FDETTRS','${DFILP}/${ENV_PREFIX}_ESCJ0660_FDETTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_OPNG_STD',  'ESF_FTECLEDA_CUR','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDA_CUR_${NORME_CF}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_OPNG_STD',  'ESF_FTECLEDR_CUR','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDR_CUR_${NORME_CF}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_OPNG_STD',  'ESF_GROUPING_TC_TOOMIT','${DFILP}/${ENV_PREFIX}_ESPD0060_GROUPING_TC_TOOMIT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_OPNG_STD',  'ESF_FTECLEDA_OPNG','${DFILP}/${ENV_PREFIX}_ESFD2900_FTECLEDA_OPNG_${NORME_CF}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_OPNG_STD',  'ESF_FTECLEDR_OPNG','${DFILP}/${ENV_PREFIX}_ESFD2900_FTECLEDR_OPNG_${NORME_CF}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_OPNG_STD',  'I17S_ESF_FTECLEDA_OPNG','${DFILP}/${ENV_PREFIX}_ESFD2900_FTECLEDA_OPNG_I17S_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_OPNG_STD',  'I17S_ESF_FTECLEDR_OPNG','${DFILP}/${ENV_PREFIX}_ESFD2900_FTECLEDR_OPNG_I17S_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_OPNG_STD',  'ESF_FTECLEDA_OPNG_ARC','${DARCH}/${ENV_PREFIX}_ESFD2900_FTECLEDA_OPNG_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}.dat.gz','O','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_OPNG_STD',  'ESF_FTECLEDR_OPNG_ARC','${DARCH}/${ENV_PREFIX}_ESFD2900_FTECLEDR_OPNG_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}.dat.gz','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17GYPOSB',  'I17G_OMG_OPNG_STD','')

	----------IDF_CT:   I17L_OMG_OPNG_SIM ------------------

		insert into BEST..TI17FNC values ('I17L_OMG_OPNG_SIM','Generate Annual opening data for I17L','ESFD2900',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17L_OMG_OPNG_SIM',  'ESF_FDETTRS','${DFILP}/${ENV_PREFIX}_ESCJ0660_FDETTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_OMG_OPNG_SIM',  'ESF_GROUPING_TC_TOOMIT','${DFILP}/${ENV_PREFIX}_ESPD0060_GROUPING_TC_TOOMIT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_OMG_OPNG_SIM',  'ESF_FTECLEDA_CUR','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDA_CUR_SIM_${NORME_CF}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_OMG_OPNG_SIM',  'ESF_FTECLEDA_CUR_SRC','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDA_CUR_${NORME_CF}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_OMG_OPNG_SIM',  'ESF_FTECLEDR_CUR','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDR_CUR_SIM_${NORME_CF}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_OMG_OPNG_SIM',  'ESF_FTECLEDR_CUR_SRC','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDR_CUR_${NORME_CF}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_OMG_OPNG_SIM',  'ESF_FTECLEDR_POSTING','$DFILP/${ENV_PREFIX}_ESFD3840_${NORME_CF}_GLT_MRG_STD_FTECLEDR_MVT_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_OMG_OPNG_SIM',  'ESF_FTECLEDA_POSTING','${DFILP}/${ENV_PREFIX}_ESPD3970_I17L_MVT_MRG_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_OMG_OPNG_SIM',  'ESF_FTECLEDA_OPNG','${DFILP}/${ENV_PREFIX}_ESFD2900_FTECLEDA_OPNG_SIM_${NORME_CF}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_OMG_OPNG_SIM',  'ESF_FTECLEDR_OPNG','${DFILP}/${ENV_PREFIX}_ESFD2900_FTECLEDR_OPNG_SIM_${NORME_CF}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_OMG_OPNG_SIM',  'ESF_FTECLEDA_OPNG_ARC','${DARCH}/${ENV_PREFIX}_ESFD2900_FTECLEDA_OPNG_SIM_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}.dat.gz','O','')
			insert into BEST..TI17PERMFIL values ('I17L_OMG_OPNG_SIM',  'ESF_FTECLEDR_OPNG_ARC','${DARCH}/${ENV_PREFIX}_ESFD2900_FTECLEDR_OPNG_SIM_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}.dat.gz','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17LYINV',  'I17L_OMG_OPNG_SIM','')
			insert into BEST..TI17REQFNC values ('I17LYINVB',  'I17L_OMG_OPNG_SIM','')
			insert into BEST..TI17REQFNC values ('I17LYPOSP',  'I17L_OMG_OPNG_SIM','')
			insert into BEST..TI17REQFNC values ('I17LYPOS',  'I17L_OMG_OPNG_SIM','')
			insert into BEST..TI17REQFNC values ('I17LYPOSB',  'I17L_OMG_OPNG_SIM','')
			insert into BEST..TI17REQFNC values ('I17LYPOSX',  'I17L_OMG_OPNG_SIM','')

	----------IDF_CT:   I17L_OMG_OPNG_STD ------------------

		insert into BEST..TI17FNC values ('I17L_OMG_OPNG_STD','Generate Annual opening data for I17L','ESFD2900',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17L_OMG_OPNG_STD',  'ESF_FDETTRS','${DFILP}/${ENV_PREFIX}_ESCJ0660_FDETTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_OMG_OPNG_STD',  'ESF_FTECLEDA_CUR','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDA_CUR_${NORME_CF}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_OMG_OPNG_STD',  'ESF_FTECLEDR_CUR','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDR_CUR_${NORME_CF}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_OMG_OPNG_STD',  'ESF_GROUPING_TC_TOOMIT','${DFILP}/${ENV_PREFIX}_ESPD0060_GROUPING_TC_TOOMIT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_OMG_OPNG_STD',  'ESF_FTECLEDA_OPNG','${DFILP}/${ENV_PREFIX}_ESFD2900_FTECLEDA_OPNG_${NORME_CF}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_OMG_OPNG_STD',  'ESF_FTECLEDR_OPNG','${DFILP}/${ENV_PREFIX}_ESFD2900_FTECLEDR_OPNG_${NORME_CF}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_OMG_OPNG_STD',  'ESF_FTECLEDA_OPNG_ARC','${DARCH}/${ENV_PREFIX}_ESFD2900_FTECLEDA_OPNG_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}.dat.gz','O','')
			insert into BEST..TI17PERMFIL values ('I17L_OMG_OPNG_STD',  'ESF_FTECLEDR_OPNG_ARC','${DARCH}/${ENV_PREFIX}_ESFD2900_FTECLEDR_OPNG_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}.dat.gz','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17LYPOSB',  'I17L_OMG_OPNG_STD','')

	----------IDF_CT:   I17P_OMG_OPNG_SIM ------------------

		insert into BEST..TI17FNC values ('I17P_OMG_OPNG_SIM','Generate Annual opening data for I17P','ESFD2900',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17P_OMG_OPNG_SIM',  'ESF_FDETTRS','${DFILP}/${ENV_PREFIX}_ESCJ0660_FDETTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_OMG_OPNG_SIM',  'ESF_GROUPING_TC_TOOMIT','${DFILP}/${ENV_PREFIX}_ESPD0060_GROUPING_TC_TOOMIT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_OMG_OPNG_SIM',  'ESF_FTECLEDA_CUR','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDA_CUR_SIM_${NORME_CF}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_OMG_OPNG_SIM',  'ESF_FTECLEDA_CUR_SRC','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDA_CUR_${NORME_CF}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_OMG_OPNG_SIM',  'ESF_FTECLEDR_CUR','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDR_CUR_SIM_${NORME_CF}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_OMG_OPNG_SIM',  'ESF_FTECLEDR_CUR_SRC','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDR_CUR_${NORME_CF}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_OMG_OPNG_SIM',  'ESF_FTECLEDR_POSTING','$DFILP/${ENV_PREFIX}_ESFD3840_${NORME_CF}_GLT_MRG_STD_FTECLEDR_MVT_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_OMG_OPNG_SIM',  'ESF_FTECLEDA_POSTING','${DFILP}/${ENV_PREFIX}_ESPD3970_I17P_MVT_MRG_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_OMG_OPNG_SIM',  'ESF_FTECLEDA_OPNG','${DFILP}/${ENV_PREFIX}_ESFD2900_FTECLEDA_OPNG_SIM_${NORME_CF}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_OMG_OPNG_SIM',  'ESF_FTECLEDR_OPNG','${DFILP}/${ENV_PREFIX}_ESFD2900_FTECLEDR_OPNG_SIM_${NORME_CF}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_OMG_OPNG_SIM',  'ESF_FTECLEDA_OPNG_ARC','${DARCH}/${ENV_PREFIX}_ESFD2900_FTECLEDA_OPNG_SIM_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}.dat.gz','O','')
			insert into BEST..TI17PERMFIL values ('I17P_OMG_OPNG_SIM',  'ESF_FTECLEDR_OPNG_ARC','${DARCH}/${ENV_PREFIX}_ESFD2900_FTECLEDR_OPNG_SIM_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}.dat.gz','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17PYPOS',  'I17P_OMG_OPNG_SIM','')
			insert into BEST..TI17REQFNC values ('I17PYPOSB',  'I17P_OMG_OPNG_SIM','')
			insert into BEST..TI17REQFNC values ('I17PYINV',  'I17P_OMG_OPNG_SIM','')
			insert into BEST..TI17REQFNC values ('I17PYINVB',  'I17P_OMG_OPNG_SIM','')
			insert into BEST..TI17REQFNC values ('I17PYPOSP',  'I17P_OMG_OPNG_SIM','')
			insert into BEST..TI17REQFNC values ('I17PYPOSX',  'I17P_OMG_OPNG_SIM','')

	----------IDF_CT:   I17P_OMG_OPNG_STD ------------------

		insert into BEST..TI17FNC values ('I17P_OMG_OPNG_STD','Generate Annual opening data for I17P','ESFD2900',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17P_OMG_OPNG_STD',  'ESF_FDETTRS','${DFILP}/${ENV_PREFIX}_ESCJ0660_FDETTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_OMG_OPNG_STD',  'ESF_FTECLEDA_CUR','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDA_CUR_${NORME_CF}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_OMG_OPNG_STD',  'ESF_FTECLEDR_CUR','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDR_CUR_${NORME_CF}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_OMG_OPNG_STD',  'ESF_GROUPING_TC_TOOMIT','${DFILP}/${ENV_PREFIX}_ESPD0060_GROUPING_TC_TOOMIT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_OMG_OPNG_STD',  'ESF_FTECLEDA_OPNG','${DFILP}/${ENV_PREFIX}_ESFD2900_FTECLEDA_OPNG_${NORME_CF}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_OMG_OPNG_STD',  'ESF_FTECLEDR_OPNG','${DFILP}/${ENV_PREFIX}_ESFD2900_FTECLEDR_OPNG_${NORME_CF}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_OMG_OPNG_STD',  'ESF_FTECLEDA_OPNG_ARC','${DARCH}/${ENV_PREFIX}_ESFD2900_FTECLEDA_OPNG_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}.dat.gz','O','')
			insert into BEST..TI17PERMFIL values ('I17P_OMG_OPNG_STD',  'ESF_FTECLEDR_OPNG_ARC','${DARCH}/${ENV_PREFIX}_ESFD2900_FTECLEDR_OPNG_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}.dat.gz','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17PYPOSB',  'I17P_OMG_OPNG_STD','')
go

