-------------------------------
--mapping of  ESFD4010

	----------   Clean tables   ---------------------

	delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD4010')
	delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD4010')
	delete BEST..TI17FNC where CHAIN_CT='ESFD4010'
	delete BEST..TI17CHN  where CHAIN_CT='ESFD4010'

	insert into BEST..TI17CHN values ('ESFD4010',  'Premium Allocated Approach')

	----------IDF_CT:   I17L_PAA_ALL_STD ------------------

		insert into BEST..TI17FNC values ('I17L_PAA_ALL_STD','Local - Premium Allocated Approach','ESFD4010',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17L_PAA_ALL_STD',  'ESF_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_PAA_ALL_STD',  'EPO_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_PAA_ALL_STD',  'ESF_FTECLEDA_REJ','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDA_REJ_I17L.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_PAA_ALL_STD',  'ESF_FTECLEDR_REJ','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDR_REJ_I17L.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_PAA_ALL_STD',  'ESF_FTECLEDA_OPNG','${DFILP}/${ENV_PREFIX}_ESFD2900_FTECLEDA_OPNG_I17L.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_PAA_ALL_STD',  'ESF_FTECLEDR_OPNG','${DFILP}/${ENV_PREFIX}_ESFD2900_FTECLEDR_OPNG_I17L.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_PAA_ALL_STD',  'EST_FCES','${DFILP}/${ENV_PREFIX}_ESFD5040_FCES_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_PAA_ALL_STD',  'EST_FPLC','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLC_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_PAA_ALL_STD',  'EST_DLCUMGTAAR','${DFILP}/${ENV_PREFIX}_ESFD4020_DLCUMGTAAR_MVT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_PAA_ALL_STD',  'EST_IRDPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE0_I17L_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_PAA_ALL_STD',  'EST_ACC_NDIC_AMOUNT','${DFILP}/${ENV_PREFIX}_ESFD3920_NDC_ALL_STD_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_PAA_ALL_STD',  'ESF_FTECLEDR','${DFILP}/${ENV_PREFIX}_ESFD3870_I17L_GLT_ALL_STD_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_PAA_ALL_STD',  'EST_IADPERICASE_STD','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17L_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_PAA_ALL_STD',  'EST_ACC_RETRO_NDIC_AMOUNT','${DFILP}/${ENV_PREFIX}_ESFD3950_NDCR_ALL_STD_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_PAA_ALL_STD',  'ESF_FTECLEDA','${DFILP}/${ENV_PREFIX}_ESFD3870_I17L_GLT_ALL_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_PAA_ALL_STD',  'ESF_FI17CLOPER','${DFILP}/${ENV_PREFIX}_ESFD1130_FI17CLOPER_I17L_DSC_ALL_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_PAA_ALL_STD',  'EST_PAA_ASSUM','${DFILP}/${ENV_PREFIX}_ESFD4010_I17L_PAA_ALL_STD_PAA_ASSUM_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_PAA_ALL_STD',  'EST_PAA_RETRO','${DFILP}/${ENV_PREFIX}_ESFD4010_I17L_PAA_ALL_STD_PAA_RETRO_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17LYPOSX',  'I17L_PAA_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17LQPOSX',  'I17L_PAA_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17LMINV',  'I17L_PAA_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17LQINV',  'I17L_PAA_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17LQPOS',  'I17L_PAA_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17LYINV',  'I17L_PAA_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17LYPOS',  'I17L_PAA_ALL_STD','')
go

