
--select * from BEST..TI17TRAPERMFIL where  PATHPATTRN_LL like '%_ESCJ0060_FBOPRSLNK[_]%' and PATHPATTRN_LL not like  '%ESCJ0060_FBOPRSLNK_TXT%'
update BEST..TI17TRAPERMFIL set PATHPATTRN_LL ="${DFILP}/${ENV_PREFIX}_ESCJ0060_FBOPRSLNK.dat"  where  PATHPATTRN_LL like '%_ESCJ0060_FBOPRSLNK[_]%' and PATHPATTRN_LL not like  '%ESCJ0060_FBOPRSLNK_TXT%'
--select * from BEST..TI17TRAPERMFIL where  PATHPATTRN_LL like '%_ESCJ0060_FBOPRSLNK.dat' and PATHPATTRN_LL not like  '%ESCJ0060_FBOPRSLNK_TXT%'

--select * from BEST..TI17TRAPERMFIL where  PATHPATTRN_LL like '%ESCJ0060_FBOPRSLNK_TXT[_]%' 
update BEST..TI17TRAPERMFIL set PATHPATTRN_LL ="${DFILP}/${ENV_PREFIX}_ESCJ0060_FBOPRSLNK_TXT.dat"  where  PATHPATTRN_LL like  '%ESCJ0060_FBOPRSLNK_TXT%' 
--select * from BEST..TI17TRAPERMFIL where PATHPATTRN_LL like  '%ESCJ0060_FBOPRSLNK_TXT.dat'  


--select * from BEST..TI17TRAPERMFIL where  PATHPATTRN_LL like '%_ESCJ0060_FCURCVSN[_]%' 
update BEST..TI17TRAPERMFIL set PATHPATTRN_LL ="${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURCVSN.dat"  where  PATHPATTRN_LL like  '%_ESCJ0060_FCURCVSN[_]%' 
--select * from BEST..TI17TRAPERMFIL where PATHPATTRN_LL like  '%_ESCJ0060_FCURCVSN.dat' 


--select * from BEST..TI17TRAPERMFIL where  PATHPATTRN_LL like '%_ESCJ0060_FCURCVSNI[_]%' 
update BEST..TI17TRAPERMFIL set PATHPATTRN_LL ="${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURCVSNI.dat"  where  PATHPATTRN_LL like  '%_ESCJ0060_FCURCVSNI[_]%' 
--select * from BEST..TI17TRAPERMFIL where PATHPATTRN_LL like  '%_ESCJ0060_FCURCVSNI.dat' 


--select * from BEST..TI17TRAPERMFIL where  PATHPATTRN_LL like '%_ESCJ0060_FCURQUOT[_]%' and PATHPATTRN_LL not like  '%_ESCJ0060_FCURQUOT_TXT%'
update BEST..TI17TRAPERMFIL set PATHPATTRN_LL ="${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURQUOT.dat"  where  PATHPATTRN_LL like '%_ESCJ0060_FCURQUOT[_]%' and PATHPATTRN_LL not like  '%_ESCJ0060_FCURQUOT_TXT%'
--select * from BEST..TI17TRAPERMFIL where  PATHPATTRN_LL like '%_ESCJ0060_FCURQUOT.dat' and PATHPATTRN_LL not like  '%ESCJ0060_FBOPRSLNK_TXT%'
 

--select * from BEST..TI17TRAPERMFIL where  PATHPATTRN_LL like '%_ESCJ0060_FCURQUOT_TXT[_]%'
update BEST..TI17TRAPERMFIL set PATHPATTRN_LL ="${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURQUOT_TXT.dat"  where  PATHPATTRN_LL like '%_ESCJ0060_FCURQUOT_TXT[_]%' 
--select * from BEST..TI17TRAPERMFIL where  PATHPATTRN_LL like '%_ESCJ0060_FCURQUOT_TXT.dat' 


--select * from BEST..TI17TRAPERMFIL where  PATHPATTRN_LL like '%_ESCJ0060_FDETTRS[_]%'  and PATHPATTRN_LL not like  '%_ESCJ0060_FDETTRS_TXT%'
update BEST..TI17TRAPERMFIL set PATHPATTRN_LL ="${DFILP}/${ENV_PREFIX}_ESCJ0060_FDETTRS.dat"  where  PATHPATTRN_LL like  '%_ESCJ0060_FDETTRS[_]%'  and PATHPATTRN_LL not like  '%_ESCJ0060_FDETTRS_TXT%'
--select * from BEST..TI17TRAPERMFIL where PATHPATTRN_LL like  '%_ESCJ0060_FDETTRS.dat'  and PATHPATTRN_LL not like  '%_ESCJ0060_FDETTRS_TXT%'

--select * from BEST..TI17TRAPERMFIL where  PATHPATTRN_LL like  '%_ESCJ0060_FDETTRS_TXT%'
update BEST..TI17TRAPERMFIL set PATHPATTRN_LL ="${DFILP}/${ENV_PREFIX}_ESCJ0060_FDETTRS_TXT.dat"  where  PATHPATTRN_LL like  '%_ESCJ0060_FDETTRS_TXT%'
--select * from BEST..TI17TRAPERMFIL where PATHPATTRN_LL like   '%_ESCJ0060_FDETTRS_TXT%'


--select * from BEST..TI17TRAPERMFIL where  PATHPATTRN_LL like '%_ESCJ0060_FLIBEL2[_]%' 
update BEST..TI17TRAPERMFIL set PATHPATTRN_LL ="${DFILP}/${ENV_PREFIX}_ESCJ0060_FLIBEL2.dat"  where  PATHPATTRN_LL like  '%_ESCJ0060_FLIBEL2[_]%' 
--select * from BEST..TI17TRAPERMFIL where PATHPATTRN_LL like  '%_ESCJ0060_FLIBEL2.dat' 


--select * from BEST..TI17TRAPERMFIL where  PATHPATTRN_LL like '%_ESCJ0060_FPRSMAP[_]%' and PATHPATTRN_LL not like  '%_ESCJ0060_FPRSMAP_TXT%'
update BEST..TI17TRAPERMFIL set PATHPATTRN_LL ="${DFILP}/${ENV_PREFIX}_ESCJ0060_FPRSMAP.dat"  where  PATHPATTRN_LL like  '%_ESCJ0060_FPRSMAP[_]%'  and PATHPATTRN_LL not like  '%_ESCJ0060_FPRSMAP_TXT%'
--select * from BEST..TI17TRAPERMFIL where PATHPATTRN_LL like  '%_ESCJ0060_FPRSMAP.dat' and PATHPATTRN_LL not like  '%_ESCJ0060_FPRSMAP_TXT%'

--select * from BEST..TI17TRAPERMFIL where  PATHPATTRN_LL like '%_ESCJ0060_FPRSMAP_TXT%' 
update BEST..TI17TRAPERMFIL set PATHPATTRN_LL ="${DFILP}/${ENV_PREFIX}_ESCJ0060_FPRSMAP_TXT.dat"  where  PATHPATTRN_LL like  '%_ESCJ0060_FPRSMAP_TXT%' 
--select * from BEST..TI17TRAPERMFIL where PATHPATTRN_LL like  '%_ESCJ0060_FPRSMAP_TXT.dat' 


--select * from BEST..TI17TRAPERMFIL where  PATHPATTRN_LL like '%_ESCJ0060_FSUBTRS[_]%' and PATHPATTRN_LL not like  '%_ESCJ0060_FSUBTRS_TXT%'
update BEST..TI17TRAPERMFIL set PATHPATTRN_LL ="${DFILP}/${ENV_PREFIX}_ESCJ0060_FSUBTRS.dat"  where  PATHPATTRN_LL like  '%_ESCJ0060_FSUBTRS[_]%'  and PATHPATTRN_LL not like  '%_ESCJ0060_FSUBTRS_TXT%'
--select * from BEST..TI17TRAPERMFIL where PATHPATTRN_LL like '%_ESCJ0060_FSUBTRS.dat'  

--select * from BEST..TI17TRAPERMFIL where  PATHPATTRN_LL like '%_ESCJ0060_FSUBTRS[_]TXT%' 
update BEST..TI17TRAPERMFIL set PATHPATTRN_LL ="${DFILP}/${ENV_PREFIX}_ESCJ0060_FSUBTRS_TXT.dat"  where  PATHPATTRN_LL like  '%_ESCJ0060_FSUBTRS_TXT%' 
--select * from BEST..TI17TRAPERMFIL where PATHPATTRN_LL like  '%_ESCJ0060_FSUBTRS_TXT.dat' 


--select * from BEST..TI17TRAPERMFIL where  PATHPATTRN_LL like '%_ESCJ0060_FTFAMCHG[_]%' 
update BEST..TI17TRAPERMFIL set PATHPATTRN_LL ="${DFILP}/${ENV_PREFIX}_ESCJ0060_FTFAMCHG.dat"  where  PATHPATTRN_LL like  '%_ESCJ0060_FTFAMCHG[_]%' 
--select * from BEST..TI17TRAPERMFIL where PATHPATTRN_LL like  '%_ESCJ0060_FTFAMCHG.dat' 


---select * from BEST..TI17TRAPERMFIL where  PATHPATTRN_LL like '%_ESCJ0060_FTRANSCODE[_]%' 
update BEST..TI17TRAPERMFIL set PATHPATTRN_LL ="${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRANSCODE.dat"  where  PATHPATTRN_LL like  '%_ESCJ0060_FTRANSCODE[_]%' 
--select * from BEST..TI17TRAPERMFIL where PATHPATTRN_LL like  '%_ESCJ0060_FTRANSCODE.dat' 

--select * from BEST..TI17TRAPERMFIL where  PATHPATTRN_LL like '%_ESCJ0060_FTRSLNK_TXT[_]%' 
update BEST..TI17TRAPERMFIL set PATHPATTRN_LL ="${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRSLNK_TXT.dat"  where  PATHPATTRN_LL like  '%_ESCJ0060_FTRSLNK_TXT[_]%' 
--select * from BEST..TI17TRAPERMFIL where PATHPATTRN_LL like  '%_ESCJ0060_FTRSLNK_TXT.dat' 

--select * from BEST..TI17TRAPERMFIL where  PATHPATTRN_LL like '%_ESCJ0060_FTRSLNK[_]%' and    PATHPATTRN_LL not like  '%_ESCJ0060_FTRSLNK_TXT%' 
update BEST..TI17TRAPERMFIL set PATHPATTRN_LL ="${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRSLNK.dat"  where  PATHPATTRN_LL like  '%_ESCJ0060_FTRSLNK[_]%'  and  PATHPATTRN_LL not like  '%_ESCJ0060_FTRSLNK_TXT%'
--select * from BEST..TI17TRAPERMFIL where PATHPATTRN_LL like  '%_ESCJ0060_FTRSLNK.dat' and PATHPATTRN_LL not like  '%_ESCJ0060_FTRSLNK_TXT%'

--select * from BEST..TI17TRAPERMFIL where  PATHPATTRN_LL like "%ES_D8830_FTECLEDA_I4I%"
--delete BEST..TI17TRAPERMFIL where  IDF_CT= 'I4I_ESPD8830' and PERMFIL_CT = 'EPO_FTECLEDASO_EBS'
--update BEST..TI17TRAPERMFIL set PATHPATTRN_LL ="${DFILP}/${ENV_PREFIX}_ES${PARM_FTECLED}D8700_FTECLEDA_I4I_${PARM_ICLODAT_D}.dat"  where  PATHPATTRN_LL like "%ES_D8830_FTECLEDA_I4I%"
--select * from BEST..TI17TRAPERMFIL where PATHPATTRN_LL like  '%ES%D8830_FTECLEDA%' 
--select * from BEST..TI17TRAPERMFIL where PATHPATTRN_LL like  '%ES${PARM_FTECLED}D8700_FTECLEDA_I4I%' 
--select * from BEST..TI17TRAPERMFIL where idf_ct ="I17G_IEX_ALL_STD" and PERMFIL_CT="EPO_FTECLEDA"  and  PATHPATTRN_LL like "%ES_D8830_FTECLEDA_I4I%"


--select * from BEST..TI17TRAPERMFIL  where IDF_CT ="ESID8700_I4_PC___" and PERMFIL_CT ="EST_FTECLEDA_EBS"
delete BEST..TI17TRAPERMFIL where IDF_CT ="ESID8700_I4_PC___" and PERMFIL_CT ="EST_FTECLEDA_EBS"
insert into BEST..TI17TRAPERMFIL values ('ESID8700_I4_PC___',  'EST_FTECLEDA_EBS',"${DFILP}/${ENV_PREFIX}_ESID8700_FTECLEDA_I4I_${PARM_ICLODAT_D}.dat",'O','')
--select * from BEST..TI17TRAPERMFIL  where IDF_CT ="ESID8700_I4_PC___" and PERMFIL_CT ="EST_FTECLEDA_EBS"

--select * from BEST..TI17TRAPERMFIL where IDF_CT ="ESID8700_I4_PC___" and PERMFIL_CT ="EST_OIADVPERICASE"
delete BEST..TI17TRAPERMFIL where IDF_CT ="ESID8700_I4_PC___" and PERMFIL_CT ="EST_OIADVPERICASE"
insert into BEST..TI17TRAPERMFIL values ('ESID8700_I4_PC___',  'EST_OIADVPERICASE',"${DFILP}/${ENV_PREFIX}_ESID0560_OIADVPERICASE_INV_${PARM_ICLODAT_D}.dat",'O','')
--select * from BEST..TI17TRAPERMFIL where IDF_CT ="ESID8700_I4_PC___" and PERMFIL_CT ="EST_OIADVPERICASE"
 
 
-- select * from BEST..TI17TRAPERMFIL where  IDF_CT ="ESPD8700" and PERMFIL_CT ="EPO_FTECLEDA" 
update BEST..TI17TRAPERMFIL set PATHPATTRN_LL ="${DFILP}/${ENV_PREFIX}_ESPD8700_FTECLEDA_I4I_${PARM_ICLODAT_D}.dat", IO="O" where  IDF_CT ="ESPD8700" and PERMFIL_CT ="EPO_FTECLEDA"
-- select * from BEST..TI17TRAPERMFIL  where  IDF_CT ="ESPD8700" and PERMFIL_CT ="EPO_FTECLEDA"
 
--select * from BEST..TI17FNC
 
/* 
select * from BEST..TI17TRAPERMFIL where IDF_CT = "ESID8700_I4_PC___" and PERMFIL_CT ="EST_FTECLEDA_EBS"
delete BEST..TI17TRAPERMFIL where IDF_CT = "ESID8700_I4_PC___" and PERMFIL_CT ="EST_FTECLEDA_EBS"
insert into BEST..TI17TRAPERMFIL values ('ESID8700_I4_PC___',  'EST_FTECLEDA_EBS',"${DFILP}/${ENV_PREFIX}_ES${PARM_FTECLED}D8700_FTECLEDA_I4I_${PARM_ICLODAT_D}.dat" ,'O','')
select * from BEST..TI17TRAPERMFIL where IDF_CT = "ESID8700_I4_PC___" and PERMFIL_CT ="EST_FTECLEDA_EBS"


select * from BEST..TI17TRAPERMFIL where IDF_CT = "ESID8700_I4_PC___" and PERMFIL_CT ="EPO_OIADVPERICASE"
delete BEST..TI17TRAPERMFIL where IDF_CT = "ESID8700_I4_PC___" and PERMFIL_CT ="EST_FTECLEDA_EBS"
insert into BEST..TI17TRAPERMFIL values ('ESID8700_I4_PC___',  'EST_FTECLEDA_EBS',"${DFILP}/${ENV_PREFIX}_ESID0560_OIADVPERICASE_INV_${PARM_ICLODAT_D}.dat" ,'O','')
select * from BEST..TI17TRAPERMFIL where IDF_CT = "ESID8700_I4_PC___" and PERMFIL_CT ="EST_FTECLEDA_EBS"

*/

--select * from BEST..TI17TRAPERMFIL where  PATHPATTRN_LL like "%ES[IP]D3800_FTECLEDR_I4I%${PARM_ICLODAT_D}%" 
update BEST..TI17TRAPERMFIL set PATHPATTRN_LL ="${DFILP}/${ENV_PREFIX}_ES${PARM_FTECLED}D3800_FTECLEDR_I4I_${PARM_ICLODAT_D}.dat"  where  PATHPATTRN_LL like  "%ES[IP]D3800_FTECLEDR_I4I%${PARM_ICLODAT_D}%"
--select * from BEST..TI17TRAPERMFIL where PATHPATTRN_LL like  "%ES%D3800_FTECLEDR_I4I%${PARM_ICLODAT_D}%" 


--select * from BEST..TI17TRAPERMFIL where  PATHPATTRN_LL like "%ES[IP]D3800_FTECLEDR_I4I%${PARM_PREV_ICLODAT_D}%" 
update BEST..TI17TRAPERMFIL set PATHPATTRN_LL ="${DFILP}/${ENV_PREFIX}_ES${PARM_FTECLED}D3800_FTECLEDR_I4I_${PARM_PREV_ICLODAT_D}.dat"  where  PATHPATTRN_LL like  "%ES[IP]D3800_FTECLEDR_I4I%${PARM_PREV_ICLODAT_D}%"
---select * from BEST..TI17TRAPERMFIL where PATHPATTRN_LL like  "%ES%D3800_FTECLEDR_I4I%${PARM_PREV_ICLODAT_D}%" 

--select * from BEST..TI17TRAPERMFIL  where  PATHPATTRN_LL like "%ESID2040_DLVGTAR%"  and IDF_CT ="ESID2560"
update BEST..TI17TRAPERMFIL set PATHPATTRN_LL ="`ls -rt ${DFILP}/${ENV_PREFIX}_ESID2040_DLVGTAR_PC_${PARM_ICL--ODAT_D}_*.dat | tail -1 `"   where  PATHPATTRN_LL like "%ESID2040_DLVGTAR%"  and IDF_CT ="ESID2560"
--select * from BEST..TI17TRAPERMFIL  where  PATHPATTRN_LL like "%ESID2040_DLVGTAR%"  and IDF_CT ="ESID2560"

go


-- correction ESID2050 EST_DLRGTAA
--select * from BEST..TI17TRAPERMFIL  where      IDF_CT = 'ESID2050' and PATHPATTRN_LL like  "%ESID2050_DLRGTAA%"
--update BEST..TI17TRAPERMFIL  
--set       PATHPATTRN_LL ="${DFILI}/${ENV_PREFIX}_ESID2050_DLRGTAA_${TYPEINV}_${PARM_ICLODAT_D}.dat"
--where        IDF_CT = 'ESID2050' and PATHPATTRN_LL like  "%ESID2050_DLRGTAA%" 

--select * from BEST..TI17TRAPERMFIL where IDF_CT in (select IDF_CT from BEST..TI17REQCHN where REQCOD_CT = "EBSEMINV" ) and PATHPATTRN_LL like "%ESPD3800_FTECLED%"
--select * from BEST..TI17TRAPERMFIL where IDF_CT in (select IDF_CT from BEST..TI17REQCHN where REQCOD_CT = "EBSEMINV" ) and PATHPATTRN_LL like "%ESPD8830_FTECLED%"
--select * from BEST..TI17TRAPERMFIL where IDF_CT in (select IDF_CT from BEST..TI17REQCHN where REQCOD_CT = "EBSEQPOS" ) and PATHPATTRN_LL like "%ESPD8830_FTECLED%"

--select * from BEST..TI17TRAPERMFIL where IDF_CT ="ESID2000" and PERMFIL_CT ="EST_DLDGTAA_IBNRIFRS"
--delete BEST..TI17TRAPERMFIL where IDF_CT ="ESID2000" and PERMFIL_CT ="EST_DLDGTAA_IBNRIFRS"
-- insert into BEST..TI17TRAPERMFIL values ('ESID2000',  'EST_DLDGTAA_IBNRIFRS','${DFILP}/${ENV_PREFIX}_ESID2000_DLDGTAA_IBNRIFRS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
 
--select * from BEST..TI17TRAPERMFIL where IDF_CT ="EBS_ESID2210" and PERMFIL_CT ="EST_DLDGTAA_IBNRIFRS"
--delete BEST..TI17TRAPERMFIL where IDF_CT ="EBS_ESID2210" and PERMFIL_CT ="EST_DLDGTAA_IBNRIFRS"
-- insert into BEST..TI17TRAPERMFIL values ('EBS_ESID2210',  'EST_DLDGTAA_IBNRIFRS','${DFILP}/${ENV_PREFIX}_ESID2000_DLDGTAA_IBNRIFRS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')

 --- correction ESID2560 
  
--select * from BEST..TI17TRAPERMFIL  where  PATHPATTRN_LL like "%ESID2040_DLVGTAR%"  and IDF_CT ="ESID2560"
--update BEST..TI17TRAPERMFIL set PATHPATTRN_LL ="`ls -rt ${DFILP}/${ENV_PREFIX}_ESID2040_DLVGTAR_PC_${PARM_ICLODAT_D}_*.dat | tail -1 `"   where  PATHPATTRN_LL like "%ESID2040_DLVGTAR%"  and IDF_CT ="ESID2560"
--select * from BEST..TI17TRAPERMFIL  where  PATHPATTRN_LL like "%ESID2040_DLVGTAR%"  and IDF_CT ="ESID2560"

--- Correction ESID0070 à retirer 
--select * from BEST..TI17TRAPERMFIL  where  IDF_CT ="ESID0070" and PERMFIL_CT ="EST_FTPNA17"--
--delete BEST..TI17TRAPERMFIL where IDF_CT ="ESID0070" and PERMFIL_CT ="EST_FTPNA17"-----
--insert into BEST..TI17TRAPERMFIL values ('ESID0070',  'EST_FTPNA17','${DFILP}/${ENV_PREFIX}_ESID2000_FTPNA17_INV_${PARM_ICLODAT_D}.dat','I','')



go
