-------------------------------
--mapping of  ESPD8100

	----------   Clean tables   ---------------------

	delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESPD8100')
	delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESPD8100')
	delete BEST..TI17FNC where CHAIN_CT='ESPD8100'
	delete BEST..TI17CHN  where CHAIN_CT='ESPD8100'

	insert into BEST..TI17CHN values ('ESPD8100',  '')

	----------IDF_CT:   EBS_ESPD8100 ------------------

		insert into BEST..TI17FNC values ('EBS_ESPD8100',' ','ESPD8100',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('EBS_ESPD8100',  'EPO_FTECLEDACO_ANNULMVT','${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_ANNULMVT_EBS_POC.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8100',  'EPO_FTECLEDRCO_ANNULMVT','${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_ANNULMVT_EBS_POC.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8100',  'EST_FTECLEDR','${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8100',  'EST_FTECLEDSII','${DFILP}/${ENV_PREFIX}_ESPD3700_FTECLED_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8100',  'EPO_FULTIMATESSII','${DFILP}/${ENV_PREFIX}_ESPD0060_FULTIMATES_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8100',  'EST_FTECLEDA','${DFILP}/${ENV_PREFIX}_ESPD3970_EBS_MVT_MRG_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8100',  'EST_GTSII_RISKMARGIN','${DFILP}/${ENV_PREFIX}_ESPD3700_GTSII_RISKMARGIN_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8100',  'EST_CLS','${ENV_PREFIX}_ESPD8100_CLSTYPE_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8100',  'EST_FILE_LIST','${ENV_PREFIX}_ESPD8100_FILE_LIST_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8100',  'EST_FULTIMATESRA','${ENV_PREFIX}_ESPD8100_BSAR_FTULTIMATESFULL_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8100',  'EST_FTECLEDARA','${ENV_PREFIX}_ESPD8100_BSAR_FTECLEDASII${TYPEINV0}_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8100',  'EST_FTECLEDRRA','${ENV_PREFIX}_ESPD8100_BSAR_FTECLEDRSII${TYPEINV0}_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8100',  'EST_FTECLEDSIIRA','${ENV_PREFIX}_ESPD8100_BSAR_FTECLEDSII${TYPEINV0}_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8100',  'EST_FTECLEDAYTD','${ENV_PREFIX}_ESPD8100_BSAR_FTECLEDASII${TYPEINV0}_YTD_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8100',  'EST_FTECLEDRYTD','${ENV_PREFIX}_ESPD8100_BSAR_FTECLEDRSII${TYPEINV0}_YTD_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8100',  'EST_GTSII_RISKMARGINRA','${ENV_PREFIX}_ESPD8100_BSAR_GTSII_RISKMARGIN${TYPEINV0}_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')


		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('EBSEYPOS',  'EBS_ESPD8100','')
			insert into BEST..TI17REQFNC values ('EBSEQINV',  'EBS_ESPD8100','')
			insert into BEST..TI17REQFNC values ('EBSEYINV',  'EBS_ESPD8100','')
			insert into BEST..TI17REQFNC values ('EBSEMINV',  'EBS_ESPD8100','')
			insert into BEST..TI17REQFNC values ('EBSEQPOC',  'EBS_ESPD8100','')
			insert into BEST..TI17REQFNC values ('EBSEQPOS',  'EBS_ESPD8100','')
			insert into BEST..TI17REQFNC values ('EBSEYPOC',  'EBS_ESPD8100','')
			insert into BEST..TI17REQFNC values ('EBSEQPOCB',  'EBS_ESPD8100','')
			insert into BEST..TI17REQFNC values ('EBSEYPOCB',  'EBS_ESPD8100','')

	----------IDF_CT:   I4I_ESPD8100 ------------------

		insert into BEST..TI17FNC values ('I4I_ESPD8100',' ','ESPD8100',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I4I_ESPD8100',  'EPO_FTECLEDACO_ANNULMVT','${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_ANNULMVT_I4I_POC.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD8100',  'EPO_FTECLEDRCO_ANNULMVT','${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_ANNULMVT_I4I_POC.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD8100',  'EST_FTECLEDA','`if [ "${TYPEINV}" = "POC" ];then echo ${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat;else echo $DFILP/${ENV_PREFIX}_ESPD8700_FTECLEDA_I4I_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat;fi;`','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD8100',  'EST_FTECLEDR','`if [ "${TYPEINV}" = "POC" ];then echo ${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_I4I_POC_${PARM_ICLODAT_D}.dat;else echo $DFILP/${ENV_PREFIX}_ESPD8700_FTECLEDR_I4I_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat;fi;`','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD8100',  'EST_CLS','${ENV_PREFIX}_ESPD8100_CLSTYPE_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD8100',  'EST_FILE_LIST','${ENV_PREFIX}_ESPD8100_FILE_LIST_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD8100',  'EST_FTECLEDARA','${ENV_PREFIX}_ESPD8100_BSAR_FTECLEDA${TYPEINV0}_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD8100',  'EST_FTECLEDRRA','${ENV_PREFIX}_ESPD8100_BSAR_FTECLEDR${TYPEINV0}_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD8100',  'EST_FTECLEDSIIRA','${ENV_PREFIX}_ESPD8100_BSAR_FTECLEDSII${TYPEINV0}_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD8100',  'EST_FTECLEDAYTD','${ENV_PREFIX}_ESPD8100_BSAR_FTECLEDA${TYPEINV0}_YTD_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD8100',  'EST_FTECLEDRYTD','${ENV_PREFIX}_ESPD8100_BSAR_FTECLEDR${TYPEINV0}_YTD_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')


		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I4IQPOC',  'I4I_ESPD8100','')
			insert into BEST..TI17REQFNC values ('I4IQPOCB',  'I4I_ESPD8100','')
			insert into BEST..TI17REQFNC values ('I4IQPOSB',  'I4I_ESPD8100','')
			insert into BEST..TI17REQFNC values ('I4IYPOC',  'I4I_ESPD8100','')
			insert into BEST..TI17REQFNC values ('I4IYPOCB',  'I4I_ESPD8100','')
			insert into BEST..TI17REQFNC values ('I4IYPOS',  'I4I_ESPD8100','')
			insert into BEST..TI17REQFNC values ('I4IYPOSB',  'I4I_ESPD8100','')
			insert into BEST..TI17REQFNC values ('I4IQPOS',  'I4I_ESPD8100','')
			insert into BEST..TI17REQFNC values ('I4IYPOSP',  'I4I_ESPD8100','')
			insert into BEST..TI17REQFNC values ('I4IQPOSP',  'I4I_ESPD8100','')
go

