-------------------------------
--mapping of  ESFD3720

	----------   Clean tables   ---------------------

	delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD3720')
	delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD3720')
	delete BEST..TI17FNC where CHAIN_CT='ESFD3720'
	delete BEST..TI17CHN  where CHAIN_CT='ESFD3720'

	insert into BEST..TI17CHN values ('ESFD3720',  'IFRS17 - UOA definition at inception')

	----------IDF_CT:   I17G_CSM_CRE_INI ------------------

		insert into BEST..TI17FNC values ('I17G_CSM_CRE_INI','IFRS17 - Group - UOA definition at inception','ESFD3720',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17G_CSM_CRE_INI',  'EPO_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_CSM_CRE_INI',  'ESF_FUOASII','${DFILP}/${ENV_PREFIX}_ESFD0060_I17G___TUOASII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_CSM_CRE_INI',  'ESF_FSSDACTR','${DFILP}/${ENV_PREFIX}_ESFD5010_FSSDACTR_TXT_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_CSM_CRE_INI',  'ESF_GTSII_CSM','${DFILP}/${ENV_PREFIX}_ESFD3710_I17G_CSM_CSU_INI_GTSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_CSM_CRE_INI',  'ESF_FRERETFACCTR_INI','${DFILP}/${ENV_PREFIX}_ESFD1130_TRERETFACCTR_I17G_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_CSM_CRE_INI',  'ESF_IADPERICASE_INI','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17G_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_CSM_CRE_INI',  'ESF_GTSII_GLOBAL_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESFD3630_I17G_IEX_ALL_INI_GTSII_GLOBAL_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_CSM_CRE_INI',  'ESF_REGION_FSECIFRS_INTER_SITE','${DFILP}/${ENV_PREFIX}_ESFD3720_I17G_CSM_CRE_INI_REGION_FSECIFRS_INTER_SITE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_CSM_CRE_INI',  'ESF_FRETIFRS','${DFILP}/${ENV_PREFIX}_ESFD3720_I17G_CSM_CRE_INI_FRETIFRS${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_CSM_CRE_INI',  'ESF_FSECIFRS','${DFILP}/${ENV_PREFIX}_ESFD3720_I17G_CSM_CRE_INI_FSECIFRS${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_CSM_CRE_INI',  'ESF_FSEGPROF','${DFILP}/${ENV_PREFIX}_ESFD3720_I17G_CSM_CRE_INI_FSEGPROF_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_CSM_CRE_INI',  'ESF_FSECIFRS_LIGHT','${DFILP}/${ENV_PREFIX}_ESFD3720_I17G_CSM_CRE_INI_FSECIFRS_LIGHT${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_CSM_CRE_INI',  'ESF_FSECIFRS_INTER_SITE','${DFILP}/${ENV_PREFIX}_ESFD3720_I17G_CSM_CRE_INI_FSECIFRS_INTER_SITE_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_CSM_CRE_INI',  'ESF_FSECIFRS_INTER_SITE_SSD','${DFILP}/${ENV_PREFIX}_ESFD3720_I17G_CSM_CRE_INI_FSECIFRS_INTER_SITE_SSD_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17GMINV',  'I17G_CSM_CRE_INI','')
			insert into BEST..TI17REQFNC values ('I17GQINV',  'I17G_CSM_CRE_INI','')
			insert into BEST..TI17REQFNC values ('I17GQPOS',  'I17G_CSM_CRE_INI','')
			insert into BEST..TI17REQFNC values ('I17GYINV',  'I17G_CSM_CRE_INI','')
			insert into BEST..TI17REQFNC values ('I17GYPOS',  'I17G_CSM_CRE_INI','')

	----------IDF_CT:   I17L_CSM_CRE_INI ------------------

		insert into BEST..TI17FNC values ('I17L_CSM_CRE_INI','IFRS17 - Local - UOA definition at inception','ESFD3720',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17L_CSM_CRE_INI',  'EPO_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_CSM_CRE_INI',  'ESF_FUOASII','${DFILP}/${ENV_PREFIX}_ESFD0060_I17L___TUOASII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_CSM_CRE_INI',  'ESF_FSSDACTR','${DFILP}/${ENV_PREFIX}_ESFD5010_FSSDACTR_TXT_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_CSM_CRE_INI',  'ESF_GTSII_CSM','${DFILP}/${ENV_PREFIX}_ESFD3710_I17L_CSM_CSU_INI_GTSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_CSM_CRE_INI',  'ESF_FRERETFACCTR_INI','${DFILP}/${ENV_PREFIX}_ESFD1130_TRERETFACCTR_I17L_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_CSM_CRE_INI',  'ESF_IADPERICASE_INI','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17L_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_CSM_CRE_INI',  'ESF_GTSII_GLOBAL_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESFD3630_I17L_IEX_ALL_INI_GTSII_GLOBAL_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_CSM_CRE_INI',  'ESF_REGION_FSECIFRS_INTER_SITE','${DFILP}/${ENV_PREFIX}_ESFD3720_I17L_CSM_CRE_INI_REGION_FSECIFRS_INTER_SITE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_CSM_CRE_INI',  'ESF_FRETIFRS','${DFILP}/${ENV_PREFIX}_ESFD3720_I17L_CSM_CRE_INI_FRETIFRS${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_CSM_CRE_INI',  'ESF_FSECIFRS','${DFILP}/${ENV_PREFIX}_ESFD3720_I17L_CSM_CRE_INI_FSECIFRS${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_CSM_CRE_INI',  'ESF_FSEGPROF','${DFILP}/${ENV_PREFIX}_ESFD3720_I17L_CSM_CRE_INI_FSEGPROF_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_CSM_CRE_INI',  'ESF_FSECIFRS_LIGHT','${DFILP}/${ENV_PREFIX}_ESFD3720_I17L_CSM_CRE_INI_FSECIFRS_LIGHT${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_CSM_CRE_INI',  'ESF_FSECIFRS_INTER_SITE','${DFILP}/${ENV_PREFIX}_ESFD3720_I17L_CSM_CRE_INI_FSECIFRS_INTER_SITE_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_CSM_CRE_INI',  'ESF_FSECIFRS_INTER_SITE_SSD','${DFILP}/${ENV_PREFIX}_ESFD3720_I17L_CSM_CRE_INI_FSECIFRS_INTER_SITE_SSD_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17LMINV',  'I17L_CSM_CRE_INI','')
			insert into BEST..TI17REQFNC values ('I17LQINV',  'I17L_CSM_CRE_INI','')
			insert into BEST..TI17REQFNC values ('I17LQPOS',  'I17L_CSM_CRE_INI','')
			insert into BEST..TI17REQFNC values ('I17LYINV',  'I17L_CSM_CRE_INI','')
			insert into BEST..TI17REQFNC values ('I17LYPOS',  'I17L_CSM_CRE_INI','')

	----------IDF_CT:   I17P_CSM_CRE_INI ------------------

		insert into BEST..TI17FNC values ('I17P_CSM_CRE_INI','IFRS17 - Parent - UOA definition at inception','ESFD3720',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17P_CSM_CRE_INI',  'EPO_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_CSM_CRE_INI',  'ESF_FUOASII','${DFILP}/${ENV_PREFIX}_ESFD0060_I17P___TUOASII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_CSM_CRE_INI',  'ESF_FSSDACTR','${DFILP}/${ENV_PREFIX}_ESFD5010_FSSDACTR_TXT_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_CSM_CRE_INI',  'ESF_GTSII_CSM','${DFILP}/${ENV_PREFIX}_ESFD3710_I17P_CSM_CSU_INI_GTSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_CSM_CRE_INI',  'ESF_FRERETFACCTR_INI','${DFILP}/${ENV_PREFIX}_ESFD1130_TRERETFACCTR_I17P_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_CSM_CRE_INI',  'ESF_IADPERICASE_INI','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17P_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_CSM_CRE_INI',  'ESF_GTSII_GLOBAL_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESFD3630_I17P_IEX_ALL_INI_GTSII_GLOBAL_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_CSM_CRE_INI',  'ESF_REGION_FSECIFRS_INTER_SITE','${DFILP}/${ENV_PREFIX}_ESFD3720_I17P_CSM_CRE_INI_REGION_FSECIFRS_INTER_SITE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_CSM_CRE_INI',  'ESF_FRETIFRS','${DFILP}/${ENV_PREFIX}_ESFD3720_I17P_CSM_CRE_INI_FRETIFRS${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_CSM_CRE_INI',  'ESF_FSECIFRS','${DFILP}/${ENV_PREFIX}_ESFD3720_I17P_CSM_CRE_INI_FSECIFRS${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_CSM_CRE_INI',  'ESF_FSEGPROF','${DFILP}/${ENV_PREFIX}_ESFD3720_I17P_CSM_CRE_INI_FSEGPROF_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_CSM_CRE_INI',  'ESF_FSECIFRS_LIGHT','${DFILP}/${ENV_PREFIX}_ESFD3720_I17P_CSM_CRE_INI_FSECIFRS_LIGHT${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_CSM_CRE_INI',  'ESF_FSECIFRS_INTER_SITE','${DFILP}/${ENV_PREFIX}_ESFD3720_I17P_CSM_CRE_INI_FSECIFRS_INTER_SITE_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_CSM_CRE_INI',  'ESF_FSECIFRS_INTER_SITE_SSD','${DFILP}/${ENV_PREFIX}_ESFD3720_I17P_CSM_CRE_INI_FSECIFRS_INTER_SITE_SSD_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17PMINV',  'I17P_CSM_CRE_INI','')
			insert into BEST..TI17REQFNC values ('I17PQINV',  'I17P_CSM_CRE_INI','')
			insert into BEST..TI17REQFNC values ('I17PQPOS',  'I17P_CSM_CRE_INI','')
			insert into BEST..TI17REQFNC values ('I17PYINV',  'I17P_CSM_CRE_INI','')
			insert into BEST..TI17REQFNC values ('I17PYPOS',  'I17P_CSM_CRE_INI','')

	----------IDF_CT:   I17S_CSM_CRE_INI ------------------

		insert into BEST..TI17FNC values ('I17S_CSM_CRE_INI','IFRS17 - Simulation - UOA definition at inception','ESFD3720',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17S_CSM_CRE_INI',  'EPO_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_CSM_CRE_INI',  'ESF_FUOASII','${DFILP}/${ENV_PREFIX}_ESFD0060_I17S___TUOASII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_CSM_CRE_INI',  'ESF_FSSDACTR','${DFILP}/${ENV_PREFIX}_ESFD5010_FSSDACTR_TXT_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_CSM_CRE_INI',  'ESF_GTSII_CSM','${DFILP}/${ENV_PREFIX}_ESFD3710_I17S_CSM_CSU_INI_GTSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_CSM_CRE_INI',  'ESF_FRERETFACCTR_INI','${DFILP}/${ENV_PREFIX}_ESFD1130_TRERETFACCTR_I17S_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_CSM_CRE_INI',  'ESF_IADPERICASE_INI','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17S_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_CSM_CRE_INI',  'ESF_GTSII_GLOBAL_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESFD3630_I17S_IEX_ALL_INI_GTSII_GLOBAL_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_CSM_CRE_INI',  'ESF_REGION_FSECIFRS_INTER_SITE','${DFILP}/${ENV_PREFIX}_ESFD3720_I17S_CSM_CRE_INI_REGION_FSECIFRS_INTER_SITE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_CSM_CRE_INI',  'ESF_FRETIFRS','${DFILP}/${ENV_PREFIX}_ESFD3720_I17S_CSM_CRE_INI_FRETIFRS${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_CSM_CRE_INI',  'ESF_FSECIFRS','${DFILP}/${ENV_PREFIX}_ESFD3720_I17S_CSM_CRE_INI_FSECIFRS${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_CSM_CRE_INI',  'ESF_FSEGPROF','${DFILP}/${ENV_PREFIX}_ESFD3720_I17S_CSM_CRE_INI_FSEGPROF_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_CSM_CRE_INI',  'ESF_FSECIFRS_LIGHT','${DFILP}/${ENV_PREFIX}_ESFD3720_I17S_CSM_CRE_INI_FSECIFRS_LIGHT${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_CSM_CRE_INI',  'ESF_FSECIFRS_INTER_SITE','${DFILP}/${ENV_PREFIX}_ESFD3720_I17S_CSM_CRE_INI_FSECIFRS_INTER_SITE_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_CSM_CRE_INI',  'ESF_FSECIFRS_INTER_SITE_SSD','${DFILP}/${ENV_PREFIX}_ESFD3720_I17S_CSM_CRE_INI_FSECIFRS_INTER_SITE_SSD_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17SMINV',  'I17S_CSM_CRE_INI','')
			insert into BEST..TI17REQFNC values ('I17SQINV',  'I17S_CSM_CRE_INI','')
			insert into BEST..TI17REQFNC values ('I17SQPOS',  'I17S_CSM_CRE_INI','')
			insert into BEST..TI17REQFNC values ('I17SYINV',  'I17S_CSM_CRE_INI','')
			insert into BEST..TI17REQFNC values ('I17SYPOS',  'I17S_CSM_CRE_INI','')
go

