-------------------------------
--mapping of  ESPD8200

	----------   Clean tables   ---------------------

	delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESPD8200')
	delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESPD8200')
	delete BEST..TI17FNC where CHAIN_CT='ESPD8200'
	delete BEST..TI17CHN  where CHAIN_CT='ESPD8200'

	insert into BEST..TI17CHN values ('ESPD8200',  '')

	----------IDF_CT:   EBS_ESPD8200 ------------------

		insert into BEST..TI17FNC values ('EBS_ESPD8200',' ','ESPD8200',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('EBS_ESPD8200',  'EPO_FTECLEDACO_ANNULMVT','${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_ANNULMVT_EBS_POC.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8200',  'EPO_FTECLEDRCO_ANNULMVT','${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_ANNULMVT_EBS_POC.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8200',  'EST_FTECLEDSII','${DFILP}/${ENV_PREFIX}_ESPD3700_FTECLED_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8200',  'EPO_FULTIMATESSII','${DFILP}/${ENV_PREFIX}_ESPD0060_FULTIMATES_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8200',  'EST_FTECLEDA','${DFILP}/${ENV_PREFIX}_ESPD3970_EBS_MVT_MRG_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8200',  'EST_FTECLEDR','$DFILP/${ENV_PREFIX}_ESPD3970_FTECLEDR_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8200',  'EST_GTSII_RISKMARGIN','${DFILP}/${ENV_PREFIX}_ESPD3700_GTSII_RISKMARGIN_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8200',  'EST_CLS','${ENV_PREFIX}_ESPD8200_CLSTYPE_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8200',  'EST_FILE_LIST','${ENV_PREFIX}_ESPD8200_FILE_LIST_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8200',  'EST_FULTIMATESRA','${ENV_PREFIX}_ESPD8200_BSAR_FTULTIMATESFULL_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8200',  'EST_FTECLEDARA','${ENV_PREFIX}_ESPD8200_BSAR_FTECLEDASII${TYPEINV0}_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8200',  'EST_FTECLEDRRA','${ENV_PREFIX}_ESPD8200_BSAR_FTECLEDRSII${TYPEINV0}_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8200',  'EST_FTECLEDSIIRA','${ENV_PREFIX}_ESPD8200_BSAR_FTECLEDSII${TYPEINV0}_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8200',  'EST_FTECLEDAYTD','${ENV_PREFIX}_ESPD8200_BSAR_FTECLEDASII${TYPEINV0}_YTD_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8200',  'EST_FTECLEDRYTD','${ENV_PREFIX}_ESPD8200_BSAR_FTECLEDRSII${TYPEINV0}_YTD_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8200',  'EST_GTSII_RISKMARGINRA','${ENV_PREFIX}_ESPD8200_BSAR_GTSII_RISKMARGIN${TYPEINV0}_${CLODATMAX_YEA}_${CLODATMAX_QTR}Q_${HOST_PRDSIT}.dat','O','')

			--- output files by site
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8200',  'ESF_FTECLEDSII_TOAS',    '${ENV_PREFIX}_ESPD3700_FTECLEDSII_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOAS}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8200',  'ESF_FTECLEDSII_TOEU',    '${ENV_PREFIX}_ESPD3700_FTECLEDSII_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOEU}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8200',  'ESF_FTECLEDSII_TOAM',    '${ENV_PREFIX}_ESPD3700_FTECLEDSII_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOAM}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8200',  'ESF_FTECLEDSII_LOCAL',    '$DFILP/${ENV_PREFIX}_ESPD3700_FTECLEDSII_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','O','')

			--- input files by site
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8200',  'ESF_FTECLEDSII_FROMAS',    '${DFILP}/${ENV_PREFIX}_ESPD3700_FTECLEDSII_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_ASTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8200',  'ESF_FTECLEDSII_FROMEU',    '${DFILP}/${ENV_PREFIX}_ESPD3700_FTECLEDSII_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_EUTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8200',  'ESF_FTECLEDSII_FROMAM',    '${DFILP}/${ENV_PREFIX}_ESPD3700_FTECLEDSII_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_AMTOLOCAL}.dat','I','')

			--- output files by site
 			insert into BEST..TI17PERMFIL values ('EBS_ESPD8200',  'ESF_SII_RISKMARGIN_TOAS',    '${ENV_PREFIX}_ESPD3700_SII_RISKMARGIN_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOAS}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8200',  'ESF_SII_RISKMARGIN_TOEU',    '${ENV_PREFIX}_ESPD3700_SII_RISKMARGIN_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOEU}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8200',  'ESF_SII_RISKMARGIN_TOAM',    '${ENV_PREFIX}_ESPD3700_SII_RISKMARGIN_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALTOAM}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8200',  'ESF_SII_RISKMARGIN_LOCAL',    '$DFILP/${ENV_PREFIX}_ESPD3700_SII_RISKMARGIN_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','O','')
			
			--- input files by site
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8200',  'ESF_SII_RISKMARGIN_FROMAS',    '${DFILP}/${ENV_PREFIX}_ESPD3700_SII_RISKMARGIN_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_ASTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8200',  'ESF_SII_RISKMARGIN_FROMEU',    '${DFILP}/${ENV_PREFIX}_ESPD3700_SII_RISKMARGIN_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_EUTOLOCAL}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8200',  'ESF_SII_RISKMARGIN_FROMAM',    '${DFILP}/${ENV_PREFIX}_ESPD3700_SII_RISKMARGIN_${NORME_CF}_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_AMTOLOCAL}.dat','I','')


		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('EBSEMINV',  'EBS_ESPD8200','')
			insert into BEST..TI17REQFNC values ('EBSEQPOC',  'EBS_ESPD8200','')
			insert into BEST..TI17REQFNC values ('EBSEQPOS',  'EBS_ESPD8200','')
			insert into BEST..TI17REQFNC values ('EBSEYPOC',  'EBS_ESPD8200','')
			insert into BEST..TI17REQFNC values ('EBSEYPOS',  'EBS_ESPD8200','')
			insert into BEST..TI17REQFNC values ('EBSEQINV',  'EBS_ESPD8200','')
			insert into BEST..TI17REQFNC values ('EBSEYINV',  'EBS_ESPD8200','')
			insert into BEST..TI17REQFNC values ('EBSEQINVB',  'EBS_ESPD8200','')
			insert into BEST..TI17REQFNC values ('EBSEYINVB',  'EBS_ESPD8200','')
			insert into BEST..TI17REQFNC values ('EBSEQPOSB',  'EBS_ESPD8200','')
			insert into BEST..TI17REQFNC values ('EBSEYPOSB',  'EBS_ESPD8200','')
			insert into BEST..TI17REQFNC values ('EBSEQPOCB',  'EBS_ESPD8200','')
			insert into BEST..TI17REQFNC values ('EBSEYPOCB',  'EBS_ESPD8200','')
			insert into BEST..TI17REQFNC values ('S',  'EBS_ESPD8200','')
			insert into BEST..TI17REQFNC values ('EBSEQPOSP',  'EBS_ESPD8200','')
			insert into BEST..TI17REQFNC values ('EBSEYPOSP',  'EBS_ESPD8200','')
go

