

-------------------------------
--mapping of  ESFDMRG0

	----------   Clean tables   ---------------------

	delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFDMRG0')
	delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFDMRG0')
	delete BEST..TI17FNC where CHAIN_CT='ESFDMRG0'
	delete BEST..TI17CHN  where CHAIN_CT='ESFDMRG0'

	insert into BEST..TI17CHN values ('ESFDMRG0',  '')

	----------IDF_CT:   I17P_EXTENDED ------------------

		insert into BEST..TI17FNC values ('I17P_EXTENDED',' ','ESFDMRG0',0)
					

		----------  Perms--------------------- 

		--- envoie RA SAP
		insert into BEST..TI17PERMFIL values ('I17P_EXTENDED','ESX_CSM_LC_FTECLEDA','${DFILP}/${ENV_PREFIX}_ESFD3780_I17P_CSM_ACC_STD_CSM_LC_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat' , 'U','')
		insert into BEST..TI17PERMFIL values ('I17P_EXTENDED','ESX_FTECLEDSII','${DFILP}/${ENV_PREFIX}_ESFD3730_I17P_SII_ALL_STD_FTECLEDSII_${TYPEINV}_${PARM_ICLODAT_D}.dat' , 'U','')
		insert into BEST..TI17PERMFIL values ('I17P_EXTENDED','ESX_FTECLEDA_GLT','${DFILP}/${ENV_PREFIX}_ESFD3870_I17P_GLT_ALL_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat' , 'U','')
		insert into BEST..TI17PERMFIL values ('I17P_EXTENDED','ESX_FTECLEDA_MVT', '${DFILP}/${ENV_PREFIX}_ESFD3840_I17P_GLT_MRG_STD_FTECLEDA_MVT_${TYPEINV}_${PARM_ICLODAT_D}.dat' , 'U','')
		insert into BEST..TI17PERMFIL values ('I17P_EXTENDED','ESX_FTECLEDR_MVT','${DFILP}/${ENV_PREFIX}_ESFD3840_I17P_GLT_MRG_STD_FTECLEDR_MVT_${TYPEINV}_${PARM_ICLODAT_D}.dat' , 'U','')
		--insert into BEST..TI17PERMFIL values ('I17P_EXTENDED','ESX_FCSM_LC_ENDING_ASS', '${DFILP}/${ENV_PREFIX}_ESFD3870_I17P_GLT_ALL_STD_FCSM_LC_ENDING_ASS_${TYPEINV}_${PARM_ICLODAT_D}.dat' , 'U','')
		--insert into BEST..TI17PERMFIL values ('I17P_EXTENDED','ESX_FCSM_ENDING_RNP', '${DFILP}/${ENV_PREFIX}_ESFD3870_I17P_GLT_ALL_STD_FCSM_ENDING_RNP_${TYPEINV}_${PARM_ICLODAT_D}.dat' , 'U','')
		insert into BEST..TI17PERMFIL values ('I17P_EXTENDED','ESX_FTECLEDR', '${DFILP}/${ENV_PREFIX}_ESFD3870_I17P_GLT_ALL_STD_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat' , 'U','')
		insert into BEST..TI17PERMFIL values ('I17P_EXTENDED','ESF_FI17CLOPER','${DFILP}/${ENV_PREFIX}_ESFD1130_FI17CLOPER_I17P_DSC_ALL_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat' , 'U','')
	

		-- Q+1
		insert into BEST..TI17PERMFIL values ('I17P_EXTENDED','ESX_FSEGPATTERNDSCf17'		,'${DFILP}/${ENV_PREFIX}_ESFD1130_FSEGPATTERNDSCf17_I17P_${TYPEINV}_${PARM_ICLODAT_D}.dat' , 'U','')
		insert into BEST..TI17PERMFIL values ('I17P_EXTENDED','ESX_GTSII_ESCOMPTE_DSC'		,'${DFILP}/${ENV_PREFIX}_ESFD3620_I17P_DSC_LKI_STD_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}.dat' , 'U','')
		insert into BEST..TI17PERMFIL values ('I17P_EXTENDED','ESX_GTSII_ESCOMPTE_RAD'		,'${DFILP}/${ENV_PREFIX}_ESFD3620_I17P_RAD_LKI_STD_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}.dat' , 'U','')
		insert into BEST..TI17PERMFIL values ('I17P_EXTENDED','ESX_GTSII_GLOBAL_CASHFLOW'	,'${DFILP}/${ENV_PREFIX}_ESFD3630_I17P_IEX_ALL_STD_GTSII_GLOBAL_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat' , 'U','')
		insert into BEST..TI17PERMFIL values ('I17P_EXTENDED','ESX_GTSII_DAC_LKI'			,'${DFILP}/${ENV_PREFIX}_ESFD3640_I17P_IVR_CHR_STD_DAC_LKI_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat' , 'U','')
		-- insert into BEST..TI17PERMFIL values ('I17P_EXTENDED','ESX_GTSII_CASHFLOW'			,'${DFILP}/${ENV_PREFIX}_ESFD3650_I17P_RAD_CKI_STD_GTSII_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat' , 'U','')
		insert into BEST..TI17PERMFIL values ('I17P_EXTENDED','ESX_GTSII_CSM_CASHFLOW'		,'${DFILP}/${ENV_PREFIX}_ESFD3760_I17P_UOA_PRO_STD_GTSII_CSM_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat' , 'U','')
		insert into BEST..TI17PERMFIL values ('I17P_EXTENDED','ESX_GTSII_CASHFLOW_RAD_CUR'	,'${DFILP}/${ENV_PREFIX}_ESFD3650_I17P_RAD_CUR_STD_GTSII_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat', 'U','')
		insert into BEST..TI17PERMFIL values ('I17P_EXTENDED','ESX_GTSII_ESCOMPTE_RAD_DSI'	,'${DFILP}/${ENV_PREFIX}_ESFD3620_I17P_RAD_DSI_STD_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}.dat', 'U','')
			
			----------   Reqs    ---------------------                                          
			
																						
		insert into BEST..TI17REQFNC values ('I17PQPOSX',  'I17P_EXTENDED','')          
		insert into BEST..TI17REQFNC values ('I17PYPOSX',  'I17P_EXTENDED','')          
		insert into BEST..TI17REQFNC values ('I17PQPOS',  'I17P_EXTENDED','')          
		insert into BEST..TI17REQFNC values ('I17PYPOS',  'I17P_EXTENDED','')          
																							
	----------IDF_CT:   I17L_EXTENDED -----------------                                    
																							
		insert into BEST..TI17FNC values ('I17L_EXTENDED',' ','ESFDMRG0',0)                 
																							
																							
		----------  Perms---------------------                                             
			
		
		--- envoie RA SAP
		insert into BEST..TI17PERMFIL values ('I17L_EXTENDED','ESX_CSM_LC_FTECLEDA','${DFILP}/${ENV_PREFIX}_ESFD3780_I17L_CSM_ACC_STD_CSM_LC_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat' , 'U','')
		insert into BEST..TI17PERMFIL values ('I17L_EXTENDED','ESX_FTECLEDSII','${DFILP}/${ENV_PREFIX}_ESFD3730_I17L_SII_ALL_STD_FTECLEDSII_${TYPEINV}_${PARM_ICLODAT_D}.dat' , 'U','')
		insert into BEST..TI17PERMFIL values ('I17L_EXTENDED','ESX_PAA_ASSUM','${DFILP}/${ENV_PREFIX}_ESFD4010_I17L_PAA_ALL_STD_PAA_ASSUM_${TYPEINV}_${PARM_ICLODAT_D}.dat' , 'U','')
		insert into BEST..TI17PERMFIL values ('I17L_EXTENDED','ESX_FTECLEDA_MVT', '${DFILP}/${ENV_PREFIX}_ESFD3840_I17L_GLT_MRG_STD_FTECLEDA_MVT_${TYPEINV}_${PARM_ICLODAT_D}.dat' , 'U','')
		insert into BEST..TI17PERMFIL values ('I17L_EXTENDED','ESX_FTECLEDR_MVT','${DFILP}/${ENV_PREFIX}_ESFD3840_I17L_GLT_MRG_STD_FTECLEDR_MVT_${TYPEINV}_${PARM_ICLODAT_D}.dat' , 'U','')
		--insert into BEST..TI17PERMFIL values ('I17L_EXTENDED','ESX_FCSM_LC_ENDING_ASS', '${DFILP}/${ENV_PREFIX}_ESFD3870_I17L_GLT_ALL_STD_FCSM_LC_ENDING_ASS_${TYPEINV}_${PARM_ICLODAT_D}.dat' , 'U','')
		--insert into BEST..TI17PERMFIL values ('I17L_EXTENDED','ESX_FCSM_ENDING_RNP', '${DFILP}/${ENV_PREFIX}_ESFD3870_I17L_GLT_ALL_STD_FCSM_ENDING_RNP_${TYPEINV}_${PARM_ICLODAT_D}.dat' , 'U','')
		insert into BEST..TI17PERMFIL values ('I17L_EXTENDED','ESX_FTECLEDR', '${DFILP}/${ENV_PREFIX}_ESFD4010_I17L_PAA_ALL_STD_PAA_RETRO_${TYPEINV}_${PARM_ICLODAT_D}.dat' , 'U','')
		insert into BEST..TI17PERMFIL values ('I17L_EXTENDED','ESF_FI17CLOPER','${DFILP}/${ENV_PREFIX}_ESFD1130_FI17CLOPER_I17L_DSC_ALL_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat' , 'U','')
					
		-- Q+1
		insert into BEST..TI17PERMFIL values ('I17L_EXTENDED','ESX_FSEGPATTERNDSCf17'		,'${DFILP}/${ENV_PREFIX}_ESFD1130_FSEGPATTERNDSCf17_I17L_${TYPEINV}_${PARM_ICLODAT_D}.dat', 'U','')
		insert into BEST..TI17PERMFIL values ('I17L_EXTENDED','ESX_GTSII_ESCOMPTE_DSC'		,'${DFILP}/${ENV_PREFIX}_ESFD3620_I17L_DSC_LKI_STD_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}.dat', 'U','')
		insert into BEST..TI17PERMFIL values ('I17L_EXTENDED','ESX_GTSII_ESCOMPTE_RAD'		,'${DFILP}/${ENV_PREFIX}_ESFD3620_I17L_RAD_LKI_STD_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}.dat', 'U','')
		insert into BEST..TI17PERMFIL values ('I17L_EXTENDED','ESX_GTSII_GLOBAL_CASHFLOW'	,'${DFILP}/${ENV_PREFIX}_ESFD3630_I17L_IEX_ALL_STD_GTSII_GLOBAL_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat', 'U','')
		insert into BEST..TI17PERMFIL values ('I17L_EXTENDED','ESX_GTSII_DAC_LKI'			,'${DFILP}/${ENV_PREFIX}_ESFD3640_I17L_IVR_CHR_STD_DAC_LKI_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat', 'U','')
		-- insert into BEST..TI17PERMFIL values ('I17L_EXTENDED','ESX_GTSII_CASHFLOW'			,'${DFILP}/${ENV_PREFIX}_ESFD3650_I17L_RAD_CKI_STD_GTSII_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat', 'U','')
		insert into BEST..TI17PERMFIL values ('I17L_EXTENDED','ESX_GTSII_CSM_CASHFLOW'		,'${DFILP}/${ENV_PREFIX}_ESFD3760_I17L_UOA_PRO_STD_GTSII_CSM_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat', 'U','')
		insert into BEST..TI17PERMFIL values ('I17L_EXTENDED','ESX_FTECLEDA'				,'${DFILP}/${ENV_PREFIX}_ESFD3870_I17L_GLT_ALL_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat', 'U','')
		insert into BEST..TI17PERMFIL values ('I17L_EXTENDED','ESX_GTSII_CASHFLOW_RAD_CUR'	,'${DFILP}/${ENV_PREFIX}_ESFD3650_I17L_RAD_CUR_STD_GTSII_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat', 'U','')
		insert into BEST..TI17PERMFIL values ('I17L_EXTENDED','ESX_GTSII_ESCOMPTE_RAD_DSI'	,'${DFILP}/${ENV_PREFIX}_ESFD3620_I17L_RAD_DSI_STD_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}.dat', 'U','')

			
		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17LQPOSX',  'I17L_EXTENDED','')
			insert into BEST..TI17REQFNC values ('I17LYPOSX',  'I17L_EXTENDED','')
			insert into BEST..TI17REQFNC values ('I17LQPOS',  'I17L_EXTENDED','')
			insert into BEST..TI17REQFNC values ('I17LYPOS',  'I17L_EXTENDED','')

-------------------------------------------------------------------Archive ----------------------------------------------------------------------------------------------------

	



go


