-------------------------------
--mapping of  ESFD3970 

	----------   Clean tables   ---------------------

	delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD3970')
	delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD3970')
	delete BEST..TI17FNC where CHAIN_CT='ESFD3970'
	delete BEST..TI17CHN  where CHAIN_CT='ESFD3970'

	insert into BEST..TI17CHN values ('ESFD3970',  'IFRS17 - NDIC cashflow calculation')

	----------IDF_CT:   EBS_ESFD3970 ------------------

		insert into BEST..TI17FNC values ('EBS_ESFD3970','EBS - NDIC STD cashflow calculation','ESFD3970',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('EBS_ESFD3970',  'ESF_IADVPERICASE_P','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD3970',  'ESF_IRDPERICASE_NP','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD3970',  'EPO_IADPERICASE_TRN','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD3970',  'EST_IADPERICASE_STD','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD3970',  'ESF_FPRSMAP_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FPRSMAP_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD3970',  'EST_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD3970',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD3970',  'EPO_FCTRGRO','${DFILP}/${ENV_PREFIX}_ESFD5010_FCTRGRO_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD3970',  'EST_FCTRGRO','${DFILP}/${ENV_PREFIX}_ESFD5010_FCTRGRO_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD3970',  'EST_ACC_NDIC_AMOUNT','${DFILP}/${ENV_PREFIX}_ESFD3920_NDC_ALL_STD_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD3970',  'EST_FSEGPATTERN_CSF','${DFILP}/${ENV_PREFIX}_ESPD0060_FSEGPATTERN_CSF_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD3970',  'EST_IRDPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5010_IRDPERICASE0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD3970',  'EPO_IADPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5040_IADPERICASE_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD3970',  'ESF_DLREGTAR','${DFILP}/${ENV_PREFIX}_ESFD2550_EBS_ESFD2550_TC_DLREGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD3970',  'EST_ACC_NDIC_RETRO_AMOUNT','${DFILP}/${ENV_PREFIX}_ESFD3950_NDCR_ALL_STD_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD3970',  'NDIC_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESFD3970_NDC_CSF_STD_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('EBSEQPOS',  'EBS_ESFD3970','')
			insert into BEST..TI17REQFNC values ('EBSEYINV',  'EBS_ESFD3970','')
			insert into BEST..TI17REQFNC values ('EBSEYPOS',  'EBS_ESFD3970','')
			insert into BEST..TI17REQFNC values ('EBSEMINV',  'EBS_ESFD3970','')
			insert into BEST..TI17REQFNC values ('EBSEQINV',  'EBS_ESFD3970','')

	----------IDF_CT:   I17G_ESFD3970 ------------------

		insert into BEST..TI17FNC values ('I17G_ESFD3970','EBS - NDIC STD cashflow calculation','ESFD3970',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17G_ESFD3970',  'ESF_IADVPERICASE_P','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD3970',  'ESF_IRDPERICASE_NP','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD3970',  'EPO_IADPERICASE_TRN','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD3970',  'EST_IADPERICASE_STD','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD3970',  'ESF_FPRSMAP_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FPRSMAP_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD3970',  'EST_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD3970',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD3970',  'EPO_FCTRGRO','${DFILP}/${ENV_PREFIX}_ESFD5010_FCTRGRO_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD3970',  'EST_FCTRGRO','${DFILP}/${ENV_PREFIX}_ESFD5010_FCTRGRO_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD3970',  'EST_ACC_NDIC_AMOUNT','${DFILP}/${ENV_PREFIX}_ESFD3920_NDC_ALL_STD_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD3970',  'EST_FSEGPATTERN_CSF','${DFILP}/${ENV_PREFIX}_ESPD0060_FSEGPATTERN_CSF_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD3970',  'EST_IRDPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5010_IRDPERICASE0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD3970',  'EPO_IADPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5040_IADPERICASE_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD3970',  'ESF_DLREGTAR','${DFILP}/${ENV_PREFIX}_ESFD2550_I17G_NTC_RPO_INI_DLREGTARSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD3970',  'EST_ACC_NDIC_RETRO_AMOUNT','${DFILP}/${ENV_PREFIX}_ESFD3950_NDCR_ALL_STD_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD3970',  'NDIC_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESFD3970_NDC_CSF_STD_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17GQPOS',  'I17G_ESFD3970','')
			insert into BEST..TI17REQFNC values ('I17GYINV',  'I17G_ESFD3970','')
			insert into BEST..TI17REQFNC values ('I17GYPOS',  'I17G_ESFD3970','')
			insert into BEST..TI17REQFNC values ('I17GMINV',  'I17G_ESFD3970','')
			insert into BEST..TI17REQFNC values ('I17GQINV',  'I17G_ESFD3970','')

	----------IDF_CT:   I17G_NDC_CSF_INI ------------------

		insert into BEST..TI17FNC values ('I17G_NDC_CSF_INI','IFRS17 Group - NDIC cashflow calculation','ESFD3970',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17G_NDC_CSF_INI',  'ESF_IRDPERICASE_NP','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_CSF_INI',  'EPO_IADPERICASE_TRN','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_CSF_INI',  'ESF_FPRSMAP_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FPRSMAP_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_CSF_INI',  'EST_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_CSF_INI',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_CSF_INI',  'EPO_FCTRGRO','${DFILP}/${ENV_PREFIX}_ESFD5010_I17G_MRG_PER_INI_FCTRGRO_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_CSF_INI',  'EPO_IADPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17G_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_CSF_INI',  'EST_FCTRGRO','${DFILP}/${ENV_PREFIX}_ESFD5010_I17G_MRG_PER_INI_FCTRGRO_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_CSF_INI',  'EST_IRDPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE_I17G_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_CSF_INI',  'EST_FSEGPATTERN_CSF','${DFILP}/${ENV_PREFIX}_ESPD0060_FSEGPATTERN_CSF_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_CSF_INI',  'EST_IADPERICASE_STD','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17G_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_CSF_INI',  'ESF_DLREGTAR','${DFILP}/${ENV_PREFIX}_ESFD2550_I17G_NTC_RPO_INI_DLREGTARSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_CSF_INI',  'ESF_IADVPERICASE_P','${DFILP}/${ENV_PREFIX}_ESFD5020_IADVPERICASE_P_I17G_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_CSF_INI',  'EST_ACC_NDIC_AMOUNT','${DFILP}/${ENV_PREFIX}_ESFD3920_I17G_NDC_ALL_INI_NDIC_ACCOUNT_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_CSF_INI',  'EST_ACC_NDIC_RETRO_AMOUNT','${DFILP}/${ENV_PREFIX}_ESFD3950_I17G_NDCR_ALL_INI_ACC_NDIC_AMOUNT_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_CSF_INI',  'NDIC_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESFD3970_I17G_NDC_CSF_INI_ACC_NDIC_AMOUNT${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17GMINV',  'I17G_NDC_CSF_INI','')
			insert into BEST..TI17REQFNC values ('I17GQINV',  'I17G_NDC_CSF_INI','')
			insert into BEST..TI17REQFNC values ('I17GQPOS',  'I17G_NDC_CSF_INI','')
			insert into BEST..TI17REQFNC values ('I17GYINV',  'I17G_NDC_CSF_INI','')
			insert into BEST..TI17REQFNC values ('I17GYPOS',  'I17G_NDC_CSF_INI','')

	----------IDF_CT:   I17L_NDC_CSF_INI ------------------

		insert into BEST..TI17FNC values ('I17L_NDC_CSF_INI','IFRS17 Local - NDIC cashflow calculation','ESFD3970',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17L_NDC_CSF_INI',  'ESF_IRDPERICASE_NP','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_NDC_CSF_INI',  'EPO_IADPERICASE_TRN','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_NDC_CSF_INI',  'ESF_FPRSMAP_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FPRSMAP_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_NDC_CSF_INI',  'EST_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_NDC_CSF_INI',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_NDC_CSF_INI',  'EPO_FCTRGRO','${DFILP}/${ENV_PREFIX}_ESFD5010_I17L_MRG_PER_INI_FCTRGRO_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_NDC_CSF_INI',  'EPO_IADPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17L_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_NDC_CSF_INI',  'EST_FCTRGRO','${DFILP}/${ENV_PREFIX}_ESFD5010_I17L_MRG_PER_INI_FCTRGRO_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_NDC_CSF_INI',  'EST_IRDPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE_I17L_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_NDC_CSF_INI',  'EST_FSEGPATTERN_CSF','${DFILP}/${ENV_PREFIX}_ESPD0060_FSEGPATTERN_CSF_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_NDC_CSF_INI',  'EST_IADPERICASE_STD','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17L_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_NDC_CSF_INI',  'ESF_DLREGTAR','${DFILP}/${ENV_PREFIX}_ESFD2550_I17L_NTC_RPO_INI_DLREGTARSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_NDC_CSF_INI',  'ESF_IADVPERICASE_P','${DFILP}/${ENV_PREFIX}_ESFD5020_IADVPERICASE_P_I17L_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_NDC_CSF_INI',  'EST_ACC_NDIC_AMOUNT','${DFILP}/${ENV_PREFIX}_ESFD3920_I17L_NDC_ALL_INI_NDIC_ACCOUNT_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_NDC_CSF_INI',  'EST_ACC_NDIC_RETRO_AMOUNT','${DFILP}/${ENV_PREFIX}_ESFD3950_I17L_NDCR_ALL_INI_ACC_NDIC_AMOUNT_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_NDC_CSF_INI',  'NDIC_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESFD3970_I17L_NDC_CSF_INI_ACC_NDIC_AMOUNT${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17LYPOS',  'I17L_NDC_CSF_INI','')
			insert into BEST..TI17REQFNC values ('I17LMINV',  'I17L_NDC_CSF_INI','')
			insert into BEST..TI17REQFNC values ('I17LQINV',  'I17L_NDC_CSF_INI','')
			insert into BEST..TI17REQFNC values ('I17LQPOS',  'I17L_NDC_CSF_INI','')
			insert into BEST..TI17REQFNC values ('I17LYINV',  'I17L_NDC_CSF_INI','')

	----------IDF_CT:   I17P_NDC_CSF_INI ------------------

		insert into BEST..TI17FNC values ('I17P_NDC_CSF_INI','IFRS17 Parent - NDIC cashflow calculation','ESFD3970',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17P_NDC_CSF_INI',  'ESF_IRDPERICASE_NP','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_NDC_CSF_INI',  'EPO_IADPERICASE_TRN','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_NDC_CSF_INI',  'ESF_FPRSMAP_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FPRSMAP_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_NDC_CSF_INI',  'EST_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_NDC_CSF_INI',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_NDC_CSF_INI',  'EPO_FCTRGRO','${DFILP}/${ENV_PREFIX}_ESFD5010_I17P_MRG_PER_INI_FCTRGRO_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_NDC_CSF_INI',  'EPO_IADPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17P_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_NDC_CSF_INI',  'EST_FCTRGRO','${DFILP}/${ENV_PREFIX}_ESFD5010_I17P_MRG_PER_INI_FCTRGRO_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_NDC_CSF_INI',  'EST_IRDPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE_I17P_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_NDC_CSF_INI',  'EST_FSEGPATTERN_CSF','${DFILP}/${ENV_PREFIX}_ESPD0060_FSEGPATTERN_CSF_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_NDC_CSF_INI',  'EST_IADPERICASE_STD','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17P_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_NDC_CSF_INI',  'ESF_DLREGTAR','${DFILP}/${ENV_PREFIX}_ESFD2550_I17P_NTC_RPO_INI_DLREGTARSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_NDC_CSF_INI',  'ESF_IADVPERICASE_P','${DFILP}/${ENV_PREFIX}_ESFD5020_IADVPERICASE_P_I17P_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_NDC_CSF_INI',  'EST_ACC_NDIC_AMOUNT','${DFILP}/${ENV_PREFIX}_ESFD3920_I17P_NDC_ALL_INI_NDIC_ACCOUNT_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_NDC_CSF_INI',  'EST_ACC_NDIC_RETRO_AMOUNT','${DFILP}/${ENV_PREFIX}_ESFD3950_I17P_NDCR_ALL_INI_ACC_NDIC_AMOUNT_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_NDC_CSF_INI',  'NDIC_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESFD3970_I17P_NDC_CSF_INI_ACC_NDIC_AMOUNT${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17PMINV',  'I17P_NDC_CSF_INI','')
			insert into BEST..TI17REQFNC values ('I17PQINV',  'I17P_NDC_CSF_INI','')
			insert into BEST..TI17REQFNC values ('I17PQPOS',  'I17P_NDC_CSF_INI','')
			insert into BEST..TI17REQFNC values ('I17PYINV',  'I17P_NDC_CSF_INI','')
			insert into BEST..TI17REQFNC values ('I17PYPOS',  'I17P_NDC_CSF_INI','')

	----------IDF_CT:   I17S_ESFD3970 ------------------

		insert into BEST..TI17FNC values ('I17S_ESFD3970','EBS - NDIC STD cashflow calculation','ESFD3970',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17S_ESFD3970',  'ESF_IADVPERICASE_P','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD3970',  'ESF_IRDPERICASE_NP','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD3970',  'EPO_IADPERICASE_TRN','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD3970',  'EST_IADPERICASE_STD','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD3970',  'ESF_FPRSMAP_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FPRSMAP_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD3970',  'EST_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD3970',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD3970',  'EPO_FCTRGRO','${DFILP}/${ENV_PREFIX}_ESFD5010_FCTRGRO_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD3970',  'EST_FCTRGRO','${DFILP}/${ENV_PREFIX}_ESFD5010_FCTRGRO_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD3970',  'EST_ACC_NDIC_AMOUNT','${DFILP}/${ENV_PREFIX}_ESFD3920_NDC_ALL_STD_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD3970',  'ESF_DLREGTAR','${DFILP}/${ENV_PREFIX}_ESFD2550_I17S_NTC_RPO_INI_DLREGTAR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD3970',  'EST_FSEGPATTERN_CSF','${DFILP}/${ENV_PREFIX}_ESPD0060_FSEGPATTERN_CSF_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD3970',  'EST_IRDPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5010_IRDPERICASE0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD3970',  'EPO_IADPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5040_IADPERICASE_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD3970',  'EST_ACC_NDIC_RETRO_AMOUNT','${DFILP}/${ENV_PREFIX}_ESFD3950_NDCR_ALL_STD_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD3970',  'NDIC_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESFD3970_NDC_CSF_STD_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17SQPOS',  'I17S_ESFD3970','')
			insert into BEST..TI17REQFNC values ('I17SYINV',  'I17S_ESFD3970','')
			insert into BEST..TI17REQFNC values ('I17SYPOS',  'I17S_ESFD3970','')
			insert into BEST..TI17REQFNC values ('I17SMINV',  'I17S_ESFD3970','')
			insert into BEST..TI17REQFNC values ('I17SQINV',  'I17S_ESFD3970','')

	----------IDF_CT:   I17S_NDC_CSF_INI ------------------

		insert into BEST..TI17FNC values ('I17S_NDC_CSF_INI','IFRS17 Simulation - NDIC cashflow calculation','ESFD3970',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17S_NDC_CSF_INI',  'ESF_IRDPERICASE_NP','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_CSF_INI',  'EPO_IADPERICASE_TRN','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_CSF_INI',  'ESF_FPRSMAP_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FPRSMAP_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_CSF_INI',  'EST_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_CSF_INI',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_CSF_INI',  'EPO_FCTRGRO','${DFILP}/${ENV_PREFIX}_ESFD5010_I17S_MRG_PER_INI_FCTRGRO_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_CSF_INI',  'EPO_IADPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17S_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_CSF_INI',  'EST_FCTRGRO','${DFILP}/${ENV_PREFIX}_ESFD5010_I17S_MRG_PER_INI_FCTRGRO_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_CSF_INI',  'EST_IRDPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE_I17S_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_CSF_INI',  'ESF_DLREGTAR','${DFILP}/${ENV_PREFIX}_ESFD2550_I17S_NTC_RPO_INI_DLREGTAR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_CSF_INI',  'EST_FSEGPATTERN_CSF','${DFILP}/${ENV_PREFIX}_ESPD0060_FSEGPATTERN_CSF_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_CSF_INI',  'EST_IADPERICASE_STD','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17S_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_CSF_INI',  'ESF_IADVPERICASE_P','${DFILP}/${ENV_PREFIX}_ESFD5020_IADVPERICASE_P_I17S_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_CSF_INI',  'EST_ACC_NDIC_AMOUNT','${DFILP}/${ENV_PREFIX}_ESFD3920_I17S_NDC_ALL_INI_NDIC_ACCOUNT_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_CSF_INI',  'EST_ACC_NDIC_RETRO_AMOUNT','${DFILP}/${ENV_PREFIX}_ESFD3950_I17S_NDCR_ALL_INI_ACC_NDIC_AMOUNT_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_CSF_INI',  'NDIC_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESFD3970_I17S_NDC_CSF_INI_ACC_NDIC_AMOUNT${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17SQPOS',  'I17S_NDC_CSF_INI','')
			insert into BEST..TI17REQFNC values ('I17SYINV',  'I17S_NDC_CSF_INI','')
			insert into BEST..TI17REQFNC values ('I17SYPOS',  'I17S_NDC_CSF_INI','')
			insert into BEST..TI17REQFNC values ('I17SQINV',  'I17S_NDC_CSF_INI','')
			insert into BEST..TI17REQFNC values ('I17SMINV',  'I17S_NDC_CSF_INI','')
go

