-------------------------------
--mapping of  ESID2560

	----------   Clean tables   ---------------------

	delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESID2560')
	delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESID2560')
	delete BEST..TI17FNC where CHAIN_CT='ESID2560'
	delete BEST..TI17CHN  where CHAIN_CT='ESID2560'

	insert into BEST..TI17CHN values ('ESID2560',  '')

	----------IDF_CT:   ESID2560 ------------------

		insert into BEST..TI17FNC values ('ESID2560',' ','ESID2560',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('ESID2560',  'EST_GTA','${DFILP}/${ENV_PREFIX}_ESIX7000_GTA.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560',  'EST_GTR','${DFILP}/${ENV_PREFIX}_ESIX7000_GTR.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560',  'EST_FDETTRS','${DFILP}/${ENV_PREFIX}_ESCJ0060_FDETTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560',  'EST_FLIBEL2','${DFILP}/${ENV_PREFIX}_ESCJ0060_FLIBEL2.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560',  'EST_FTRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560',  'EST_VENTNP_TRIMCUR','${DFILP}/${ENV_PREFIX}_ESIX7000_VENTNP_TRIMCUR.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560',  'EST_VENTNP_TRIMPREV','${DFILP}/${ENV_PREFIX}_ESIX7000_VENTNP_TRIMPREV.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560',  'EST_MGTR','${DFILP}/${ENV_PREFIX}_ESIX7000_MGTR${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560',  'EST_IGTR','${DFILP}/${ENV_PREFIX}_ESID0560_IGTR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560',  'EST_FTVENTNP','${DFILP}/${ENV_PREFIX}_ESID0060_FTVENTNP_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560',  'EST_IGTAR','${DFILP}/${ENV_PREFIX}_ESID0560_IGTAR${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560',  'EST_MGTAR','${DFILP}/${ENV_PREFIX}_ESIX7000_MGTAR${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560',  'EST_FPLATXCUM','${DFILP}/${ENV_PREFIX}_ESID0560_FPLATXCUM_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560',  'EST_DLAGTR','${DFILP}/${ENV_PREFIX}_ESID0560_DLAGTR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560',  'EST_DLSGTR','${DFILP}/${ENV_PREFIX}_ESID1800_DLSGTR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560',  'EST_FVENTNPANT','${DFILP}/${ENV_PREFIX}_ESIX7000_FVENTNPANT_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560',  'EST_DLAGTAR','${DFILP}/${ENV_PREFIX}_ESID0560_DLAGTAR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560',  'EST_DLDVGTR','${DFILP}/${ENV_PREFIX}_ESID2550_DLDVGTR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560',  'EST_DLREGTR','${DFILP}/${ENV_PREFIX}_ESID2500_DLREGTR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560',  'EST_DLRPGTR','${DFILP}/${ENV_PREFIX}_ESID2500_DLRPGTR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560',  'EST_DLRTGTR','${DFILP}/${ENV_PREFIX}_ESID2500_DLRTGTR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560',  'EST_DLSGTAR','${DFILP}/${ENV_PREFIX}_ESID1800_DLSGTAR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560',  'EST_DLVGTR','${DFILP}/${ENV_PREFIX}_ESID2040_DLVGTR_PC_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560',  'EST_DLREGTAR','${DFILP}/${ENV_PREFIX}_ESID2500_DLREGTAR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560',  'EST_DLRNPGTR','${DFILP}/${ENV_PREFIX}_ESID1550_DLRNPGTR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560',  'EST_DLRPGTAR','${DFILP}/${ENV_PREFIX}_ESID2500_DLRPGTAR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560',  'EST_DLRTCGTR','${DFILP}/${ENV_PREFIX}_ESID2500_DLRTCGTR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560',  'EST_DLRTFGTR','${DFILP}/${ENV_PREFIX}_ESID2500_DLRTFGTR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560',  'EST_DLRTGTAR','${DFILP}/${ENV_PREFIX}_ESID2500_DLRTGTAR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560',  'EST_FTRSLNK7','${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRSLNK7_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560',  'EST_IRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_IRDVPERICASE_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560',  'EST_DLRNPGTAR','${DFILP}/${ENV_PREFIX}_ESID1550_DLRNPGTAR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560',  'EST_DLRTCGTAR','${DFILP}/${ENV_PREFIX}_ESID2500_DLRTCGTAR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560',  'EST_DLRTFGTAR','${DFILP}/${ENV_PREFIX}_ESID2500_DLRTFGTAR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560',  'EST_OIRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_OIRDVPERICASE_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560',  'EST_DLGTARSNEM','${DFILP}/${ENV_PREFIX}_ESID2100_DLGTARSNEM_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560',  'EST_DLREMAJGTR','${DFILP}/${ENV_PREFIX}_ESID2500_DLREMAJGTR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560',  'EST_DLREMAJGTAR','${DFILP}/${ENV_PREFIX}_ESID2500_DLREMAJGTAR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560',  'EST_CADVPERIESB0','${DFILP}/${ENV_PREFIX}_ESID0060_CADVPERIESB0_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560',  'EST_DLVGTAR','`ls -rt ${DFILP}/${ENV_PREFIX}_ESID2040_DLVGTAR_PC_${PARM_ICLODAT_D}_*.dat | tail -1 `','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560',  'EST_TOTGTR','${DFILP}/${ENV_PREFIX}_ESID2560_TOTGTR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2560',  'EST_TOTGTAR','${DFILP}/${ENV_PREFIX}_ESID2560_TOTGTAR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2560',  'EST_DLDVGTAR','${DFILP}/${ENV_PREFIX}_ESID2560_DLDVGTAR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2560',  'EST_DLTOTGTR','${DFILP}/${ENV_PREFIX}_ESID2560_DLTOTGTR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2560',  'EST_DLTOTGTAR','${DFILP}/${ENV_PREFIX}_ESID2560_DLTOTGTAR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I4IMINV',  'ESID2560','')
			insert into BEST..TI17REQFNC values ('I4IQINV',  'ESID2560','')
			insert into BEST..TI17REQFNC values ('I4IYINV',  'ESID2560','')
			insert into BEST..TI17REQFNC values ('I4IYINVB',  'ESID2560','')

	----------IDF_CT:   ESID2560_I4_PC___ ------------------

		insert into BEST..TI17FNC values ('ESID2560_I4_PC___',' ','ESID2560',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC___',  'EST_DLVGTR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC___',  'EST_DLVGTAR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC___',  'EST_GTA','${DFILP}/${ENV_PREFIX}_ESIX7000_GTA.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC___',  'EST_GTR','${DFILP}/${ENV_PREFIX}_ESIX7000_GTR.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC___',  'EST_FDETTRS','${DFILP}/${ENV_PREFIX}_ESCJ0060_FDETTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC___',  'EST_FLIBEL2','${DFILP}/${ENV_PREFIX}_ESCJ0060_FLIBEL2.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC___',  'EST_FTRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC___',  'EST_VENTNP_TRIMCUR','${DFILP}/${ENV_PREFIX}_ESIX7000_VENTNP_TRIMCUR.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC___',  'EST_VENTNP_TRIMPREV','${DFILP}/${ENV_PREFIX}_ESIX7000_VENTNP_TRIMPREV.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC___',  'EST_MGTR','${DFILP}/${ENV_PREFIX}_ESIX7000_MGTR${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC___',  'EST_IGTR','${DFILP}/${ENV_PREFIX}_ESID0560_IGTR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC___',  'EST_FTVENTNP','${DFILP}/${ENV_PREFIX}_ESID0060_FTVENTNP_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC___',  'EST_MGTAR','${DFILP}/${ENV_PREFIX}_ESIX7000_MGTAR${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC___',  'EST_IGTAR0','${DFILP}/${ENV_PREFIX}_ESID0560_IGTAR${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC___',  'EST_FPLATXCUM','${DFILP}/${ENV_PREFIX}_ESID0560_FPLATXCUM_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC___',  'EST_DLAGTR','${DFILP}/${ENV_PREFIX}_ESID0560_DLAGTR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC___',  'EST_DLSGTR','${DFILP}/${ENV_PREFIX}_ESID1800_DLSGTR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC___',  'EST_FVENTNPANT','${DFILP}/${ENV_PREFIX}_ESIX7000_FVENTNPANT_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC___',  'EST_DLAGTAR','${DFILP}/${ENV_PREFIX}_ESID0560_DLAGTAR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC___',  'EST_DLRPGTR','${DFILP}/${ENV_PREFIX}_ESID2500_DLRPGTR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC___',  'EST_DLRTGTR','${DFILP}/${ENV_PREFIX}_ESID2500_DLRTGTR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC___',  'EST_DLSGTAR','${DFILP}/${ENV_PREFIX}_ESID1800_DLSGTAR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC___',  'EST_DLRNPGTR','${DFILP}/${ENV_PREFIX}_ESID1550_DLRNPGTR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC___',  'EST_DLRPGTAR','${DFILP}/${ENV_PREFIX}_ESID2500_DLRPGTAR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC___',  'EST_DLRTCGTR','${DFILP}/${ENV_PREFIX}_ESID2500_DLRTCGTR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC___',  'EST_DLRTFGTR','${DFILP}/${ENV_PREFIX}_ESID2500_DLRTFGTR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC___',  'EST_DLRTGTAR','${DFILP}/${ENV_PREFIX}_ESID2500_DLRTGTAR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC___',  'EST_FTRSLNK7','${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRSLNK7_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC___',  'EST_IGTAR','${DFILP}/${ENV_PREFIX}_ESID0560_I4_PC___IGTAR${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC___',  'EST_IRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_IRDVPERICASE_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC___',  'EST_DLRNPGTAR','${DFILP}/${ENV_PREFIX}_ESID1550_DLRNPGTAR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC___',  'EST_DLRTCGTAR','${DFILP}/${ENV_PREFIX}_ESID2500_DLRTCGTAR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC___',  'EST_DLRTFGTAR','${DFILP}/${ENV_PREFIX}_ESID2500_DLRTFGTAR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC___',  'EST_OIRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_OIRDVPERICASE_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC___',  'EST_DLGTARSNEM','${DFILP}/${ENV_PREFIX}_ESID2100_DLGTARSNEM_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC___',  'EST_DLDVGTR','${DFILP}/${ENV_PREFIX}_ESID2550_I4_PC___DLDVGTR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC___',  'EST_DLREGTR','${DFILP}/${ENV_PREFIX}_ESID2500_I4_PC___DLREGTR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC___',  'EST_CADVPERIESB0','${DFILP}/${ENV_PREFIX}_ESID0060_CADVPERIESB0_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC___',  'EST_DLREGTAR','${DFILP}/${ENV_PREFIX}_ESID2500_I4_PC___DLREGTAR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC___',  'EST_DLREMAJGTR','${DFILP}/${ENV_PREFIX}_ESID2500_I4_PC___DLREMAJGTR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC___',  'EST_TOTGTR','${DFILP}/${ENV_PREFIX}_ESID2560_I4_PC___TOTGTR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC___',  'EST_TOTGTAR','${DFILP}/${ENV_PREFIX}_ESID2560_I4_PC___TOTGTAR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC___',  'EST_DLDVGTAR','${DFILP}/${ENV_PREFIX}_ESID2560_I4_PC___DLDVGTAR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC___',  'EST_DLTOTGTR','${DFILP}/${ENV_PREFIX}_ESID2560_I4_PC___DLTOTGTR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC___',  'EST_DLTOTGTAR','${DFILP}/${ENV_PREFIX}_ESID2560_I4_PC___DLTOTGTAR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2560_I4_PC___',  'EST_DLREMAJGTAR','${DFILP}/${ENV_PREFIX}_ESID2500_I4_PC___DLREMAJGTAR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I4IMINVB',  'ESID2560_I4_PC___','')
			insert into BEST..TI17REQFNC values ('I4IQINV',  'ESID2560_I4_PC___','')
			insert into BEST..TI17REQFNC values ('I4IQINVB',  'ESID2560_I4_PC___','')
			insert into BEST..TI17REQFNC values ('I4IYINV',  'ESID2560_I4_PC___','')
			insert into BEST..TI17REQFNC values ('I4IYINVB',  'ESID2560_I4_PC___','')
go

