-------------------------------
--mapping of  ESPD3610 

	----------   Clean tables   ---------------------

	delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESPD3610')
	delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESPD3610')
	delete BEST..TI17FNC where CHAIN_CT='ESPD3610'
	delete BEST..TI17CHN  where CHAIN_CT='ESPD3610'

	insert into BEST..TI17CHN values ('ESPD3610',  'Cach flow calculation jobs ESID3702A et ESID3703A')

	----------IDF_CT:   EBS_ESPD3610 ------------------

		insert into BEST..TI17FNC values ('EBS_ESPD3610','Post omega EBS','ESPD3610',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610',  'EST_FLIBEL2','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610',  'ESF_DLDGTR_P','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610',  'ESF_DLDGTR_NP','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610',  'ESF_IADVPERICASE_P','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610',  'ESF_IRDPERICASE_NP','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610',  'EST_IADPERICASE_STD','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610',  'ESF_FTUWSEC','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTUWSEC.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610',  'EST_FWHGTA','${DFILP}/${ENV_PREFIX}_ESCJ0660_FWHGTA.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610',  'EST_FWHGTR','${DFILP}/${ENV_PREFIX}_ESCJ0660_FWHGTR.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610',  'EST_FCURSII','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURSII.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610',  'EST_FRATINGRTO','${DFILP}/${ENV_PREFIX}_ESCJ0660_FRATINGRTO.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610',  'EST_FPRSMAP_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FPRSMAP_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610',  'EST_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610',  'EST_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610',  'EST_CURGTA','${DFILP}/${ENV_PREFIX}_ESFD4050_FTECLEDA_I4I_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610',  'EST_DLDGTAA','${DFILP}/${ENV_PREFIX}_ESFD2230_DLDGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610',  'EST_DLSGTAA','${DFILP}/${ENV_PREFIX}_ESPD1800_DLSGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610',  'EST_DLSGTAR','${DFILP}/${ENV_PREFIX}_ESPD1800_DLSGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610',  'EST_FCTRFWH','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTRFWH_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610',  'EPO_DLDGTAR_E','${DFILP}/${ENV_PREFIX}_ESPD2570_DLDGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610',  'EST_DLREGTAR','${DFILP}/${ENV_PREFIX}_ESPD2550_DLREGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610',  'EST_FULAERAT','${DFILP}/${ENV_PREFIX}_ESPD0060_FULAERAT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610',  'EST_FCTRGRO','${DFILP}/${ENV_PREFIX}_ESFD5010_FCTRGRO_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610',  'EST_DLREMAJGTAR','${DFILP}/${ENV_PREFIX}_ESPD2550_DLREMAJGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610',  'EST_FSEGPATTERNFWH','${DFILP}/${ENV_PREFIX}_ESPD0060_FSEGPATTERNFWH_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610',  'EST_DLDGTAA_DLSGTAA','${DFILI}/${ENV_PREFIX}_ESPD3610_DLDGTAA_DLSGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610',  'EST_DLDGTAR_DLSGTAR','${DFILI}/${ENV_PREFIX}_ESPD3610_DLDGTAR_DLSGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610',  'EST_FSEGPATTERN_BDT','${DFILP}/${ENV_PREFIX}_ESPD0060_FSEGPATTERN_BDT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610',  'EST_FSEGPATTERN_CSF','${DFILP}/${ENV_PREFIX}_ESPD0060_FSEGPATTERN_CSF_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610',  'EST_FSEGPATTERN_ICR','${DFILP}/${ENV_PREFIX}_ESPD0060_FSEGPATTERN_ICR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610',  'EST_FSEGPATTERN_INF','${DFILP}/${ENV_PREFIX}_ESPD0060_FSEGPATTERN_INF_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610',  'EST_IRDPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5010_IRDPERICASE0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610',  'EST_FPLATXCUMALL','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLATXCUMALL0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610',  'EST_IADPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5040_IADPERICASE_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610',  'EST_FTECLEDASII','`if [ "${TYPEINV}" = "POC" ];then echo ${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_EBS_POS_${PARM_ICLODAT_D}.dat;else echo ${DFILP}/empty.dat;fi;`','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610',  'ESF_GTSII_ICR','${DFILT}/${ENV_PREFIX}_ESPD3610_GTSII_ICR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610',  'EST_DLCUMGTAAR','${DFILP}/${ENV_PREFIX}_ESPD3610_DLCUMGTAAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610',  'EST_DLSIIGTAA','${DFILP}/${ENV_PREFIX}_ESPD3610_EST_DLSIIGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610',  'EST_DLSIIGTAR','${DFILP}/${ENV_PREFIX}_ESPD3610_EST_DLSIIGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610',  'EST_GTSII_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESPD3610_GTSII_CASHFLOW_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610',  'EST_GTSII_CLACC_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESPD3610_GTSII_CLACC_CASHFLOW_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610',  'EST_IADPERICASE_CTRGRO','${DFILP}/${ENV_PREFIX}_ESPD3610_EST_IADPERICASE_CTRGRO_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610',  'EST_GTSII_GLOBAL_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESPD3610_GTSII_GLOBAL_CASHFLOW_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610',  'EST_GTSII_REMAINTOPAY_ULAE','${DFILP}/${ENV_PREFIX}_ESPD3610_GTSII_REMAINTOPAY_ULAE_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610',  'EST_DLCUMGTAAR_IBNR_FUTCLAIMS','${DFILP}/${ENV_PREFIX}_ESPD3610_DLCUMGTAAR_IBNR_FUTCLAIMS_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610',  'EST_GTSII_REMAINTOPAY_ULAEINF','${DFILP}/${ENV_PREFIX}_ESPD3610_GTSII_REMAINTOPAY_ULAEINF_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('EBSEQPOC',  'EBS_ESPD3610','	Quarterly')
			insert into BEST..TI17REQFNC values ('EBSEQPOCB',  'EBS_ESPD3610','Quarterly')
			insert into BEST..TI17REQFNC values ('EBSEQPOS',  'EBS_ESPD3610','Quarterly')
			insert into BEST..TI17REQFNC values ('EBSEYINV',  'EBS_ESPD3610','Annual INV')
			insert into BEST..TI17REQFNC values ('EBSEYPOC',  'EBS_ESPD3610','Annual POC')
			insert into BEST..TI17REQFNC values ('EBSEYPOCB',  'EBS_ESPD3610','Annual POC')
			insert into BEST..TI17REQFNC values ('EBSEYPOS',  'EBS_ESPD3610','Annual POS')
			insert into BEST..TI17REQFNC values ('EBSEMINV',  'EBS_ESPD3610','Quarterly')
			insert into BEST..TI17REQFNC values ('EBSEQINV',  'EBS_ESPD3610','Quarterly')
			
			
	----------IDF_CT:   EBS_ESPD3610_BBNI ------------------

		insert into BEST..TI17FNC values ('EBS_ESPD3610_BBNI','Post omega EBS','ESPD3610',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_BBNI',  'EST_FLIBEL2','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_BBNI',  'ESF_DLDGTR_P','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_BBNI',  'ESF_DLDGTR_NP','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_BBNI',  'ESF_IADVPERICASE_P','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_BBNI',  'ESF_IRDPERICASE_NP','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_BBNI',  'EST_IADPERICASE_STD','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_BBNI',  'ESF_FTUWSEC','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTUWSEC.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_BBNI',  'EST_FWHGTA','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_BBNI',  'EST_FWHGTR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_BBNI',  'EST_FCURSII','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURSII.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_BBNI',  'EST_FRATINGRTO','${DFILP}/${ENV_PREFIX}_ESCJ0660_FRATINGRTO.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_BBNI',  'EST_FPRSMAP_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FPRSMAP_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_BBNI',  'EST_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_BBNI',  'EST_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_BBNI',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_BBNI',  'EST_CURGTA','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_BBNI',  'EST_DLDGTAA','${DFILP}/${ENV_PREFIX}_ESFD2230_BBNI_DLDGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_BBNI',  'EST_DLSGTAA','${DFILP}/${ENV_PREFIX}_ESPD1800_BBNI_DLSGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','U','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_BBNI',  'EST_DLSGTAR','${DFILP}/${ENV_PREFIX}_ESPD1800_BBNI_DLSGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','U','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_BBNI',  'EST_FCTRFWH','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTRFWH_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_BBNI',  'EPO_DLDGTAR_E','${DFILP}/${ENV_PREFIX}_ESPD2570_BBNI_DLDGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_BBNI',  'EST_DLREGTAR','${DFILP}/${ENV_PREFIX}_ESPD2550_BBNI_DLREGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_BBNI',  'EST_FULAERAT','${DFILP}/${ENV_PREFIX}_ESPD0060_FULAERAT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_BBNI',  'EST_FCTRGRO','${DFILP}/${ENV_PREFIX}_ESFD5010_FCTRGRO_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_BBNI',  'EST_DLREMAJGTAR','${DFILP}/${ENV_PREFIX}_ESPD2550_BBNI_DLREMAJGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_BBNI',  'EST_FSEGPATTERNFWH','${DFILP}/${ENV_PREFIX}_ESPD0060_FSEGPATTERNFWH_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_BBNI',  'EST_DLDGTAA_DLSGTAA','${DFILI}/${ENV_PREFIX}_ESPD3610_BBNI_DLDGTAA_DLSGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_BBNI',  'EST_DLDGTAR_DLSGTAR','${DFILI}/${ENV_PREFIX}_ESPD3610_BBNI_DLDGTAR_DLSGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_BBNI',  'EST_FSEGPATTERN_BDT','${DFILP}/${ENV_PREFIX}_ESPD0060_FSEGPATTERN_BDT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_BBNI',  'EST_FSEGPATTERN_CSF','${DFILP}/${ENV_PREFIX}_ESPD0060_FSEGPATTERN_CSF_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_BBNI',  'EST_FSEGPATTERN_ICR','${DFILP}/${ENV_PREFIX}_ESPD0060_FSEGPATTERN_ICR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_BBNI',  'EST_FSEGPATTERN_INF','${DFILP}/${ENV_PREFIX}_ESPD0060_FSEGPATTERN_INF_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_BBNI',  'EST_IRDPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5060_IRDPERICASE_BBNI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')	 --
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_BBNI',  'EST_FPLATXCUMALL','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLATXCUMALL0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','') 
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_BBNI',  'EST_IADPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5060_IADPERICASE_BBNI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')	
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_BBNI',  'EST_FTECLEDASII','`if [ "${TYPEINV}" = "POC" ];then echo ${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_EBS_POS_${PARM_ICLODAT_D}.dat;else echo ${DFILP}/empty.dat;fi;`','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_BBNI',  'ESF_GTSII_ICR','${DFILT}/${ENV_PREFIX}_ESPD3610_BBNI_GTSII_ICR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_BBNI',  'EST_DLCUMGTAAR','${DFILP}/${ENV_PREFIX}_ESPD3610_BBNI_DLCUMGTAAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_BBNI',  'EST_DLSIIGTAA','${DFILP}/${ENV_PREFIX}_ESPD3610_BBNI_EST_DLSIIGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_BBNI',  'EST_DLSIIGTAR','${DFILP}/${ENV_PREFIX}_ESPD3610_BBNI_EST_DLSIIGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_BBNI',  'EST_GTSII_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESPD3610_BBNI_GTSII_CASHFLOW_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_BBNI',  'EST_GTSII_CLACC_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESPD3610_BBNI_GTSII_CLACC_CASHFLOW_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_BBNI',  'EST_IADPERICASE_CTRGRO','${DFILP}/${ENV_PREFIX}_ESPD3610_BBNI_EST_IADPERICASE_CTRGRO_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_BBNI',  'EST_GTSII_GLOBAL_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESPD3610_BBNI_GTSII_GLOBAL_CASHFLOW_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_BBNI',  'EST_GTSII_REMAINTOPAY_ULAE','${DFILP}/${ENV_PREFIX}_ESPD3610_BBNI_GTSII_REMAINTOPAY_ULAE_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_BBNI',  'EST_DLCUMGTAAR_IBNR_FUTCLAIMS','${DFILP}/${ENV_PREFIX}_ESPD3610_BBNI_DLCUMGTAAR_IBNR_FUTCLAIMS_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_BBNI',  'EST_GTSII_REMAINTOPAY_ULAEINF','${DFILP}/${ENV_PREFIX}_ESPD3610_BBNI_GTSII_REMAINTOPAY_ULAEINF_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('EBSEQPOC',  'EBS_ESPD3610_BBNI','	Quarterly')
			insert into BEST..TI17REQFNC values ('EBSEQPOCB',  'EBS_ESPD3610_BBNI','Quarterly')
			insert into BEST..TI17REQFNC values ('EBSEQPOS',  'EBS_ESPD3610_BBNI','Quarterly')
			insert into BEST..TI17REQFNC values ('EBSEYINV',  'EBS_ESPD3610_BBNI','Annual INV')
			insert into BEST..TI17REQFNC values ('EBSEYPOC',  'EBS_ESPD3610_BBNI','Annual POC')
			insert into BEST..TI17REQFNC values ('EBSEYPOCB',  'EBS_ESPD3610_BBNI','Annual POC')
			insert into BEST..TI17REQFNC values ('EBSEYPOS',  'EBS_ESPD3610_BBNI','Annual POS')
			insert into BEST..TI17REQFNC values ('EBSEMINV',  'EBS_ESPD3610_BBNI','Quarterly')
			insert into BEST..TI17REQFNC values ('EBSEQINV',  'EBS_ESPD3610_BBNI','Quarterly')			

	----------IDF_CT:   EBS_ESPD3610_INI ------------------

		insert into BEST..TI17FNC values ('EBS_ESPD3610_INI','Post omega EBS','ESPD3610',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_INI',  'EST_FLIBEL2','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_INI',  'ESF_DLDGTR_P','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_INI',  'ESF_DLDGTR_NP','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_INI',  'ESF_IADVPERICASE_P','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_INI',  'ESF_IRDPERICASE_NP','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_INI',  'EST_IADPERICASE_STD','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_INI',  'ESF_FTUWSEC','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTUWSEC.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_INI',  'EST_FWHGTA','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_INI',  'EST_FWHGTR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_INI',  'EST_FCURSII','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURSII.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_INI',  'EST_FRATINGRTO','${DFILP}/${ENV_PREFIX}_ESCJ0660_FRATINGRTO.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_INI',  'EST_FPRSMAP_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FPRSMAP_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_INI',  'EST_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_INI',  'EST_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_INI',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_INI',  'EST_CURGTA','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_INI',  'EST_DLDGTAA','${DFILP}/${ENV_PREFIX}_ESFD2230_INI_DLDGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_INI',  'EST_DLSGTAA','${DFILP}/${ENV_PREFIX}_ESPD1800_INI_DLSGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','U','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_INI',  'EST_DLSGTAR','${DFILP}/${ENV_PREFIX}_ESPD1800_INI_DLSGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','U','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_INI',  'EST_FCTRFWH','${DFILP}/${ENV_PREFIX}_ESPD0060_FCTRFWH_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_INI',  'EPO_DLDGTAR_E','${DFILP}/${ENV_PREFIX}_ESPD2570_INI_DLDGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_INI',  'EST_DLREGTAR','${DFILP}/${ENV_PREFIX}_ESPD2550_INI_DLREGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_INI',  'EST_FULAERAT','${DFILP}/${ENV_PREFIX}_ESPD0060_FULAERAT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_INI',  'EST_FCTRGRO','${DFILP}/${ENV_PREFIX}_ESFD5010_FCTRGRO_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_INI',  'EST_DLREMAJGTAR','${DFILP}/${ENV_PREFIX}_ESPD2550_INI_DLREMAJGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_INI',  'EST_FSEGPATTERNFWH','${DFILP}/${ENV_PREFIX}_ESPD0060_FSEGPATTERNFWH_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_INI',  'EST_DLDGTAA_DLSGTAA','${DFILI}/${ENV_PREFIX}_ESPD3610_INI_DLDGTAA_DLSGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_INI',  'EST_DLDGTAR_DLSGTAR','${DFILI}/${ENV_PREFIX}_ESPD3610_INI_DLDGTAR_DLSGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_INI',  'EST_FSEGPATTERN_BDT','${DFILP}/${ENV_PREFIX}_ESPD0060_FSEGPATTERN_BDT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_INI',  'EST_FSEGPATTERN_CSF','${DFILP}/${ENV_PREFIX}_ESPD0060_FSEGPATTERN_CSF_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_INI',  'EST_FSEGPATTERN_ICR','${DFILP}/${ENV_PREFIX}_ESPD0060_FSEGPATTERN_ICR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_INI',  'EST_FSEGPATTERN_INF','${DFILP}/${ENV_PREFIX}_ESPD0060_FSEGPATTERN_INF_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_INI',  'EST_IRDPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5060_IRDPERICASE_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')	 --
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_INI',  'EST_FPLATXCUMALL','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLATXCUMALL0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','') 
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_INI',  'EST_IADPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5060_IADPERICASE_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')	
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_INI',  'EST_FTECLEDASII','`if [ "${TYPEINV}" = "POC" ];then echo ${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_EBS_POS_${PARM_ICLODAT_D}.dat;else echo ${DFILP}/empty.dat;fi;`','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_INI',  'ESF_GTSII_ICR','${DFILT}/${ENV_PREFIX}_ESPD3610_INI_GTSII_ICR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_INI',  'EST_DLCUMGTAAR','${DFILP}/${ENV_PREFIX}_ESPD3610_INI_DLCUMGTAAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_INI',  'EST_DLSIIGTAA','${DFILP}/${ENV_PREFIX}_ESPD3610_INI_EST_DLSIIGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_INI',  'EST_DLSIIGTAR','${DFILP}/${ENV_PREFIX}_ESPD3610_INI_EST_DLSIIGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_INI',  'EST_GTSII_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESPD3610_INI_GTSII_CASHFLOW_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_INI',  'EST_GTSII_CLACC_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESPD3610_INI_GTSII_CLACC_CASHFLOW_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_INI',  'EST_IADPERICASE_CTRGRO','${DFILP}/${ENV_PREFIX}_ESPD3610_INI_EST_IADPERICASE_CTRGRO_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_INI',  'EST_GTSII_GLOBAL_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESPD3610_INI_GTSII_GLOBAL_CASHFLOW_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_INI',  'EST_GTSII_REMAINTOPAY_ULAE','${DFILP}/${ENV_PREFIX}_ESPD3610_INI_GTSII_REMAINTOPAY_ULAE_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_INI',  'EST_DLCUMGTAAR_IBNR_FUTCLAIMS','${DFILP}/${ENV_PREFIX}_ESPD3610_INI_DLCUMGTAAR_IBNR_FUTCLAIMS_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3610_INI',  'EST_GTSII_REMAINTOPAY_ULAEINF','${DFILP}/${ENV_PREFIX}_ESPD3610_INI_GTSII_REMAINTOPAY_ULAEINF_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------
 
			insert into BEST..TI17REQFNC values ('EBSEQPOC',  'EBS_ESPD3610_INI','	Quarterly')
			insert into BEST..TI17REQFNC values ('EBSEQPOCB',  'EBS_ESPD3610_INI','Quarterly')
			insert into BEST..TI17REQFNC values ('EBSEQPOS',  'EBS_ESPD3610_INI','Quarterly')
			insert into BEST..TI17REQFNC values ('EBSEYINV',  'EBS_ESPD3610_INI','Annual INV')
			insert into BEST..TI17REQFNC values ('EBSEYPOC',  'EBS_ESPD3610_INI','Annual POC')
			insert into BEST..TI17REQFNC values ('EBSEYPOCB',  'EBS_ESPD3610_INI','Annual POC')
			insert into BEST..TI17REQFNC values ('EBSEYPOS',  'EBS_ESPD3610_INI','Annual POS')
			insert into BEST..TI17REQFNC values ('EBSEMINV',  'EBS_ESPD3610_INI','Quarterly')
			insert into BEST..TI17REQFNC values ('EBSEQINV',  'EBS_ESPD3610_INI','Quarterly')			
			
			
go
  
