-------------------------------
--mapping of  ESPD3800

	----------   Clean tables   ---------------------

	delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESPD3800')
	delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESPD3800')
	delete BEST..TI17FNC where CHAIN_CT='ESPD3800'
	delete BEST..TI17CHN  where CHAIN_CT='ESPD3800'

	insert into BEST..TI17CHN values ('ESPD3800',  '')

	----------IDF_CT:   EBS_ESPD3800 ------------------

		insert into BEST..TI17FNC values ('EBS_ESPD3800','IFRS4 Post omega  EBS','ESPD3800',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'EPO_FESB','${DFILP}/${ENV_PREFIX}_ESCJ0660_FESB.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'EPO_SUBTRS','${DFILP}/${ENV_PREFIX}_ESCJ0660_SUBTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'EPO_FCLIENT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCLIENT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'EPO_FCPLACC','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCPLACC.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'EPO_FDETTRS','${DFILP}/${ENV_PREFIX}_ESCJ0660_FDETTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'EPO_FSOBBLOB','${DFILP}/${ENV_PREFIX}_ESCJ0660_FSOBBLOB.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'EPO_FSSDACTR','${DFILP}/${ENV_PREFIX}_ESCJ0660_FSSDACTR.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'EPO_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'EPO_OIADVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5060_ESCJ0660_OIADVPERICASE.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'EPO_VENTNPSIICO','${DFILP}/${ENV_PREFIX}_ESPD3710_VENTNP_EBS_POC_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'EPO_DLDSIIGTARCO','${DFILP}/${ENV_PREFIX}_ESPD3710_DLDSIIGTAR_EBS_POC_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'EPO_VENTNPSIISO','${DFILP}/${ENV_PREFIX}_ESPD3710_VENTNP_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
						
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'EPO_DLSGTR','${DFILP}/${ENV_PREFIX}_ESFD5070_ESPD1800_DLSGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'EPO_DLREGTR','${DFILP}/${ENV_PREFIX}_ESFD5070_ESPD2550_DLREGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'EPO_DLRGTAA','${DFILP}/${ENV_PREFIX}_ESFD5070_ESPD2550_DLRGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')

			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'EPO_DLDGTAR_E','${DFILP}/${ENV_PREFIX}_ESFD5070_ESPD2570_DLDGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'EPO_DLDGTR_E','${DFILP}/${ENV_PREFIX}_ESFD5070_ESPD2570_DLDGTR_E_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'EPO_DLREGTAR','${DFILP}/${ENV_PREFIX}_ESFD5070_ESPD2550_DLREGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'EPO_DLSGTAASO','${DFILP}/${ENV_PREFIX}_ESFD5070_ESPD1800_DLSGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'EPO_DLSGTARCO','${DFILP}/${ENV_PREFIX}_ESFD5070_ESPD1800_DLSGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'EPO_DLSGTARSO','${DFILP}/${ENV_PREFIX}_ESFD5070_ESPD1800_DLSGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'EPO_DLDGTAASII','${DFILP}/${ENV_PREFIX}_ESFD5070_ESFD2230_DLDGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'EPO_DLSGTAASII','${DFILP}/${ENV_PREFIX}_ESFD5070_ESPD1800_DLSGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')

			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'EPO_DLASIIGTR','${DFILP}/${ENV_PREFIX}_ESFD5070_ESPD3630_DLASIIGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'EPO_DLDSIIGTR','${DFILP}/${ENV_PREFIX}_ESPD3620_DLDSIIGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'EPO_DLSGTARSIICO','${DFILP}/${ENV_PREFIX}_ESFD5070_ESPD1800_DLSGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'EPO_DLSGTARSIISO','${DFILP}/${ENV_PREFIX}_ESFD5070_ESPD1800_DLSGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'EPO_DLASIIGTAA','${DFILP}/${ENV_PREFIX}_ESFD5070_ESPD3630_DLASIIGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'EPO_DLASIIGTAR','${DFILP}/${ENV_PREFIX}_ESFD5070_ESPD3630_DLASIIGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'EPO_DLDSIIGTAA','${DFILP}/${ENV_PREFIX}_ESPD3620_DLDSIIGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'EPO_DLREMAJGTR','${DFILP}/${ENV_PREFIX}_ESFD5070_ESPD2550_DLREMAJGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'EPO_DLREMAJGTAR','${DFILP}/${ENV_PREFIX}_ESFD5070_ESPD2550_DLREMAJGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')			
			
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'EPO_FCTRGRO','${DFILP}/${ENV_PREFIX}_ESFD5010_FCTRGRO_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'EPO_FTECLEDRSIICO','${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'EPO_DLDSIIGTARSO','${DFILP}/${ENV_PREFIX}_ESPD3710_DLDSIIGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')

			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'EPO_FPLACEMT2','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLACEMT2_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'EPO_FPLATXCUM','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLATXCUM_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'EPO_OIRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5010_OIRDVPERICASE_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'EPO_GTSII_RISKMARGINCO','${DFILP}/${ENV_PREFIX}_ESPD3700_GTSII_RISKMARGIN_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'EPO_FTECLEDACO_ANNULMVT','${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_ANNULMVT_EBS_POC.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'EPO_FTECLEDRCO_ANNULMVT','${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_ANNULMVT_EBS_POC.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'EPO_FTECLEDASIICO_ANNULMVT','${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_ANNULMVT_EBS_POC.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'EPO_FTECLEDRSIICO_ANNULMVT','${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_ANNULMVT_EBS_POC.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'EPO_FTECLEDACO','${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'EPO_FTECLEDRCO','${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'EPO_FTECLEDRSO','${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'EPO_FTECLEDASIICO','${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'EPO_FTECLEDASIICO_ARC','${DARCH}/${ENV_PREFIX}_ESPD3800_FTECLEDA_EBS_POC_${PARM_ICLODAT_D}_${CRE_D}.dat.gz','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'EPO_FTECLEDRSIICO_ARC','${DARCH}/${ENV_PREFIX}_ESPD3800_FTECLEDR_EBS_POC_${PARM_ICLODAT_D}_${CRE_D}.dat.gz','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'EPO_FTECLEDASIICO_ANNULMVT_ARC','${DARCH}/${ENV_PREFIX}_ESPD3800_FTECLEDA_ANNULMVT_EBS_POC_${PARM_ICLODAT_D}_${CRE_D}.dat.gz','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'EPO_FTECLEDRSIICO_ANNULMVT_ARC','${DARCH}/${ENV_PREFIX}_ESPD3800_FTECLEDR_ANNULMVT_EBS_POC_${PARM_ICLODAT_D}_${CRE_D}.dat.gz','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'EPO_GTSII_RISKMARGINCO_ARC','${DARCH}/${ENV_PREFIX}_ESPD3700_GTSII_RISKMARGIN_EBS_${TYPEINV}_${PARM_ICLODAT_D}_${CRE_D}.dat.gz','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'ESF_FTECLEDR_MVT','${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD3800',  'ESF_FTECLEDR_EXCLUDED','${DFILI}/${ENV_PREFIX}_ESPD3800_FTECLEDR_EBS_EXCL_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('EBSEQPOC',  'EBS_ESPD3800','')
			insert into BEST..TI17REQFNC values ('EBSEQPOS',  'EBS_ESPD3800','')
			insert into BEST..TI17REQFNC values ('EBSEYINV',  'EBS_ESPD3800','')
			insert into BEST..TI17REQFNC values ('EBSEYPOC',  'EBS_ESPD3800','')
			insert into BEST..TI17REQFNC values ('EBSEYPOS',  'EBS_ESPD3800','')
			insert into BEST..TI17REQFNC values ('EBSEQPOCB',  'EBS_ESPD3800','')
			insert into BEST..TI17REQFNC values ('EBSEYPOCB',  'EBS_ESPD3800','')
			insert into BEST..TI17REQFNC values ('EBSEMINV',  'EBS_ESPD3800','')
			insert into BEST..TI17REQFNC values ('EBSEQINV',  'EBS_ESPD3800','')

	----------IDF_CT:   I4I_ESPD3800 ------------------

		insert into BEST..TI17FNC values ('I4I_ESPD3800','IFRS4 Post omega  IFRS','ESPD3800',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I4I_ESPD3800',  'EPO_DLDGTAASII','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3800',  'EPO_SUBTRS','${DFILP}/${ENV_PREFIX}_ESCJ0060_FSUBTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3800',  'EPO_FDETTRS','${DFILP}/${ENV_PREFIX}_ESCJ0060_FDETTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3800',  'EPO_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3800',  'EPO_FCLIENT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCLIENT_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3800',  'EPO_FCPLACC','${DFILP}/${ENV_PREFIX}_ESID0560_FCPLACC_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3800',  'EPO_FCTRGRO','${DFILP}/${ENV_PREFIX}_ESID0560_FCTRGRO_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3800',  'EPO_FSOBBLOB','${DFILP}/${ENV_PREFIX}_ESCJ0060_FSOBBLOB_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3800',  'EPO_FSSDACTR','${DFILP}/${ENV_PREFIX}_ESCJ0060_FSSDACTR_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3800',  'EPO_FTECLEDR','${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDR_I4I_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3800',  'EPO_FPLACEMT2','${DFILP}/${ENV_PREFIX}_ESEH1110_FPLACEMT2_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3800',  'EPO_FPLATXCUM','${DFILP}/${ENV_PREFIX}_ESID0560_FPLATXCUM_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3800',  'EPO_DLSGTR','${DFILP}/${ENV_PREFIX}_ESPD1800_DLSGTR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3800',  'EPO_DLREGTR','${DFILP}/${ENV_PREFIX}_ESPD2550_DLREGTR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3800',  'EPO_DLRGTAA','${DFILP}/${ENV_PREFIX}_ESPD2550_DLRGTAA_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3800',  'EPO_DLSGTRSO','${DFILP}/${ENV_PREFIX}_ESPD1800_DLSGTR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3800',  'EPO_OIADVPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_OIADVPERICASE_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3800',  'EPO_OIRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_OIRDVPERICASE_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3800',  'EPO_DLREGTAR','${DFILP}/${ENV_PREFIX}_ESPD2550_DLREGTAR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3800',  'EPO_DLREGTRSO','${DFILP}/${ENV_PREFIX}_ESPD2550_DLREGTR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3800',  'EPO_DLRGTAASO','${DFILP}/${ENV_PREFIX}_ESPD2550_DLRGTAA_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3800',  'EPO_DLSGTAASO','${DFILP}/${ENV_PREFIX}_ESPD1800_DLSGTAA_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3800',  'EPO_DLSGTARCO','${DFILP}/${ENV_PREFIX}_ESPD1800_DLSGTAR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3800',  'EPO_DLSGTARSO','${DFILP}/${ENV_PREFIX}_ESPD1800_DLSGTAR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3800',  'EPO_DLSGTAASII','${DFILP}/${ENV_PREFIX}_ESPD1800_DLSGTAA_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3800',  'EPO_DLREGTARSO','${DFILP}/${ENV_PREFIX}_ESPD2550_DLREGTAR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3800',  'EPO_FTECLEDASO_CUR','${DFILP}/${ENV_PREFIX}_ESPD3860_FTECLEDA_CUR_I4I_POS_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3800',  'EPO_DLREMAJGTR','${DFILP}/${ENV_PREFIX}_ESPD2550_DLREMAJGTR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3800',  'EPO_DLREMAJGTAR','${DFILP}/${ENV_PREFIX}_ESPD2550_DLREMAJGTAR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3800',  'EPO_DLREMAJGTRSO','${DFILP}/${ENV_PREFIX}_ESPD2550_DLREMAJGTR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3800',  'EPO_DLREMAJGTARSO','${DFILP}/${ENV_PREFIX}_ESPD2550_DLREMAJGTAR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3800',  'EPO_FTECLEDRSO','${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_I4I_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3800',  'EPO_FTECLEDACO_ANNULMVT','${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_ANNULMVT_I4I_POC.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3800',  'EPO_FTECLEDRCO','${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_I4I_POC_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3800',  'EPO_FTECLEDRCO_ANNULMVT','${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_ANNULMVT_I4I_POC.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3800',  'EPO_FTECLEDACO','${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3800',  'EPO_FTECLEDASO_MTH','${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_MTH_I4I_POS_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3800',  'EPO_FTECLEDASO_MVT','${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_MVT_I4I_POS_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3800',  'EPO_FTECLEDACO_ARC','${DARCH}/${ENV_PREFIX}_ESPD3800_FTECLEDA_I4I_POC_${PARM_ICLODAT_D}_${CRE_D}.dat.gz','O','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3800',  'EPO_FTECLEDRCO_ARC','${DARCH}/${ENV_PREFIX}_ESPD3800_FTECLEDR_I4I_POC_${PARM_ICLODAT_D}_${CRE_D}.dat.gz','O','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3800',  'EPO_FTECLEDACO_ANNULMVT_ARC','${DARCH}/${ENV_PREFIX}_ESPD3800_FTECLEDA_ANNULMVT_I4I_POC_${PARM_ICLODAT_D}_${CRE_D}.dat.gz','O','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3800',  'EPO_FTECLEDRCO_ANNULMVT_ARC','${DARCH}/${ENV_PREFIX}_ESPD3800_FTECLEDR_ANNULMVT_I4I_POC_${PARM_ICLODAT_D}_${CRE_D}.dat.gz','O','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3800',  'ESF_FTECLEDR_MVT','${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_I4I_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD3800',  'ESF_FTECLEDR_EXCLUDED','${DFILI}/${ENV_PREFIX}_ESPD3800_FTECLEDR_I4I_EXCL_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I4IQPOC',  'I4I_ESPD3800','')
			insert into BEST..TI17REQFNC values ('I4IYPOSB',  'I4I_ESPD3800','')
			insert into BEST..TI17REQFNC values ('I4IQPOCB',  'I4I_ESPD3800','')
			insert into BEST..TI17REQFNC values ('I4IQPOS',  'I4I_ESPD3800','')
			insert into BEST..TI17REQFNC values ('I4IQPOSB',  'I4I_ESPD3800','')
			insert into BEST..TI17REQFNC values ('I4IYPOC',  'I4I_ESPD3800','')
			insert into BEST..TI17REQFNC values ('I4IYPOCB',  'I4I_ESPD3800','')
			insert into BEST..TI17REQFNC values ('I4IYPOS',  'I4I_ESPD3800','')
go

