-------------------------------
--mapping of  ESFD2750

	----------   Clean tables   ---------------------

		delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD2750')
		delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD2750')
		delete BEST..TI17FNC where CHAIN_CT='ESFD2750'
		delete BEST..TI17CHN  where CHAIN_CT='ESFD2750'

		insert into BEST..TI17CHN values ('ESFD2750',  'Temporaire Bouclette Future RetroP AI Generation')

	
	
	----------IDF_CT:   I17G_LCC_RPO_STD_OPT1 ------------------

		insert into BEST..TI17FNC values ('I17G_LCC_RPO_STD_OPT1','Retro LC and AOC component','ESFD2750',0)
					

		----------  Perms---------------------


			INSERT INTO BEST..TI17PERMFIL VALUES ( 'I17G_LCC_RPO_STD_OPT1', 'EST_DLREGTR_ESFD2550', '${DFILP}/${ENV_PREFIX}_ESFD2550_I17G_LCC_RPO_STD_DLREGTRSII_${TYPEINV}_${PARM_ICLODAT_D}.dat', 'I', ' ' )
			INSERT INTO BEST..TI17PERMFIL VALUES ( 'I17G_LCC_RPO_STD_OPT1', 'EST_DLREGTR_ESFD2650', '${DFILP}/${ENV_PREFIX}_ESFD2650_I17G_LCC_RPO_STD_OPT1_DLREGTRSII_${TYPEINV}_${PARM_ICLODAT_D}.dat', 'O', ' ' )
			
			INSERT INTO BEST..TI17PERMFIL VALUES ( 'I17G_LCC_RPO_STD_OPT1', 'EST_DLREMAJGTR_ESFD2550', '${DFILP}/${ENV_PREFIX}_ESFD2550_I17G_LCC_RPO_STD_DLREMAJGTRSII_${TYPEINV}_${PARM_ICLODAT_D}.dat', 'I', ' ' )
			INSERT INTO BEST..TI17PERMFIL VALUES ( 'I17G_LCC_RPO_STD_OPT1', 'EST_DLREMAJGTR_ESFD2650', '${DFILP}/${ENV_PREFIX}_ESFD2650_I17G_LCC_RPO_STD_OPT1_DLREMAJGTRSII_${TYPEINV}_${PARM_ICLODAT_D}.dat', 'O', ' ' )
			
			INSERT INTO BEST..TI17PERMFIL VALUES ( 'I17G_LCC_RPO_STD_OPT1', 'EST_DLRGTAA_ESFD2550', '${DFILP}/${ENV_PREFIX}_ESFD2550_I17G_LCC_RPO_STD_DLRGTAASII_${TYPEINV}_${PARM_ICLODAT_D}.dat', 'I', ' ' )
			INSERT INTO BEST..TI17PERMFIL VALUES ( 'I17G_LCC_RPO_STD_OPT1', 'EST_DLRGTAA_ESFD2650', '${DFILP}/${ENV_PREFIX}_ESFD2650_I17G_LCC_RPO_STD_OPT1_DLRGTAASII_${TYPEINV}_${PARM_ICLODAT_D}.dat', 'O', ' ' )
			
			INSERT INTO BEST..TI17PERMFIL values ('I17G_LCC_RPO_STD_OPT1',  'EST_DLDGTAA_ESFD2550','${DFILP}/${ENV_PREFIX}_ESFD2550_I17G_LCC_RPO_STD_DLDGTAA3780_3890SII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			INSERT INTO BEST..TI17PERMFIL values ('I17G_LCC_RPO_STD_OPT1',  'EST_DLDGTAA_ESFD2650','${DFILP}/${ENV_PREFIX}_ESFD2650_I17G_LCC_RPO_STD_OPT_DLDGTAA3780_3890SII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
	
		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17GMINV',  'I17G_LCC_RPO_STD_OPT1','')
			insert into BEST..TI17REQFNC values ('I17GQINV',  'I17G_LCC_RPO_STD_OPT1','')
			insert into BEST..TI17REQFNC values ('I17GQPOS',  'I17G_LCC_RPO_STD_OPT1','')
			insert into BEST..TI17REQFNC values ('I17GYINV',  'I17G_LCC_RPO_STD_OPT1','')
			insert into BEST..TI17REQFNC values ('I17GYPOS',  'I17G_LCC_RPO_STD_OPT1','')

go	

