-------------------------------
--mapping of  ESFD3920 

	----------   Clean tables   ---------------------

	delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD3920')
	delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD3920')
	delete BEST..TI17FNC where CHAIN_CT='ESFD3920'
	delete BEST..TI17CHN  where CHAIN_CT='ESFD3920'

	insert into BEST..TI17CHN values ('ESFD3920',  'NDIC assume calculation')

	----------IDF_CT:   EBS_ESFD3920 ------------------

		insert into BEST..TI17FNC values ('EBS_ESFD3920','EBS - NDIC STD assume calculation','ESFD3920',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('EBS_ESFD3920',  'EST_FTHRHLDUWY','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTHRHLDUWY.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD3920',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD3920',  'EPO_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURQUOT_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD3920',  'ESF_NDIC_NCB','${DFILP}/${ENV_PREFIX}_ESPD0060_NDIC_NCB_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD3920',  'EST_DLCUMGTAAR','${DFILP}/${ENV_PREFIX}_ESFD4020_DLCUMGTAAR_ITD_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD3920',  'EST_NDIC_FLOARAT','${DFILP}/${ENV_PREFIX}_ESFD2220_NDIC_FLOARAT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD3920',  'EST_IADPERICASE_EBS','${DFILP}/${ENV_PREFIX}_ESFD5040_IADPERICASE_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD3920',  'ESF_GTSII_GLOBAL_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESPD3610_GTSII_GLOBAL_CASHFLOW_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD3920',  'ESF_DLSGTAA','${DFILP}/${ENV_PREFIX}_ESPD1800_I17G_AET_RPO_I17_DLSGTAASII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD3920',  'EST_DLCUMGTAAR_PREV','${DFILP}/${ENV_PREFIX}_ESFD4020_DLCUMGTAAR_ITD_EBS_POS_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD3920',  'ESF_GTSII_GLOBAL_CASHFLOW_PREV','${DFILP}/${ENV_PREFIX}_ESPD3610_GTSII_GLOBAL_CASHFLOW_EBS_POS_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD3920',  'EST_ACC_NDIC_AMOUNT','${DFILP}/${ENV_PREFIX}_ESFD3920_NDC_ALL_STD_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD3920',  'EST_IADPERICASE','${DFILI}/${ENV_PREFIX}_ESFD3920_IADPERICASE_STD_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD3920',  'EST_IADPERICASE_FILTERED','${DFILI}/${ENV_PREFIX}_ESFD3920_IADPERICASE_FILTERED_STD_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD3920',  'ESF_DLSGTAA_FILTERED','${DFILI}/${ENV_PREFIX}_ESFD3920_EBS_DLSGTAA_FILTERED_I17G_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('EBSEMINV',  'EBS_ESFD3920','')
			insert into BEST..TI17REQFNC values ('EBSEQINV',  'EBS_ESFD3920','')
			insert into BEST..TI17REQFNC values ('EBSEQPOS',  'EBS_ESFD3920','')
			insert into BEST..TI17REQFNC values ('EBSEYINV',  'EBS_ESFD3920','')
			insert into BEST..TI17REQFNC values ('EBSEYPOS',  'EBS_ESFD3920','')

	----------IDF_CT:   I17G_ESFD3920 ------------------

		insert into BEST..TI17FNC values ('I17G_ESFD3920','I17G - NDIC STD assume calculation','ESFD3920',0)
					

		----------  Perms---------------------
			insert into BEST..TI17PERMFIL values ('I17G_ESFD3920',  'ESF_DLSGTAA','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD3920',  'EST_FTHRHLDUWY','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTHRHLDUWY.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD3920',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD3920',  'EPO_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD3920',  'ESF_NDIC_NCB','${DFILP}/${ENV_PREFIX}_ESPD0060_NDIC_NCB_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD3920',  'EST_DLCUMGTAAR','${DFILP}/${ENV_PREFIX}_ESFD4020_DLCUMGTAAR_ITD_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD3920',  'EST_NDIC_FLOARAT','${DFILP}/${ENV_PREFIX}_ESFD2220_NDIC_FLOARAT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD3920',  'EST_IADPERICASE_EBS','${DFILP}/${ENV_PREFIX}_ESFD5040_IADPERICASE_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD3920',  'ESF_GTSII_GLOBAL_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESPD3610_GTSII_GLOBAL_CASHFLOW_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD3920',  'EST_DLCUMGTAAR_PREV','${DFILP}/${ENV_PREFIX}_ESFD4020_DLCUMGTAAR_ITD_EBS_POS_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD3920',  'ESF_GTSII_GLOBAL_CASHFLOW_PREV','${DFILP}/${ENV_PREFIX}_ESPD3610_GTSII_GLOBAL_CASHFLOW_EBS_POS_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD3920',  'EST_ACC_NDIC_AMOUNT','${DFILP}/${ENV_PREFIX}_ESFD3920_NDC_ALL_STD_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD3920',  'EST_IADPERICASE','${DFILI}/${ENV_PREFIX}_ESFD3920_IADPERICASE_STD_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD3920',  'EST_IADPERICASE_FILTERED','${DFILI}/${ENV_PREFIX}_ESFD3920_IADPERICASE_FILTERED_STD_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD3920',  'ESF_DLSGTAA_FILTERED','${DFILI}/${ENV_PREFIX}_ESFD3920_I17G_DLSGTAA_FILTERED_I17G_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17GMINV',  'I17G_ESFD3920','')
			insert into BEST..TI17REQFNC values ('I17GQINV',  'I17G_ESFD3920','')
			insert into BEST..TI17REQFNC values ('I17GQPOS',  'I17G_ESFD3920','')
			insert into BEST..TI17REQFNC values ('I17GYINV',  'I17G_ESFD3920','')
			insert into BEST..TI17REQFNC values ('I17GYPOS',  'I17G_ESFD3920','')

	----------IDF_CT:   I17G_NDC_ALL_INI ------------------

		insert into BEST..TI17FNC values ('I17G_NDC_ALL_INI','IFRS17 Group - NDIC assume calculation','ESFD3920',0)
					

		----------  Perms---------------------
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_INI',  'ESF_DLSGTAA','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_INI',  'EST_DLCUMGTAAR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_INI',  'EST_FTHRHLDUWY','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTHRHLDUWY.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_INI',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_INI',  'EPO_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_INI',  'ESF_NDIC_NCB','${DFILP}/${ENV_PREFIX}_ESPD0060_NDIC_NCB_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_INI',  'EST_NDIC_FLOARAT','${DFILP}/${ENV_PREFIX}_ESFD2220_NDIC_INI_FLOARAT${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_INI',  'EST_IADPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17G_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_INI',  'ESF_GTSII_GLOBAL_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESFD3610_I17G_CSF_ALL_INI_GTSII_GLOBAL_CASHFLOW${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_INI',  'EST_DLCUMGTAAR_PREV','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_INI',  'ESF_GTSII_GLOBAL_CASHFLOW_PREV','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_INI',  'EST_ACC_NDIC_AMOUNT','${DFILP}/${ENV_PREFIX}_ESFD3920_I17G_NDC_ALL_INI_NDIC_ACCOUNT_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_INI',  'EST_IADPERICASE_FILTERED','${DFILI}/${ENV_PREFIX}_ESFD3920_IADPERICASE_FILTERED_I17G_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_INI',  'ESF_DLSGTAA_FILTERED','${DFILI}/${ENV_PREFIX}_ESFD3920_I17G_NDC_ALL_INI_DLSGTAA_FILTERED_I17G_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17GMINV',  'I17G_NDC_ALL_INI','')
			insert into BEST..TI17REQFNC values ('I17GQINV',  'I17G_NDC_ALL_INI','')
			insert into BEST..TI17REQFNC values ('I17GQPOS',  'I17G_NDC_ALL_INI','')
			insert into BEST..TI17REQFNC values ('I17GYINV',  'I17G_NDC_ALL_INI','')
			insert into BEST..TI17REQFNC values ('I17GYPOS',  'I17G_NDC_ALL_INI','')

	----------IDF_CT:   I17G_NDC_ALL_STD_AA0 ------------------

		insert into BEST..TI17FNC values ('I17G_NDC_ALL_STD_AA0','MicroAOC NDIC AA0','ESFD3920',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA0',  'ESF_DLSGTAA','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA0',  'EST_FTHRHLDUWY','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTHRHLDUWY.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA0',  'EPO_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURQUOT_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA0',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA0',  'EST_IADPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_IADPERICASE_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA0',  'ESF_NDIC_NCB','${DFILP}/${ENV_PREFIX}_ESPD0060_NDIC_NCB_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA0',  'EST_DLCUMGTAAR','${DFILP}/${ENV_PREFIX}_ESFD4020_DLCUMGTAAR_ITD_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA0',  'EST_IADPERICASE_EBS','${DFILP}/${ENV_PREFIX}_ESFD5040_IADPERICASE_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA0',  'EST_DLDGTAASIISO','${DFILP}/${ENV_PREFIX}_ESFD2230_I17G_ESFD2230___${TYPEAOC_CT}_DLDGTAASII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA0',  'EST_NDIC_FLOARAT','${DFILP}/${ENV_PREFIX}_ESFD2230_I17G_ESFD2230___${TYPEAOC_CT}_NDIC_FLOARAT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA0',  'ESF_GTSII_GLOBAL_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESFD3610_I17G_ESFD3610___AA0_GTSII_GLOBAL_CASHFLOW${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA0',  'EST_DLCUMGTAAR_PREV','${DFILP}/${ENV_PREFIX}_ESFD4020_DLCUMGTAAR_ITD_EBS_POS_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA0',  'ESF_GTSII_GLOBAL_CASHFLOW_PREV','${DFILP}/${ENV_PREFIX}_ESFD3610_I17G_ESFD3610___AA0_GTSII_GLOBAL_CASHFLOWPOS_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA0',  'EST_ACC_NDIC_AMOUNT','${DFILP}/${ENV_PREFIX}_ESFD3920_I17G_NDC_ALL_STD_AA0_NDIC_ACCOUNT_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA0',  'EST_IADPERICASE_FILTERED','${DFILI}/${ENV_PREFIX}_ESFD3920_I17G_NDC_ALL_STD_AA0_IADPERICASE_FILTERED_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA0',  'ESF_DLSGTAA_FILTERED','${DFILI}/${ENV_PREFIX}_ESFD3920_I17G_NDC_ALL_STD_AA0_DLSGTAA_FILTERED_I17G_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('POSO',  'I17G_NDC_ALL_STD_AA0','POSO')
			insert into BEST..TI17REQFNC values ('INVO',  'I17G_NDC_ALL_STD_AA0','INVO')
			insert into BEST..TI17REQFNC values ('POCO',  'I17G_NDC_ALL_STD_AA0','POCO')

	----------IDF_CT:   I17G_NDC_ALL_STD_AA1 ------------------

		insert into BEST..TI17FNC values ('I17G_NDC_ALL_STD_AA1','MicroAOC NDIC AA1','ESFD3920',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA1',  'ESF_DLSGTAA','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA1',  'EST_FTHRHLDUWY','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTHRHLDUWY.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA1',  'EPO_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURQUOT_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA1',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA1',  'EST_IADPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_IADPERICASE_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA1',  'ESF_NDIC_NCB','${DFILP}/${ENV_PREFIX}_ESPD0060_NDIC_NCB_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA1',  'EST_DLCUMGTAAR','${DFILP}/${ENV_PREFIX}_ESFD4020_DLCUMGTAAR_ITD_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA1',  'EST_IADPERICASE_EBS','${DFILP}/${ENV_PREFIX}_ESFD5040_IADPERICASE_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA1',  'EST_DLDGTAASIISO','${DFILP}/${ENV_PREFIX}_ESFD2230_I17G_ESFD2230___${TYPEAOC_CT}_DLDGTAASII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA1',  'EST_NDIC_FLOARAT','${DFILP}/${ENV_PREFIX}_ESFD2230_I17G_ESFD2230___${TYPEAOC_CT}_NDIC_FLOARAT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA1',  'ESF_GTSII_GLOBAL_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESFD3610_I17G_ESFD3610___AA1_GTSII_GLOBAL_CASHFLOW${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA1',  'EST_DLCUMGTAAR_PREV','${DFILP}/${ENV_PREFIX}_ESFD4020_DLCUMGTAAR_ITD_EBS_POS_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA1',  'ESF_GTSII_GLOBAL_CASHFLOW_PREV','${DFILP}/${ENV_PREFIX}_ESFD3610_I17G_ESFD3610___AA1_GTSII_GLOBAL_CASHFLOWPOS_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA1',  'EST_ACC_NDIC_AMOUNT','${DFILP}/${ENV_PREFIX}_ESFD3920_I17G_NDC_ALL_STD_AA1_NDIC_ACCOUNT_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA1',  'EST_IADPERICASE_FILTERED','${DFILI}/${ENV_PREFIX}_ESFD3920_I17G_NDC_ALL_STD_AA1_IADPERICASE_FILTERED_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA1',  'ESF_DLSGTAA_FILTERED','${DFILI}/${ENV_PREFIX}_ESFD3920_I17G_NDC_ALL_STD_AA1_DLSGTAA_FILTERED_I17G_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('INVO',  'I17G_NDC_ALL_STD_AA1','INVO')
			insert into BEST..TI17REQFNC values ('POCO',  'I17G_NDC_ALL_STD_AA1','POCO')
			insert into BEST..TI17REQFNC values ('POSO',  'I17G_NDC_ALL_STD_AA1','POSO')

	----------IDF_CT:   I17G_NDC_ALL_STD_AA2 ------------------

		insert into BEST..TI17FNC values ('I17G_NDC_ALL_STD_AA2','MicroAOC NDIC AA2','ESFD3920',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA2',  'ESF_DLSGTAA','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA2',  'EST_FTHRHLDUWY','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTHRHLDUWY.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA2',  'EPO_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURQUOT_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA2',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA2',  'EST_IADPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_IADPERICASE_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA2',  'ESF_NDIC_NCB','${DFILP}/${ENV_PREFIX}_ESPD0060_NDIC_NCB_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA2',  'EST_DLCUMGTAAR','${DFILP}/${ENV_PREFIX}_ESFD4020_DLCUMGTAAR_ITD_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA2',  'EST_IADPERICASE_EBS','${DFILP}/${ENV_PREFIX}_ESFD5040_IADPERICASE_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA2',  'EST_DLDGTAASIISO','${DFILP}/${ENV_PREFIX}_ESFD2230_I17G_ESFD2230___${TYPEAOC_CT}_DLDGTAASII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA2',  'EST_NDIC_FLOARAT','${DFILP}/${ENV_PREFIX}_ESFD2230_I17G_ESFD2230___${TYPEAOC_CT}_NDIC_FLOARAT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA2',  'ESF_GTSII_GLOBAL_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESFD3610_I17G_ESFD3610___AA2_GTSII_GLOBAL_CASHFLOW${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA2',  'EST_DLCUMGTAAR_PREV','${DFILP}/${ENV_PREFIX}_ESFD4020_DLCUMGTAAR_ITD_EBS_POS_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA2',  'ESF_GTSII_GLOBAL_CASHFLOW_PREV','${DFILP}/${ENV_PREFIX}_ESFD3610_I17G_ESFD3610___AA2_GTSII_GLOBAL_CASHFLOWPOS_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA2',  'EST_ACC_NDIC_AMOUNT','${DFILP}/${ENV_PREFIX}_ESFD3920_I17G_NDC_ALL_STD_AA2_NDIC_ACCOUNT_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA2',  'EST_IADPERICASE_FILTERED','${DFILI}/${ENV_PREFIX}_ESFD3920_I17G_NDC_ALL_STD_AA2_IADPERICASE_FILTERED_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA2',  'ESF_DLSGTAA_FILTERED','${DFILI}/${ENV_PREFIX}_ESFD3920_I17G_NDC_ALL_STD_AA2_DLSGTAA_FILTERED_I17G_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('INVO',  'I17G_NDC_ALL_STD_AA2','INVO')
			insert into BEST..TI17REQFNC values ('POCO',  'I17G_NDC_ALL_STD_AA2','POCO')
			insert into BEST..TI17REQFNC values ('POSO',  'I17G_NDC_ALL_STD_AA2','POSO')

	----------IDF_CT:   I17G_NDC_ALL_STD_AA3 ------------------

		insert into BEST..TI17FNC values ('I17G_NDC_ALL_STD_AA3','MicroAOC NDIC AA3','ESFD3920',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA3',  'ESF_DLSGTAA','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA3',  'EST_FTHRHLDUWY','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTHRHLDUWY.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA3',  'EPO_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURQUOT_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA3',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA3',  'EST_IADPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_IADPERICASE_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA3',  'ESF_NDIC_NCB','${DFILP}/${ENV_PREFIX}_ESPD0060_NDIC_NCB_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA3',  'EST_DLCUMGTAAR','${DFILP}/${ENV_PREFIX}_ESFD4020_DLCUMGTAAR_ITD_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA3',  'EST_IADPERICASE_EBS','${DFILP}/${ENV_PREFIX}_ESFD5040_IADPERICASE_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA3',  'EST_DLDGTAASIISO','${DFILP}/${ENV_PREFIX}_ESFD2230_I17G_ESFD2230___${TYPEAOC_CT}_DLDGTAASII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA3',  'EST_NDIC_FLOARAT','${DFILP}/${ENV_PREFIX}_ESFD2230_I17G_ESFD2230___${TYPEAOC_CT}_NDIC_FLOARAT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA3',  'ESF_GTSII_GLOBAL_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESFD3610_I17G_ESFD3610___AA3_GTSII_GLOBAL_CASHFLOW${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA3',  'EST_DLCUMGTAAR_PREV','${DFILP}/${ENV_PREFIX}_ESFD4020_DLCUMGTAAR_ITD_EBS_POS_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA3',  'ESF_GTSII_GLOBAL_CASHFLOW_PREV','${DFILP}/${ENV_PREFIX}_ESFD3610_I17G_ESFD3610___AA3_GTSII_GLOBAL_CASHFLOWPOS_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA3',  'EST_ACC_NDIC_AMOUNT','${DFILP}/${ENV_PREFIX}_ESFD3920_I17G_NDC_ALL_STD_AA3_NDIC_ACCOUNT_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA3',  'EST_IADPERICASE_FILTERED','${DFILI}/${ENV_PREFIX}_ESFD3920_I17G_NDC_ALL_STD_AA3_IADPERICASE_FILTERED_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_NDC_ALL_STD_AA3',  'ESF_DLSGTAA_FILTERED','${DFILI}/${ENV_PREFIX}_ESFD3920_I17G_NDC_ALL_STD_AA3_DLSGTAA_FILTERED_I17G_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('INVO',  'I17G_NDC_ALL_STD_AA3','INVO')
			insert into BEST..TI17REQFNC values ('POCO',  'I17G_NDC_ALL_STD_AA3','POCO')
			insert into BEST..TI17REQFNC values ('POSO',  'I17G_NDC_ALL_STD_AA3','POSO')

	----------IDF_CT:   I17L_NDC_ALL_INI ------------------

		insert into BEST..TI17FNC values ('I17L_NDC_ALL_INI','IFRS17 Local - NDIC assume calculation','ESFD3920',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17L_NDC_ALL_INI',  'ESF_DLSGTAA','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_NDC_ALL_INI',  'EST_DLCUMGTAAR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_NDC_ALL_INI',  'EST_FTHRHLDUWY','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTHRHLDUWY.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_NDC_ALL_INI',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_NDC_ALL_INI',  'EPO_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_NDC_ALL_INI',  'ESF_NDIC_NCB','${DFILP}/${ENV_PREFIX}_ESPD0060_NDIC_NCB_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_NDC_ALL_INI',  'EST_IADPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17L_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_NDC_ALL_INI',  'EST_NDIC_FLOARAT','${DFILP}/${ENV_PREFIX}_ESFD2220_I17L_NDIC_INI_FLOARAT${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_NDC_ALL_INI',  'ESF_GTSII_GLOBAL_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESFD3610_I17L_CSF_ALL_INI_GTSII_GLOBAL_CASHFLOW${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_NDC_ALL_INI',  'EST_DLCUMGTAAR_PREV','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_NDC_ALL_INI',  'ESF_GTSII_GLOBAL_CASHFLOW_PREV','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_NDC_ALL_INI',  'EST_ACC_NDIC_AMOUNT','${DFILP}/${ENV_PREFIX}_ESFD3920_I17L_NDC_ALL_INI_NDIC_ACCOUNT_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_NDC_ALL_INI',  'EST_IADPERICASE_FILTERED','${DFILI}/${ENV_PREFIX}_ESFD3920_IADPERICASE_FILTERED_I17L_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_NDC_ALL_INI',  'ESF_DLSGTAA_FILTERED','${DFILI}/${ENV_PREFIX}_ESFD3920_I17L_NDC_ALL_INI_DLSGTAA_FILTERED_I17L_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17LMINV',  'I17L_NDC_ALL_INI','')
			insert into BEST..TI17REQFNC values ('I17LQINV',  'I17L_NDC_ALL_INI','')
			insert into BEST..TI17REQFNC values ('I17LQPOS',  'I17L_NDC_ALL_INI','')
			insert into BEST..TI17REQFNC values ('I17LYINV',  'I17L_NDC_ALL_INI','')
			insert into BEST..TI17REQFNC values ('I17LYPOS',  'I17L_NDC_ALL_INI','')

	----------IDF_CT:   I17P_NDC_ALL_INI ------------------

		insert into BEST..TI17FNC values ('I17P_NDC_ALL_INI','IFRS17 Parent - NDIC assume calculation','ESFD3920',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17P_NDC_ALL_INI',  'ESF_DLSGTAA','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_NDC_ALL_INI',  'EST_DLCUMGTAAR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_NDC_ALL_INI',  'EST_FTHRHLDUWY','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTHRHLDUWY.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_NDC_ALL_INI',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_NDC_ALL_INI',  'EPO_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_NDC_ALL_INI',  'ESF_NDIC_NCB','${DFILP}/${ENV_PREFIX}_ESPD0060_NDIC_NCB_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_NDC_ALL_INI',  'EST_IADPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17P_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_NDC_ALL_INI',  'EST_NDIC_FLOARAT','${DFILP}/${ENV_PREFIX}_ESFD2220_I17P_NDIC_INI_FLOARAT${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_NDC_ALL_INI',  'ESF_GTSII_GLOBAL_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESFD3610_I17P_CSF_ALL_INI_GTSII_GLOBAL_CASHFLOW${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_NDC_ALL_INI',  'EST_DLCUMGTAAR_PREV','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_NDC_ALL_INI',  'ESF_GTSII_GLOBAL_CASHFLOW_PREV','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_NDC_ALL_INI',  'EST_ACC_NDIC_AMOUNT','${DFILP}/${ENV_PREFIX}_ESFD3920_I17P_NDC_ALL_INI_NDIC_ACCOUNT_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_NDC_ALL_INI',  'EST_IADPERICASE_FILTERED','${DFILI}/${ENV_PREFIX}_ESFD3920_IADPERICASE_FILTERED_I17P_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_NDC_ALL_INI',  'ESF_DLSGTAA_FILTERED','${DFILI}/${ENV_PREFIX}_ESFD3920_I17P_NDC_ALL_INI_DLSGTAA_FILTERED_I17P_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17PYPOS',  'I17P_NDC_ALL_INI','')
			insert into BEST..TI17REQFNC values ('I17PMINV',  'I17P_NDC_ALL_INI','')
			insert into BEST..TI17REQFNC values ('I17PQINV',  'I17P_NDC_ALL_INI','')
			insert into BEST..TI17REQFNC values ('I17PQPOS',  'I17P_NDC_ALL_INI','')
			insert into BEST..TI17REQFNC values ('I17PYINV',  'I17P_NDC_ALL_INI','')

	----------IDF_CT:   I17S_ESFD3920 ------------------

		insert into BEST..TI17FNC values ('I17S_ESFD3920','I17G - NDIC STD assume calculation','ESFD3920',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17S_ESFD3920',  'ESF_DLSGTAA','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD3920',  'EST_FTHRHLDUWY','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTHRHLDUWY.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD3920',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD3920',  'EPO_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD3920',  'ESF_NDIC_NCB','${DFILP}/${ENV_PREFIX}_ESPD0060_NDIC_NCB_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD3920',  'EST_DLCUMGTAAR','${DFILP}/${ENV_PREFIX}_ESFD4020_DLCUMGTAAR_ITD_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD3920',  'EST_NDIC_FLOARAT','${DFILP}/${ENV_PREFIX}_ESFD2220_NDIC_FLOARAT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD3920',  'EST_IADPERICASE_EBS','${DFILP}/${ENV_PREFIX}_ESFD5040_IADPERICASE_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD3920',  'ESF_GTSII_GLOBAL_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESPD3610_GTSII_GLOBAL_CASHFLOW_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD3920',  'EST_DLCUMGTAAR_PREV','${DFILP}/${ENV_PREFIX}_ESFD4020_DLCUMGTAAR_ITD_EBS_POS_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD3920',  'ESF_GTSII_GLOBAL_CASHFLOW_PREV','${DFILP}/${ENV_PREFIX}_ESPD3610_GTSII_GLOBAL_CASHFLOW_EBS_POS_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD3920',  'EST_ACC_NDIC_AMOUNT','${DFILP}/${ENV_PREFIX}_ESFD3920_NDC_ALL_STD_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD3920',  'EST_IADPERICASE','${DFILI}/${ENV_PREFIX}_ESFD3920_IADPERICASE_STD_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD3920',  'EST_IADPERICASE_FILTERED','${DFILI}/${ENV_PREFIX}_ESFD3920_IADPERICASE_FILTERED_STD_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD3920',  'ESF_DLSGTAA_FILTERED','${DFILI}/${ENV_PREFIX}_ESFD3920_I17S_DLSGTAA_FILTERED_I17S_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17SMINV',  'I17S_ESFD3920','')
			insert into BEST..TI17REQFNC values ('I17SQINV',  'I17S_ESFD3920','')
			insert into BEST..TI17REQFNC values ('I17SQPOS',  'I17S_ESFD3920','')
			insert into BEST..TI17REQFNC values ('I17SYINV',  'I17S_ESFD3920','')
			insert into BEST..TI17REQFNC values ('I17SYPOS',  'I17S_ESFD3920','')

	----------IDF_CT:   I17S_NDC_ALL_INI ------------------

		insert into BEST..TI17FNC values ('I17S_NDC_ALL_INI','IFRS17 Simulation - NDIC assume calculation','ESFD3920',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_INI',  'ESF_DLSGTAA','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_INI',  'EST_DLCUMGTAAR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_INI',  'EST_FTHRHLDUWY','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTHRHLDUWY.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_INI',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_INI',  'EPO_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_INI',  'ESF_NDIC_NCB','${DFILP}/${ENV_PREFIX}_ESPD0060_NDIC_NCB_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_INI',  'EST_NDIC_FLOARAT','${DFILP}/${ENV_PREFIX}_ESFD2220_NDIC_INI_FLOARAT${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_INI',  'EST_IADPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17S_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_INI',  'ESF_GTSII_GLOBAL_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESFD3610_I17S_CSF_ALL_INI_GTSII_GLOBAL_CASHFLOW${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_INI',  'EST_DLCUMGTAAR_PREV','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_INI',  'ESF_GTSII_GLOBAL_CASHFLOW_PREV','${DFILP}/empty.datt','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_INI',  'EST_ACC_NDIC_AMOUNT','${DFILP}/${ENV_PREFIX}_ESFD3920_I17S_NDC_ALL_INI_NDIC_ACCOUNT_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_INI',  'EST_IADPERICASE_FILTERED','${DFILI}/${ENV_PREFIX}_ESFD3920_IADPERICASE_FILTERED_I17S_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_INI',  'ESF_DLSGTAA_FILTERED','${DFILI}/${ENV_PREFIX}_ESFD3920_I17S_NDC_ALL_INI_DLSGTAA_FILTERED_I17S_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17SMINV',  'I17S_NDC_ALL_INI','')
			insert into BEST..TI17REQFNC values ('I17SQINV',  'I17S_NDC_ALL_INI','')
			insert into BEST..TI17REQFNC values ('I17SQPOS',  'I17S_NDC_ALL_INI','')
			insert into BEST..TI17REQFNC values ('I17SYINV',  'I17S_NDC_ALL_INI','')
			insert into BEST..TI17REQFNC values ('I17SYPOS',  'I17S_NDC_ALL_INI','')

	----------IDF_CT:   I17S_NDC_ALL_STD_AA0 ------------------

		insert into BEST..TI17FNC values ('I17S_NDC_ALL_STD_AA0','MicroAOC NDIC AA0','ESFD3920',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_STD_AA0',  'ESF_DLSGTAA','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_STD_AA0',  'EST_FTHRHLDUWY','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTHRHLDUWY.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_STD_AA0',  'EPO_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURQUOT_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_STD_AA0',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_STD_AA0',  'EST_IADPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_IADPERICASE_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_STD_AA0',  'ESF_NDIC_NCB','${DFILP}/${ENV_PREFIX}_ESPD0060_NDIC_NCB_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_STD_AA0',  'EST_DLCUMGTAAR','${DFILP}/${ENV_PREFIX}_ESFD4020_DLCUMGTAAR_ITD_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_STD_AA0',  'EST_DLDGTAASIISO','${DFILP}/${ENV_PREFIX}_ESFD2220_I17S_ESFD2220___${TYPEAOC_CT}_DLDGTAASII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_STD_AA0',  'EST_NDIC_FLOARAT','${DFILP}/${ENV_PREFIX}_ESFD2220_I17S_ESFD2220___${TYPEAOC_CT}_NDIC_FLOARAT${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_STD_AA0',  'EST_ACC_NDIC_AMOUNT','${DFILP}/${ENV_PREFIX}_ESFD3920_I17S_NDC_ALL_STD_AA0_NDIC_ACCOUNT_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_STD_AA0',  'EST_IADPERICASE_FILTERED','${DFILI}/${ENV_PREFIX}_ESFD3920_I17S_NDC_ALL_STD_AA0_IADPERICASE_FILTERED_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_STD_AA0',  'ESF_DLSGTAA_FILTERED','${DFILI}/${ENV_PREFIX}_ESFD3920_I17S_NDC_ALL_STD_AA0_DLSGTAA_FILTERED_I17S_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------


	----------IDF_CT:   I17S_NDC_ALL_STD_AA1 ------------------

		insert into BEST..TI17FNC values ('I17S_NDC_ALL_STD_AA1','MicroAOC NDIC AA1','ESFD3920',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_STD_AA1',  'ESF_DLSGTAA','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_STD_AA1',  'EST_FTHRHLDUWY','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTHRHLDUWY.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_STD_AA1',  'EPO_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURQUOT_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_STD_AA1',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_STD_AA1',  'EST_IADPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_IADPERICASE_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_STD_AA1',  'ESF_NDIC_NCB','${DFILP}/${ENV_PREFIX}_ESPD0060_NDIC_NCB_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_STD_AA1',  'EST_DLCUMGTAAR','${DFILP}/${ENV_PREFIX}_ESFD4020_DLCUMGTAAR_ITD_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_STD_AA1',  'EST_DLDGTAASIISO','${DFILP}/${ENV_PREFIX}_ESFD2220_I17S_ESFD2220___${TYPEAOC_CT}_DLDGTAASII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_STD_AA1',  'EST_NDIC_FLOARAT','${DFILP}/${ENV_PREFIX}_ESFD2220_I17S_ESFD2220___${TYPEAOC_CT}_NDIC_FLOARAT${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_STD_AA1',  'EST_ACC_NDIC_AMOUNT','${DFILP}/${ENV_PREFIX}_ESFD3920_I17S_NDC_ALL_STD_AA1_NDIC_ACCOUNT_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_STD_AA1',  'EST_IADPERICASE_FILTERED','${DFILI}/${ENV_PREFIX}_ESFD3920_I17S_NDC_ALL_STD_AA1_IADPERICASE_FILTERED_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_STD_AA1',  'ESF_DLSGTAA_FILTERED','${DFILI}/${ENV_PREFIX}_ESFD3920_I17S_NDC_ALL_STD_AA1_DLSGTAA_FILTERED_I17S_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------


	----------IDF_CT:   I17S_NDC_ALL_STD_AA2 ------------------

		insert into BEST..TI17FNC values ('I17S_NDC_ALL_STD_AA2','MicroAOC NDIC AA2','ESFD3920',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_STD_AA2',  'ESF_DLSGTAA','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_STD_AA2',  'EST_FTHRHLDUWY','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTHRHLDUWY.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_STD_AA2',  'EPO_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURQUOT_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_STD_AA2',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_STD_AA2',  'EST_IADPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_IADPERICASE_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_STD_AA2',  'ESF_NDIC_NCB','${DFILP}/${ENV_PREFIX}_ESPD0060_NDIC_NCB_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_STD_AA2',  'EST_DLCUMGTAAR','${DFILP}/${ENV_PREFIX}_ESFD4020_DLCUMGTAAR_ITD_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_STD_AA2',  'EST_DLDGTAASIISO','${DFILP}/${ENV_PREFIX}_ESFD2220_I17S_ESFD2220___${TYPEAOC_CT}_DLDGTAASII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_STD_AA2',  'EST_NDIC_FLOARAT','${DFILP}/${ENV_PREFIX}_ESFD2220_I17S_ESFD2220___${TYPEAOC_CT}_NDIC_FLOARAT${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_STD_AA2',  'EST_ACC_NDIC_AMOUNT','${DFILP}/${ENV_PREFIX}_ESFD3920_I17S_NDC_ALL_STD_AA2_NDIC_ACCOUNT_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_STD_AA2',  'EST_IADPERICASE_FILTERED','${DFILI}/${ENV_PREFIX}_ESFD3920_I17S_NDC_ALL_STD_AA2_IADPERICASE_FILTERED_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_STD_AA2',  'ESF_DLSGTAA_FILTERED','${DFILI}/${ENV_PREFIX}_ESFD3920_I17S_NDC_ALL_STD_AA2_DLSGTAA_FILTERED_I17S_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------


	----------IDF_CT:   I17S_NDC_ALL_STD_AA3 ------------------

		insert into BEST..TI17FNC values ('I17S_NDC_ALL_STD_AA3','MicroAOC NDIC AA3','ESFD3920',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_STD_AA3',  'ESF_DLSGTAA','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_STD_AA3',  'EST_FTHRHLDUWY','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTHRHLDUWY.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_STD_AA3',  'EPO_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURQUOT_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_STD_AA3',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_STD_AA3',  'EST_IADPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_IADPERICASE_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_STD_AA3',  'ESF_NDIC_NCB','${DFILP}/${ENV_PREFIX}_ESPD0060_NDIC_NCB_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_STD_AA3',  'EST_DLCUMGTAAR','${DFILP}/${ENV_PREFIX}_ESFD4020_DLCUMGTAAR_ITD_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_STD_AA3',  'EST_DLDGTAASIISO','${DFILP}/${ENV_PREFIX}_ESFD2220_I17S_ESFD2220___${TYPEAOC_CT}_DLDGTAASII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_STD_AA3',  'EST_NDIC_FLOARAT','${DFILP}/${ENV_PREFIX}_ESFD2220_I17S_ESFD2220___${TYPEAOC_CT}_NDIC_FLOARAT${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_STD_AA3',  'EST_ACC_NDIC_AMOUNT','${DFILP}/${ENV_PREFIX}_ESFD3920_I17S_NDC_ALL_STD_AA3_NDIC_ACCOUNT_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_STD_AA3',  'EST_IADPERICASE_FILTERED','${DFILI}/${ENV_PREFIX}_ESFD3920_I17S_NDC_ALL_STD_AA3_IADPERICASE_FILTERED_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_NDC_ALL_STD_AA3',  'ESF_DLSGTAA_FILTERED','${DFILI}/${ENV_PREFIX}_ESFD3920_I17S_NDC_ALL_STD_AA3_DLSGTAA_FILTERED_I17S_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

go

