-------------------------------
--mapping of  ESFD3870

	----------   Clean tables   ---------------------

	delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD3870')
	delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD3870')
	delete BEST..TI17FNC where CHAIN_CT='ESFD3870'
	delete BEST..TI17CHN  where CHAIN_CT='ESFD3870'

	insert into BEST..TI17CHN values ('ESFD3870',  'Merge of IFRS17 GLT files')

	----------IDF_CT:   I17G_GLT_ALL_INI ------------------

		insert into BEST..TI17FNC values ('I17G_GLT_ALL_INI','Merge of IFRS17 GLT files','ESFD3870',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_INI',  'ESF_DLRGTAASII','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_INI',  'ESF_FTECLEDA_AOC','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_INI',  'ESF_FTECLEDA_STD','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_INI',  'ESF_FTECLEDR_STD','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_INI',  'ESF_FTECLEDA_GAPMAP','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_INI',  'ESF_FTECLEDR_GAPMAP','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_INI',  'ESF_FTECLEDA_CSM_ACC','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_INI',  'ESF_FTECLEDR_CSM_ACC','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_INI',  'ESF_DLREGTRSII','${DFILP}/${ENV_PREFIX}_ESFD2550_I17G_LCC_RPO_INI_DLREGTRSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_INI',  'ESF_FTECLEDA_INI','${DFILP}/${ENV_PREFIX}_ESFD3740_I17G_SII_GLT_INI_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_INI',  'ESF_FTECLEDR_INI','${DFILP}/${ENV_PREFIX}_ESFD3740_I17G_SII_GLT_INI_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_INI',  'ESF_DLREGTARSII','${DFILP}/${ENV_PREFIX}_ESFD2550_I17G_LCC_RPO_INI_DLREGTARSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_INI',  'ESF_DLRGTAA_LCC_INI','${DFILP}/${ENV_PREFIX}_ESFD2550_I17G_LCC_RPO_INI_DLRGTAASII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_INI',  'ESF_IADPERICASE_DUMMY','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_DUMMY_I17G_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_INI',  'ESF_IADPERICASE_ONEFUT','${DFILP}/${ENV_PREFIX}_ESFD3740_I17G_SII_GLT_INI_IADPERICASE_ONEFUT_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_INI',  'ESF_IADPERICASE_PROFUT','${DFILP}/${ENV_PREFIX}_ESFD3740_I17G_SII_GLT_INI_IADPERICASE_PROFUT_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_INI',  'ESF_FPLATXCUMALL0','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLATXCUMALL0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')			
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_INI',  'ESF_FTECLEDA','${DFILP}/${ENV_PREFIX}_ESFD3870_I17G_GLT_ALL_INI_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_INI',  'ESF_FTECLEDR','${DFILP}/${ENV_PREFIX}_ESFD3870_I17G_GLT_ALL_INI_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17GMINV',  'I17G_GLT_ALL_INI','')
			insert into BEST..TI17REQFNC values ('I17GQINV',  'I17G_GLT_ALL_INI','')
			insert into BEST..TI17REQFNC values ('I17GQPOS',  'I17G_GLT_ALL_INI','')
			insert into BEST..TI17REQFNC values ('I17GYINV',  'I17G_GLT_ALL_INI','')
			insert into BEST..TI17REQFNC values ('I17GYPOS',  'I17G_GLT_ALL_INI','')

	----------IDF_CT:   I17G_GLT_ALL_STD ------------------

		insert into BEST..TI17FNC values ('I17G_GLT_ALL_STD','Merge of IFRS17 GLT files','ESFD3870',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_STD',  'ESF_DLRGTAA_LCC_INI','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_STD',  'EST_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_STD',  'ESF_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_STD',  'ESF_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_STD',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_STD',  'ESF_FTECLEDA_REJ','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDA_REJ_I17G.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_STD',  'ESF_FTECLEDR_REJ','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDR_REJ_I17G.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_STD',  'ESF_FTECLEDA_OPNG','${DFILP}/${ENV_PREFIX}_ESFD2900_FTECLEDA_OPNG_I17G.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_STD',  'ESF_FTECLEDR_OPNG','${DFILP}/${ENV_PREFIX}_ESFD2900_FTECLEDR_OPNG_I17G.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_STD',  'ESF_IRDPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE0_I17G_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_STD',  'ESF_TRERETFACCTR','${DFILP}/${ENV_PREFIX}_ESFD1130_TRERETFACCTR_I17G_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_STD',  'ESF_DLREGTRSII','${DFILP}/${ENV_PREFIX}_ESFD2550_I17G_LCC_RPO_STD_DLREGTRSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_STD',  'ESF_DLRGTAASII','${DFILP}/${ENV_PREFIX}_ESFD2550_I17G_LCC_RPO_STD_DLRGTAASII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_STD',  'ESF_FTECLEDA_AOC','${DFILP}/${ENV_PREFIX}_ESFD3890_I17G_GLT_AOC_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_STD',  'ESF_FTECLEDA_STD','${DFILP}/${ENV_PREFIX}_ESFD3740_I17G_SII_GLT_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_STD',  'ESF_FTECLEDR_STD','${DFILP}/${ENV_PREFIX}_ESFD3740_I17G_SII_GLT_STD_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_STD',  'ESF_FTECLEDA_3870','${DFILP}/${ENV_PREFIX}_ESFD3870_I17G_GLT_ALL_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_STD',  'ESF_DLREGTARSII','${DFILP}/${ENV_PREFIX}_ESFD2550_I17G_LCC_RPO_STD_DLREGTARSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_STD',  'ESF_FTECLEDA_GAPMAP','${DFILP}/${ENV_PREFIX}_ESFD4030_I17G_GAP_MAP_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_STD',  'ESF_FTECLEDR_GAPMAP','${DFILP}/${ENV_PREFIX}_ESFD4030_I17G_GAP_MAP_STD_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_STD',  'ESF_FTECLEDA_3870_PREV','${DFILP}/${ENV_PREFIX}_ESFD3870_I17G_GLT_ALL_STD_FTECLEDA_POS_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_STD',  'ESF_IADPERICASE_DUMMY','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_DUMMY_I17G_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_STD',  'ESF_IADPERICASE_DUMMY_INI','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_DUMMY_I17G_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')			
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_STD',  'ESF_FTECLEDA_CSM_ACC','${DFILP}/${ENV_PREFIX}_ESFD3780_I17G_CSM_ACC_STD_CSM_LC_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_STD',  'ESF_FTECLEDR_CSM_ACC','${DFILP}/${ENV_PREFIX}_ESFD3780_I17G_CSM_ACC_STD_CSM_LC_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_STD',  'ESF_IADVPERICASE','${DFILP}/${ENV_PREFIX}_ESPD1800_I17G_AET_RPO_I17_IADPERICASE_I17_MERGE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_STD',  'ESF_IADPERICASE_ONEFUT','${DFILP}/${ENV_PREFIX}_ESFD3740_I17G_SII_GLT_INI_IADPERICASE_ONEFUT_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_STD',  'ESF_IADPERICASE_PROFUT','${DFILP}/${ENV_PREFIX}_ESFD3740_I17G_SII_GLT_INI_IADPERICASE_PROFUT_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_STD',  'ESF_FTECLEDA_8700','${DFILP}/${ENV_PREFIX}_ESID8700_FTECLEDA_I4I_${PARM_ICLODAT_D}.dat','I','')	
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_STD',  'ESF_FTECLEDA_INI','${DFILP}/${ENV_PREFIX}_ESFD3870_I17G_GLT_ALL_INI_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_STD',  'ESF_IADPERICASE_DUMMY_MRG','${DFILP}/${ENV_PREFIX}_ESFD3870_IADPERICASE_DUMMY_I17G_MRG_${TYPEINV}_${PARM_ICLODAT_D}.dat','U','')									
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_STD',  'ESF_FTECLEDA','${DFILP}/${ENV_PREFIX}_ESFD3870_I17G_GLT_ALL_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_STD',  'ESF_FTECLEDR','${DFILP}/${ENV_PREFIX}_ESFD3870_I17G_GLT_ALL_STD_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_STD',  'ESF_FTECLEDR_INI','${DFILP}/${ENV_PREFIX}_ESFD3870_I17G_GLT_ALL_INI_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_STD',  'ESF_FCSM_ENDING_RNP','${DFILP}/${ENV_PREFIX}_ESFD3870_I17G_GLT_ALL_STD_FCSM_ENDING_RNP_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_STD',  'ESF_FCSM_LC_ENDING_ASS','${DFILP}/${ENV_PREFIX}_ESFD3870_I17G_GLT_ALL_STD_FCSM_LC_ENDING_ASS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_STD',  'ESF_FCSM_ENDING_RNP_ONLY','${DFILP}/${ENV_PREFIX}_ESFD3870_I17G_GLT_ALL_STD_FCSM_ENDING_RNP_ONLY_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_GLT_ALL_STD',  'ESF_FCSM_LC_ENDING_ASS_ONLY','${DFILP}/${ENV_PREFIX}_ESFD3870_I17G_GLT_ALL_STD_FCSM_LC_ENDING_ASS_ONLY_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17GQPOS',  'I17G_GLT_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17GYINV',  'I17G_GLT_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17GYPOS',  'I17G_GLT_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17GMINV',  'I17G_GLT_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17GQINV',  'I17G_GLT_ALL_STD','')

	----------IDF_CT:   I17L_GLT_ALL_INI ------------------

		insert into BEST..TI17FNC values ('I17L_GLT_ALL_INI','Merge of IFRS17 GLT files','ESFD3870',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_INI',  'ESF_DLRGTAASII','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_INI',  'ESF_FTECLEDA_AOC','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_INI',  'ESF_FTECLEDA_STD','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_INI',  'ESF_FTECLEDR_STD','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_INI',  'ESF_DLRGTAA_LCC_INI','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_INI',  'ESF_FTECLEDA_GAPMAP','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_INI',  'ESF_FTECLEDR_GAPMAP','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_INI',  'ESF_FTECLEDA_CSM_ACC','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_INI',  'ESF_FTECLEDR_CSM_ACC','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_INI',  'ESF_DLREGTRSII','${DFILP}/${ENV_PREFIX}_ESFD2550_I17L_LCC_RPO_INI_DLREGTRSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_INI',  'ESF_FTECLEDA_INI','${DFILP}/${ENV_PREFIX}_ESFD3740_I17L_SII_GLT_INI_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_INI',  'ESF_FTECLEDR_INI','${DFILP}/${ENV_PREFIX}_ESFD3740_I17L_SII_GLT_INI_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_INI',  'ESF_DLREGTARSII','${DFILP}/${ENV_PREFIX}_ESFD2550_I17L_LCC_RPO_INI_DLREGTARSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_INI',  'ESF_IADPERICASE_DUMMY','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_DUMMY_I17L_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_INI',  'ESF_IADPERICASE_ONEFUT','${DFILP}/${ENV_PREFIX}_ESFD3740_I17L_SII_GLT_INI_IADPERICASE_ONEFUT_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_INI',  'ESF_IADPERICASE_PROFUT','${DFILP}/${ENV_PREFIX}_ESFD3740_I17L_SII_GLT_INI_IADPERICASE_PROFUT_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_INI',  'ESF_FPLATXCUMALL0','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLATXCUMALL0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')	
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_INI',  'ESF_FTECLEDA','${DFILP}/${ENV_PREFIX}_ESFD3870_I17L_GLT_ALL_INI_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_INI',  'ESF_FTECLEDR','${DFILP}/${ENV_PREFIX}_ESFD3870_I17L_GLT_ALL_INI_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17LQINV',  'I17L_GLT_ALL_INI','')
			insert into BEST..TI17REQFNC values ('I17LQPOS',  'I17L_GLT_ALL_INI','')
			insert into BEST..TI17REQFNC values ('I17LYINV',  'I17L_GLT_ALL_INI','')
			insert into BEST..TI17REQFNC values ('I17LYPOS',  'I17L_GLT_ALL_INI','')
			insert into BEST..TI17REQFNC values ('I17LMINV',  'I17L_GLT_ALL_INI','')

	----------IDF_CT:   I17L_GLT_ALL_STD ------------------

		insert into BEST..TI17FNC values ('I17L_GLT_ALL_STD','Merge of IFRS17 GLT files','ESFD3870',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_STD',  'ESF_DLRGTAASII','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_STD',  'ESF_DLRGTAA_LCC_INI','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_STD',  'EST_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_STD',  'ESF_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_STD',  'ESF_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_STD',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_STD',  'ESF_FTECLEDA_REJ','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDA_REJ_I17L.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_STD',  'ESF_FTECLEDR_REJ','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDR_REJ_I17L.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_STD',  'ESF_FTECLEDA_OPNG','${DFILP}/${ENV_PREFIX}_ESFD2900_FTECLEDA_OPNG_I17L.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_STD',  'ESF_FTECLEDR_OPNG','${DFILP}/${ENV_PREFIX}_ESFD2900_FTECLEDR_OPNG_I17L.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_STD',  'ESF_IRDPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE0_I17L_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_STD',  'ESF_TRERETFACCTR','${DFILP}/${ENV_PREFIX}_ESFD1130_TRERETFACCTR_I17L_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_STD',  'ESF_DLREGTRSII','${DFILP}/${ENV_PREFIX}_ESFD2550_I17L_LCC_RPO_STD_DLREGTRSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_STD',  'ESF_FTECLEDA_AOC','${DFILP}/${ENV_PREFIX}_ESFD3890_I17L_GLT_AOC_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_STD',  'ESF_FTECLEDA_STD','${DFILP}/${ENV_PREFIX}_ESFD3740_I17L_SII_GLT_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_STD',  'ESF_FTECLEDR_STD','${DFILP}/${ENV_PREFIX}_ESFD3740_I17L_SII_GLT_STD_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_STD',  'ESF_DLREGTARSII','${DFILP}/${ENV_PREFIX}_ESFD2550_I17L_LCC_RPO_STD_DLREGTARSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_STD',  'ESF_FTECLEDA_GAPMAP','${DFILP}/${ENV_PREFIX}_ESFD4030_I17L_GAP_MAP_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_STD',  'ESF_FTECLEDR_GAPMAP','${DFILP}/${ENV_PREFIX}_ESFD4030_I17L_GAP_MAP_STD_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_STD',  'ESF_FTECLEDA_3870_PREV','${DFILP}/${ENV_PREFIX}_ESFD3870_I17L_GLT_ALL_STD_FTECLEDA_POS_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_STD',  'ESF_IADPERICASE_DUMMY','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_DUMMY_I17L_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_STD',  'ESF_IADPERICASE_DUMMY_INI','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_DUMMY_I17L_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')			
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_STD',  'ESF_FTECLEDR_CSM_ACC','${DFILP}/${ENV_PREFIX}_ESFD3780_I17L_CSM_ACC_STD_CSM_LC_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_STD',  'ESF_FTECLEDA_3870','${DFILP}/${ENV_PREFIX}_ESFD3870_I17L_GLT_ALL_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_STD',  'ESF_IADVPERICASE','${DFILP}/${ENV_PREFIX}_ESPD1800_I17L_AET_RPO_I17_IADPERICASE_I17_MERGE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_STD',  'ESF_IADPERICASE_ONEFUT','${DFILP}/${ENV_PREFIX}_ESFD3740_I17L_SII_GLT_INI_IADPERICASE_ONEFUT_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_STD',  'ESF_IADPERICASE_PROFUT','${DFILP}/${ENV_PREFIX}_ESFD3740_I17L_SII_GLT_INI_IADPERICASE_PROFUT_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_STD',  'ESF_FTECLEDA_CSM_ACC','${DFILP}/${ENV_PREFIX}_ESFD3780_I17L_CSM_ACC_STD_CSM_LC_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_STD',  'ESF_FTECLEDA_8700','${DFILP}/${ENV_PREFIX}_ESID8700_FTECLEDA_I4I_${PARM_ICLODAT_D}.dat','I','')	
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_STD',  'ESF_FTECLEDA_INI','${DFILP}/${ENV_PREFIX}_ESFD3870_I17L_GLT_ALL_INI_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_STD',  'ESF_IADPERICASE_DUMMY_MRG','${DFILP}/${ENV_PREFIX}_ESFD3870_IADPERICASE_DUMMY_I17L_MRG_${TYPEINV}_${PARM_ICLODAT_D}.dat','U','')											
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_STD',  'ESF_FTECLEDR','${DFILP}/${ENV_PREFIX}_ESFD3870_I17L_GLT_ALL_STD_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','') 
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_STD',  'ESF_FTECLEDR_INI','${DFILP}/${ENV_PREFIX}_ESFD3870_I17L_GLT_ALL_INI_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_STD',  'ESF_FTECLEDA','${DFILP}/${ENV_PREFIX}_ESFD3870_I17L_GLT_ALL_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_STD',  'ESF_FCSM_ENDING_RNP','${DFILP}/${ENV_PREFIX}_ESFD3870_I17L_GLT_ALL_STD_FCSM_ENDING_RNP_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat','O','')   
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_STD',  'ESF_FCSM_LC_ENDING_ASS','${DFILP}/${ENV_PREFIX}_ESFD3870_I17L_GLT_ALL_STD_FCSM_LC_ENDING_ASS_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat','O','')	
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_STD',  'ESF_FCSM_ENDING_RNP_ONLY','${DFILP}/${ENV_PREFIX}_ESFD3870_I17L_GLT_ALL_STD_FCSM_ENDING_RNP_ONLY_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat','O','')   
			insert into BEST..TI17PERMFIL values ('I17L_GLT_ALL_STD',  'ESF_FCSM_LC_ENDING_ASS_ONLY','${DFILP}/${ENV_PREFIX}_ESFD3870_I17L_GLT_ALL_STD_FCSM_LC_ENDING_ASS_ONLY_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17LYINV',  'I17L_GLT_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17LYPOS',  'I17L_GLT_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17LMINV',  'I17L_GLT_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17LQINV',  'I17L_GLT_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17LQPOS',  'I17L_GLT_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17LQPOSX',  'I17L_GLT_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17LYPOSX',  'I17L_GLT_ALL_STD','')

	----------IDF_CT:   I17P_GLT_ALL_INI ------------------

		insert into BEST..TI17FNC values ('I17P_GLT_ALL_INI','Merge of IFRS17 GLT files','ESFD3870',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_INI',  'ESF_DLRGTAASII','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_INI',  'ESF_FTECLEDA_AOC','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_INI',  'ESF_FTECLEDA_STD','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_INI',  'ESF_FTECLEDR_STD','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_INI',  'ESF_DLRGTAA_LCC_INI','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_INI',  'ESF_FTECLEDA_GAPMAP','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_INI',  'ESF_FTECLEDR_GAPMAP','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_INI',  'ESF_FTECLEDA_CSM_ACC','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_INI',  'ESF_FTECLEDR_CSM_ACC','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_INI',  'ESF_DLREGTRSII','${DFILP}/${ENV_PREFIX}_ESFD2550_I17P_LCC_RPO_INI_DLREGTRSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_INI',  'ESF_FTECLEDA_INI','${DFILP}/${ENV_PREFIX}_ESFD3740_I17P_SII_GLT_INI_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_INI',  'ESF_FTECLEDR_INI','${DFILP}/${ENV_PREFIX}_ESFD3740_I17P_SII_GLT_INI_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_INI',  'ESF_DLREGTARSII','${DFILP}/${ENV_PREFIX}_ESFD2550_I17P_LCC_RPO_INI_DLREGTARSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_INI',  'ESF_IADPERICASE_DUMMY','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_DUMMY_I17P_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_INI',  'ESF_IADPERICASE_ONEFUT','${DFILP}/${ENV_PREFIX}_ESFD3740_I17P_SII_GLT_INI_IADPERICASE_ONEFUT_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_INI',  'ESF_IADPERICASE_PROFUT','${DFILP}/${ENV_PREFIX}_ESFD3740_I17P_SII_GLT_INI_IADPERICASE_PROFUT_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_INI',  'ESF_FPLATXCUMALL0','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLATXCUMALL0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')	
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_INI',  'ESF_FTECLEDA','${DFILP}/${ENV_PREFIX}_ESFD3870_I17P_GLT_ALL_INI_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_INI',  'ESF_FTECLEDR','${DFILP}/${ENV_PREFIX}_ESFD3870_I17P_GLT_ALL_INI_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17PMINV',  'I17P_GLT_ALL_INI','')
			insert into BEST..TI17REQFNC values ('I17PQINV',  'I17P_GLT_ALL_INI','')
			insert into BEST..TI17REQFNC values ('I17PQPOS',  'I17P_GLT_ALL_INI','')
			insert into BEST..TI17REQFNC values ('I17PYINV',  'I17P_GLT_ALL_INI','')
			insert into BEST..TI17REQFNC values ('I17PYPOS',  'I17P_GLT_ALL_INI','')

	----------IDF_CT:   I17P_GLT_ALL_STD ------------------

		insert into BEST..TI17FNC values ('I17P_GLT_ALL_STD','Merge of IFRS17 GLT files','ESFD3870',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_STD',  'ESF_DLRGTAASII','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_STD',  'ESF_DLRGTAA_LCC_INI','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_STD',  'EST_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_STD',  'ESF_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_STD',  'ESF_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_STD',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_STD',  'ESF_FTECLEDA_REJ','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDA_REJ_I17P.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_STD',  'ESF_FTECLEDR_REJ','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDR_REJ_I17P.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_STD',  'ESF_FTECLEDA_OPNG','${DFILP}/${ENV_PREFIX}_ESFD2900_FTECLEDA_OPNG_I17P.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_STD',  'ESF_FTECLEDR_OPNG','${DFILP}/${ENV_PREFIX}_ESFD2900_FTECLEDR_OPNG_I17P.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_STD',  'ESF_IRDPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE0_I17P_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_STD',  'ESF_TRERETFACCTR','${DFILP}/${ENV_PREFIX}_ESFD1130_TRERETFACCTR_I17P_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_STD',  'ESF_DLREGTRSII','${DFILP}/${ENV_PREFIX}_ESFD2550_I17P_LCC_RPO_STD_DLREGTRSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_STD',  'ESF_FTECLEDA_AOC','${DFILP}/${ENV_PREFIX}_ESFD3890_I17P_GLT_AOC_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_STD',  'ESF_FTECLEDA_STD','${DFILP}/${ENV_PREFIX}_ESFD3740_I17P_SII_GLT_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_STD',  'ESF_FTECLEDR_STD','${DFILP}/${ENV_PREFIX}_ESFD3740_I17P_SII_GLT_STD_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_STD',  'ESF_DLREGTARSII','${DFILP}/${ENV_PREFIX}_ESFD2550_I17P_LCC_RPO_STD_DLREGTARSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_STD',  'ESF_FTECLEDA_GAPMAP','${DFILP}/${ENV_PREFIX}_ESFD4030_I17P_GAP_MAP_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_STD',  'ESF_FTECLEDR_GAPMAP','${DFILP}/${ENV_PREFIX}_ESFD4030_I17P_GAP_MAP_STD_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_STD',  'ESF_FTECLEDA_3870_PREV','${DFILP}/${ENV_PREFIX}_ESFD3870_I17P_GLT_ALL_STD_FTECLEDA_POS_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_STD',  'ESF_IADPERICASE_DUMMY','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_DUMMY_I17P_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_STD',  'ESF_IADPERICASE_DUMMY_INI','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_DUMMY_I17P_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')			
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_STD',  'ESF_FTECLEDR_CSM_ACC','${DFILP}/${ENV_PREFIX}_ESFD3780_I17P_CSM_ACC_STD_CSM_LC_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_STD',  'ESF_FTECLEDA_3870','${DFILP}/${ENV_PREFIX}_ESFD3870_I17P_GLT_ALL_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_STD',  'ESF_IADVPERICASE','${DFILP}/${ENV_PREFIX}_ESPD1800_I17P_AET_RPO_I17_IADPERICASE_I17_MERGE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_STD',  'ESF_IADPERICASE_ONEFUT','${DFILP}/${ENV_PREFIX}_ESFD3740_I17P_SII_GLT_INI_IADPERICASE_ONEFUT_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_STD',  'ESF_IADPERICASE_PROFUT','${DFILP}/${ENV_PREFIX}_ESFD3740_I17P_SII_GLT_INI_IADPERICASE_PROFUT_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_STD',  'ESF_FTECLEDA_CSM_ACC','${DFILP}/${ENV_PREFIX}_ESFD3780_I17P_CSM_ACC_STD_CSM_LC_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_STD',  'ESF_FTECLEDA_8700','${DFILP}/${ENV_PREFIX}_ESID8700_FTECLEDA_I4I_${PARM_ICLODAT_D}.dat','I','')				
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_STD',  'ESF_FTECLEDA_INI','${DFILP}/${ENV_PREFIX}_ESFD3870_I17P_GLT_ALL_INI_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_STD',  'ESF_IADPERICASE_DUMMY_MRG','${DFILP}/${ENV_PREFIX}_ESFD3870_IADPERICASE_DUMMY_I17P_MRG_${TYPEINV}_${PARM_ICLODAT_D}.dat','U','')							
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_STD',  'ESF_FTECLEDR_INI','${DFILP}/${ENV_PREFIX}_ESFD3870_I17P_GLT_ALL_INI_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_STD',  'ESF_FTECLEDA','${DFILP}/${ENV_PREFIX}_ESFD3870_I17P_GLT_ALL_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_STD',  'ESF_FTECLEDR','${DFILP}/${ENV_PREFIX}_ESFD3870_I17P_GLT_ALL_STD_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_STD',  'ESF_FCSM_ENDING_RNP','${DFILP}/${ENV_PREFIX}_ESFD3870_I17P_GLT_ALL_STD_FCSM_ENDING_RNP_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat','O','')	
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_STD',  'ESF_FCSM_LC_ENDING_ASS','${DFILP}/${ENV_PREFIX}_ESFD3870_I17P_GLT_ALL_STD_FCSM_LC_ENDING_ASS_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat','O','')		
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_STD',  'ESF_FCSM_ENDING_RNP_ONLY','${DFILP}/${ENV_PREFIX}_ESFD3870_I17P_GLT_ALL_STD_FCSM_ENDING_RNP_ONLY_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat','O','')	
			insert into BEST..TI17PERMFIL values ('I17P_GLT_ALL_STD',  'ESF_FCSM_LC_ENDING_ASS_ONLY','${DFILP}/${ENV_PREFIX}_ESFD3870_I17P_GLT_ALL_STD_FCSM_LC_ENDING_ASS_ONLY_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17PMINV',  'I17P_GLT_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17PQINV',  'I17P_GLT_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17PQPOS',  'I17P_GLT_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17PYINV',  'I17P_GLT_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17PYPOS',  'I17P_GLT_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17PQPOSX',  'I17P_GLT_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17PYPOSX',  'I17P_GLT_ALL_STD','')

	----------IDF_CT:   I17S_GLT_ALL_INI ------------------

		insert into BEST..TI17FNC values ('I17S_GLT_ALL_INI','Merge of IFRS17 GLT files','ESFD3870',0)  
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_INI',  'ESF_DLRGTAASII','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_INI',  'ESF_FTECLEDA_AOC','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_INI',  'ESF_FTECLEDA_STD','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_INI',  'ESF_FTECLEDR_STD','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_INI',  'ESF_FTECLEDA_GAPMAP','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_INI',  'ESF_FTECLEDR_GAPMAP','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_INI',  'ESF_FTECLEDA_CSM_ACC','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_INI',  'ESF_FTECLEDR_CSM_ACC','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_INI',  'ESF_DLREGTRSII','${DFILP}/${ENV_PREFIX}_ESFD2550_I17S_LCC_RPO_INI_DLREGTRSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_INI',  'ESF_FTECLEDA_INI','${DFILP}/${ENV_PREFIX}_ESFD3740_I17S_SII_GLT_INI_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_INI',  'ESF_FTECLEDR_INI','${DFILP}/${ENV_PREFIX}_ESFD3740_I17S_SII_GLT_INI_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_INI',  'ESF_DLREGTARSII','${DFILP}/${ENV_PREFIX}_ESFD2550_I17S_LCC_RPO_INI_DLREGTARSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_INI',  'ESF_DLRGTAA_LCC_INI','${DFILP}/${ENV_PREFIX}_ESFD2550_I17S_LCC_RPO_INI_DLRGTAASII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_INI',  'ESF_IADPERICASE_DUMMY','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_DUMMY_I17S_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_INI',  'ESF_IADPERICASE_ONEFUT','${DFILP}/${ENV_PREFIX}_ESFD3740_I17S_SII_GLT_INI_IADPERICASE_ONEFUT_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_INI',  'ESF_IADPERICASE_PROFUT','${DFILP}/${ENV_PREFIX}_ESFD3740_I17S_SII_GLT_INI_IADPERICASE_PROFUT_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_INI',  'ESF_FPLATXCUMALL0','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLATXCUMALL0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')	
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_INI',  'ESF_FTECLEDA','${DFILP}/${ENV_PREFIX}_ESFD3870_I17S_GLT_ALL_INI_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_INI',  'ESF_FTECLEDR','${DFILP}/${ENV_PREFIX}_ESFD3870_I17S_GLT_ALL_INI_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17SMINV',  'I17S_GLT_ALL_INI','')
			insert into BEST..TI17REQFNC values ('I17SQINV',  'I17S_GLT_ALL_INI','')
			insert into BEST..TI17REQFNC values ('I17SQPOS',  'I17S_GLT_ALL_INI','')
			insert into BEST..TI17REQFNC values ('I17SYINV',  'I17S_GLT_ALL_INI','')
			insert into BEST..TI17REQFNC values ('I17SYPOS',  'I17S_GLT_ALL_INI','')

	----------IDF_CT:   I17S_GLT_ALL_STD ------------------

		insert into BEST..TI17FNC values ('I17S_GLT_ALL_STD','Merge of IFRS17 GLT files','ESFD3870',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_STD',  'ESF_DLRGTAA_LCC_INI','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_STD',  'EST_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_STD',  'ESF_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_STD',  'ESF_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_STD',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_STD',  'ESF_FTECLEDA_REJ','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDA_REJ_I17S_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_STD',  'ESF_FTECLEDR_REJ','${DFILP}/${ENV_PREFIX}_ESFX7000_FTECLEDR_REJ_I17S_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_STD',  'ESF_FTECLEDA_OPNG','${DFILP}/${ENV_PREFIX}_ESFD2900_FTECLEDA_OPNG_I17S_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_STD',  'ESF_FTECLEDR_OPNG','${DFILP}/${ENV_PREFIX}_ESFD2900_FTECLEDR_OPNG_I17S_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_STD',  'ESF_IRDPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE0_I17S_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_STD',  'ESF_TRERETFACCTR','${DFILP}/${ENV_PREFIX}_ESFD1130_TRERETFACCTR_I17S_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_STD',  'ESF_DLREGTRSII','${DFILP}/${ENV_PREFIX}_ESFD2550_I17S_LCC_RPO_STD_DLREGTRSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_STD',  'ESF_DLRGTAASII','${DFILP}/${ENV_PREFIX}_ESFD2550_I17S_LCC_RPO_STD_DLRGTAASII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_STD',  'ESF_FTECLEDA_AOC','${DFILP}/${ENV_PREFIX}_ESFD3890_I17S_GLT_AOC_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_STD',  'ESF_FTECLEDA_STD','${DFILP}/${ENV_PREFIX}_ESFD3740_I17S_SII_GLT_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_STD',  'ESF_FTECLEDR_STD','${DFILP}/${ENV_PREFIX}_ESFD3740_I17S_SII_GLT_STD_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_STD',  'ESF_FTECLEDA_3870','${DFILP}/${ENV_PREFIX}_ESFD3870_I17S_GLT_ALL_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_STD',  'ESF_DLREGTARSII','${DFILP}/${ENV_PREFIX}_ESFD2550_I17S_LCC_RPO_STD_DLREGTARSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_STD',  'ESF_FTECLEDA_GAPMAP','${DFILP}/${ENV_PREFIX}_ESFD4030_I17S_GAP_MAP_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_STD',  'ESF_FTECLEDR_GAPMAP','${DFILP}/${ENV_PREFIX}_ESFD4030_I17S_GAP_MAP_STD_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_STD',  'ESF_FTECLEDA_3870_PREV','${DFILP}/${ENV_PREFIX}_ESFD3870_I17G_GLT_ALL_STD_FTECLEDA_POS_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_STD',  'ESF_IADPERICASE_DUMMY','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_DUMMY_I17S_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_STD',  'ESF_IADPERICASE_DUMMY_INI','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_DUMMY_I17S_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')			
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_STD',  'ESF_FTECLEDA_CSM_ACC','${DFILP}/${ENV_PREFIX}_ESFD3780_I17S_CSM_ACC_STD_CSM_LC_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_STD',  'ESF_FTECLEDR_CSM_ACC','${DFILP}/${ENV_PREFIX}_ESFD3780_I17S_CSM_ACC_STD_CSM_LC_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_STD',  'ESF_IADVPERICASE','${DFILP}/${ENV_PREFIX}_ESPD1800_I17S_AET_RPO_I17_IADPERICASE_I17_MERGE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_STD',  'ESF_IADPERICASE_ONEFUT','${DFILP}/${ENV_PREFIX}_ESFD3740_I17S_SII_GLT_INI_IADPERICASE_ONEFUT_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_STD',  'ESF_IADPERICASE_PROFUT','${DFILP}/${ENV_PREFIX}_ESFD3740_I17S_SII_GLT_INI_IADPERICASE_PROFUT_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_STD',  'ESF_FTECLEDA_8700','${DFILP}/${ENV_PREFIX}_ESID8700_FTECLEDA_I4I_${PARM_ICLODAT_D}.dat','I','')	
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_STD',  'ESF_FTECLEDA_INI','${DFILP}/${ENV_PREFIX}_ESFD3870_I17S_GLT_ALL_INI_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_STD',  'ESF_IADPERICASE_DUMMY_MRG','${DFILP}/${ENV_PREFIX}_ESFD3870_IADPERICASE_DUMMY_I17S_MRG_${TYPEINV}_${PARM_ICLODAT_D}.dat','U','')										
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_STD',  'ESF_FTECLEDA','${DFILP}/${ENV_PREFIX}_ESFD3870_I17S_GLT_ALL_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_STD',  'ESF_FTECLEDR','${DFILP}/${ENV_PREFIX}_ESFD3870_I17S_GLT_ALL_STD_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_STD',  'ESF_FTECLEDR_INI','${DFILP}/${ENV_PREFIX}_ESFD3870_I17S_GLT_ALL_INI_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_STD',  'ESF_FCSM_ENDING_RNP','${DFILP}/${ENV_PREFIX}_ESFD3870_I17S_GLT_ALL_STD_FCSM_ENDING_RNP_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_STD',  'ESF_FCSM_LC_ENDING_ASS','${DFILP}/${ENV_PREFIX}_ESFD3870_I17S_GLT_ALL_STD_FCSM_LC_ENDING_ASS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')		
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_STD',  'ESF_FCSM_ENDING_RNP_ONLY','${DFILP}/${ENV_PREFIX}_ESFD3870_I17S_GLT_ALL_STD_FCSM_ENDING_RNP_ONLY_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_GLT_ALL_STD',  'ESF_FCSM_LC_ENDING_ASS_ONLY','${DFILP}/${ENV_PREFIX}_ESFD3870_I17S_GLT_ALL_STD_FCSM_LC_ENDING_ASS_ONLY_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17SMINV',  'I17S_GLT_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17SQINV',  'I17S_GLT_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17SQPOS',  'I17S_GLT_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17SYINV',  'I17S_GLT_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17SYPOS',  'I17S_GLT_ALL_STD','')
go

