-------------------------------
--mapping of  ESFD4040

	----------   Clean tables   ---------------------

	delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD4040')
	delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD4040')
	delete BEST..TI17FNC where CHAIN_CT='ESFD4040'
	delete BEST..TI17CHN  where CHAIN_CT='ESFD4040'

	insert into BEST..TI17CHN values ('ESFD4040',  'IFRS17- CSUOE/R closing data')

	----------IDF_CT:   I17G_CLO_TP_ALL ------------------

		insert into BEST..TI17FNC values ('I17G_CLO_TP_ALL','IFRS17- CSUOE/R closing data','ESFD4040',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17G_CLO_TP_ALL',  'EST_FLAG_ANN_LMT_I17L','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_CLO_TP_ALL',  'EST_FLAG_ANN_LMT_I17P','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_CLO_TP_ALL',  'MANUAL_OVERWRITE','`ls -t ${DUSERS}/DIP_CSM_I17G_${PARM_ICLODAT_D}_*.txt | head -1 `','I','')
			insert into BEST..TI17PERMFIL values ('I17G_CLO_TP_ALL',  'EST_IRDPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE0_I17G_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_CLO_TP_ALL',  'ESF_FLORETFACTOR_STD','${DFILP}/${ENV_PREFIX}_ESPJ0090_FLORETFACTOR_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_CLO_TP_ALL',  'EST_FLAG_ANN_LMT_I17G','${DFILP}/${ENV_PREFIX}_ESFD3990_I17G_EST_FLAG_ANN_LMT_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_CLO_TP_ALL',  'EST_IADPERICASE_INI_I17G','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17G_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_CLO_TP_ALL',  'EST_IADPERICASE_INI_I17L','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17L_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_CLO_TP_ALL',  'EST_IADPERICASE_INI_I17P','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17P_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_CLO_TP_ALL',  'EST_IADPERICASE_STD_I17G','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17G_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_CLO_TP_ALL',  'EST_IADPERICASE_STD_I17L','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17L_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_CLO_TP_ALL',  'EST_IADPERICASE_STD_I17P','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17P_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_CLO_TP_ALL',  'EST_RATIO_I17G_RETRO_P','${DFILP}/${ENV_PREFIX}_ESFD3640_I17G_IVR_CHR_STD_RATIO_RET_P_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_CLO_TP_ALL',  'EST_RATIO_I17L_RETRO_P','${DFILP}/${ENV_PREFIX}_ESFD3640_I17L_IVR_CHR_STD_RATIO_RET_P_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_CLO_TP_ALL',  'EST_RATIO_I17P_RETRO_P','${DFILP}/${ENV_PREFIX}_ESFD3640_I17P_IVR_CHR_STD_RATIO_RET_P_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_CLO_TP_ALL',  'ESF_CSM_LC_AMORT_PATTERN_EBS','${DFILP}/${ENV_PREFIX}_ESFD3770_CSM_LC_AMORT_PATTERN_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_CLO_TP_ALL',  'EST_RATIO_I17G_ASSUMED','${DFILP}/${ENV_PREFIX}_ESFD3640_I17G_IVR_CHR_STD_RATIO_ASSUMED_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_CLO_TP_ALL',  'EST_RATIO_I17G_RETRO_NP','${DFILP}/${ENV_PREFIX}_ESFD3640_I17G_IVR_CHR_STD_RATIO_RET_NP_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_CLO_TP_ALL',  'EST_RATIO_I17L_ASSUMED','${DFILP}/${ENV_PREFIX}_ESFD3640_I17L_IVR_CHR_STD_RATIO_ASSUMED_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_CLO_TP_ALL',  'EST_RATIO_I17L_RETRO_NP','${DFILP}/${ENV_PREFIX}_ESFD3640_I17L_IVR_CHR_STD_RATIO_RET_NP_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_CLO_TP_ALL',  'EST_RATIO_I17P_ASSUMED','${DFILP}/${ENV_PREFIX}_ESFD3640_I17P_IVR_CHR_STD_RATIO_ASSUMED_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_CLO_TP_ALL',  'EST_RATIO_I17P_RETRO_NP','${DFILP}/${ENV_PREFIX}_ESFD3640_I17P_IVR_CHR_STD_RATIO_RET_NP_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_CLO_TP_ALL',  'ESF_FLORETFACTOR_INI_I17G','${DFILP}/${ENV_PREFIX}_ESPJ0090_I17G_AEE_RPO_I17_FLORETFACTOR_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_CLO_TP_ALL',  'ESF_FLORETFACTOR_INI_I17L','${DFILP}/${ENV_PREFIX}_ESPJ0090_I17L_AEE_RPO_I17_FLORETFACTOR_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_CLO_TP_ALL',  'ESF_FLORETFACTOR_INI_I17P','${DFILP}/${ENV_PREFIX}_ESPJ0090_I17P_AEE_RPO_I17_FLORETFACTOR_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_CLO_TP_ALL',  'MERGE_PERICASE_EXTENDED','${DFILP}/${ENV_PREFIX}_ESFD4040_FI17CTRINFO_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17GYINVB',  'I17G_CLO_TP_ALL','')
			insert into BEST..TI17REQFNC values ('I17GYPOS',  'I17G_CLO_TP_ALL','')
			insert into BEST..TI17REQFNC values ('I17GYPOSB',  'I17G_CLO_TP_ALL','')
			insert into BEST..TI17REQFNC values ('I17GMINV',  'I17G_CLO_TP_ALL','')
			insert into BEST..TI17REQFNC values ('I17GQINV',  'I17G_CLO_TP_ALL','')
			insert into BEST..TI17REQFNC values ('I17GQINVB',  'I17G_CLO_TP_ALL','')
			insert into BEST..TI17REQFNC values ('I17GQPOS',  'I17G_CLO_TP_ALL','')
			insert into BEST..TI17REQFNC values ('I17GQPOSB',  'I17G_CLO_TP_ALL','')
			insert into BEST..TI17REQFNC values ('I17GYINV',  'I17G_CLO_TP_ALL','')
			insert into BEST..TI17REQFNC values ('I17GYPOSP',  'I17G_CLO_TP_ALL','')
			insert into BEST..TI17REQFNC values ('I17GQPOSP',  'I17G_CLO_TP_ALL','')

	----------IDF_CT:   I17S_CLO_TP_ALL ------------------

		insert into BEST..TI17FNC values ('I17S_CLO_TP_ALL','IFRS17- CSUOE/R closing data','ESFD4040',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17S_CLO_TP_ALL',  'EST_FLAG_ANN_LMT_I17L','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_CLO_TP_ALL',  'EST_FLAG_ANN_LMT_I17P','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_CLO_TP_ALL',  'MANUAL_OVERWRITE','`ls -t ${DUSERS}/DIP_CSM_I17S_${PARM_ICLODAT_D}_*.txt | head -1 `','I','')
			insert into BEST..TI17PERMFIL values ('I17S_CLO_TP_ALL',  'EST_IRDPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE0_I17S_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_CLO_TP_ALL',  'ESF_FLORETFACTOR_STD','${DFILP}/${ENV_PREFIX}_ESPJ0090_FLORETFACTOR_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_CLO_TP_ALL',  'EST_FLAG_ANN_LMT_I17G','${DFILP}/${ENV_PREFIX}_ESFD3990_I17S_EST_FLAG_ANN_LMT_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_CLO_TP_ALL',  'EST_IADPERICASE_INI_I17G','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17S_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_CLO_TP_ALL',  'EST_IADPERICASE_INI_I17L','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17L_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_CLO_TP_ALL',  'EST_IADPERICASE_INI_I17P','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17P_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_CLO_TP_ALL',  'EST_IADPERICASE_STD_I17G','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17S_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_CLO_TP_ALL',  'EST_IADPERICASE_STD_I17L','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17L_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_CLO_TP_ALL',  'EST_IADPERICASE_STD_I17P','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17P_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_CLO_TP_ALL',  'EST_RATIO_I17G_RETRO_P','${DFILP}/${ENV_PREFIX}_ESFD3640_I17S_IVR_CHR_STD_RATIO_RET_P_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_CLO_TP_ALL',  'EST_RATIO_I17L_RETRO_P','${DFILP}/${ENV_PREFIX}_ESFD3640_I17L_IVR_CHR_STD_RATIO_RET_P_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_CLO_TP_ALL',  'EST_RATIO_I17P_RETRO_P','${DFILP}/${ENV_PREFIX}_ESFD3640_I17P_IVR_CHR_STD_RATIO_RET_P_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_CLO_TP_ALL',  'ESF_CSM_LC_AMORT_PATTERN_EBS','${DFILP}/${ENV_PREFIX}_ESFD3770_CSM_LC_AMORT_PATTERN_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_CLO_TP_ALL',  'EST_RATIO_I17G_ASSUMED','${DFILP}/${ENV_PREFIX}_ESFD3640_I17S_IVR_CHR_STD_RATIO_ASSUMED_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_CLO_TP_ALL',  'EST_RATIO_I17G_RETRO_NP','${DFILP}/${ENV_PREFIX}_ESFD3640_I17S_IVR_CHR_STD_RATIO_RET_NP_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_CLO_TP_ALL',  'EST_RATIO_I17L_ASSUMED','${DFILP}/${ENV_PREFIX}_ESFD3640_I17L_IVR_CHR_STD_RATIO_ASSUMED_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_CLO_TP_ALL',  'EST_RATIO_I17L_RETRO_NP','${DFILP}/${ENV_PREFIX}_ESFD3640_I17L_IVR_CHR_STD_RATIO_RET_NP_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_CLO_TP_ALL',  'EST_RATIO_I17P_ASSUMED','${DFILP}/${ENV_PREFIX}_ESFD3640_I17P_IVR_CHR_STD_RATIO_ASSUMED_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_CLO_TP_ALL',  'EST_RATIO_I17P_RETRO_NP','${DFILP}/${ENV_PREFIX}_ESFD3640_I17P_IVR_CHR_STD_RATIO_RET_NP_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_CLO_TP_ALL',  'ESF_FLORETFACTOR_INI_I17G','${DFILP}/${ENV_PREFIX}_ESPJ0090_I17S_AEE_RPO_I17_FLORETFACTOR_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_CLO_TP_ALL',  'ESF_FLORETFACTOR_INI_I17L','${DFILP}/${ENV_PREFIX}_ESPJ0090_I17L_AEE_RPO_I17_FLORETFACTOR_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_CLO_TP_ALL',  'ESF_FLORETFACTOR_INI_I17P','${DFILP}/${ENV_PREFIX}_ESPJ0090_I17P_AEE_RPO_I17_FLORETFACTOR_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_CLO_TP_ALL',  'MERGE_PERICASE_EXTENDED','${DFILP}/${ENV_PREFIX}_ESFD4040_FI17CTRINFO_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17SQPOS',  'I17S_CLO_TP_ALL','')
			insert into BEST..TI17REQFNC values ('I17SQPOSB',  'I17S_CLO_TP_ALL','')
			insert into BEST..TI17REQFNC values ('I17SYINV',  'I17S_CLO_TP_ALL','')
			insert into BEST..TI17REQFNC values ('I17SYINVB',  'I17S_CLO_TP_ALL','')
			insert into BEST..TI17REQFNC values ('I17SYPOS',  'I17S_CLO_TP_ALL','')
			insert into BEST..TI17REQFNC values ('I17SYPOSB',  'I17S_CLO_TP_ALL','')
			insert into BEST..TI17REQFNC values ('I17SMINV',  'I17S_CLO_TP_ALL','')
			insert into BEST..TI17REQFNC values ('I17SQINV',  'I17S_CLO_TP_ALL','')
			insert into BEST..TI17REQFNC values ('I17SQINVB',  'I17S_CLO_TP_ALL','')
			insert into BEST..TI17REQFNC values ('I17SYPOSP',  'I17S_CLO_TP_ALL','')
			insert into BEST..TI17REQFNC values ('I17SQPOSP',  'I17S_CLO_TP_ALL','')
go

