-------------------------------
--mapping of  ESPD8830

	----------   Clean tables   ---------------------

	delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESPD8830')
	delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESPD8830')
	delete BEST..TI17FNC where CHAIN_CT='ESPD8830'
	delete BEST..TI17CHN  where CHAIN_CT='ESPD8830'

	insert into BEST..TI17CHN values ('ESPD8830',  '')

	----------IDF_CT:   EBS_ESPD8830 ------------------

		insert into BEST..TI17FNC values ('EBS_ESPD8830','IFRS4 Post omega  EBS','ESPD8830',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EST_GTA','${DFILP}/${ENV_PREFIX}_ESIX7000_GTA.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EST_GTR','${DFILP}/${ENV_PREFIX}_ESIX7000_GTR.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EST_CURGTA','${DFILP}/${ENV_PREFIX}_ESIX7000_CURGTA.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EST_CURGTR','${DFILP}/${ENV_PREFIX}_ESIX7000_CURGTR.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EST_STATGTA','${DFILP}/${ENV_PREFIX}_ESIX7000_STATGTA.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EST_STATGTR','${DFILP}/${ENV_PREFIX}_ESIX7000_STATGTR.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EST_ARCSTATGTA','${DFILP}/${ENV_PREFIX}_ESIX7000_ARCSTATGTA.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EST_ARCSTATGTR','${DFILP}/${ENV_PREFIX}_ESIX7000_ARCSTATGTR.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EPO_OIADVPERICASE','${DFILP}/${ENV_PREFIX}_ESCJ0660_OIADVPERICASE.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EPO_GTEP','${DFILP}/${ENV_PREFIX}_ESPD4000_GTEP_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EPO_FTECLEDRSO','${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_EBS_POS_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EPO_GTEPSIISO','${DFILP}/${ENV_PREFIX}_ESPD4000_GTEP_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EPO_DLSGTRSO','${DFILP}/${ENV_PREFIX}_ESPD1800_DLSGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EPO_FPLC','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLC_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EPO_FTECLEDRSIISO','${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_EBS_POS_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EPO_DLEIGTAA','${DFILP}/${ENV_PREFIX}_ESPD2550_DLEIGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EPO_DLREGTRSO','${DFILP}/${ENV_PREFIX}_ESPD2550_DLREGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EPO_DLRGTAASO','${DFILP}/${ENV_PREFIX}_ESPD2550_DLRGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EPO_DLSGTAASO','${DFILP}/${ENV_PREFIX}_ESPD1800_DLSGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EPO_DLSGTARSO','${DFILP}/${ENV_PREFIX}_ESPD1800_DLSGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EPO_DLSGTRSIISO','${DFILP}/${ENV_PREFIX}_ESPD1800_DLSGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EPO_DLREJGTRSO','${DFILP}/${ENV_PREFIX}_ESPD2900_DLREJGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EPO_FCTRSTATSO','${DFILP}/${ENV_PREFIX}_ESPD3900_FCTRSTAT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EPO_FSEGSTATSO','${DFILP}/${ENV_PREFIX}_ESPD3900_FSEGSTAT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EPO_DLREGTRSIISO','${DFILP}/${ENV_PREFIX}_ESPD2550_DLREGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EPO_DLRGTAASIISO','${DFILP}/${ENV_PREFIX}_ESPD2550_DLRGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EPO_DLASIIGTRSO','${DFILP}/${ENV_PREFIX}_ESPD3630_DLASIIGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EPO_DLDSIIGTRSO','${DFILP}/${ENV_PREFIX}_ESPD3620_DLDSIIGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EPO_DLREJGTAASO','${DFILP}/${ENV_PREFIX}_ESPD2900_DLREJGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EPO_DLREJGTARSO','${DFILP}/${ENV_PREFIX}_ESPD2900_DLREJGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EPO_DLREJGTRSIISO','${DFILP}/${ENV_PREFIX}_ESPD2900_DLREJGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EPO_FTECLEDASIISO','${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EPO_DLREMAJGTRSO','${DFILP}/${ENV_PREFIX}_ESPD2550_DLREMAJGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EPO_DLREJGTAASIISO','${DFILP}/${ENV_PREFIX}_ESPD2900_DLREJGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EPO_DLREJGTARSIISO','${DFILP}/${ENV_PREFIX}_ESPD2900_DLREJGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EPO_DLREMAJGTRSIISO','${DFILP}/${ENV_PREFIX}_ESPD2550_DLREMAJGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EPO_CRVPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5010_CRVPERICASE0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EST_GTSII_RISKMARGIN','${DFILP}/${ENV_PREFIX}_ESPD3700_GTSII_RISKMARGIN_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EPO_DLEIFTECLEDSIIEPSO','${DFILP}/${ENV_PREFIX}_ESPD4000_DLEIFTECLEDSIIEP_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EST_ARCSTATGTAR','${DFILP}/${ENV_PREFIX}_ESIX7000_ARCSTATGTAR.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EPO_GTRANO','${DFILP}/${ENV_PREFIX}_ESPD8830_GTRANO_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EPO_FTECLEDRSO_ARC','${DARCH}/${ENV_PREFIX}_ESPD3800_FTECLEDR_EBS_POS_${PARM_ICLODAT_D}_${CRE_D}.dat.gz','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EPO_GTEPSIISO_ARC','${DARCH}/${ENV_PREFIX}_ESPD4000_GTEP_EBS_${TYPEINV}_${PARM_ICLODAT_D}_${CRE_D}.dat.gz','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EPO_FTECLEDRSIISO_ARC','${DARCH}/${ENV_PREFIX}_ESPD3800_FTECLEDR_EBS_POS_${PARM_ICLODAT_D}_${CRE_D}.dat.gz','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EPO_DLEIGTAA_ARC','${DARCH}/${ENV_PREFIX}_ESPD2550_DLEIGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}_${CRE_D}.dat.gz','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EPO_DLSGTRSIISO_ARC','${DARCH}/${ENV_PREFIX}_ESPD1800_DLSGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}_${CRE_D}.dat.gz','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EPO_FCTRSTATSO_ARC','${DARCH}/${ENV_PREFIX}_ESPD3900_FCTRSTAT_EBS_${TYPEINV}_${PARM_ICLODAT_D}_${CRE_D}.dat.gz','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EPO_FSEGSTATSO_ARC','${DARCH}/${ENV_PREFIX}_ESPD3900_FSEGSTAT_EBS_${TYPEINV}_${PARM_ICLODAT_D}_${CRE_D}.dat.gz','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EPO_DLREGTRSIISO_ARC','${DARCH}/${ENV_PREFIX}_ESPD2550_DLREGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}_${CRE_D}.dat.gz','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EPO_DLRGTAASIISO_ARC','${DARCH}/${ENV_PREFIX}_ESPD2550_DLRGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}_${CRE_D}.dat.gz','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EPO_DLASIIGTRSO_ARC','${DARCH}/${ENV_PREFIX}_ESPD3630_DLASIIGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}_${CRE_D}.dat.gz','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EPO_DLDSIIGTRSO_ARC','${DARCH}/${ENV_PREFIX}_ESPD3620_DLDSIIGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}_${CRE_D}.dat.gz','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EPO_FTECLEDASIISO_ARC','${DARCH}/${ENV_PREFIX}_ESPD3800_FTECLEDA_EBS_${TYPEINV}_${PARM_ICLODAT_D}_${CRE_D}.dat.gz','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EPO_DLREMAJGTRSIISO_ARC','${DARCH}/${ENV_PREFIX}_ESPD2550_DLREMAJGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}_${CRE_D}.dat.gz','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EST_CURGTA_Apres_POSE_ARC','${DARCH}/${ENV_PREFIX}_ESIX7000_CURGTA_Apres_POSE_${TYPEINV}_${PARM_ICLODAT_D}_${CRE_D}.dat.gz','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EST_CURGTR_Apres_POSE_ARC','${DARCH}/${ENV_PREFIX}_ESIX7000_CURGTR_Apres_POSE_${TYPEINV}_${PARM_ICLODAT_D}_${CRE_D}.dat.gz','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EST_GTSII_RISKMARGIN_ARC','${DARCH}/${ENV_PREFIX}_ESPD3700_GTSII_RISKMARGIN_EBS_${TYPEINV}_${PARM_ICLODAT_D}_${CRE_D}.dat.gz','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD8830',  'EPO_DLEIFTECLEDSIIEPSO_ARC','${DARCH}/${ENV_PREFIX}_ESPD4000_DLEIFTECLEDSIIEP_EBS_${TYPEINV}_${PARM_ICLODAT_D}_${CRE_D}.dat.gz','O','')

		----------   Reqs    ---------------------


	----------IDF_CT:   I4I_ESPD8830 ------------------

		insert into BEST..TI17FNC values ('I4I_ESPD8830','IFRS4 Post omega  IFRS','ESPD8830',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I4I_ESPD8830',  'EST_GTA','${DFILP}/${ENV_PREFIX}_ESIX7000_GTA.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD8830',  'EST_GTR','${DFILP}/${ENV_PREFIX}_ESIX7000_GTR.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD8830',  'EST_CURGTA','${DFILP}/${ENV_PREFIX}_ESIX7000_CURGTA.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD8830',  'EST_CURGTR','${DFILP}/${ENV_PREFIX}_ESIX7000_CURGTR.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD8830',  'EST_STATGTA','${DFILP}/${ENV_PREFIX}_ESIX7000_STATGTA.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD8830',  'EST_STATGTR','${DFILP}/${ENV_PREFIX}_ESIX7000_STATGTR.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD8830',  'EST_ARCSTATGTA','${DFILP}/${ENV_PREFIX}_ESIX7000_ARCSTATGTA.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD8830',  'EST_ARCSTATGTR','${DFILP}/${ENV_PREFIX}_ESIX7000_ARCSTATGTR.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD8830',  'EPO_FPLC','${DFILP}/${ENV_PREFIX}_ESID2500_FPLC_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD8830',  'EPO_FCTRSTATSO','${DFILP}/${ENV_PREFIX}_ESPD3900_FCTRSTAT_I4I_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD8830',  'EPO_FSEGSTATSO','${DFILP}/${ENV_PREFIX}_ESPD3900_FSEGSTAT_I4I_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD8830',  'EPO_GTEP','${DFILP}/${ENV_PREFIX}_ESPD4000_GTEP_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD8830',  'EPO_FTECLEDASO','${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_I4I_POS_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD8830',  'EPO_CRVPERICASE0','${DFILP}/${ENV_PREFIX}_ESID0060_CRVPERICASE0_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD8830',  'EPO_GTEPSIISO','${DFILP}/${ENV_PREFIX}_ESPD4000_GTEP_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD8830',  'EPO_DLSGTRSO','${DFILP}/${ENV_PREFIX}_ESPD1800_DLSGTR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD8830',  'EPO_OIADVPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_OIADVPERICASE_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD8830',  'EPO_DLEIGTAA','${DFILP}/${ENV_PREFIX}_ESPD2550_DLEIGTAA_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD8830',  'EPO_DLREGTRSO','${DFILP}/${ENV_PREFIX}_ESPD2550_DLREGTR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD8830',  'EPO_DLRGTAASO','${DFILP}/${ENV_PREFIX}_ESPD2550_DLRGTAA_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD8830',  'EPO_DLSGTAASO','${DFILP}/${ENV_PREFIX}_ESPD1800_DLSGTAA_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD8830',  'EPO_DLSGTARSO','${DFILP}/${ENV_PREFIX}_ESPD1800_DLSGTAR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD8830',  'EPO_DLREJGTRSO','${DFILP}/${ENV_PREFIX}_ESPD2900_DLREJGTR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD8830',  'EPO_FTECLEDASO_CUR','${DFILP}/${ENV_PREFIX}_ESPD3860_FTECLEDA_CUR_I4I_POS_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD8830',  'EPO_FTECLEDASO_MVT','${DFILP}/${ENV_PREFIX}_ESPD3860_FTECLEDA_MVT_I4I_POS_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD8830',  'EPO_DLREJGTAASO','${DFILP}/${ENV_PREFIX}_ESPD2900_DLREJGTAA_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD8830',  'EPO_DLREJGTARSO','${DFILP}/${ENV_PREFIX}_ESPD2900_DLREJGTAR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD8830',  'EPO_FTECLEDRSO','${DFILP}/${ENV_PREFIX}_ES${PARM_FTECLED}D3800_FTECLEDR_I4I_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD8830',  'EPO_DLREMAJGTRSO','${DFILP}/${ENV_PREFIX}_ESPD2550_DLREMAJGTR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD8830',  'EST_ARCSTATGTAR','${DFILP}/${ENV_PREFIX}_ESIX7000_ARCSTATGTAR.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD8830',  'EPO_GTRANO','${DFILP}/${ENV_PREFIX}_ESPD8830_GTRANO_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD8830',  'EPO_GTEP_ARC','${DARCH}/${ENV_PREFIX}_ESPD4000_GTEP_I4I_${TYPEINV}_${PARM_ICLODAT_D}_${CRE_D}.dat.gz','O','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD8830',  'EPO_CRVPERICASE0_ARC','${DARCH}/${ENV_PREFIX}_ESID0060_CRVPERICASE0_INV_${PARM_ICLODAT_D}_${CRE_D}.dat.gz','O','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD8830',  'EPO_DLSGTRSO_ARC','${DARCH}/${ENV_PREFIX}_ESPD1800_DLSGTR_I4I_${TYPEINV}_${PARM_ICLODAT_D}_${CRE_D}.dat.gz','O','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD8830',  'EPO_DLEIGTAA_ARC','${DARCH}/${ENV_PREFIX}_ESPD2550_DLEIGTAA_I4I_${TYPEINV}_${PARM_ICLODAT_D}_${CRE_D}.dat.gz','O','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD8830',  'EPO_DLREGTRSO_ARC','${DARCH}/${ENV_PREFIX}_ESPD2550_DLREGTR_I4I_${TYPEINV}_${PARM_ICLODAT_D}_${CRE_D}.dat.gz','O','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD8830',  'EPO_DLRGTAASO_ARC','${DARCH}/${ENV_PREFIX}_ESPD2550_DLRGTAA_I4I_${TYPEINV}_${PARM_ICLODAT_D}_${CRE_D}.dat.gz','O','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD8830',  'EPO_DLREMAJGTRSO_ARC','${DARCH}/${ENV_PREFIX}_ESPD2550_DLREMAJGTR_I4I_${TYPEINV}_${PARM_ICLODAT_D}_${CRE_D}.dat.gz','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I4IQPOSB',  'I4I_ESPD8830','')
			insert into BEST..TI17REQFNC values ('I4IYPOSB',  'I4I_ESPD8830','')
go

