-------------------------------
--mapping of  ESFD3830

	----------   Clean tables   ---------------------

	delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD3830')
	delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD3830')
	delete BEST..TI17FNC where CHAIN_CT='ESFD3830'
	delete BEST..TI17CHN  where CHAIN_CT='ESFD3830'

	insert into BEST..TI17CHN values ('ESFD3830',  'Merge cashflow and discount')

	----------IDF_CT:   I17G_SII_MRG_INI ------------------

		insert into BEST..TI17FNC values ('I17G_SII_MRG_INI','Merge cashflow and discount at inception','ESFD3830',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17G_SII_MRG_INI',  'ESF_GTSII_IFRS17_CSM','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_SII_MRG_INI',  'ESF_GTSII_CSM_CASHFLOW','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_SII_MRG_INI',  'ESF_GTSII_ESCOMPTE_DSI','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_SII_MRG_INI',  'ESF_GTSII_ESCOMPTE_FWD','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_SII_MRG_INI',  'ESF_GTSII_ESCOMPTE_UWD','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_SII_MRG_INI',  'ESF_GTSII_IFRS17_REVENUE','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_SII_MRG_INI',  'ESF_GTSII_CASHFLOW_RAD_CUR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_SII_MRG_INI',  'ESF_GTSII_ESCOMPTE_RAD_DSI','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_SII_MRG_INI',  'ESF_FSECIFRS','${DFILP}/${ENV_PREFIX}_ESFD3720_I17G_CSM_CRE_INI_FSECIFRS${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_SII_MRG_INI',  'ESF_GTSII_ICR','${DFILP}/${ENV_PREFIX}_ESFD3610_I17G_CSF_ALL_INI_GTSII_ICR${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_SII_MRG_INI',  'ESF_IADPERICASE_INI','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17G_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_SII_MRG_INI',  'ESF_IADPERICASE_DUMMY','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_DUMMY_I17G_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_SII_MRG_INI',  'ESF_GTSII_IFRS17_CSM_ESCOMPTE','${DFILP}/${ENV_PREFIX}_ESFD3710_I17G_CSM_CSU_INI_GTSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_SII_MRG_INI',  'ESF_GTSII_ESCOMPTE_LKI','${DFILP}/${ENV_PREFIX}_ESFD3620_I17G_DSC_LKI_INI_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_SII_MRG_INI',  'ESF_GTSII_CASHFLOW_RAD_CKI','${DFILP}/${ENV_PREFIX}_ESFD3650_I17G_RAD_CKI_INI_GTSII_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_SII_MRG_INI',  'ESF_GTSII_ESCOMPTE_RAD_LKI','${DFILP}/${ENV_PREFIX}_ESFD3620_I17G_RAD_LKI_INI_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_SII_MRG_INI',  'ESF_GTSII_CASHFLOW_RAP_CKI','${DFILP}/${ENV_PREFIX}_ESFD3650_I17G_RAP_CKI_INI_GTSII_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_SII_MRG_INI',  'ESF_GTSII_CLACC_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESFD3610_I17G_CSF_ALL_INI_GTSII_CLACC_CASHFLOW${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_SII_MRG_INI',  'ESF_GTSII_REMAINTOPAY_ULAE','${DFILP}/${ENV_PREFIX}_ESFD3610_I17G_CSF_ALL_INI_GTSII_RMTP_ULAE_SII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_SII_MRG_INI',  'ESF_GTSII_GLOBAL_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESFD3630_I17G_IEX_ALL_INI_GTSII_GLOBAL_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_SII_MRG_INI',  'ESF_GTSII_ONE_STD','${DFILP}/${ENV_PREFIX}_ESFD3830_I17G_SII_MRG_INI_GTSII_ONEFUT_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_SII_MRG_INI',  'ESF_GTSII_DUMMY_STD','${DFILP}/${ENV_PREFIX}_ESFD3830_I17G_SII_MRG_INI_GTSII_DUMMY_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_SII_MRG_INI',  'ESF_GTSII_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESFD3830_I17G_SII_MRG_INI_GTSII_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17GMINV',  'I17G_SII_MRG_INI','')
			insert into BEST..TI17REQFNC values ('I17GQINV',  'I17G_SII_MRG_INI','')
			insert into BEST..TI17REQFNC values ('I17GQPOS',  'I17G_SII_MRG_INI','')
			insert into BEST..TI17REQFNC values ('I17GYINV',  'I17G_SII_MRG_INI','')
			insert into BEST..TI17REQFNC values ('I17GYPOS',  'I17G_SII_MRG_INI','')

	----------IDF_CT:   I17G_SII_MRG_STD ------------------

		insert into BEST..TI17FNC values ('I17G_SII_MRG_STD','Merge cashflow and discount at standard','ESFD3830',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17G_SII_MRG_STD',  'ESF_GTSII_ICR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_SII_MRG_STD',  'ESF_GTSII_CLACC_CASHFLOW','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_SII_MRG_STD',  'ESF_GTSII_REMAINTOPAY_ULAE','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_SII_MRG_STD',  'ESF_GTSII_IFRS17_CSM_ESCOMPTE','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_SII_MRG_STD',  'ESF_GTSII_IFRS17_CSM','${DFILP}/${ENV_PREFIX}_ESFD3690_I17G_IRV_ALL_STD_GTSII_IFRS17_CSM${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_SII_MRG_STD',  'ESF_GTSII_ESCOMPTE_DSI','${DFILP}/${ENV_PREFIX}_ESFD3620_I17G_DSC_DSI_STD_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_SII_MRG_STD',  'ESF_GTSII_ESCOMPTE_LKI','${DFILP}/${ENV_PREFIX}_ESFD3690_I17G_IRV_ALL_STD_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_SII_MRG_STD',  'ESF_GTSII_CASHFLOW_RAD_CKI','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_SII_MRG_STD',  'ESF_GTSII_CASHFLOW_RAD_CUR','${DFILP}/${ENV_PREFIX}_ESFD3650_I17G_RAD_CUR_STD_GTSII_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_SII_MRG_STD',  'ESF_GTSII_CSM_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESFD3760_I17G_UOA_PRO_STD_GTSII_CSM_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_SII_MRG_STD',  'ESF_GTSII_ESCOMPTE_FWD','${DFILP}/${ENV_PREFIX}_ESFD3690_I17G_IRV_ALL_STD_GTSII_ESCOMPTE_FWD_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_SII_MRG_STD',  'ESF_GTSII_ESCOMPTE_RAD_DSI','${DFILP}/${ENV_PREFIX}_ESFD3620_I17G_RAD_DSI_STD_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_SII_MRG_STD',  'ESF_GTSII_ESCOMPTE_RAD_LKI','${DFILP}/${ENV_PREFIX}_ESFD3620_I17G_RAD_LKI_STD_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_SII_MRG_STD',  'ESF_GTSII_CASHFLOW_RAP_CUR','${DFILP}/${ENV_PREFIX}_ESFD3650_I17G_RAP_CUR_STD_GTSII_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_SII_MRG_STD',  'ESF_GTSII_IFRS17_REVENUE','${DFILP}/${ENV_PREFIX}_ESFD3690_I17G_IRV_ALL_STD_GTSII_IFRS17_REVENUE${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_SII_MRG_STD',  'ESF_GTSII_GLOBAL_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESFD3630_I17G_IEX_ALL_STD_GTSII_GLOBAL_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_SII_MRG_STD',  'ESF_GTSII_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESFD3830_I17G_SII_MRG_STD_GTSII_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17GMINV',  'I17G_SII_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17GQINV',  'I17G_SII_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17GQPOS',  'I17G_SII_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17GYINV',  'I17G_SII_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17GYPOS',  'I17G_SII_MRG_STD','')

	----------IDF_CT:   I17L_SII_MRG_INI ------------------

		insert into BEST..TI17FNC values ('I17L_SII_MRG_INI','Merge cashflow and discount at inception','ESFD3830',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17L_SII_MRG_INI',  'ESF_GTSII_ICR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_SII_MRG_INI',  'ESF_GTSII_IFRS17_CSM','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_SII_MRG_INI',  'ESF_GTSII_CSM_CASHFLOW','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_SII_MRG_INI',  'ESF_GTSII_ESCOMPTE_DSI','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_SII_MRG_INI',  'ESF_GTSII_ESCOMPTE_FWD','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_SII_MRG_INI',  'ESF_GTSII_ESCOMPTE_UWD','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_SII_MRG_INI',  'ESF_GTSII_IFRS17_REVENUE','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_SII_MRG_INI',  'ESF_GTSII_CASHFLOW_RAD_CUR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_SII_MRG_INI',  'ESF_GTSII_ESCOMPTE_RAD_DSI','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_SII_MRG_INI',  'ESF_FSECIFRS','${DFILP}/${ENV_PREFIX}_ESFD3720_I17L_CSM_CRE_INI_FSECIFRS${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_SII_MRG_INI',  'ESF_IADPERICASE_INI','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17L_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_SII_MRG_INI',  'ESF_IADPERICASE_DUMMY','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_DUMMY_I17L_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_SII_MRG_INI',  'ESF_GTSII_IFRS17_CSM_ESCOMPTE','${DFILP}/${ENV_PREFIX}_ESFD3710_I17L_CSM_CSU_INI_GTSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_SII_MRG_INI',  'ESF_GTSII_ESCOMPTE_LKI','${DFILP}/${ENV_PREFIX}_ESFD3620_I17L_DSC_LKI_INI_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_SII_MRG_INI',  'ESF_GTSII_CASHFLOW_RAD_CKI','${DFILP}/${ENV_PREFIX}_ESFD3650_I17L_RAD_CKI_INI_GTSII_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_SII_MRG_INI',  'ESF_GTSII_ESCOMPTE_RAD_LKI','${DFILP}/${ENV_PREFIX}_ESFD3620_I17L_RAD_LKI_INI_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_SII_MRG_INI',  'ESF_GTSII_CASHFLOW_RAP_CKI','${DFILP}/${ENV_PREFIX}_ESFD3650_I17L_RAP_CKI_INI_GTSII_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_SII_MRG_INI',  'ESF_GTSII_CLACC_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESFD3610_I17L_CSF_ALL_INI_GTSII_CLACC_CASHFLOW${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_SII_MRG_INI',  'ESF_GTSII_REMAINTOPAY_ULAE','${DFILP}/${ENV_PREFIX}_ESFD3610_I17L_CSF_ALL_INI_GTSII_RMTP_ULAE_SII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_SII_MRG_INI',  'ESF_GTSII_GLOBAL_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESFD3630_I17L_IEX_ALL_INI_GTSII_GLOBAL_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_SII_MRG_INI',  'ESF_GTSII_ONE_STD','${DFILP}/${ENV_PREFIX}_ESFD3830_I17L_SII_MRG_INI_GTSII_ONEFUT_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_SII_MRG_INI',  'ESF_GTSII_DUMMY_STD','${DFILP}/${ENV_PREFIX}_ESFD3830_I17L_SII_MRG_INI_GTSII_DUMMY_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_SII_MRG_INI',  'ESF_GTSII_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESFD3830_I17L_SII_MRG_INI_GTSII_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17LMINV',  'I17L_SII_MRG_INI','')
			insert into BEST..TI17REQFNC values ('I17LQINV',  'I17L_SII_MRG_INI','')
			insert into BEST..TI17REQFNC values ('I17LQPOS',  'I17L_SII_MRG_INI','')
			insert into BEST..TI17REQFNC values ('I17LYINV',  'I17L_SII_MRG_INI','')
			insert into BEST..TI17REQFNC values ('I17LYPOS',  'I17L_SII_MRG_INI','')

	----------IDF_CT:   I17L_SII_MRG_STD ------------------

		insert into BEST..TI17FNC values ('I17L_SII_MRG_STD','Merge cashflow and discount at standard','ESFD3830',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17L_SII_MRG_STD',  'ESF_GTSII_ICR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_SII_MRG_STD',  'ESF_GTSII_CLACC_CASHFLOW','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_SII_MRG_STD',  'ESF_GTSII_REMAINTOPAY_ULAE','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_SII_MRG_STD',  'ESF_GTSII_IFRS17_CSM_ESCOMPTE','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_SII_MRG_STD',  'ESF_GTSII_IFRS17_CSM','${DFILP}/${ENV_PREFIX}_ESFD3690_I17L_IRV_ALL_STD_GTSII_IFRS17_CSM${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_SII_MRG_STD',  'ESF_GTSII_ESCOMPTE_DSI','${DFILP}/${ENV_PREFIX}_ESFD3620_I17L_DSC_DSI_STD_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_SII_MRG_STD',  'ESF_GTSII_ESCOMPTE_LKI','${DFILP}/${ENV_PREFIX}_ESFD3690_I17L_IRV_ALL_STD_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_SII_MRG_STD',  'ESF_GTSII_CASHFLOW_RAD_CUR','${DFILP}/${ENV_PREFIX}_ESFD3650_I17L_RAD_CUR_STD_GTSII_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_SII_MRG_STD',  'ESF_GTSII_ESCOMPTE_FWD','${DFILP}/${ENV_PREFIX}_ESFD3690_I17L_IRV_ALL_STD_GTSII_ESCOMPTE_FWD_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_SII_MRG_STD',  'ESF_GTSII_ESCOMPTE_RAD_DSI','${DFILP}/${ENV_PREFIX}_ESFD3620_I17L_RAD_DSI_STD_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_SII_MRG_STD',  'ESF_GTSII_IFRS17_REVENUE','${DFILP}/${ENV_PREFIX}_ESFD3690_I17L_IRV_ALL_STD_GTSII_IFRS17_REVENUE${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_SII_MRG_STD',  'ESF_GTSII_CASHFLOW_RAD_CKI','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_SII_MRG_STD',  'ESF_GTSII_CSM_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESFD3760_I17L_UOA_PRO_STD_GTSII_CSM_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_SII_MRG_STD',  'ESF_GTSII_ESCOMPTE_RAD_LKI','${DFILP}/${ENV_PREFIX}_ESFD3620_I17L_RAD_LKI_STD_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_SII_MRG_STD',  'ESF_GTSII_CASHFLOW_RAP_CUR','${DFILP}/${ENV_PREFIX}_ESFD3650_I17L_RAP_CUR_STD_GTSII_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_SII_MRG_STD',  'ESF_GTSII_GLOBAL_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESFD3630_I17L_IEX_ALL_STD_GTSII_GLOBAL_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_SII_MRG_STD',  'ESF_GTSII_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESFD3830_I17L_SII_MRG_STD_GTSII_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17LMINV',  'I17L_SII_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17LQINV',  'I17L_SII_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17LQPOS',  'I17L_SII_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17LYINV',  'I17L_SII_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17LYPOS',  'I17L_SII_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17LQPOSX',  'I17L_SII_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17LYPOSX',  'I17L_SII_MRG_STD','')

	----------IDF_CT:   I17P_SII_MRG_INI ------------------

		insert into BEST..TI17FNC values ('I17P_SII_MRG_INI','Merge cashflow and discount at inception','ESFD3830',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17P_SII_MRG_INI',  'ESF_GTSII_ICR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_SII_MRG_INI',  'ESF_GTSII_IFRS17_CSM','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_SII_MRG_INI',  'ESF_GTSII_CSM_CASHFLOW','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_SII_MRG_INI',  'ESF_GTSII_ESCOMPTE_DSI','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_SII_MRG_INI',  'ESF_GTSII_ESCOMPTE_FWD','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_SII_MRG_INI',  'ESF_GTSII_ESCOMPTE_UWD','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_SII_MRG_INI',  'ESF_GTSII_IFRS17_REVENUE','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_SII_MRG_INI',  'ESF_GTSII_CASHFLOW_RAD_CUR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_SII_MRG_INI',  'ESF_GTSII_ESCOMPTE_RAD_DSI','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_SII_MRG_INI',  'ESF_FSECIFRS','${DFILP}/${ENV_PREFIX}_ESFD3720_I17P_CSM_CRE_INI_FSECIFRS${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_SII_MRG_INI',  'ESF_IADPERICASE_INI','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17P_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_SII_MRG_INI',  'ESF_IADPERICASE_DUMMY','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_DUMMY_I17P_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_SII_MRG_INI',  'ESF_GTSII_IFRS17_CSM_ESCOMPTE','${DFILP}/${ENV_PREFIX}_ESFD3710_I17P_CSM_CSU_INI_GTSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_SII_MRG_INI',  'ESF_GTSII_ESCOMPTE_LKI','${DFILP}/${ENV_PREFIX}_ESFD3620_I17P_DSC_LKI_INI_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_SII_MRG_INI',  'ESF_GTSII_CASHFLOW_RAD_CKI','${DFILP}/${ENV_PREFIX}_ESFD3650_I17P_RAD_CKI_INI_GTSII_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_SII_MRG_INI',  'ESF_GTSII_ESCOMPTE_RAD_LKI','${DFILP}/${ENV_PREFIX}_ESFD3620_I17P_RAD_LKI_INI_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_SII_MRG_INI',  'ESF_GTSII_CASHFLOW_RAP_CKI','${DFILP}/${ENV_PREFIX}_ESFD3650_I17P_RAP_CKI_INI_GTSII_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_SII_MRG_INI',  'ESF_GTSII_CLACC_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESFD3610_I17P_CSF_ALL_INI_GTSII_CLACC_CASHFLOW${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_SII_MRG_INI',  'ESF_GTSII_REMAINTOPAY_ULAE','${DFILP}/${ENV_PREFIX}_ESFD3610_I17P_CSF_ALL_INI_GTSII_RMTP_ULAE_SII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_SII_MRG_INI',  'ESF_GTSII_GLOBAL_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESFD3630_I17P_IEX_ALL_INI_GTSII_GLOBAL_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_SII_MRG_INI',  'ESF_GTSII_ONE_STD','${DFILP}/${ENV_PREFIX}_ESFD3830_I17P_SII_MRG_INI_GTSII_ONEFUT_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_SII_MRG_INI',  'ESF_GTSII_DUMMY_STD','${DFILP}/${ENV_PREFIX}_ESFD3830_I17P_SII_MRG_INI_GTSII_DUMMY_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_SII_MRG_INI',  'ESF_GTSII_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESFD3830_I17P_SII_MRG_INI_GTSII_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17PMINV',  'I17P_SII_MRG_INI','')
			insert into BEST..TI17REQFNC values ('I17PQINV',  'I17P_SII_MRG_INI','')
			insert into BEST..TI17REQFNC values ('I17PQPOS',  'I17P_SII_MRG_INI','')
			insert into BEST..TI17REQFNC values ('I17PYINV',  'I17P_SII_MRG_INI','')
			insert into BEST..TI17REQFNC values ('I17PYPOS',  'I17P_SII_MRG_INI','')

	----------IDF_CT:   I17P_SII_MRG_STD ------------------

		insert into BEST..TI17FNC values ('I17P_SII_MRG_STD','Merge cashflow and discount at standard','ESFD3830',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17P_SII_MRG_STD',  'ESF_GTSII_ICR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_SII_MRG_STD',  'ESF_GTSII_CLACC_CASHFLOW','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_SII_MRG_STD',  'ESF_GTSII_REMAINTOPAY_ULAE','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_SII_MRG_STD',  'ESF_GTSII_IFRS17_CSM_ESCOMPTE','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_SII_MRG_STD',  'ESF_GTSII_IFRS17_CSM','${DFILP}/${ENV_PREFIX}_ESFD3690_I17P_IRV_ALL_STD_GTSII_IFRS17_CSM${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_SII_MRG_STD',  'ESF_GTSII_ESCOMPTE_DSI','${DFILP}/${ENV_PREFIX}_ESFD3620_I17P_DSC_DSI_STD_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_SII_MRG_STD',  'ESF_GTSII_ESCOMPTE_LKI','${DFILP}/${ENV_PREFIX}_ESFD3690_I17P_IRV_ALL_STD_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_SII_MRG_STD',  'ESF_GTSII_CASHFLOW_RAD_CUR','${DFILP}/${ENV_PREFIX}_ESFD3650_I17P_RAD_CUR_STD_GTSII_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_SII_MRG_STD',  'ESF_GTSII_ESCOMPTE_FWD','${DFILP}/${ENV_PREFIX}_ESFD3690_I17P_IRV_ALL_STD_GTSII_ESCOMPTE_FWD_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_SII_MRG_STD',  'ESF_GTSII_ESCOMPTE_RAD_DSI','${DFILP}/${ENV_PREFIX}_ESFD3620_I17P_RAD_DSI_STD_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_SII_MRG_STD',  'ESF_GTSII_IFRS17_REVENUE','${DFILP}/${ENV_PREFIX}_ESFD3690_I17P_IRV_ALL_STD_GTSII_IFRS17_REVENUE${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_SII_MRG_STD',  'ESF_GTSII_CASHFLOW_RAD_CKI','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_SII_MRG_STD',  'ESF_GTSII_CSM_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESFD3760_I17P_UOA_PRO_STD_GTSII_CSM_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_SII_MRG_STD',  'ESF_GTSII_ESCOMPTE_RAD_LKI','${DFILP}/${ENV_PREFIX}_ESFD3620_I17P_RAD_LKI_STD_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_SII_MRG_STD',  'ESF_GTSII_CASHFLOW_RAP_CUR','${DFILP}/${ENV_PREFIX}_ESFD3650_I17P_RAP_CUR_STD_GTSII_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_SII_MRG_STD',  'ESF_GTSII_GLOBAL_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESFD3630_I17P_IEX_ALL_STD_GTSII_GLOBAL_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_SII_MRG_STD',  'ESF_GTSII_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESFD3830_I17P_SII_MRG_STD_GTSII_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17PMINV',  'I17P_SII_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17PQINV',  'I17P_SII_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17PQPOS',  'I17P_SII_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17PYINV',  'I17P_SII_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17PYPOS',  'I17P_SII_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17PYPOSX',  'I17P_SII_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17PQPOSX',  'I17P_SII_MRG_STD','')

	----------IDF_CT:   I17S_SII_MRG_INI ------------------

		insert into BEST..TI17FNC values ('I17S_SII_MRG_INI','Merge cashflow and discount at inception','ESFD3830',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17S_SII_MRG_INI',  'ESF_GTSII_IFRS17_CSM','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_SII_MRG_INI',  'ESF_GTSII_CSM_CASHFLOW','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_SII_MRG_INI',  'ESF_GTSII_ESCOMPTE_DSI','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_SII_MRG_INI',  'ESF_GTSII_ESCOMPTE_FWD','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_SII_MRG_INI',  'ESF_GTSII_ESCOMPTE_UWD','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_SII_MRG_INI',  'ESF_GTSII_IFRS17_REVENUE','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_SII_MRG_INI',  'ESF_GTSII_CASHFLOW_RAD_CUR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_SII_MRG_INI',  'ESF_GTSII_ESCOMPTE_RAD_DSI','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_SII_MRG_INI',  'ESF_FSECIFRS','${DFILP}/${ENV_PREFIX}_ESFD3720_I17S_CSM_CRE_INI_FSECIFRS${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_SII_MRG_INI',  'ESF_GTSII_ICR','${DFILP}/${ENV_PREFIX}_ESFD3610_I17S_CSF_ALL_INI_GTSII_ICR${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_SII_MRG_INI',  'ESF_IADPERICASE_INI','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17S_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_SII_MRG_INI',  'ESF_IADPERICASE_DUMMY','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_DUMMY_I17S_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_SII_MRG_INI',  'ESF_GTSII_IFRS17_CSM_ESCOMPTE','${DFILP}/${ENV_PREFIX}_ESFD3710_I17S_CSM_CSU_INI_GTSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_SII_MRG_INI',  'ESF_GTSII_ESCOMPTE_LKI','${DFILP}/${ENV_PREFIX}_ESFD3620_I17S_DSC_LKI_INI_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_SII_MRG_INI',  'ESF_GTSII_CASHFLOW_RAD_CKI','${DFILP}/${ENV_PREFIX}_ESFD3650_I17S_RAD_CKI_INI_GTSII_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_SII_MRG_INI',  'ESF_GTSII_ESCOMPTE_RAD_LKI','${DFILP}/${ENV_PREFIX}_ESFD3620_I17S_RAD_LKI_INI_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_SII_MRG_INI',  'ESF_GTSII_CASHFLOW_RAP_CKI','${DFILP}/${ENV_PREFIX}_ESFD3650_I17S_RAP_CKI_INI_GTSII_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_SII_MRG_INI',  'ESF_GTSII_CLACC_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESFD3610_I17S_CSF_ALL_INI_GTSII_CLACC_CASHFLOW${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_SII_MRG_INI',  'ESF_GTSII_REMAINTOPAY_ULAE','${DFILP}/${ENV_PREFIX}_ESFD3610_I17S_CSF_ALL_INI_GTSII_RMTP_ULAE_SII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_SII_MRG_INI',  'ESF_GTSII_GLOBAL_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESFD3630_I17S_IEX_ALL_INI_GTSII_GLOBAL_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_SII_MRG_INI',  'ESF_GTSII_ONE_STD','${DFILP}/${ENV_PREFIX}_ESFD3830_I17S_SII_MRG_INI_GTSII_ONEFUT_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_SII_MRG_INI',  'ESF_GTSII_DUMMY_STD','${DFILP}/${ENV_PREFIX}_ESFD3830_I17S_SII_MRG_INI_GTSII_DUMMY_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_SII_MRG_INI',  'ESF_GTSII_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESFD3830_I17S_SII_MRG_INI_GTSII_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17SMINV',  'I17S_SII_MRG_INI','')
			insert into BEST..TI17REQFNC values ('I17SQINV',  'I17S_SII_MRG_INI','')
			insert into BEST..TI17REQFNC values ('I17SQPOS',  'I17S_SII_MRG_INI','')
			insert into BEST..TI17REQFNC values ('I17SYINV',  'I17S_SII_MRG_INI','')
			insert into BEST..TI17REQFNC values ('I17SYPOS',  'I17S_SII_MRG_INI','')

	----------IDF_CT:   I17S_SII_MRG_STD ------------------

		insert into BEST..TI17FNC values ('I17S_SII_MRG_STD','Merge cashflow and discount at standard','ESFD3830',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17S_SII_MRG_STD',  'ESF_GTSII_ICR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_SII_MRG_STD',  'ESF_GTSII_CLACC_CASHFLOW','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_SII_MRG_STD',  'ESF_GTSII_REMAINTOPAY_ULAE','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_SII_MRG_STD',  'ESF_GTSII_IFRS17_CSM_ESCOMPTE','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_SII_MRG_STD',  'ESF_GTSII_IFRS17_CSM','${DFILP}/${ENV_PREFIX}_ESFD3690_I17S_IRV_ALL_STD_GTSII_IFRS17_CSM${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_SII_MRG_STD',  'ESF_GTSII_ESCOMPTE_DSI','${DFILP}/${ENV_PREFIX}_ESFD3620_I17S_DSC_DSI_STD_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_SII_MRG_STD',  'ESF_GTSII_ESCOMPTE_LKI','${DFILP}/${ENV_PREFIX}_ESFD3690_I17S_IRV_ALL_STD_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_SII_MRG_STD',  'ESF_GTSII_CASHFLOW_RAD_CKI','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_SII_MRG_STD',  'ESF_GTSII_CASHFLOW_RAD_CUR','${DFILP}/${ENV_PREFIX}_ESFD3650_I17S_RAD_CUR_STD_GTSII_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_SII_MRG_STD',  'ESF_GTSII_CSM_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESFD3760_I17S_UOA_PRO_STD_GTSII_CSM_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_SII_MRG_STD',  'ESF_GTSII_ESCOMPTE_FWD','${DFILP}/${ENV_PREFIX}_ESFD3690_I17S_IRV_ALL_STD_GTSII_ESCOMPTE_FWD_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_SII_MRG_STD',  'ESF_GTSII_ESCOMPTE_RAD_DSI','${DFILP}/${ENV_PREFIX}_ESFD3620_I17S_RAD_DSI_STD_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_SII_MRG_STD',  'ESF_GTSII_ESCOMPTE_RAD_LKI','${DFILP}/${ENV_PREFIX}_ESFD3620_I17S_RAD_LKI_STD_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_SII_MRG_STD',  'ESF_GTSII_CASHFLOW_RAP_CUR','${DFILP}/${ENV_PREFIX}_ESFD3650_I17S_RAP_CUR_STD_GTSII_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_SII_MRG_STD',  'ESF_GTSII_IFRS17_REVENUE','${DFILP}/${ENV_PREFIX}_ESFD3690_I17S_IRV_ALL_STD_GTSII_IFRS17_REVENUE${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_SII_MRG_STD',  'ESF_GTSII_GLOBAL_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESFD3630_I17S_IEX_ALL_STD_GTSII_GLOBAL_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_SII_MRG_STD',  'ESF_GTSII_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESFD3830_I17S_SII_MRG_STD_GTSII_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17SMINV',  'I17S_SII_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17SQINV',  'I17S_SII_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17SQPOS',  'I17S_SII_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17SYINV',  'I17S_SII_MRG_STD','')
			insert into BEST..TI17REQFNC values ('I17SYPOS',  'I17S_SII_MRG_STD','')
go

