----------------------------------------------------------------------------------------------------------
-- [001] 07/09/2020 M.NAJI : SPIRA 87596 Intialisation du mapping  chaine par fichier  
-- [002] 28/09/2020 : JYP : SPIRA 83609 : microAOC, manage multi instance IDF_CT
-- [003] 03/11/2020 : M.NAJI : SPIRA 99999 : Optimisation et fusion des chaine ESP3610 et ESFD3610
----------------------------------------------------------------------------------------------------------


-------------------------------
--	Init  ESPD3610
-------------------------------


	if not exists ( select 1 from BEST..TI17CHN where CHAIN_CT='ESPD3610')  insert into BEST..TI17CHN values ('ESPD3610',  'Cach flow calculation jobs ESID3702A et ESID3703A')

		--  ESPD3610_BookingPOCEAnnuel ESPD3610_BookingPOCEAnnuel 

	delete BEST..TI17PERMFIL where IDF_CT ='EBS_ESPD3610'
	if not exists ( select 1 from BEST..TI17FNC where idf_ct ='EBS_ESPD3610'  ) insert into BEST..TI17FNC values ('EBS_ESPD3610',  'Post omega EBS')


	----------   Reqs of chain   ---------------------

	delete BEST..TI17REQCHN where   IDF_CT = 'EBS_ESPD3610' and  CHAIN_CT='ESPD3610'

	insert into BEST..TI17REQCHN values ('EBSEMINVB','ESPD3610','EBS_ESPD3610','Monthly INV EBS booking')
	insert into BEST..TI17REQCHN values ('EBSEQINV','ESPD3610','EBS_ESPD3610','Quarterly INV EBS')
	insert into BEST..TI17REQCHN values ('EBSEQINVB','ESPD3610','EBS_ESPD3610','Quarterly INV EBS booking')
	insert into BEST..TI17REQCHN values ('EBSEQPOS','ESPD3610','EBS_ESPD3610','Quarterly POS EBS')
	insert into BEST..TI17REQCHN values ('EBSEQPOSB','ESPD3610','EBS_ESPD3610','Quarterly POS EBS booking')
	insert into BEST..TI17REQCHN values ('EBSEQPOC','ESPD3610','EBS_ESPD3610','	Quarterly POC EBS')
	insert into BEST..TI17REQCHN values ('EBSEQPOCB','ESPD3610','EBS_ESPD3610','Quarterly POC EBS booking')
	insert into BEST..TI17REQCHN values ('EBSEYINV','ESPD3610','EBS_ESPD3610','Annual INV EBS')
	insert into BEST..TI17REQCHN values ('EBSEYINVB','ESPD3610','EBS_ESPD3610','Annual INV EBS booking')
	insert into BEST..TI17REQCHN values ('EBSEYPOS','ESPD3610','EBS_ESPD3610','Annual POS EBS')
	insert into BEST..TI17REQCHN values ('EBSEYPOSB','ESPD3610','EBS_ESPD3610','Annual POS EBS booking')
	insert into BEST..TI17REQCHN values ('EBSEYPOC','ESPD3610','EBS_ESPD3610','Annual POC EBS')
	insert into BEST..TI17REQCHN values ('EBSEYPOCB','ESPD3610','EBS_ESPD3610','Annual POC EBS booking')

	----------  Perms---------------------

	delete BEST..TI17PERMFIL where IDF_CT ='EBS_ESPD3610'


	-- INPUT
	INSERT INTO  BEST..TI17PERMFIL VALUES ( 'EBS_ESPD3610', 'EPO_DLDGTAR_E', '${DFILP}/${PCH}ESPD2570_DLDGTARSII${TYPEINV0}_E.dat', 'I', ' ' )
	INSERT INTO  BEST..TI17PERMFIL VALUES ( 'EBS_ESPD3610', 'ESF_DLDGTR_NP', '${DFILP}/empty.dat', 'I', ' ' )
	INSERT INTO  BEST..TI17PERMFIL VALUES ( 'EBS_ESPD3610', 'ESF_DLDGTR_P', '${DFILP}/empty.dat', 'I', ' ' )
	INSERT INTO  BEST..TI17PERMFIL VALUES ( 'EBS_ESPD3610', 'ESF_IADVPERICASE_P', '${DFILP}/empty.dat', 'I', ' ' )
	INSERT INTO  BEST..TI17PERMFIL VALUES ( 'EBS_ESPD3610', 'ESF_IRDPERICASE_NP', '${DFILP}/empty.dat', 'I', ' ' )
	INSERT INTO  BEST..TI17PERMFIL VALUES ( 'EBS_ESPD3610', 'EST_CURGTA', '${DFILP}/${PCH}ESPD3800_FTECLEDASO_EBS.dat', 'I', ' ' )
	INSERT INTO  BEST..TI17PERMFIL VALUES ( 'EBS_ESPD3610', 'EST_DLDGTAA', '${DFILP}/${PCH}ESID2220_DLDGTAASII${TYPEINV0}.dat', 'I', ' ' )
	INSERT INTO  BEST..TI17PERMFIL VALUES ( 'EBS_ESPD3610', 'EST_DLDGTAA_CUMULS_COUR', '${DFILP}/${PCH}ESID2210_DLDGTAASII${TYPEINV0}.dat', 'I', ' ' )
	INSERT INTO  BEST..TI17PERMFIL VALUES ( 'EBS_ESPD3610', 'EST_DLDGTAA_E_TRNCODEBS', '${DFILP}/${PCH}ESID2220_DLDGTAASII${TYPEINV0}.dat', 'I', ' ' )
	INSERT INTO  BEST..TI17PERMFIL VALUES ( 'EBS_ESPD3610', 'EST_DLREGTAR', '${DFILP}/${PCH}ESPD2550_DLREGTARSII${TYPEINV0}.dat', 'I', ' ' )
	INSERT INTO  BEST..TI17PERMFIL VALUES ( 'EBS_ESPD3610', 'EST_DLREMAJGTAR', '${DFILP}/${PCH}ESPD2550_DLREMAJGTARSII${TYPEINV0}.dat', 'I', ' ' )
	INSERT INTO  BEST..TI17PERMFIL VALUES ( 'EBS_ESPD3610', 'EST_DLSGTAA', '${DFILP}/${PCH}ESPD1800_DLSGTAASII${TYPEINV0}.dat', 'I', ' ' )
	INSERT INTO  BEST..TI17PERMFIL VALUES ( 'EBS_ESPD3610', 'EST_DLSGTAR', '${DFILP}/${PCH}ESPD1800_DLSGTARSII${TYPEINV0}.dat', 'I', ' ' )
	INSERT INTO  BEST..TI17PERMFIL VALUES ( 'EBS_ESPD3610', 'EST_FBOPRSLNK_TXT', '${DFILP}/${PCH}ESPT0000_FBOPRSLNK_TXT_${PARM_ICLODAT_D}.dat', 'I', ' ' )
	INSERT INTO  BEST..TI17PERMFIL VALUES ( 'EBS_ESPD3610', 'EST_FCTRFWH', '${DFILP}/${PCH}ESPD0060_FCTRFWH.dat', 'I', ' ' )
	INSERT INTO  BEST..TI17PERMFIL VALUES ( 'EBS_ESPD3610', 'EST_FCTRGRO', '${DFILP}/${PCH}ESPT0000_FCTRGRO.dat', 'I', ' ' )
	INSERT INTO  BEST..TI17PERMFIL VALUES ( 'EBS_ESPD3610', 'EST_FCTRGRO1', '${DFILP}/${PCH}ESPT0000_FCTRGRO1.dat', 'I', ' ' )
	INSERT INTO  BEST..TI17PERMFIL VALUES ( 'EBS_ESPD3610', 'EST_FCTRGROLESII', '${DFILP}/${PCH}ESPT0000_FCTRGROLESII.dat', 'I', ' ' )
	INSERT INTO  BEST..TI17PERMFIL VALUES ( 'EBS_ESPD3610', 'EST_FCURQUOT_TXT', '${DFILP}/${PCH}ESPT0000_FCURQUOT_TXT_${PARM_ICLODAT_D}.dat', 'I', ' ' )
	INSERT INTO  BEST..TI17PERMFIL VALUES ( 'EBS_ESPD3610', 'EST_FCURSII', '${DFILP}/${PCH}ESPT0000_FCURSII.dat', 'I', ' ' )
	INSERT INTO  BEST..TI17PERMFIL VALUES ( 'EBS_ESPD3610', 'EST_FLIBEL2', '${DFILP}/empty.dat', 'I', ' ' )
	INSERT INTO  BEST..TI17PERMFIL VALUES ( 'EBS_ESPD3610', 'EST_FPRSMAP_TXT', '${DFILP}/${PCH}ESPT0000_FPRSMAP_TXT_${PARM_ICLODAT_D}.dat', 'I', ' ' )
	INSERT INTO  BEST..TI17PERMFIL VALUES ( 'EBS_ESPD3610', 'EST_FRATINGRTO', '${DFILP}/${PCH}ESPT0000_FRATINGRTO.dat', 'I', ' ' )
	INSERT INTO  BEST..TI17PERMFIL VALUES ( 'EBS_ESPD3610', 'EST_FSEGPATTERNFWH', '${DFILP}/${PCH}ESPD0060_FSEGPATTERNFWH.dat', 'I', ' ' )
	INSERT INTO  BEST..TI17PERMFIL VALUES ( 'EBS_ESPD3610', 'EST_FSEGPATTERN_BDT', '${DFILP}/${PCH}ESPD0060_FSEGPATTERN_BDT.dat', 'I', ' ' )
	INSERT INTO  BEST..TI17PERMFIL VALUES ( 'EBS_ESPD3610', 'EST_FSEGPATTERN_CSF', '${DFILP}/${PCH}ESPD0060_FSEGPATTERN_CSF_${PARM_ICLODAT_D}.dat', 'I', ' ' )
	INSERT INTO  BEST..TI17PERMFIL VALUES ( 'EBS_ESPD3610', 'EST_FSEGPATTERN_ICR', '${DFILP}/${PCH}ESPD0060_FSEGPATTERN_ICR_${PARM_ICLODAT_D}.dat', 'I', ' ' )
	INSERT INTO  BEST..TI17PERMFIL VALUES ( 'EBS_ESPD3610', 'EST_FSEGPATTERN_INF', '${DFILP}/${PCH}ESPD0060_FSEGPATTERN_INF.dat', 'I', ' ' )
	INSERT INTO  BEST..TI17PERMFIL VALUES ( 'EBS_ESPD3610', 'EST_FTECLEDASII', '`if [ "${param_Context_id}" = "POSE" ];then echo ${DFILP}/empty.dat;else echo ${DFILP}/${PCH}ESPD3800_FTECLEDASIISO.dat;fi;`', ' ', ' ' )
	INSERT INTO  BEST..TI17PERMFIL VALUES ( 'EBS_ESPD3610', 'EST_FTECLEDASIISO', '`if [ "${param_Context_id}" = "POSE" ];then echo ${DFILP}/empty.dat;else echo ${DFILP}/${PCH}ESPD3800_FTECLEDASIISO.dat;fi;`', ' ', ' ' )
	INSERT INTO  BEST..TI17PERMFIL VALUES ( 'EBS_ESPD3610', 'EST_FTRSLNK_TXT', '${DFILP}/${PCH}ESPT0000_FTRSLNK_TXT_${PARM_ICLODAT_D}.dat', 'I', ' ' )
	INSERT INTO  BEST..TI17PERMFIL VALUES ( 'EBS_ESPD3610', 'EST_FULAERAT', '${DFILP}/${PCH}ESPD0060_FULAERAT${TYPEINV0}_${PARM_ICLODAT_D}.dat', 'I', ' ' )
	INSERT INTO  BEST..TI17PERMFIL VALUES ( 'EBS_ESPD3610', 'EST_FWHGTA', '${DFILP}/${PCH}ESPT0000_FWHGTA.dat', 'I', ' ' )
	INSERT INTO  BEST..TI17PERMFIL VALUES ( 'EBS_ESPD3610', 'EST_FWHGTR', '${DFILP}/${PCH}ESPT0000_FWHGTR.dat', 'I', ' ' )
	INSERT INTO  BEST..TI17PERMFIL VALUES ( 'EBS_ESPD3610', 'EST_IADPERICASE', '${DFILP}/${PCH}ESPT0000_IADPERICASE_${PARM_ICLODAT_D}.dat', 'I', ' ' )
	INSERT INTO  BEST..TI17PERMFIL VALUES ( 'EBS_ESPD3610', 'EST_IADPERICASE_STD', '${DFILP}/empty.dat', 'I', ' ' )
	INSERT INTO  BEST..TI17PERMFIL VALUES ( 'EBS_ESPD3610', 'EST_IRDPERICASE0', '${DFILP}/${PCH}ESPT0000_IRDPERICASE0.dat', 'I', ' ' )
	insert into BEST..TI17PERMFIL values  ( 'EBS_ESPD3610',  'EST_FPLATXCUMALL','${DFILP}/${PCH}ESPT0000_FPLATXCUMALL.dat','I','')
		
	-- OUTPUT
	INSERT INTO  BEST..TI17PERMFIL VALUES ( 'EBS_ESPD3610', 'ESF_GTSII_ICR', '${DFILT}/${ENV_PREFIX}_ESPD3610_ESID3703A_${param_Context_id}_GTSII_ICR.dat', 'O', ' ' )
	INSERT INTO  BEST..TI17PERMFIL VALUES ( 'EBS_ESPD3610', 'EST_DLCUMGTAAR', '${DFILP}/${PCH}ESPD3610_DLCUMGTAAR_${param_Context_id}.dat', 'O', ' ' )
	INSERT INTO  BEST..TI17PERMFIL VALUES ( 'EBS_ESPD3610', 'EST_DLCUMGTAAR_IBNR_FUTCLAIMS', '${DFILP}/${PCH}ESPD3610_DLCUMGTAAR_IBNR_FUTCLAIMS_${param_Context_id}.dat', 'O', ' ' )
	INSERT INTO  BEST..TI17PERMFIL VALUES ( 'EBS_ESPD3610', 'EST_GTSII_CASHFLOW', '${DFILP}/${PCH}ESPD3610_GTSII_CASHFLOW_$[param_Context_id}_${PARM_ICLODAT_D}.dat', 'O', ' ' )
	INSERT INTO  BEST..TI17PERMFIL VALUES ( 'EBS_ESPD3610', 'EST_GTSII_CLACC_CASHFLOW', '${DFILP}/${ENV_PREFIX}_ESPD3610_GTSII_CLACC_CASHFLOW${TYPEINV0}.dat', 'O', ' ' )
	INSERT INTO  BEST..TI17PERMFIL VALUES ( 'EBS_ESPD3610', 'EST_GTSII_GLOBAL_CASHFLOW', '${DFILP}/${PCH}ESPD3610_GTSII_GLOBAL_CASHFLOW${TYPEINV0}_${PARM_ICLODAT_D}.dat', 'O', ' ' )
	INSERT INTO  BEST..TI17PERMFIL VALUES ( 'EBS_ESPD3610', 'EST_GTSII_REMAINTOPAY_ULAE', '${DFILP}/${PCH}ESPD3610_GTSII_REMAINTOPAY_ULAE_SII${TYPEINV0}_${PARM_ICLODAT_D}.dat', 'Q', ' ' )
	INSERT INTO  BEST..TI17PERMFIL VALUES ( 'EBS_ESPD3610', 'EST_GTSII_REMAINTOPAY_ULAEINF', '${DFILP}/${PCH}ESPD3610_GTSII_REMAINTOPAY_ULAEINF_SII${TYPEINV0}_${PARM_ICLODAT_D}.dat', 'O', ' ' )

	INSERT INTO  BEST..TI17PERMFIL VALUES ( 'EBS_ESPD3610', 'EST_REMAINTOPAY_ULAE', '${DFILI}/${PCH}ESPD3610_EST_REMAINTOPAY_ULAE.dat', 'O', ' ' )
	INSERT INTO  BEST..TI17PERMFIL VALUES ( 'EBS_ESPD3610', 'EST_CASHFLOW', '${DFILI}/${PCH}ESPD3610_EST_CASHFLOW.dat', 'O', ' ' )
	INSERT INTO  BEST..TI17PERMFIL VALUES ( 'EBS_ESPD3610', 'EST_REMAINTOPAY_FHNI', '${DFILI}/${PCH}ESPD3610_EST_REMAINTOPAY_FHNI.dat', 'O', ' ' )
	INSERT INTO  BEST..TI17PERMFIL VALUES ( 'EBS_ESPD3610', 'EST_DLSIIGTAA', '${DFILI}/${PCH}ESPD3610_EST_DLSIIGTAA.dat', 'O', ' ' )
	INSERT INTO  BEST..TI17PERMFIL VALUES ( 'EBS_ESPD3610', 'EST_IADPERICASE_CTRGRO', '${DFILI}/${PCH}ESPD3610_EST_IADPERICASE_CTRGRO.dat', 'O', ' ' )


  ---------- micro AOC AAX_ESPD3610

	delete BEST..TI17PERMFIL where IDF_CT ='AAX_ESPD3610'
	if not exists ( select 1 from BEST..TI17FNC where idf_ct ='AAX_ESPD3610'  ) insert into BEST..TI17FNC values ('AAX_ESPD3610',  'MicroAOC Cashflow AA0')

	----------  Perms---------------------

		insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_FLIBEL2','${DFILP}/empty.dat',' ','')
		insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_FTECLEDASII','${DFILP}/empty.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EPO_FTECLEDASIISO','${DFILP}/empty.dat',' ','')
		insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_FTECLEDASIISO','${DFILP}/empty.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_GTR','${DFILP}/${PCH}ESIX7000_GTR.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_FPLC','${DFILP}/${PCH}ESPT0000_FPLC.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_FT','${DFILP}/${PCH}ESPT0000_${VNORME}_ESID2210_FT_EBS.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_FTFAC','${DFILP}/${PCH}ESPT0000_FTFAC.dat',' ','')
		insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_FWHGTA','${DFILP}/${PCH}ESPT0000_FWHGTA.dat',' ','')
		insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_FWHGTR','${DFILP}/${PCH}ESPT0000_FWHGTR.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_GTEP','${DFILP}/${PCH}ESPD4000_GTEPSIISO.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EPO_FCLIENT','${DFILP}/${PCH}ESPT0000_FCLIENT.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EPO_FCPLACC','${DFILP}/${PCH}ESPT0000_FCPLACC.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EPO_FCTRULT','${DFILP}/${PCH}ESPT0000_FCTRULT.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_DLCGTAA','${DFILP}/${PCH}ESPT0000_DLCGTAA.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_FCLIENT','${DFILP}/${PCH}ESPT0000_FCLIENT.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_FCPLACC','${DFILP}/${PCH}ESPT0000_FCPLACC.dat',' ','')
		insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_FCTRFWH','${DFILP}/${PCH}ESPD0060_FCTRFWH.dat',' ','')
		insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_FCTRGRO','${DFILP}/${PCH}ESPT0000_FCTRGRO.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_FCTRULT','${DFILP}/${PCH}ESPT0000_FCTRULT.dat',' ','')
		insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_FCURSII','${DFILP}/${PCH}ESPT0000_FCURSII.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_FDETTRS','${DFILP}/${PCH}ESPT0000_FDETTRS.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_FTRSLNK','${DFILP}/${PCH}ESPT0000_FTRSLNK.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_IBNR','${DFILP}/${PCH}ESID2210_${VNORME}_ESID2210_IBNR_EBSSO.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_LABOCY1','${DFILP}/${PCH}ESPT0000_LABOCY1.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EPO_DLEIGTAA','${DFILP}/${PCH}ESPD2550_${VNORME}_ESPD2550_DLEIGTAA.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EPO_FCURQUOT','${DFILP}/${PCH}ESPT0000_FCURQUOT.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EPO_FTECLEDR','${DFILP}/${PCH}ESPT0000_FTECLEDR.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_CTRULT02','${DFILP}/${PCH}ESPT0000_CTRULT02.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_DLGTAAPA','${DFILP}/${PCH}ESPT0000_DLGTAAPA.dat',' ','')
		insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_FCTRGRO1','${DFILP}/${PCH}ESPT0000_FCTRGRO1.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_FCURQUOT','${DFILP}/${PCH}ESPT0000_FCURQUOT.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_FSSDACTR','${DFILP}/${PCH}ESPT0000_FSSDACTR.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_FTFAMCHG','${DFILP}/${PCH}ESPT0000_FTFAMCHG.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_FTTR_PRM','${DFILP}/${PCH}ESPT0000_FTTR_PRM.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EPO_FTRSLNK8','${DFILI}/${PCH}_ESPD0060_FTRSLNK8.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_DLSGTR','${DFILP}/${PCH}ESPD1800_DLSGTRSIISO.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EPO_FBOPRSLNK','${DFILP}/${PCH}ESPT0000_FBOPRSLNK.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EPO_FPLACEMT0','${DFILP}/${PCH}ESPT0000_FPLACEMT0.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_DCGTAALOA','${DFILP}/${PCH}ESPT0000_DCGTAALOA.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_DLCUMGTAA','${DFILP}/${PCH}ESPT0000_DLCUMGTAA.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_DLGTAAPRE','${DFILP}/${PCH}ESPT0000_DLGTAAPRE.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_FBOPRSLNK','${DFILP}/${PCH}ESPT0000_FBOPRSLNK.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_FLOARAT','${DFILP}/${PCH}ESID2210_${VNORME}_ESID2210_FLOARAT_EBS.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_FPLATXCUM','${DFILP}/${PCH}ESPT0000_FPLATXCUM.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_IADPERIFR','${DFILP}/${PCH}ESPT0000_IADPERIFR.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EPO_DLDGTRSO','${DFILP}/${PCH}ESPD2570_${VNORME}_FUTR_LR_NP_DLDGTRSIISO.dat',' ','')
		insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_DLDGTAA','${DFILP}/${PCH}ESID2220_${VNORME}_FUTR_LR_DLDGTAASIISO.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_DLREGTR','${DFILP}/${PCH}ESPD2550_${VNORME}_ESPD2550_DLREGTRSIISO.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_DLRGTAA','${DFILP}/${PCH}ESPD2550_${VNORME}_ESPD2550_DLRGTAASIISO.dat',' ','')
		insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_DLSGTAA','${DFILP}/${PCH}ESPD1800_DLSGTAASIISO.dat',' ','')
		insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_DLSGTAR','${DFILP}/${PCH}ESPD1800_DLSGTARSIISO.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EPO_FCTREST0','${DFILP}/${PCH}ESPD0060_FCTREST0_EBS.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EPO_FPLACEMT22','${DFILI}/${PCH}ESPD0060_FPLACEMT22.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EPO_FTECLEDRSO','${DFILP}/${PCH}ESPD3800_FTECLEDRSO.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_ARCSTATGTA','${DFILP}/${PCH}ESIX7000_ARCSTATGTA.dat',' ','')
		insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_CURGTA','${DFILP}/${PCH}ESPD3800_FTECLEDASO_EBS.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_DLASIIGTR','${DFILP}/${PCH}ESPD3630_${IDF_CT}_DLASIIGTRSO.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_DLCGTAAREC','${DFILP}/${PCH}ESPT0000_DLCGTAAREC.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_DLCUMGTAAS','${DFILP}/${PCH}ESPT0000_DLCUMGTAAS.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_DLDSIIGTR','${DFILP}/${PCH}ESPD3620_${IDF_CT}_DLDSIIGTRSO.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_DLGTAAFPRE','${DFILP}/${PCH}ESPT0000_DLGTAAFPRE.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_DLGTAAPNAE','${DFILP}/${PCH}ESPT0000_DLGTAAPNAE.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_DLGTAARPPE','${DFILP}/${PCH}ESPT0000_DLGTAARPPE.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_DLGTAUPUC','${DFILP}/${PCH}ESID2220_${VNORME}_FUTR_LR_DLGTAUPUC__.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_DTSTATGTAA','${DFILP}/${PCH}ESPT0000_DTSTATGTAA.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_FPRMLOA','${DFILP}/${PCH}ESID2210_${VNORME}_ESID2210_FPRMLOA_EBSSO.dat',' ','')
		insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_FRATINGRTO','${DFILP}/${PCH}ESPT0000_FRATINGRTO.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_FRISKMSII','${DFILP}/${PCH}ESPD0060_FRISKMSIISO.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_FTHRHLDUWY','${DFILP}/${PCH}ESPT0000_FTHRHLDUWY.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_IADPERIFCI','${DFILP}/${PCH}ESPT0000_IADPERIFCI.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_IADPERIFCT','${DFILP}/${PCH}ESPT0000_IADPERIFCT.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_IGTAAF','${DFILP}/${PCH}ESPD3800_FTECLEDASO_EBS.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EPO_DLDGTR_E','${DFILP}/${PCH}ESPD2570_${VNORME}_FUTR_LR_NP_DLDGTRSIISO_E.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EPO_FCTREST1','${DFILP}/${PCH}ESID2210_${VNORME}_ESID2210_FCTREST1SIISO.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EPO_FCTRESTA','${DFILP}/${PCH}ESPD0060_FCTRESTASIISO.dat',' ','')
		insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_DLREGTAR','${DFILP}/${PCH}ESPD2550_${VNORME}_ESPD2550_DLREGTARSIISO.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_DLASIIGTAA','${DFILP}/${PCH}ESPD3630_${IDF_CT}_DLASIIGTAASO.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_DLASIIGTAR','${DFILP}/${PCH}ESPD3630_${IDF_CT}_DLASIIGTARSO.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_DLCGTAAEPPE','${DFILP}/${PCH}ESPT0000_DLCGTAAEPPE.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_DLDSIIGTAA','${DFILP}/${PCH}ESPD3620_${IDF_CT}_DLDSIIGTAASO.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_DLDSIIGTAR','${DFILP}/${PCH}ESPD3620_${IDF_CT}_DLDSIIGTARSO.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_FTECLEDSII','${DFILP}/${PCH}ESPD3700_${IDF_CT}_FTECLEDSIISO.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_FUTURE_EBS','${DFILP}/${PCH}ESID2220_${VNORME}_FUTR_LR_FUTURE_EBSSO.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EPO_FTECLEDASO','${DFILP}/${PCH}ESPD3800_FTECLEDASO_EBS.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EPO_IRDPERICASE0','${DFILP}/${PCH}ESPT0000_IRDPERICASE0.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_DLCUMGTAATOT','${DFILI}/${PCH}ESID2210_${VNORME}_ESID2210_DLCUMGTAATOT.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_DLGTAATFPNAE','${DFILP}/${PCH}ESPT0000_DLGTAATFPNAE.dat',' ','')
		insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_FCTRGROLESII','${DFILP}/${PCH}ESPT0000_FCTRGROLESII.dat',' ','')
		insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_FPLATXCUMALL','${DFILP}/${PCH}ESPT0000_FPLATXCUMALL.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_FTECLEDASO','${DFILP}/${PCH}ESPD3800_FTECLEDASO_EBS.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_IRDPERICASE0','${DFILP}/${PCH}ESPT0000_IRDPERICASE0.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_DLCTREST3_O2','${DFILI}/${PCH}ESFD2003D_${VNORME}_FUTR_LR_DLCTREST3_O2.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_DLREMAJGTR','${DFILP}/${PCH}ESPD2550_${VNORME}_ESPD2550_DLREMAJGTRSIISO.dat',' ','')
		insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_DLREMAJGTAR','${DFILP}/${PCH}ESPD2550_${VNORME}_ESPD2550_DLREMAJGTARSIISO.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_CTRESTLOSPBPAP','${DFILI}/${PCH}ESID2210_${VNORME}_ESID2210_CTRESTLOSPBPAP.dat',' ','')
		insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_FSEGPATTERNFWH','${DFILP}/${PCH}ESPD0060_FSEGPATTERNFWH.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EPO_GTEP_POOL','${PCH}ESPD2050_GTEP_POOL_${param_Context_id}.dat',' ','')
		insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_FSEGPATTERN_BDT','${DFILP}/${PCH}ESPD0060_FSEGPATTERN_BDT.dat',' ','')
		insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_FSEGPATTERN_ICR','${DFILP}/${PCH}ESPD0060_FSEGPATTERN_ICR.dat',' ','')
		insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_FSEGPATTERN_INF','${DFILP}/${PCH}ESPD0060_FSEGPATTERN_INF.dat',' ','')
		insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_DLDGTAA_CUMULS_COUR','${DFILP}/${PCH}ESID2210_${VNORME}_ESID2210_DLDGTAASIISO.dat',' ','')
		insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_DLDGTAA_E_TRNCODEBS','${DFILP}/${PCH}ESID2220_${VNORME}_FUTR_LR_DLDGTAASIISO.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EPO_FUTURE_RETRO_EBS','${DFILP}/${PCH}ESPD2570_${VNORME}_FUTR_LR_NP_FUTURE_RETRO_EBS.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_FPRSMAP','${DFILP}/${PCH}ESPT0000_FPRSMAP_${PARM_ICLODAT_D}.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_DLEIFTECLEDSIIEP','${DFILP}/${PCH}ESPD4000_DLEIFTECLEDSIIEPSO.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_GTSII_RISKMARGIN','${DFILP}/${PCH}ESPD3700_${IDF_CT}_GTSII_RISKMARGINSO.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EPO_DLDGTR_CUMULS_PREC','${DFILP}/${PCH}ESPD2570_${VNORME}_FUTR_LR_NP_DLDGTR_CUMULS_PREC.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EPO_RETITDPRM_UPR_ACT','${DFILP}/${PCH}ESPD0060_RETITDPRM_UPR_ACTSO.dat',' ','')
		insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_FULAERAT','${DFILP}/${PCH}ESPD0060_FULAERATSO_${PARM_ICLODAT_D}.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_GTSII_ESCOMPTE_CLM','${DFILP}/${PCH}ESPD3700_${IDF_CT}_GTSII_ESCOMPTE_CLM.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_BLANCHIMENT_RPCC','${DFILP}/${PCH}ESID2210_${VNORME}_ESID2210_BLANCHIMENT_RPCCSIISO.dat',' ','')
		insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_IADPERICASE','${DFILP}/${PCH}ESPT0000_IADPERICASE_${PARM_ICLODAT_D}.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_FSEGEST','${DFILP}/${PCH}ESPD0060_FSEGEST_SOLVENCYSO_${PARM_ICLODAT_D}.dat',' ','')
		insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_FSEGPATTERN_CSF','${DFILP}/${PCH}ESPD0060_FSEGPATTERN_CSF_${PARM_ICLODAT_D}.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_FSEGPATTERN_DSC','${DFILP}/${PCH}ESPD0060_FSEGPATTERN_DSC_${PARM_ICLODAT_D}.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_FSEGEST_SOLVENCY','${DFILP}/${PCH}ESPD0060_FSEGEST_SOLVENCYSO_${PARM_ICLODAT_D}.dat',' ','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EPO_DLEIFTECLEDSIIEI_POOL','${PCH}ESPD2050_DLEIFTECLEDSIIEI_POOL_${param_Context_id}.dat',' ','')
		insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_GTSII_GLOBAL_CASHFLOW','${DFILP}/${PCH}ESPD3610_${IDF_CT}_GTSII_GLOBAL_CASHFLOWSO_${PARM_ICLODAT_D}.dat',' ','')
		insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_GTSII_REMAINTOPAY_ULAE','${DFILP}/${PCH}ESPD3610_${IDF_CT}_GTSII_REMAINTOPAY_ULAE_SIISO_${PARM_ICLODAT_D}.dat',' ','')
		insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_GTSII_REMAINTOPAY_ULAEINF','${DFILP}/${PCH}ESPD3610_${IDF_CT}_GTSII_REMAINTOPAY_ULAEINF_SIISO_${PARM_ICLODAT_D}.dat',' ','')
		insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'ESF_DLDGTR_P','${DFILP}/empty.dat','I','')
		insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'ESF_DLDGTR_NP','${DFILP}/empty.dat','I','')
		insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'ESF_IADVPERICASE_P','${DFILP}/empty.dat','I','')
		insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'ESF_IRDPERICASE_NP','${DFILP}/empty.dat','I','')
		insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_IADPERICASE_STD','${DFILP}/empty.dat','I','')
		insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_FPRSMAP_TXT','${DFILP}/${PCH}ESPT0000_FPRSMAP_TXT_${PARM_ICLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_FTRSLNK_TXT','${DFILP}/${PCH}ESPT0000_FTRSLNK_TXT_${PARM_ICLODAT_D}.dat','I','')
		--insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_IRDPERICASE','${DFILI}/${ENV_PREFIX}_ESID0060_IRDPERICASE0_${CLODAT}.dat','I','')
		insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_FCURQUOT_TXT','${DFILP}/${PCH}ESPT0000_FCURQUOT_TXT_${PARM_ICLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_FBOPRSLNK_TXT','${DFILP}/${PCH}ESPT0000_FBOPRSLNK_TXT_${PARM_ICLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EPO_DLDGTAR_E','${DFILP}/${PCH}ESPD2570_${VNORME}_FUTR_LR_NP_DLDGTARSIISO_E.dat','O','')
		insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_DLCUMGTAAR','${DFILP}/${PCH}ESPD3610_${IDF_CT}_DLCUMGTAAR_POSE.dat','O','')
		insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_GTSII_CASHFLOW','${DFILP}/${PCH}ESPD3610_${IDF_CT}_GTSII_CASHFLOW_POSE_${PARM_ICLODAT_D}.dat','O','')
		insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_DLCUMGTAAR_IBNR_FUTCLAIMS','${DFILP}/${PCH}ESPD3610_${IDF_CT}_DLCUMGTAAR_IBNR_FUTCLAIMS_POSE.dat','O','')
		insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'ESF_GTSII_ICR','${DFILT}/${ENV_PREFIX}_ESPD3610_${IDF_CT}_ESID3703A_${param_Context_id}_GTSII_ICR.dat','O','')
		insert into BEST..TI17PERMFIL values ('AAX_ESPD3610',  'EST_GTSII_CLACC_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESPD3610_${IDF_CT}_GTSII_CLACC_CASHFLOW${TYPEINV0}.dat','O','')

	----------   Reqs of chain   ---------------------
		delete BEST..TI17REQCHN where   IDF_CT = 'AAX_ESPD3610' and  CHAIN_CT='ESPD3610'
		insert into BEST..TI17REQCHN values ('POSO',  'ESPD3610','AAX_ESPD3610','AAX_ESPD3610')
		insert into BEST..TI17REQCHN values ('POCO',  'ESPD3610','AAX_ESPD3610','AAX_ESPD3610')


  if @@servername = "DEV_TPO2"
           UPDATE BEST..TI17PERMFIL  SET   PATHPATTRN_LL = str_replace(PATHPATTRN_LL,"${DFIL","${XDFIL") WHERE IO in ("I") and IDF_CT = 'EBS_ESPD3610'


GO




