-------------------------------
--mapping of  ESFD2570

	----------   Clean tables   ---------------------

	delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD2570')
	delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD2570')
	delete BEST..TI17FNC where CHAIN_CT='ESFD2570'
	delete BEST..TI17CHN  where CHAIN_CT='ESFD2570'

	insert into BEST..TI17CHN values ('ESFD2570',  'Retro NP at Inception')

	----------IDF_CT:   I17G_ESFD2570___AA0 ------------------

		insert into BEST..TI17FNC values ('I17G_ESFD2570___AA0','Micro AOC FutureLR NP','ESFD2570',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA0',  'EST_FTRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA0',  'EPO_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA0',  'EPO_FBOPRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA0',  'EPO_FTECLEDRSO','${DFILP}/${ENV_PREFIX}_ESFD4050_FTECLEDR_I4I_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA0',  'EPO_DLSGTRSII_AE','${DFILP}/${ENV_PREFIX}_ESPD1800_DLSGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA0',  'EPO_FPLACEMT22','${DFILP}/${ENV_PREFIX}_ESPD0060_FPLACEMT22_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA0',  'EPO_IRDPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5010_IRDPERICASE0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA0',  'EPO_RETITDPRM_UPR_ACT','${DFILP}/${ENV_PREFIX}_ESPD0060_RETITDPRM_UPR_ACT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA0',  'EPO_DLDGTRCO','${DFILP}/${ENV_PREFIX}_ESFD2570_I17G_ESFD2570___AA0_DLDGTRSIICO.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA0',  'EPO_DLDGTRSO','${DFILP}/${ENV_PREFIX}_ESFD2570_I17G_ESFD2570___AA0_DLDGTRSII${TYPEINV}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA0',  'EPO_DLDGTR_E','${DFILP}/${ENV_PREFIX}_ESFD2570_I17G_ESFD2570___AA0_DLDGTRSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA0',  'EST_RETITDPRM','${DFILP}/${ENV_PREFIX}_ESFD2570_I17G_ESFD2570___AA0_RETITDPRM_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA0',  'EPO_DLDGTAR_E','${DFILP}/${ENV_PREFIX}_ESFD2570_I17G_ESFD2570___AA0_DLDGTARSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA0',  'EST_RETUPR_ESTIME','${DFILP}/${ENV_PREFIX}_ESFD2570_I17G_ESFD2570___AA0_RETUPR_ESTIME_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA0',  'EPO_FUTURE_RETRO_EBS','${DFILP}/${ENV_PREFIX}_ESFD2570_I17G_ESFD2570___AA0_FUTURE_RETRO_EBS${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA0',  'EPO_DLSGTRSII_AE_RETRONP','${DFILP}/${ENV_PREFIX}_ESFD2570_I17G_ESFD2570___${TYPEAOC_CT}_AE_RETRONP_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('INVO',  'I17G_ESFD2570___AA0','INVO')
			insert into BEST..TI17REQFNC values ('POCO',  'I17G_ESFD2570___AA0','POCO')
			insert into BEST..TI17REQFNC values ('POSO',  'I17G_ESFD2570___AA0','POSO')

	----------IDF_CT:   I17G_ESFD2570___AA1 ------------------

		insert into BEST..TI17FNC values ('I17G_ESFD2570___AA1','Micro AOC FutureLR NP','ESFD2570',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA1',  'EST_FTRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA1',  'EPO_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA1',  'EPO_FBOPRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA1',  'EPO_FTECLEDRSO','${DFILP}/${ENV_PREFIX}_ESFD4050_FTECLEDR_I4I_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA1',  'EPO_DLSGTRSII_AE','${DFILP}/${ENV_PREFIX}_ESPD1800_DLSGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA1',  'EPO_FPLACEMT22','${DFILP}/${ENV_PREFIX}_ESPD0060_FPLACEMT22_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA1',  'EPO_IRDPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5010_IRDPERICASE0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA1',  'EPO_RETITDPRM_UPR_ACT','${DFILP}/${ENV_PREFIX}_ESPD0060_RETITDPRM_UPR_ACT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA1',  'EPO_DLDGTRCO','${DFILP}/${ENV_PREFIX}_ESFD2570_I17G_ESFD2570___AA1_DLDGTRSIICO.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA1',  'EPO_DLDGTRSO','${DFILP}/${ENV_PREFIX}_ESFD2570_I17G_ESFD2570___AA1_DLDGTRSII${TYPEINV}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA1',  'EPO_DLDGTR_E','${DFILP}/${ENV_PREFIX}_ESFD2570_I17G_ESFD2570___AA1_DLDGTRSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA1',  'EST_RETITDPRM','${DFILP}/${ENV_PREFIX}_ESFD2570_I17G_ESFD2570___AA1_RETITDPRM_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA1',  'EPO_DLDGTAR_E','${DFILP}/${ENV_PREFIX}_ESFD2570_I17G_ESFD2570___AA1_DLDGTARSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA1',  'EST_RETUPR_ESTIME','${DFILP}/${ENV_PREFIX}_ESFD2570_I17G_ESFD2570___AA1_RETUPR_ESTIME_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA1',  'EPO_FUTURE_RETRO_EBS','${DFILP}/${ENV_PREFIX}_ESFD2570_I17G_ESFD2570___AA1_FUTURE_RETRO_EBS${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA1',  'EPO_DLSGTRSII_AE_RETRONP','${DFILP}/${ENV_PREFIX}_ESFD2570_I17G_ESFD2570___${TYPEAOC_CT}_AE_RETRONP_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('INVO',  'I17G_ESFD2570___AA1','INVO')
			insert into BEST..TI17REQFNC values ('POCO',  'I17G_ESFD2570___AA1','POCO')
			insert into BEST..TI17REQFNC values ('POSO',  'I17G_ESFD2570___AA1','POSO')

	----------IDF_CT:   I17G_ESFD2570___AA2 ------------------

		insert into BEST..TI17FNC values ('I17G_ESFD2570___AA2','Micro AOC FutureLR NP','ESFD2570',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA2',  'EST_FTRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA2',  'EPO_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA2',  'EPO_FBOPRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA2',  'EPO_FTECLEDRSO','${DFILP}/${ENV_PREFIX}_ESFD4050_FTECLEDR_I4I_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA2',  'EPO_DLSGTRSII_AE','${DFILP}/${ENV_PREFIX}_ESPD1800_DLSGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA2',  'EPO_FPLACEMT22','${DFILP}/${ENV_PREFIX}_ESPD0060_FPLACEMT22_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA2',  'EPO_IRDPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5010_IRDPERICASE0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA2',  'EPO_RETITDPRM_UPR_ACT','${DFILP}/${ENV_PREFIX}_ESPD0060_RETITDPRM_UPR_ACT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA2',  'EPO_DLDGTRCO','${DFILP}/${ENV_PREFIX}_ESFD2570_I17G_ESFD2570___AA2_DLDGTRSIICO.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA2',  'EPO_DLDGTRSO','${DFILP}/${ENV_PREFIX}_ESFD2570_I17G_ESFD2570___AA2_DLDGTRSII${TYPEINV}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA2',  'EPO_DLDGTR_E','${DFILP}/${ENV_PREFIX}_ESFD2570_I17G_ESFD2570___AA2_DLDGTRSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA2',  'EST_RETITDPRM','${DFILP}/${ENV_PREFIX}_ESFD2570_I17G_ESFD2570___AA2_RETITDPRM_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA2',  'EPO_DLDGTAR_E','${DFILP}/${ENV_PREFIX}_ESFD2570_I17G_ESFD2570___AA2_DLDGTARSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA2',  'EST_RETUPR_ESTIME','${DFILP}/${ENV_PREFIX}_ESFD2570_I17G_ESFD2570___AA2_RETUPR_ESTIME_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA2',  'EPO_FUTURE_RETRO_EBS','${DFILP}/${ENV_PREFIX}_ESFD2570_I17G_ESFD2570___AA2_FUTURE_RETRO_EBS${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA2',  'EPO_DLSGTRSII_AE_RETRONP','${DFILP}/${ENV_PREFIX}_ESFD2570_I17G_ESFD2570___${TYPEAOC_CT}_AE_RETRONP_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('INVO',  'I17G_ESFD2570___AA2','INVO')
			insert into BEST..TI17REQFNC values ('POCO',  'I17G_ESFD2570___AA2','POCO')
			insert into BEST..TI17REQFNC values ('POSO',  'I17G_ESFD2570___AA2','POSO')

	----------IDF_CT:   I17G_ESFD2570___AA3 ------------------

		insert into BEST..TI17FNC values ('I17G_ESFD2570___AA3','Micro AOC FutureLR NP','ESFD2570',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA3',  'EST_FTRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA3',  'EPO_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA3',  'EPO_FBOPRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA3',  'EPO_FTECLEDRSO','${DFILP}/${ENV_PREFIX}_ESFD4050_FTECLEDR_I4I_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA3',  'EPO_DLSGTRSII_AE','${DFILP}/${ENV_PREFIX}_ESPD1800_DLSGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA3',  'EPO_FPLACEMT22','${DFILP}/${ENV_PREFIX}_ESPD0060_FPLACEMT22_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA3',  'EPO_IRDPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5010_IRDPERICASE0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA3',  'EPO_RETITDPRM_UPR_ACT','${DFILP}/${ENV_PREFIX}_ESPD0060_RETITDPRM_UPR_ACT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA3',  'EPO_DLDGTRCO','${DFILP}/${ENV_PREFIX}_ESFD2570_I17G_ESFD2570___AA3_DLDGTRSIICO.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA3',  'EPO_DLDGTRSO','${DFILP}/${ENV_PREFIX}_ESFD2570_I17G_ESFD2570___AA3_DLDGTRSII${TYPEINV}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA3',  'EPO_DLDGTR_E','${DFILP}/${ENV_PREFIX}_ESFD2570_I17G_ESFD2570___AA3_DLDGTRSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA3',  'EST_RETITDPRM','${DFILP}/${ENV_PREFIX}_ESFD2570_I17G_ESFD2570___AA3_RETITDPRM_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA3',  'EPO_DLDGTAR_E','${DFILP}/${ENV_PREFIX}_ESFD2570_I17G_ESFD2570___AA3_DLDGTARSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA3',  'EST_RETUPR_ESTIME','${DFILP}/${ENV_PREFIX}_ESFD2570_I17G_ESFD2570___AA3_RETUPR_ESTIME_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA3',  'EPO_FUTURE_RETRO_EBS','${DFILP}/${ENV_PREFIX}_ESFD2570_I17G_ESFD2570___AA3_FUTURE_RETRO_EBS${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_ESFD2570___AA3',  'EPO_DLSGTRSII_AE_RETRONP','${DFILP}/${ENV_PREFIX}_ESFD2570_I17G_ESFD2570___${TYPEAOC_CT}_AE_RETRONP_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('INVO',  'I17G_ESFD2570___AA3','INVO')
			insert into BEST..TI17REQFNC values ('POCO',  'I17G_ESFD2570___AA3','POCO')
			insert into BEST..TI17REQFNC values ('POSO',  'I17G_ESFD2570___AA3','POSO')

	----------IDF_CT:   I17G_FUT_RNP_INI ------------------

		insert into BEST..TI17FNC values ('I17G_FUT_RNP_INI','Retro NP at Inception','ESFD2570',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17G_FUT_RNP_INI',  'EPO_FTECLEDR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_FUT_RNP_INI',  'EPO_FTECLEDRCO','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_FUT_RNP_INI',  'EPO_FTECLEDRSO','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_FUT_RNP_INI',  'EPO_DLSGTRSII_AE','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_FUT_RNP_INI',  'EPO_RETITDPRM_UPR_ACT','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_FUT_RNP_INI',  'EPO_DLDGTR_CUMULS_PREC','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_FUT_RNP_INI',  'EST_FDETTRS','${DFILP}/${ENV_PREFIX}_ESCJ0660_FDETTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_FUT_RNP_INI',  'EST_FTRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_FUT_RNP_INI',  'EPO_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_FUT_RNP_INI',  'EST_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_FUT_RNP_INI',  'EPO_FBOPRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_FUT_RNP_INI',  'EST_FBOPRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_FUT_RNP_INI',  'EST_FDETTRS_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FDETTRS_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_FUT_RNP_INI',  'EST_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_FUT_RNP_INI',  'EPO_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_FUT_RNP_INI',  'EST_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_FUT_RNP_INI',  'EPO_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_FUT_RNP_INI',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_FUT_RNP_INI',  'EPO_FPLACEMT22','${DFILP}/${ENV_PREFIX}_ESPD0060_FPLACEMT22_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_FUT_RNP_INI',  'EPO_IRDPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE_NP_I17G_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_FUT_RNP_INI',  'EPO_DLDGTRCO','${DFILP}/${ENV_PREFIX}_ESFD2570_I17G_FUT_RNP_INI_DLDGTRSIICO.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_FUT_RNP_INI',  'EPO_DLDGTRSO','${DFILP}/${ENV_PREFIX}_ESFD2570_I17G_FUT_RNP_INI_DLDGTRSIISO.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_FUT_RNP_INI',  'EPO_DLDGTR_E','${DFILP}/${ENV_PREFIX}_ESFD2570_I17G_FUT_RNP_INI_DLDGTRSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_FUT_RNP_INI',  'EST_RETITDPRM','${DFILP}/${ENV_PREFIX}_ESFD2570_I17G_FUT_RNP_INI_RETITDPRM_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_FUT_RNP_INI',  'EPO_DLDGTAR_E','${DFILP}/${ENV_PREFIX}_ESFD2570_I17G_FUT_RNP_INI_DLDGTARSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_FUT_RNP_INI',  'EPO_DLDGTRCO_E','${DFILP}/${ENV_PREFIX}_ESFD2570_I17G_FUT_RNP_INI_DLDGTRSIICO_E${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_FUT_RNP_INI',  'EPO_DLDGTRSO_E','${DFILP}/${ENV_PREFIX}_ESFD2570_I17G_FUT_RNP_INI_DLDGTRSIISO_E${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_FUT_RNP_INI',  'EPO_DLDGTARCO_E','${DFILP}/${ENV_PREFIX}_ESFD2570_I17G_FUT_RNP_INI_DLDGTARSIICO_E${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_FUT_RNP_INI',  'EPO_DLDGTARSO_E','${DFILP}/${ENV_PREFIX}_ESFD2570_I17G_FUT_RNP_INI_DLDGTARSIISO_E${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_FUT_RNP_INI',  'EST_RETUPR_ESTIME','${DFILP}/${ENV_PREFIX}_ESFD2570_I17G_FUT_RNP_INI_RETUPR_ESTIME_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_FUT_RNP_INI',  'EPO_DLSGTRSII_AE_RETRONP','${DFILP}/${ENV_PREFIX}_ESFD2570_I17G_FUT_RNP_INI_AE_RETRONP_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_FUT_RNP_INI',  'EPO_DLDGTR_TCODINI','${DFILP}/${ENV_PREFIX}_ESFD2570_I17G_FUT_RNP_INI_DLDGTR_TCODINI_SII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_FUT_RNP_INI',  'EPO_DLDGTAR_TCODINI','${DFILP}/${ENV_PREFIX}_ESFD2570_I17G_FUT_RNP_INI_DLDGTAR_TCODINI_SII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_FUT_RNP_INI',  'EPO_FUTURE_RETRO_EBS','${DFILP}/${ENV_PREFIX}_ESFD2570_I17G_FUT_RNP_INI_FUTURE_RETRO_EBS_INI${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17GQINV',  'I17G_FUT_RNP_INI','')
			insert into BEST..TI17REQFNC values ('I17GQPOS',  'I17G_FUT_RNP_INI','')
			insert into BEST..TI17REQFNC values ('I17GYINV',  'I17G_FUT_RNP_INI','')
			insert into BEST..TI17REQFNC values ('I17GYPOS',  'I17G_FUT_RNP_INI','')
			insert into BEST..TI17REQFNC values ('I17GMINV',  'I17G_FUT_RNP_INI','')

	----------IDF_CT:   I17L_FUT_RNP_INI ------------------

		insert into BEST..TI17FNC values ('I17L_FUT_RNP_INI','Retro NP at Inception','ESFD2570',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17L_FUT_RNP_INI',  'EPO_FTECLEDR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_FUT_RNP_INI',  'EPO_FTECLEDRCO','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_FUT_RNP_INI',  'EPO_FTECLEDRSO','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_FUT_RNP_INI',  'EPO_DLSGTRSII_AE','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_FUT_RNP_INI',  'EPO_RETITDPRM_UPR_ACT','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_FUT_RNP_INI',  'EPO_DLDGTR_CUMULS_PREC','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_FUT_RNP_INI',  'EST_FDETTRS','${DFILP}/${ENV_PREFIX}_ESCJ0660_FDETTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_FUT_RNP_INI',  'EST_FTRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_FUT_RNP_INI',  'EPO_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_FUT_RNP_INI',  'EST_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_FUT_RNP_INI',  'EPO_FBOPRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_FUT_RNP_INI',  'EST_FBOPRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_FUT_RNP_INI',  'EST_FDETTRS_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FDETTRS_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_FUT_RNP_INI',  'EST_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_FUT_RNP_INI',  'EPO_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_FUT_RNP_INI',  'EST_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_FUT_RNP_INI',  'EPO_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_FUT_RNP_INI',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_FUT_RNP_INI',  'EPO_FPLACEMT22','${DFILP}/${ENV_PREFIX}_ESPD0060_FPLACEMT22_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_FUT_RNP_INI',  'EPO_IRDPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE_NP_I17L_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_FUT_RNP_INI',  'EPO_DLDGTRCO','${DFILP}/${ENV_PREFIX}_ESFD2570_I17L_FUT_RNP_INI_DLDGTRSIICO.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_FUT_RNP_INI',  'EPO_DLDGTRSO','${DFILP}/${ENV_PREFIX}_ESFD2570_I17L_FUT_RNP_INI_DLDGTRSIISO.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_FUT_RNP_INI',  'EPO_DLDGTR_E','${DFILP}/${ENV_PREFIX}_ESFD2570_I17L_FUT_RNP_INI_DLDGTRSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_FUT_RNP_INI',  'EST_RETITDPRM','${DFILP}/${ENV_PREFIX}_ESFD2570_I17L_FUT_RNP_INI_RETITDPRM_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_FUT_RNP_INI',  'EPO_DLDGTAR_E','${DFILP}/${ENV_PREFIX}_ESFD2570_I17L_FUT_RNP_INI_DLDGTARSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_FUT_RNP_INI',  'EPO_DLDGTRCO_E','${DFILP}/${ENV_PREFIX}_ESFD2570_I17L_FUT_RNP_INI_DLDGTRSIICO_E${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_FUT_RNP_INI',  'EPO_DLDGTRSO_E','${DFILP}/${ENV_PREFIX}_ESFD2570_I17L_FUT_RNP_INI_DLDGTRSIISO_E${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_FUT_RNP_INI',  'EPO_DLDGTARCO_E','${DFILP}/${ENV_PREFIX}_ESFD2570_I17L_FUT_RNP_INI_DLDGTARSIICO_E${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_FUT_RNP_INI',  'EPO_DLDGTARSO_E','${DFILP}/${ENV_PREFIX}_ESFD2570_I17L_FUT_RNP_INI_DLDGTARSIISO_E${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_FUT_RNP_INI',  'EST_RETUPR_ESTIME','${DFILP}/${ENV_PREFIX}_ESFD2570_I17L_FUT_RNP_INI_RETUPR_ESTIME_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_FUT_RNP_INI',  'EPO_DLSGTRSII_AE_RETRONP','${DFILP}/${ENV_PREFIX}_ESFD2570_I17L_FUT_RNP_INI_AE_RETRONP_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_FUT_RNP_INI',  'EPO_DLDGTR_TCODINI','${DFILP}/${ENV_PREFIX}_ESFD2570_I17L_FUT_RNP_INI_DLDGTR_TCODINI_SII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_FUT_RNP_INI',  'EPO_DLDGTAR_TCODINI','${DFILP}/${ENV_PREFIX}_ESFD2570_I17L_FUT_RNP_INI_DLDGTAR_TCODINI_SII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_FUT_RNP_INI',  'EPO_FUTURE_RETRO_EBS','${DFILP}/${ENV_PREFIX}_ESFD2570_I17L_FUT_RNP_INI_FUTURE_RETRO_EBS_INI${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17LMINV',  'I17L_FUT_RNP_INI','')
			insert into BEST..TI17REQFNC values ('I17LQINV',  'I17L_FUT_RNP_INI','')
			insert into BEST..TI17REQFNC values ('I17LQPOS',  'I17L_FUT_RNP_INI','')
			insert into BEST..TI17REQFNC values ('I17LYINV',  'I17L_FUT_RNP_INI','')
			insert into BEST..TI17REQFNC values ('I17LYPOS',  'I17L_FUT_RNP_INI','')

	----------IDF_CT:   I17P_FUT_RNP_INI ------------------

		insert into BEST..TI17FNC values ('I17P_FUT_RNP_INI','Retro NP at Inception','ESFD2570',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17P_FUT_RNP_INI',  'EPO_FTECLEDR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_FUT_RNP_INI',  'EPO_FTECLEDRCO','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_FUT_RNP_INI',  'EPO_FTECLEDRSO','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_FUT_RNP_INI',  'EPO_DLSGTRSII_AE','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_FUT_RNP_INI',  'EPO_RETITDPRM_UPR_ACT','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_FUT_RNP_INI',  'EPO_DLDGTR_CUMULS_PREC','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_FUT_RNP_INI',  'EST_FDETTRS','${DFILP}/${ENV_PREFIX}_ESCJ0660_FDETTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_FUT_RNP_INI',  'EST_FTRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_FUT_RNP_INI',  'EPO_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_FUT_RNP_INI',  'EST_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_FUT_RNP_INI',  'EPO_FBOPRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_FUT_RNP_INI',  'EST_FBOPRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_FUT_RNP_INI',  'EST_FDETTRS_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FDETTRS_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_FUT_RNP_INI',  'EST_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_FUT_RNP_INI',  'EPO_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_FUT_RNP_INI',  'EST_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_FUT_RNP_INI',  'EPO_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_FUT_RNP_INI',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_FUT_RNP_INI',  'EPO_FPLACEMT22','${DFILP}/${ENV_PREFIX}_ESPD0060_FPLACEMT22_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_FUT_RNP_INI',  'EPO_IRDPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE_NP_I17P_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_FUT_RNP_INI',  'EPO_DLDGTRCO','${DFILP}/${ENV_PREFIX}_ESFD2570_I17P_FUT_RNP_INI_DLDGTRSIICO.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_FUT_RNP_INI',  'EPO_DLDGTRSO','${DFILP}/${ENV_PREFIX}_ESFD2570_I17P_FUT_RNP_INI_DLDGTRSIISO.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_FUT_RNP_INI',  'EPO_DLDGTR_E','${DFILP}/${ENV_PREFIX}_ESFD2570_I17P_FUT_RNP_INI_DLDGTRSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_FUT_RNP_INI',  'EST_RETITDPRM','${DFILP}/${ENV_PREFIX}_ESFD2570_I17P_FUT_RNP_INI_RETITDPRM_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_FUT_RNP_INI',  'EPO_DLDGTAR_E','${DFILP}/${ENV_PREFIX}_ESFD2570_I17P_FUT_RNP_INI_DLDGTARSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_FUT_RNP_INI',  'EPO_DLDGTRCO_E','${DFILP}/${ENV_PREFIX}_ESFD2570_I17P_FUT_RNP_INI_DLDGTRSIICO_E${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_FUT_RNP_INI',  'EPO_DLDGTRSO_E','${DFILP}/${ENV_PREFIX}_ESFD2570_I17P_FUT_RNP_INI_DLDGTRSIISO_E${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_FUT_RNP_INI',  'EPO_DLDGTARCO_E','${DFILP}/${ENV_PREFIX}_ESFD2570_I17P_FUT_RNP_INI_DLDGTARSIICO_E${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_FUT_RNP_INI',  'EPO_DLDGTARSO_E','${DFILP}/${ENV_PREFIX}_ESFD2570_I17P_FUT_RNP_INI_DLDGTARSIISO_E${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_FUT_RNP_INI',  'EST_RETUPR_ESTIME','${DFILP}/${ENV_PREFIX}_ESFD2570_I17P_FUT_RNP_INI_RETUPR_ESTIME_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_FUT_RNP_INI',  'EPO_DLSGTRSII_AE_RETRONP','${DFILP}/${ENV_PREFIX}_ESFD2570_I17P_FUT_RNP_INI_AE_RETRONP_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_FUT_RNP_INI',  'EPO_DLDGTR_TCODINI','${DFILP}/${ENV_PREFIX}_ESFD2570_I17P_FUT_RNP_INI_DLDGTR_TCODINI_SII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_FUT_RNP_INI',  'EPO_DLDGTAR_TCODINI','${DFILP}/${ENV_PREFIX}_ESFD2570_I17P_FUT_RNP_INI_DLDGTAR_TCODINI_SII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_FUT_RNP_INI',  'EPO_FUTURE_RETRO_EBS','${DFILP}/${ENV_PREFIX}_ESFD2570_I17P_FUT_RNP_INI_FUTURE_RETRO_EBS_INI${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17PMINV',  'I17P_FUT_RNP_INI','')
			insert into BEST..TI17REQFNC values ('I17PQINV',  'I17P_FUT_RNP_INI','')
			insert into BEST..TI17REQFNC values ('I17PQPOS',  'I17P_FUT_RNP_INI','')
			insert into BEST..TI17REQFNC values ('I17PYINV',  'I17P_FUT_RNP_INI','')
			insert into BEST..TI17REQFNC values ('I17PYPOS',  'I17P_FUT_RNP_INI','')

	----------IDF_CT:   I17S_ESFD2570___AA0 ------------------

		insert into BEST..TI17FNC values ('I17S_ESFD2570___AA0','Micro AOC FutureLR NP','ESFD2570',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA0',  'EPO_DLSGTRSII_AE','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA0',  'EST_FTRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA0',  'EPO_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA0',  'EPO_FBOPRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0060_FBOPRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA0',  'EPO_IRDPERICASE0','${DFILP}/${ENV_PREFIX}_ESID0060_IRDPERICASE0_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA0',  'EPO_FTECLEDRSO','${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA0',  'EPO_FPLACEMT22','${DFILP}/${ENV_PREFIX}_ESPD0060_FPLACEMT22_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA0',  'EPO_RETITDPRM_UPR_ACT','${DFILP}/${ENV_PREFIX}_ESPD0060_RETITDPRM_UPR_ACT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA0',  'EPO_DLDGTRCO','${DFILP}/${ENV_PREFIX}_ESFD2570_I17S_ESFD2570___AA0_DLDGTRSIICO.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA0',  'EPO_DLDGTRSO','${DFILP}/${ENV_PREFIX}_ESFD2570_I17S_ESFD2570___AA0_DLDGTRSII${TYPEINV}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA0',  'EPO_DLDGTR_E','${DFILP}/${ENV_PREFIX}_ESFD2570_I17S_ESFD2570___AA0_DLDGTRSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA0',  'EST_RETITDPRM','${DFILP}/${ENV_PREFIX}_ESFD2570_I17S_ESFD2570___AA0_RETITDPRM_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA0',  'EPO_DLDGTAR_E','${DFILP}/${ENV_PREFIX}_ESFD2570_I17S_ESFD2570___AA0_DLDGTARSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA0',  'EST_RETUPR_ESTIME','${DFILP}/${ENV_PREFIX}_ESFD2570_I17S_ESFD2570___AA0_RETUPR_ESTIME_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA0',  'EPO_FUTURE_RETRO_EBS','${DFILP}/${ENV_PREFIX}_ESFD2570_I17S_ESFD2570___AA0_FUTURE_RETRO_EBS${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA0',  'EPO_DLSGTRSII_AE_RETRONP','${DFILP}/${ENV_PREFIX}_ESFD2570_I17S_ESFD2570___${TYPEAOC_CT}_AE_RETRONP_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------


	----------IDF_CT:   I17S_ESFD2570___AA1 ------------------

		insert into BEST..TI17FNC values ('I17S_ESFD2570___AA1','Micro AOC FutureLR NP','ESFD2570',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA1',  'EPO_DLSGTRSII_AE','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA1',  'EST_FTRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA1',  'EPO_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA1',  'EPO_FBOPRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0060_FBOPRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA1',  'EPO_IRDPERICASE0','${DFILP}/${ENV_PREFIX}_ESID0060_IRDPERICASE0_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA1',  'EPO_FPLACEMT22','${DFILP}/${ENV_PREFIX}_ESPD0060_FPLACEMT22_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA1',  'EPO_FTECLEDRSO','${DFILP}/${ENV_PREFIX}_ES${PARM_FTECLED}D3800_FTECLEDR_I4I_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA1',  'EPO_RETITDPRM_UPR_ACT','${DFILP}/${ENV_PREFIX}_ESPD0060_RETITDPRM_UPR_ACT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA1',  'EPO_DLDGTRCO','${DFILP}/${ENV_PREFIX}_ESFD2570_I17S_ESFD2570___AA1_DLDGTRSIICO.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA1',  'EPO_DLDGTRSO','${DFILP}/${ENV_PREFIX}_ESFD2570_I17S_ESFD2570___AA1_DLDGTRSII${TYPEINV}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA1',  'EPO_DLDGTR_E','${DFILP}/${ENV_PREFIX}_ESFD2570_I17S_ESFD2570___AA1_DLDGTRSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA1',  'EST_RETITDPRM','${DFILP}/${ENV_PREFIX}_ESFD2570_I17S_ESFD2570___AA1_RETITDPRM_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA1',  'EPO_DLDGTAR_E','${DFILP}/${ENV_PREFIX}_ESFD2570_I17S_ESFD2570___AA1_DLDGTARSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA1',  'EST_RETUPR_ESTIME','${DFILP}/${ENV_PREFIX}_ESFD2570_I17S_ESFD2570___AA1_RETUPR_ESTIME_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA1',  'EPO_FUTURE_RETRO_EBS','${DFILP}/${ENV_PREFIX}_ESFD2570_I17S_ESFD2570___AA1_FUTURE_RETRO_EBS${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA1',  'EPO_DLSGTRSII_AE_RETRONP','${DFILP}/${ENV_PREFIX}_ESFD2570_I17S_ESFD2570___${TYPEAOC_CT}_AE_RETRONP_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------


	----------IDF_CT:   I17S_ESFD2570___AA2 ------------------

		insert into BEST..TI17FNC values ('I17S_ESFD2570___AA2','Micro AOC FutureLR NP','ESFD2570',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA2',  'EPO_DLSGTRSII_AE','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA2',  'EST_FTRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA2',  'EPO_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA2',  'EPO_FBOPRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0060_FBOPRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA2',  'EPO_IRDPERICASE0','${DFILP}/${ENV_PREFIX}_ESID0060_IRDPERICASE0_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA2',  'EPO_FTECLEDRSO','${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA2',  'EPO_FPLACEMT22','${DFILP}/${ENV_PREFIX}_ESPD0060_FPLACEMT22_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA2',  'EPO_RETITDPRM_UPR_ACT','${DFILP}/${ENV_PREFIX}_ESPD0060_RETITDPRM_UPR_ACT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA2',  'EPO_DLDGTRCO','${DFILP}/${ENV_PREFIX}_ESFD2570_I17S_ESFD2570___AA2_DLDGTRSIICO.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA2',  'EPO_DLDGTRSO','${DFILP}/${ENV_PREFIX}_ESFD2570_I17S_ESFD2570___AA2_DLDGTRSII${TYPEINV}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA2',  'EPO_DLDGTR_E','${DFILP}/${ENV_PREFIX}_ESFD2570_I17S_ESFD2570___AA2_DLDGTRSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA2',  'EST_RETITDPRM','${DFILP}/${ENV_PREFIX}_ESFD2570_I17S_ESFD2570___AA2_RETITDPRM_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA2',  'EPO_DLDGTAR_E','${DFILP}/${ENV_PREFIX}_ESFD2570_I17S_ESFD2570___AA2_DLDGTARSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA2',  'EST_RETUPR_ESTIME','${DFILP}/${ENV_PREFIX}_ESFD2570_I17S_ESFD2570___AA2_RETUPR_ESTIME_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA2',  'EPO_FUTURE_RETRO_EBS','${DFILP}/${ENV_PREFIX}_ESFD2570_I17S_ESFD2570___AA2_FUTURE_RETRO_EBS${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA2',  'EPO_DLSGTRSII_AE_RETRONP','${DFILP}/${ENV_PREFIX}_ESFD2570_I17S_ESFD2570___${TYPEAOC_CT}_AE_RETRONP_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------


	----------IDF_CT:   I17S_ESFD2570___AA3 ------------------

		insert into BEST..TI17FNC values ('I17S_ESFD2570___AA3','Micro AOC FutureLR NP','ESFD2570',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA3',  'EPO_DLSGTRSII_AE','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA3',  'EST_FTRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA3',  'EPO_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA3',  'EPO_FBOPRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0060_FBOPRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA3',  'EPO_IRDPERICASE0','${DFILP}/${ENV_PREFIX}_ESID0060_IRDPERICASE0_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA3',  'EPO_FTECLEDRSO','${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA3',  'EPO_FPLACEMT22','${DFILP}/${ENV_PREFIX}_ESPD0060_FPLACEMT22_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA3',  'EPO_RETITDPRM_UPR_ACT','${DFILP}/${ENV_PREFIX}_ESPD0060_RETITDPRM_UPR_ACT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA3',  'EPO_DLDGTRCO','${DFILP}/${ENV_PREFIX}_ESFD2570_I17S_ESFD2570___AA3_DLDGTRSIICO.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA3',  'EPO_DLDGTRSO','${DFILP}/${ENV_PREFIX}_ESFD2570_I17S_ESFD2570___AA3_DLDGTRSII${TYPEINV}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA3',  'EPO_DLDGTR_E','${DFILP}/${ENV_PREFIX}_ESFD2570_I17S_ESFD2570___AA3_DLDGTRSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA3',  'EST_RETITDPRM','${DFILP}/${ENV_PREFIX}_ESFD2570_I17S_ESFD2570___AA3_RETITDPRM_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA3',  'EPO_DLDGTAR_E','${DFILP}/${ENV_PREFIX}_ESFD2570_I17S_ESFD2570___AA3_DLDGTARSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA3',  'EST_RETUPR_ESTIME','${DFILP}/${ENV_PREFIX}_ESFD2570_I17S_ESFD2570___AA3_RETUPR_ESTIME_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA3',  'EPO_FUTURE_RETRO_EBS','${DFILP}/${ENV_PREFIX}_ESFD2570_I17S_ESFD2570___AA3_FUTURE_RETRO_EBS${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_ESFD2570___AA3',  'EPO_DLSGTRSII_AE_RETRONP','${DFILP}/${ENV_PREFIX}_ESFD2570_I17S_ESFD2570___${TYPEAOC_CT}_AE_RETRONP_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------


	----------IDF_CT:   I17S_FUT_RNP_INI ------------------

		insert into BEST..TI17FNC values ('I17S_FUT_RNP_INI','Retro NP at Inception','ESFD2570',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17S_FUT_RNP_INI',  'EPO_FTECLEDR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_FUT_RNP_INI',  'EPO_FTECLEDRCO','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_FUT_RNP_INI',  'EPO_FTECLEDRSO','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_FUT_RNP_INI',  'EPO_DLSGTRSII_AE','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_FUT_RNP_INI',  'EPO_RETITDPRM_UPR_ACT','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_FUT_RNP_INI',  'EPO_DLDGTR_CUMULS_PREC','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_FUT_RNP_INI',  'EST_FDETTRS','${DFILP}/${ENV_PREFIX}_ESCJ0660_FDETTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_FUT_RNP_INI',  'EST_FTRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_FUT_RNP_INI',  'EPO_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_FUT_RNP_INI',  'EST_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_FUT_RNP_INI',  'EPO_FBOPRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_FUT_RNP_INI',  'EST_FBOPRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_FUT_RNP_INI',  'EST_FDETTRS_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FDETTRS_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_FUT_RNP_INI',  'EST_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_FUT_RNP_INI',  'EPO_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_FUT_RNP_INI',  'EST_FCURQUOT_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_FUT_RNP_INI',  'EPO_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_FUT_RNP_INI',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_FUT_RNP_INI',  'EPO_FPLACEMT22','${DFILP}/${ENV_PREFIX}_ESPD0060_FPLACEMT22_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_FUT_RNP_INI',  'EPO_IRDPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE_NP_I17S_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_FUT_RNP_INI',  'EPO_DLDGTRCO','${DFILP}/${ENV_PREFIX}_ESFD2570_I17S_FUT_RNP_INI_DLDGTRSIICO.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_FUT_RNP_INI',  'EPO_DLDGTRSO','${DFILP}/${ENV_PREFIX}_ESFD2570_I17S_FUT_RNP_INI_DLDGTRSIISO.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_FUT_RNP_INI',  'EPO_DLDGTR_E','${DFILP}/${ENV_PREFIX}_ESFD2570_I17S_FUT_RNP_INI_DLDGTRSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_FUT_RNP_INI',  'EST_RETITDPRM','${DFILP}/${ENV_PREFIX}_ESFD2570_I17S_FUT_RNP_INI_RETITDPRM_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_FUT_RNP_INI',  'EPO_DLDGTAR_E','${DFILP}/${ENV_PREFIX}_ESFD2570_I17S_FUT_RNP_INI_DLDGTARSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_FUT_RNP_INI',  'EPO_DLDGTRCO_E','${DFILP}/${ENV_PREFIX}_ESFD2570_I17S_FUT_RNP_INI_DLDGTRSIICO_E${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_FUT_RNP_INI',  'EPO_DLDGTRSO_E','${DFILP}/${ENV_PREFIX}_ESFD2570_I17S_FUT_RNP_INI_DLDGTRSIISO_E${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_FUT_RNP_INI',  'EPO_DLDGTARCO_E','${DFILP}/${ENV_PREFIX}_ESFD2570_I17S_FUT_RNP_INI_DLDGTARSIICO_E${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_FUT_RNP_INI',  'EPO_DLDGTARSO_E','${DFILP}/${ENV_PREFIX}_ESFD2570_I17S_FUT_RNP_INI_DLDGTARSIISO_E${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_FUT_RNP_INI',  'EST_RETUPR_ESTIME','${DFILP}/${ENV_PREFIX}_ESFD2570_I17S_FUT_RNP_INI_RETUPR_ESTIME_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_FUT_RNP_INI',  'EPO_DLSGTRSII_AE_RETRONP','${DFILP}/${ENV_PREFIX}_ESFD2570_I17S_FUT_RNP_INI_AE_RETRONP_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_FUT_RNP_INI',  'EPO_DLDGTR_TCODINI','${DFILP}/${ENV_PREFIX}_ESFD2570_I17S_FUT_RNP_INI_DLDGTR_TCODINI_SII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_FUT_RNP_INI',  'EPO_DLDGTAR_TCODINI','${DFILP}/${ENV_PREFIX}_ESFD2570_I17S_FUT_RNP_INI_DLDGTAR_TCODINI_SII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_FUT_RNP_INI',  'EPO_FUTURE_RETRO_EBS','${DFILP}/${ENV_PREFIX}_ESFD2570_I17S_FUT_RNP_INI_FUTURE_RETRO_EBS_INI${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17SMINV',  'I17S_FUT_RNP_INI','')
			insert into BEST..TI17REQFNC values ('I17SQINV',  'I17S_FUT_RNP_INI','')
			insert into BEST..TI17REQFNC values ('I17SQPOS',  'I17S_FUT_RNP_INI','')
			insert into BEST..TI17REQFNC values ('I17SYINV',  'I17S_FUT_RNP_INI','')
			insert into BEST..TI17REQFNC values ('I17SYPOS',  'I17S_FUT_RNP_INI','')
go

