-------------------------------
--mapping of  ESFD4030

	----------   Clean tables   ---------------------

	delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD4030')
	delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD4030')
	delete BEST..TI17FNC where CHAIN_CT='ESFD4030'
	delete BEST..TI17CHN  where CHAIN_CT='ESFD4030'

	insert into BEST..TI17CHN values ('ESFD4030',  'GAAPCod BDA to GLT')

	----------IDF_CT:   EBS_GAP_MAP_STD ------------------

		insert into BEST..TI17FNC values ('EBS_GAP_MAP_STD','GAAPMAP BDA to GTL','ESFD4030',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('EBS_GAP_MAP_STD',  'ESF_FTECLEDA','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_GAP_MAP_STD',  'ESF_FTECLEDR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_GAP_MAP_STD',  'ESF_FCSM_ENDING_RNP','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_GAP_MAP_STD',  'ESF_FCSM_LC_ENDING_ASS','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_GAP_MAP_STD',  'ESF_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_GAP_MAP_STD',  'ESF_GAAPMAP','${DFILP}/${ENV_PREFIX}_ESPD0060_GAAPMAP_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_GAP_MAP_STD',  'ESF_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FBOPRSLNK_TXT_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_GAP_MAP_STD',  'EPO_FTECLEDA','${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_GAP_MAP_STD',  'EPO_FTECLEDR','${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_GAP_MAP_STD',  'EST_FTECLEDA','${DFILP}/${ENV_PREFIX}_ES${PARM_FTECLED}D8700_FTECLEDA_I4I_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_GAP_MAP_STD',  'ESF_CSM_PROF','${DFILP}/${ENV_PREFIX}_ESFD3750_I17G_CSM_ALL_STD_PROF_BY_CTR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_GAP_MAP_STD',  'ESF_FPLATXCUMALL0','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLATXCUMALL0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_GAP_MAP_STD',  'ESF_CSM_LC_AMORT_PATTERN','${DFILP}/${ENV_PREFIX}_ESFD3770_CSM_LC_AMORT_PATTERN_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_GAP_MAP_STD',  'ESF_CSM_LC_AMORT_PATTERN_PREV','${DFILP}/${ENV_PREFIX}_ESFD3770_CSM_LC_AMORT_PATTERN_EBS_POS_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_GAP_MAP_STD',  'ESF_FTECLEDA_70_EBS','${DFILI}/${ENV_PREFIX}_ESFD4030_EBS_GAP_MAP_STD_ESF_FTECLEDA_70_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_GAP_MAP_STD',  'ESF_FTECLEDA_40_IFRS4','${DFILI}/${ENV_PREFIX}_ESFD4030_EBS_GAP_MAP_STD_ESF_FTECLEDA_40_IFRS4_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_GAP_MAP_STD',  'ESF_FTECLEDA_100_IFRS17','${DFILI}/${ENV_PREFIX}_ESFD4030_EBS_GAP_MAP_STD_ESF_FTECLEDA_100_IFRS17_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_GAP_MAP_STD',  'EST_FTECLEDR','`if [ "${TYPEINV}" = "INV" ];then echo ${DFILP}/${ENV_PREFIX}_ESID8700_PC___FTECLEDR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat;else echo ${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_I4I_${PARM_ICLODAT_D}.dat;fi;`','I','')
			insert into BEST..TI17PERMFIL values ('EBS_GAP_MAP_STD',  'ESF_FTECLEDA_OUT','${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_GAP_MAP_STD',  'ESF_FTECLEDR_OUT','${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_GAP_MAP_STD',  'ESF_FTECLEDA_DELTA','${DFILP}/${ENV_PREFIX}_ESFD4030_EBS_GAP_MAP_STD_FTECLEDA_DELTA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_GAP_MAP_STD',  'ESF_FTECLEDR_DELTA','${DFILP}/${ENV_PREFIX}_ESFD4030_EBS_GAP_MAP_STD_FTECLEDR_DELTA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_GAP_MAP_STD',  'ESF_FGAAPMAP_RETRO','${DFILP}/${ENV_PREFIX}_ESFD4030_EBS_GAP_MAP_STD_FGAAPMAP_RETRO_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_GAP_MAP_STD',  'ESF_FGAAPMAP_ASSUMED','${DFILP}/${ENV_PREFIX}_ESFD4030_EBS_GAP_MAP_STD_FGAAPMAP_ASSUMED_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_GAP_MAP_STD',  'ESF_IADVPERICASE','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_GAP_MAP_STD',  'ESF_IRDVPERICASE','${DFILP}/empty.dat','I','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('EBSEQPOCB',  'EBS_GAP_MAP_STD','')
			insert into BEST..TI17REQFNC values ('EBSEQPOS',  'EBS_GAP_MAP_STD','')
			insert into BEST..TI17REQFNC values ('EBSEYINV',  'EBS_GAP_MAP_STD','')
			insert into BEST..TI17REQFNC values ('EBSEYPOC',  'EBS_GAP_MAP_STD','')
			insert into BEST..TI17REQFNC values ('EBSEYPOCB',  'EBS_GAP_MAP_STD','')
			insert into BEST..TI17REQFNC values ('EBSEYPOS',  'EBS_GAP_MAP_STD','')
			insert into BEST..TI17REQFNC values ('EBSEMINV',  'EBS_GAP_MAP_STD','')
			insert into BEST..TI17REQFNC values ('EBSEQINV',  'EBS_GAP_MAP_STD','')
			insert into BEST..TI17REQFNC values ('EBSEQPOC',  'EBS_GAP_MAP_STD','')

	----------IDF_CT:   I17G_GAP_MAP_LIF ------------------

		insert into BEST..TI17FNC values ('I17G_GAP_MAP_LIF','GAAPMAP BDA to GTL','ESFD4030',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_LIF',  'EPO_FTECLEDA','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_LIF',  'EPO_FTECLEDR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_LIF',  'ESF_CSM_PROF','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_LIF',  'ESF_FTECLEDA','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_LIF',  'ESF_FTECLEDR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_LIF',  'EST_FPLATXCUM','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_LIF',  'ESF_FCSM_ENDING_RNP','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_LIF',  'ESF_IADPERICASE_INI','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_LIF',  'ESF_FCSM_LC_ENDING_ASS','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_LIF',  'ESF_CSM_LC_AMORT_PATTERN','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_LIF',  'ESF_CSM_LC_AMORT_PATTERN_PREV','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_LIF',  'ESF_FCLIENT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCLIENT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_LIF',  'ESF_FCTRGRO0','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCTRGRO0.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_LIF',  'ESF_FSOBBLOB','${DFILP}/${ENV_PREFIX}_ESCJ0660_FSOBBLOB.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_LIF',  'ESF_FSSDACTR','${DFILP}/${ENV_PREFIX}_ESCJ0660_FSSDACTR.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_LIF',  'ESF_FPLACEMT2','${DFILP}/${ENV_PREFIX}_ESCJ0660_FPLACEMT2.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_LIF',  'ESF_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_LIF',  'ESF_FSSDACTR_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FSSDACTR_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_LIF',  'ESF_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FBOPRSLNK_TXT_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_LIF',  'ESF_FCPLACC','${DFILP}/${ENV_PREFIX}_ESFD0560_I17G_FCPLACC_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_LIF',  'EST_FTECLEDR','${DFILP}/${ENV_PREFIX}_ES${PARM_FTECLED}D3800_FTECLEDR_I4I_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_LIF',  'ESF_GAAPMAP','${DFILP}/${ENV_PREFIX}_ESFD0060_I17G____GAAPMAPLIF_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_LIF',  'ESF_IADVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD0560_I17G_IADVPERICASE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_LIF',  'ESF_IRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD0560_I17G_IRDVPERICASE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_LIF',  'EST_FTECLEDA','${DFILP}/${ENV_PREFIX}_ES${PARM_FTECLED}D3800_FTECLEDA_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_LIF',  'ESF_FTECLEDA_I17AELIFE','${DFILP}/${ENV_PREFIX}_ESFD1800_I17G_OMG_CES_LIF_TECLEDAI17AELIFE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_LIF',  'ESF_FTECLEDR_I17AELIFE','${DFILP}/${ENV_PREFIX}_ESFD1800_I17G_OMG_CES_LIF_TECLEDRI17AELIFE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_LIF',  'ESF_DLRGTAA','${DFILP}/${ENV_PREFIX}_ESFD2550_I17G_AEL_RPO_LIF_DLRGTAASII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')			
			--insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_LIF',  'ESF_DLRGTAA','${DFILP}/empty.dat','I','')

			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_LIF',  'ESF_FTECLEDA_OUT','${DFILP}/${ENV_PREFIX}_ESFD4030_I17G_GAP_MAP_LIF_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_LIF',  'ESF_FTECLEDR_OUT','${DFILP}/${ENV_PREFIX}_ESFD4030_I17G_GAP_MAP_LIF_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_LIF',  'ESF_FGAAPMAP_RETRO','${DFILP}/${ENV_PREFIX}_ESFD4030_I17G_GAP_MAP_LIF_FGAAPMAP_RETRO_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_LIF',  'ESF_FTECLEDA_DELTA','${DFILP}/${ENV_PREFIX}_ESFD4030_I17G_GAP_MAP_LIF_FTECLEDA_DELTA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_LIF',  'ESF_FTECLEDR_DELTA','${DFILP}/${ENV_PREFIX}_ESFD4030_I17G_GAP_MAP_LIF_FTECLEDR_DELTA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_LIF',  'ESF_FGAAPMAP_ASSUMED','${DFILP}/${ENV_PREFIX}_ESFD4030_I17G_GAP_MAP_LIF_FGAAPMAP_ASSUMED_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_LIF',  'ESF_FTECLEDA_I17AELIFE_OUT','${DFILP}/${ENV_PREFIX}_ESFD4030_I17G_OMG_CES_LIF_TECLEDAI17AELIFE_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_LIF',  'ESF_FTECLEDR_I17AELIFE_OUT','${DFILP}/${ENV_PREFIX}_ESFD4030_I17G_OMG_CES_LIF_TECLEDRI17AELIFE_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17GMINV',  'I17G_GAP_MAP_LIF','')
			insert into BEST..TI17REQFNC values ('I17GQINV',  'I17G_GAP_MAP_LIF','')
			insert into BEST..TI17REQFNC values ('I17GQINVB',  'I17G_GAP_MAP_LIF','')
			insert into BEST..TI17REQFNC values ('I17GQPOS',  'I17G_GAP_MAP_LIF','')
			insert into BEST..TI17REQFNC values ('I17GQPOSB',  'I17G_GAP_MAP_LIF','')
			insert into BEST..TI17REQFNC values ('I17GYINV',  'I17G_GAP_MAP_LIF','')
			insert into BEST..TI17REQFNC values ('I17GYINVB',  'I17G_GAP_MAP_LIF','')
			insert into BEST..TI17REQFNC values ('I17GYPOS',  'I17G_GAP_MAP_LIF','')
			insert into BEST..TI17REQFNC values ('I17GYPOSB',  'I17G_GAP_MAP_LIF','')
			insert into BEST..TI17REQFNC values ('I17GQPOSP',  'I17G_GAP_MAP_LIF','')
			insert into BEST..TI17REQFNC values ('I17GYPOSP',  'I17G_GAP_MAP_LIF','')

	----------IDF_CT:   I17G_GAP_MAP_STD ------------------

		insert into BEST..TI17FNC values ('I17G_GAP_MAP_STD','GAAPMAP BDA to GTL','ESFD4030',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD',  'ESF_FCLIENT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCLIENT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD',  'ESF_FCTRGRO0','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCTRGRO0.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD',  'ESF_FSOBBLOB','${DFILP}/${ENV_PREFIX}_ESCJ0660_FSOBBLOB.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD',  'ESF_FSSDACTR','${DFILP}/${ENV_PREFIX}_ESCJ0660_FSSDACTR.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD',  'ESF_FPLACEMT2','${DFILP}/${ENV_PREFIX}_ESCJ0660_FPLACEMT2.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD',  'ESF_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD',  'ESF_FSSDACTR_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FSSDACTR_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD',  'ESF_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FBOPRSLNK_TXT_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD',  'ESF_FCPLACC','${DFILP}/${ENV_PREFIX}_ESFD0560_I17G_FCPLACC_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD',  'ESF_GAAPMAP','${DFILP}/${ENV_PREFIX}_ESFD0060_I17G____GAAPMAP_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD',  'EST_FTECLEDA','${DFILP}/${ENV_PREFIX}_ES${PARM_FTECLED}D8700_FTECLEDA_I4I_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD',  'EST_FTECLEDR','${DFILP}/${ENV_PREFIX}_ES${PARM_FTECLED}D3800_FTECLEDR_I4I_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD',  'EST_FPLATXCUM','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLATXCUM_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD',  'ESF_IRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE0_I17G_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD',  'EPO_FTECLEDA','${DFILP}/${ENV_PREFIX}_ESPD3970_EBS_MVT_MRG_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD',  'EPO_FTECLEDR','${DFILP}/${ENV_PREFIX}_ESPD3970_EBS_MVT_MRG_STD_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD',  'ESF_FTECLEDA','${DFILP}/${ENV_PREFIX}_ESFD3870_I17G_GLT_ALL_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD',  'ESF_FTECLEDR','${DFILP}/${ENV_PREFIX}_ESFD3870_I17G_GLT_ALL_STD_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD',  'ESF_IADPERICASE_INI','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17G_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD',  'ESF_CSM_PROF','${DFILP}/${ENV_PREFIX}_ESFD3750_I17G_CSM_ALL_STD_PROF_BY_CTR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD',  'ESF_FPLATXCUMALL0','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLATXCUMALL0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD',  'ESF_CSM_LC_AMORT_PATTERN','${DFILP}/${ENV_PREFIX}_ESFD3770_CSM_LC_AMORT_PATTERN_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD',  'ESF_CSM_LC_AMORT_PATTERN_PREV','${DFILP}/${ENV_PREFIX}_ESFD3770_CSM_LC_AMORT_PATTERN_EBS_POS_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD',  'ESF_FCSM_ENDING_RNP','${DFILP}/${ENV_PREFIX}_ESFD3870_I17G_GLT_ALL_STD_FCSM_ENDING_RNP_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD',  'ESF_IADVPERICASE','${DFILP}/${ENV_PREFIX}_ESPD1800_I17G_AET_RPO_I17_IADPERICASE_I17_MERGE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD',  'ESF_FTECLEDA_70_EBS','${DFILI}/${ENV_PREFIX}_ESFD4030_I17G_GAP_MAP_STD_ESF_FTECLEDA_70_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD',  'ESF_FCSM_LC_ENDING_ASS','${DFILP}/${ENV_PREFIX}_ESFD3870_I17G_GLT_ALL_STD_FCSM_LC_ENDING_ASS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD',  'ESF_FTECLEDA_40_IFRS4','${DFILI}/${ENV_PREFIX}_ESFD4030_I17G_GAP_MAP_STD_ESF_FTECLEDA_40_IFRS4_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD',  'ESF_FTECLEDA_100_IFRS17','${DFILI}/${ENV_PREFIX}_ESFD4030_I17G_GAP_MAP_STD_ESF_FTECLEDA_100_IFRS17_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD',  'ESF_FTECLEDA_OUT','${DFILI}/${ENV_PREFIX}_ESFD4030_I17G_GAP_MAP_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD',  'ESF_FTECLEDR_OUT','${DFILI}/${ENV_PREFIX}_ESFD4030_I17G_GAP_MAP_STD_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD',  'ESF_FGAAPMAP_RETRO','${DFILP}/${ENV_PREFIX}_ESFD4030_I17G_GAP_MAP_STD_FGAAPMAP_RETRO_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD',  'ESF_FTECLEDA_DELTA','${DFILP}/${ENV_PREFIX}_ESFD4030_I17G_GAP_MAP_STD_FTECLEDA_DELTA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD',  'ESF_FTECLEDR_DELTA','${DFILP}/${ENV_PREFIX}_ESFD4030_I17G_GAP_MAP_STD_FTECLEDR_DELTA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_GAP_MAP_STD',  'ESF_FGAAPMAP_ASSUMED','${DFILP}/${ENV_PREFIX}_ESFD4030_I17G_GAP_MAP_STD_FGAAPMAP_ASSUMED_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17GMINV',  'I17G_GAP_MAP_STD','')
			insert into BEST..TI17REQFNC values ('I17GQINV',  'I17G_GAP_MAP_STD','')
			insert into BEST..TI17REQFNC values ('I17GQINVB',  'I17G_GAP_MAP_STD','')
			insert into BEST..TI17REQFNC values ('I17GQPOS',  'I17G_GAP_MAP_STD','')
			insert into BEST..TI17REQFNC values ('I17GQPOSB',  'I17G_GAP_MAP_STD','')
			insert into BEST..TI17REQFNC values ('I17GYINV',  'I17G_GAP_MAP_STD','')
			insert into BEST..TI17REQFNC values ('I17GYINVB',  'I17G_GAP_MAP_STD','')
			insert into BEST..TI17REQFNC values ('I17GYPOS',  'I17G_GAP_MAP_STD','')
			insert into BEST..TI17REQFNC values ('I17GYPOSB',  'I17G_GAP_MAP_STD','')
			insert into BEST..TI17REQFNC values ('I17GQPOSP',  'I17G_GAP_MAP_STD','')
			insert into BEST..TI17REQFNC values ('I17GYPOSP',  'I17G_GAP_MAP_STD','')

	----------IDF_CT:   I17L_GAP_MAP_LIF ------------------

		insert into BEST..TI17FNC values ('I17L_GAP_MAP_LIF','GAAPMAP BDA to GTL','ESFD4030',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_LIF',  'EPO_FTECLEDA','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_LIF',  'EPO_FTECLEDR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_LIF',  'ESF_CSM_PROF','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_LIF',  'ESF_FTECLEDA','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_LIF',  'ESF_FTECLEDR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_LIF',  'EST_FPLATXCUM','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_LIF',  'ESF_FCSM_ENDING_RNP','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_LIF',  'ESF_IADPERICASE_INI','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_LIF',  'ESF_FCSM_LC_ENDING_ASS','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_LIF',  'ESF_CSM_LC_AMORT_PATTERN','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_LIF',  'ESF_CSM_LC_AMORT_PATTERN_PREV','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_LIF',  'ESF_FCLIENT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCLIENT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_LIF',  'ESF_FCTRGRO0','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCTRGRO0.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_LIF',  'ESF_FSOBBLOB','${DFILP}/${ENV_PREFIX}_ESCJ0660_FSOBBLOB.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_LIF',  'ESF_FSSDACTR','${DFILP}/${ENV_PREFIX}_ESCJ0660_FSSDACTR.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_LIF',  'ESF_FPLACEMT2','${DFILP}/${ENV_PREFIX}_ESCJ0660_FPLACEMT2.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_LIF',  'ESF_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_LIF',  'ESF_FSSDACTR_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FSSDACTR_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_LIF',  'ESF_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FBOPRSLNK_TXT_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_LIF',  'ESF_FCPLACC','${DFILP}/${ENV_PREFIX}_ESFD0560_I17G_FCPLACC_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_LIF',  'EST_FTECLEDR','${DFILP}/${ENV_PREFIX}_ES${PARM_FTECLED}D3800_FTECLEDR_I4I_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_LIF',  'ESF_GAAPMAP','${DFILP}/${ENV_PREFIX}_ESFD0060_I17L____GAAPMAPLIF_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_LIF',  'ESF_IADVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD0560_I17L_IADVPERICASE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_LIF',  'ESF_IRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD0560_I17L_IRDVPERICASE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_LIF',  'EST_FTECLEDA','${DFILP}/${ENV_PREFIX}_ES${PARM_FTECLED}D3800_FTECLEDA_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_LIF',  'ESF_FTECLEDA_I17AELIFE','${DFILP}/${ENV_PREFIX}_ESFD1800_I17L_OMG_CES_LIF_TECLEDAI17AELIFE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_LIF',  'ESF_FTECLEDR_I17AELIFE','${DFILP}/${ENV_PREFIX}_ESFD1800_I17L_OMG_CES_LIF_TECLEDRI17AELIFE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			--insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_LIF',  'ESF_DLRGTAA','${DFILP}/${ENV_PREFIX}_ESFD2550_I17L_AEL_RPO_LIF_DLRGTAASII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')	
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_LIF',  'ESF_DLRGTAA','${DFILP}/empty.dat','I','')
			
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_LIF',  'ESF_FTECLEDA_OUT','${DFILP}/${ENV_PREFIX}_ESFD4030_I17L_GAP_MAP_LIF_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_LIF',  'ESF_FTECLEDR_OUT','${DFILP}/${ENV_PREFIX}_ESFD4030_I17L_GAP_MAP_LIF_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_LIF',  'ESF_FGAAPMAP_RETRO','${DFILP}/${ENV_PREFIX}_ESFD4030_I17L_GAP_MAP_LIF_FGAAPMAP_RETRO_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_LIF',  'ESF_FTECLEDA_DELTA','${DFILP}/${ENV_PREFIX}_ESFD4030_I17L_GAP_MAP_LIF_FTECLEDA_DELTA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_LIF',  'ESF_FTECLEDR_DELTA','${DFILP}/${ENV_PREFIX}_ESFD4030_I17L_GAP_MAP_LIF_FTECLEDR_DELTA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_LIF',  'ESF_FGAAPMAP_ASSUMED','${DFILP}/${ENV_PREFIX}_ESFD4030_I17L_GAP_MAP_LIF_FGAAPMAP_ASSUMED_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_LIF',  'ESF_FTECLEDA_I17AELIFE_OUT','${DFILP}/${ENV_PREFIX}_ESFD4030_I17L_OMG_CES_LIF_TECLEDAI17AELIFE_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_LIF',  'ESF_FTECLEDR_I17AELIFE_OUT','${DFILP}/${ENV_PREFIX}_ESFD4030_I17L_OMG_CES_LIF_TECLEDRI17AELIFE_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17LMINV',  'I17L_GAP_MAP_LIF','')
			insert into BEST..TI17REQFNC values ('I17LQINV',  'I17L_GAP_MAP_LIF','')
			insert into BEST..TI17REQFNC values ('I17LQINVB',  'I17L_GAP_MAP_LIF','')
			insert into BEST..TI17REQFNC values ('I17LQPOS',  'I17L_GAP_MAP_LIF','')
			--insert into BEST..TI17REQFNC values ('I17LQPOSB',  'I17L_GAP_MAP_LIF','')
			insert into BEST..TI17REQFNC values ('I17LYINV',  'I17L_GAP_MAP_LIF','')
			insert into BEST..TI17REQFNC values ('I17LYINVB',  'I17L_GAP_MAP_LIF','')
			insert into BEST..TI17REQFNC values ('I17LYPOS',  'I17L_GAP_MAP_LIF','')
			--insert into BEST..TI17REQFNC values ('I17LYPOSB',  'I17L_GAP_MAP_LIF','')
			insert into BEST..TI17REQFNC values ('I17LQPOSP',  'I17L_GAP_MAP_LIF','')
			insert into BEST..TI17REQFNC values ('I17LYPOSP',  'I17L_GAP_MAP_LIF','')
			insert into BEST..TI17REQFNC values ('I17LQPOSX',  'I17L_GAP_MAP_LIF','')
			insert into BEST..TI17REQFNC values ('I17LYPOSX',  'I17L_GAP_MAP_LIF','')

	----------IDF_CT:   I17L_GAP_MAP_STD ------------------

		insert into BEST..TI17FNC values ('I17L_GAP_MAP_STD','GAAPCod BDA to GTL','ESFD4030',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD',  'ESF_FCLIENT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCLIENT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD',  'ESF_FCTRGRO0','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCTRGRO0.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD',  'ESF_FSOBBLOB','${DFILP}/${ENV_PREFIX}_ESCJ0660_FSOBBLOB.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD',  'ESF_FSSDACTR','${DFILP}/${ENV_PREFIX}_ESCJ0660_FSSDACTR.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD',  'ESF_FPLACEMT2','${DFILP}/${ENV_PREFIX}_ESCJ0660_FPLACEMT2.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD',  'ESF_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD',  'ESF_FSSDACTR_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FSSDACTR_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD',  'ESF_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FBOPRSLNK_TXT_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD',  'ESF_FCPLACC','${DFILP}/${ENV_PREFIX}_ESFD0560_I17G_FCPLACC_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD',  'ESF_GAAPMAP','${DFILP}/${ENV_PREFIX}_ESFD0060_I17L____GAAPMAP_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD',  'EST_FTECLEDA','${DFILP}/${ENV_PREFIX}_ES${PARM_FTECLED}D8700_FTECLEDA_I4I_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD',  'EST_FTECLEDR','${DFILP}/${ENV_PREFIX}_ES${PARM_FTECLED}D3800_FTECLEDR_I4I_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD',  'EST_FPLATXCUM','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLATXCUM_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD',  'ESF_IRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE0_I17L_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD',  'EPO_FTECLEDA','${DFILP}/${ENV_PREFIX}_ESPD3970_EBS_MVT_MRG_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD',  'EPO_FTECLEDR','${DFILP}/${ENV_PREFIX}_ESPD3970_EBS_MVT_MRG_STD_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD',  'ESF_IADPERICASE_INI','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17L_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD',  'ESF_CSM_PROF','${DFILP}/${ENV_PREFIX}_ESFD3750_I17L_CSM_ALL_STD_PROF_BY_CTR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD',  'ESF_FPLATXCUMALL0','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLATXCUMALL0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD',  'ESF_CSM_LC_AMORT_PATTERN','${DFILP}/${ENV_PREFIX}_ESFD3770_CSM_LC_AMORT_PATTERN_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD',  'ESF_FTECLEDA','${DFILP}/${ENV_PREFIX}_ESFD4010_I17L_PAA_ALL_STD_PAA_ASSUM_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD',  'ESF_FTECLEDR','${DFILP}/${ENV_PREFIX}_ESFD4010_I17L_PAA_ALL_STD_PAA_RETRO_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD',  'ESF_CSM_LC_AMORT_PATTERN_PREV','${DFILP}/${ENV_PREFIX}_ESFD3770_CSM_LC_AMORT_PATTERN_EBS_POS_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD',  'ESF_IADVPERICASE','${DFILP}/${ENV_PREFIX}_ESPD1800_I17L_AET_RPO_I17_IADPERICASE_I17_MERGE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD',  'ESF_FTECLEDA_70_EBS','${DFILI}/${ENV_PREFIX}_ESFD4030_I17L_GAP_MAP_STD_ESF_FTECLEDA_70_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD',  'ESF_FTECLEDA_40_IFRS4','${DFILI}/${ENV_PREFIX}_ESFD4030_I17L_GAP_MAP_STD_ESF_FTECLEDA_40_IFRS4_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD',  'ESF_FCSM_ENDING_RNP','${DFILP}/${ENV_PREFIX}_ESFD3870_I17L_GLT_ALL_STD_FCSM_ENDING_RNP_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD',  'ESF_FTECLEDA_100_IFRS17','${DFILI}/${ENV_PREFIX}_ESFD4030_I17L_GAP_MAP_STD_ESF_FTECLEDA_100_IFRS17_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD',  'ESF_FCSM_LC_ENDING_ASS','${DFILP}/${ENV_PREFIX}_ESFD3870_I17L_GLT_ALL_STD_FCSM_LC_ENDING_ASS_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD',  'ESF_FTECLEDA_OUT','${DFILI}/${ENV_PREFIX}_ESFD4030_I17L_GAP_MAP_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD',  'ESF_FTECLEDR_OUT','${DFILI}/${ENV_PREFIX}_ESFD4030_I17L_GAP_MAP_STD_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD',  'ESF_FGAAPMAP_RETRO','${DFILP}/${ENV_PREFIX}_ESFD4030_I17L_GAP_MAP_STD_FGAAPMAP_RETRO_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD',  'ESF_FTECLEDA_DELTA','${DFILP}/${ENV_PREFIX}_ESFD4030_I17L_GAP_MAP_STD_FTECLEDA_DELTA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD',  'ESF_FTECLEDR_DELTA','${DFILP}/${ENV_PREFIX}_ESFD4030_I17L_GAP_MAP_STD_FTECLEDR_DELTA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_GAP_MAP_STD',  'ESF_FGAAPMAP_ASSUMED','${DFILP}/${ENV_PREFIX}_ESFD4030_I17L_GAP_MAP_STD_FGAAPMAP_ASSUMED_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17LMINV',  'I17L_GAP_MAP_STD','')
			insert into BEST..TI17REQFNC values ('I17LQINV',  'I17L_GAP_MAP_STD','')
			insert into BEST..TI17REQFNC values ('I17LQINVB',  'I17L_GAP_MAP_STD','')
			insert into BEST..TI17REQFNC values ('I17LQPOS',  'I17L_GAP_MAP_STD','')
			--insert into BEST..TI17REQFNC values ('I17LQPOSB',  'I17L_GAP_MAP_STD','')
			insert into BEST..TI17REQFNC values ('I17LYINV',  'I17L_GAP_MAP_STD','')
			insert into BEST..TI17REQFNC values ('I17LYINVB',  'I17L_GAP_MAP_STD','')
			insert into BEST..TI17REQFNC values ('I17LYPOS',  'I17L_GAP_MAP_STD','')
			--insert into BEST..TI17REQFNC values ('I17LYPOSB',  'I17L_GAP_MAP_STD','')
			insert into BEST..TI17REQFNC values ('I17LQPOSP',  'I17L_GAP_MAP_STD','')
			insert into BEST..TI17REQFNC values ('I17LYPOSP',  'I17L_GAP_MAP_STD','')
			insert into BEST..TI17REQFNC values ('I17LQPOSX',  'I17L_GAP_MAP_STD','')
			insert into BEST..TI17REQFNC values ('I17LYPOSX',  'I17L_GAP_MAP_STD','')

	----------IDF_CT:   I17P_GAP_MAP_LIF ------------------

		insert into BEST..TI17FNC values ('I17P_GAP_MAP_LIF','GAAPMAP BDA to GTL','ESFD4030',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_LIF',  'EPO_FTECLEDA','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_LIF',  'EPO_FTECLEDR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_LIF',  'ESF_CSM_PROF','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_LIF',  'ESF_FTECLEDA','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_LIF',  'ESF_FTECLEDR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_LIF',  'EST_FPLATXCUM','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_LIF',  'ESF_FCSM_ENDING_RNP','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_LIF',  'ESF_IADPERICASE_INI','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_LIF',  'ESF_FCSM_LC_ENDING_ASS','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_LIF',  'ESF_CSM_LC_AMORT_PATTERN','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_LIF',  'ESF_CSM_LC_AMORT_PATTERN_PREV','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_LIF',  'ESF_FCLIENT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCLIENT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_LIF',  'ESF_FCTRGRO0','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCTRGRO0.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_LIF',  'ESF_FSOBBLOB','${DFILP}/${ENV_PREFIX}_ESCJ0660_FSOBBLOB.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_LIF',  'ESF_FSSDACTR','${DFILP}/${ENV_PREFIX}_ESCJ0660_FSSDACTR.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_LIF',  'ESF_FPLACEMT2','${DFILP}/${ENV_PREFIX}_ESCJ0660_FPLACEMT2.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_LIF',  'ESF_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_LIF',  'ESF_FSSDACTR_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FSSDACTR_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_LIF',  'ESF_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FBOPRSLNK_TXT_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_LIF',  'ESF_FCPLACC','${DFILP}/${ENV_PREFIX}_ESFD0560_I17G_FCPLACC_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_LIF',  'EST_FTECLEDR','${DFILP}/${ENV_PREFIX}_ES${PARM_FTECLED}D3800_FTECLEDR_I4I_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_LIF',  'ESF_GAAPMAP','${DFILP}/${ENV_PREFIX}_ESFD0060_I17P____GAAPMAPLIF_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_LIF',  'ESF_IADVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD0560_I17P_IADVPERICASE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_LIF',  'ESF_IRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD0560_I17P_IRDVPERICASE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_LIF',  'EST_FTECLEDA','${DFILP}/${ENV_PREFIX}_ES${PARM_FTECLED}D3800_FTECLEDA_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_LIF',  'ESF_FTECLEDA_I17AELIFE','${DFILP}/${ENV_PREFIX}_ESFD1800_I17P_OMG_CES_LIF_TECLEDAI17AELIFE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_LIF',  'ESF_FTECLEDR_I17AELIFE','${DFILP}/${ENV_PREFIX}_ESFD1800_I17P_OMG_CES_LIF_TECLEDRI17AELIFE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			--insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_LIF',  'ESF_DLRGTAA','${DFILP}/${ENV_PREFIX}_ESFD2550_I17P_AEL_RPO_LIF_DLRGTAASII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')			
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_LIF',  'ESF_DLRGTAA','${DFILP}/empty.dat','I','') 

			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_LIF',  'ESF_FTECLEDA_OUT','${DFILP}/${ENV_PREFIX}_ESFD4030_I17P_GAP_MAP_LIF_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_LIF',  'ESF_FTECLEDR_OUT','${DFILP}/${ENV_PREFIX}_ESFD4030_I17P_GAP_MAP_LIF_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_LIF',  'ESF_FGAAPMAP_RETRO','${DFILP}/${ENV_PREFIX}_ESFD4030_I17P_GAP_MAP_LIF_FGAAPMAP_RETRO_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_LIF',  'ESF_FTECLEDA_DELTA','${DFILP}/${ENV_PREFIX}_ESFD4030_I17P_GAP_MAP_LIF_FTECLEDA_DELTA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_LIF',  'ESF_FTECLEDR_DELTA','${DFILP}/${ENV_PREFIX}_ESFD4030_I17P_GAP_MAP_LIF_FTECLEDR_DELTA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_LIF',  'ESF_FGAAPMAP_ASSUMED','${DFILP}/${ENV_PREFIX}_ESFD4030_I17P_GAP_MAP_LIF_FGAAPMAP_ASSUMED_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_LIF',  'ESF_FTECLEDA_I17AELIFE_OUT','${DFILP}/${ENV_PREFIX}_ESFD4030_I17P_OMG_CES_LIF_TECLEDAI17AELIFE_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_LIF',  'ESF_FTECLEDR_I17AELIFE_OUT','${DFILP}/${ENV_PREFIX}_ESFD4030_I17P_OMG_CES_LIF_TECLEDRI17AELIFE_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17PMINV',  'I17P_GAP_MAP_LIF','')
			insert into BEST..TI17REQFNC values ('I17PQINV',  'I17P_GAP_MAP_LIF','')
			insert into BEST..TI17REQFNC values ('I17PQINVB',  'I17P_GAP_MAP_LIF','')
			insert into BEST..TI17REQFNC values ('I17PQPOS',  'I17P_GAP_MAP_LIF','')
			--insert into BEST..TI17REQFNC values ('I17PQPOSB',  'I17P_GAP_MAP_LIF','')
			insert into BEST..TI17REQFNC values ('I17PYINV',  'I17P_GAP_MAP_LIF','')
			insert into BEST..TI17REQFNC values ('I17PYINVB',  'I17P_GAP_MAP_LIF','')
			insert into BEST..TI17REQFNC values ('I17PYPOS',  'I17P_GAP_MAP_LIF','')
			--insert into BEST..TI17REQFNC values ('I17PYPOSB',  'I17P_GAP_MAP_LIF','')
			insert into BEST..TI17REQFNC values ('I17PQPOSP',  'I17P_GAP_MAP_LIF','')
			insert into BEST..TI17REQFNC values ('I17PYPOSP',  'I17P_GAP_MAP_LIF','')
			insert into BEST..TI17REQFNC values ('I17PQPOSX',  'I17P_GAP_MAP_LIF','')
			insert into BEST..TI17REQFNC values ('I17PYPOSX',  'I17P_GAP_MAP_LIF','')

	----------IDF_CT:   I17P_GAP_MAP_STD ------------------

		insert into BEST..TI17FNC values ('I17P_GAP_MAP_STD','GAAPCod BDA to GTL','ESFD4030',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD',  'ESF_FCLIENT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCLIENT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD',  'ESF_FCTRGRO0','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCTRGRO0.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD',  'ESF_FSOBBLOB','${DFILP}/${ENV_PREFIX}_ESCJ0660_FSOBBLOB.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD',  'ESF_FSSDACTR','${DFILP}/${ENV_PREFIX}_ESCJ0660_FSSDACTR.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD',  'ESF_FPLACEMT2','${DFILP}/${ENV_PREFIX}_ESCJ0660_FPLACEMT2.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD',  'ESF_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD',  'ESF_FSSDACTR_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FSSDACTR_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD',  'ESF_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FBOPRSLNK_TXT_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD',  'ESF_FCPLACC','${DFILP}/${ENV_PREFIX}_ESFD0560_I17G_FCPLACC_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD',  'ESF_GAAPMAP','${DFILP}/${ENV_PREFIX}_ESFD0060_I17P____GAAPMAP_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD',  'EST_FTECLEDA','${DFILP}/${ENV_PREFIX}_ES${PARM_FTECLED}D8700_FTECLEDA_I4I_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD',  'EST_FTECLEDR','${DFILP}/${ENV_PREFIX}_ES${PARM_FTECLED}D3800_FTECLEDR_I4I_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD',  'EST_FPLATXCUM','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLATXCUM_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD',  'ESF_IRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE0_I17P_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD',  'EPO_FTECLEDA','${DFILP}/${ENV_PREFIX}_ESPD3970_EBS_MVT_MRG_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD',  'EPO_FTECLEDR','${DFILP}/${ENV_PREFIX}_ESPD3970_EBS_MVT_MRG_STD_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD',  'ESF_IADPERICASE_INI','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17P_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD',  'ESF_CSM_PROF','${DFILP}/${ENV_PREFIX}_ESFD3750_I17P_CSM_ALL_STD_PROF_BY_CTR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD',  'ESF_FPLATXCUMALL0','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLATXCUMALL0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD',  'ESF_CSM_LC_AMORT_PATTERN','${DFILP}/${ENV_PREFIX}_ESFD3770_CSM_LC_AMORT_PATTERN_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD',  'ESF_FTECLEDA','${DFILP}/${ENV_PREFIX}_ESFD3870_I17P_GLT_ALL_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD',  'ESF_FTECLEDR','${DFILP}/${ENV_PREFIX}_ESFD3870_I17P_GLT_ALL_STD_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD',  'ESF_CSM_LC_AMORT_PATTERN_PREV','${DFILP}/${ENV_PREFIX}_ESFD3770_CSM_LC_AMORT_PATTERN_EBS_POS_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD',  'ESF_IADVPERICASE','${DFILP}/${ENV_PREFIX}_ESPD1800_I17P_AET_RPO_I17_IADPERICASE_I17_MERGE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD',  'ESF_FTECLEDA_70_EBS','${DFILI}/${ENV_PREFIX}_ESFD4030_I17P_GAP_MAP_STD_ESF_FTECLEDA_70_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD',  'ESF_FTECLEDA_40_IFRS4','${DFILI}/${ENV_PREFIX}_ESFD4030_I17P_GAP_MAP_STD_ESF_FTECLEDA_40_IFRS4_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD',  'ESF_FCSM_ENDING_RNP','${DFILP}/${ENV_PREFIX}_ESFD3870_I17P_GLT_ALL_STD_FCSM_ENDING_RNP_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD',  'ESF_FTECLEDA_100_IFRS17','${DFILI}/${ENV_PREFIX}_ESFD4030_I17P_GAP_MAP_STD_ESF_FTECLEDA_100_IFRS17_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD',  'ESF_FCSM_LC_ENDING_ASS','${DFILP}/${ENV_PREFIX}_ESFD3870_I17P_GLT_ALL_STD_FCSM_LC_ENDING_ASS_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD',  'ESF_FTECLEDA_OUT','${DFILI}/${ENV_PREFIX}_ESFD4030_I17P_GAP_MAP_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD',  'ESF_FTECLEDR_OUT','${DFILI}/${ENV_PREFIX}_ESFD4030_I17P_GAP_MAP_STD_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD',  'ESF_FGAAPMAP_RETRO','${DFILP}/${ENV_PREFIX}_ESFD4030_I17P_GAP_MAP_STD_FGAAPMAP_RETRO_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD',  'ESF_FTECLEDA_DELTA','${DFILP}/${ENV_PREFIX}_ESFD4030_I17P_GAP_MAP_STD_FTECLEDA_DELTA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD',  'ESF_FTECLEDR_DELTA','${DFILP}/${ENV_PREFIX}_ESFD4030_I17P_GAP_MAP_STD_FTECLEDR_DELTA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_GAP_MAP_STD',  'ESF_FGAAPMAP_ASSUMED','${DFILP}/${ENV_PREFIX}_ESFD4030_I17P_GAP_MAP_STD_FGAAPMAP_ASSUMED_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17PMINV',  'I17P_GAP_MAP_STD','')
			insert into BEST..TI17REQFNC values ('I17PQINV',  'I17P_GAP_MAP_STD','')
			insert into BEST..TI17REQFNC values ('I17PQINVB',  'I17P_GAP_MAP_STD','')
			insert into BEST..TI17REQFNC values ('I17PQPOS',  'I17P_GAP_MAP_STD','')
			--insert into BEST..TI17REQFNC values ('I17PQPOSB',  'I17P_GAP_MAP_STD','')
			insert into BEST..TI17REQFNC values ('I17PYINV',  'I17P_GAP_MAP_STD','')
			insert into BEST..TI17REQFNC values ('I17PYINVB',  'I17P_GAP_MAP_STD','')
			insert into BEST..TI17REQFNC values ('I17PYPOS',  'I17P_GAP_MAP_STD','')
			--insert into BEST..TI17REQFNC values ('I17PYPOSB',  'I17P_GAP_MAP_STD','')
			insert into BEST..TI17REQFNC values ('I17PQPOSP',  'I17P_GAP_MAP_STD','')
			insert into BEST..TI17REQFNC values ('I17PYPOSP',  'I17P_GAP_MAP_STD','')
			insert into BEST..TI17REQFNC values ('I17PQPOSX',  'I17P_GAP_MAP_STD','')
			insert into BEST..TI17REQFNC values ('I17PYPOSX',  'I17P_GAP_MAP_STD','')

	----------IDF_CT:   I17S_GAP_MAP_LIF ------------------

		insert into BEST..TI17FNC values ('I17S_GAP_MAP_LIF','GAAPMAP BDA to GTL','ESFD4030',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_LIF',  'EPO_FTECLEDA','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_LIF',  'EPO_FTECLEDR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_LIF',  'ESF_CSM_PROF','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_LIF',  'ESF_FTECLEDA','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_LIF',  'ESF_FTECLEDR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_LIF',  'EST_FPLATXCUM','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_LIF',  'ESF_FCSM_ENDING_RNP','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_LIF',  'ESF_IADPERICASE_INI','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_LIF',  'ESF_FCSM_LC_ENDING_ASS','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_LIF',  'ESF_CSM_LC_AMORT_PATTERN','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_LIF',  'ESF_CSM_LC_AMORT_PATTERN_PREV','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_LIF',  'ESF_FCLIENT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCLIENT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_LIF',  'ESF_FCTRGRO0','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCTRGRO0.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_LIF',  'ESF_FSOBBLOB','${DFILP}/${ENV_PREFIX}_ESCJ0660_FSOBBLOB.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_LIF',  'ESF_FSSDACTR','${DFILP}/${ENV_PREFIX}_ESCJ0660_FSSDACTR.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_LIF',  'ESF_FPLACEMT2','${DFILP}/${ENV_PREFIX}_ESCJ0660_FPLACEMT2.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_LIF',  'ESF_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_LIF',  'ESF_FSSDACTR_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FSSDACTR_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_LIF',  'ESF_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FBOPRSLNK_TXT_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_LIF',  'ESF_FCPLACC','${DFILP}/${ENV_PREFIX}_ESFD0560_I17G_FCPLACC_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_LIF',  'EST_FTECLEDA','${DFILP}/${ENV_PREFIX}_ES${PARM_FTECLED}D8700_FTECLEDA_I4I_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_LIF',  'EST_FTECLEDR','${DFILP}/${ENV_PREFIX}_ES${PARM_FTECLED}D3800_FTECLEDR_I4I_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_LIF',  'ESF_GAAPMAP','${DFILP}/${ENV_PREFIX}_ESFD0060_I17S____GAAPMAPLIF_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_LIF',  'ESF_IADVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD0560_I17S_IADVPERICASE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_LIF',  'ESF_IRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD0560_I17S_IRDVPERICASE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_LIF',  'ESF_FTECLEDA_I17AELIFE','${DFILP}/${ENV_PREFIX}_ESFD1800_I17S_OMG_CES_LIF_TECLEDAI17AELIFE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_LIF',  'ESF_FTECLEDR_I17AELIFE','${DFILP}/${ENV_PREFIX}_ESFD1800_I17S_OMG_CES_LIF_TECLEDRI17AELIFE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			--insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_LIF',  'ESF_DLRGTAA','${DFILP}/${ENV_PREFIX}_ESFD2550_I17S_AEL_RPO_LIF_DLRGTAASII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')			
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_LIF',  'ESF_DLRGTAA','${DFILP}/empty.dat','I','')

			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_LIF',  'ESF_FTECLEDA_OUT','${DFILP}/${ENV_PREFIX}_ESFD4030_I17S_GAP_MAP_LIF_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_LIF',  'ESF_FTECLEDR_OUT','${DFILP}/${ENV_PREFIX}_ESFD4030_I17S_GAP_MAP_LIF_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_LIF',  'ESF_FGAAPMAP_RETRO','${DFILP}/${ENV_PREFIX}_ESFD4030_I17S_GAP_MAP_LIF_FGAAPMAP_RETRO_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_LIF',  'ESF_FTECLEDA_DELTA','${DFILP}/${ENV_PREFIX}_ESFD4030_I17S_GAP_MAP_LIF_FTECLEDA_DELTA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_LIF',  'ESF_FTECLEDR_DELTA','${DFILP}/${ENV_PREFIX}_ESFD4030_I17S_GAP_MAP_LIF_FTECLEDR_DELTA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_LIF',  'ESF_FGAAPMAP_ASSUMED','${DFILP}/${ENV_PREFIX}_ESFD4030_I17S_GAP_MAP_LIF_FGAAPMAP_ASSUMED_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_LIF',  'ESF_FTECLEDA_I17AELIFE_OUT','${DFILP}/${ENV_PREFIX}_ESFD4030_I17S_OMG_CES_LIF_TECLEDAI17AELIFE_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_GAP_MAP_LIF',  'ESF_FTECLEDR_I17AELIFE_OUT','${DFILP}/${ENV_PREFIX}_ESFD4030_I17S_OMG_CES_LIF_TECLEDRI17AELIFE_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17SMINV',  'I17S_GAP_MAP_LIF','')
			insert into BEST..TI17REQFNC values ('I17SQINV',  'I17S_GAP_MAP_LIF','')
			insert into BEST..TI17REQFNC values ('I17SQINVB',  'I17S_GAP_MAP_LIF','')
			insert into BEST..TI17REQFNC values ('I17SQPOS',  'I17S_GAP_MAP_LIF','')
			--insert into BEST..TI17REQFNC values ('I17SQPOSB',  'I17S_GAP_MAP_LIF','')
			insert into BEST..TI17REQFNC values ('I17SYINV',  'I17S_GAP_MAP_LIF','')
			insert into BEST..TI17REQFNC values ('I17SYINVB',  'I17S_GAP_MAP_LIF','')
			insert into BEST..TI17REQFNC values ('I17SYPOS',  'I17S_GAP_MAP_LIF','')
			--insert into BEST..TI17REQFNC values ('I17SYPOSB',  'I17S_GAP_MAP_LIF','')
			insert into BEST..TI17REQFNC values ('I17SQPOSP',  'I17S_GAP_MAP_LIF','')
			insert into BEST..TI17REQFNC values ('I17SYPOSP',  'I17S_GAP_MAP_LIF','')


go

