-------------------------------
--mapping of  ESID2070

	----------   Clean tables   ---------------------

	delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESID2070')
	delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESID2070')
	delete BEST..TI17FNC where CHAIN_CT='ESID2070'
	delete BEST..TI17CHN  where CHAIN_CT='ESID2070'

	insert into BEST..TI17CHN values ('ESID2070',  '')

	----------IDF_CT:   ESID2070 ------------------

		insert into BEST..TI17FNC values ('ESID2070',' ','ESID2070',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('ESID2070',  'EST_SUBTRS','${DFILP}/${ENV_PREFIX}_ESCJ0060_FSUBTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2070',  'EST_FTRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2070',  'EST_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2070',  'EST_ARCSTATGTR','${DFILP}/${ENV_PREFIX}_ESIX7000_ARCSTATGTR.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2070',  'EST_IGTR00','${DFILP}/${ENV_PREFIX}_ESIJ7000_IGTR00_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2070',  'EST_FCTRFIC','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCTRFIC_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2070',  'EST_FINTWIT','${DFILP}/${ENV_PREFIX}_ESID0060_FINTWIT_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2070',  'EST_FLSTMTH','${DFILP}/${ENV_PREFIX}_ESID0060_FLSTMTH_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2070',  'EST_FSEGPAR','${DFILP}/${ENV_PREFIX}_ESCJ0060_FSEGPAR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2070',  'EST_IGTAA00','${DFILP}/${ENV_PREFIX}_ESIJ7000_IGTAA00_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2070',  'EST_FCPLACC0','${DFILP}/${ENV_PREFIX}_ESEH1110_FCPLACC0_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2070',  'EST_FVCTRGRO','${DFILP}/${ENV_PREFIX}_ESEH1110_FVCTRGRO_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2070',  'EST_FCESSION1','${DFILP}/${ENV_PREFIX}_ESEH1110_FCESSION1_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2070',  'EST_FDEPOSIT0','${DFILP}/${ENV_PREFIX}_ESID0060_FDEPOSIT0_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2070',  'EST_FPFUNWIT0','${DFILP}/${ENV_PREFIX}_ESID0060_FPFUNWIT0_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2070',  'EST_FPINTWIT0','${DFILP}/${ENV_PREFIX}_ESID0060_FPINTWIT0_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2070',  'EST_FPLACEMT0','${DFILP}/${ENV_PREFIX}_ESEH1110_FPLACEMT0_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2070',  'EST_FPLACEMT1','${DFILP}/${ENV_PREFIX}_ESEH1110_FPLACEMT1_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2070',  'EST_VTSTATGTA0','${DFILP}/${ENV_PREFIX}_ESID1010_VTSTATGTA0_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2070',  'EST_FLIFDRI','${DFILP}/${ENV_PREFIX}_ESCJ0060_FLIFDRI${IT}_ALL_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2070',  'EST_IAVPERICASE0','${DFILP}/${ENV_PREFIX}_ESEH1100_IAVPERICASE0_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2070',  'EST_IRVPERICASE0','${DFILP}/${ENV_PREFIX}_ESID0060_IRVPERICASE0_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2070',  'EST_SUBTRSESBPROP','${DFILP}/${ENV_PREFIX}_ESCJ0060_FSUBTRSESBPROP_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2070',  'EST_FLIFEST0','`if [ "${IT}" = "Q" ];then CH="2";else CH="3";fi;echo "${DFILP}/${ENV_PREFIX}_ESID01${CH}0_FLIFEST${IT}0_${TYPEINV}_${PARM_ICLODAT_D}.dat";`','I','')
			insert into BEST..TI17PERMFIL values ('ESID2070',  'EST_SEGRATANO','${DFILP}/${ENV_PREFIX}_ESID2070_SEGRATANO_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2070',  'EST_CRIBLEANO','${DFILP}/${ENV_PREFIX}_ESID2070_CRIBLEANO${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2070',  'EST_FVPLACEMT','${DFILP}/${ENV_PREFIX}_ESID2070_FVPLACEMT${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2070',  'EST_LIFENDCPT','${DFILP}/${ENV_PREFIX}_ESID2070_LIFENDCPT${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2070',  'EST_LIFESTANA','${DFILP}/${ENV_PREFIX}_ESID2070_LIFESTANA${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2070',  'EST_LIFESTLIB','${DFILP}/${ENV_PREFIX}_ESID2070_LIFESTLIB${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2070',  'EST_FVPLACEMT1','${DFILP}/${ENV_PREFIX}_ESID2070_FVPLACEMT1${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2070',  'EST_FVPLACEMT2','${DFILP}/${ENV_PREFIX}_ESID2070_FVPLACEMT2${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2070',  'EST_ERRUPDBATCH','${DFILP}/${ENV_PREFIX}_ESID2070_ERRUPDBATCH${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2070',  'EST_LIFESTNOACC','${DFILP}/${ENV_PREFIX}_ESID2070_LIFESTNOACC${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2070',  'EST_VLIFEST2070','${DFILP}/${ENV_PREFIX}_ESID2070_VLIFEST2070${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2070',  'EST_FRATTACHEVOL','${DFILP}/${ENV_PREFIX}_ESID2070_FRATTACHEVOL${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2070',  'EST_310_SORT_GT_O','${DFILP}/${ENV_PREFIX}_ESID2070_310_SORT_GT${IT}_O_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2070',  'EST_430_SORT_GT_O','${DFILP}/${ENV_PREFIX}_ESID2070_430_SORT_GT${IT}_O_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2070',  'EST_470_SORT_GT_O','${DFILP}/${ENV_PREFIX}_ESID2070_470_SORT_GT${IT}_O_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2070',  'EST_IARVPERICASE0','${DFILP}/${ENV_PREFIX}_ESID2070_IARVPERICASE0${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2070',  'EST_IARVPERICASE4','${DFILP}/${ENV_PREFIX}_ESID2070_IARVPERICASE4${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2070',  'EST_160_SORT_CPLACC_O','${DFILP}/${ENV_PREFIX}_ESID2070_160_SORT_CPLACC${IT}_O_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2070',  'EST_180_SORT_LSTMTH_O','${DFILP}/${ENV_PREFIX}_ESID2070_180_SORT_LSTMTH${IT}_O_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2070',  'EST_ESTC2035_LIFDRI_O1','${DFILP}/${ENV_PREFIX}_ESID2070_ESTC2035_LIFDRI${IT}_O1_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2070',  'EST_200_ESTC2034_GTB1_O','${DFILP}/${ENV_PREFIX}_ESID2070_200_ESTC2034_GTB1${IT}_O_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2070',  'EST_31_SORT_R_IAVPERICASE_O','${DFILP}/${ENV_PREFIX}_ESID2070_31_SORT_R_IAVPERICASE${IT}_O_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2070',  'EST_180_ESTC2040_OLD_LIFEST_O2','${DFILP}/${ENV_PREFIX}_ESID2070_180_ESTC2040_OLD_LIFEST${IT}_O2_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('A',  'ESID2070','')
			insert into BEST..TI17REQFNC values ('I4IMINV',  'ESID2070','@variante')
			insert into BEST..TI17REQFNC values ('I4IQINV',  'ESID2070','@variante')
			insert into BEST..TI17REQFNC values ('I4IYINV',  'ESID2070','@variante')

	----------IDF_CT:   I4I_Q_PER_LIF ------------------

		insert into BEST..TI17FNC values ('I4I_Q_PER_LIF',' ','ESID2070',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I4I_Q_PER_LIF',  'EST_SUBTRS','${DFILP}/${ENV_PREFIX}_ESCJ0060_FSUBTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_PER_LIF',  'EST_FTRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_PER_LIF',  'EST_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_PER_LIF',  'EST_ARCSTATGTR','${DFILP}/${ENV_PREFIX}_ESIX7000_ARCSTATGTR.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_PER_LIF',  'EST_IGTR00','${DFILP}/${ENV_PREFIX}_ESIJ7000_IGTR00_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_PER_LIF',  'EST_FCTRFIC','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCTRFIC_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_PER_LIF',  'EST_FINTWIT','${DFILP}/${ENV_PREFIX}_ESID0060_FINTWIT_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_PER_LIF',  'EST_FLSTMTH','${DFILP}/${ENV_PREFIX}_ESID0060_FLSTMTH_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_PER_LIF',  'EST_FSEGPAR','${DFILP}/${ENV_PREFIX}_ESCJ0060_FSEGPAR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_PER_LIF',  'EST_IGTAA00','${DFILP}/${ENV_PREFIX}_ESIJ7000_IGTAA00_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_PER_LIF',  'EST_FCPLACC0','${DFILP}/${ENV_PREFIX}_ESEH1110_FCPLACC0_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_PER_LIF',  'EST_FVCTRGRO','${DFILP}/${ENV_PREFIX}_ESEH1110_FVCTRGRO_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_PER_LIF',  'EST_FCESSION1','${DFILP}/${ENV_PREFIX}_ESEH1110_FCESSION1_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_PER_LIF',  'EST_FDEPOSIT0','${DFILP}/${ENV_PREFIX}_ESID0060_FDEPOSIT0_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_PER_LIF',  'EST_FPFUNWIT0','${DFILP}/${ENV_PREFIX}_ESID0060_FPFUNWIT0_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_PER_LIF',  'EST_FPINTWIT0','${DFILP}/${ENV_PREFIX}_ESID0060_FPINTWIT0_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_PER_LIF',  'EST_FPLACEMT0','${DFILP}/${ENV_PREFIX}_ESEH1110_FPLACEMT0_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_PER_LIF',  'EST_FPLACEMT1','${DFILP}/${ENV_PREFIX}_ESEH1110_FPLACEMT1_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_PER_LIF',  'EST_VTSTATGTA0','${DFILP}/${ENV_PREFIX}_ESID1010_VTSTATGTA0_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_PER_LIF',  'EST_FLIFDRI','${DFILP}/${ENV_PREFIX}_ESCJ0060_FLIFDRI${IT}_ALL_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_PER_LIF',  'EST_IAVPERICASE0','${DFILP}/${ENV_PREFIX}_ESEH1100_IAVPERICASE0_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_PER_LIF',  'EST_IRVPERICASE0','${DFILP}/${ENV_PREFIX}_ESID0060_IRVPERICASE0_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_PER_LIF',  'EST_SUBTRSESBPROP','${DFILP}/${ENV_PREFIX}_ESCJ0060_FSUBTRSESBPROP_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_PER_LIF',  'EST_FLIFEST0','`if [ "${IT}" = "Q" ];then CH="2";else CH="3";fi;echo "${DFILP}/${ENV_PREFIX}_ESID01${CH}0_FLIFEST${IT}0_${TYPEINV}_${PARM_ICLODAT_D}.dat";`','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_PER_LIF',  'EST_SEGRATANO','${DFILP}/${ENV_PREFIX}_ESID2070_SEGRATANO_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_PER_LIF',  'EST_CRIBLEANO','${DFILP}/${ENV_PREFIX}_ESID2070_CRIBLEANO${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_PER_LIF',  'EST_FVPLACEMT','${DFILP}/${ENV_PREFIX}_ESID2070_FVPLACEMT${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_PER_LIF',  'EST_LIFENDCPT','${DFILP}/${ENV_PREFIX}_ESID2070_LIFENDCPT${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_PER_LIF',  'EST_LIFESTANA','${DFILP}/${ENV_PREFIX}_ESID2070_LIFESTANA${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_PER_LIF',  'EST_LIFESTLIB','${DFILP}/${ENV_PREFIX}_ESID2070_LIFESTLIB${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_PER_LIF',  'EST_FVPLACEMT1','${DFILP}/${ENV_PREFIX}_ESID2070_FVPLACEMT1${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_PER_LIF',  'EST_FVPLACEMT2','${DFILP}/${ENV_PREFIX}_ESID2070_FVPLACEMT2${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_PER_LIF',  'EST_ERRUPDBATCH','${DFILP}/${ENV_PREFIX}_ESID2070_ERRUPDBATCH${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_PER_LIF',  'EST_LIFESTNOACC','${DFILP}/${ENV_PREFIX}_ESID2070_LIFESTNOACC${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_PER_LIF',  'EST_VLIFEST2070','${DFILP}/${ENV_PREFIX}_ESID2070_VLIFEST2070${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_PER_LIF',  'EST_FRATTACHEVOL','${DFILP}/${ENV_PREFIX}_ESID2070_FRATTACHEVOL${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_PER_LIF',  'EST_310_SORT_GT_O','${DFILP}/${ENV_PREFIX}_ESID2070_310_SORT_GT${IT}_O_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_PER_LIF',  'EST_430_SORT_GT_O','${DFILP}/${ENV_PREFIX}_ESID2070_430_SORT_GT${IT}_O_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_PER_LIF',  'EST_470_SORT_GT_O','${DFILP}/${ENV_PREFIX}_ESID2070_470_SORT_GT${IT}_O_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_PER_LIF',  'EST_IARVPERICASE0','${DFILP}/${ENV_PREFIX}_ESID2070_IARVPERICASE0${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_PER_LIF',  'EST_IARVPERICASE4','${DFILP}/${ENV_PREFIX}_ESID2070_IARVPERICASE4${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_PER_LIF',  'EST_160_SORT_CPLACC_O','${DFILP}/${ENV_PREFIX}_ESID2070_160_SORT_CPLACC${IT}_O_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_PER_LIF',  'EST_180_SORT_LSTMTH_O','${DFILP}/${ENV_PREFIX}_ESID2070_180_SORT_LSTMTH${IT}_O_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_PER_LIF',  'EST_ESTC2035_LIFDRI_O1','${DFILP}/${ENV_PREFIX}_ESID2070_ESTC2035_LIFDRI${IT}_O1_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_PER_LIF',  'EST_200_ESTC2034_GTB1_O','${DFILP}/${ENV_PREFIX}_ESID2070_200_ESTC2034_GTB1${IT}_O_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_PER_LIF',  'EST_31_SORT_R_IAVPERICASE_O','${DFILP}/${ENV_PREFIX}_ESID2070_31_SORT_R_IAVPERICASE${IT}_O_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_PER_LIF',  'EST_180_ESTC2040_OLD_LIFEST_O2','${DFILP}/${ENV_PREFIX}_ESID2070_180_ESTC2040_OLD_LIFEST${IT}_O2_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I4IMINV',  'I4I_Q_PER_LIF','@variante')
			insert into BEST..TI17REQFNC values ('I4IQINV',  'I4I_Q_PER_LIF','@variante')
			insert into BEST..TI17REQFNC values ('I4IYINV',  'I4I_Q_PER_LIF','@variante')

	----------IDF_CT:   I4I_Y_PER_LIF ------------------

		insert into BEST..TI17FNC values ('I4I_Y_PER_LIF',' ','ESID2070',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I4I_Y_PER_LIF',  'EST_SUBTRS','${DFILP}/${ENV_PREFIX}_ESCJ0060_FSUBTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_PER_LIF',  'EST_FTRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_PER_LIF',  'EST_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_PER_LIF',  'EST_ARCSTATGTR','${DFILP}/${ENV_PREFIX}_ESIX7000_ARCSTATGTR.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_PER_LIF',  'EST_IGTR00','${DFILP}/${ENV_PREFIX}_ESIJ7000_IGTR00_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_PER_LIF',  'EST_FCTRFIC','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCTRFIC_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_PER_LIF',  'EST_FINTWIT','${DFILP}/${ENV_PREFIX}_ESID0060_FINTWIT_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_PER_LIF',  'EST_FLSTMTH','${DFILP}/${ENV_PREFIX}_ESID0060_FLSTMTH_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_PER_LIF',  'EST_FSEGPAR','${DFILP}/${ENV_PREFIX}_ESCJ0060_FSEGPAR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_PER_LIF',  'EST_IGTAA00','${DFILP}/${ENV_PREFIX}_ESIJ7000_IGTAA00_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_PER_LIF',  'EST_FCPLACC0','${DFILP}/${ENV_PREFIX}_ESEH1110_FCPLACC0_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_PER_LIF',  'EST_FVCTRGRO','${DFILP}/${ENV_PREFIX}_ESEH1110_FVCTRGRO_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_PER_LIF',  'EST_FCESSION1','${DFILP}/${ENV_PREFIX}_ESEH1110_FCESSION1_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_PER_LIF',  'EST_FDEPOSIT0','${DFILP}/${ENV_PREFIX}_ESID0060_FDEPOSIT0_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_PER_LIF',  'EST_FPFUNWIT0','${DFILP}/${ENV_PREFIX}_ESID0060_FPFUNWIT0_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_PER_LIF',  'EST_FPINTWIT0','${DFILP}/${ENV_PREFIX}_ESID0060_FPINTWIT0_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_PER_LIF',  'EST_FPLACEMT0','${DFILP}/${ENV_PREFIX}_ESEH1110_FPLACEMT0_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_PER_LIF',  'EST_FPLACEMT1','${DFILP}/${ENV_PREFIX}_ESEH1110_FPLACEMT1_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_PER_LIF',  'EST_VTSTATGTA0','${DFILP}/${ENV_PREFIX}_ESID1010_VTSTATGTA0_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_PER_LIF',  'EST_FLIFDRI','${DFILP}/${ENV_PREFIX}_ESCJ0060_FLIFDRI${IT}_ALL_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_PER_LIF',  'EST_IAVPERICASE0','${DFILP}/${ENV_PREFIX}_ESEH1100_IAVPERICASE0_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_PER_LIF',  'EST_IRVPERICASE0','${DFILP}/${ENV_PREFIX}_ESID0060_IRVPERICASE0_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_PER_LIF',  'EST_SUBTRSESBPROP','${DFILP}/${ENV_PREFIX}_ESCJ0060_FSUBTRSESBPROP_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_PER_LIF',  'EST_FLIFEST0','`if [ "${IT}" = "Q" ];then CH="2";else CH="3";fi;echo "${DFILP}/${ENV_PREFIX}_ESID01${CH}0_FLIFEST${IT}0_${TYPEINV}_${PARM_ICLODAT_D}.dat";`','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_PER_LIF',  'EST_SEGRATANO','${DFILP}/${ENV_PREFIX}_ESID2070_SEGRATANO_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_PER_LIF',  'EST_CRIBLEANO','${DFILP}/${ENV_PREFIX}_ESID2070_CRIBLEANO${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_PER_LIF',  'EST_FVPLACEMT','${DFILP}/${ENV_PREFIX}_ESID2070_FVPLACEMT${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_PER_LIF',  'EST_LIFENDCPT','${DFILP}/${ENV_PREFIX}_ESID2070_LIFENDCPT${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_PER_LIF',  'EST_LIFESTANA','${DFILP}/${ENV_PREFIX}_ESID2070_LIFESTANA${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_PER_LIF',  'EST_LIFESTLIB','${DFILP}/${ENV_PREFIX}_ESID2070_LIFESTLIB${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_PER_LIF',  'EST_FVPLACEMT1','${DFILP}/${ENV_PREFIX}_ESID2070_FVPLACEMT1${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_PER_LIF',  'EST_FVPLACEMT2','${DFILP}/${ENV_PREFIX}_ESID2070_FVPLACEMT2${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_PER_LIF',  'EST_ERRUPDBATCH','${DFILP}/${ENV_PREFIX}_ESID2070_ERRUPDBATCH${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_PER_LIF',  'EST_LIFESTNOACC','${DFILP}/${ENV_PREFIX}_ESID2070_LIFESTNOACC${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_PER_LIF',  'EST_VLIFEST2070','${DFILP}/${ENV_PREFIX}_ESID2070_VLIFEST2070${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_PER_LIF',  'EST_FRATTACHEVOL','${DFILP}/${ENV_PREFIX}_ESID2070_FRATTACHEVOL${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_PER_LIF',  'EST_310_SORT_GT_O','${DFILP}/${ENV_PREFIX}_ESID2070_310_SORT_GT${IT}_O_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_PER_LIF',  'EST_430_SORT_GT_O','${DFILP}/${ENV_PREFIX}_ESID2070_430_SORT_GT${IT}_O_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_PER_LIF',  'EST_470_SORT_GT_O','${DFILP}/${ENV_PREFIX}_ESID2070_470_SORT_GT${IT}_O_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_PER_LIF',  'EST_IARVPERICASE0','${DFILP}/${ENV_PREFIX}_ESID2070_IARVPERICASE0${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_PER_LIF',  'EST_IARVPERICASE4','${DFILP}/${ENV_PREFIX}_ESID2070_IARVPERICASE4${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_PER_LIF',  'EST_160_SORT_CPLACC_O','${DFILP}/${ENV_PREFIX}_ESID2070_160_SORT_CPLACC${IT}_O_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_PER_LIF',  'EST_180_SORT_LSTMTH_O','${DFILP}/${ENV_PREFIX}_ESID2070_180_SORT_LSTMTH${IT}_O_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_PER_LIF',  'EST_ESTC2035_LIFDRI_O1','${DFILP}/${ENV_PREFIX}_ESID2070_ESTC2035_LIFDRI${IT}_O1_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_PER_LIF',  'EST_200_ESTC2034_GTB1_O','${DFILP}/${ENV_PREFIX}_ESID2070_200_ESTC2034_GTB1${IT}_O_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_PER_LIF',  'EST_31_SORT_R_IAVPERICASE_O','${DFILP}/${ENV_PREFIX}_ESID2070_31_SORT_R_IAVPERICASE${IT}_O_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_PER_LIF',  'EST_180_ESTC2040_OLD_LIFEST_O2','${DFILP}/${ENV_PREFIX}_ESID2070_180_ESTC2040_OLD_LIFEST${IT}_O2_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I4IMINV',  'I4I_Y_PER_LIF','@variante')
			insert into BEST..TI17REQFNC values ('I4IQINV',  'I4I_Y_PER_LIF','@variante')
			insert into BEST..TI17REQFNC values ('I4IYINV',  'I4I_Y_PER_LIF','@variante')
go

