---- ESID70000
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESIX7000_STATGTACTL.dat'		where IDF_CT='ESID7000'	 and PERMFIL_CT= 'EST_STATGTACTL'				
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESIX7000_FVENTNPANT.dat'		where  PATHPATTRN_LL  like  "%_ESIX7000_FVENTNPANT%" 			
--select * from BEST..TI17PERMFIL where IDF_CT='ESID7000'	 and PERMFIL_CT= 'EST_STATGTACTL'		

--- correction des ${CLODAT} qui restent 


update BEST..TI17PERMFIL 
set PATHPATTRN_LL = str_replace (PATHPATTRN_LL, "${CLODAT}.dat", "${TYPEINV}_${PARM_ICLODAT_D}.dat")
--select * from BEST..TI17PERMFIL  
where  PATHPATTRN_LL  like  "%${CLODAT}%"

update BEST..TI17PERMFIL 
set PATHPATTRN_LL = str_replace (PATHPATTRN_LL, "{DFILI}", "{DFILP}")
--select * from BEST..TI17PERMFIL 
 where idf_ct like "%ESID0060%"  
 

update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID0060_EST_ANN_LIMIT_FAC_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID0060'	 and PERMFIL_CT= 'EST_ANN_LIMIT_FAC'				
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID0060_EST_ANN_LIMIT_TRT_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID0060'	 and PERMFIL_CT= 'EST_ANN_LIMIT_TRT'				
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURQUOT_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID0060'	 and PERMFIL_CT= 'EST_FCURQUOT'				
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${PCH}ESID0060_FDATDERCPA_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID0060'	 and PERMFIL_CT= 'EST_FDATDERCPA'				


--remplacement de ${NORME0} par SII

update BEST..TI17PERMFIL 
set PATHPATTRN_LL = str_replace (PATHPATTRN_LL, "${NORME0}", "SII")
--select * from BEST..TI17PERMFIL 
where  PATHPATTRN_LL  like  '%${NORME0}%'

-- correction d'une mauvaise livraison:un blanc entre ESPD1800 et I17 (Linh)
update BEST..TI17PERMFIL 
set PATHPATTRN_LL = str_replace (PATHPATTRN_LL, "ESPD1800_ I17", "ESPD1800_I17")
--select * from BEST..TI17PERMFIL 
where  PATHPATTRN_LL  like  '%ESPD1800_ I17%'
 
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${PCH}ESID0060_FDATDERCPA_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID0060'	 and PERMFIL_CT= 'EST_FDATDERCPA'				 
			
 
-- correction TECLEDA*
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILI}/${ENV_PREFIX}_ESID8710_DIFF_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID8710'	 and PERMFIL_CT= 'EST_FTECLEDA_DIFF'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID8710'	 and PERMFIL_CT= 'EST_FTECLEDA'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESPT0000'	 and PERMFIL_CT= 'EST_FTECLEDA'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='DWUD0130'	 and PERMFIL_CT= 'EST_FTECLEDA'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='DWUD9130'	 and PERMFIL_CT= 'EST_FTECLEDA'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID8100'	 and PERMFIL_CT= 'EST_FTECLEDA'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID8700'	 and PERMFIL_CT= 'EST_FTECLEDA'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID8800'	 and PERMFIL_CT= 'EST_FTECLEDA'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='STAD1530'	 and PERMFIL_CT= 'EST_FTECLEDA'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_GAP_MAP_STD'	 and PERMFIL_CT= 'EST_FTECLEDA'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID8700_I4_PC___FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID8700_I4_PC___'	 and PERMFIL_CT= 'EST_FTECLEDA'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID8700_I4_PC___FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID8710'	 and PERMFIL_CT= 'EST_FTECLEDA_PC'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESLD3800_FTECLEDALO${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESLD8100'	 and PERMFIL_CT= 'ESL_FTECLEDALO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDASII_ANNULMVTSII_POC_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD8100'	 and PERMFIL_CT= 'EPO_FTECLEDACO_ANNULMVT'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDASII_ANNULMVT_POC_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD8100'	 and PERMFIL_CT= 'EPO_FTECLEDACO_ANNULMVT'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDASII_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD3800'	 and PERMFIL_CT= 'EPO_FTECLEDACO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDASII_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD3800'	 and PERMFIL_CT= 'EPO_FTECLEDACO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDASII_POC_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD3850'	 and PERMFIL_CT= 'EPO_FTECLEDASIICO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDASII_ANNULMVT_POC_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD3800'	 and PERMFIL_CT= 'EPO_FTECLEDASIICO_ANNULMVT'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDASII_ANNULMVTSII_POC_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD3800'	 and PERMFIL_CT= 'EPO_FTECLEDASIICO_ANNULMVT'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDASII_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESPD2900'	 and PERMFIL_CT= 'EPO_FTECLEDASIISO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDASII_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='DWUD0130'	 and PERMFIL_CT= 'EPO_FTECLEDASIISO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDASII_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='DWUD9130'	 and PERMFIL_CT= 'EPO_FTECLEDASIISO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDASII_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESPD2900'	 and PERMFIL_CT= 'EPO_FTECLEDASIISO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDASII_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD8830'	 and PERMFIL_CT= 'EPO_FTECLEDASIISO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDASII_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD8800'	 and PERMFIL_CT= 'EPO_FTECLEDASIISO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDASII_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD8830'	 and PERMFIL_CT= 'EPO_FTECLEDASIISO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESPD8700'	 and PERMFIL_CT= 'EPO_FTECLEDASO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='DWUD0130'	 and PERMFIL_CT= 'EPO_FTECLEDASO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='DWUD9130'	 and PERMFIL_CT= 'EPO_FTECLEDASO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD8800'	 and PERMFIL_CT= 'EPO_FTECLEDASO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD8830'	 and PERMFIL_CT= 'EPO_FTECLEDASO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD8830'	 and PERMFIL_CT= 'EPO_FTECLEDASO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_MVT_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESPD8700'	 and PERMFIL_CT= 'EPO_FTECLEDASO_MVT'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESPD8700'	 and PERMFIL_CT= 'EPO_FTECLEDA'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_POC_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESFD2220'	 and PERMFIL_CT= 'EPO_FTECLEDACO'

-- correction TECLEDR*
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILI}/${ENV_PREFIX}_ESID8710_DIFF_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID8710'	 and PERMFIL_CT= 'EST_FTECLEDR_DIFF'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID3800_I4_PC_C__'	 and PERMFIL_CT= 'EST_FTECLEDR'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID8710'	 and PERMFIL_CT= 'EST_FTECLEDR'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESPT0000'	 and PERMFIL_CT= 'EST_FTECLEDR'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='DWUD0130'	 and PERMFIL_CT= 'EST_FTECLEDR'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='DWUD9130'	 and PERMFIL_CT= 'EST_FTECLEDR'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID8100'	 and PERMFIL_CT= 'EST_FTECLEDR'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID8700'	 and PERMFIL_CT= 'EST_FTECLEDR'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID8800'	 and PERMFIL_CT= 'EST_FTECLEDR'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_GAP_MAP_STD'	 and PERMFIL_CT= 'EST_FTECLEDR'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID8700_I4_PC___FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID8700_I4_PC___'	 and PERMFIL_CT= 'EST_FTECLEDR'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID8700_I4_PC___FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID8710'	 and PERMFIL_CT= 'EST_FTECLEDR_PC'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESLD3800_FTECLEDRLO${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESLD8100'	 and PERMFIL_CT= 'ESL_FTECLEDRLO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDRSII_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD8100'	 and PERMFIL_CT= 'EST_FTECLEDR'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDRSII_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD8100'	 and PERMFIL_CT= 'EST_FTECLEDR'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDRSII_POC_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD3850'	 and PERMFIL_CT= 'EPO_FTECLEDRCO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDRCO_ANNULMVT_I4I_POC_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD3800'	 and PERMFIL_CT= 'EPO_FTECLEDRCO_ANNULMVT'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDRCO_ANNULMVT_EBS_POC_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD3800'	 and PERMFIL_CT= 'EPO_FTECLEDRCO_ANNULMVT'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDRSII_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD3810'	 and PERMFIL_CT= 'EPO_FTECLEDRSII'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDRSII_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD3810'	 and PERMFIL_CT= 'EPO_FTECLEDRSII'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDRSII_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD3800'	 and PERMFIL_CT= 'EPO_FTECLEDRCO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDRSII_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD3800'	 and PERMFIL_CT= 'EPO_FTECLEDRCO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDRSII_POC_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD3850'	 and PERMFIL_CT= 'EPO_FTECLEDRSIICO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_ANNULMVT_I4I_POC_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD3800'	 and PERMFIL_CT= 'EPO_FTECLEDRSIICO_ANNULMVT'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_ANNULMVT_EBS_POC_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD3800'	 and PERMFIL_CT= 'EPO_FTECLEDRSIICO_ANNULMVT'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDRSII_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESPD2900'	 and PERMFIL_CT= 'EPO_FTECLEDRSIISO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDRSII_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='DWUD0130'	 and PERMFIL_CT= 'EPO_FTECLEDRSIISO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDRSII_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='DWUD9130'	 and PERMFIL_CT= 'EPO_FTECLEDRSIISO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDRSII_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESPD2900'	 and PERMFIL_CT= 'EPO_FTECLEDRSIISO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDRSII_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD8830'	 and PERMFIL_CT= 'EPO_FTECLEDRSIISO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDRSII_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD8800'	 and PERMFIL_CT= 'EPO_FTECLEDRSIISO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDRSII_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD8830'	 and PERMFIL_CT= 'EPO_FTECLEDRSIISO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD3800'	 and PERMFIL_CT= 'EPO_FTECLEDRSO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD3800'	 and PERMFIL_CT= 'EPO_FTECLEDRSO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='DWUD0130'	 and PERMFIL_CT= 'EPO_FTECLEDRSO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='DWUD9130'	 and PERMFIL_CT= 'EPO_FTECLEDRSO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD8800'	 and PERMFIL_CT= 'EPO_FTECLEDRSO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD8830'	 and PERMFIL_CT= 'EPO_FTECLEDRSO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD8800'	 and PERMFIL_CT= 'EPO_FTECLEDRSO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD8830'	 and PERMFIL_CT= 'EPO_FTECLEDRSO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD3800'	 and PERMFIL_CT= 'EPO_FTECLEDR'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD8830'	 and PERMFIL_CT= 'EPO_FTECLEDR'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD3800'	 and PERMFIL_CT= 'EPO_FTECLEDR'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD8830'	 and PERMFIL_CT= 'EPO_FTECLEDR'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD2570'	 and PERMFIL_CT= 'EPO_FTECLEDRSO'


-- 2ème passe de correction
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID3800_I4_PC_C__'	 and PERMFIL_CT= 'EST_FTECLEDA'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDASII_POC_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD3850'	 and PERMFIL_CT= 'EPO_FTECLEDACO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_CUR_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD3800'	 and PERMFIL_CT= 'EPO_FTECLEDASO_CUR'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_CUR_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD3800'	 and PERMFIL_CT= 'EPO_FTECLEDASO_CUR'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_CUR_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESPD8700'	 and PERMFIL_CT= 'EPO_FTECLEDASO_CUR'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_CUR_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD8830'	 and PERMFIL_CT= 'EPO_FTECLEDASO_CUR'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_CUR_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD8830'	 and PERMFIL_CT= 'EPO_FTECLEDASO_CUR'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_MTH_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD3800'	 and PERMFIL_CT= 'EPO_FTECLEDASO_MTH'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_MTH_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD3800'	 and PERMFIL_CT= 'EPO_FTECLEDASO_MTH'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_MTH_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESPD8700'	 and PERMFIL_CT= 'EPO_FTECLEDASO_MTH'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDASII_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESFD4020'	 and PERMFIL_CT= 'EST_FTECLEDASII'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDASII_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESID2210'	 and PERMFIL_CT= 'EST_FTECLEDASII'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDASII_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESID2210'	 and PERMFIL_CT= 'EPO_FTECLEDASIISO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDASII_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESID2210'	 and PERMFIL_CT= 'EST_FTECLEDASIISO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '$DFILP/${ENV_PREFIX}_ESPD3800_FTECLEDA_EBS_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESID2210'	 and PERMFIL_CT= 'EST_CURGTA'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '$DFILP/${ENV_PREFIX}_ESPD3800_FTECLEDA_EBS_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESID2210'	 and PERMFIL_CT= 'EST_IGTAAF'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '$DFILP/${ENV_PREFIX}_ESPD3800_FTECLEDA_EBS_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESID2210'	 and PERMFIL_CT= 'EPO_FTECLEDASO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '$DFILP/${ENV_PREFIX}_ESPD3800_FTECLEDA_EBS_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESID2210'	 and PERMFIL_CT= 'EST_FTECLEDASO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESID2210'	 and PERMFIL_CT= 'EPO_FTECLEDRSO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '`if [ ${TYPEINV} = POS ];then echo ${DFILP}/empty.dat;else echo ${DFILP}/${ENV_PREFIX}_${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDASII_${TYPEINV}_${PARM_ICLODAT_D}.dat;fi;`'		where IDF_CT='EBS_ESPD3610'	 and PERMFIL_CT= 'EST_FTECLEDASII'

update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3700_FTECLEDSII${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID8600'	 and PERMFIL_CT= 'EST_FTECLEDSII'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_ANNULMVT_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD8100'	 and PERMFIL_CT= 'EPO_FTECLEDACO_ANNULMVT'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_ANNULMVT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD8100'	 and PERMFIL_CT= 'EPO_FTECLEDACO_ANNULMVT'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD3810'	 and PERMFIL_CT= 'EPO_FTECLEDA'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_ANNULMVT_I4I_POC_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD3800'	 and PERMFIL_CT= 'EPO_FTECLEDACO_ANNULMVT'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_ANNULMVT_EBS_POC_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD3800'	 and PERMFIL_CT= 'EPO_FTECLEDACO_ANNULMVT'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_ANNULMVT_I4I_POC_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD3800'	 and PERMFIL_CT= 'EPO_FTECLEDASIICO_ANNULMVT'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_ANNULMVT_EBS_POC_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD3800'	 and PERMFIL_CT= 'EPO_FTECLEDASIICO_ANNULMVT'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_ANNULMVT_EBS_POC_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD3800'	 and PERMFIL_CT= 'EPO_FTECLEDRCO_ANNULMVT'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_ANNULMVT_I4I_POC_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD3800'	 and PERMFIL_CT= 'EPO_FTECLEDRCO_ANNULMVT'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3700_FTECLEDSII_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESID2210'	 and PERMFIL_CT= 'EST_FTECLEDSII'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESID2210'	 and PERMFIL_CT= 'EPO_FTECLEDRSO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD4000_DLEIFTECLEDSIIEP_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESID2210'	 and PERMFIL_CT= 'EST_DLEIFTECLEDSIIEP'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD4000_DLEIFTECLEDSIIEP_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD8830'	 and PERMFIL_CT= 'EPO_DLEIFTECLEDSIIEPSO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD4000_DLEIFTECLEDEP_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD8830'	 and PERMFIL_CT= 'EPO_DLEIFTECLEDSIIEPSO'


update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESID2210'	 and PERMFIL_CT= 'EPO_FTECLEDRSO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD4000_DLEIFTECLEDSIIEP_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD8830'	 and PERMFIL_CT= 'EPO_DLEIFTECLEDSIIEPSO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD4000_DLEIFTECLEDEP_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD8830'	 and PERMFIL_CT= 'EPO_DLEIFTECLEDSIIEPSO'


-- Pour faire avancer l'inventaire EUROPE du 13/03 il manque _ entre ESFD5000 et I17 plantage ESFD5010 et ESFD25020
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD5000_I17G_TMP_PER_INI_PROTO_IADPERICASE_INI_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='I17G_MRG_PER_INI'	 and PERMFIL_CT= 'EST_PROTO_IADPERICASE_POS'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESFD5000_I17P_TMP_PER_INI_PROTO_IADPERICASE_INI_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='I17P_MRG_PER_INI'	 and PERMFIL_CT= 'EST_PROTO_IADPERICASE_POS'
go



if not exists(select 1 from BEST..TI17PERMFIL  	where IDF_CT='ESID2000'	 		 and PERMFIL_CT= 'EST_FBOPRSLNK' )
	insert into BEST..TI17PERMFIL values ( 'ESID2000','EST_FBOPRSLNK', '${DFILP}/${ENV_PREFIX}_ESCJ0060_FBOPRSLNK_${TYPEINV}_${PARM_ICLODAT_D}.dat' , "I","")

if not exists(select 1 from BEST..TI17PERMFIL  	where IDF_CT='EBS_ESFD2210___AA0'	 		 and PERMFIL_CT= 'EST_FBOPRSLNK' )
	insert into BEST..TI17PERMFIL values ( 'EBS_ESFD2210___AA0','EST_FBOPRSLNK', '${DFILP}/${ENV_PREFIX}_ESCJ0060_FBOPRSLNK_${TYPEINV}_${PARM_ICLODAT_D}.dat' , "I","")

if not exists(select 1 from BEST..TI17PERMFIL  	where IDF_CT='EBS_ESFD2210___AA1'	 		 and PERMFIL_CT= 'EST_FBOPRSLNK' )
	insert into BEST..TI17PERMFIL values ( 'EBS_ESFD2210___AA1','EST_FBOPRSLNK', '${DFILP}/${ENV_PREFIX}_ESCJ0060_FBOPRSLNK_${TYPEINV}_${PARM_ICLODAT_D}.dat' , "I","")

if not exists(select 1 from BEST..TI17PERMFIL  	where IDF_CT='EBS_ESFD2210___AA2'	 		 and PERMFIL_CT= 'EST_FBOPRSLNK' )
	insert into BEST..TI17PERMFIL values ( 'EBS_ESFD2210___AA2','EST_FBOPRSLNK', '${DFILP}/${ENV_PREFIX}_ESCJ0060_FBOPRSLNK_${TYPEINV}_${PARM_ICLODAT_D}.dat' , "I","")

if not exists(select 1 from BEST..TI17PERMFIL  	where IDF_CT='EBS_ESFD2210___AA3'	 		 and PERMFIL_CT= 'EST_FBOPRSLNK' )
	insert into BEST..TI17PERMFIL values ( 'EBS_ESFD2210___AA3','EST_FBOPRSLNK', '${DFILP}/${ENV_PREFIX}_ESCJ0060_FBOPRSLNK_${TYPEINV}_${PARM_ICLODAT_D}.dat' , "I","")

update BEST..TI17PERMFIL  set PATHPATTRN_LL = '`if [ "${TYPEINV}" = "POS" ];then echo ${DFILP}/empty.dat;else echo ${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDASII_POS_${PARM_ICLODAT_D}.dat;fi;`'	where IDF_CT='EBS_ESPD3630'	 and PERMFIL_CT= 'EST_FTECLEDASII'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '`if [ "${TYPEINV}" = "POS" ];then echo ${DFILP}/empty.dat;else echo ${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDASII_POS_${PARM_ICLODAT_D}.dat;fi;`'	where IDF_CT='EBS_ESPD3630'	 and PERMFIL_CT= 'EST_FTECLEDASIISO'



-- correction de Roger 

update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3700_FTECLED_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD8100'	 and PERMFIL_CT= 'EST_FTECLEDSII'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3700_FTECLED_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID8600'	 and PERMFIL_CT= 'EST_FTECLEDSII'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDA_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID3800_I4_PC_C__'	 and PERMFIL_CT= 'EST_FTECLEDA'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDA_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='DWUD0130'	 and PERMFIL_CT= 'EST_FTECLEDA'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDA_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='DWUD9130'	 and PERMFIL_CT= 'EST_FTECLEDA'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDA_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID8100'	 and PERMFIL_CT= 'EST_FTECLEDA'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDA_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID8700'	 and PERMFIL_CT= 'EST_FTECLEDA'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDA_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID8800'	 and PERMFIL_CT= 'EST_FTECLEDA'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDA_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESPT0000'	 and PERMFIL_CT= 'EST_FTECLEDA'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDA_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='STAD1530'	 and PERMFIL_CT= 'EST_FTECLEDA'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDA_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_GAP_MAP_STD'	 and PERMFIL_CT= 'EST_FTECLEDA'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='I17G_GAP_MAP_STD'	 and PERMFIL_CT= 'EST_FTECLEDA'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDA_CUR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID3800_I4_PC_C__'	 and PERMFIL_CT= 'EST_FTECLEDA_CUR'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDA_CUR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID8700'	 and PERMFIL_CT= 'EST_FTECLEDA_CUR'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDA_CUR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID8700_I4_PC___'	 and PERMFIL_CT= 'EST_FTECLEDA_CUR'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDA_MTH_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID3810'	 and PERMFIL_CT= 'EST_FTECLEDA_MTH'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDA_MTH_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID7000'	 and PERMFIL_CT= 'EST_FTECLEDA_MTH'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDA_MTH_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID8700'	 and PERMFIL_CT= 'EST_FTECLEDA_MTH'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDA_MVT_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID3810'	 and PERMFIL_CT= 'EST_FTECLEDA_MVT'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDA_MVT_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID3850'	 and PERMFIL_CT= 'EST_FTECLEDA_MVT'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDA_MVT_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID7000'	 and PERMFIL_CT= 'EST_FTECLEDA_MVT'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDA_MVT_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID8700'	 and PERMFIL_CT= 'EST_FTECLEDA_MVT'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDA_REP_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID3810'	 and PERMFIL_CT= 'EST_FTECLEDA_REP'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDA_REP_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID8700'	 and PERMFIL_CT= 'EST_FTECLEDA_REP'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID3800_I4_PC_C__'	 and PERMFIL_CT= 'EST_FTECLEDR'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='DWUD0130'	 and PERMFIL_CT= 'EST_FTECLEDR'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='DWUD9130'	 and PERMFIL_CT= 'EST_FTECLEDR'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID8100'	 and PERMFIL_CT= 'EST_FTECLEDR'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID8700'	 and PERMFIL_CT= 'EST_FTECLEDR'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID8800'	 and PERMFIL_CT= 'EST_FTECLEDR'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESPT0000'	 and PERMFIL_CT= 'EST_FTECLEDR'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_GAP_MAP_STD'	 and PERMFIL_CT= 'EST_FTECLEDR'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDR_CUR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID3800_I4_PC_C__'	 and PERMFIL_CT= 'EST_FTECLEDR_CUR'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDR_CUR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID8700'	 and PERMFIL_CT= 'EST_FTECLEDR_CUR'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDR_CUR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID8700_I4_PC___'	 and PERMFIL_CT= 'EST_FTECLEDR_CUR'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDR_MVT_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID3810'	 and PERMFIL_CT= 'EST_FTECLEDR_MVT'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDR_MVT_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID8700'	 and PERMFIL_CT= 'EST_FTECLEDR_MVT'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_PC___FTECLEDA_MTH_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID3800_I4_PC_M__'	 and PERMFIL_CT= 'EST_FTECLEDA_MTH'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_PC___FTECLEDA_MTH_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID8700_I4_PC___'	 and PERMFIL_CT= 'EST_FTECLEDA_MTH'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_PC___FTECLEDA_MVT_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID3800_I4_PC_M__'	 and PERMFIL_CT= 'EST_FTECLEDA_MVT'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_PC___FTECLEDA_MVT_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID8700_I4_PC___'	 and PERMFIL_CT= 'EST_FTECLEDA_MVT'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_PC___FTECLEDA_REP_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID3800_I4_PC_M__'	 and PERMFIL_CT= 'EST_FTECLEDA_REP'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_PC___FTECLEDA_REP_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID8700_I4_PC___'	 and PERMFIL_CT= 'EST_FTECLEDA_REP'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_PC___FTECLEDR_MVT_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID3800_I4_PC_M__'	 and PERMFIL_CT= 'EST_FTECLEDR_MVT'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_PC___FTECLEDR_MVT_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID8700_I4_PC___'	 and PERMFIL_CT= 'EST_FTECLEDR_MVT'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID8700_PC___FTECLEDA_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID8700_I4_PC___'	 and PERMFIL_CT= 'EST_FTECLEDA'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID8700_PC___FTECLEDR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESID8700_I4_PC___'	 and PERMFIL_CT= 'EST_FTECLEDR'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESLD3800_FTECLEDA_I4I_LOC_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESLD3800'	 and PERMFIL_CT= 'ESL_FTECLEDALO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESLD3800_FTECLEDA_I4I_LOC_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESLD8700'	 and PERMFIL_CT= 'ESL_FTECLEDALO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESLD3800_FTECLEDA_MTH_I4I_LOC_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESLD3800'	 and PERMFIL_CT= 'ESL_FTECLEDALO_MTH'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESLD3800_FTECLEDA_MTH_I4I_LOC_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESLD8700'	 and PERMFIL_CT= 'ESL_FTECLEDALO_MTH'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESLD3800_FTECLEDA_MVT_I4I_LOC_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESLD3800'	 and PERMFIL_CT= 'ESL_FTECLEDALO_MVT'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESLD3800_FTECLEDA_MVT_I4I_LOC_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESLD3850'	 and PERMFIL_CT= 'ESL_FTECLEDALO_MVT'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESLD3800_FTECLEDA_MVT_I4I_LOC_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESLD8700'	 and PERMFIL_CT= 'ESL_FTECLEDALO_MVT'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESLD3800_FTECLEDR_I4I_LOC_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESLD3800'	 and PERMFIL_CT= 'ESL_FTECLEDRLO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3700_FTECLED_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD8100'	 and PERMFIL_CT= 'EST_FTECLEDSII'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3700_FTECLED_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD8600'	 and PERMFIL_CT= 'EST_FTECLEDSII'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_${NORME}_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD8100'	 and PERMFIL_CT= 'EST_FTECLEDA'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_${NORME}_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD8100'	 and PERMFIL_CT= 'EST_FTECLEDA'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_I4I_POC_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD3850'	 and PERMFIL_CT= 'EPO_FTECLEDACO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD3810'	 and PERMFIL_CT= 'EPO_FTECLEDA'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '$DFILP/${ENV_PREFIX}_ESPD3800_FTECLEDA_I4I_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD3810'	 and PERMFIL_CT= 'EPO_FTECLEDA'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '$DFILP/${ENV_PREFIX}_ESPD3800_FTECLEDA_I4I_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_GAP_MAP_STD'	 and PERMFIL_CT= 'EPO_FTECLEDA'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '$DFILP/${ENV_PREFIX}_ESPD3800_FTECLEDA_I4I_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='I17G_GAP_MAP_STD'	 and PERMFIL_CT= 'EPO_FTECLEDA'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '$DFILP/${ENV_PREFIX}_ESPD3800_FTECLEDA_I4I_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='I17L_GAP_MAP_STD'	 and PERMFIL_CT= 'EPO_FTECLEDA'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '$DFILP/${ENV_PREFIX}_ESPD3800_FTECLEDA_I4I_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='I17P_GAP_MAP_STD'	 and PERMFIL_CT= 'EPO_FTECLEDA'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD3810'	 and PERMFIL_CT= 'EPO_FTECLEDASII'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_EBS_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD3810'	 and PERMFIL_CT= 'EPO_FTECLEDASII'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_I4I_POC_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD3800'	 and PERMFIL_CT= 'EPO_FTECLEDACO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_EBS_POC_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD3800'	 and PERMFIL_CT= 'EPO_FTECLEDACO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_i4I_POC_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD3850'	 and PERMFIL_CT= 'EPO_FTECLEDASIICO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_EBS_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='DWUD0130'	 and PERMFIL_CT= 'EPO_FTECLEDASIISO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_EBS_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='DWUD9130'	 and PERMFIL_CT= 'EPO_FTECLEDASIISO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_EBS_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESPD2900'	 and PERMFIL_CT= 'EPO_FTECLEDASIISO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_EBS_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD8800'	 and PERMFIL_CT= 'EPO_FTECLEDASIISO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_EBS_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD8830'	 and PERMFIL_CT= 'EPO_FTECLEDASIISO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_I4I_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESPD8700'	 and PERMFIL_CT= 'EPO_FTECLEDASO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_I4I_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='DWUD0130'	 and PERMFIL_CT= 'EPO_FTECLEDASO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_I4I_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='DWUD9130'	 and PERMFIL_CT= 'EPO_FTECLEDASO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_I4I_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD8800'	 and PERMFIL_CT= 'EPO_FTECLEDASO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_I4I_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD8830'	 and PERMFIL_CT= 'EPO_FTECLEDASO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_CUR_I4I_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD3800'	 and PERMFIL_CT= 'EPO_FTECLEDASO_CUR'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_CUR_I4I_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESPD8700'	 and PERMFIL_CT= 'EPO_FTECLEDASO_CUR'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_CUR_I4I_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD8830'	 and PERMFIL_CT= 'EPO_FTECLEDASO_CUR'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_MTH_I4I_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD3800'	 and PERMFIL_CT= 'EPO_FTECLEDASO_MTH'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_MTH_I4I_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESPD8700'	 and PERMFIL_CT= 'EPO_FTECLEDASO_MTH'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_MVT_I4I_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD3800'	 and PERMFIL_CT= 'EPO_FTECLEDASO_MVT'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_MVT_I4I_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESPD8700'	 and PERMFIL_CT= 'EPO_FTECLEDASO_MVT'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_MVT_I4I_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD3850'	 and PERMFIL_CT= 'EPO_FTECLEDASO_MVT'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_MVT_I4I_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_MVT_SPL_STD'	 and PERMFIL_CT= 'EPO_FTECLEDASO_MVT'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD8100'	 and PERMFIL_CT= 'EST_FTECLEDR'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD8100'	 and PERMFIL_CT= 'EST_FTECLEDR'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_I4I_POC_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD3850'	 and PERMFIL_CT= 'EPO_FTECLEDRCO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD3810'	 and PERMFIL_CT= 'EPO_FTECLEDR'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_EBS_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD3810'	 and PERMFIL_CT= 'EPO_FTECLEDR'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_GAP_MAP_STD'	 and PERMFIL_CT= 'EPO_FTECLEDR'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD3810'	 and PERMFIL_CT= 'EPO_FTECLEDRSII'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD3810'	 and PERMFIL_CT= 'EPO_FTECLEDRSII'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD3800'	 and PERMFIL_CT= 'EPO_FTECLEDRCO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD3800'	 and PERMFIL_CT= 'EPO_FTECLEDRCO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD3850'	 and PERMFIL_CT= 'EPO_FTECLEDRSIICO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_EBS_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='DWUD0130'	 and PERMFIL_CT= 'EPO_FTECLEDRSIISO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_EBS_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='DWUD9130'	 and PERMFIL_CT= 'EPO_FTECLEDRSIISO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_EBS_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESPD2900'	 and PERMFIL_CT= 'EPO_FTECLEDRSIISO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_EBS_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD8800'	 and PERMFIL_CT= 'EPO_FTECLEDRSIISO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_EBS_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD8830'	 and PERMFIL_CT= 'EPO_FTECLEDRSIISO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_I4I_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD3800'	 and PERMFIL_CT= 'EPO_FTECLEDRSO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_I4I_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='DWUD0130'	 and PERMFIL_CT= 'EPO_FTECLEDRSO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_I4I_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='DWUD9130'	 and PERMFIL_CT= 'EPO_FTECLEDRSO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_I4I_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD8800'	 and PERMFIL_CT= 'EPO_FTECLEDRSO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_I4I_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD8830'	 and PERMFIL_CT= 'EPO_FTECLEDRSO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD4000_DLEIFTECLEDSIIEP_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD4000'	 and PERMFIL_CT= 'EST_DLEIFTECLEDSIIEP'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD4000_DLEIFTECLEDSIIEP_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD4000'	 and PERMFIL_CT= 'EST_DLEIFTECLEDSIIEP'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD4000_DLEIFTECLEDSIIEP_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='I17G_SII_IOR_STD'	 and PERMFIL_CT= 'EST_DLEIFTECLEDSIIEP'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD4000_DLEIFTECLEDSIIEP_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='I17L_SII_IOR_STD'	 and PERMFIL_CT= 'EST_DLEIFTECLEDSIIEP'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD4000_DLEIFTECLEDSIIEP_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='I17P_SII_IOR_STD'	 and PERMFIL_CT= 'EST_DLEIFTECLEDSIIEP'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD4000_DLEIFTECLEDSIIEP_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='I17G_SII_IOR_INI'	 and PERMFIL_CT= 'EST_DLEIFTECLEDSIIEP'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD4000_DLEIFTECLEDSIIEP_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='I17L_SII_IOR_INI'	 and PERMFIL_CT= 'EST_DLEIFTECLEDSIIEP'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD4000_DLEIFTECLEDSIIEP_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='I17P_SII_IOR_INI'	 and PERMFIL_CT= 'EST_DLEIFTECLEDSIIEP'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDA_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='ESPD8700'	 and PERMFIL_CT= 'EPO_FTECLEDA'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD3800'	 and PERMFIL_CT= 'EPO_FTECLEDR'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD8830'	 and PERMFIL_CT= 'EPO_FTECLEDR'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3620_DLEIFTECLEDSIIEI_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD2050'	 and PERMFIL_CT= 'EST_DLEIFTECLEDSIIEI'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3620_DLEIFTECLEDSIIEI_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD3620'	 and PERMFIL_CT= 'EST_DLEIFTECLEDSIIEI'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3700_FTECLED_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD3620'	 and PERMFIL_CT= 'EST_FTECLEDSII'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3700_FTECLED_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESID2210'	 and PERMFIL_CT= 'EST_FTECLEDSII'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '$DFILP/${ENV_PREFIX}_ESPD3800_FTECLEDA_I4I_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='I17G_IEX_ALL_STD'	 and PERMFIL_CT= 'EPO_FTECLEDA'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '$DFILP/${ENV_PREFIX}_ESPD3800_FTECLEDA_I4I_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='I17L_IEX_ALL_STD'	 and PERMFIL_CT= 'EPO_FTECLEDA'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '$DFILP/${ENV_PREFIX}_ESPD3800_FTECLEDA_I4I_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='I17P_IEX_ALL_STD'	 and PERMFIL_CT= 'EPO_FTECLEDA'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_I4I_POC_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESFD2220'	 and PERMFIL_CT= 'EPO_FTECLEDACO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_EBS_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESFD4020'	 and PERMFIL_CT= 'EST_FTECLEDASII'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_EBS_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESID2210'	 and PERMFIL_CT= 'EST_FTECLEDASII'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_EBS_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESID2210'	 and PERMFIL_CT= 'EPO_FTECLEDASIISO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_EBS_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESID2210'	 and PERMFIL_CT= 'EST_FTECLEDASIISO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '$DFILP/${ENV_PREFIX}_ESPD3800_FTECLEDA_I4I_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='I4I_ESPD8830'	 and PERMFIL_CT= 'EPO_FTECLEDASO_EBS'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '$DFILP/${ENV_PREFIX}_ESPD3800_FTECLEDA_I4I_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD8830'	 and PERMFIL_CT= 'EPO_FTECLEDASO_EBS'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '$DFILP/${ENV_PREFIX}_ESPD3800_FTECLEDA_I4I_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD3900'	 and PERMFIL_CT= 'EST_CURGTA'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '$DFILP/${ENV_PREFIX}_ESPD3800_FTECLEDA_I4I_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD3610'	 and PERMFIL_CT= 'EST_CURGTA'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '$DFILP/${ENV_PREFIX}_ESPD3800_FTECLEDA_I4I_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESFD2220'	 and PERMFIL_CT= 'EPO_FTECLEDASO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '$DFILP/${ENV_PREFIX}_ESPD3800_FTECLEDA_I4I_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESFD4020'	 and PERMFIL_CT= 'EST_FTECLEDASO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '$DFILP/${ENV_PREFIX}_ESPD3800_FTECLEDA_I4I_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD8800'	 and PERMFIL_CT= 'EPO_FTECLEDASO_EBS'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '$DFILP/${ENV_PREFIX}_ESPD3800_FTECLEDA_I4I_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESID2210'	 and PERMFIL_CT= 'EST_CURGTA'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '$DFILP/${ENV_PREFIX}_ESPD3800_FTECLEDA_I4I_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESID2210'	 and PERMFIL_CT= 'EST_IGTAAF'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '$DFILP/${ENV_PREFIX}_ESPD3800_FTECLEDA_I4I_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESID2210'	 and PERMFIL_CT= 'EPO_FTECLEDASO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '$DFILP/${ENV_PREFIX}_ESPD3800_FTECLEDA_I4I_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESID2210'	 and PERMFIL_CT= 'EST_FTECLEDASO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_I4I_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD2570'	 and PERMFIL_CT= 'EPO_FTECLEDRSO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDR_I4I_POS_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESID2210'	 and PERMFIL_CT= 'EPO_FTECLEDRSO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD4000_DLEIFTECLEDSIIEP_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD3620'	 and PERMFIL_CT= 'EST_DLEIFTECLEDSIIEP'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD4000_DLEIFTECLEDSIIEP_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESID2210'	 and PERMFIL_CT= 'EST_DLEIFTECLEDSIIEP'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD4000_DLEIFTECLEDSIIEP_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat'		where IDF_CT='EBS_ESPD8830'	 and PERMFIL_CT= 'EPO_DLEIFTECLEDSIIEPSO'
update BEST..TI17PERMFIL  set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_EBS_POC_${PARM_ICLODAT_D}.dat' 		where IDF_CT='EBS_ESPD8100'  and PERMFIL_CT= 'EST_FTECLEDA'

--- Modif TDE
update BEST..TI17PERMFIL set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDA_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat' 	where IDF_CT='ESID3800'  and PERMFIL_CT= 'EST_FTECLEDA'
update BEST..TI17PERMFIL set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDA_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat' 	where IDF_CT='ESPD8100'  and PERMFIL_CT= 'EST_FTECLEDA'
update BEST..TI17PERMFIL set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDA_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat' 	where IDF_CT='I17G_GAP_MAP_STD'  and PERMFIL_CT= 'EST_FTECLEDA'
update BEST..TI17PERMFIL set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDA_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat' 	where IDF_CT='I17L_GAP_MAP_STD'  and PERMFIL_CT= 'EST_FTECLEDA'
update BEST..TI17PERMFIL set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDA_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat' 	where IDF_CT='I17P_GAP_MAP_STD'  and PERMFIL_CT= 'EST_FTECLEDA'

update BEST..TI17PERMFIL set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDA_CUR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat' 	where IDF_CT='ESID3800'  and PERMFIL_CT= 'EST_FTECLEDA_CUR'

update BEST..TI17PERMFIL set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDA_MTH_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat' 	where IDF_CT='ESID3800'  and PERMFIL_CT= 'EST_FTECLEDA_MTH'

update BEST..TI17PERMFIL set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDA_MVT_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat' 	where IDF_CT='ESID3800'  and PERMFIL_CT= 'EST_FTECLEDA_MVT'

update BEST..TI17PERMFIL set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDA_REP_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat' 	where IDF_CT='ESID3800'  and PERMFIL_CT= 'EST_FTECLEDA_REP'

update BEST..TI17PERMFIL set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat' 	where IDF_CT='ESID3800'  and PERMFIL_CT= 'EST_FTECLEDR'
update BEST..TI17PERMFIL set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat' 	where IDF_CT='ESPD8100'  and PERMFIL_CT= 'EST_FTECLEDR'
update BEST..TI17PERMFIL set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat' 	where IDF_CT='I17G_GAP_MAP_STD'  and PERMFIL_CT= 'EST_FTECLEDR'
update BEST..TI17PERMFIL set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat' 	where IDF_CT='I17L_GAP_MAP_STD'  and PERMFIL_CT= 'EST_FTECLEDR'
update BEST..TI17PERMFIL set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat' 	where IDF_CT='I17P_GAP_MAP_STD'  and PERMFIL_CT= 'EST_FTECLEDR'

update BEST..TI17PERMFIL set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDR_MVT_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat' 	where IDF_CT='ESID3800'  and PERMFIL_CT= 'EST_FTECLEDR_MVT'

update BEST..TI17PERMFIL set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3800_FTECLEDR_CUR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat' 	where IDF_CT='ESID3800'  and PERMFIL_CT= 'EST_FTECLEDR_CUR'

update BEST..TI17PERMFIL set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID0060_FDATDERCPA_${TYPEINV}_${PARM_ICLODAT_D}.dat' 	where IDF_CT='ESID2000'  and PERMFIL_CT= 'EST_FDATDERCPA'
update BEST..TI17PERMFIL set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID0060_FDATDERCPA_${TYPEINV}_${PARM_ICLODAT_D}.dat' 	where IDF_CT='ESID0060'  and PERMFIL_CT= 'EST_FDATDERCPA'
update BEST..TI17PERMFIL set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID0060_FDATDERCPA_${TYPEINV}_${PARM_ICLODAT_D}.dat' 	where IDF_CT='ESDJ7010'  and PERMFIL_CT= 'EST_FDATDERCPA'

go 



update BEST..TI17PERMFIL set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3900_FCTRSTAT_${TYPEINV}_${PARM_ICLODAT_D}.dat' 	where IDF_CT='ESID3900'  and PERMFIL_CT= 'EST_FCTRSTAT'
update BEST..TI17PERMFIL set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3900_FCTRSTAT_${TYPEINV}_${PARM_ICLODAT_D}.dat' 	where IDF_CT='ESID8900'  and PERMFIL_CT= 'EST_FCTRSTAT'

update BEST..TI17PERMFIL set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3900_FSEGSTAT${TYPEINV}_${PARM_ICLODAT_D}.dat' 	where IDF_CT='ESID3900'  and PERMFIL_CT= 'EST_FSEGSTAT'
update BEST..TI17PERMFIL set PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESID3900_FSEGSTAT${TYPEINV}_${PARM_ICLODAT_D}.dat' 	where IDF_CT='ESID8900'  and PERMFIL_CT= 'EST_FSEGSTAT'

go 

