use BEST
go


update BEST..TI17PERMFIL set PATHPATTRN_LL='${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat' where IDF_CT = 'EBS_ESPD8200' and PERMFIL_CT='EST_FTECLEDA'

Go