-------------------------------
--mapping of  ESFD2650

	----------   Clean tables   ---------------------

	delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD2650')
	delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD2650')
	delete BEST..TI17FNC where CHAIN_CT='ESFD2650'
	delete BEST..TI17CHN  where CHAIN_CT='ESFD2650'

	insert into BEST..TI17CHN values ('ESFD2650',  'Bouclette Future RetroP AI Generation')

	
	
	----------IDF_CT:   I17G_LCC_RPO_STD_OPT2 ------------------

		insert into BEST..TI17FNC values ('I17G_LCC_RPO_STD_OPT2','Retro LC and AOC component','ESFD2650',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17G_LCC_RPO_STD_OPT2',  'EST_DLVGTR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_LCC_RPO_STD_OPT2',  'EST_DLRPGTR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_LCC_RPO_STD_OPT2',  'EST_DLRTGTR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_LCC_RPO_STD_OPT2',  'EST_DLRNPGTR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_LCC_RPO_STD_OPT2',  'EST_DLRTCGTR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_LCC_RPO_STD_OPT2',  'EST_DLRTFGTR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_LCC_RPO_STD_OPT2',  'EST_DLDSIIGTR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_LCC_RPO_STD_OPT2',  'EST_DLGTRSNEM','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_LCC_RPO_STD_OPT2',  'EST_SUBTRS','${DFILP}/${ENV_PREFIX}_ESCJ0660_SUBTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_LCC_RPO_STD_OPT2',  'EST_FDETTRS','${DFILP}/${ENV_PREFIX}_ESCJ0660_FDETTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_LCC_RPO_STD_OPT2',  'EST_FTRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_LCC_RPO_STD_OPT2',  'EST_FCURCVSN','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURCVSN.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_LCC_RPO_STD_OPT2',  'EST_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_LCC_RPO_STD_OPT2',  'EST_FSSDACTR','${DFILP}/${ENV_PREFIX}_ESCJ0660_FSSDACTR.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_LCC_RPO_STD_OPT2',  'EST_FBOPRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_LCC_RPO_STD_OPT2',  'EST_FCURCVSNI','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURCVSNI.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_LCC_RPO_STD_OPT2',  'EST_FTRANSCODE','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRANSCODE.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_LCC_RPO_STD_OPT2',  'EST_FCES','${DFILP}/${ENV_PREFIX}_ESFD5040_FCES_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_LCC_RPO_STD_OPT2',  'EST_FPLC','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLC_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_LCC_RPO_STD_OPT2',  'ESF_TAXRETMGNT','${DFILP}/${ENV_PREFIX}_ESPD0060_TAXRETMGNT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_LCC_RPO_STD_OPT2',  'EST_GTEP','${DFILP}/${ENV_PREFIX}_ESFD2550_I17G_LCC_RPO_STD_GTEP_${TYPEINV}_${PARM_ICLODAT_D}.dat','U','')
			insert into BEST..TI17PERMFIL values ('I17G_LCC_RPO_STD_OPT2',  'EST_FPLACEMT0','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLACEMT0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_LCC_RPO_STD_OPT2',  'EST_IRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE0_I17G_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_LCC_RPO_STD_OPT2',  'ESF_FLORETFACTOR','${DFILP}/${ENV_PREFIX}_ESPJ0090_FLORETFACTOR_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_LCC_RPO_STD_OPT2',  'EST_IADVPERICASE','${DFILP}/${ENV_PREFIX}_ESPD1800_I17G_AET_RPO_I17_IADPERICASE_I17_MERGE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_LCC_RPO_STD_OPT2',  'EST_IADVPERICASE0','${DFILP}/${ENV_PREFIX}_ESPD1800_I17G_AET_RPO_I17_IADPERICASE_I17_MERGE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_LCC_RPO_STD_OPT2',  'ESF_DLSGTR_AE','${DFILP}/${ENV_PREFIX}_ESPD1800_I17G_AET_RPO_I17_DLSGTRSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_LCC_RPO_STD_OPT2',  'EST_FPLATXCUMALL','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLATXCUMALL0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_LCC_RPO_STD_OPT2',  'ESF_ESFD3890_AOC','${DFILP}/${ENV_PREFIX}_ESFD3890_I17G_GLT_AOC_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_LCC_RPO_STD_OPT2',  'ESF_IRDPERICASE_NP','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE_NP_I17G_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_LCC_RPO_STD_OPT2',  'EST_DLDGTAA','${DFILP}/${ENV_PREFIX}_ESFD2550_I17G_LCC_RPO_STD_DLDGTAA3780_3890SII_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			
			insert into BEST..TI17PERMFIL values ('I17G_LCC_RPO_STD_OPT2',  'ESF_ESFD3740_AICHG_UWI','${DFILP}/${ENV_PREFIX}_ESFD3740_I17G_SII_GLT_STD_AICHG_UWI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_LCC_RPO_STD_OPT2',  'ESF_DLDGTAA3780SII','${DFILP}/${ENV_PREFIX}_ESFD3780_I17G_CSM_ACC_STD_CSM_LC_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_LCC_RPO_STD_OPT2',  'ESF_ESFD3780_CSM_RETRO','${DFILP}/${ENV_PREFIX}_ESFD3780_I17G_CSM_ACC_STD_CSM_LC_FTECLEDR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_LCC_RPO_STD_OPT2',  'EST_DLEIGTAA','${DFILP}/${ENV_PREFIX}_ESFD2650_I17G_LCC_RPO_STD_OPT2_DLEIGTAA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_LCC_RPO_STD_OPT2',  'EST_DLDVGTR','${DFILP}/${ENV_PREFIX}_ESFD2650_I17G_LCC_RPO_STD_OPT2_DLDVGTRSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_LCC_RPO_STD_OPT2',  'EST_DLDVGTR1','${DFILP}/${ENV_PREFIX}_ESFD2650_I17G_LCC_RPO_STD_OPT2_DLDVGTRSII1_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_LCC_RPO_STD_OPT2',  'EST_DLREGTR','${DFILP}/${ENV_PREFIX}_ESFD2650_I17G_LCC_RPO_STD_OPT2_DLREGTRSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_LCC_RPO_STD_OPT2',  'EST_DLRGTAA','${DFILP}/${ENV_PREFIX}_ESFD2650_I17G_LCC_RPO_STD_OPT2_DLRGTAASII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_LCC_RPO_STD_OPT2',  'EST_DLREGTAR','${DFILP}/${ENV_PREFIX}_ESFD2650_I17G_LCC_RPO_STD_OPT2_DLREGTARSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_LCC_RPO_STD_OPT2',  'EST_DLRIGTAA','${DFILP}/${ENV_PREFIX}_ESFD2650_I17G_LCC_RPO_STD_OPT2_DLRIGTAASII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_LCC_RPO_STD_OPT2',  'EST_DLRIGTAANOS','${DFILP}/${ENV_PREFIX}_ESFD2650_I17G_LCC_RPO_STD_OPT2_DLRIGTAANOS${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_LCC_RPO_STD_OPT2',  'EST_DLSGTR','${DFILP}/${ENV_PREFIX}_ESFD2650_I17G_LCC_RPO_STD_OPT2_3740_3780_RETRO_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_LCC_RPO_STD_OPT2',  'EST_DLREMAJGTR','${DFILP}/${ENV_PREFIX}_ESFD2650_I17G_LCC_RPO_STD_OPT2_DLREMAJGTRSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_LCC_RPO_STD_OPT2',  'EST_DLREGTR_OVR','${DFILP}/${ENV_PREFIX}_ESFD2650_I17G_LCC_RPO_STD_OPT2_DLREGTR_OVRSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_LCC_RPO_STD_OPT2',  'EST_DLREMAJGTAR','${DFILP}/${ENV_PREFIX}_ESFD2650_I17G_LCC_RPO_STD_OPT2_DLREMAJGTARSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_LCC_RPO_STD_OPT2',  'EST_DLREGTAR_OVR','${DFILP}/${ENV_PREFIX}_ESFD2650_I17G_LCC_RPO_STD_OPT2_DLREGTAR_OVRSII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_LCC_RPO_STD_OPT2',  'ESF_DLDGTAA3780_3890SII','${DFILP}/${ENV_PREFIX}_ESFD2650_I17G_LCC_RPO_STD_OPT2_DLDGTAA3780_3890SII_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_LCC_RPO_STD_OPT2',  'ESF_DLEILGTAA0','${DFILP}/${ENV_PREFIX}_ESFD2650_I17G_LCC_RPO_STD_OPT2_DLEILGTAA0_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17GMINV',  'I17G_LCC_RPO_STD_OPT2','')
			insert into BEST..TI17REQFNC values ('I17GQINV',  'I17G_LCC_RPO_STD_OPT2','')
			insert into BEST..TI17REQFNC values ('I17GQPOS',  'I17G_LCC_RPO_STD_OPT2','')
			insert into BEST..TI17REQFNC values ('I17GYINV',  'I17G_LCC_RPO_STD_OPT2','')
			insert into BEST..TI17REQFNC values ('I17GYPOS',  'I17G_LCC_RPO_STD_OPT2','')

go	 