-------------------------------
--mapping of  ESFD3660

	----------   Clean tables   ---------------------

	delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD3660')
	delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD3660')
	delete BEST..TI17FNC where CHAIN_CT='ESFD3660'
	delete BEST..TI17CHN  where CHAIN_CT='ESFD3660'

	insert into BEST..TI17CHN values ('ESFD3660',  'Discount forward')
	----------IDF_CT:   EBS_ESFD3660_STD ------------------

		insert into BEST..TI17FNC values ('EBS_ESFD3660_STD','EBS - Discount forward','ESFD3660',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('EBS_ESFD3660_STD',  'EPO_FCURSII','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURSII.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD3660_STD',  'ESF_FPRSMAP_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FPRSMAP_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD3660_STD',  'ESF_TRERETFACCTR','${DFILP}/empty.dat','I','') -- 
			insert into BEST..TI17PERMFIL values ('EBS_ESFD3660_STD',  'ESF_FSEGPATTERNDSCf17','${DFILP}/${ENV_PREFIX}_ESPD0060_FSEGPATTERN_DSC_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','') -- A regerener ESFD1130_FSEGPATTERNDSCf17_I17G
			--insert into BEST..TI17PERMFIL values ('EBS_ESFD3660_STD',  'ESF_FSEGPATTERNDSCf17','${DFILP}/${ENV_PREFIX}_ESFD1130_FSEGPATTERNDSCf17_I17G_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD3660_STD',  'ESF_GTSII_ESCOMPTE','${DFILP}/${ENV_PREFIX}_ESPD3620_GTSII_ESCOMPTE_CLM_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD3660_STD',  'ESF_GTSII_ESCOMPTE_RAD','${DFILP}/empty.dat','I','')
			
			insert into BEST..TI17PERMFIL values ('EBS_ESFD3660_STD',  'ESF_GTSII_ESCOMPTE_PREVCLODAT','${DFILP}/${ENV_PREFIX}_ESPD3700_GTSII_ESCOMPTE_CLM_IFRS17_EBS_POS_${PARM_PREV_ICLODAT_D}.dat','I','')	
			--insert into BEST..TI17PERMFIL values ('EBS_ESFD3660_STD',  'ESF_GTSII_ESCOMPTE_PREVCLODAT','${DFILP}/empty.dat','I','') --
			insert into BEST..TI17PERMFIL values ('EBS_ESFD3660_STD',  'ESF_GTSII_GLOBAL_CASHFLOW_RAD','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD3660_STD',  'ESF_GTSII_ESCOMPTE_RAD_PREVCLODAT','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD3660_STD',  'ESF_GTSII_GLOBAL_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESFD5070_ESPD3610_GTSII_GLOBAL_CASHFLOW_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','') -- MERGE STD BBNI
			insert into BEST..TI17PERMFIL values ('EBS_ESFD3660_STD',  'ESF_GTSII_GLOBAL_CASHFLOW_RAD_PREV','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD3660_STD',  'ESF_GTSII_GLOBAL_CASHFLOW_PREV','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD3660_STD',  'ESF_GTSII_ESCOMPTE_FWD','${DFILP}/${ENV_PREFIX}_ESFD3660_EBS_ESFD3660_STD_GTSII_ESCOMPTE_FWD_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17GMINV',  'EBS_ESFD3660_STD','')
			insert into BEST..TI17REQFNC values ('I17GQINV',  'EBS_ESFD3660_STD','')
			insert into BEST..TI17REQFNC values ('I17GQPOS',  'EBS_ESFD3660_STD','')
			insert into BEST..TI17REQFNC values ('I17GYINV',  'EBS_ESFD3660_STD','')
			insert into BEST..TI17REQFNC values ('I17GYPOS',  'EBS_ESFD3660_STD','')
			
	----------IDF_CT:   EBS_ESFD3660_INI ------------------

		insert into BEST..TI17FNC values ('EBS_ESFD3660_INI','EBS - INI Discount forward','ESFD3660',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('EBS_ESFD3660_INI',  'EPO_FCURSII','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURSII.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD3660_INI',  'ESF_FPRSMAP_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FPRSMAP_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD3660_INI',  'ESF_TRERETFACCTR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD3660_INI',  'ESF_FSEGPATTERNDSCf17','${DFILP}/${ENV_PREFIX}_ESPD0060_FSEGPATTERN_DSC_EBS_POS_${PARM_PREV_ICLODAT_D}.dat','I','')  --Q-1
			--insert into BEST..TI17PERMFIL values ('EBS_ESFD3660_INI',  'ESF_FSEGPATTERNDSCf17','${DFILP}/${ENV_PREFIX}_ESFD1130_FSEGPATTERNDSCf17_I17G_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')			
			insert into BEST..TI17PERMFIL values ('EBS_ESFD3660_INI',  'ESF_GTSII_ESCOMPTE','${DFILP}/${ENV_PREFIX}_ESFD3620_EBS_ESFD3620_INI_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD3660_INI',  'ESF_GTSII_ESCOMPTE_RAD','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD3660_INI',  'ESF_GTSII_ESCOMPTE_PREVCLODAT','${DFILP}/${ENV_PREFIX}_ESPD3700_GTSII_ESCOMPTE_CLM_IFRS17_EBS_POS_${PARM_PREV_ICLODAT_D}.dat','I','') -- STD ESPD3700_GTSII_ESCOMPTE_CLM_IFRS17_EBS

			insert into BEST..TI17PERMFIL values ('EBS_ESFD3660_INI',  'ESF_GTSII_GLOBAL_CASHFLOW_RAD','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD3660_INI',  'ESF_GTSII_ESCOMPTE_RAD_PREVCLODAT','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD3660_INI',  'ESF_GTSII_GLOBAL_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESPD3610_INI_GTSII_GLOBAL_CASHFLOW_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD3660_INI',  'ESF_GTSII_GLOBAL_CASHFLOW_RAD_PREV','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESFD3660_INI',  'ESF_GTSII_GLOBAL_CASHFLOW_PREV','${DFILP}/${ENV_PREFIX}_ESFD5070_ESPD3610_GTSII_GLOBAL_CASHFLOW_EBS_POS_${PARM_PREV_ICLODAT_D}.dat','I','') -- MERGE BBNI Et STD
			insert into BEST..TI17PERMFIL values ('EBS_ESFD3660_INI',  'ESF_GTSII_ESCOMPTE_FWD','${DFILP}/${ENV_PREFIX}_ESFD3660_EBS_ESFD3660_INI_GTSII_ESCOMPTE_FWD_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('EBSEMINV',  'EBS_ESFD3660_INI','POSE')
			insert into BEST..TI17REQFNC values ('EBSEQPOC',  'EBS_ESFD3660_INI','POCE')
			insert into BEST..TI17REQFNC values ('EBSEQPOCB', 'EBS_ESFD3660_INI','BookingPOC')
			insert into BEST..TI17REQFNC values ('EBSEQPOS',  'EBS_ESFD3660_INI','POSE')
			insert into BEST..TI17REQFNC values ('EBSEYPOC',  'EBS_ESFD3660_INI','POCE')
			insert into BEST..TI17REQFNC values ('EBSEYPOCB', 'EBS_ESFD3660_INI','BookingPOC')
			insert into BEST..TI17REQFNC values ('EBSEYPOS',  'EBS_ESFD3660_INI','POSE')
			insert into BEST..TI17REQFNC values ('EBSEQINV',  'EBS_ESFD3660_INI','INVE')
			insert into BEST..TI17REQFNC values ('EBSEYINV',  'EBS_ESFD3660_INI','INVE')

	----------IDF_CT:   I17G_UWD_ALL_STD ------------------

		insert into BEST..TI17FNC values ('I17G_UWD_ALL_STD','Group - Discount forward','ESFD3660',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17G_UWD_ALL_STD',  'EPO_FCURSII','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURSII.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_UWD_ALL_STD',  'ESF_FPRSMAP_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FPRSMAP_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_UWD_ALL_STD',  'ESF_TRERETFACCTR','${DFILP}/${ENV_PREFIX}_ESFD1130_TRERETFACCTR_I17G_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_UWD_ALL_STD',  'ESF_FSEGPATTERNDSCf17','${DFILP}/${ENV_PREFIX}_ESFD1130_FSEGPATTERNDSCf17_I17G_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_UWD_ALL_STD',  'ESF_GTSII_ESCOMPTE','${DFILP}/${ENV_PREFIX}_ESFD3620_I17G_DSC_LKI_INI_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_UWD_ALL_STD',  'ESF_GTSII_ESCOMPTE_RAD','${DFILP}/${ENV_PREFIX}_ESFD3620_I17G_RAD_LKI_INI_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_UWD_ALL_STD',  'ESF_GTSII_ESCOMPTE_PREVCLODAT','${DFILP}/${ENV_PREFIX}_ESFD3620_I17G_DSC_LKI_STD_GTSII_ESCOMPTE_POS_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_UWD_ALL_STD',  'ESF_GTSII_GLOBAL_CASHFLOW_RAD','${DFILP}/${ENV_PREFIX}_ESFD3680_I17G_RAD_GLO_INI_GTSII_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_UWD_ALL_STD',  'ESF_GTSII_ESCOMPTE_RAD_PREVCLODAT','${DFILP}/${ENV_PREFIX}_ESFD3620_I17G_RAD_LKI_STD_GTSII_ESCOMPTE_POS_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_UWD_ALL_STD',  'ESF_GTSII_GLOBAL_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESFD3630_I17G_IEX_ALL_INI_GTSII_GLOBAL_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_UWD_ALL_STD',  'ESF_GTSII_GLOBAL_CASHFLOW_RAD_PREV','${DFILP}/${ENV_PREFIX}_ESFD3680_I17G_RAD_GLO_STD_GTSII_CASHFLOW_POS_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_UWD_ALL_STD',  'ESF_GTSII_GLOBAL_CASHFLOW_PREV','${DFILP}/${ENV_PREFIX}_ESFD3630_I17G_IEX_ALL_STD_GTSII_GLOBAL_CASHFLOW_POS_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_UWD_ALL_STD',  'ESF_GTSII_ESCOMPTE_FWD','${DFILP}/${ENV_PREFIX}_ESFD3660_I17G_UWD_ALL_STD_GTSII_ESCOMPTE_FWD_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17GMINV',  'I17G_UWD_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17GQINV',  'I17G_UWD_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17GQPOS',  'I17G_UWD_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17GYINV',  'I17G_UWD_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17GYPOS',  'I17G_UWD_ALL_STD','')

	----------IDF_CT:   I17L_UWD_ALL_STD ------------------

		insert into BEST..TI17FNC values ('I17L_UWD_ALL_STD','Local - Discount forward','ESFD3660',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17L_UWD_ALL_STD',  'EPO_FCURSII','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURSII.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_UWD_ALL_STD',  'ESF_FPRSMAP_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FPRSMAP_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_UWD_ALL_STD',  'ESF_TRERETFACCTR','${DFILP}/${ENV_PREFIX}_ESFD1130_TRERETFACCTR_I17L_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_UWD_ALL_STD',  'ESF_GTSII_ESCOMPTE','${DFILP}/${ENV_PREFIX}_ESFD3620_I17L_DSC_LKI_INI_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_UWD_ALL_STD',  'ESF_GTSII_ESCOMPTE_RAD','${DFILP}/${ENV_PREFIX}_ESFD3620_I17L_RAD_LKI_INI_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_UWD_ALL_STD',  'ESF_FSEGPATTERNDSCf17','${DFILP}/${ENV_PREFIX}_ESFD1130_FSEGPATTERNDSCf17_I17L_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_UWD_ALL_STD',  'ESF_GTSII_ESCOMPTE_PREVCLODAT','${DFILP}/${ENV_PREFIX}_ESFD3620_I17L_DSC_LKI_STD_GTSII_ESCOMPTE_POS_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_UWD_ALL_STD',  'ESF_GTSII_GLOBAL_CASHFLOW_RAD','${DFILP}/${ENV_PREFIX}_ESFD3680_I17L_RAD_GLO_INI_GTSII_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_UWD_ALL_STD',  'ESF_GTSII_ESCOMPTE_RAD_PREVCLODAT','${DFILP}/${ENV_PREFIX}_ESFD3620_I17L_RAD_LKI_STD_GTSII_ESCOMPTE_POS_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_UWD_ALL_STD',  'ESF_GTSII_GLOBAL_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESFD3630_I17L_IEX_ALL_INI_GTSII_GLOBAL_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_UWD_ALL_STD',  'ESF_GTSII_GLOBAL_CASHFLOW_RAD_PREV','${DFILP}/${ENV_PREFIX}_ESFD3680_I17L_RAD_GLO_STD_GTSII_CASHFLOW_POS_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_UWD_ALL_STD',  'ESF_GTSII_GLOBAL_CASHFLOW_PREV','${DFILP}/${ENV_PREFIX}_ESFD3630_I17L_IEX_ALL_STD_GTSII_GLOBAL_CASHFLOW_POS_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_UWD_ALL_STD',  'ESF_GTSII_ESCOMPTE_FWD','${DFILP}/${ENV_PREFIX}_ESFD3660_I17L_UWD_ALL_STD_GTSII_ESCOMPTE_FWD_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17LMINV',  'I17L_UWD_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17LQINV',  'I17L_UWD_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17LQPOS',  'I17L_UWD_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17LYINV',  'I17L_UWD_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17LYPOS',  'I17L_UWD_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17LYPOSX',  'I17L_UWD_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17LQPOSX',  'I17L_UWD_ALL_STD','')

	----------IDF_CT:   I17P_UWD_ALL_STD ------------------

		insert into BEST..TI17FNC values ('I17P_UWD_ALL_STD','Parent - Discount forward','ESFD3660',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17P_UWD_ALL_STD',  'EPO_FCURSII','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURSII.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_UWD_ALL_STD',  'ESF_FPRSMAP_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FPRSMAP_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_UWD_ALL_STD',  'ESF_TRERETFACCTR','${DFILP}/${ENV_PREFIX}_ESFD1130_TRERETFACCTR_I17P_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_UWD_ALL_STD',  'ESF_GTSII_ESCOMPTE','${DFILP}/${ENV_PREFIX}_ESFD3620_I17P_DSC_LKI_INI_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_UWD_ALL_STD',  'ESF_GTSII_ESCOMPTE_RAD','${DFILP}/${ENV_PREFIX}_ESFD3620_I17P_RAD_LKI_INI_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_UWD_ALL_STD',  'ESF_FSEGPATTERNDSCf17','${DFILP}/${ENV_PREFIX}_ESFD1130_FSEGPATTERNDSCf17_I17P_${TYPEINV}_${PARM_ICLODAT_D}${PARM_POSX}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_UWD_ALL_STD',  'ESF_GTSII_ESCOMPTE_PREVCLODAT','${DFILP}/${ENV_PREFIX}_ESFD3620_I17P_DSC_LKI_STD_GTSII_ESCOMPTE_POS_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_UWD_ALL_STD',  'ESF_GTSII_GLOBAL_CASHFLOW_RAD','${DFILP}/${ENV_PREFIX}_ESFD3680_I17P_RAD_GLO_INI_GTSII_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_UWD_ALL_STD',  'ESF_GTSII_ESCOMPTE_RAD_PREVCLODAT','${DFILP}/${ENV_PREFIX}_ESFD3620_I17P_RAD_LKI_STD_GTSII_ESCOMPTE_POS_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_UWD_ALL_STD',  'ESF_GTSII_GLOBAL_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESFD3630_I17P_IEX_ALL_INI_GTSII_GLOBAL_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_UWD_ALL_STD',  'ESF_GTSII_GLOBAL_CASHFLOW_RAD_PREV','${DFILP}/${ENV_PREFIX}_ESFD3680_I17P_RAD_GLO_STD_GTSII_CASHFLOW_POS_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_UWD_ALL_STD',  'ESF_GTSII_GLOBAL_CASHFLOW_PREV','${DFILP}/${ENV_PREFIX}_ESFD3630_I17P_IEX_ALL_STD_GTSII_GLOBAL_CASHFLOW_POS_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_UWD_ALL_STD',  'ESF_GTSII_ESCOMPTE_FWD','${DFILP}/${ENV_PREFIX}_ESFD3660_I17P_UWD_ALL_STD_GTSII_ESCOMPTE_FWD_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17PYINV',  'I17P_UWD_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17PYPOS',  'I17P_UWD_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17PMINV',  'I17P_UWD_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17PQINV',  'I17P_UWD_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17PQPOS',  'I17P_UWD_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17PYPOSX',  'I17P_UWD_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17PQPOSX',  'I17P_UWD_ALL_STD','')

	----------IDF_CT:   I17S_UWD_ALL_STD ------------------

		insert into BEST..TI17FNC values ('I17S_UWD_ALL_STD','Simulation - Discount forward','ESFD3660',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17S_UWD_ALL_STD',  'EPO_FCURSII','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURSII.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_UWD_ALL_STD',  'ESF_FPRSMAP_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FPRSMAP_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_UWD_ALL_STD',  'ESF_TRERETFACCTR','${DFILP}/${ENV_PREFIX}_ESFD1130_TRERETFACCTR_I17S_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_UWD_ALL_STD',  'ESF_FSEGPATTERNDSCf17','${DFILP}/${ENV_PREFIX}_ESFD1130_FSEGPATTERNDSCf17_I17S_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_UWD_ALL_STD',  'ESF_GTSII_ESCOMPTE','${DFILP}/${ENV_PREFIX}_ESFD3620_I17S_DSC_LKI_INI_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_UWD_ALL_STD',  'ESF_GTSII_ESCOMPTE_RAD','${DFILP}/${ENV_PREFIX}_ESFD3620_I17S_RAD_LKI_INI_GTSII_ESCOMPTE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_UWD_ALL_STD',  'ESF_GTSII_ESCOMPTE_PREVCLODAT','${DFILP}/${ENV_PREFIX}_ESFD3620_I17G_DSC_LKI_STD_GTSII_ESCOMPTE_POS_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_UWD_ALL_STD',  'ESF_GTSII_GLOBAL_CASHFLOW_RAD','${DFILP}/${ENV_PREFIX}_ESFD3680_I17S_RAD_GLO_INI_GTSII_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_UWD_ALL_STD',  'ESF_GTSII_ESCOMPTE_RAD_PREVCLODAT','${DFILP}/${ENV_PREFIX}_ESFD3620_I17S_RAD_LKI_STD_GTSII_ESCOMPTE_POS_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_UWD_ALL_STD',  'ESF_GTSII_GLOBAL_CASHFLOW','${DFILP}/${ENV_PREFIX}_ESFD3630_I17S_IEX_ALL_INI_GTSII_GLOBAL_CASHFLOW_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_UWD_ALL_STD',  'ESF_GTSII_GLOBAL_CASHFLOW_RAD_PREV','${DFILP}/${ENV_PREFIX}_ESFD3680_I17S_RAD_GLO_STD_GTSII_CASHFLOW_POS_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_UWD_ALL_STD',  'ESF_GTSII_GLOBAL_CASHFLOW_PREV','${DFILP}/${ENV_PREFIX}_ESFD3630_I17S_IEX_ALL_STD_GTSII_GLOBAL_CASHFLOW_POS_${PARM_PREV_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_UWD_ALL_STD',  'ESF_GTSII_ESCOMPTE_FWD','${DFILP}/${ENV_PREFIX}_ESFD3660_I17S_UWD_ALL_STD_GTSII_ESCOMPTE_FWD_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17SMINV',  'I17S_UWD_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17SQINV',  'I17S_UWD_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17SQPOS',  'I17S_UWD_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17SYINV',  'I17S_UWD_ALL_STD','')
			insert into BEST..TI17REQFNC values ('I17SYPOS',  'I17S_UWD_ALL_STD','')
go

