-------------------------------
--mapping of  ESPD2570

	----------   Clean tables   ---------------------

	delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESPD2570')
	delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESPD2570')
	delete BEST..TI17FNC where CHAIN_CT='ESPD2570'
	delete BEST..TI17CHN  where CHAIN_CT='ESPD2570'

	insert into BEST..TI17CHN values ('ESPD2570',  'FUTURE FOR RETRO NP CONTRACT')

	----------IDF_CT:   EBS_ESPD2570 ------------------

		insert into BEST..TI17FNC values ('EBS_ESPD2570','IFRS4 Post omega  EBS','ESPD2570',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('EBS_ESPD2570',  'EST_FTRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2570',  'EPO_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2570',  'EPO_FBOPRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2570',  'EPO_FTECLEDRSO','${DFILP}/${ENV_PREFIX}_ESFD4050_FTECLEDR_I4I_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2570',  'EPO_DLSGTRSII_AE','${DFILP}/${ENV_PREFIX}_ESPD1800_DLSGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2570',  'EPO_FPLACEMT22','${DFILP}/${ENV_PREFIX}_ESPD0060_FPLACEMT22_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2570',  'EPO_IRDPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5010_IRDPERICASE0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2570',  'EPO_RETITDPRM_UPR_ACT','${DFILP}/${ENV_PREFIX}_ESPD0060_RETITDPRM_UPR_ACT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2570',  'EPO_DLDGTRCO','${DFILP}/${ENV_PREFIX}_ESPD2570_DLDGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2570',  'EPO_DLDGTRSO','${DFILP}/${ENV_PREFIX}_ESPD2570_DLDGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2570',  'EPO_DLDGTAR_E','${DFILP}/${ENV_PREFIX}_ESPD2570_DLDGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2570',  'EPO_DLDGTR_E','${DFILP}/${ENV_PREFIX}_ESPD2570_DLDGTR_E_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2570',  'EST_RETITDPRM','${DFILP}/${ENV_PREFIX}_ESPD2570_RETITDPRM_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2570',  'EST_RETUPR_ESTIME','${DFILP}/${ENV_PREFIX}_ESPD2570_RETUPR_ESTIME_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2570',  'EPO_FUTURE_RETRO_EBS','${DFILP}/${ENV_PREFIX}_ESPD2570_FUTURE_RETRO_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2570',  'EPO_DLSGTRSII_AE_RETRONP','${DFILP}/${ENV_PREFIX}_ESPD2570_DLSGTRSII_AE_RETRONP_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('EBSEMINV',  'EBS_ESPD2570','')
			insert into BEST..TI17REQFNC values ('EBSEQINV',  'EBS_ESPD2570','')
			insert into BEST..TI17REQFNC values ('EBSEQPOC',  'EBS_ESPD2570','')
			insert into BEST..TI17REQFNC values ('EBSEQPOS',  'EBS_ESPD2570','')
			insert into BEST..TI17REQFNC values ('EBSEYINV',  'EBS_ESPD2570','')
			insert into BEST..TI17REQFNC values ('EBSEYPOC',  'EBS_ESPD2570','')
			insert into BEST..TI17REQFNC values ('EBSEYPOS',  'EBS_ESPD2570','')
			insert into BEST..TI17REQFNC values ('EBSEQPOCB',  'EBS_ESPD2570','')
			insert into BEST..TI17REQFNC values ('EBSEYPOCB',  'EBS_ESPD2570','')


	----------IDF_CT:   EBS_ESPD2570_BBNI ------------------

		insert into BEST..TI17FNC values ('EBS_ESPD2570_BBNI','IFRS4 Post omega  EBS','ESPD2570',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('EBS_ESPD2570_BBNI',  'EST_FTRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2570_BBNI',  'EPO_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2570_BBNI',  'EPO_FBOPRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2570_BBNI',  'EPO_FTECLEDRSO','${DFILP}/empty.dat','I','') 
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2570_BBNI',  'EPO_DLSGTRSII_AE','${DFILP}/${ENV_PREFIX}_ESPD1800_BBNI_DLSGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2570_BBNI',  'EPO_FPLACEMT22','${DFILP}/${ENV_PREFIX}_ESPD0060_FPLACEMT22_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2570_BBNI',  'EPO_IRDPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5060_IRDPERICASE_BBNI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')	
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2570_BBNI',  'EPO_RETITDPRM_UPR_ACT','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2570_BBNI',  'EPO_DLDGTRCO','${DFILP}/${ENV_PREFIX}_ESPD2570_BBNI_DLDGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2570_BBNI',  'EPO_DLDGTRSO','${DFILP}/${ENV_PREFIX}_ESPD2570_BBNI_DLDGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2570_BBNI',  'EPO_DLDGTAR_E','${DFILP}/${ENV_PREFIX}_ESPD2570_BBNI_DLDGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2570_BBNI',  'EPO_DLDGTR_E','${DFILP}/${ENV_PREFIX}_ESPD2570_BBNI_DLDGTR_E_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2570_BBNI',  'EST_RETITDPRM','${DFILP}/${ENV_PREFIX}_ESPD2570_BBNI_RETITDPRM_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2570_BBNI',  'EST_RETUPR_ESTIME','${DFILP}/${ENV_PREFIX}_ESPD2570_BBNI_RETUPR_ESTIME_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2570_BBNI',  'EPO_FUTURE_RETRO_EBS','${DFILP}/${ENV_PREFIX}_ESPD2570_BBNI_FUTURE_RETRO_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2570_BBNI',  'EPO_DLSGTRSII_AE_RETRONP','${DFILP}/${ENV_PREFIX}_ESPD2570_BBNI_DLSGTRSII_AE_RETRONP_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('EBSEMINV',  'EBS_ESPD2570_BBNI','')
			insert into BEST..TI17REQFNC values ('EBSEQINV',  'EBS_ESPD2570_BBNI','')
			insert into BEST..TI17REQFNC values ('EBSEQPOC',  'EBS_ESPD2570_BBNI','')
			insert into BEST..TI17REQFNC values ('EBSEQPOS',  'EBS_ESPD2570_BBNI','')
			insert into BEST..TI17REQFNC values ('EBSEYINV',  'EBS_ESPD2570_BBNI','')
			insert into BEST..TI17REQFNC values ('EBSEYPOC',  'EBS_ESPD2570_BBNI','')
			insert into BEST..TI17REQFNC values ('EBSEYPOS',  'EBS_ESPD2570_BBNI','')
			insert into BEST..TI17REQFNC values ('EBSEQPOCB',  'EBS_ESPD2570_BBNI','')
			insert into BEST..TI17REQFNC values ('EBSEYPOCB',  'EBS_ESPD2570_BBNI','')

----------IDF_CT:   EBS_ESPD2570_INI ------------------

		insert into BEST..TI17FNC values ('EBS_ESPD2570_INI','EBS Post omega  INI','ESPD2570',0)
					
    
		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('EBS_ESPD2570_INI',  'EST_FTRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2570_INI',  'EPO_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2570_INI',  'EPO_FBOPRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2570_INI',  'EPO_FTECLEDRSO','${DFILP}/empty.dat','I','') 
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2570_INI',  'EPO_DLSGTRSII_AE','${DFILP}/${ENV_PREFIX}_ESPD1800_INI_DLSGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2570_INI',  'EPO_FPLACEMT22','${DFILP}/${ENV_PREFIX}_ESPD0060_FPLACEMT22_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2570_INI',  'EPO_IRDPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5060_IRDPERICASE_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')	
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2570_INI',  'EPO_RETITDPRM_UPR_ACT','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2570_INI',  'EPO_DLDGTRCO','${DFILP}/${ENV_PREFIX}_ESPD2570_INI_DLDGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2570_INI',  'EPO_DLDGTRSO','${DFILP}/${ENV_PREFIX}_ESPD2570_INI_DLDGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2570_INI',  'EPO_DLDGTAR_E','${DFILP}/${ENV_PREFIX}_ESPD2570_INI_DLDGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2570_INI',  'EPO_DLDGTR_E','${DFILP}/${ENV_PREFIX}_ESPD2570_INI_DLDGTR_E_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2570_INI',  'EST_RETITDPRM','${DFILP}/${ENV_PREFIX}_ESPD2570_INI_RETITDPRM_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2570_INI',  'EST_RETUPR_ESTIME','${DFILP}/${ENV_PREFIX}_ESPD2570_INI_RETUPR_ESTIME_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2570_INI',  'EPO_FUTURE_RETRO_EBS','${DFILP}/${ENV_PREFIX}_ESPD2570_INI_FUTURE_RETRO_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2570_INI',  'EPO_DLSGTRSII_AE_RETRONP','${DFILP}/${ENV_PREFIX}_ESPD2570_INI_DLSGTRSII_AE_RETRONP_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('EBSEMINV',  'EBS_ESPD2570_INI','')
			insert into BEST..TI17REQFNC values ('EBSEQINV',  'EBS_ESPD2570_INI','')
			insert into BEST..TI17REQFNC values ('EBSEQPOC',  'EBS_ESPD2570_INI','')
			insert into BEST..TI17REQFNC values ('EBSEQPOS',  'EBS_ESPD2570_INI','')
			insert into BEST..TI17REQFNC values ('EBSEYINV',  'EBS_ESPD2570_INI','')
			insert into BEST..TI17REQFNC values ('EBSEYPOC',  'EBS_ESPD2570_INI','')
			insert into BEST..TI17REQFNC values ('EBSEYPOS',  'EBS_ESPD2570_INI','')
			insert into BEST..TI17REQFNC values ('EBSEQPOCB',  'EBS_ESPD2570_INI','')
			insert into BEST..TI17REQFNC values ('EBSEYPOCB',  'EBS_ESPD2570_INI','')



go

