------------------------------


    ----------   Clean tables   ---------------------

    delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESGD2560')
    delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESGD2560')
    delete BEST..TI17FNC where CHAIN_CT='ESGD2560'
    delete BEST..TI17CHN  where CHAIN_CT='ESGD2560'

    insert into BEST..TI17CHN values ('ESGD2560',  '')


	----------IDF_CT:   I4I_EBS_SERQS_MERGE_REFRESH ------------------

		insert into BEST..TI17FNC values ('I4I_EBS_SERQS_MERGE_REFRESH',' ','ESGD2560',0)

		insert into BEST..TI17PERMFIL values ('I4I_EBS_SERQS_MERGE_REFRESH',  'EST_FCURCVSN','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURCVSN.dat','O','')
		insert into BEST..TI17PERMFIL values ('I4I_EBS_SERQS_MERGE_REFRESH',  'EST_FCURCVSN_EBS','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURCVSN.dat','O','')
		insert into BEST..TI17PERMFIL values ('I4I_EBS_SERQS_MERGE_REFRESH',  'EST_FCURQUOT_60','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURQUOT.dat','I','')
	    insert into BEST..TI17PERMFIL values ('I4I_EBS_SERQS_MERGE_REFRESH',  'EST_FSSDACTR_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FSSDACTR_TXT_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
    	--insert into BEST..TI17PERMFIL values ('I4I_EBS_SERQS_MERGE_REFRESH',  'EST_FCES_BBNI','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCESSION0.dat','O','') 
		--insert into BEST..TI17PERMFIL values ('I4I_EBS_SERQS_MERGE_REFRESH',  'EST_FPLACEMT2','${DFILP}/${ENV_PREFIX}_ESCJ0660_FPLACEMT2.dat','O','')

		insert into BEST..TI17PERMFIL values ('I4I_EBS_SERQS_MERGE_REFRESH',  'EST_FGRP','/dev/null','O','')
		insert into BEST..TI17PERMFIL values ('I4I_EBS_SERQS_MERGE_REFRESH',  'EST_SUBTRS','/dev/null','O','')
		insert into BEST..TI17PERMFIL values ('I4I_EBS_SERQS_MERGE_REFRESH',  'EST_FCTRFIC','/dev/null','O','')
		insert into BEST..TI17PERMFIL values ('I4I_EBS_SERQS_MERGE_REFRESH',  'EST_FDETTRS','/dev/null','O','')
		insert into BEST..TI17PERMFIL values ('I4I_EBS_SERQS_MERGE_REFRESH',  'EST_FLIFDRI','/dev/null','O','')
		insert into BEST..TI17PERMFIL values ('I4I_EBS_SERQS_MERGE_REFRESH',  'EST_FLIFTHR','/dev/null','O','')
		insert into BEST..TI17PERMFIL values ('I4I_EBS_SERQS_MERGE_REFRESH',  'EST_FRETTRF','/dev/null','O','')
		insert into BEST..TI17PERMFIL values ('I4I_EBS_SERQS_MERGE_REFRESH',  'EST_FSEGPAR','/dev/null','O','')
		insert into BEST..TI17PERMFIL values ('I4I_EBS_SERQS_MERGE_REFRESH',  'EST_FSUBSID','/dev/null','O','')
		insert into BEST..TI17PERMFIL values ('I4I_EBS_SERQS_MERGE_REFRESH',  'EST_FTRSLNK','/dev/null','O','')
		insert into BEST..TI17PERMFIL values ('I4I_EBS_SERQS_MERGE_REFRESH',  'EST_TACCPAR','/dev/null','O','')
		insert into BEST..TI17PERMFIL values ('I4I_EBS_SERQS_MERGE_REFRESH',  'EST_FACMTRSH','/dev/null','O','')
		insert into BEST..TI17PERMFIL values ('I4I_EBS_SERQS_MERGE_REFRESH',  'EST_FBANTECL','/dev/null','O','')
		insert into BEST..TI17PERMFIL values ('I4I_EBS_SERQS_MERGE_REFRESH',  'EST_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT.dat','O','')
		insert into BEST..TI17PERMFIL values ('I4I_EBS_SERQS_MERGE_REFRESH',  'EST_FSEGMENT','/dev/null','O','')
		insert into BEST..TI17PERMFIL values ('I4I_EBS_SERQS_MERGE_REFRESH',  'EST_FSOBBLOB','/dev/null','O','')
		insert into BEST..TI17PERMFIL values ('I4I_EBS_SERQS_MERGE_REFRESH',  'EST_FCURCVSNI','/dev/null','O','')
		insert into BEST..TI17PERMFIL values ('I4I_EBS_SERQS_MERGE_REFRESH',  'EST_FTRANSCODE','/dev/null','O','')
		insert into BEST..TI17PERMFIL values ('I4I_EBS_SERQS_MERGE_REFRESH',  'EST_SUBTRSASSO','/dev/null','O','')
		insert into BEST..TI17PERMFIL values ('I4I_EBS_SERQS_MERGE_REFRESH',  'EST_SUBTRSBASE','/dev/null','O','')
		insert into BEST..TI17PERMFIL values ('I4I_EBS_SERQS_MERGE_REFRESH',  'EST_FLIFDRI_ALL','/dev/null','O','')
		insert into BEST..TI17PERMFIL values ('I4I_EBS_SERQS_MERGE_REFRESH',  'EST_FTRSLNKVRET','/dev/null','O','')
		insert into BEST..TI17PERMFIL values ('I4I_EBS_SERQS_MERGE_REFRESH',  'EST_FLIFDRIQ_ALL','/dev/null','O','')
		insert into BEST..TI17PERMFIL values ('I4I_EBS_SERQS_MERGE_REFRESH',  'EST_FLIFDRIY_ALL','/dev/null','O','')
		insert into BEST..TI17PERMFIL values ('I4I_EBS_SERQS_MERGE_REFRESH',  'EST_SUBTRSESBPROP','/dev/null','O','')
		insert into BEST..TI17PERMFIL values ('I4I_EBS_SERQS_MERGE_REFRESH',  'EST_FTRANSCODEVRET','/dev/null','O','')
		insert into BEST..TI17PERMFIL values ('I4I_EBS_SERQS_MERGE_REFRESH',  'EST_SUBTRSBLOCKLIFEST','/dev/null','O','')


		----------   Reqs    ---------------------
		insert into BEST..TI17REQFNC values ('ALL',  'I4I_EBS_SERQS_MERGE_REFRESH','')

go

--mapping of  ESGD2560 <==ESID2550

	----------IDF_CT:   I4I_SERQS_MERGE_REFRESH ------------------

		insert into BEST..TI17FNC values ('I4I_SERQS_MERGE_REFRESH',' ','ESGD2560',0)

		
		insert into BEST..TI17PERMFIL values ('I4I_SERQS_MERGE_REFRESH',  'EST_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURQUOT.dat','I','')
		insert into BEST..TI17PERMFIL values ('I4I_SERQS_MERGE_REFRESH',  'EST_IADPERIFCT0','${DFILP}/${ENV_PREFIX}_ESEH1100_IADPERIFCT0_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
		insert into BEST..TI17PERMFIL values ('I4I_SERQS_MERGE_REFRESH',  'EST_IADPERICASE0','${DFILP}/${ENV_PREFIX}_ESEH1100_IADPERICASE0_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
		insert into BEST..TI17PERMFIL values ('I4I_SERQS_MERGE_REFRESH',  'EST_IAVPERICASE0','${DFILP}/${ENV_PREFIX}_ESEH1100_IAVPERICASE0_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
		insert into BEST..TI17PERMFIL values ('I4I_SERQS_MERGE_REFRESH',  'EST_IADPERICASE_ENTIER0','${DFILP}/${ENV_PREFIX}_ESEH1100_IADPERICASE_ENTIER0_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

	

        insert into BEST..TI17REQFNC values ('A'      ,  'I4I_SERQS_MERGE_REFRESH','')
        insert into BEST..TI17REQFNC values ('I4IMINVB',  'I4I_SERQS_MERGE_REFRESH','@variante')
        insert into BEST..TI17REQFNC values ('I4IMINV',  'I4I_SERQS_MERGE_REFRESH','')
        insert into BEST..TI17REQFNC values ('I4IQINV',  'I4I_SERQS_MERGE_REFRESH','@variante')
        insert into BEST..TI17REQFNC values ('I4IYINV',  'I4I_SERQS_MERGE_REFRESH','@variante')   
go
-------------------------------
--mapping of  ESGD2560 <==ESPD2550

	----------IDF_CT:   EBS_SERQS_MERGE_REFRESH ------------------

		insert into BEST..TI17FNC values ('EBS_SERQS_MERGE_REFRESH','EBS Post omega NDIC','ESGD2560',0)
	
		----------  Perms---------------------  

	
    	insert into BEST..TI17PERMFIL values ('EBS_SERQS_MERGE_REFRESH',  'EST_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT.dat','I','')

		insert into BEST..TI17PERMFIL values ('EBS_SERQS_MERGE_REFRESH',  'EST_IADVPERICASE0','${DFILP}/${ENV_PREFIX}_ESID1000_IADVPERICASE0_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
        insert into BEST..TI17PERMFIL values ('EBS_SERQS_MERGE_REFRESH',  'EST_IADVPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_IADVPERICASE_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
        insert into BEST..TI17PERMFIL values ('EBS_SERQS_MERGE_REFRESH',  'EST_IRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_IRDVPERICASE_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
        insert into BEST..TI17PERMFIL values ('EBS_SERQS_MERGE_REFRESH',  'EST_FCES','${DFILP}/${ENV_PREFIX}_ESID2500_FCES_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
        insert into BEST..TI17PERMFIL values ('EBS_SERQS_MERGE_REFRESH',  'EST_FPLC','${DFILP}/${ENV_PREFIX}_ESID2500_FPLC_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
        insert into BEST..TI17PERMFIL values ('EBS_SERQS_MERGE_REFRESH',  'EST_IADPERICASE_DUMMY','/dev/null','O','')
        
		insert into BEST..TI17PERMFIL values ('EBS_SERQS_MERGE_REFRESH',  'EST_IADPERIFCT0','${DFILP}/${ENV_PREFIX}_ESCJ0660_IADPERIFCT0.dat','O','')
		insert into BEST..TI17PERMFIL values ('EBS_SERQS_MERGE_REFRESH',  'EST_IADPERICASE0','${DFILP}/${ENV_PREFIX}_ESCJ0660_IADPERICASE0.dat','O','')
		insert into BEST..TI17PERMFIL values ('EBS_SERQS_MERGE_REFRESH',  'EST_IAVPERICASE0','${DFILP}/${ENV_PREFIX}_ESCJ0660_IAVPERICASE0.dat','O','')	
		insert into BEST..TI17PERMFIL values ('EBS_SERQS_MERGE_REFRESH',  'EST_IADPERICASE_ENTIER0','${DFILP}/${ENV_PREFIX}_ESCJ0660_IADPERICASE_ENTIER0.dat','O','')
                       
	
        insert into BEST..TI17PERMFIL values ('EBS_SERQS_MERGE_REFRESH',  'EST_FCESSION0','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCESSION0.dat','O','')
 		insert into BEST..TI17PERMFIL values ('EBS_SERQS_MERGE_REFRESH',  'EST_FPLACEMT0','${DFILP}/${ENV_PREFIX}_ESCJ0660_FPLACEMT0.dat','O','')
		insert into BEST..TI17PERMFIL values ('EBS_SERQS_MERGE_REFRESH',  'ESF_TAXRETMGNT','${DFILP}/${ENV_PREFIX}_ESPD0060_TAXRETMGNT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
	
	

		----------   Reqs    ---------------------

	    insert into BEST..TI17REQFNC values ('EBSEYPOC',  'EBS_SERQS_MERGE_REFRESH','')
		insert into BEST..TI17REQFNC values ('EBSEQPOC',  'EBS_SERQS_MERGE_REFRESH','')
		insert into BEST..TI17REQFNC values ('EBSEMINV',  'EBS_SERQS_MERGE_REFRESH','')
		insert into BEST..TI17REQFNC values ('EBSEMINVB', 'EBS_SERQS_MERGE_REFRESH','')
		insert into BEST..TI17REQFNC values ('EBSEQINV',  'EBS_SERQS_MERGE_REFRESH','')
		insert into BEST..TI17REQFNC values ('EBSEQPOCB', 'EBS_SERQS_MERGE_REFRESH','')
		insert into BEST..TI17REQFNC values ('EBSEQPOS',  'EBS_SERQS_MERGE_REFRESH','')
		insert into BEST..TI17REQFNC values ('EBSEYINV',  'EBS_SERQS_MERGE_REFRESH','')
		insert into BEST..TI17REQFNC values ('EBSEYPOCB', 'EBS_SERQS_MERGE_REFRESH','')
		insert into BEST..TI17REQFNC values ('EBSEYPOS',  'EBS_SERQS_MERGE_REFRESH','')
	

go






-------------------------------
--mapping of  ESGD2560 <==ESFD2550

	
	----------IDF_CT:   I17G_SERQS_MERGE_REFRESH ------------------

		insert into BEST..TI17FNC values ('I17G_SERQS_MERGE_REFRESH','Bouclette Future RetroP Inception','ESGD2560',0)
					
		
		----------  Perms---------------------





	
			
--			insert into BEST..TI17PERMFIL values ('I17G_SERQS_MERGE_REFRESH',  'ESF_ILL_BUCKET','${DFILP}/${ENV_PREFIX}_ESFD2050_ILL_BUCKET_I17G.dat','O','')
		
		

		----------   Reqs    ---------------------

            insert into BEST..TI17REQFNC values ('EBSEYPOC',  'I17G_SERQS_MERGE_REFRESH','')
        	insert into BEST..TI17REQFNC values ('EBSEQPOC',  'I17G_SERQS_MERGE_REFRESH','')
        	insert into BEST..TI17REQFNC values ('EBSEMINV',  'I17G_SERQS_MERGE_REFRESH','')
        	insert into BEST..TI17REQFNC values ('EBSEMINVB', 'I17G_SERQS_MERGE_REFRESH','')
        	insert into BEST..TI17REQFNC values ('EBSEQINV',  'I17G_SERQS_MERGE_REFRESH','')
        	insert into BEST..TI17REQFNC values ('EBSEQPOCB', 'I17G_SERQS_MERGE_REFRESH','')
        	insert into BEST..TI17REQFNC values ('EBSEQPOS',  'I17G_SERQS_MERGE_REFRESH','')
        	insert into BEST..TI17REQFNC values ('EBSEYINV',  'I17G_SERQS_MERGE_REFRESH','')
        	insert into BEST..TI17REQFNC values ('EBSEYPOCB', 'I17G_SERQS_MERGE_REFRESH','')
        	insert into BEST..TI17REQFNC values ('EBSEYPOS',  'I17G_SERQS_MERGE_REFRESH','')
go
-------------------------------
--mapping of  ESGD2560 <==ESFD2550

	
	----------IDF_CT:   I17L_SERQS_MERGE ------------------

		insert into BEST..TI17FNC values ('I17L_SERQS_MERGE_REFRESH','Bouclette Future RetroP Inception','ESGD2560',0)
					
		
		----------  Perms---------------------




			insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE_REFRESH',  'ESF_FI17CLOPER','${DFILP}/${ENV_PREFIX}_ESFD1130_FI17CLOPER_I17L_DSC_ALL_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

	
			insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE_REFRESH',  'EST_FCES','${DFILP}/${ENV_PREFIX}_ESFD5040_I17L_MRG_FUT_INI_FCES_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE_REFRESH',  'EST_FPLC','${DFILP}/${ENV_PREFIX}_ESFD5010_I17L_MRG_PER_INI_FPLC_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE_REFRESH',  'EST_FPLACEMT0','${DFILP}/${ENV_PREFIX}_ESFD5010_I17L_MRG_PER_INI_FPLACEMT0_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE_REFRESH',  'EST_IADVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17L_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE_REFRESH',  'EST_IRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE_I17L_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE_REFRESH',  'EST_FCTRGRO','${DFILP}/${ENV_PREFIX}_ESFD5010_I17L_MRG_PER_INI_FCTRGRO_${PARM_TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
            insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE_REFRESH',  'EST_FPLATXCUM','${DFILP}/${ENV_PREFIX}_ESFD5010_I17L_MRG_PER_INI_FPLATXCUM_${PARM_TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE_REFRESH',  'EST_FPLATXCUMALL','${DFILP}/${ENV_PREFIX}_ESFD5010_I17L_MRG_PER_INI_FPLATXCUMALL_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE_REFRESH',  'ESF_FLORETFACTOR','${DFILP}/${ENV_PREFIX}_ESPJ0090_I17L_AEE_RPO_I17_FLORETFACTOR_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE_REFRESH',  'EST_IRDPERICASE0_I17','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE0_I17L_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE_REFRESH',  'ESF_ILL_BUCKET','${DFILP}/${ENV_PREFIX}_ESFD2050_ILL_BUCKET_I17L.dat','O','')
	
			insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE_REFRESH',  'ESF_TRERETFACCTR','${DFILP}/${ENV_PREFIX}_ESFD1130_TRERETFACCTR_I17L_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE_REFRESH',  'ESF_SECIFRS_CR_EXTRACT','${DFILP}/${ENV_PREFIX}_ESFD1130_SECIFRS_CR_EXTRACT_I17L_DSC_ALL_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
	
		----------   Reqs    ---------------------

            insert into BEST..TI17REQFNC values ('EBSEYPOC',  'I17L_SERQS_MERGE_REFRESH','')
        	insert into BEST..TI17REQFNC values ('EBSEQPOC',  'I17L_SERQS_MERGE_REFRESH','')
        	insert into BEST..TI17REQFNC values ('EBSEMINV',  'I17L_SERQS_MERGE_REFRESH','')
        	insert into BEST..TI17REQFNC values ('EBSEMINVB', 'I17L_SERQS_MERGE_REFRESH','')
        	insert into BEST..TI17REQFNC values ('EBSEQINV',  'I17L_SERQS_MERGE_REFRESH','')
        	insert into BEST..TI17REQFNC values ('EBSEQPOCB', 'I17L_SERQS_MERGE_REFRESH','')
        	insert into BEST..TI17REQFNC values ('EBSEQPOS',  'I17L_SERQS_MERGE_REFRESH','')
        	insert into BEST..TI17REQFNC values ('EBSEYINV',  'I17L_SERQS_MERGE_REFRESH','')
        	insert into BEST..TI17REQFNC values ('EBSEYPOCB', 'I17L_SERQS_MERGE_REFRESH','')
        	insert into BEST..TI17REQFNC values ('EBSEYPOS',  'I17L_SERQS_MERGE_REFRESH','')
go

--mapping of  ESGD2560 <==ESFD2550

	
	----------IDF_CT:   I17P_SERQS_MERGE_REFRESH_REFRESH ------------------

		insert into BEST..TI17FNC values ('I17P_SERQS_MERGE_REFRESH','Bouclette Future RetroP Inception','ESGD2560',0)
					
		
		----------  Perms---------------------




			insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE_REFRESH',  'ESF_FI17CLOPER','${DFILP}/${ENV_PREFIX}_ESFD1130_FI17CLOPER_I17P_DSC_ALL_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

	
			insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE_REFRESH',  'EST_FCES','${DFILP}/${ENV_PREFIX}_ESFD5040_I17P_MRG_FUT_INI_FCES_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE_REFRESH',  'EST_FPLC','${DFILP}/${ENV_PREFIX}_ESFD5010_I17P_MRG_PER_INI_FPLC_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE_REFRESH',  'EST_FPLACEMT0','${DFILP}/${ENV_PREFIX}_ESFD5010_I17P_MRG_PER_INI_FPLACEMT0_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE_REFRESH',  'EST_IADVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17P_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE_REFRESH',  'EST_IRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE_I17P_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE_REFRESH',  'EST_FCTRGRO','${DFILP}/${ENV_PREFIX}_ESFD5010_I17P_MRG_PER_INI_FCTRGRO_${PARM_TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
            insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE_REFRESH',  'EST_FPLATXCUM','${DFILP}/${ENV_PREFIX}_ESFD5010_I17P_MRG_PER_INI_FPLATXCUM_${PARM_TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE_REFRESH',  'EST_FPLATXCUMALL','${DFILP}/${ENV_PREFIX}_ESFD5010_I17P_MRG_PER_INI_FPLATXCUMALL_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE_REFRESH',  'ESF_FLORETFACTOR','${DFILP}/${ENV_PREFIX}_ESPJ0090_I17P_AEE_RPO_I17_FLORETFACTOR_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE_REFRESH',  'EST_IRDPERICASE0_I17','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE0_I17P_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE_REFRESH',  'ESF_ILL_BUCKET','${DFILP}/${ENV_PREFIX}_ESFD2050_ILL_BUCKET_I17P.dat','O','')

			insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE_REFRESH',  'ESF_TRERETFACCTR','${DFILP}/${ENV_PREFIX}_ESFD1130_TRERETFACCTR_I17P_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE_REFRESH',  'ESF_SECIFRS_CR_EXTRACT','${DFILP}/${ENV_PREFIX}_ESFD1130_SECIFRS_CR_EXTRACT_I17P_DSC_ALL_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
	
		----------   Reqs    ---------------------

	        insert into BEST..TI17REQFNC values ('EBSEYPOC',  'I17P_SERQS_MERGE_REFRESH','')
        	insert into BEST..TI17REQFNC values ('EBSEQPOC',  'I17P_SERQS_MERGE_REFRESH','')
        	insert into BEST..TI17REQFNC values ('EBSEMINV',  'I17P_SERQS_MERGE_REFRESH','')
        	insert into BEST..TI17REQFNC values ('EBSEMINVB', 'I17P_SERQS_MERGE_REFRESH','')
        	insert into BEST..TI17REQFNC values ('EBSEQINV',  'I17P_SERQS_MERGE_REFRESH','')
        	insert into BEST..TI17REQFNC values ('EBSEQPOCB', 'I17P_SERQS_MERGE_REFRESH','')
        	insert into BEST..TI17REQFNC values ('EBSEQPOS',  'I17P_SERQS_MERGE_REFRESH','')
        	insert into BEST..TI17REQFNC values ('EBSEYINV',  'I17P_SERQS_MERGE_REFRESH','')
        	insert into BEST..TI17REQFNC values ('EBSEYPOCB', 'I17P_SERQS_MERGE_REFRESH','')
        	insert into BEST..TI17REQFNC values ('EBSEYPOS',  'I17P_SERQS_MERGE_REFRESH','')

go   