-------------------------------
--mapping of  ESID2040

	----------   Clean tables   ---------------------

	delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESID2040')
	delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESID2040')
	delete BEST..TI17FNC where CHAIN_CT='ESID2040'
	delete BEST..TI17CHN  where CHAIN_CT='ESID2040'

	insert into BEST..TI17CHN values ('ESID2040',  '')

	----------IDF_CT:   ESID2040 ------------------

		insert into BEST..TI17FNC values ('ESID2040',' ','ESID2040',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('ESID2040',  'EST_SUBTRS','${DFILP}/${ENV_PREFIX}_ESCJ0060_FSUBTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2040',  'EST_FTRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2040',  'EST_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2040',  'EST_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2040',  'EST_FCPLACC','${DFILP}/${ENV_PREFIX}_ESID0560_FCPLACC_INV_${PARM_ICLODAT2_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2040',  'EST_FGRP','${DFILP}/${ENV_PREFIX}_ESCJ0060_FGRP_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2040',  'EST_FSUBSID','${DFILP}/${ENV_PREFIX}_ESCJ0060_FSUBSID_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2040',  'EST_SRGTC','${DFILP}/${ENV_PREFIX}_ESID2030_SRGTC${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2040',  'EST_FACCPAR0','${DFILP}/${ENV_PREFIX}_ESID0060_FACCPAR0_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2040',  'EST_FACMTRSH','${DFILP}/${ENV_PREFIX}_ESCJ0060_FACMTRSH_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2040',  'EST_FBANTECL','${DFILP}/${ENV_PREFIX}_ESCJ0060_FBANTECL_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2040',  'EST_SEGRATANO','${DFILP}/${ENV_PREFIX}_ESID2070_SEGRATANO_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2040',  'EST_CPLIFDRI','${DFILP}/${ENV_PREFIX}_ESID2030_CPLIFDRI${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2040',  'EST_SUBTRSASSO','${DFILP}/${ENV_PREFIX}_ESCJ0060_FSUBTRSASSO_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2040',  'EST_CRIBLEANO','${DFILP}/${ENV_PREFIX}_ESID2070_CRIBLEANO${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2040',  'EST_FVPLACEMT','${DFILP}/${ENV_PREFIX}_ESID2070_FVPLACEMT${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2040',  'EST_IAVPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_IAVPERICASE_${TYPEINV}_${PARM_ICLODAT2_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2040',  'EST_IRVPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_IRVPERICASE_${TYPEINV}_${PARM_ICLODAT2_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2040',  'EST_VLIFEST195','${DFILP}/${ENV_PREFIX}_ESID2030_VLIFEST195${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2040',  'EST_LIFESTNOACC','${DFILP}/${ENV_PREFIX}_ESID2070_LIFESTNOACC${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2040',  'EST_SUBTRSESBPROP','${DFILP}/${ENV_PREFIX}_ESCJ0060_FSUBTRSESBPROP_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2040',  'EST_IARVPERICASE0','${DFILP}/${ENV_PREFIX}_ESID2070_IARVPERICASE0${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2040',  'EST_IARVPERICASE4','${DFILP}/${ENV_PREFIX}_ESID2070_IARVPERICASE4${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID2040',  'EST_SRGTE_PA','${DFILP}/${ENV_PREFIX}_ESID2040_SRGTE_PA${IT}_${BALSHTYEA}1231.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2040',  'EST_DLVGTR_PA','${DFILP}/${ENV_PREFIX}_ESID2040_DLVGTR_PA${IT}_${BALSHTYEA}1231.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2040',  'EST_SRGTEF_PA','${DFILP}/${ENV_PREFIX}_ESID2040_SRGTEF_PA${IT}_${BALSHTYEA}1231.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2040',  'EST_CMPCALC_PA','${DFILP}/${ENV_PREFIX}_ESID2040_CMPCALC_PA${IT}_${BALSHTYEA}1231.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2040',  'EST_DLVGTAA_PA','${DFILP}/${ENV_PREFIX}_ESID2040_DLVGTAA_PA${IT}_${BALSHTYEA}1231.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2040',  'EST_DLVGTAR_PA','${DFILP}/${ENV_PREFIX}_ESID2040_DLVGTAR_PA${IT}_${BALSHTYEA}1231.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2040',  'EST_SRGTE_SRV_PA','${DFILP}/${ENV_PREFIX}_ESID2040_SRGTE_SRV_PA${IT}_${BALSHTYEA}1231.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2040',  'EST_SRGTEF_SRV_PA','${DFILP}/${ENV_PREFIX}_ESID2040_SRGTEF_SRV_PA${IT}_${BALSHTYEA}1231.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2040',  'EST_SIGNANO','${DFILP}/${ENV_PREFIX}_ESID2040_SIGNANO${IT}_${TYPEINV}_${PARM_ICLODAT2_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2040',  'EST_SRGTE_PC','${DFILP}/${ENV_PREFIX}_ESID2040_SRGTE_PC${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2040',  'EST_DLVGTAR_PC','${DFILP}/${ENV_PREFIX}_ESID2040_DLVGTAR_PC${IT}_${PARM_ICLODAT_D}_${CRE_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2040',  'EST_SRGTEF_PC','${DFILP}/${ENV_PREFIX}_ESID2040_SRGTEF_PC${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2040',  'EST_DLVGTAA_PC','${DFILP}/${ENV_PREFIX}_ESID2040_DLVGTAA_PC${IT}_${PARM_ICLODAT2_D}_${CRE_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2040',  'EST_DLVGTR_PC','${DFILP}/${ENV_PREFIX}_ESID2040_DLVGTR_PC${IT}_${TYPEINV}_${PARM_ICLODAT2_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2040',  'EST_CMPCALC_PC','${DFILP}/${ENV_PREFIX}_ESID2040_CMPCALC_PC${IT}_${TYPEINV}_${PARM_ICLODAT2_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2040',  'EST_SRGTE_SRV_PC','${DFILP}/${ENV_PREFIX}_ESID2040_SRGTE_SRV_PC${IT}_${TYPEINV}_${PARM_ICLODAT2_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2040',  'EST_SRGTR_VENTIL','${DFILP}/${ENV_PREFIX}_ESID2040_SRGTR_VENTIL${IT}_${TYPEINV}_${PARM_ICLODAT2_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID2040',  'EST_SRGTEF_SRV_PC','${DFILP}/${ENV_PREFIX}_ESID2040_SRGTEF_SRV_PC${IT}_${TYPEINV}_${PARM_ICLODAT2_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('A',  'ESID2040','')
			insert into BEST..TI17REQFNC values ('I4IMINV',  'ESID2040','')
			insert into BEST..TI17REQFNC values ('I4IQINV',  'ESID2040','@variante')
			insert into BEST..TI17REQFNC values ('I4IYINV',  'ESID2040','@variante')

	----------IDF_CT:   I4I_Q_CMP_LIF ------------------

		insert into BEST..TI17FNC values ('I4I_Q_CMP_LIF',' ','ESID2040',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I4I_Q_CMP_LIF',  'EST_SUBTRS','${DFILP}/${ENV_PREFIX}_ESCJ0060_FSUBTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_CMP_LIF',  'EST_FTRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_CMP_LIF',  'EST_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_CMP_LIF',  'EST_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_CMP_LIF',  'EST_FCPLACC','${DFILP}/${ENV_PREFIX}_ESID0560_FCPLACC_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_CMP_LIF',  'EST_FGRP','${DFILP}/${ENV_PREFIX}_ESCJ0060_FGRP_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_CMP_LIF',  'EST_FSUBSID','${DFILP}/${ENV_PREFIX}_ESCJ0060_FSUBSID_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_CMP_LIF',  'EST_SRGTC','${DFILP}/${ENV_PREFIX}_ESID2030_SRGTC${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_CMP_LIF',  'EST_FACCPAR0','${DFILP}/${ENV_PREFIX}_ESID0060_FACCPAR0_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_CMP_LIF',  'EST_FACMTRSH','${DFILP}/${ENV_PREFIX}_ESCJ0060_FACMTRSH_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_CMP_LIF',  'EST_FBANTECL','${DFILP}/${ENV_PREFIX}_ESCJ0060_FBANTECL_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_CMP_LIF',  'EST_SEGRATANO','${DFILP}/${ENV_PREFIX}_ESID2070_SEGRATANO_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_CMP_LIF',  'EST_CPLIFDRI','${DFILP}/${ENV_PREFIX}_ESID2030_CPLIFDRI${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_CMP_LIF',  'EST_SUBTRSASSO','${DFILP}/${ENV_PREFIX}_ESCJ0060_FSUBTRSASSO_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_CMP_LIF',  'EST_IAVPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_IAVPERICASE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_CMP_LIF',  'EST_IRVPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_IRVPERICASE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_CMP_LIF',  'EST_CRIBLEANO','${DFILP}/${ENV_PREFIX}_ESID2070_CRIBLEANO${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_CMP_LIF',  'EST_FVPLACEMT','${DFILP}/${ENV_PREFIX}_ESID2070_FVPLACEMT${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_CMP_LIF',  'EST_VLIFEST195','${DFILP}/${ENV_PREFIX}_ESID2030_VLIFEST195${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_CMP_LIF',  'EST_LIFESTNOACC','${DFILP}/${ENV_PREFIX}_ESID2070_LIFESTNOACC${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_CMP_LIF',  'EST_SUBTRSESBPROP','${DFILP}/${ENV_PREFIX}_ESCJ0060_FSUBTRSESBPROP_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_CMP_LIF',  'EST_SUBTRSBLOCKLIFEST','${DFILP}/${ENV_PREFIX}_ESCJ0060_FSUBTRSBLOCKLIFEST_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_CMP_LIF',  'EST_IARVPERICASE0','${DFILP}/${ENV_PREFIX}_ESID2070_IARVPERICASE0${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_CMP_LIF',  'EST_IARVPERICASE4','${DFILP}/${ENV_PREFIX}_ESID2070_IARVPERICASE4${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_CMP_LIF',  'EST_SRGTE_PC','${DFILP}/${ENV_PREFIX}_ESID2040_SRGTE_PC${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_CMP_LIF',  'EST_DLVGTR_PC','${DFILP}/${ENV_PREFIX}_ESID2040_DLVGTR_PC${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_CMP_LIF',  'EST_SRGTEF_PC','${DFILP}/${ENV_PREFIX}_ESID2040_SRGTEF_PC${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_CMP_LIF',  'EST_CMPCALC_PC','${DFILP}/${ENV_PREFIX}_ESID2040_CMPCALC_PC${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_CMP_LIF',  'EST_DLVGTAA_PC','${DFILP}/${ENV_PREFIX}_ESID2040_DLVGTAA_PC${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_CMP_LIF',  'EST_DLVGTAR_PC','${DFILP}/${ENV_PREFIX}_ESID2040_DLVGTAR_PC${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_CMP_LIF',  'EST_SIGNANO_PC','${DFILP}/${ENV_PREFIX}_ESID2040_SIGNANO_PC${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_CMP_LIF',  'EST_SRGTE_PA','${DFILP}/${ENV_PREFIX}_ESID2040_SRGTE_PA${IT}_${TYPEINV}_${PARM_BALSHTYEA_NF}1231.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_CMP_LIF',  'EST_SRGTE_SRV_PC','${DFILP}/${ENV_PREFIX}_ESID2040_SRGTE_SRV_PC${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_CMP_LIF',  'EST_SRGTR_VENTIL','${DFILP}/${ENV_PREFIX}_ESID2040_SRGTR_VENTIL${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_CMP_LIF',  'EST_DLVGTR_PA','${DFILP}/${ENV_PREFIX}_ESID2040_DLVGTR_PA${IT}_${TYPEINV}_${PARM_BALSHTYEA_NF}1231.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_CMP_LIF',  'EST_SRGTEF_PA','${DFILP}/${ENV_PREFIX}_ESID2040_SRGTEF_PA${IT}_${TYPEINV}_${PARM_BALSHTYEA_NF}1231.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_CMP_LIF',  'EST_SRGTEF_SRV_PC','${DFILP}/${ENV_PREFIX}_ESID2040_SRGTEF_SRV_PC${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_CMP_LIF',  'EST_CMPCALC_PA','${DFILP}/${ENV_PREFIX}_ESID2040_CMPCALC_PA${IT}_${TYPEINV}_${PARM_BALSHTYEA_NF}1231.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_CMP_LIF',  'EST_DLVGTAA_PA','${DFILP}/${ENV_PREFIX}_ESID2040_DLVGTAA_PA${IT}_${TYPEINV}_${PARM_BALSHTYEA_NF}1231.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_CMP_LIF',  'EST_DLVGTAR_PA','${DFILP}/${ENV_PREFIX}_ESID2040_DLVGTAR_PA${IT}_${TYPEINV}_${PARM_BALSHTYEA_NF}1231.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_CMP_LIF',  'EST_SIGNANO_PA','${DFILP}/${ENV_PREFIX}_ESID2040_SIGNANO_PA${IT}_${TYPEINV}_${PARM_BALSHTYEA_NF}1231.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_CMP_LIF',  'EST_SRGTE_SRV_PA','${DFILP}/${ENV_PREFIX}_ESID2040_SRGTE_SRV_PA${IT}_${TYPEINV}_${PARM_BALSHTYEA_NF}1231.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_CMP_LIF',  'EST_SRGTEF_SRV_PA','${DFILP}/${ENV_PREFIX}_ESID2040_SRGTEF_SRV_PA${IT}_${TYPEINV}_${PARM_BALSHTYEA_NF}1231.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_CMP_LIF',  'EST_FUNDWITHHELD_I17G_PC','${DFILP}/${ENV_PREFIX}_ESID2040_FUNDWITHHELD_I17G_PC${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_CMP_LIF',  'EST_FUNDWITHHELD_I17L_PC','${DFILP}/${ENV_PREFIX}_ESID2040_FUNDWITHHELD_I17L_PC${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Q_CMP_LIF',  'EST_FUNDWITHHELD_I17P_PC','${DFILP}/${ENV_PREFIX}_ESID2040_FUNDWITHHELD_I17P_PC${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I4IMINV',  'I4I_Q_CMP_LIF','')
			insert into BEST..TI17REQFNC values ('I4IQINV',  'I4I_Q_CMP_LIF','@variante')
			insert into BEST..TI17REQFNC values ('I4IYINV',  'I4I_Q_CMP_LIF','@variante')

	----------IDF_CT:   I4I_Y_CMP_LIF ------------------

		insert into BEST..TI17FNC values ('I4I_Y_CMP_LIF',' ','ESID2040',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I4I_Y_CMP_LIF',  'EST_SUBTRS','${DFILP}/${ENV_PREFIX}_ESCJ0060_FSUBTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_CMP_LIF',  'EST_FTRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_CMP_LIF',  'EST_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_CMP_LIF',  'EST_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_CMP_LIF',  'EST_FCPLACC','${DFILP}/${ENV_PREFIX}_ESID0560_FCPLACC_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_CMP_LIF',  'EST_FGRP','${DFILP}/${ENV_PREFIX}_ESCJ0060_FGRP_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_CMP_LIF',  'EST_FSUBSID','${DFILP}/${ENV_PREFIX}_ESCJ0060_FSUBSID_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_CMP_LIF',  'EST_SRGTC','${DFILP}/${ENV_PREFIX}_ESID2030_SRGTC${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_CMP_LIF',  'EST_FACCPAR0','${DFILP}/${ENV_PREFIX}_ESID0060_FACCPAR0_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_CMP_LIF',  'EST_FACMTRSH','${DFILP}/${ENV_PREFIX}_ESCJ0060_FACMTRSH_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_CMP_LIF',  'EST_FBANTECL','${DFILP}/${ENV_PREFIX}_ESCJ0060_FBANTECL_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_CMP_LIF',  'EST_SEGRATANO','${DFILP}/${ENV_PREFIX}_ESID2070_SEGRATANO_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_CMP_LIF',  'EST_CPLIFDRI','${DFILP}/${ENV_PREFIX}_ESID2030_CPLIFDRI${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_CMP_LIF',  'EST_SUBTRSASSO','${DFILP}/${ENV_PREFIX}_ESCJ0060_FSUBTRSASSO_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_CMP_LIF',  'EST_IAVPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_IAVPERICASE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_CMP_LIF',  'EST_IRVPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_IRVPERICASE_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_CMP_LIF',  'EST_CRIBLEANO','${DFILP}/${ENV_PREFIX}_ESID2070_CRIBLEANO${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_CMP_LIF',  'EST_FVPLACEMT','${DFILP}/${ENV_PREFIX}_ESID2070_FVPLACEMT${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_CMP_LIF',  'EST_VLIFEST195','${DFILP}/${ENV_PREFIX}_ESID2030_VLIFEST195${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_CMP_LIF',  'EST_LIFESTNOACC','${DFILP}/${ENV_PREFIX}_ESID2070_LIFESTNOACC${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_CMP_LIF',  'EST_SUBTRSESBPROP','${DFILP}/${ENV_PREFIX}_ESCJ0060_FSUBTRSESBPROP_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_CMP_LIF',  'EST_SUBTRSBLOCKLIFEST','${DFILP}/${ENV_PREFIX}_ESCJ0060_FSUBTRSBLOCKLIFEST_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_CMP_LIF',  'EST_IARVPERICASE0','${DFILP}/${ENV_PREFIX}_ESID2070_IARVPERICASE0${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_CMP_LIF',  'EST_IARVPERICASE4','${DFILP}/${ENV_PREFIX}_ESID2070_IARVPERICASE4${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_CMP_LIF',  'EST_SRGTE_PC','${DFILP}/${ENV_PREFIX}_ESID2040_SRGTE_PC${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_CMP_LIF',  'EST_DLVGTR_PC','${DFILP}/${ENV_PREFIX}_ESID2040_DLVGTR_PC${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_CMP_LIF',  'EST_SRGTEF_PC','${DFILP}/${ENV_PREFIX}_ESID2040_SRGTEF_PC${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_CMP_LIF',  'EST_CMPCALC_PC','${DFILP}/${ENV_PREFIX}_ESID2040_CMPCALC_PC${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_CMP_LIF',  'EST_DLVGTAA_PC','${DFILP}/${ENV_PREFIX}_ESID2040_DLVGTAA_PC${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_CMP_LIF',  'EST_DLVGTAR_PC','${DFILP}/${ENV_PREFIX}_ESID2040_DLVGTAR_PC${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_CMP_LIF',  'EST_SIGNANO_PC','${DFILP}/${ENV_PREFIX}_ESID2040_SIGNANO_PC${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_CMP_LIF',  'EST_SRGTE_PA','${DFILP}/${ENV_PREFIX}_ESID2040_SRGTE_PA${IT}_${TYPEINV}_${PARM_BALSHTYEA_NF}1231.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_CMP_LIF',  'EST_SRGTE_SRV_PC','${DFILP}/${ENV_PREFIX}_ESID2040_SRGTE_SRV_PC${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_CMP_LIF',  'EST_SRGTR_VENTIL','${DFILP}/${ENV_PREFIX}_ESID2040_SRGTR_VENTIL${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_CMP_LIF',  'EST_DLVGTR_PA','${DFILP}/${ENV_PREFIX}_ESID2040_DLVGTR_PA${IT}_${TYPEINV}_${PARM_BALSHTYEA_NF}1231.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_CMP_LIF',  'EST_SRGTEF_PA','${DFILP}/${ENV_PREFIX}_ESID2040_SRGTEF_PA${IT}_${TYPEINV}_${PARM_BALSHTYEA_NF}1231.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_CMP_LIF',  'EST_SRGTEF_SRV_PC','${DFILP}/${ENV_PREFIX}_ESID2040_SRGTEF_SRV_PC${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_CMP_LIF',  'EST_CMPCALC_PA','${DFILP}/${ENV_PREFIX}_ESID2040_CMPCALC_PA${IT}_${TYPEINV}_${PARM_BALSHTYEA_NF}1231.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_CMP_LIF',  'EST_DLVGTAA_PA','${DFILP}/${ENV_PREFIX}_ESID2040_DLVGTAA_PA${IT}_${TYPEINV}_${PARM_BALSHTYEA_NF}1231.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_CMP_LIF',  'EST_DLVGTAR_PA','${DFILP}/${ENV_PREFIX}_ESID2040_DLVGTAR_PA${IT}_${TYPEINV}_${PARM_BALSHTYEA_NF}1231.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_CMP_LIF',  'EST_SIGNANO_PA','${DFILP}/${ENV_PREFIX}_ESID2040_SIGNANO_PA${IT}_${TYPEINV}_${PARM_BALSHTYEA_NF}1231.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_CMP_LIF',  'EST_SRGTE_SRV_PA','${DFILP}/${ENV_PREFIX}_ESID2040_SRGTE_SRV_PA${IT}_${TYPEINV}_${PARM_BALSHTYEA_NF}1231.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_CMP_LIF',  'EST_SRGTEF_SRV_PA','${DFILP}/${ENV_PREFIX}_ESID2040_SRGTEF_SRV_PA${IT}_${TYPEINV}_${PARM_BALSHTYEA_NF}1231.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_CMP_LIF',  'EST_FUNDWITHHELD_I17G_PC','${DFILP}/${ENV_PREFIX}_ESID2040_FUNDWITHHELD_I17G_PC${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_CMP_LIF',  'EST_FUNDWITHHELD_I17L_PC','${DFILP}/${ENV_PREFIX}_ESID2040_FUNDWITHHELD_I17L_PC${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_Y_CMP_LIF',  'EST_FUNDWITHHELD_I17P_PC','${DFILP}/${ENV_PREFIX}_ESID2040_FUNDWITHHELD_I17P_PC${IT}_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I4IMINV',  'I4I_Y_CMP_LIF','')
			insert into BEST..TI17REQFNC values ('I4IQINV',  'I4I_Y_CMP_LIF','@variante')
			insert into BEST..TI17REQFNC values ('I4IYINV',  'I4I_Y_CMP_LIF','@variante')
go

