-------------------------------


    ----------   Clean tables   ---------------------

    delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESGD2550')
    delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESGD2550')
    delete BEST..TI17FNC where CHAIN_CT='ESGD2550'
    delete BEST..TI17CHN  where CHAIN_CT='ESGD2550'

    insert into BEST..TI17CHN values ('ESGD2550',  '')


	----------IDF_CT:   I4I_EBS_ESGD2550_SERQS_MERGE ------------------

		insert into BEST..TI17FNC values ('I4I_EBS_ESGD2550_SERQS_MERGE',' ','ESGD2550',0)

        insert into BEST..TI17PERMFIL values ('I4I_EBS_ESGD2550_SERQS_MERGE',  'EST_FSSDACTR_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FSSDACTR_TXT_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
        insert into BEST..TI17PERMFIL values ('I4I_EBS_ESGD2550_SERQS_MERGE',  'EST_FSSDACTR_TXT_EBS','${DFILP}/${ENV_PREFIX}_ESCJ0660_FSSDACTR_TXT.dat','O','')
        
		insert into BEST..TI17PERMFIL values ('I4I_EBS_ESGD2550_SERQS_MERGE',  'EST_FSSDACTR_TXT_MERGE','${DFILP}/${ENV_PREFIX}_ESGD2550_FSSDACTR_TXT_MERGE_SERQS.dat','O','')
        
		insert into BEST..TI17PERMFIL values ('I4I_EBS_ESGD2550_SERQS_MERGE',  'EST_FSSDACTR','${DFILP}/${ENV_PREFIX}_ESCJ0060_FSSDACTR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
		insert into BEST..TI17PERMFIL values ('I4I_EBS_ESGD2550_SERQS_MERGE',  'EST_FSSDACTR_EBS','${DFILP}/${ENV_PREFIX}_ESCJ0660_FSSDACTR.dat','O','')
		insert into BEST..TI17PERMFIL values ('I4I_EBS_ESGD2550_SERQS_MERGE',  'EST_FCURCVSNI','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURCVSNI.dat','O','')
		insert into BEST..TI17PERMFIL values ('I4I_EBS_ESGD2550_SERQS_MERGE',  'EST_FCURCVSNI_EBS','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURCVSNI.dat','O','')
		insert into BEST..TI17PERMFIL values ('I4I_EBS_ESGD2550_SERQS_MERGE',  'EST_FCURCVSN','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURCVSN.dat','O','')
		insert into BEST..TI17PERMFIL values ('I4I_EBS_ESGD2550_SERQS_MERGE',  'EST_FCURCVSN_EBS','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURCVSN.dat','O','')
	
		insert into BEST..TI17PERMFIL values ('I4I_EBS_ESGD2550_SERQS_MERGE',  'ESF_FCES_EBS_SERQ','${DFILP}/${ENV_PREFIX}_ESGD2550_FCES_EBS_${PARM_TYPEINV2}_SERQ.dat','O','')
		insert into BEST..TI17PERMFIL values ('I4I_EBS_ESGD2550_SERQS_MERGE',  'ESF_FLORETFACTOR_EBS_SERQ','${DFILP}/${ENV_PREFIX}_ESGD2550_LORETFACTOR_EBS_${PARM_TYPEINV2}_SERQ.dat','O','')
																														
		
		
		----------   Reqs    ---------------------
		insert into BEST..TI17REQFNC values ('ALL',  'I4I_EBS_ESGD2550_SERQS_MERGE','')

go


--mapping of  ESGD2550 <==ESID2550

	----------IDF_CT:   I4I_ESGD2550_SERQS_MERGE ------------------

		insert into BEST..TI17FNC values ('I4I_ESGD2550_SERQS_MERGE',' ','ESGD2550',0)


        insert into BEST..TI17PERMFIL values ('I4I_ESGD2550_SERQS_MERGE',  'EST_FSSDACTR_TXT','${DFILP}/${ENV_PREFIX}_ESGD2550_FSSDACTR_TXT_MERGE_SERQS.dat','I','')
		insert into BEST..TI17PERMFIL values ('I4I_ESGD2550_SERQS_MERGE',  'ESF_FCES_SERQ','${DFILP}/${ENV_PREFIX}_ESGD2550_FCES_EBS_${PARM_TYPEINV2}_SERQ.dat','I','')
		insert into BEST..TI17PERMFIL values ('I4I_ESGD2550_SERQS_MERGE',  'ESF_FLORETFACTOR_SERQ','${DFILP}/${ENV_PREFIX}_ESGD2550_LORETFACTOR_EBS_${PARM_TYPEINV2}_SERQ.dat','I','')
	
		insert into BEST..TI17PERMFIL values ('I4I_ESGD2550_SERQS_MERGE',  'EST_IADVPERICASE0','${DFILP}/${ENV_PREFIX}_ESID1000_IADVPERICASE0_INV_${PARM_ICLODAT_D}.dat','I','')
        insert into BEST..TI17PERMFIL values ('I4I_ESGD2550_SERQS_MERGE',  'EST_IADVPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_IADVPERICASE_INV_${PARM_ICLODAT_D}.dat','I','')
        insert into BEST..TI17PERMFIL values ('I4I_ESGD2550_SERQS_MERGE',  'EST_IRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_IRDVPERICASE_INV_${PARM_ICLODAT_D}.dat','I','')
        insert into BEST..TI17PERMFIL values ('I4I_ESGD2550_SERQS_MERGE',  'EST_FCES','${DFILP}/${ENV_PREFIX}_ESID2500_FCES_INV_${PARM_ICLODAT_D}.dat','I','')
        insert into BEST..TI17PERMFIL values ('I4I_ESGD2550_SERQS_MERGE',  'EST_FPLC','${DFILP}/${ENV_PREFIX}_ESID2500_FPLC_INV_${PARM_ICLODAT_D}.dat','I','')
  
        insert into BEST..TI17PERMFIL values ('I4I_ESGD2550_SERQS_MERGE',  'EST_IADVPERICASE0_GL','${DFILP}/${ENV_PREFIX}_ESID1000_IADVPERICASE0_INV_${PARM_ICLODAT_D}_GL.dat','O','')
        insert into BEST..TI17PERMFIL values ('I4I_ESGD2550_SERQS_MERGE',  'EST_IADVPERICASE_GL','${DFILP}/${ENV_PREFIX}_ESID0560_IADVPERICASE_INV_${PARM_ICLODAT_D}_GL.dat','O','')
        insert into BEST..TI17PERMFIL values ('I4I_ESGD2550_SERQS_MERGE',  'EST_IRDVPERICASE_GL','${DFILP}/${ENV_PREFIX}_ESID0560_IRDVPERICASE_INV_${PARM_ICLODAT_D}_GL.dat','O','')
        insert into BEST..TI17PERMFIL values ('I4I_ESGD2550_SERQS_MERGE',  'EST_FCES_GL','${DFILP}/${ENV_PREFIX}_ESID2500_FCES_INV_${PARM_ICLODAT_D}_GL.dat','O','')
        insert into BEST..TI17PERMFIL values ('I4I_ESGD2550_SERQS_MERGE',  'EST_FPLC_GL','${DFILP}/${ENV_PREFIX}_ESID2500_FPLC_INV_${PARM_ICLODAT_D}_GL.dat','O','')
        
        insert into BEST..TI17REQFNC values ('I4IMINV',  'I4I_ESGD2550_SERQS_MERGE','')
        insert into BEST..TI17REQFNC values ('I4IQINV',  'I4I_ESGD2550_SERQS_MERGE','@variante')
        insert into BEST..TI17REQFNC values ('I4IYINV',  'I4I_ESGD2550_SERQS_MERGE','@variante')
go
-------------------------------
--mapping of  ESGD2550 <==ESPD2550

	----------IDF_CT:   EBS_ESGD2550_SERQS_MERGE ------------------

		insert into BEST..TI17FNC values ('EBS_ESGD2550_SERQS_MERGE','EBS Post omega NDIC','ESGD2550',0)
	
		----------  Perms---------------------  

		
		insert into BEST..TI17PERMFIL values ('EBS_ESGD2550_SERQS_MERGE',  'ESF_FCES_SERQ','${DFILP}/${ENV_PREFIX}_ESGD2550_FCES_EBS_${PARM_TYPEINV2}_SERQ.dat','I','')
		insert into BEST..TI17PERMFIL values ('EBS_ESGD2550_SERQS_MERGE',  'ESF_FLORETFACTOR_SERQ','${DFILP}/${ENV_PREFIX}_ESGD2550_LORETFACTOR_EBS_${PARM_TYPEINV2}_SERQ.dat','I','')

		insert into BEST..TI17PERMFIL values ('EBS_ESGD2550_SERQS_MERGE',  'ESF_FCES_EBS_INV_SERQ','${DFILP}/${ENV_PREFIX}_ESGD2550_FCES_EBS_INV_SERQ.dat','I','')
		insert into BEST..TI17PERMFIL values ('EBS_ESGD2550_SERQS_MERGE',  'ESF_FLORETFACTOR_EBS_INV_SERQ','${DFILP}/${ENV_PREFIX}_ESGD2550_LORETFACTOR_EBS_INV_SERQ.dat','I','')
		

		insert into BEST..TI17PERMFIL values ('EBS_ESGD2550_SERQS_MERGE',  'EST_FSSDACTR_TXT','${DFILP}/${ENV_PREFIX}_ESGD2550_FSSDACTR_TXT_MERGE_SERQS.dat','I','')
		

		insert into BEST..TI17PERMFIL values ('EBS_ESGD2550_SERQS_MERGE',  'EST_FCES','${DFILP}/${ENV_PREFIX}_ESFD5040_FCES_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('EBS_ESGD2550_SERQS_MERGE',  'EST_FPLC','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLC_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('EBS_ESGD2550_SERQS_MERGE',  'ESF_FLORETFACTOR','${DFILP}/${ENV_PREFIX}_ESPJ0090_FLORETFACTOR_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('EBS_ESGD2550_SERQS_MERGE',  'EST_IADVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5010_IADVPERICASE_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('EBS_ESGD2550_SERQS_MERGE',  'EST_IADVPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5010_IADVPERICASE_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('EBS_ESGD2550_SERQS_MERGE',  'EST_IRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5010_OIRDVPERICASE_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('EBS_ESGD2550_SERQS_MERGE',  'ESF_TAXRETMGNT','${DFILP}/${ENV_PREFIX}_ESPD0060_TAXRETMGNT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('EBS_ESGD2550_SERQS_MERGE',  'EST_FCTRGRO','${DFILP}/${ENV_PREFIX}_ESFD5010_FCTRGRO_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','O','')
		insert into BEST..TI17PERMFIL values ('EBS_ESGD2550_SERQS_MERGE',  'EST_FPLATXCUMALL','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLATXCUMALL0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
		insert into BEST..TI17PERMFIL values ('EBS_ESGD2550_SERQS_MERGE',  'EST_FPLACEMT0','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLACEMT0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')

		insert into BEST..TI17PERMFIL values ('EBS_ESGD2550_SERQS_MERGE',  'EST_FCES_BBNI','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCESSION0.dat','I','') 
		insert into BEST..TI17PERMFIL values ('EBS_ESGD2550_SERQS_MERGE',  'EST_IADVPERICASE_BBNI','${DFILP}/${ENV_PREFIX}_ESFD5060_IADPERICASE_MRG_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')			
		insert into BEST..TI17PERMFIL values ('EBS_ESGD2550_SERQS_MERGE',  'EST_IRDVPERICASE_BBNI','${DFILP}/${ENV_PREFIX}_ESFD5060_IRDPERICASE_BBNI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')	

		insert into BEST..TI17PERMFIL values ('EBS_ESGD2550_SERQS_MERGE',  'EST_IADPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5040_IADPERICASE_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','O','')
		insert into BEST..TI17PERMFIL values ('EBS_ESGD2550_SERQS_MERGE',  'EST_IRDPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5010_IRDPERICASE0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','O','')
		insert into BEST..TI17PERMFIL values ('EBS_ESGD2550_SERQS_MERGE',  'EST_IADVPERICASE_STD','${DFILP}/${ENV_PREFIX}_ESFD5040_IADVPERICASE_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','O','')
		insert into BEST..TI17PERMFIL values ('EBS_ESGD2550_SERQS_MERGE',  'EST_FPLATXCUM','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLATXCUM_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','O','')
		insert into BEST..TI17PERMFIL values ('EBS_ESGD2550_SERQS_MERGE',  'EST_FPLACEMT2','${DFILP}/${ENV_PREFIX}_ESCJ0660_FPLACEMT2.dat','O','')
		insert into BEST..TI17PERMFIL values ('EBS_ESGD2550_SERQS_MERGE',  'EST_FCESSION1','${DFILP}/${ENV_PREFIX}_ESFD5010_FCESSION1_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','O','')

		insert into BEST..TI17PERMFIL values ('EBS_ESGD2550_SERQS_MERGE',  'EST_FCES_GL','${DFILP}/${ENV_PREFIX}_ESFD5040_FCES_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}_GL.dat','O','')
		insert into BEST..TI17PERMFIL values ('EBS_ESGD2550_SERQS_MERGE',  'EST_FPLC_GL','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLC_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}_GL.dat','0','')
		insert into BEST..TI17PERMFIL values ('EBS_ESGD2550_SERQS_MERGE',  'ESF_FLORETFACTOR_GL','${DFILP}/${ENV_PREFIX}_ESPJ0090_FLORETFACTOR_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}_GL.dat','O','')
		insert into BEST..TI17PERMFIL values ('EBS_ESGD2550_SERQS_MERGE',  'EST_IADVPERICASE_GL','${DFILP}/${ENV_PREFIX}_ESFD5010_IADVPERICASE_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}_GL.dat','O','')
		insert into BEST..TI17PERMFIL values ('EBS_ESGD2550_SERQS_MERGE',  'EST_IADVPERICASE0_GL','${DFILP}/${ENV_PREFIX}_ESFD5010_IADVPERICASE_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}_GL.dat','O','')
		insert into BEST..TI17PERMFIL values ('EBS_ESGD2550_SERQS_MERGE',  'EST_IRDVPERICASE_GL','${DFILP}/${ENV_PREFIX}_ESFD5010_OIRDVPERICASE_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}_GL.dat','O','')
		insert into BEST..TI17PERMFIL values ('EBS_ESGD2550_SERQS_MERGE',  'ESF_TAXRETMGNT_GL','${DFILP}/${ENV_PREFIX}_ESPD0060_TAXRETMGNT_EBS_${TYPEINV}_${PARM_ICLODAT_D}_GL.dat','I','')
		insert into BEST..TI17PERMFIL values ('EBS_ESGD2550_SERQS_MERGE',  'EST_FCTRGRO_GL','${DFILP}/${ENV_PREFIX}_ESFD5010_FCTRGRO_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}_GL.dat','O','')
		insert into BEST..TI17PERMFIL values ('EBS_ESGD2550_SERQS_MERGE',  'EST_FPLATXCUMALL_GL','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLATXCUMALL0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}_GL.dat','I','')
		insert into BEST..TI17PERMFIL values ('EBS_ESGD2550_SERQS_MERGE',  'EST_FPLACEMT0_GL','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLACEMT0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}_GL.dat','I','')

		insert into BEST..TI17PERMFIL values ('EBS_ESGD2550_SERQS_MERGE',  'EST_FCES_BBNI_GL','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCESSION0_GL.dat','O','') 
		insert into BEST..TI17PERMFIL values ('EBS_ESGD2550_SERQS_MERGE',  'EST_IADVPERICASE_BBNI_GL','${DFILP}/${ENV_PREFIX}_ESFD5060_IADPERICASE_MRG_${TYPEINV}_${PARM_ICLODAT_D}_GL.dat','O','')			
		insert into BEST..TI17PERMFIL values ('EBS_ESGD2550_SERQS_MERGE',  'EST_IRDVPERICASE_BBNI_GL','${DFILP}/${ENV_PREFIX}_ESFD5060_IRDPERICASE_BBNI_${TYPEINV}_${PARM_ICLODAT_D}_GL.dat','O','')	

		insert into BEST..TI17PERMFIL values ('EBS_ESGD2550_SERQS_MERGE',  'EST_IADPERICASE_GL','${DFILP}/${ENV_PREFIX}_ESFD5040_IADPERICASE_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}_GL.dat','O','')
		insert into BEST..TI17PERMFIL values ('EBS_ESGD2550_SERQS_MERGE',  'EST_IRDPERICASE0_GL','${DFILP}/${ENV_PREFIX}_ESFD5010_IRDPERICASE0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}_GL.dat','O','')
		insert into BEST..TI17PERMFIL values ('EBS_ESGD2550_SERQS_MERGE',  'EST_IADVPERICASE_STD_GL','${DFILP}/${ENV_PREFIX}_ESFD5040_IADVPERICASE_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}_GL.dat','O','')
		insert into BEST..TI17PERMFIL values ('EBS_ESGD2550_SERQS_MERGE',  'EST_FPLATXCUM_GL','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLATXCUM_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}_GL.dat','O','')
		insert into BEST..TI17PERMFIL values ('EBS_ESGD2550_SERQS_MERGE',  'EST_FPLACEMT2_GL','${DFILP}/${ENV_PREFIX}_ESCJ0660_FPLACEMT2_GL.dat','O','')
		insert into BEST..TI17PERMFIL values ('EBS_ESGD2550_SERQS_MERGE',  'EST_FCESSION1_GL','${DFILP}/${ENV_PREFIX}_ESFD5010_FCESSION1_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}_GL.dat','O','')


		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('EBSEMINV',  'EBS_ESGD2550_SERQS_MERGE','')
			insert into BEST..TI17REQFNC values ('EBSEQINV',  'EBS_ESGD2550_SERQS_MERGE','')
			insert into BEST..TI17REQFNC values ('EBSEQPOS',  'EBS_ESGD2550_SERQS_MERGE','')
			insert into BEST..TI17REQFNC values ('EBSEYINV',  'EBS_ESGD2550_SERQS_MERGE','')
			insert into BEST..TI17REQFNC values ('EBSEYPOS',  'EBS_ESGD2550_SERQS_MERGE','')


go






-------------------------------
--mapping of  ESGD2550 <==ESFD2550

	
	----------IDF_CT:   I17G_SERQS_MERGE ------------------

		insert into BEST..TI17FNC values ('I17G_SERQS_MERGE','Bouclette Future RetroP Inception','ESGD2550',0)
					
		
		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17G_SERQS_MERGE',  'ESF_FCES_I17_SERQ','${DFILP}/${ENV_PREFIX}_ESGD2550_FCES_I17G_${TYPEINV}_SERQ.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_SERQS_MERGE',  'ESF_FLORETFACTOR_I17_SERQ','${DFILP}/${ENV_PREFIX}_ESGD2550_LORETFACTOR_I17G_${TYPEINV}_SERQ.dat','O','')

			insert into BEST..TI17PERMFIL values ('I17G_SERQS_MERGE',  'ESF_FCES_I17_INV_SERQ','${DFILP}/${ENV_PREFIX}_ESGD2550_FCES_I17G_INV_SERQ.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_SERQS_MERGE',  'ESF_FLORETFACTOR_I17_INV_SERQ','${DFILP}/${ENV_PREFIX}_ESGD2550_LORETFACTOR_I17G_INV_SERQ.dat','I','')
			
			insert into BEST..TI17PERMFIL values ('I17G_SERQS_MERGE',  'ESF_FCES_SERQ','${DFILP}/${ENV_PREFIX}_ESGD2550_FCES_I17G_${TYPEINV}_SERQ.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_SERQS_MERGE',  'ESF_FLORETFACTOR_SERQ','${DFILP}/${ENV_PREFIX}_ESGD2550_LORETFACTOR_I17G_${TYPEINV}_SERQ.dat','O','')

			insert into BEST..TI17PERMFIL values ('I17G_SERQS_MERGE',  'ESF_FI17CLOPER','${DFILP}/${ENV_PREFIX}_ESFD1130_FI17CLOPER_I17G_DSC_ALL_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

			insert into BEST..TI17PERMFIL values ('I17G_SERQS_MERGE',  'EST_FSSDACTR_TXT','${DFILP}/${ENV_PREFIX}_ESGD2550_FSSDACTR_TXT_MERGE_SERQS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_SERQS_MERGE',  'EST_FCES_EBS','${DFILP}/${ENV_PREFIX}_ESFD5040_FCES_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')

			insert into BEST..TI17PERMFIL values ('I17G_SERQS_MERGE',  'EST_FCES_5010','${DFILP}/${ENV_PREFIX}_ESFD5040_I17G_MRG_FUT_INI_FCES_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_SERQS_MERGE',  'EST_FCES_5030','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_SERQS_MERGE',  'ESF_IRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5010_IRDPERICASE0_EBS_${PARM_TYPEINV2}_²${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_SERQS_MERGE',  'ESF_RETRO_PLAN','${DFILP}/${ENV_PREFIX}_ESFD5040_I17G_RETRO_PLAN_${PARM_ICLODAT_D}.dat','I','')
				
			insert into BEST..TI17PERMFIL values ('I17G_SERQS_MERGE',  'EST_FCES','${DFILP}/${ENV_PREFIX}_ESFD5040_I17G_MRG_FUT_INI_FCES_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_SERQS_MERGE',  'EST_FPLC','${DFILP}/${ENV_PREFIX}_ESFD5010_I17G_MRG_PER_INI_FPLC_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_SERQS_MERGE',  'EST_FPLACEMT0','${DFILP}/${ENV_PREFIX}_ESFD5010_I17G_MRG_PER_INI_FPLACEMT0_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_SERQS_MERGE',  'EST_IADVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17G_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_SERQS_MERGE',  'EST_IRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE_I17G_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			--insert into BEST..TI17PERMFIL values ('I17G_SERQS_MERGE',  'EST_IRDVPERICASE_NP','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE_NP_I17G_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_SERQS_MERGE',  'EST_FCTRGRO','${DFILP}/${ENV_PREFIX}_ESFD5010_I17G_MRG_PER_INI_FCTRGRO_${PARM_TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
            insert into BEST..TI17PERMFIL values ('I17G_SERQS_MERGE',  'EST_FPLATXCUM','${DFILP}/${ENV_PREFIX}_ESFD5010_I17G_MRG_PER_INI_FPLATXCUM_${PARM_TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_SERQS_MERGE',  'EST_FPLATXCUMALL','${DFILP}/${ENV_PREFIX}_ESFD5010_I17G_MRG_PER_INI_FPLATXCUMALL_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_SERQS_MERGE',  'ESF_FLORETFACTOR_MRG','${DFILP}/${ENV_PREFIX}_ESPJ0090_I17G_AEE_RPO_I17_FLORETFACTOR_MRG_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_SERQS_MERGE',  'ESF_FLORETFACTOR','${DFILP}/${ENV_PREFIX}_ESPJ0090_I17G_AEE_RPO_I17_FLORETFACTOR_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			--insert into BEST..TI17PERMFIL values ('I17G_SERQS_MERGE',  'EST_IRDPERICASE0_I17','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE0_I17G_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_SERQS_MERGE',  'ESF_ILL_BUCKET','${DFILP}/${ENV_PREFIX}_ESFD2050_ILL_BUCKET_I17G.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_SERQS_MERGE',  'ESF_TRERETFACCTR','${DFILP}/${ENV_PREFIX}_ESFD1130_TRERETFACCTR_I17G_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			--insert into BEST..TI17PERMFIL values ('I17G_SERQS_MERGE',  'ESF_FMARKET','${DFILP}/${ENV_PREFIX}_ESFD0060_I17G_FMARKET_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_SERQS_MERGE',  'ESF_SECIFRS_CR_EXTRACT','${DFILP}/${ENV_PREFIX}_ESFD1130_SECIFRS_CR_EXTRACT_I17G_DSC_ALL_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
		
			insert into BEST..TI17PERMFIL values ('I17G_SERQS_MERGE',  'EST_FCES_GL','${DFILP}/${ENV_PREFIX}_ESFD5040_I17G_MRG_FUT_INI_FCES_${TYPEINV}_${PARM_ICLODAT_D}_GL.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_SERQS_MERGE',  'EST_FPLC_GL','${DFILP}/${ENV_PREFIX}_ESFD5010_I17G_MRG_PER_INI_FPLC_${TYPEINV}_${PARM_ICLODAT_D}_GL.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_SERQS_MERGE',  'EST_FPLACEMT0_GL','${DFILP}/${ENV_PREFIX}_ESFD5010_I17G_MRG_PER_INI_FPLACEMT0_${TYPEINV}_${PARM_ICLODAT_D}_GL.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_SERQS_MERGE',  'EST_IADVPERICASE_GL','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17G_INI_${TYPEINV}_${PARM_ICLODAT_D}_GL.dat','O','')
	        insert into BEST..TI17PERMFIL values ('I17G_SERQS_MERGE',  'EST_IRDVPERICASE_GL','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE_I17G_INI_${TYPEINV}_${PARM_ICLODAT_D}_GL.dat','O','')
			--insert into BEST..TI17PERMFIL values ('I17G_SERQS_MERGE',  'EST_IRDVPERICASE_NP_GL','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE_NP_I17G_INI_${TYPEINV}_${PARM_ICLODAT_D}_GL.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_SERQS_MERGE',  'EST_FCTRGRO_GL','${DFILP}/${ENV_PREFIX}_ESFD5010_I17G_MRG_PER_INI_FCTRGRO_${PARM_TYPEINV}_${PARM_ICLODAT_D}_GL.dat','O','')
            insert into BEST..TI17PERMFIL values ('I17G_SERQS_MERGE',  'EST_FPLATXCUM_GL','${DFILP}/${ENV_PREFIX}_ESFD5010_I17G_MRG_PER_INI_FPLATXCUM_${PARM_TYPEINV}_${PARM_ICLODAT_D}_GL.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_SERQS_MERGE',  'EST_FPLATXCUMALL_GL','${DFILP}/${ENV_PREFIX}_ESFD5010_I17G_MRG_PER_INI_FPLATXCUMALL_${TYPEINV}_${PARM_ICLODAT_D}_GL.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_SERQS_MERGE',  'ESF_FLORETFACTOR_MRG_GL','${DFILP}/${ENV_PREFIX}_ESPJ0090_I17G_AEE_RPO_I17_FLORETFACTOR_MRG_${TYPEINV}_${PARM_ICLODAT_D}_GL.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_SERQS_MERGE',  'ESF_FLORETFACTOR_GL','${DFILP}/${ENV_PREFIX}_ESPJ0090_I17G_AEE_RPO_I17_FLORETFACTOR_INI_${TYPEINV}_${PARM_ICLODAT_D}_GL.dat','O','')
			--insert into BEST..TI17PERMFIL values ('I17G_SERQS_MERGE',  'EST_IRDPERICASE0_I17_GL','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE0_I17G_${TYPEINV}_${PARM_ICLODAT_D}_GL.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_SERQS_MERGE',  'ESF_ILL_BUCKET_GL','${DFILP}/${ENV_PREFIX}_ESFD2050_ILL_BUCKET_I17G_GL.dat','O','')
	        insert into BEST..TI17PERMFIL values ('I17G_SERQS_MERGE',  'ESF_TRERETFACCTR_GL','${DFILP}/${ENV_PREFIX}_ESFD1130_TRERETFACCTR_I17G_${TYPEINV}_${PARM_ICLODAT_D}_GL.dat','O','')
			--insert into BEST..TI17PERMFIL values ('I17G_SERQS_MERGE',  'ESF_FMARKET_GL','${DFILP}/${ENV_PREFIX}_ESFD0060_I17G_FMARKET_${TYPEINV}_${PARM_ICLODAT_D}_GL.dat','O','')
        	insert into BEST..TI17PERMFIL values ('I17G_SERQS_MERGE',  'ESF_SECIFRS_CR_EXTRACT_GL','${DFILP}/${ENV_PREFIX}_ESFD1130_SECIFRS_CR_EXTRACT_I17G_DSC_ALL_STD_${TYPEINV}_${PARM_ICLODAT_D}_GL.dat','O','')
		
		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17GMINV',  'I17G_SERQS_MERGE','')
			insert into BEST..TI17REQFNC values ('I17GQINV',  'I17G_SERQS_MERGE','')
			insert into BEST..TI17REQFNC values ('I17GQPOS',  'I17G_SERQS_MERGE','')
			insert into BEST..TI17REQFNC values ('I17GYINV',  'I17G_SERQS_MERGE','')
			insert into BEST..TI17REQFNC values ('I17GYPOS',  'I17G_SERQS_MERGE','')
go


	----------IDF_CT:   I17L_SERQS_MERGE ------------------

		insert into BEST..TI17FNC values ('I17L_SERQS_MERGE','Bouclette Future RetroP Inception','ESGD2550',0)
					
		
		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE',  'ESF_FCES_I17_SERQ','${DFILP}/${ENV_PREFIX}_ESGD2550_FCES_I17L_${TYPEINV}_SERQ.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE',  'ESF_FLORETFACTOR_I17_SERQ','${DFILP}/${ENV_PREFIX}_ESGD2550_LORETFACTOR_I17L_${TYPEINV}_SERQ.dat','O','')

			insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE',  'ESF_FCES_I17_INV_SERQ','${DFILP}/${ENV_PREFIX}_ESGD2550_FCES_I17L_INV_SERQ.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE',  'ESF_FLORETFACTOR_I17_INV_SERQ','${DFILP}/${ENV_PREFIX}_ESGD2550_LORETFACTOR_I17L_INV_SERQ.dat','I','')
			
			insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE',  'ESF_FCES_SERQ','${DFILP}/${ENV_PREFIX}_ESGD2550_FCES_I17L_${TYPEINV}_SERQ.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE',  'ESF_FLORETFACTOR_SERQ','${DFILP}/${ENV_PREFIX}_ESGD2550_LORETFACTOR_I17L_${TYPEINV}_SERQ.dat','O','')

			insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE',  'ESF_FI17CLOPER','${DFILP}/${ENV_PREFIX}_ESFD1130_FI17CLOPER_I17L_DSC_ALL_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

			insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE',  'EST_FSSDACTR_TXT','${DFILP}/${ENV_PREFIX}_ESGD2550_FSSDACTR_TXT_MERGE_SERQS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE',  'EST_FCES_EBS','${DFILP}/${ENV_PREFIX}_ESFD5040_FCES_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')

		
			insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE',  'EST_FCES_5010','${DFILP}/${ENV_PREFIX}_ESFD5040_I17L_MRG_FUT_INI_FCES_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE',  'EST_FCES_5030','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE',  'ESF_IRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5010_IRDPERICASE0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE',  'ESF_RETRO_PLAN','${DFILP}/${ENV_PREFIX}_ESFD5040_I17L_RETRO_PLAN_${PARM_ICLODAT_D}.dat','I','')

			insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE',  'EST_FCES','${DFILP}/${ENV_PREFIX}_ESFD5040_I17L_MRG_FUT_INI_FCES_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE',  'EST_FPLC','${DFILP}/${ENV_PREFIX}_ESFD5010_I17L_MRG_PER_INI_FPLC_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE',  'EST_FPLACEMT0','${DFILP}/${ENV_PREFIX}_ESFD5010_I17L_MRG_PER_INI_FPLACEMT0_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE',  'EST_IADVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17L_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE',  'EST_IRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE_I17L_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE',  'EST_FCTRGRO','${DFILP}/${ENV_PREFIX}_ESFD5010_I17L_MRG_PER_INI_FCTRGRO_${PARM_TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
            insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE',  'EST_FPLATXCUM','${DFILP}/${ENV_PREFIX}_ESFD5010_I17L_MRG_PER_INI_FPLATXCUM_${PARM_TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE',  'EST_FPLATXCUMALL','${DFILP}/${ENV_PREFIX}_ESFD5010_I17L_MRG_PER_INI_FPLATXCUMALL_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE',  'ESF_FLORETFACTOR_MRG','${DFILP}/${ENV_PREFIX}_ESPJ0090_I17L_AEE_RPO_I17_FLORETFACTOR_MRG_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE',  'ESF_FLORETFACTOR','${DFILP}/${ENV_PREFIX}_ESPJ0090_I17L_AEE_RPO_I17_FLORETFACTOR_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			--insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE',  'EST_IRDPERICASE0_I17','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE0_I17L_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE',  'ESF_ILL_BUCKET','${DFILP}/${ENV_PREFIX}_ESFD2050_ILL_BUCKET_I17G.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE',  'ESF_TRERETFACCTR','${DFILP}/${ENV_PREFIX}_ESFD1130_TRERETFACCTR_I17L_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE',  'ESF_SECIFRS_CR_EXTRACT','${DFILP}/${ENV_PREFIX}_ESFD1130_SECIFRS_CR_EXTRACT_I17L_DSC_ALL_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
		
			insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE',  'EST_FCES_GL','${DFILP}/${ENV_PREFIX}_ESFD5040_I17L_MRG_FUT_INI_FCES_${TYPEINV}_${PARM_ICLODAT_D}_GL.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE',  'EST_FPLC_GL','${DFILP}/${ENV_PREFIX}_ESFD5010_I17L_MRG_PER_INI_FPLC_${TYPEINV}_${PARM_ICLODAT_D}_GL.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE',  'EST_FPLACEMT0_GL','${DFILP}/${ENV_PREFIX}_ESFD5010_I17L_MRG_PER_INI_FPLACEMT0_${TYPEINV}_${PARM_ICLODAT_D}_GL.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE',  'EST_IADVPERICASE_GL','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17L_INI_${TYPEINV}_${PARM_ICLODAT_D}_GL.dat','O','')
	        insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE',  'EST_IRDVPERICASE_GL','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE_I17L_INI_${TYPEINV}_${PARM_ICLODAT_D}_GL.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE',  'EST_FCTRGRO_GL','${DFILP}/${ENV_PREFIX}_ESFD5010_I17L_MRG_PER_INI_FCTRGRO_${PARM_TYPEINV}_${PARM_ICLODAT_D}_GL.dat','O','')
            insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE',  'EST_FPLATXCUM_GL','${DFILP}/${ENV_PREFIX}_ESFD5010_I17L_MRG_PER_INI_FPLATXCUM_${PARM_TYPEINV}_${PARM_ICLODAT_D}_GL.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE',  'EST_FPLATXCUMALL_GL','${DFILP}/${ENV_PREFIX}_ESFD5010_I17L_MRG_PER_INI_FPLATXCUMALL_${TYPEINV}_${PARM_ICLODAT_D}_GL.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE',  'ESF_FLORETFACTOR_MRG_GL','${DFILP}/${ENV_PREFIX}_ESPJ0090_I17L_AEE_RPO_I17_FLORETFACTOR_MRG_${TYPEINV}_${PARM_ICLODAT_D}_GL.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE',  'ESF_FLORETFACTOR_GL','${DFILP}/${ENV_PREFIX}_ESPJ0090_I17L_AEE_RPO_I17_FLORETFACTOR_INI_${TYPEINV}_${PARM_ICLODAT_D}_GL.dat','O','')
			--insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE',  'EST_IRDPERICASE0_I17_GL','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE0_I17L_${TYPEINV}_${PARM_ICLODAT_D}_GL.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE',  'ESF_ILL_BUCKET_GL','${DFILP}/${ENV_PREFIX}_ESFD2050_ILL_BUCKET_I17L_GL.dat','O','')
	        insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE',  'ESF_TRERETFACCTR_GL','${DFILP}/${ENV_PREFIX}_ESFD1130_TRERETFACCTR_I17L_${TYPEINV}_${PARM_ICLODAT_D}_GL.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_SERQS_MERGE',  'ESF_SECIFRS_CR_EXTRACT_GL','${DFILP}/${ENV_PREFIX}_ESFD1130_SECIFRS_CR_EXTRACT_I17L_DSC_ALL_STD_${TYPEINV}_${PARM_ICLODAT_D}_GL.dat','O','')
		
		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17GMINV',  'I17L_SERQS_MERGE','')
			insert into BEST..TI17REQFNC values ('I17GQINV',  'I17L_SERQS_MERGE','')
			insert into BEST..TI17REQFNC values ('I17GQPOS',  'I17L_SERQS_MERGE','')
			insert into BEST..TI17REQFNC values ('I17GYINV',  'I17L_SERQS_MERGE','')
			insert into BEST..TI17REQFNC values ('I17GYPOS',  'I17L_SERQS_MERGE','')
go

--mapping of  ESGD2550 <==ESFD2550

	
	----------IDF_CT:   I17P_SERQS_MERGE ------------------

		insert into BEST..TI17FNC values ('I17P_SERQS_MERGE','Bouclette Future RetroP Inception','ESGD2550',0)
					
		
		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE',  'ESF_FCES_I17_SERQ','${DFILP}/${ENV_PREFIX}_ESGD2550_FCES_I17P_${TYPEINV}_SERQ.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE',  'ESF_FLORETFACTOR_I17_SERQ','${DFILP}/${ENV_PREFIX}_ESGD2550_LORETFACTOR_I17P_${TYPEINV}_SERQ.dat','O','')

			insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE',  'ESF_FCES_I17_INV_SERQ','${DFILP}/${ENV_PREFIX}_ESGD2550_FCES_I17P_INV_SERQ.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE',  'ESF_FLORETFACTOR_I17_INV_SERQ','${DFILP}/${ENV_PREFIX}_ESGD2550_LORETFACTOR_I17P_INV_SERQ.dat','I','')
			
			insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE',  'ESF_FCES_SERQ','${DFILP}/${ENV_PREFIX}_ESGD2550_FCES_I17P_${TYPEINV}_SERQ.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE',  'ESF_FLORETFACTOR_SERQ','${DFILP}/${ENV_PREFIX}_ESGD2550_LORETFACTOR_I17P_${TYPEINV}_SERQ.dat','O','')

			insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE',  'ESF_FI17CLOPER','${DFILP}/${ENV_PREFIX}_ESFD1130_FI17CLOPER_I17P_DSC_ALL_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

			insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE',  'EST_FSSDACTR_TXT','${DFILP}/${ENV_PREFIX}_ESGD2550_FSSDACTR_TXT_MERGE_SERQS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE',  'EST_FCES_EBS','${DFILP}/${ENV_PREFIX}_ESFD5040_FCES_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')

			insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE',  'EST_FCES_5010','${DFILP}/${ENV_PREFIX}_ESFD5040_I17P_MRG_FUT_INI_FCES_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE',  'EST_FCES_5030','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE',  'ESF_IRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5010_IRDPERICASE0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE',  'ESF_RETRO_PLAN','${DFILP}/${ENV_PREFIX}_ESFD5040_I17P_RETRO_PLAN_${PARM_ICLODAT_D}.dat','I','')

	
			insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE',  'EST_FCES','${DFILP}/${ENV_PREFIX}_ESFD5040_I17P_MRG_FUT_INI_FCES_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE',  'EST_FPLC','${DFILP}/${ENV_PREFIX}_ESFD5010_I17P_MRG_PER_INI_FPLC_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE',  'EST_FPLACEMT0','${DFILP}/${ENV_PREFIX}_ESFD5010_I17P_MRG_PER_INI_FPLACEMT0_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE',  'EST_IADVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17P_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE',  'EST_IRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE_I17P_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE',  'EST_FCTRGRO','${DFILP}/${ENV_PREFIX}_ESFD5010_I17P_MRG_PER_INI_FCTRGRO_${PARM_TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
            insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE',  'EST_FPLATXCUM','${DFILP}/${ENV_PREFIX}_ESFD5010_I17P_MRG_PER_INI_FPLATXCUM_${PARM_TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE',  'EST_FPLATXCUMALL','${DFILP}/${ENV_PREFIX}_ESFD5010_I17P_MRG_PER_INI_FPLATXCUMALL_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE',  'ESF_FLORETFACTOR_MRG','${DFILP}/${ENV_PREFIX}_ESPJ0090_I17P_AEE_RPO_I17_FLORETFACTOR_MRG_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE',  'ESF_FLORETFACTOR','${DFILP}/${ENV_PREFIX}_ESPJ0090_I17P_AEE_RPO_I17_FLORETFACTOR_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			--insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE',  'EST_IRDPERICASE0_I17','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE0_I17P_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE',  'ESF_ILL_BUCKET','${DFILP}/${ENV_PREFIX}_ESFD2050_ILL_BUCKET_I17G.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE',  'ESF_TRERETFACCTR','${DFILP}/${ENV_PREFIX}_ESFD1130_TRERETFACCTR_I17P_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE',  'ESF_SECIFRS_CR_EXTRACT','${DFILP}/${ENV_PREFIX}_ESFD1130_SECIFRS_CR_EXTRACT_I17P_DSC_ALL_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
		
			insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE',  'EST_FCES_GL','${DFILP}/${ENV_PREFIX}_ESFD5040_I17P_MRG_FUT_INI_FCES_${TYPEINV}_${PARM_ICLODAT_D}_GL.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE',  'EST_FPLC_GL','${DFILP}/${ENV_PREFIX}_ESFD5010_I17P_MRG_PER_INI_FPLC_${TYPEINV}_${PARM_ICLODAT_D}_GL.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE',  'EST_FPLACEMT0_GL','${DFILP}/${ENV_PREFIX}_ESFD5010_I17P_MRG_PER_INI_FPLACEMT0_${TYPEINV}_${PARM_ICLODAT_D}_GL.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE',  'EST_IADVPERICASE_GL','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17P_INI_${TYPEINV}_${PARM_ICLODAT_D}_GL.dat','O','')
	        insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE',  'EST_IRDVPERICASE_GL','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE_I17P_INI_${TYPEINV}_${PARM_ICLODAT_D}_GL.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE',  'EST_FCTRGRO_GL','${DFILP}/${ENV_PREFIX}_ESFD5010_I17P_MRG_PER_INI_FCTRGRO_${PARM_TYPEINV}_${PARM_ICLODAT_D}_GL.dat','O','')
            insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE',  'EST_FPLATXCUM_GL','${DFILP}/${ENV_PREFIX}_ESFD5010_I17P_MRG_PER_INI_FPLATXCUM_${PARM_TYPEINV}_${PARM_ICLODAT_D}_GL.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE',  'EST_FPLATXCUMALL_GL','${DFILP}/${ENV_PREFIX}_ESFD5010_I17P_MRG_PER_INI_FPLATXCUMALL_${TYPEINV}_${PARM_ICLODAT_D}_GL.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE',  'ESF_FLORETFACTOR_MRG_GL','${DFILP}/${ENV_PREFIX}_ESPJ0090_I17P_AEE_RPO_I17_FLORETFACTOR_MRG_${TYPEINV}_${PARM_ICLODAT_D}_GL.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE',  'ESF_FLORETFACTOR_GL','${DFILP}/${ENV_PREFIX}_ESPJ0090_I17P_AEE_RPO_I17_FLORETFACTOR_INI_${TYPEINV}_${PARM_ICLODAT_D}_GL.dat','O','')
			--insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE',  'EST_IRDPERICASE0_I17_GL','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE0_I17P_${TYPEINV}_${PARM_ICLODAT_D}_GL.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE',  'ESF_ILL_BUCKET_GL','${DFILP}/${ENV_PREFIX}_ESFD2050_ILL_BUCKET_I17P_GL.dat','O','')
	        insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE',  'ESF_TRERETFACCTR_GL','${DFILP}/${ENV_PREFIX}_ESFD1130_TRERETFACCTR_I17P_${TYPEINV}_${PARM_ICLODAT_D}_GL.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_SERQS_MERGE',  'ESF_SECIFRS_CR_EXTRACT_GL','${DFILP}/${ENV_PREFIX}_ESFD1130_SECIFRS_CR_EXTRACT_I17P_DSC_ALL_STD_${TYPEINV}_${PARM_ICLODAT_D}_GL.dat','O','')
		
		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17GMINV',  'I17P_SERQS_MERGE','')
			insert into BEST..TI17REQFNC values ('I17GQINV',  'I17P_SERQS_MERGE','')
			insert into BEST..TI17REQFNC values ('I17GQPOS',  'I17P_SERQS_MERGE','')
			insert into BEST..TI17REQFNC values ('I17GYINV',  'I17P_SERQS_MERGE','')
			insert into BEST..TI17REQFNC values ('I17GYPOS',  'I17P_SERQS_MERGE','')
go
