-------------------------------
--mapping of  ESDJ0110

	----------   Clean tables   ---------------------

	delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESDJ0110')
	delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESDJ0110')
	delete BEST..TI17FNC where CHAIN_CT='ESDJ0110'
	delete BEST..TI17CHN  where CHAIN_CT='ESDJ0110'

	insert into BEST..TI17CHN values ('ESDJ0110',  '')

	----------IDF_CT:   ESDJ0110 ------------------

		insert into BEST..TI17FNC values ('ESDJ0110',' ','ESDJ0110',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('ESDJ0110',  'EST_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESDJ0110',  'EST_SUBTRS','${DFILP}/${ENV_PREFIX}_ESDJ1010_SUBTRS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESDJ0110',  'EST_FSUBSID','${DFILP}/${ENV_PREFIX}_ESDJ1010_FSUBSID_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESDJ0110',  'EST_FLIFDRI','${DFILP}/${ENV_PREFIX}_ESDJ1010_FLIFDRI${IT}_ALL_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESDJ0110',  'EST_IARVPERICASE4','${DFILP}/${ENV_PREFIX}_ESDJ1010_IARVPERICASE4_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESDJ0110',  'EST_SUBTRSESBPROP','${DFILP}/${ENV_PREFIX}_ESDJ1010_SUBTRSESBPROP_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESDJ0110',  'EST_FESB','${DFILP}/${ENV_PREFIX}_ESDJ0110_FESB_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESDJ0110',  'EST_TCALL','${DFILP}/${ENV_PREFIX}_ESDJ0110_TCALL_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESDJ0110',  'EST_TGAPTHR','${DFILP}/${ENV_PREFIX}_ESDJ0110_TGAPTHR_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESDJ0110',  'EST_FAVERATE','${DFILP}/${ENV_PREFIX}_ESDJ0110_FAVERATE_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESDJ0110',  'EST_FCPLACC0','${DFILP}/${ENV_PREFIX}_ESDJ0110_FCPLACC0_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESDJ0110',  'EST_FACCTRAA0','${DFILP}/${ENV_PREFIX}_ESDJ0110_FACCTRAA0_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESDJ0110',  'EST_TGAPACCPRO','${DFILP}/${ENV_PREFIX}_ESDJ0110_TGAPACCPRO_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESDJ0110',  'EST_FLIFEST0','${DFILP}/${ENV_PREFIX}_ESDJ0110_FLIFEST${IT}0_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESDJ0110',  'EST_ERRUPDBATCH','${DFILP}/${ENV_PREFIX}_ESDJ0110_ERRUPDBATCH_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESDJ0110',  'EST_FSUBTRSBASE','${DFILP}/${ENV_PREFIX}_ESDJ0110_FSUBTRSBASE_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESDJ0110',  'EST_FIDLIFEST_MVT','${DFILP}/${ENV_PREFIX}_ESDJ0110_FIDLIFEST_MVT_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESDJ0110',  'EST_FIDLIFEST_CALL','${DFILP}/${ENV_PREFIX}_ESDJ0110_FIDLIFEST_CALL_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESDJ0110',  'EST_ESTC2040_LAST_LIFEST_O1','${DFILP}/${ENV_PREFIX}_ESDJ0110_ESTC2040_LAST_LIFEST_O1_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESDJ0110',  'EST_180_ESTC2040_OLD_LIFEST_O2','${DFILP}/${ENV_PREFIX}_ESDJ0110_180_ESTC2040_OLD_LIFEST_O2_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('ALL',  'ESDJ0110','')
go

