-------------------------------
--mapping of  ESFD2040

	----------   Clean tables   ---------------------

	delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD2040')
	delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD2040')
	delete BEST..TI17FNC where CHAIN_CT='ESFD2040'
	delete BEST..TI17CHN  where CHAIN_CT='ESFD2040'

	insert into BEST..TI17CHN values ('ESFD2040',  '')

	----------IDF_CT:   ESFD2040 ------------------

		insert into BEST..TI17FNC values ('ESFD2040',' ','ESFD2040',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_SUBTRS','${DFILP}/${ENV_PREFIX}_ESCJ0060_FSUBTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_FTRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_FGRP','${DFILP}/${ENV_PREFIX}_ESCJ0060_FGRP_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_FSUBSID','${DFILP}/${ENV_PREFIX}_ESCJ0060_FSUBSID_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_FCPLACC','${DFILP}/${ENV_PREFIX}_ESID0560_FCPLACC_INV_${PARM_ICLODAT2_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_SRGTC','${DFILP}/${ENV_PREFIX}_ESFD2030_SRGTC${IT}_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_FACCPAR0','${DFILP}/${ENV_PREFIX}_ESID0060_FACCPAR0_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_FACMTRSH','${DFILP}/${ENV_PREFIX}_ESCJ0060_FACMTRSH_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_FBANTECL','${DFILP}/${ENV_PREFIX}_ESCJ0060_FBANTECL_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_SEGRATANO','${DFILP}/${ENV_PREFIX}_ESFD2070_SEGRATANO_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_CPLIFDRI','${DFILP}/${ENV_PREFIX}_ESFD2030_CPLIFDRI${IT}_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_SUBTRSASSO','${DFILP}/${ENV_PREFIX}_ESCJ0060_FSUBTRSASSO_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_CRIBLEANO','${DFILP}/${ENV_PREFIX}_ESFD2070_CRIBLEANO${IT}_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_FVPLACEMT','${DFILP}/${ENV_PREFIX}_ESFD2070_FVPLACEMT${IT}_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_IAVPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_IAVPERICASE_INV_${PARM_ICLODAT2_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_IRVPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_IRVPERICASE_INV_${PARM_ICLODAT2_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_VLIFEST195','${DFILP}/${ENV_PREFIX}_ESFD2030_VLIFEST195${IT}_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_LIFESTNOACC','${DFILP}/${ENV_PREFIX}_ESFD2070_LIFESTNOACC${IT}_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_SUBTRSESBPROP','${DFILP}/${ENV_PREFIX}_ESCJ0060_FSUBTRSESBPROP_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_IARVPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD2070_IARVPERICASE0${IT}_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_IARVPERICASE4','${DFILP}/${ENV_PREFIX}_ESFD2070_IARVPERICASE4${IT}_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_SRGTE_PA','${DFILP}/${ENV_PREFIX}_ESFD2040_SRGTE_PA${IT}_${BALSHTYEA}1231.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_DLVGTR_PA','${DFILP}/${ENV_PREFIX}_ESFD2040_DLVGTR_PA${IT}_${BALSHTYEA}1231.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_SRGTEF_PA','${DFILP}/${ENV_PREFIX}_ESFD2040_SRGTEF_PA${IT}_${BALSHTYEA}1231.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_CMPCALC_PA','${DFILP}/${ENV_PREFIX}_ESFD2040_CMPCALC_PA${IT}_${BALSHTYEA}1231.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_DLVGTAA_PA','${DFILP}/${ENV_PREFIX}_ESFD2040_DLVGTAA_PA${IT}_${BALSHTYEA}1231.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_DLVGTAR_PA','${DFILP}/${ENV_PREFIX}_ESFD2040_DLVGTAR_PA${IT}_${BALSHTYEA}1231.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_SIGNANO','${DFILP}/${ENV_PREFIX}_ESFD2040_SIGNANO${IT}_INV_${PARM_ICLODAT2_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_SRGTE_PC','${DFILP}/${ENV_PREFIX}_ESFD2040_SRGTE_PC${IT}_INV_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_SRGTEF_PC','${DFILP}/${ENV_PREFIX}_ESFD2040_SRGTEF_PC${IT}_INV_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_DLVGTR_PC','${DFILP}/${ENV_PREFIX}_ESFD2040_DLVGTR_PC${IT}_INV_${PARM_ICLODAT2_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_SRGTE_SRV_PA','${DFILP}/${ENV_PREFIX}_ESFD2040_SRGTE_SRV_PA${IT}_${BALSHTYEA}1231.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_CMPCALC_PC','${DFILP}/${ENV_PREFIX}_ESFD2040_CMPCALC_PC${IT}_INV_${PARM_ICLODAT2_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_SRGTEF_SRV_PA','${DFILP}/${ENV_PREFIX}_ESFD2040_SRGTEF_SRV_PA${IT}_${BALSHTYEA}1231.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_DLVGTAR_PC','${DFILP}/${ENV_PREFIX}_ESFD2040_DLVGTAR_PC${IT}_${PARM_ICLODAT_D}_${CRE_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_SRGTE_SRV_PC','${DFILP}/${ENV_PREFIX}_ESFD2040_SRGTE_SRV_PC${IT}_INV_${PARM_ICLODAT2_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_SRGTR_VENTIL','${DFILP}/${ENV_PREFIX}_ESFD2040_SRGTR_VENTIL${IT}_INV_${PARM_ICLODAT2_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_DLVGTAA_PC','${DFILP}/${ENV_PREFIX}_ESFD2040_DLVGTAA_PC${IT}_${PARM_ICLODAT2_D}_${CRE_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESFD2040',  'EST_SRGTEF_SRV_PC','${DFILP}/${ENV_PREFIX}_ESFD2040_SRGTEF_SRV_PC${IT}_INV_${PARM_ICLODAT2_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I4IMINV',  'ESFD2040','')
			insert into BEST..TI17REQFNC values ('I4IQINV',  'ESFD2040','@variante')
			insert into BEST..TI17REQFNC values ('I4IYINV',  'ESFD2040','@variante')
go

