-------------------------------
--mapping of  ESPD2550

	----------   Clean tables   ---------------------

	delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESPD2550')
	delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESPD2550')
	delete BEST..TI17FNC where CHAIN_CT='ESPD2550'
	delete BEST..TI17CHN  where CHAIN_CT='ESPD2550'

	insert into BEST..TI17CHN values ('ESPD2550',  '')

	----------IDF_CT:   EBS_ESPD2550 ------------------

		insert into BEST..TI17FNC values ('EBS_ESPD2550','IFRS4 Post omega  EBS','ESPD2550',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550',  'EST_DLVGTR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550',  'EST_DLRPGTR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550',  'EST_DLRTGTR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550',  'EST_DLRNPGTR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550',  'EST_DLRTCGTR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550',  'EST_DLRTFGTR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550',  'ESF_DLSGTR_AE','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550',  'EST_DLGTRSNEM','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550',  'EST_SUBTRS','${DFILP}/${ENV_PREFIX}_ESCJ0660_SUBTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550',  'EST_FDETTRS','${DFILP}/${ENV_PREFIX}_ESCJ0660_FDETTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550',  'EST_FTRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550',  'EST_FCURCVSN','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURCVSN.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550',  'EST_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550',  'EST_FSSDACTR','${DFILP}/${ENV_PREFIX}_ESCJ0660_FSSDACTR.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550',  'EST_FCURCVSNI','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURCVSNI.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550',  'EST_FTRANSCODE','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRANSCODE.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550',  'EST_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550',  'EST_GTEP','${DFILP}/${ENV_PREFIX}_ESPD4000_GTEP_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550',  'EST_DLDGTAA','${DFILP}/${ENV_PREFIX}_ESFD2230_DLDGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550',  'EST_FCES','${DFILP}/${ENV_PREFIX}_ESFD5040_FCES_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550',  'EST_FPLC','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLC_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550',  'EST_DLDSIIGTR','${DFILP}/${ENV_PREFIX}_ESPD3620_DLDSIIGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550',  'EST_DLCUMGTAATOT','${DFILP}/${ENV_PREFIX}_ESID2210_DLCUMGTAATOT_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550',  'EST_DLSGTR','${DFILP}/${ENV_PREFIX}_ESPD2570_DLSGTRSII_AE_RETRONP_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550',  'ESF_FLORETFACTOR','${DFILP}/${ENV_PREFIX}_ESPJ0090_FLORETFACTOR_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550',  'EST_IADVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5010_IADVPERICASE_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550',  'EST_IADVPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5010_IADVPERICASE_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550',  'EST_IRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5010_OIRDVPERICASE_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550',  'EST_DLDVGTR','${DFILP}/${ENV_PREFIX}_ESPD2550_DLDVGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550',  'EST_DLREGTR','${DFILP}/${ENV_PREFIX}_ESPD2550_DLREGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550',  'EST_DLRGTAA','${DFILP}/${ENV_PREFIX}_ESPD2550_DLRGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550',  'EST_DLEIGTAA','${DFILP}/${ENV_PREFIX}_ESPD2550_DLEIGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550',  'EST_DLREGTAR','${DFILP}/${ENV_PREFIX}_ESPD2550_DLREGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550',  'EST_DLRIGTAA','${DFILP}/${ENV_PREFIX}_ESPD2550_DLRIGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550',  'EST_DLREMAJGTR','${DFILP}/${ENV_PREFIX}_ESPD2550_DLREMAJGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550',  'EST_DLREGTR_OVR','${DFILP}/${ENV_PREFIX}_ESPD2550_DLREGTR_OVR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550',  'EST_DLREMAJGTAR','${DFILP}/${ENV_PREFIX}_ESPD2550_DLREMAJGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550',  'EST_DLRIGTAANOS','${DFILP}/${ENV_PREFIX}_ESPD2550_DLRIGTAANOS_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550',  'EST_DLREGTAR_OVR','${DFILP}/${ENV_PREFIX}_ESPD2550_DLREGTAR_OVR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550',  'ESF_DLRIGTAA_DACI17','${DFILP}/${ENV_PREFIX}_ESPD2550_DLRIGTAA_DACI17_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550',  'ESF_DLREGTR_DACI17','${DFILP}/${ENV_PREFIX}_ESPD2550_EBS_ESPD2550_DLREGTR_DACI17_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550',  'ESF_DLRGTAA_DACI17','${DFILP}/${ENV_PREFIX}_ESPD2550_EBS_ESPD2550_DLRGTAA_DACI17_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550',  'ESF_DLEIGTAA_DACI17','${DFILP}/${ENV_PREFIX}_ESPD2550_EBS_ESPD2550_DLEIGTAA_DACI17_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550',  'ESF_DLREGTAR_DACI17','${DFILP}/${ENV_PREFIX}_ESPD2550_EBS_ESPD2550_DLREGTAR_DACI17_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('EBSEYINV',  'EBS_ESPD2550','')
			insert into BEST..TI17REQFNC values ('EBSEYPOC',  'EBS_ESPD2550','')
			insert into BEST..TI17REQFNC values ('EBSEYPOCB',  'EBS_ESPD2550','')
			insert into BEST..TI17REQFNC values ('EBSEYPOS',  'EBS_ESPD2550','')
			insert into BEST..TI17REQFNC values ('EBSEMINV',  'EBS_ESPD2550','')
			insert into BEST..TI17REQFNC values ('EBSEQINV',  'EBS_ESPD2550','')
			insert into BEST..TI17REQFNC values ('EBSEQPOC',  'EBS_ESPD2550','')
			insert into BEST..TI17REQFNC values ('EBSEQPOCB',  'EBS_ESPD2550','')
			insert into BEST..TI17REQFNC values ('EBSEQPOS',  'EBS_ESPD2550','')


	----------IDF_CT:   EBS_ESPD2550_BBNI ------------------

		insert into BEST..TI17FNC values ('EBS_ESPD2550_BBNI','IFRS4 Post omega  EBS','ESPD2550',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_BBNI',  'EST_DLVGTR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_BBNI',  'EST_DLRPGTR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_BBNI',  'EST_DLRTGTR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_BBNI',  'EST_DLRNPGTR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_BBNI',  'EST_DLRTCGTR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_BBNI',  'EST_DLRTFGTR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_BBNI',  'ESF_DLSGTR_AE','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_BBNI',  'EST_DLGTRSNEM','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_BBNI',  'EST_SUBTRS','${DFILP}/${ENV_PREFIX}_ESCJ0660_SUBTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_BBNI',  'EST_FDETTRS','${DFILP}/${ENV_PREFIX}_ESCJ0660_FDETTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_BBNI',  'EST_FTRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_BBNI',  'EST_FCURCVSN','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURCVSN.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_BBNI',  'EST_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_BBNI',  'EST_FSSDACTR','${DFILP}/${ENV_PREFIX}_ESCJ0660_FSSDACTR.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_BBNI',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_BBNI',  'EST_FCURCVSNI','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURCVSNI.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_BBNI',  'EST_FTRANSCODE','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRANSCODE.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_BBNI',  'EST_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_BBNI',  'EST_GTEP','${DFILP}/${ENV_PREFIX}_ESPD4000_BBNI_GTEP_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_BBNI',  'EST_DLDGTAA','${DFILP}/${ENV_PREFIX}_ESFD2230_BBNI_DLDGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			--insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_BBNI',  'EST_FCES','${DFILP}/${ENV_PREFIX}_ESFD5040_FCES_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','') 
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_BBNI',  'EST_FCES','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCESSION0.dat','I','') 
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_BBNI',  'EST_FPLC','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLC_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_BBNI',  'EST_DLDSIIGTR','${DFILP}/${ENV_PREFIX}_ESPD3620_DLDSIIGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_BBNI',  'EST_DLCUMGTAATOT','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_BBNI',  'EST_DLSGTR','${DFILP}/empty.dat','I','') --,'${DFILP}/${ENV_PREFIX}_ESPD2570_DLSGTRSII_AE_RETRONP_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_BBNI',  'ESF_FLORETFACTOR','${DFILP}/${ENV_PREFIX}_ESPJ0090_FLORETFACTOR_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_BBNI',  'EST_IADVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5060_IADPERICASE_MRG_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')			
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_BBNI',  'EST_IADVPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5060_IADPERICASE_MRG_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')	
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_BBNI',  'EST_IRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5060_IRDPERICASE_BBNI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')	
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_BBNI',  'EST_DLDVGTR','${DFILP}/${ENV_PREFIX}_ESPD2550_BBNI_DLDVGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_BBNI',  'EST_DLREGTR','${DFILP}/${ENV_PREFIX}_ESPD2550_BBNI_DLREGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_BBNI',  'EST_DLRGTAA','${DFILP}/${ENV_PREFIX}_ESPD2550_BBNI_DLRGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_BBNI',  'EST_DLEIGTAA','${DFILP}/${ENV_PREFIX}_ESPD2550_BBNI_DLEIGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_BBNI',  'EST_DLREGTAR','${DFILP}/${ENV_PREFIX}_ESPD2550_BBNI_DLREGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_BBNI',  'EST_DLRIGTAA','${DFILP}/${ENV_PREFIX}_ESPD2550_BBNI_DLRIGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_BBNI',  'EST_DLREMAJGTR','${DFILP}/${ENV_PREFIX}_ESPD2550_BBNI_DLREMAJGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_BBNI',  'EST_DLREGTR_OVR','${DFILP}/${ENV_PREFIX}_ESPD2550_BBNI_DLREGTR_OVR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_BBNI',  'EST_DLREMAJGTAR','${DFILP}/${ENV_PREFIX}_ESPD2550_BBNI_DLREMAJGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_BBNI',  'EST_DLRIGTAANOS','${DFILP}/${ENV_PREFIX}_ESPD2550_BBNI_DLRIGTAANOS_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_BBNI',  'EST_DLREGTAR_OVR','${DFILP}/${ENV_PREFIX}_ESPD2550_BBNI_DLREGTAR_OVR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_BBNI',  'ESF_DLRIGTAA_DACI17','${DFILP}/${ENV_PREFIX}_ESPD2550_BBNI_DLRIGTAA_DACI17_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_BBNI',  'ESF_DLREGTR_DACI17','${DFILP}/${ENV_PREFIX}_ESPD2550_BBNI_EBS_ESPD2550_BBNI_DLREGTR_DACI17_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_BBNI',  'ESF_DLRGTAA_DACI17','${DFILP}/${ENV_PREFIX}_ESPD2550_BBNI_EBS_ESPD2550_BBNI_DLRGTAA_DACI17_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_BBNI',  'ESF_DLEIGTAA_DACI17','${DFILP}/${ENV_PREFIX}_ESPD2550_BBNI_EBS_ESPD2550_BBNI_DLEIGTAA_DACI17_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_BBNI',  'ESF_DLREGTAR_DACI17','${DFILP}/${ENV_PREFIX}_ESPD2550_BBNI_EBS_ESPD2550_BBNI_DLREGTAR_DACI17_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('EBSEYINV',  'EBS_ESPD2550_BBNI','')
			insert into BEST..TI17REQFNC values ('EBSEYPOC',  'EBS_ESPD2550_BBNI','')
			insert into BEST..TI17REQFNC values ('EBSEYPOCB',  'EBS_ESPD2550_BBNI','')
			insert into BEST..TI17REQFNC values ('EBSEYPOS',  'EBS_ESPD2550_BBNI','')
			insert into BEST..TI17REQFNC values ('EBSEMINV',  'EBS_ESPD2550_BBNI','')
			insert into BEST..TI17REQFNC values ('EBSEQINV',  'EBS_ESPD2550_BBNI','')
			insert into BEST..TI17REQFNC values ('EBSEQPOC',  'EBS_ESPD2550_BBNI','')
			insert into BEST..TI17REQFNC values ('EBSEQPOCB',  'EBS_ESPD2550_BBNI','')
			insert into BEST..TI17REQFNC values ('EBSEQPOS',  'EBS_ESPD2550_BBNI','')

	----------IDF_CT:   EBS_ESPD2550_INI ------------------

		insert into BEST..TI17FNC values ('EBS_ESPD2550_INI','IFRS4 Post omega  EBS','ESPD2550',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_INI',  'EST_DLVGTR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_INI',  'EST_DLRPGTR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_INI',  'EST_DLRTGTR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_INI',  'EST_DLRNPGTR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_INI',  'EST_DLRTCGTR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_INI',  'EST_DLRTFGTR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_INI',  'ESF_DLSGTR_AE','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_INI',  'EST_DLGTRSNEM','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_INI',  'EST_SUBTRS','${DFILP}/${ENV_PREFIX}_ESCJ0660_SUBTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_INI',  'EST_FDETTRS','${DFILP}/${ENV_PREFIX}_ESCJ0660_FDETTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_INI',  'EST_FTRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_INI',  'EST_FCURCVSN','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURCVSN.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_INI',  'EST_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_INI',  'EST_FSSDACTR','${DFILP}/${ENV_PREFIX}_ESCJ0660_FSSDACTR.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_INI',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_INI',  'EST_FCURCVSNI','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCURCVSNI.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_INI',  'EST_FTRANSCODE','${DFILP}/${ENV_PREFIX}_ESCJ0660_FTRANSCODE.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_INI',  'EST_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_INI',  'EST_GTEP','${DFILP}/${ENV_PREFIX}_ESPD4000_INI_GTEP_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_INI',  'EST_DLDGTAA','${DFILP}/${ENV_PREFIX}_ESFD2230_INI_DLDGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			--insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_INI',  'EST_FCES','${DFILP}/${ENV_PREFIX}_ESFD5040_FCES_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','') 
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_INI',  'EST_FCES','${DFILP}/${ENV_PREFIX}_ESCJ0660_FCESSION0.dat','I','') 
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_INI',  'EST_FPLC','${DFILP}/${ENV_PREFIX}_ESFD5010_FPLC_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_INI',  'EST_DLDSIIGTR','${DFILP}/${ENV_PREFIX}_ESPD3620_DLDSIIGTR_EBS_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_INI',  'EST_DLCUMGTAATOT','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_INI',  'EST_DLSGTR','${DFILP}/empty.dat','I','') --,'${DFILP}/${ENV_PREFIX}_ESPD2570_DLSGTRSII_AE_RETRONP_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_INI',  'ESF_FLORETFACTOR','${DFILP}/${ENV_PREFIX}_ESFD5060_EBS_INI_FLORETFACTOR_INI_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_INI',  'EST_IADVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5060_IADPERICASE_MRG_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')			
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_INI',  'EST_IADVPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5060_IADPERICASE_MRG_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')	
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_INI',  'EST_IRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5060_IRDPERICASE_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')	
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_INI',  'EST_DLDVGTR','${DFILP}/${ENV_PREFIX}_ESPD2550_INI_DLDVGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_INI',  'EST_DLREGTR','${DFILP}/${ENV_PREFIX}_ESPD2550_INI_DLREGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_INI',  'EST_DLRGTAA','${DFILP}/${ENV_PREFIX}_ESPD2550_INI_DLRGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_INI',  'EST_DLEIGTAA','${DFILP}/${ENV_PREFIX}_ESPD2550_INI_DLEIGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_INI',  'EST_DLREGTAR','${DFILP}/${ENV_PREFIX}_ESPD2550_INI_DLREGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_INI',  'EST_DLRIGTAA','${DFILP}/${ENV_PREFIX}_ESPD2550_INI_DLRIGTAA_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_INI',  'EST_DLREMAJGTR','${DFILP}/${ENV_PREFIX}_ESPD2550_INI_DLREMAJGTR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_INI',  'EST_DLREGTR_OVR','${DFILP}/${ENV_PREFIX}_ESPD2550_INI_DLREGTR_OVR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_INI',  'EST_DLREMAJGTAR','${DFILP}/${ENV_PREFIX}_ESPD2550_INI_DLREMAJGTAR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_INI',  'EST_DLRIGTAANOS','${DFILP}/${ENV_PREFIX}_ESPD2550_INI_DLRIGTAANOS_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_INI',  'EST_DLREGTAR_OVR','${DFILP}/${ENV_PREFIX}_ESPD2550_INI_DLREGTAR_OVR_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_INI',  'ESF_DLRIGTAA_DACI17','${DFILP}/${ENV_PREFIX}_ESPD2550_INI_DLRIGTAA_DACI17_EBS_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_INI',  'ESF_DLREGTR_DACI17','${DFILP}/${ENV_PREFIX}_ESPD2550_INI_EBS_ESPD2550_INI_DLREGTR_DACI17_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_INI',  'ESF_DLRGTAA_DACI17','${DFILP}/${ENV_PREFIX}_ESPD2550_INI_EBS_ESPD2550_INI_DLRGTAA_DACI17_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_INI',  'ESF_DLEIGTAA_DACI17','${DFILP}/${ENV_PREFIX}_ESPD2550_INI_EBS_ESPD2550_INI_DLEIGTAA_DACI17_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('EBS_ESPD2550_INI',  'ESF_DLREGTAR_DACI17','${DFILP}/${ENV_PREFIX}_ESPD2550_INI_EBS_ESPD2550_INI_DLREGTAR_DACI17_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('EBSEYINV',  'EBS_ESPD2550_INI','')
			insert into BEST..TI17REQFNC values ('EBSEYPOC',  'EBS_ESPD2550_INI','')
			insert into BEST..TI17REQFNC values ('EBSEYPOCB',  'EBS_ESPD2550_INI','')
			insert into BEST..TI17REQFNC values ('EBSEYPOS',  'EBS_ESPD2550_INI','')
			insert into BEST..TI17REQFNC values ('EBSEMINV',  'EBS_ESPD2550_INI','')
			insert into BEST..TI17REQFNC values ('EBSEQINV',  'EBS_ESPD2550_INI','')
			insert into BEST..TI17REQFNC values ('EBSEQPOC',  'EBS_ESPD2550_INI','')
			insert into BEST..TI17REQFNC values ('EBSEQPOCB',  'EBS_ESPD2550_INI','')
			insert into BEST..TI17REQFNC values ('EBSEQPOS',  'EBS_ESPD2550_INI','')





	----------IDF_CT:   I4I_ESPD2550 ------------------

		insert into BEST..TI17FNC values ('I4I_ESPD2550','IFRS4 Post omega  IFRS','ESPD2550',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I4I_ESPD2550',  'EST_DLVGTR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD2550',  'EST_DLDGTAA','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD2550',  'EST_DLRPGTR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD2550',  'EST_DLRTGTR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD2550',  'EST_DLRNPGTR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD2550',  'EST_DLRTCGTR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD2550',  'EST_DLRTFGTR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD2550',  'ESF_DLSGTR_AE','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD2550',  'EST_DLGTRSNEM','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD2550',  'ESF_DLREGTR_DACI17','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD2550',  'EST_SUBTRS','${DFILP}/${ENV_PREFIX}_ESCJ0060_FSUBTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD2550',  'EST_FDETTRS','${DFILP}/${ENV_PREFIX}_ESCJ0060_FDETTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD2550',  'EST_FTRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD2550',  'EST_FCURCVSN','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURCVSN.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD2550',  'EST_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD2550',  'EST_FBOPRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0660_FBOPRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD2550',  'EST_FCURCVSNI','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURCVSNI.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD2550',  'EST_FTRANSCODE','${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRANSCODE.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD2550',  'EST_FTRSLNK_TXT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRSLNK_TXT.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD2550',  'EST_FCES','${DFILP}/${ENV_PREFIX}_ESID2500_FCES_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD2550',  'EST_FPLC','${DFILP}/${ENV_PREFIX}_ESID2500_FPLC_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD2550',  'EST_FSSDACTR','${DFILP}/${ENV_PREFIX}_ESCJ0060_FSSDACTR_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD2550',  'EST_GTEP','${DFILP}/${ENV_PREFIX}_ESPD4000_GTEP_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD2550',  'EST_DLSGTR','${DFILP}/${ENV_PREFIX}_ESPD1800_DLSGTR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD2550',  'EST_IADVPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_IADVPERICASE_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD2550',  'EST_IADVPERICASE0','${DFILP}/${ENV_PREFIX}_ESID0560_IADVPERICASE_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD2550',  'EST_IRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_OIRDVPERICASE_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD2550',  'ESF_FLORETFACTOR','${DFILP}/${ENV_PREFIX}_ESPJ0090_FLORETFACTOR_STD_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD2550',  'EST_DLDVGTR','${DFILP}/${ENV_PREFIX}_ESPD2550_DLDVGTR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD2550',  'EST_DLREGTR','${DFILP}/${ENV_PREFIX}_ESPD2550_DLREGTR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD2550',  'EST_DLRGTAA','${DFILP}/${ENV_PREFIX}_ESPD2550_DLRGTAA_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD2550',  'EST_DLEIGTAA','${DFILP}/${ENV_PREFIX}_ESPD2550_DLEIGTAA_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD2550',  'EST_DLREGTAR','${DFILP}/${ENV_PREFIX}_ESPD2550_DLREGTAR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD2550',  'EST_DLRIGTAA','${DFILP}/${ENV_PREFIX}_ESPD2550_DLRIGTAA_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD2550',  'EST_DLREMAJGTR','${DFILP}/${ENV_PREFIX}_ESPD2550_DLREMAJGTR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD2550',  'EST_DLREGTR_OVR','${DFILP}/${ENV_PREFIX}_ESPD2550_DLREGTR_OVR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD2550',  'EST_DLREMAJGTAR','${DFILP}/${ENV_PREFIX}_ESPD2550_DLREMAJGTAR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD2550',  'EST_DLRIGTAANOS','${DFILP}/${ENV_PREFIX}_ESPD2550_DLRIGTAANOS_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I4I_ESPD2550',  'EST_DLREGTAR_OVR','${DFILP}/${ENV_PREFIX}_ESPD2550_DLREGTAR_OVR_I4I_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I4IQPOC',  'I4I_ESPD2550','')
			insert into BEST..TI17REQFNC values ('I4IQPOCB',  'I4I_ESPD2550','')
			insert into BEST..TI17REQFNC values ('I4IQPOS',  'I4I_ESPD2550','')
			insert into BEST..TI17REQFNC values ('I4IQPOSB',  'I4I_ESPD2550','')
			insert into BEST..TI17REQFNC values ('I4IYPOC',  'I4I_ESPD2550','')
			insert into BEST..TI17REQFNC values ('I4IYPOCB',  'I4I_ESPD2550','')
			insert into BEST..TI17REQFNC values ('I4IYPOS',  'I4I_ESPD2550','')
			insert into BEST..TI17REQFNC values ('I4IYPOSB',  'I4I_ESPD2550','')
go

