-------------------------------
--mapping of  ESID1520

	----------   Clean tables   ---------------------

	delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESID1520')
	delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESID1520')
	delete BEST..TI17FNC where CHAIN_CT='ESID1520'
	delete BEST..TI17CHN  where CHAIN_CT='ESID1520'

	insert into BEST..TI17CHN values ('ESID1520',  '')

	----------IDF_CT:   ESID1520 ------------------

		insert into BEST..TI17FNC values ('ESID1520',' ','ESID1520',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('ESID1520',  'EST_CURGTR','${DFILP}/${ENV_PREFIX}_ESIX7000_CURGTR.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID1520',  'EST_SUBTRS','${DFILP}/${ENV_PREFIX}_ESCJ0060_FSUBTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID1520',  'EST_FDETTRS','${DFILP}/${ENV_PREFIX}_ESCJ0060_FDETTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID1520',  'EST_FTRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID1520',  'EST_FCURCVSN','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURCVSN.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID1520',  'EST_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID1520',  'EST_FCURCVSNI','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURCVSNI.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID1520',  'EST_FTRANSCODE','${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRANSCODE.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID1520',  'EST_GTEP','${DFILP}/${ENV_PREFIX}_ESCJ0060_GTEP${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID1520',  'EST_FACCSUP','${DFILP}/${ENV_PREFIX}_ESID0560_FACCSUP_${TYPEINV}_${PARM_ICLODAT2_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID1520',  'EST_FLIFPLN','${DFILP}/${ENV_PREFIX}_ESID0560_FLIFPLN_${TYPEINV}_${PARM_ICLODAT2_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID1520',  'EST_FACCSUPF','${DFILP}/${ENV_PREFIX}_ESID0560_FACCSUPF_${TYPEINV}_${PARM_ICLODAT2_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID1520',  'EST_FCESSION0','${DFILP}/${ENV_PREFIX}_ESEH1110_FCESSION0_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID1520',  'EST_FPLACEMT0','${DFILP}/${ENV_PREFIX}_ESEH1110_FPLACEMT0_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID1520',  'EST_FVPLACEMT','${DFILP}/${ENV_PREFIX}_ESID2030_FVPLACEMT_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID1520',  'EST_IADVPERICASE','${DFILP}/${ENV_PREFIX}_ESID0560_IADVPERICASE_INV_${PARM_ICLODAT2_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID1520',  'EST_IADVPERICASE0','${DFILP}/${ENV_PREFIX}_ESID1000_IADVPERICASE0_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID1520',  'EST_IARVPERICASE0','${DFILP}/${ENV_PREFIX}_ESID2030_IARVPERICASE0_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID1520',  'EST_IARVPERICASE4','${DFILP}/${ENV_PREFIX}_ESID2030_IARVPERICASE4_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID1520',  'EST_IRDVPERICASE0','${DFILP}/${ENV_PREFIX}_ESID1500_IRDVPERICASE0_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESID1520',  'EST_FCES','${DFILP}/${ENV_PREFIX}_ESID1520_FCES_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID1520',  'EST_FPLC','${DFILP}/${ENV_PREFIX}_ESID1520_FPLC_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID1520',  'EST_ECRSRVAPC','${DFILP}/${ENV_PREFIX}_ESID1520_ECRSRVAPC_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID1520',  'EST_ECRSRVRPC','${DFILP}/${ENV_PREFIX}_ESID1520_ECRSRVRPC_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID1520',  'EST_ECRSRVACBP','${DFILP}/${ENV_PREFIX}_ESID1520_ECRSRVACBP_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID1520',  'EST_ECRSRVRCBP','${DFILP}/${ENV_PREFIX}_ESID1520_ECRSRVRCBP_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID1520',  'EST_FLIFPLN1','${DFILP}/${ENV_PREFIX}_ESID1520_EST_FLIFPLN1_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID1520',  'EST_FLIFPLN2','${DFILP}/${ENV_PREFIX}_ESID1520_EST_FLIFPLN2_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID1520',  'EST_FLIFPLN3','${DFILP}/${ENV_PREFIX}_ESID1520_EST_FLIFPLN3_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID1520',  'EST_ECRSRVAPC_PA','${DFILP}/${ENV_PREFIX}_ESID1520_ECRSRVAPC_PA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID1520',  'EST_ECRSRVRPC_PA','${DFILP}/${ENV_PREFIX}_ESID1520_ECRSRVRPC_PA_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID1520',  'EST_FLIFPLN1_VENTIL','${DFILP}/${ENV_PREFIX}_ESID1520_FLIFPLN1_VENTIL_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESID1520',  'EST_FLIFPLN3_VENTIL','${DFILP}/${ENV_PREFIX}_ESID1520_FLIFPLN3_VENTIL_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('A',  'ESID1520','')
			insert into BEST..TI17REQFNC values ('I4IMINV',  'ESID1520','')
			insert into BEST..TI17REQFNC values ('I4IQINV',  'ESID1520','@variante')
			insert into BEST..TI17REQFNC values ('I4IYINV',  'ESID1520','@variante')
go

