-------------------------------
--mapping of  ESFD2030

	----------   Clean tables   ---------------------

	delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD2030')
	delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD2030')
	delete BEST..TI17FNC where CHAIN_CT='ESFD2030'
	delete BEST..TI17CHN  where CHAIN_CT='ESFD2030'

	insert into BEST..TI17CHN values ('ESFD2030',  '')

	----------IDF_CT:   ESFD2030 ------------------

		insert into BEST..TI17FNC values ('ESFD2030',' ','ESFD2030',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('ESFD2030',  'EST_SUBTRS','${DFILP}/${ENV_PREFIX}_ESCJ0060_FSUBTRS.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD2030',  'EST_FTRSLNK','${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRSLNK.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD2030',  'EST_FCURQUOT','${DFILP}/${ENV_PREFIX}_ESCJ0060_FCURQUOT.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD2030',  'EST_FTRANSCODE','${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRANSCODE.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD2030',  'EST_LIFEP','${DFILP}/${ENV_PREFIX}_ESCJ0060_LIFEPINV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD2030',  'EST_FFAMCNA','${DFILP}/${ENV_PREFIX}_ESID0060_FFAMCNA_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD2030',  'EST_FACCPAR0','${DFILP}/${ENV_PREFIX}_ESID0060_FACCPAR0_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD2030',  'EST_FCPLACC0','${DFILP}/${ENV_PREFIX}_ESEH1110_FCPLACC0_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD2030',  'EST_FSSDACTR','${DFILP}/${ENV_PREFIX}_ESCJ0060_FSSDACTR_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD2030',  'EST_SUBTRSASSO','${DFILP}/${ENV_PREFIX}_ESCJ0060_FSUBTRSASSO_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD2030',  'EST_SUBTRSBASE','${DFILP}/${ENV_PREFIX}_ESCJ0060_FSUBTRSBASE_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD2030',  'EST_FTRSLNKVRET','${DFILP}/${ENV_PREFIX}_ESCJ0060_FTRSLNKVRET_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD2030',  'EST_FVPLACEMT','${DFILP}/${ENV_PREFIX}_ESFD2070_FVPLACEMT${IT}_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD2030',  'EST_LIFENDCPT','${DFILP}/${ENV_PREFIX}_ESFD2070_LIFENDCPT${IT}_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD2030',  'EST_LIFESTLIB','${DFILP}/${ENV_PREFIX}_ESFD2070_LIFESTLIB${IT}_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD2030',  'EST_IAVPERICASE0','${DFILP}/${ENV_PREFIX}_ESEH1100_IAVPERICASE0_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD2030',  'EST_IRVPERICASE0','${DFILP}/${ENV_PREFIX}_ESID0060_IRVPERICASE0_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD2030',  'EST_FVPLACEMT2','${DFILP}/${ENV_PREFIX}_ESFD2070_FVPLACEMT2${IT}_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD2030',  'EST_LIFESTNOACC','${DFILP}/${ENV_PREFIX}_ESFD2070_LIFESTNOACC${IT}_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD2030',  'EST_SUBTRSESBPROP','${DFILP}/${ENV_PREFIX}_ESCJ0060_FSUBTRSESBPROP_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD2030',  'EST_VLIFEST2070','${DFILP}/${ENV_PREFIX}_ESFD2070_VLIFEST2070${IT}_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD2030',  'EST_310_SORT_GT_O','${DFILP}/${ENV_PREFIX}_ESFD2070_310_SORT_GT${IT}_O_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD2030',  'EST_430_SORT_GT_O','${DFILP}/${ENV_PREFIX}_ESFD2070_430_SORT_GT${IT}_O_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD2030',  'EST_470_SORT_GT_O','${DFILP}/${ENV_PREFIX}_ESFD2070_470_SORT_GT${IT}_O_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD2030',  'EST_IARVPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD2070_IARVPERICASE0${IT}_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD2030',  'EST_IARVPERICASE4','${DFILP}/${ENV_PREFIX}_ESFD2070_IARVPERICASE4${IT}_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD2030',  'EST_160_SORT_CPLACC_O','${DFILP}/${ENV_PREFIX}_ESFD2070_160_SORT_CPLACC${IT}_O_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD2030',  'EST_180_SORT_LSTMTH_O','${DFILP}/${ENV_PREFIX}_ESFD2070_180_SORT_LSTMTH${IT}_O_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD2030',  'EST_ESTC2035_LIFDRI_O1','${DFILP}/${ENV_PREFIX}_ESFD2070_ESTC2035_LIFDRI${IT}_O1_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD2030',  'EST_200_ESTC2034_GTB1_O','${DFILP}/${ENV_PREFIX}_ESFD2070_200_ESTC2034_GTB1${IT}_O_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD2030',  'EST_180_ESTC2040_OLD_LIFEST_O2','${DFILP}/${ENV_PREFIX}_ESFD2070_180_ESTC2040_OLD_LIFEST${IT}_O2_INV_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('ESFD2030',  'EST_SRGTC','${DFILP}/${ENV_PREFIX}_ESFD2030_SRGTC${IT}_INV_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESFD2030',  'EST_SRGTCB1','${DFILP}/${ENV_PREFIX}_ESFD2030_SRGTCB1${IT}_INV_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESFD2030',  'EST_CPLIFDRI','${DFILP}/${ENV_PREFIX}_ESFD2030_CPLIFDRI${IT}_INV_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESFD2030',  'EST_CPLIFEST','${DFILP}/${ENV_PREFIX}_ESFD2030_CPLIFEST${IT}_INV_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESFD2030',  'EST_DLRLIFEI','${DFILP}/${ENV_PREFIX}_ESFD2030_DLRLIFEI${IT}_INV_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESFD2030',  'EST_DLRLIFEP','${DFILP}/${ENV_PREFIX}_ESFD2030_DLRLIFEP${IT}_INV_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESFD2030',  'EST_CPLIFDRIN','${DFILP}/${ENV_PREFIX}_ESFD2030_CPLIFDRIN${IT}_INV_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESFD2030',  'EST_LIFTRANSFR','${DFILP}/${ENV_PREFIX}_ESFD2030_LIFTRANSFR${IT}_INV_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESFD2030',  'EST_VLIFEST195','${DFILP}/${ENV_PREFIX}_ESFD2030_VLIFEST195${IT}_INV_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESFD2030',  'EST_CPLIFDRIASC','${DFILP}/${ENV_PREFIX}_ESFD2030_CPLIFDRIASC${IT}_INV_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESFD2030',  'EST_CPLIFEST_MVT','${DFILP}/${ENV_PREFIX}_ESFD2030_CPLIFEST_MVT${IT}_INV_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('ESFD2030',  'EST_205_ESTC2040_OLD_LIFEST_O2','${DFILP}/${ENV_PREFIX}_ESFD2030_205_ESTC2040_OLD_LIFEST_O2${IT}_INV_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I4IMINV',  'ESFD2030','')
			insert into BEST..TI17REQFNC values ('I4IMINVB',  'ESFD2030','')
			insert into BEST..TI17REQFNC values ('I4IQINV',  'ESFD2030','')
			insert into BEST..TI17REQFNC values ('I4IQINVB',  'ESFD2030','')
			insert into BEST..TI17REQFNC values ('I4IYINV',  'ESFD2030','')
			insert into BEST..TI17REQFNC values ('I4IYINVB',  'ESFD2030','')
go

