-------------------------------
--mapping of  ESFD3940

	----------   Clean tables   ---------------------

	delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD3940')
	delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD3940')
	delete BEST..TI17FNC where CHAIN_CT='ESFD3940'
	delete BEST..TI17CHN  where CHAIN_CT='ESFD3940'

	insert into BEST..TI17CHN values ('ESFD3940',  'Granularity products')

	----------IDF_CT:   I17G_GRN_ALL_INI ------------------

		insert into BEST..TI17FNC values ('I17G_GRN_ALL_INI','Granularity products','ESFD3940',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17G_GRN_ALL_INI',  'ESF_FCTRI17PRD','${DFILP}/${ENV_PREFIX}_ESFD0060_I17G____FCTRI17PRD${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GRN_ALL_INI',  'ESF_FI17PRODUCT','${DFILP}/${ENV_PREFIX}_ESFD0060_I17G____FI17PRODUCT${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GRN_ALL_INI',  'ESF_FSECIFRS','${DFILP}/${ENV_PREFIX}_ESFD3720_I17G_CSM_CRE_INI_FSECIFRS${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GRN_ALL_INI',  'ESF_FCTRI17PRD_RET_BR','${DFILP}/${ENV_PREFIX}_ESFD0060_I17G____FCTRI17PRD_RET_BR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GRN_ALL_INI',  'ESF_FCTRI17PRD_RET_INI','${DFILP}/${ENV_PREFIX}_ESFD0060_I17G____FCTRI17PRD_RET_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GRN_ALL_INI',  'ESF_PI_UPDATE_TSECIFRS','${DFILP}/${ENV_PREFIX}_ESFD3860_I17G_PRO_INT_STD_PI_UPDATE_TSECIFRS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_GRN_ALL_INI',  'ESF_FCTRI17PRD_NEW','${DFILP}/${ENV_PREFIX}_ESFD3940_I17G_GRN_ALL_INI_FCTRI17PRD.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_GRN_ALL_INI',  'ESF_FI17PRODUCT_CUR','${DFILP}/${ENV_PREFIX}_ESFD3940_I17G_GRN_ALL_INI_FI17PRODUCT_CUR.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_GRN_ALL_INI',  'ESF_FI17PRODUCT_NEW','${DFILP}/${ENV_PREFIX}_ESFD3940_I17G_GRN_ALL_INI_FI17PRODUCT${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------


	----------IDF_CT:   I17L_GRN_ALL_INI ------------------

		insert into BEST..TI17FNC values ('I17L_GRN_ALL_INI','Granularity products','ESFD3940',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17L_GRN_ALL_INI',  'ESF_FCTRI17PRD','${DFILP}/${ENV_PREFIX}_ESFD0060_I17L____FCTRI17PRD${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GRN_ALL_INI',  'ESF_FI17PRODUCT','${DFILP}/${ENV_PREFIX}_ESFD0060_I17L____FI17PRODUCT${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GRN_ALL_INI',  'ESF_FSECIFRS','${DFILP}/${ENV_PREFIX}_ESFD3720_I17L_CSM_CRE_INI_FSECIFRS${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GRN_ALL_INI',  'ESF_FCTRI17PRD_RET_BR','${DFILP}/${ENV_PREFIX}_ESFD0060_I17L____FCTRI17PRD_RET_BR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GRN_ALL_INI',  'ESF_FCTRI17PRD_RET_INI','${DFILP}/${ENV_PREFIX}_ESFD0060_I17L____FCTRI17PRD_RET_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GRN_ALL_INI',  'ESF_PI_UPDATE_TSECIFRS','${DFILP}/${ENV_PREFIX}_ESFD3860_I17L_PRO_INT_STD_PI_UPDATE_TSECIFRS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_GRN_ALL_INI',  'ESF_FCTRI17PRD_NEW','${DFILP}/${ENV_PREFIX}_ESFD3940_I17L_GRN_ALL_INI_FCTRI17PRD.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_GRN_ALL_INI',  'ESF_FI17PRODUCT_CUR','${DFILP}/${ENV_PREFIX}_ESFD3940_I17L_GRN_ALL_INI_FI17PRODUCT_CUR.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_GRN_ALL_INI',  'ESF_FI17PRODUCT_NEW','${DFILP}/${ENV_PREFIX}_ESFD3940_I17L_GRN_ALL_INI_FI17PRODUCT${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------


	----------IDF_CT:   I17P_GRN_ALL_INI ------------------

		insert into BEST..TI17FNC values ('I17P_GRN_ALL_INI','Granularity products','ESFD3940',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17P_GRN_ALL_INI',  'ESF_FCTRI17PRD','${DFILP}/${ENV_PREFIX}_ESFD0060_I17P____FCTRI17PRD${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GRN_ALL_INI',  'ESF_FI17PRODUCT','${DFILP}/${ENV_PREFIX}_ESFD0060_I17P____FI17PRODUCT${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GRN_ALL_INI',  'ESF_FSECIFRS','${DFILP}/${ENV_PREFIX}_ESFD3720_I17P_CSM_CRE_INI_FSECIFRS${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GRN_ALL_INI',  'ESF_FCTRI17PRD_RET_BR','${DFILP}/${ENV_PREFIX}_ESFD0060_I17P____FCTRI17PRD_RET_BR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GRN_ALL_INI',  'ESF_FCTRI17PRD_RET_INI','${DFILP}/${ENV_PREFIX}_ESFD0060_I17P____FCTRI17PRD_RET_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GRN_ALL_INI',  'ESF_PI_UPDATE_TSECIFRS','${DFILP}/${ENV_PREFIX}_ESFD3860_I17P_PRO_INT_STD_PI_UPDATE_TSECIFRS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_GRN_ALL_INI',  'ESF_FCTRI17PRD_NEW','${DFILP}/${ENV_PREFIX}_ESFD3940_I17P_GRN_ALL_INI_FCTRI17PRD.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_GRN_ALL_INI',  'ESF_FI17PRODUCT_CUR','${DFILP}/${ENV_PREFIX}_ESFD3940_I17P_GRN_ALL_INI_FI17PRODUCT_CUR.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_GRN_ALL_INI',  'ESF_FI17PRODUCT_NEW','${DFILP}/${ENV_PREFIX}_ESFD3940_I17P_GRN_ALL_INI_FI17PRODUCT${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------


	----------IDF_CT:   I17S_GRN_ALL_INI ------------------

		insert into BEST..TI17FNC values ('I17S_GRN_ALL_INI','Granularity products','ESFD3940',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17S_GRN_ALL_INI',  'ESF_FCTRI17PRD','${DFILP}/${ENV_PREFIX}_ESFD0060_I17S____FCTRI17PRD${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GRN_ALL_INI',  'ESF_FI17PRODUCT','${DFILP}/${ENV_PREFIX}_ESFD0060_I17S____FI17PRODUCT${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GRN_ALL_INI',  'ESF_FSECIFRS','${DFILP}/${ENV_PREFIX}_ESFD3720_I17S_CSM_CRE_INI_FSECIFRS${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GRN_ALL_INI',  'ESF_FCTRI17PRD_RET_BR','${DFILP}/${ENV_PREFIX}_ESFD0060_I17S____FCTRI17PRD_RET_BR_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GRN_ALL_INI',  'ESF_FCTRI17PRD_RET_INI','${DFILP}/${ENV_PREFIX}_ESFD0060_I17S____FCTRI17PRD_RET_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GRN_ALL_INI',  'ESF_PI_UPDATE_TSECIFRS','${DFILP}/${ENV_PREFIX}_ESFD3860_I17S_PRO_INT_STD_PI_UPDATE_TSECIFRS_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_GRN_ALL_INI',  'ESF_FCTRI17PRD_NEW','${DFILP}/${ENV_PREFIX}_ESFD3940_I17S_GRN_ALL_INI_FCTRI17PRD.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_GRN_ALL_INI',  'ESF_FI17PRODUCT_CUR','${DFILP}/${ENV_PREFIX}_ESFD3940_I17S_GRN_ALL_INI_FI17PRODUCT_CUR.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_GRN_ALL_INI',  'ESF_FI17PRODUCT_NEW','${DFILP}/${ENV_PREFIX}_ESFD3940_I17S_GRN_ALL_INI_FI17PRODUCT${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

go

