-------------------------------
--mapping of  ESFD8600

	----------   Clean tables   ---------------------

	delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD8600')
	delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD8600')
	delete BEST..TI17FNC where CHAIN_CT='ESFD8600'
	delete BEST..TI17CHN  where CHAIN_CT='ESFD8600'

	insert into BEST..TI17CHN values ('ESFD8600',  'Booking IFRS 17 cashflow and accounting files to infocenter')

	----------IDF_CT:   EBS_OMG_DW_STD ------------------

		insert into BEST..TI17FNC values ('EBS_OMG_DW_STD','specific TNR','ESFD8600',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('EBS_OMG_DW_STD',  'ESF_FTECLEDA_LIF','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_OMG_DW_STD',  'ESF_FTECLEDR_LIF','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_OMG_DW_STD',  'EPO_FTECLEDSII','$DFILP/${ENV_PREFIX}_ESPD3700_FTECLEDSII_EBS_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_OMG_DW_STD',  'EST_FTECLEDASII','${DFILP}/${ENV_PREFIX}_ESPD3970_EBS_MVT_MRG_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_OMG_DW_STD',  'EST_FTECLEDR','$DFILP/${ENV_PREFIX}_ES${PARM_FTECLED}D8700_FTECLEDR_I4I_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_OMG_DW_STD',  'EST_FTECLEDRSII','$DFILP/${ENV_PREFIX}_ESPD3970_FTECLEDR_EBS_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_OMG_DW_STD',  'EST_FTECLEDA_ANNULMVT','${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDASII${TYPEINV}_ANNULMVT${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_OMG_DW_STD',  'EST_FTECLEDR_ANNULMVT','${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDRSII${TYPEINV}_ANNULMVT${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_OMG_DW_STD',  'EPO_GTSII_RISKMARGIN','$DFILP/${ENV_PREFIX}_ESPD3700_SII_RISKMARGIN_EBS_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_OMG_DW_STD',  'ESF_FTECLEDA_I17G','${DFILP}/${ENV_PREFIX}_ESPD3970_I17G_MVT_MRG_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_OMG_DW_STD',  'ESF_FTECLEDA_I17L','${DFILP}/${ENV_PREFIX}_ESPD3970_I17L_MVT_MRG_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_OMG_DW_STD',  'ESF_FTECLEDA_I17P','${DFILP}/${ENV_PREFIX}_ESPD3970_I17P_MVT_MRG_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_OMG_DW_STD',  'ESF_FTECLEDA_I17S','${DFILP}/${ENV_PREFIX}_ESPD3970_I17S_MVT_MRG_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_OMG_DW_STD',  'ESF_FTECLEDR_I17G','$DFILP/${ENV_PREFIX}_ESFD3840_I17G_GLT_MRG_STD_FTECLEDR_MVT_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_OMG_DW_STD',  'ESF_FTECLEDR_I17L','$DFILP/${ENV_PREFIX}_ESFD3840_I17L_GLT_MRG_STD_FTECLEDR_MVT_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_OMG_DW_STD',  'ESF_FTECLEDR_I17P','$DFILP/${ENV_PREFIX}_ESFD3840_I17P_GLT_MRG_STD_FTECLEDR_MVT_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_OMG_DW_STD',  'ESF_FTECLEDR_I17S','$DFILP/${ENV_PREFIX}_ESFD3840_I17S_GLT_MRG_STD_FTECLEDR_MVT_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_OMG_DW_STD',  'ESF_FTECLEDSII_I17G','$DFILP/${ENV_PREFIX}_ESFD3730_FTECLEDSII_I17G_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_OMG_DW_STD',  'ESF_FTECLEDSII_I17L','$DFILP/${ENV_PREFIX}_ESFD3730_FTECLEDSII_I17L_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_OMG_DW_STD',  'ESF_FTECLEDSII_I17P','$DFILP/${ENV_PREFIX}_ESFD3730_FTECLEDSII_I17P_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_OMG_DW_STD',  'ESF_FTECLEDSII_I17S','$DFILP/${ENV_PREFIX}_ESFD3730_FTECLEDSII_I17S_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','I','')
			insert into BEST..TI17PERMFIL values ('EBS_OMG_DW_STD',  'EST_FTECLEDA','`if [ "${param_Context_id}" = "INVE" ];then echo ${DFILP}/${ENV_PREFIX}_ESID8700_FTECLEDA_I4I_INV_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat;else echo ${DFILP}/${ENV_PREFIX}_ESPD8700_FTECLEDA_I4I_POS_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat;fi;`','I','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('EBSEMINV',  'EBS_OMG_DW_STD','')
			insert into BEST..TI17REQFNC values ('EBSEQINV',  'EBS_OMG_DW_STD','')
			insert into BEST..TI17REQFNC values ('EBSEQPOS',  'EBS_OMG_DW_STD','')
			insert into BEST..TI17REQFNC values ('EBSEYINV',  'EBS_OMG_DW_STD','')
			insert into BEST..TI17REQFNC values ('EBSEYPOS',  'EBS_OMG_DW_STD','')
			insert into BEST..TI17REQFNC values ('EBSEQINVB',  'EBS_OMG_DW_STD','')
			insert into BEST..TI17REQFNC values ('EBSEYINVB',  'EBS_OMG_DW_STD','')
			insert into BEST..TI17REQFNC values ('EBSEQPOSB',  'EBS_OMG_DW_STD','')
			insert into BEST..TI17REQFNC values ('EBSEYPOSB',  'EBS_OMG_DW_STD','')
			insert into BEST..TI17REQFNC values ('EBSEQPOSP',  'EBS_OMG_DW_STD','')
			insert into BEST..TI17REQFNC values ('EBSEYPOSP',  'EBS_OMG_DW_STD','')

	----------IDF_CT:   I17G_OMG_DW_STD ------------------

		insert into BEST..TI17FNC values ('I17G_OMG_DW_STD','Booking IFRS17 to infocenter','ESFD8600',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17G_OMG_DW_STD',  'ESF_FTECLEDA_LIF','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_DW_STD',  'ESF_FTECLEDR_LIF','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_DW_STD',  'EPO_FTECLEDSII','$DFILP/${ENV_PREFIX}_ESPD3700_FTECLEDSII_EBS_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_DW_STD',  'EST_FTECLEDASII','${DFILP}/${ENV_PREFIX}_ESPD3970_EBS_MVT_MRG_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_DW_STD',  'EST_FTECLEDR','$DFILP/${ENV_PREFIX}_ES${PARM_FTECLED}D8700_FTECLEDR_I4I_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_DW_STD',  'EST_FTECLEDRSII','$DFILP/${ENV_PREFIX}_ESPD3970_FTECLEDR_EBS_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_DW_STD',  'ESF_FTECLEDR_I17S','$DFILP/${ENV_PREFIX}_ESFD3840_I17S_GLT_MRG_STD_FTECLEDR_MVT_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_DW_STD',  'EST_FTECLEDA_ANNULMVT','${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDASII${TYPEINV}_ANNULMVT${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_DW_STD',  'EST_FTECLEDR_ANNULMVT','${DFILP}/${ENV_PREFIX}_ESPD3800_FTECLEDRSII${TYPEINV}_ANNULMVT${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_DW_STD',  'EPO_GTSII_RISKMARGIN','$DFILP/${ENV_PREFIX}_ESPD3700_SII_RISKMARGIN_EBS_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_DW_STD',  'ESF_FTECLEDA_I17G','${DFILP}/${ENV_PREFIX}_ESPD3970_I17G_MVT_MRG_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_DW_STD',  'ESF_FTECLEDA_I17L','${DFILP}/${ENV_PREFIX}_ESPD3970_I17L_MVT_MRG_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_DW_STD',  'ESF_FTECLEDA_I17P','${DFILP}/${ENV_PREFIX}_ESPD3970_I17P_MVT_MRG_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_DW_STD',  'ESF_FTECLEDA_I17S','${DFILP}/${ENV_PREFIX}_ESPD3970_I17S_MVT_MRG_STD_FTECLEDA_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_DW_STD',  'ESF_FTECLEDR_I17G','$DFILP/${ENV_PREFIX}_ESFD3840_I17G_GLT_MRG_STD_FTECLEDR_MVT_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_DW_STD',  'ESF_FTECLEDR_I17L','$DFILP/${ENV_PREFIX}_ESFD3840_I17L_GLT_MRG_STD_FTECLEDR_MVT_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_DW_STD',  'ESF_FTECLEDR_I17P','$DFILP/${ENV_PREFIX}_ESFD3840_I17P_GLT_MRG_STD_FTECLEDR_MVT_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_DW_STD',  'ESF_FTECLEDSII_I17G','$DFILP/${ENV_PREFIX}_ESFD3730_FTECLEDSII_I17G_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_DW_STD',  'ESF_FTECLEDSII_I17L','$DFILP/${ENV_PREFIX}_ESFD3730_FTECLEDSII_I17L_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_DW_STD',  'ESF_FTECLEDSII_I17P','$DFILP/${ENV_PREFIX}_ESFD3730_FTECLEDSII_I17P_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_DW_STD',  'ESF_FTECLEDSII_I17S','$DFILP/${ENV_PREFIX}_ESFD3730_FTECLEDSII_I17S_${TYPEINV}_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_OMG_DW_STD',  'EST_FTECLEDA','`if [ "${param_Context_id}" = "INVG" ];then echo $DFILP/${ENV_PREFIX}_ESID8700_FTECLEDA_I4I_INV_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat;else echo $DFILP/${ENV_PREFIX}_ESPD8700_FTECLEDA_I4I_POS_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat;fi;`','I','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17GMINV',  'I17G_OMG_DW_STD','')
			insert into BEST..TI17REQFNC values ('I17GQINV',  'I17G_OMG_DW_STD','')
			insert into BEST..TI17REQFNC values ('I17GQINVB',  'I17G_OMG_DW_STD','')
			insert into BEST..TI17REQFNC values ('I17GQPOS',  'I17G_OMG_DW_STD','')
			insert into BEST..TI17REQFNC values ('I17GQPOSB',  'I17G_OMG_DW_STD','')
			insert into BEST..TI17REQFNC values ('I17GYINV',  'I17G_OMG_DW_STD','')
			insert into BEST..TI17REQFNC values ('I17GYINVB',  'I17G_OMG_DW_STD','')
			insert into BEST..TI17REQFNC values ('I17GYPOS',  'I17G_OMG_DW_STD','')
			insert into BEST..TI17REQFNC values ('I17GYPOSB',  'I17G_OMG_DW_STD','')
			insert into BEST..TI17REQFNC values ('I17GQPOSP',  'I17G_OMG_DW_STD','')
			insert into BEST..TI17REQFNC values ('I17GYPOSP',  'I17G_OMG_DW_STD','')
			
------------------------------  EVOL ALIMENTATION TTECLEDA/R POSX ------------------------------------------------

-----  AJOUT IDF_CT :  I17L_OMG_DW_STD / Pour I17 et I17P  --------------------------------------------------

----- PARAMETRES : PARM_PREV_ICLODAT QUI PERMET DE DETERMINER LA SUFFIXE TABLE -----------------------------------

	----------IDF_CT:   I17L_OMG_DW_STD ------------------

		insert into BEST..TI17FNC values ('I17L_OMG_DW_STD','Booking IFRS17 to infocenter','ESFD8600',0)
					

		----------  Perms---------------------



			insert into BEST..TI17PERMFIL values ('I17L_OMG_DW_STD',  'EST_FTECLEDASII','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_OMG_DW_STD',  'EST_FTECLEDR','${DFILP}/empty.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_OMG_DW_STD',  'EST_FTECLEDRSII','${DFILP}/empty.dat','I','')
			
			insert into BEST..TI17PERMFIL values ('I17L_OMG_DW_STD',  'ESF_FTECLEDA_I17L','${DFILP}/${ENV_PREFIX}_ESPD3970_I17L_MVT_MRG_STD_FTECLEDA_POS_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_OMG_DW_STD',  'ESF_FTECLEDA_I17P','${DFILP}/${ENV_PREFIX}_ESPD3970_I17P_MVT_MRG_STD_FTECLEDA_POS_${PARM_ICLODAT_D}.dat','I','')

			insert into BEST..TI17PERMFIL values ('I17L_OMG_DW_STD',  'ESF_FTECLEDR_I17L','$DFILP/${ENV_PREFIX}_ESFD3840_I17L_GLT_MRG_STD_FTECLEDR_MVT_POS_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_OMG_DW_STD',  'ESF_FTECLEDR_I17P','$DFILP/${ENV_PREFIX}_ESFD3840_I17P_GLT_MRG_STD_FTECLEDR_MVT_POS_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','I','')

			insert into BEST..TI17PERMFIL values ('I17L_OMG_DW_STD',  'ESF_FTECLEDSII_I17L','$DFILP/${ENV_PREFIX}_ESFD3730_FTECLEDSII_I17L_POS_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_OMG_DW_STD',  'ESF_FTECLEDSII_I17P','$DFILP/${ENV_PREFIX}_ESFD3730_FTECLEDSII_I17P_POS_${PARM_ICLODAT_D}_${PARAM_LOCALSIT}.dat','I','')


		----------   Reqs    ---------------------
		
			insert into BEST..TI17REQFNC values ('I17LQPOSX',  'I17L_OMG_DW_STD','')
			insert into BEST..TI17REQFNC values ('I17LYPOSX',  'I17L_OMG_DW_STD','')			
			
go

