-------------------------------
--mapping of  ESFD5020

	----------   Clean tables   ---------------------

	delete BEST..TI17PERMFIL where IDF_CT in  ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD5020')
	delete BEST..TI17REQFNC where     IDF_CT  in ( select IDF_CT from BEST..TI17FNC where   CHAIN_CT='ESFD5020')
	delete BEST..TI17FNC where CHAIN_CT='ESFD5020'
	delete BEST..TI17CHN  where CHAIN_CT='ESFD5020'

	insert into BEST..TI17CHN values ('ESFD5020',  'IFRS17 IADPericase Generation')

	----------IDF_CT:   I17G_EXT_PER_INI ------------------

		insert into BEST..TI17FNC values ('I17G_EXT_PER_INI','Group - INI IFRS17 IADPericase Generation','ESFD5020',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17G_EXT_PER_INI',  'ESF_FI17CLOPER','${DFILP}/${ENV_PREFIX}_ESFD1130_FI17CLOPER_I17G_DSC_ALL_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_EXT_PER_INI',  'EST_IADPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5040_I17G_MRG_FUT_INI_IADPERICASE_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_EXT_PER_INI',  'EST_IRDPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5010_I17G_MRG_PER_INI_IRDPERICASE_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_EXT_PER_INI',  'EST_IADPERICASE0_INI','${DFILP}/${ENV_PREFIX}_ESFD5010_I17G_MRG_PER_INI_IADPERICASE0_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_EXT_PER_INI',  'ESF_SECIFRS_CR_EXTRACT','${DFILP}/${ENV_PREFIX}_ESFD1130_SECIFRS_CR_EXTRACT_I17G_DSC_ALL_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_EXT_PER_INI',  'EST_IADPERICASE_DUMMY','${DFILP}/${ENV_PREFIX}_ESFD5010_I17G_MRG_PER_INI_IADPERICASE_DUMMY_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_EXT_PER_INI',  'EST_IADPERICASE_I17','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17G_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_EXT_PER_INI',  'EST_IRDPERICASE_I17','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE_I17G_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_EXT_PER_INI',  'EST_IADVPERICASE_P_INI','${DFILP}/${ENV_PREFIX}_ESFD5020_IADVPERICASE_P_I17G_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_EXT_PER_INI',  'EST_IRDPERICASE_I17_NP','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE_NP_I17G_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_EXT_PER_INI',  'EST_IADPERICASE_DUMMY_I17','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_DUMMY_I17G_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17GMINV',  'I17G_EXT_PER_INI','')
			insert into BEST..TI17REQFNC values ('I17GQINV',  'I17G_EXT_PER_INI','')
			insert into BEST..TI17REQFNC values ('I17GQPOS',  'I17G_EXT_PER_INI','')
			insert into BEST..TI17REQFNC values ('I17GYINV',  'I17G_EXT_PER_INI','')
			insert into BEST..TI17REQFNC values ('I17GYPOS',  'I17G_EXT_PER_INI','')

	----------IDF_CT:   I17G_EXT_PER_STD ------------------

		insert into BEST..TI17FNC values ('I17G_EXT_PER_STD','Group - STD IFRS17 IADPericase Generation','ESFD5020',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17G_EXT_PER_STD',  'EST_IRDPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5010_IRDPERICASE0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_EXT_PER_STD',  'EST_IADPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5040_IADPERICASE_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_EXT_PER_STD',  'EST_OIRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5010_OIRDVPERICASE_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_EXT_PER_STD',  'ESF_FI17CLOPER','${DFILP}/${ENV_PREFIX}_ESFD1130_FI17CLOPER_I17G_DSC_ALL_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_EXT_PER_STD',  'EST_IADPERICASE_DUMMY','${DFILP}/${ENV_PREFIX}_ESFD5010_IADPERICASE_DUMMY_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_EXT_PER_STD',  'ESF_SECIFRS_CR_EXTRACT','${DFILP}/${ENV_PREFIX}_ESFD1130_SECIFRS_CR_EXTRACT_I17G_DSC_ALL_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17G_EXT_PER_STD',  'ESF_IADPERICASE_I17_INI','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17G_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')				
			insert into BEST..TI17PERMFIL values ('I17G_EXT_PER_STD',  'EST_IRDPERICASE0_I17','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE0_I17G_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_EXT_PER_STD',  'EST_IADPERICASE_I17','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17G_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_EXT_PER_STD',  'EST_OIRDVPERICASE_I17','${DFILP}/${ENV_PREFIX}_ESFD5020_OIRDVPERICASE_I17G_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17G_EXT_PER_STD',  'EST_IADPERICASE_DUMMY_I17','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_DUMMY_I17G_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')		
			insert into BEST..TI17PERMFIL values ('I17G_EXT_PER_STD',  'ESF_IADPERICASE_I17_MERGE','${DFILP}/${ENV_PREFIX}_ESFD5020_I17G_EXT_PER_STD_IADPERICASE_MERGE_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')	

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17GQINV',  'I17G_EXT_PER_STD','')
			insert into BEST..TI17REQFNC values ('I17GQPOS',  'I17G_EXT_PER_STD','')
			insert into BEST..TI17REQFNC values ('I17GYINV',  'I17G_EXT_PER_STD','')
			insert into BEST..TI17REQFNC values ('I17GYPOS',  'I17G_EXT_PER_STD','')
			insert into BEST..TI17REQFNC values ('I17GMINV',  'I17G_EXT_PER_STD','')

	----------IDF_CT:   I17L_EXT_PER_INI ------------------

		insert into BEST..TI17FNC values ('I17L_EXT_PER_INI','Local - INI IADPericase Generation','ESFD5020',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17L_EXT_PER_INI',  'EST_IADPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5040_I17L_MRG_FUT_INI_IADPERICASE_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_EXT_PER_INI',  'EST_IRDPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5010_I17L_MRG_PER_INI_IRDPERICASE_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_EXT_PER_INI',  'ESF_FI17CLOPER','${DFILP}/${ENV_PREFIX}_ESFD1130_FI17CLOPER_I17L_DSC_ALL_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_EXT_PER_INI',  'EST_IADPERICASE0_INI','${DFILP}/${ENV_PREFIX}_ESFD5010_I17L_MRG_PER_INI_IADPERICASE0_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_EXT_PER_INI',  'ESF_SECIFRS_CR_EXTRACT','${DFILP}/${ENV_PREFIX}_ESFD1130_SECIFRS_CR_EXTRACT_I17L_DSC_ALL_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_EXT_PER_INI',  'EST_IADPERICASE_DUMMY','${DFILP}/${ENV_PREFIX}_ESFD5010_I17L_MRG_PER_INI_IADPERICASE_DUMMY_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_EXT_PER_INI',  'EST_IADPERICASE_I17','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17L_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_EXT_PER_INI',  'EST_IRDPERICASE_I17','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE_I17L_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_EXT_PER_INI',  'EST_IADVPERICASE_P_INI','${DFILP}/${ENV_PREFIX}_ESFD5020_IADVPERICASE_P_I17L_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_EXT_PER_INI',  'EST_IRDPERICASE_I17_NP','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE_NP_I17L_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_EXT_PER_INI',  'EST_IADPERICASE_DUMMY_I17','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_DUMMY_I17L_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17LYPOS',  'I17L_EXT_PER_INI','')
			insert into BEST..TI17REQFNC values ('I17LMINV',  'I17L_EXT_PER_INI','')
			insert into BEST..TI17REQFNC values ('I17LQINV',  'I17L_EXT_PER_INI','')
			insert into BEST..TI17REQFNC values ('I17LQPOS',  'I17L_EXT_PER_INI','')
			insert into BEST..TI17REQFNC values ('I17LYINV',  'I17L_EXT_PER_INI','')

	----------IDF_CT:   I17L_EXT_PER_STD ------------------

		insert into BEST..TI17FNC values ('I17L_EXT_PER_STD','Local - STD IADPericase Generation','ESFD5020',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17L_EXT_PER_STD',  'EST_IRDPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5010_IRDPERICASE0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_EXT_PER_STD',  'EST_IADPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5040_IADPERICASE_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_EXT_PER_STD',  'EST_OIRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5010_OIRDVPERICASE_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_EXT_PER_STD',  'EST_IADPERICASE_DUMMY','${DFILP}/${ENV_PREFIX}_ESFD5010_IADPERICASE_DUMMY_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_EXT_PER_STD',  'ESF_FI17CLOPER','${DFILP}/${ENV_PREFIX}_ESFD1130_FI17CLOPER_I17L_DSC_ALL_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_EXT_PER_STD',  'ESF_SECIFRS_CR_EXTRACT','${DFILP}/${ENV_PREFIX}_ESFD1130_SECIFRS_CR_EXTRACT_I17L_DSC_ALL_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17L_EXT_PER_STD',  'ESF_IADPERICASE_I17_INI','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17L_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')			
			insert into BEST..TI17PERMFIL values ('I17L_EXT_PER_STD',  'EST_IRDPERICASE0_I17','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE0_I17L_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_EXT_PER_STD',  'EST_IADPERICASE_I17','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17L_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_EXT_PER_STD',  'EST_OIRDVPERICASE_I17','${DFILP}/${ENV_PREFIX}_ESFD5020_OIRDVPERICASE_I17L_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17L_EXT_PER_STD',  'EST_IADPERICASE_DUMMY_I17','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_DUMMY_I17L_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')			
			insert into BEST..TI17PERMFIL values ('I17L_EXT_PER_STD',  'ESF_IADPERICASE_I17_MERGE','${DFILP}/${ENV_PREFIX}_ESFD5020_I17L_EXT_PER_STD_IADPERICASE_MERGE_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')	
		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17LMINV',  'I17L_EXT_PER_STD','')
			insert into BEST..TI17REQFNC values ('I17LQINV',  'I17L_EXT_PER_STD','')
			insert into BEST..TI17REQFNC values ('I17LQPOS',  'I17L_EXT_PER_STD','')
			insert into BEST..TI17REQFNC values ('I17LYINV',  'I17L_EXT_PER_STD','')
			insert into BEST..TI17REQFNC values ('I17LYPOS',  'I17L_EXT_PER_STD','')
			insert into BEST..TI17REQFNC values ('I17LQPOSX',  'I17L_EXT_PER_STD','')
			insert into BEST..TI17REQFNC values ('I17LYPOSX',  'I17L_EXT_PER_STD','')

	----------IDF_CT:   I17P_EXT_PER_INI ------------------

		insert into BEST..TI17FNC values ('I17P_EXT_PER_INI','Parent - INI IADPericase Generation','ESFD5020',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17P_EXT_PER_INI',  'EST_IADPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5040_I17P_MRG_FUT_INI_IADPERICASE_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_EXT_PER_INI',  'EST_IRDPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5010_I17P_MRG_PER_INI_IRDPERICASE_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_EXT_PER_INI',  'ESF_FI17CLOPER','${DFILP}/${ENV_PREFIX}_ESFD1130_FI17CLOPER_I17P_DSC_ALL_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_EXT_PER_INI',  'EST_IADPERICASE0_INI','${DFILP}/${ENV_PREFIX}_ESFD5010_I17P_MRG_PER_INI_IADPERICASE0_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_EXT_PER_INI',  'ESF_SECIFRS_CR_EXTRACT','${DFILP}/${ENV_PREFIX}_ESFD1130_SECIFRS_CR_EXTRACT_I17P_DSC_ALL_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_EXT_PER_INI',  'EST_IADPERICASE_DUMMY','${DFILP}/${ENV_PREFIX}_ESFD5010_I17P_MRG_PER_INI_IADPERICASE_DUMMY_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_EXT_PER_INI',  'EST_IADPERICASE_I17','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17P_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_EXT_PER_INI',  'EST_IRDPERICASE_I17','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE_I17P_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_EXT_PER_INI',  'EST_IADVPERICASE_P_INI','${DFILP}/${ENV_PREFIX}_ESFD5020_IADVPERICASE_P_I17P_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_EXT_PER_INI',  'EST_IRDPERICASE_I17_NP','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE_NP_I17P_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_EXT_PER_INI',  'EST_IADPERICASE_DUMMY_I17','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_DUMMY_I17P_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17PYINV',  'I17P_EXT_PER_INI','')
			insert into BEST..TI17REQFNC values ('I17PYPOS',  'I17P_EXT_PER_INI','')
			insert into BEST..TI17REQFNC values ('I17PMINV',  'I17P_EXT_PER_INI','')
			insert into BEST..TI17REQFNC values ('I17PQINV',  'I17P_EXT_PER_INI','')
			insert into BEST..TI17REQFNC values ('I17PQPOS',  'I17P_EXT_PER_INI','')

	----------IDF_CT:   I17P_EXT_PER_STD ------------------

		insert into BEST..TI17FNC values ('I17P_EXT_PER_STD','Parent - STD IADPericase Generation','ESFD5020',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17P_EXT_PER_STD',  'EST_IRDPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5010_IRDPERICASE0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_EXT_PER_STD',  'EST_IADPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5040_IADPERICASE_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_EXT_PER_STD',  'EST_OIRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5010_OIRDVPERICASE_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_EXT_PER_STD',  'EST_IADPERICASE_DUMMY','${DFILP}/${ENV_PREFIX}_ESFD5010_IADPERICASE_DUMMY_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_EXT_PER_STD',  'ESF_FI17CLOPER','${DFILP}/${ENV_PREFIX}_ESFD1130_FI17CLOPER_I17P_DSC_ALL_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_EXT_PER_STD',  'ESF_SECIFRS_CR_EXTRACT','${DFILP}/${ENV_PREFIX}_ESFD1130_SECIFRS_CR_EXTRACT_I17P_DSC_ALL_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17P_EXT_PER_STD',  'ESF_IADPERICASE_I17_INI','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17P_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')				
			insert into BEST..TI17PERMFIL values ('I17P_EXT_PER_STD',  'EST_IRDPERICASE0_I17','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE0_I17P_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_EXT_PER_STD',  'EST_IADPERICASE_I17','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17P_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_EXT_PER_STD',  'EST_OIRDVPERICASE_I17','${DFILP}/${ENV_PREFIX}_ESFD5020_OIRDVPERICASE_I17P_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17P_EXT_PER_STD',  'EST_IADPERICASE_DUMMY_I17','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_DUMMY_I17P_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')			
			insert into BEST..TI17PERMFIL values ('I17P_EXT_PER_STD',  'ESF_IADPERICASE_I17_MERGE','${DFILP}/${ENV_PREFIX}_ESFD5020_I17P_EXT_PER_STD_IADPERICASE_MERGE_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')	

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17PMINV',  'I17P_EXT_PER_STD','')
			insert into BEST..TI17REQFNC values ('I17PQINV',  'I17P_EXT_PER_STD','')
			insert into BEST..TI17REQFNC values ('I17PQPOS',  'I17P_EXT_PER_STD','')
			insert into BEST..TI17REQFNC values ('I17PYINV',  'I17P_EXT_PER_STD','')
			insert into BEST..TI17REQFNC values ('I17PYPOS',  'I17P_EXT_PER_STD','')
			insert into BEST..TI17REQFNC values ('I17PQPOSX',  'I17P_EXT_PER_STD','')
			insert into BEST..TI17REQFNC values ('I17PYPOSX',  'I17P_EXT_PER_STD','')

	----------IDF_CT:   I17S_EXT_PER_INI ------------------

		insert into BEST..TI17FNC values ('I17S_EXT_PER_INI','Simulation - INI IFRS17 IADPericase Generation','ESFD5020',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17S_EXT_PER_INI',  'ESF_FI17CLOPER','${DFILP}/${ENV_PREFIX}_ESFD1130_FI17CLOPER_I17S_DSC_ALL_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_EXT_PER_INI',  'EST_IADPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5040_I17G_MRG_FUT_INI_IADPERICASE_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_EXT_PER_INI',  'EST_IRDPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5010_I17G_MRG_PER_INI_IRDPERICASE_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_EXT_PER_INI',  'EST_IADPERICASE0_INI','${DFILP}/${ENV_PREFIX}_ESFD5010_I17G_MRG_PER_INI_IADPERICASE0_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_EXT_PER_INI',  'ESF_SECIFRS_CR_EXTRACT','${DFILP}/${ENV_PREFIX}_ESFD1130_SECIFRS_CR_EXTRACT_I17S_DSC_ALL_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_EXT_PER_INI',  'EST_IADPERICASE_DUMMY','${DFILP}/${ENV_PREFIX}_ESFD5010_I17G_MRG_PER_INI_IADPERICASE_DUMMY_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_EXT_PER_INI',  'EST_IADPERICASE_I17','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17S_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_EXT_PER_INI',  'EST_IRDPERICASE_I17','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE_I17S_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_EXT_PER_INI',  'EST_IADVPERICASE_P_INI','${DFILP}/${ENV_PREFIX}_ESFD5020_IADVPERICASE_P_I17S_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_EXT_PER_INI',  'EST_IRDPERICASE_I17_NP','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE_NP_I17S_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_EXT_PER_INI',  'EST_IADPERICASE_DUMMY_I17','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_DUMMY_I17S_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')

		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17SMINV',  'I17S_EXT_PER_INI','')
			insert into BEST..TI17REQFNC values ('I17SQINV',  'I17S_EXT_PER_INI','')
			insert into BEST..TI17REQFNC values ('I17SQPOS',  'I17S_EXT_PER_INI','')
			insert into BEST..TI17REQFNC values ('I17SYINV',  'I17S_EXT_PER_INI','')
			insert into BEST..TI17REQFNC values ('I17SYPOS',  'I17S_EXT_PER_INI','')

	----------IDF_CT:   I17S_EXT_PER_STD ------------------

		insert into BEST..TI17FNC values ('I17S_EXT_PER_STD','Simulation - STD IFRS17 IADPericase Generation','ESFD5020',0)
					

		----------  Perms---------------------

			insert into BEST..TI17PERMFIL values ('I17S_EXT_PER_STD',  'EST_IRDPERICASE0','${DFILP}/${ENV_PREFIX}_ESFD5010_IRDPERICASE0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_EXT_PER_STD',  'EST_IADPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5040_IADPERICASE_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_EXT_PER_STD',  'EST_OIRDVPERICASE','${DFILP}/${ENV_PREFIX}_ESFD5010_OIRDVPERICASE_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_EXT_PER_STD',  'ESF_FI17CLOPER','${DFILP}/${ENV_PREFIX}_ESFD1130_FI17CLOPER_I17S_DSC_ALL_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_EXT_PER_STD',  'EST_IADPERICASE_DUMMY','${DFILP}/${ENV_PREFIX}_ESFD5010_IADPERICASE_DUMMY_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_EXT_PER_STD',  'ESF_SECIFRS_CR_EXTRACT','${DFILP}/${ENV_PREFIX}_ESFD1130_SECIFRS_CR_EXTRACT_I17S_DSC_ALL_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')
			insert into BEST..TI17PERMFIL values ('I17S_EXT_PER_STD',  'ESF_IADPERICASE_I17_INI','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17S_INI_${TYPEINV}_${PARM_ICLODAT_D}.dat','I','')			
			insert into BEST..TI17PERMFIL values ('I17S_EXT_PER_STD',  'EST_IRDPERICASE0_I17','${DFILP}/${ENV_PREFIX}_ESFD5020_IRDPERICASE0_I17S_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_EXT_PER_STD',  'EST_IADPERICASE_I17','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_I17S_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_EXT_PER_STD',  'EST_OIRDVPERICASE_I17','${DFILP}/${ENV_PREFIX}_ESFD5020_OIRDVPERICASE_I17S_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')
			insert into BEST..TI17PERMFIL values ('I17S_EXT_PER_STD',  'EST_IADPERICASE_DUMMY_I17','${DFILP}/${ENV_PREFIX}_ESFD5020_IADPERICASE_DUMMY_I17S_STD_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')				
			insert into BEST..TI17PERMFIL values ('I17S_EXT_PER_STD',  'ESF_IADPERICASE_I17_MERGE','${DFILP}/${ENV_PREFIX}_ESFD5020_I17S_EXT_PER_STD_IADPERICASE_MERGE_${TYPEINV}_${PARM_ICLODAT_D}.dat','O','')	
		----------   Reqs    ---------------------

			insert into BEST..TI17REQFNC values ('I17SQINV',  'I17S_EXT_PER_STD','')
			insert into BEST..TI17REQFNC values ('I17SQPOS',  'I17S_EXT_PER_STD','')
			insert into BEST..TI17REQFNC values ('I17SYINV',  'I17S_EXT_PER_STD','')
			insert into BEST..TI17REQFNC values ('I17SYPOS',  'I17S_EXT_PER_STD','')
			insert into BEST..TI17REQFNC values ('I17SMINV',  'I17S_EXT_PER_STD','')
go

