use BEST
go

BEGIN TRAN

PRINT 'Select data before insert/update'
select * from BEST..TSEGUWCOLUMN where SGTUWTAB_CF = 'TSEGUWASMSEC' and SGTUWCOL_CF in ('FACADMTYP_B')
select * from BEST..TSEGCRITERIA where SGTCRI_CF  in ('SBS_Indicator')
select * from BEST..TSEGUWTABLE where SGTUWTAB_CF = 'TSEGUWASMSEC'


PRINT 'DELETION IF RECORD EXISTS for criteria and column'
DELETE FROM BEST..TSEGCRITERIA where SGTCRI_CF in ('SBS_Indicator')
select @@rowcount, 'rows deleted'

DELETE FROM  BEST..TSEGUWCOLUMN where SGTUWTAB_CF = 'TSEGUWASMSEC' and SGTUWCOL_CF in ('FACADMTYP_B')
select @@rowcount, 'rows deleted'


INSERT INTO BEST..TSEGUWCOLUMN ( SGTUWTAB_CF, SGTUWCOL_CF, SGTUWCOL_LS, SGTUWTYP_CT, SGTUWORDER_NB, SGTUWLEN_NB, SGTUWSCA_NB, SGTUWPRE_NB, CRE_D, CREUSR_CF, LSTUPD_D, LSTUPDUSR_CF ) 
	VALUES ( 'TSEGUWASMSEC', 'FACADMTYP_B', 'SBS_Indicator', 'bit', 195, NULL, NULL, NULL, getdate(), 'UBEU', getdate(), 'UBEU' )

INSERT INTO BEST..TSEGCRITERIA ( SGTCRI_CF, SGTCRISUBCAT_NT, SGTUWCOL_CF, SGTCRI_LS, SGTCRITYP_CT, SGTCRICTL_CT, SGTCRIPAR_LS, CRE_D, CREUSR_CF, LSTUPD_D, LSTUPDUSR_CF) 
	VALUES ( 'SBS_Indicator', 11, 'FACADMTYP_B', 'SBS Flag? (Y/N)', '3', '1', NULL, GETDATE (), 'UBEU', GETDATE (), 'UBEU')


update BEST..TSEGUWTABLE set LSTUPD_D = getDate(), LSTUPDUSR_CF = suser_name(), SGTRQST_T = 'SELECT TCONTR.CTR_NF as CTR_NF, TCONTR.UWY_NF as UWY_NF, TSECTION.UW_NT as UW_NT, 
TCONTR.END_NT as END_NT, 
TSECTION.SEC_NF as SEC_NF, 
CASE WHEN TCONTR.LSTUPD_D > TSECTION.LSTUPD_D AND TCONTR.LSTUPD_D > TDIVISIO.LSTUPD_D THEN TCONTR.LSTUPD_D WHEN TSECTION.LSTUPD_D > 
TDIVISIO.LSTUPD_D THEN TSECTION.LSTUPD_D ELSE TDIVISIO.LSTUPD_D END as UWLSTUPD_D, 
TCONTR.SSD_CF as SSD_CF, TCONTR.ACCESB_CF as ACCESB_CF, TSECTION.NAT_CF as NAT_CF, TCONTR.CTRSTS_CT as CTRSTS_CT, TCONTR.CTRTYP_CT as CTRTYP_CT, TSECTION.SECSTS_CT as SECSTS_CT, 
TSECTION.SECACCSTS_CT as SECACCSTS_CT, TCONTR.LSTEND_B as LSTEND_B, TCONTR.LSTUWY_B as LSTUWY_B, TCLIENT_CED.CLISSD_CF as CLISSD_CF, TSECTION.ACCADMTYP_CT as ACCADMTYP_CT, 
TCONTR.ACCGRP_CF as ACCGRP_CF, TDIVISIO.ACCLIA_M as ACCLIA_M, TCONTR.ADMGRP_CF as ADMGRP_CF, TCONTR.ALLTRT_B as ALLTRT_B, TCLSTABI_CED.AMBCURRAT_CT as AMBCURRAT_CT, 
TSECTION.ANLCTY_CF as ANLCTY_CF, TSECTION.ASSFINANCE_CT as ASSFINANCE_CT, TCONTR.BOQ_NF as BOQ_NF, TCONTR.CAT_B as CAT_B, 0 as CATCNDEXI_B, null as CATRSKTYP_CT, 
TCONTR.CED_NF as CED_NF, TCLIENT_CED.CLIACT_CF as CLIACT_CF, TCLIENT_CED.CLICTY_CF as CLICTY_CF, TCLIENT_CED.CLINAT_CF as CLINAT_CF, TCLIENT_CED.CLISTS_CT as CLISTS_CT, 
TCLIENT_CED.CLISUPIND_B as CLISUPIND_B, TCLIENT_CED.CLITYP_CF as CLITYP_CF, TSECTION.CLMATTTYP_CT as CLMATTTYP_CT, TSECTION.CLMCUTOFF_B as CLMCUTOFF_B, 
TSECTION.CLMRUNOFF_B as CLMRUNOFF_B, TCONTR.CNATYP_CT as CNATYP_CT, TCONTR.CTRACC_D as CTRACC_D, TCONTR.CTRACCSTS_CT as CTRACCSTS_CT, 
dateadd(dd,datediff( dd, "19000101", Isnull(TCONTR.SCOEXP_D, TCONTR.CTREXP_D)),"19000101") as CTREXP_D, TCONTR.CTRINC_D as CTRINC_D, 
TCONTR.CTROLDNBR_LM as CTROLDNBR_LM, substring(ctroldnbr_lm,1,5) as CTROLDNBR_LS, "F" as CTRNAT_CT, TCONTR.CTRQUA_CF as CTRQUA_CF, TCONTR.CTRQUA10_CF as CTRQUA10_CF, 
TCONTR.CTRQUA2_CF as CTRQUA2_CF, TCONTR.CTRQUA3_CF as CTRQUA3_CF, TCONTR.CTRQUA4_CF as CTRQUA4_CF, TCONTR.CTRQUA5_CF as CTRQUA5_CF, TCONTR.CTRQUA6_CF as CTRQUA6_CF, 
TCONTR.CTRQUA7_CF as CTRQUA7_CF, TCONTR.CTRQUA8_CF as CTRQUA8_CF, TCONTR.CTRQUA9_CF as CTRQUA9_CF, TCONTR.CTRSTS_D as CTRSTS_D, TFAMLIA.CUTSHA_R as CUTSHA_R, 
TDIVISIO.DIV_NT as DIV_NT, TDIVISIO.LOB_CF as DIVLOB_CF, TSECTION.EAREXP_B as EAREXP_B, TFAMLIA.EGPCUR_CF as EGPCUR_CF, 
TCONTR.ENDINC_D as ENDINC_D, isnull(TCONTR.ESTCRB_CT, "O") as ESTCRB_CT, TSECTION.ESTCTR_NF as ESTCTR_NF, TCONTR.FACACTSCT_CT as FACACTSCT_CT, 
CASE WHEN TCONTR.CTRTYP_CT = 1 AND TGRP2.FACADMTYP_B = NULL or TGRP2.FACADMTYP_B = 2 THEN 0 WHEN TCONTR.CTRTYP_CT = 1 AND TGRP2.FACADMTYP_B <> NULL THEN TGRP2.FACADMTYP_B 
WHEN TCONTR.SSD_CF = 13 AND TCONTR.CTRTYP_CT = 2 THEN 1 ELSE TCONTR.FACADMTYP_B END as FACADMTYP_CT, 0 as FLOCNDEXI_B, TCONTR.FRSINC_D as FRSINC_D, TCONTR.FRSUWY_NF as FRSUWY_NF, 
TCONTR.GANPAYORD_NT as GANPAYORD_NT, TSECTION.GAR_CF as GAR_CF, TCONTR.GENPRMPAY_NF as GENPRMPAY_NF, null as GRPSTS_CT, CASE WHEN TCLIENT_IND.CLI_NF = 0 THEN 999 ELSE 
TCLIENT_IND.HINDNBR_NT END as HINDNBR_NT, TCLIENT_CED.HLD_NF as HLD_NF, THOLDING_CED.HLDCTY_CF as HLDCTY_CF, TREPCRI_IND.HORDGRP_NT as HORDGRP_NT, TFAMLIA.INDAMT_M as INDAMT_M, 
TCLIENT_IND.HLD_NF as INDHLD_NF, CASE WHEN isnull(TCONTR.PRD_NF,0)=0 THEN 0 ELSE 1 END as INT_B, TCLSTABI_CED.ISICURRAT_CT as ISICURRAT_CT, TFAMLIA.LAYCAP_M as LAYCAP_M, 
TCONTR.LDISCO_B as LDISCO_B, TFAMLIA.LIACUR_CF as LIACUR_CF, TSECTION.LIAEVT_B as LIAEVT_B, TSECTION.LIARSK_B as LIARSK_B, TCONTR.LIFTRTTYP_CF as LIFTRTTYP_CF, 
TSECTION.LOB_CF as LOB_CF, 0 as LOSCOREXI_B, 0 as LOSCTBEXI_B, TCONTR.LSTUWYRSK_B as LSTUWYRSK_B, 0 as MULPRG_B, CASE WHEN TSECTION.NAT_CF in ("30","31","32","40","41") 
THEN "N" ELSE "P" END as NAT_B, TSECTION.OCC_CF as OCC_CF, isnull(isnull(TCONTR.ORGCED_NF, TCONTR.CED_NF),0) as ORGCED_NF, TSECTION.PCPCUR_CF as PCPCUR_CF, 
TCONTR.PCPEXTREF_LL as PCPEXTREF_LL, TCONTR.PCPIND_NF as PCPIND_NF, TCONTR.PCPLOB_CF as PCPLOB_CF, TSECTION.PCPRSKTRY_CF as PCPRSKTRY_CF, TCONTR.PCPTOP_CF as PCPTOP_CF, 
TCONTR.PRD_NF as PRD_NF, TSOBBLOB.PRDCOD_CT as PRDCOD_CT, 0 as PRFCOMEXI_B, TCONTR.PRG_NF as PRG_NF, null as PRGNATFAM_CT, TSECTION.PRMCUTOFF_B as PRMCUTOFF_B, 
TSECTION.PRMRUNOFF_B as PRMRUNOFF_B, case when TDIVISIO.refsec_nf = TSECTION.sec_nf and TSECTION.lstend_b = 1 and TSTASTAQUOT1.EXC_R != 0 then 
(TFAMLIA.prtcos_m*TSTASTAQUOT2.EXC_R)/TSTASTAQUOT1.EXC_R else 0 end as PRTCOS_M, TCONTR.REITYP_CF as REITYP_CF, TCONTR.REN_B as REN_B, TCONTR.RSKCOMPRM_B as RSKCOMPRM_B, 
TOCC.RSKNATFAM_CF as RSKNATFAM_CF, TFAMLIA.SCOGLOEGP_M as SCOGLOEGP_M, null as SCOINC_D, TFAMLIA.SCOLIA_M as SCOLIA_M, TFAMLIA.SCOLIALIM_M as SCOLIALIM_M, 
TFAMLIA.SCOORGEGP_M as SCOORGEGP_M, TFAMLIA.SCOPML_M as SCOPML_M, TSECTION.SECACCSTS2_CT as SECACCSTS2_CT, TSECTION.SECCAN_D as SECCAN_D, null as SECINC_D, 
TSECTION.SECQUA_CF as SECQUA_CF, TSECTION.SECQUA10_CF as SECQUA10_CF, TSECTION.SECQUA2_CF as SECQUA2_CF, TSECTION.SECQUA3_CF as SECQUA3_CF, TSECTION.SECQUA4_CF as SECQUA4_CF, 
TSECTION.SECQUA5_CF as SECQUA5_CF, TSECTION.SECQUA6_CF as SECQUA6_CF, TSECTION.SECQUA7_CF as SECQUA7_CF, TSECTION.SECQUA8_CF as SECQUA8_CF, TSECTION.SECQUA9_CF as SECQUA9_CF, 
TFAMLIA.SIGSHA_R as SIGSHA_R, TSECTION.SOB_CF as SOB_CF, TCLINTSU_CED.SORDNBR_NT as SORDNBR_NT, TCLSTABI_CED.SPCURRAT_CT as SPCURRAT_CT, right(replicate("0", 2) + 
convert(varchar,TCONTR.ssd_cf), 2) + "-" + right(replicate("0", 2) + convert(varchar,TCONTR.accesb_cf), 2) as SSD_ESB, 0 as STOCNDEXI_B, TSECTION.SUBNAT_CF as SUBNAT_CF, 
CASE WHEN TSECTION.LOB_CF in ("30","31") then "L" ELSE "F" END as TFL_IND, null as EDI_CALC, null as CAT_RISK_COVERED_CALC, CASE WHEN TCONTR.CTR_NF is not null and 
TCONTR.CTR_NF <> "        " THEN CASE WHEN TCONTR.FACADMTYP_B = 0 THEN "BS" ELSE "Specialties" END ELSE null END as SBS_ADMIN_CALC, isnull(TACCLIA.MPLSCEAMT_M,0) + 
isnull(TACCLIA.OTHPARAMT_M,0) as GAL_CONSO_CALC, TACCLIA.ACCLIA_M - isnull( TACCLIA.CBIAMT_M,0) as GAL_RETRO_CALC, TFAMLIA.CUTSHA_R * TFAMLIA.RIDSHA_R * 100 as 
SCOR_SHARE_ORG_CALC, isnull(TACCLIA.CBIAMT_M,0) as GAL_CBI_CALC, isnull(TACCLIA.JVTAMT_M,0) as GAL_JV_CALC, isnull(TACCLIA.MPLSCEAMT_M,0) as GAL_FAC_IMPACT_CALC, 
isnull(TACCLIA.NGHAMT_M,0) as GAL_NEIGHBORHOOD_CALC, isnull(TACCLIA.OTHLOBAMT_M,0) as GAL_OTHER_LOB_CALC, isnull(TACCLIA.OTHPARAMT_M,0) as GAL_OTHER_PART_CALC, 
TFAMLIA.CUTSHA_R * 100 as SCOR_SHARE_CEDED_CALC, TSECTION.RETPCT_R*100 as SEC_RETRO_RATIO_CALC, TFAMLIA.RIDSHA_R * 100 as CEDED_SHARE_CALC, CASE WHEN TCONTR.CED_NF <> 0 THEN 1 
ELSE 0 END as IO_CLIENT_SCOR_CALC, TFAMCHG.CTBGENFEE_R * 100 as COM_PC_EXPENSES_CALC, TFAMCHG.FIXCOM_R * 100 as COM_FIX_CALC, TFAMCHG.LOSCTB_R * 100 as COM_PC_LOSS_CALC, 
TFAMCHG.MAXCOM_R * 100 as COM_VARIABLE_MAX_CALC, TFAMCHG.MAXRATCLP_R * 100 as LR_VARIABLE_MAX_CALC, TFAMCHG.MINCOM_R * 100 as COM_VARIABLE_MIN_CALC, 
TFAMCHG.MINRATCLP_R * 100 as LR_VARIABLE_MIN_CALC, TFAMCHG.OVRCOM_R * 100 as COM_OVERRIDER_CALC, TFAMCHG.PRFCOM_R * 100 as COM_PC_PROFIT_CALC, 
TFAMCHG.PRVCOM_R * 100 as COM_VARIABLE_PROV_CALC, null as COM_VARIABLE_CALC, TFAMLIA.LIAAGRDED_M as AGG_DEDUCTIBLE_CALC, TSECTION.TOP_CF as TOP_CF, 
CASE WHEN TRFCROSSREF.CTR_NF is null then 0 else 1 END as TRFTRT_B, CASE WHEN TCONTR.REITYP_CF = 1 THEN 1 ELSE CASE WHEN TCONTR.REITYP_CF in (null,2,3,4,5,7,10,12) THEN 2 
ELSE CASE WHEN TCONTR.REITYP_CF = 6 THEN 3 ELSE CASE WHEN TCONTR.REITYP_CF = 8 THEN 4 ELSE CASE WHEN TCONTR.REITYP_CF = 9 THEN 5 ELSE CASE WHEN TCONTR.REITYP_CF = 15 THEN 6 
ELSE CASE WHEN TCONTR.REITYP_CF = 16 THEN 7 ELSE CASE WHEN TCONTR.REITYP_CF = 17 THEN 8 ELSE CASE WHEN TCONTR.REITYP_CF = 18 THEN 9 ELSE CASE WHEN TCONTR.REITYP_CF = 19 THEN 10 
ELSE CASE WHEN TCONTR.REITYP_CF = 20 THEN 20 END END END END END END END END END END END as TYPREI_CF, THOLDING_IND.ULT_NF as ULT_NF, TSECTION.USGAAP_CT as USGAAP_CT, 
TSECTION.USRCRTCOD_CT as USRCRTCOD_CT, TSECTION.USRCRTVAL_LM as USRCRTVAL_LM, TCONTR.UWGRP_CF as UWGRP_CF, TCONTR.UWORG_CF as UWORG_CF, TSECTION.WRKCAT_CT as WRKCAT_CT, 
TCLIADDR_CED.CLIADDSTA_CF as CLIADDSTA_CF, TCONTR.PCPSOB_CF as PCPSOB_CF, TCLIENT_CED.HORDNBR_NT AS HORDNBR_NT, TCLIADDR_IND.CLIADDCTY_CF AS INDADDCTY_CF, 
TDIVISIO.PCPRSKTRY_CF AS PCPRSKTRY_DIV_CF, TCONTR.PCPOCC_CF AS PCPOCC_CF, TCONTR.POLDUR_CF AS POLDUR_CF, THOLDING_CED.ULT_NF AS CEDULT_NF, TCONTR.MAS_NF AS MAS_NF , 
TDIVISIO.PCPRSKTRY_CF as PRINCRSKTRY_CF, CASE WHEN TDIVISIO.RETAPPMOD_CT = 1 THEN 1 ELSE 0 END as MANRET_B, TSECTION.STREXP_B as STREXP_B, TSECTION.FLDEXP_B as FLDEXP_B, 
1 as FACADMTYP_B FROM BFAC..TCONTR TCONTR INNER JOIN BREF..TSUBSID TSUBSID ON TSUBSID.SSD_CF = TCONTR.SSD_CF INNER JOIN BFAC..TDIVISIO TDIVISIO ON TDIVISIO.CTR_NF = TCONTR.CTR_NF 
AND TDIVISIO.UWY_NF = TCONTR.UWY_NF AND TDIVISIO.UW_NT = TCONTR.UW_NT AND TDIVISIO.END_NT = TCONTR.END_NT LEFT JOIN BFAC..TACCLIA TACCLIA ON TDIVISIO.CTR_NF = TACCLIA.CTR_NF AND 
TDIVISIO.UWY_NF = TACCLIA.UWY_NF AND TDIVISIO.UW_NT = TACCLIA.UW_NT AND TDIVISIO.DIV_NT = TACCLIA.DIV_NT INNER JOIN BFAC..TSECTION TSECTION ON TSECTION.CTR_NF = TCONTR.CTR_NF AND 
TSECTION.UWY_NF = TCONTR.UWY_NF AND TSECTION.UW_NT = TCONTR.UW_NT AND TSECTION.END_NT = TCONTR.END_NT AND TSECTION.DIV_NT = TDIVISIO.DIV_NT LEFT OUTER JOIN BFAC..TFAMLIA TFAMLIA 
ON TFAMLIA.CTR_NF = TCONTR.CTR_NF AND TFAMLIA.UWY_NF = TCONTR.UWY_NF AND TFAMLIA.UW_NT = TCONTR.UW_NT AND TFAMLIA.END_NT = TCONTR.END_NT AND TFAMLIA.SEC_NF = TSECTION.SEC_NF LEFT 
OUTER JOIN BREF..TSTASTAQUOT TSTASTAQUOT1 ON TFAMLIA.SSD_CF = TSTASTAQUOT1.SSD_CF AND TFAMLIA.UWY_NF - 1 = TSTASTAQUOT1.exc_y AND TFAMLIA.EGPCUR_CF = TSTASTAQUOT1.CUR_CF LEFT 
OUTER JOIN BREF..TSTASTAQUOT TSTASTAQUOT2 ON TFAMLIA.SSD_CF = TSTASTAQUOT2.SSD_CF AND TFAMLIA.UWY_NF - 1 = TSTASTAQUOT2.exc_y AND TFAMLIA.PRTCUR_CF = TSTASTAQUOT2.CUR_CF LEFT 
OUTER JOIN BFAC..TFAMCHG TFAMCHG ON TFAMCHG.CTR_NF = TCONTR.CTR_NF AND TFAMCHG.UWY_NF = TCONTR.UWY_NF AND TFAMCHG.UW_NT = TCONTR.UW_NT AND TFAMCHG.END_NT = TCONTR.END_NT AND 
TFAMCHG.SEC_NF = TSECTION.SEC_NF LEFT OUTER JOIN BCLI..TCLIENT TCLIENT_CED ON TCONTR.CED_NF = TCLIENT_CED.CLI_NF LEFT OUTER JOIN BCLI..THOLDING THOLDING_CED ON TCLIENT_CED.HLD_NF =
 THOLDING_CED.HLD_NF LEFT OUTER JOIN BFAC..TINSURED TINSURED ON TINSURED.IND_NF = TCONTR.PCPIND_NF LEFT OUTER JOIN BCLI..TCLIENT TCLIENT_IND on TCLIENT_IND.CLI_NF = 
 TINSURED.CLIIND_NF LEFT OUTER JOIN BCLI..THOLDING THOLDING_IND ON TCLIENT_IND.HLD_NF = THOLDING_IND.HLD_NF LEFT OUTER JOIN BCLI..TREPCRI TREPCRI_IND ON CASE WHEN 
 TCLIENT_IND.CLI_NF = 0 THEN 999 ELSE TCLIENT_IND.HINDNBR_NT END = TREPCRI_IND.HORDNBR_NT AND TREPCRI_IND.LAG_CF = "E" LEFT OUTER JOIN BCLI..TCLIADDR TCLIADDR_IND ON 
 (TCLIADDR_IND.CLI_NF = TCLIENT_IND.CLI_NF AND TCLIADDR_IND.ADDSUP_B = 0 AND TCLIADDR_IND.HEDOFFIND_B = 1) LEFT OUTER JOIN BCLI..TCLSTABI TCLSTABI_CED ON TCONTR.CED_NF = 
 TCLSTABI_CED.CLI_NF LEFT OUTER JOIN BCLI..TCLINTSU TCLINTSU_CED ON (TCLIENT_CED.CLI_NF = TCLINTSU_CED.CLI_NF AND TCLINTSU_CED.SORDNBR_NT is not null AND 
 TCLINTSU_CED.CLIINTSSD_CF <> 3) LEFT OUTER JOIN BCLI..TCLIENT TCLIENT_PAY ON TCONTR.GENPRMPAY_NF = TCLIENT_PAY.CLI_NF LEFT OUTER JOIN BREF..TOCC TOCC ON 
 TSECTION.OCC_CF=TOCC.RSKNAT_CF LEFT OUTER JOIN BREF..TSOBBLOB TSOBBLOB ON TSOBBLOB.SOB_CF = TSECTION.SOB_CF AND TSOBBLOB.LOB_CF = TSECTION.LOB_CF LEFT OUTER JOIN 
 BFAC..TRFCROSSREF TRFCROSSREF ON (TRFCROSSREF.CTR_NF = TCONTR.CTR_NF and TRFCROSSREF.TRFACCSTS_CT in (51,98,141,61) and TRFCROSSREF.TRFSTS_CT <> 14 ) LEFT OUTER JOIN
 BCLI..TCLIADDR TCLIADDR_CED ON (TCONTR.CED_NF = TCLIADDR_CED.CLI_NF AND TCLIADDR_CED.ADDSUP_B=0 AND TCLIADDR_CED.HEDOFFIND_B=1) LEFT JOIN BREF..TGRP2 TGRP2 on 
 TCONTR.UWGRP_CF = TGRP2.GRP_CF WHERE TSUBSID.PRDSIT_CF = @prdsitCf UNION SELECT TSECTION_DEL.CTR_NF AS CTR_NF, TSECTION_DEL.UWY_NF AS UWY_NF, TSECTION_DEL.UW_NT AS UW_NT, 
 TSECTION_DEL.END_NT AS END_NT, TSECTION_DEL.SEC_NF AS SEC_NF, NULL AS UWLSTUPD_D, TSECTION_DEL.SSD_CF AS SSD_CF, TSECTION_DEL.ACCESB_CF AS ACCESB_CF, 
 TSECTION_DEL.NAT_CF AS NAT_CF, TCONTR.CTRSTS_CT AS CTRSTS_CT, TSECTION_DEL.CTRTYP_CT AS CTRTYP_CT, 22 AS SECSTS_CT, 3 AS SECACCSTS_CT, TCONTR.LSTEND_B AS LSTEND_B, 
 TCONTR.LSTUWY_B AS LSTUWY_B, TCLIENT_CED.CLISSD_CF AS CLISSD_CF, 2 AS ACCADMTYP_CT, TSECTION_DEL.ACCGRP_CF AS ACCGRP_CF, 0 AS ACCLIA_M, 
 TSECTION_DEL.ADMGRP_CF AS ADMGRP_CF, 0 AS ALLTRT_B, TCLSTABI_CED.AMBCURRAT_CT AS AMBCURRAT_CT, TSECTION_DEL.ANLCTY_CF AS ANLCTY_CF, NULL AS ASSFINANCE_CT, NULL AS BOQ_NF, 0 
 AS CAT_B, 0 AS CATCNDEXI_B, NULL AS CATRSKTYP_CT, TSECTION_DEL.CED_NF AS CED_NF, TCLIENT_CED.CLIACT_CF AS CLIACT_CF, TCLIENT_CED.CLICTY_CF AS CLICTY_CF, TCLIENT_CED.CLINAT_CF AS 
 CLINAT_CF, TCLIENT_CED.CLISTS_CT AS CLISTS_CT, TCLIENT_CED.CLISUPIND_B AS CLISUPIND_B, TCLIENT_CED.CLITYP_CF AS CLITYP_CF, NULL AS CLMATTTYP_CT, 0 AS CLMCUTOFF_B, 0 AS 
 CLMRUNOFF_B, NULL AS CNATYP_CT, NULL AS CTRACC_D, TCONTR.CTRACCSTS_CT AS CTRACCSTS_CT, dateadd(dd,datediff( dd, "19000101", Isnull(TCONTR.SCOEXP_D, TCONTR.CTREXP_D)),"19000101") 
 AS CTREXP_D, NULL AS CTRINC_D, TCONTR.CTROLDNBR_LM as CTROLDNBR_LM, substring(ctroldnbr_lm,1,5) as CTROLDNBR_LS, "F" AS CTRNAT_CT, TSECTION_DEL.CTRQUA_CF AS CTRQUA_CF, NULL AS 
 CTRQUA10_CF, TSECTION_DEL.CTRQUA2_CF AS CTRQUA2_CF, TSECTION_DEL.CTRQUA3_CF AS CTRQUA3_CF, TSECTION_DEL.CTRQUA4_CF AS CTRQUA4_CF, TSECTION_DEL.CTRQUA5_CF AS CTRQUA5_CF, NULL AS 
 CTRQUA6_CF, NULL AS CTRQUA7_CF, NULL AS CTRQUA8_CF, NULL AS CTRQUA9_CF, NULL AS CTRSTS_D, TFAMLIA.CUTSHA_R AS CUTSHA_R, TSECTION_DEL.DIV_NT AS DIV_NT, NULL AS DIVLOB_CF, 0 AS 
 EAREXP_B, TFAMLIA.EGPCUR_CF AS EGPCUR_CF, TCONTR.ENDINC_D AS ENDINC_D, "O" AS ESTCRB_CT, "" AS ESTCTR_NF, TSECTION_DEL.FACACTSCT_CT AS FACACTSCT_CT, CASE WHEN 
 TSECTION_DEL.SSD_CF = 13 and TSECTION_DEL.CTRTYP_CT = 2 THEN 1 ELSE TSECTION_DEL.FACADMTYP_B END as FACADMTYP_CT, 0 AS FLOCNDEXI_B, NULL AS FRSINC_D, NULL AS FRSUWY_NF, 
 NULL AS GANPAYORD_NT, TSECTION_DEL.GAR_CF AS GAR_CF, NULL AS GENPRMPAY_NF, NULL AS GRPSTS_CT, CASE WHEN TCLIENT_IND.CLI_NF = 0 THEN 999 ELSE TCLIENT_IND.HINDNBR_NT END AS 
 HINDNBR_NT, TCLIENT_CED.HLD_NF AS HLD_NF, NULL AS HLDCTY_CF, TREPCRI_IND.HORDGRP_NT AS HORDGRP_NT, TFAMLIA.INDAMT_M AS INDAMT_M, NULL AS INDHLD_NF, 
 CASE WHEN ISNULL (TSECTION_DEL.PRD_NF, 0) = 0 THEN 0 ELSE 1 END AS INT_B, TCLSTABI_CED.ISICURRAT_CT AS ISICURRAT_CT, TFAMLIA.LAYCAP_M AS LAYCAP_M, 0 AS LDISCO_B, 
 TFAMLIA.LIACUR_CF AS LIACUR_CF, 0 AS LIAEVT_B, 0 AS LIARSK_B, NULL AS LIFTRTTYP_CF, TSECTION_DEL.LOB_CF AS LOB_CF, 0 AS LOSCOREXI_B, 0 AS LOSCTBEXI_B, TCONTR.LSTUWYRSK_B AS 
 LSTUWYRSK_B, 0 AS MULPRG_B, CASE WHEN TSECTION_DEL.NAT_CF IN ( "30", "31", "32", "40", "41" ) THEN "N" ELSE "P" END AS NAT_B, TSECTION_DEL.OCC_CF AS OCC_CF, 
 ISNULL (ISNULL (TSECTION_DEL.ORGCED_NF, TSECTION_DEL.CED_NF), 0) AS ORGCED_NF, TSUBSID.SSDCUR_CF AS PCPCUR_CF, NULL AS PCPEXTREF_LL, TCONTR.PCPIND_NF AS PCPIND_NF, 
 TCONTR.PCPLOB_CF AS PCPLOB_CF, TSECTION_DEL.PCPRSKTRY_CF AS PCPRSKTRY_CF, TCONTR.PCPTOP_CF AS PCPTOP_CF, TSECTION_DEL.PRD_NF AS PRD_NF, TSOBBLOB.PRDCOD_CT AS PRDCOD_CT, 0 AS 
 PRFCOMEXI_B, NULL AS PRG_NF, NULL AS PRGNATFAM_CT, 0 AS PRMCUTOFF_B, 0 AS PRMRUNOFF_B, case when TSECTION_DEL.refsec_nf = TSECTION_DEL.sec_nf and TCONTR.lstend_b = 1 and 
 TSTASTAQUOT1.EXC_R != 0 then (TFAMLIA.prtcos_m*TSTASTAQUOT2.EXC_R)/TSTASTAQUOT1.EXC_R else 0 end AS PRTCOS_M, TSECTION_DEL.REITYP_CF AS REITYP_CF, TCONTR.REN_B AS REN_B, 0 AS 
 RSKCOMPRM_B, TOCC.RSKNATFAM_CF AS RSKNATFAM_CF, TFAMLIA.SCOGLOEGP_M AS SCOGLOEGP_M, NULL AS SCOINC_D, TFAMLIA.SCOLIA_M AS SCOLIA_M, TFAMLIA.SCOLIALIM_M AS SCOLIALIM_M, 
 TFAMLIA.SCOORGEGP_M AS SCOORGEGP_M, TFAMLIA.SCOPML_M AS SCOPML_M, NULL AS SECACCSTS2_CT, NULL AS SECCAN_D, NULL AS SECINC_D, TSECTION_DEL.SECQUA_CF AS SECQUA_CF, 
 NULL AS SECQUA10_CF, TSECTION_DEL.SECQUA2_CF AS SECQUA2_CF, TSECTION_DEL.SECQUA3_CF AS SECQUA3_CF, TSECTION_DEL.SECQUA4_CF AS SECQUA4_CF, TSECTION_DEL.SECQUA5_CF AS SECQUA5_CF, 
 NULL AS SECQUA6_CF, NULL AS SECQUA7_CF, NULL AS SECQUA8_CF, NULL AS SECQUA9_CF, TFAMLIA.SIGSHA_R AS SIGSHA_R, TSECTION_DEL.SOB_CF AS SOB_CF, TCLINTSU_CED.SORDNBR_NT AS 
 SORDNBR_NT, TCLSTABI_CED.SPCURRAT_CT AS SPCURRAT_CT, RIGHT (REPLICATE ("0", 2) + CONVERT (VARCHAR, TSECTION_DEL.ssd_cf), 2) + "-" + RIGHT (REPLICATE ("0", 2) + 
 CONVERT (VARCHAR, TSECTION_DEL.accesb_cf), 2) AS SSD_ESB, 0 AS STOCNDEXI_B, TSECTION_DEL.SUBNAT_CF AS SUBNAT_CF, CASE WHEN TSECTION_DEL.LOB_CF IN ("30", "31") 
 THEN "L" ELSE "F" END AS TFL_IND, NULL AS EDI_CALC, NULL AS CAT_RISK_COVERED_CALC, CASE WHEN TSECTION_DEL.CTR_NF IS NOT NULL AND TSECTION_DEL.CTR_NF <> "        
 " THEN CASE WHEN TSECTION_DEL.FACADMTYP_B = 0 THEN "BS" ELSE "Specialties" END ELSE NULL END AS SBS_ADMIN_CALC, ISNULL (TACCLIA.MPLSCEAMT_M, 0) + 
 ISNULL (TACCLIA.OTHPARAMT_M, 0) AS GAL_CONSO_CALC, TACCLIA.ACCLIA_M - ISNULL (TACCLIA.CBIAMT_M, 0) AS GAL_RETRO_CALC, TFAMLIA.CUTSHA_R * TFAMLIA.RIDSHA_R * 100 AS 
 SCOR_SHARE_ORG_CALC, ISNULL (TACCLIA.CBIAMT_M, 0) AS GAL_CBI_CALC, ISNULL (TACCLIA.JVTAMT_M, 0) AS GAL_JV_CALC, ISNULL (TACCLIA.MPLSCEAMT_M, 0) AS GAL_FAC_IMPACT_CALC, 
 ISNULL (TACCLIA.NGHAMT_M, 0) AS GAL_NEIGHBORHOOD_CALC, ISNULL (TACCLIA.OTHLOBAMT_M, 0) AS GAL_OTHER_LOB_CALC, ISNULL (TACCLIA.OTHPARAMT_M, 0) AS GAL_OTHER_PART_CALC, 
 TFAMLIA.CUTSHA_R * 100 AS SCOR_SHARE_CEDED_CALC, 0 AS SEC_RETRO_RATIO_CALC, TFAMLIA.RIDSHA_R * 100 AS CEDED_SHARE_CALC, 0 AS IO_CLIENT_SCOR_CALC, 
 TFAMCHG.CTBGENFEE_R * 100 AS COM_PC_EXPENSES_CALC, TFAMCHG.FIXCOM_R * 100 AS COM_FIX_CALC, TFAMCHG.LOSCTB_R * 100 AS COM_PC_LOSS_CALC, TFAMCHG.MAXCOM_R * 100 AS 
 COM_VARIABLE_MAX_CALC, TFAMCHG.MAXRATCLP_R * 100 AS LR_VARIABLE_MAX_CALC, TFAMCHG.MINCOM_R * 100 AS COM_VARIABLE_MIN_CALC, TFAMCHG.MINRATCLP_R * 100 AS LR_VARIABLE_MIN_CALC, 
 TFAMCHG.OVRCOM_R * 100 AS COM_OVERRIDER_CALC, TFAMCHG.PRFCOM_R * 100 AS COM_PC_PROFIT_CALC, TFAMCHG.PRVCOM_R * 100 AS COM_VARIABLE_PROV_CALC, NULL AS COM_VARIABLE_CALC, 
 TFAMLIA.LIAAGRDED_M AS AGG_DEDUCTIBLE_CALC, TSECTION_DEL.TOP_CF AS TOP_CF, CASE WHEN TRFCROSSREF.TRFACCSTS_CT IN ( 51, 98, 141, 61 ) AND TRFCROSSREF.TRFSTS_CT <> 14 THEN 1 
 ELSE 0 END AS TRFTRT_B, CASE WHEN TSECTION_DEL.REITYP_CF = 1 THEN 1 ELSE CASE WHEN TSECTION_DEL.REITYP_CF IN ( NULL, 2, 3, 4, 5, 7, 10, 12 ) THEN 2 ELSE CASE WHEN 
 TSECTION_DEL.REITYP_CF = 6 THEN 3 ELSE CASE WHEN TSECTION_DEL.REITYP_CF = 8 THEN 4 ELSE CASE WHEN TSECTION_DEL.REITYP_CF = 9 THEN 5 ELSE CASE WHEN TSECTION_DEL.REITYP_CF = 15 
 THEN 6 ELSE CASE WHEN TSECTION_DEL.REITYP_CF = 16 THEN 7 ELSE CASE WHEN TSECTION_DEL.REITYP_CF = 17 THEN 8 ELSE CASE WHEN TSECTION_DEL.REITYP_CF = 18 THEN 9 ELSE CASE WHEN 
 TSECTION_DEL.REITYP_CF = 19 THEN 10 ELSE CASE WHEN TSECTION_DEL.REITYP_CF = 20 THEN 20 END END END END END END END END END END END AS TYPREI_CF, NULL AS ULT_NF, NULL AS USGAAP_CT,
 NULL AS USRCRTCOD_CT, NULL AS USRCRTVAL_LM, TSECTION_DEL.UWGRP_CF AS UWGRP_CF, TSECTION_DEL.UWORG_CF AS UWORG_CF, NULL AS WRKCAT_CT, TCLIADDR_CED.CLIADDSTA_CF AS CLIADDSTA_CF, 
 TCONTR.PCPSOB_CF AS PCPSOB_CF, TCLIENT_CED.HORDNBR_NT AS HORDNBR_NT, TCLIADDR_IND.CLIADDCTY_CF AS INDADDCTY_CF, TDIVISIO.PCPRSKTRY_CF AS PCPRSKTRY_DIV_CF, TCONTR.PCPOCC_CF AS 
 PCPOCC_CF, TCONTR.POLDUR_CF AS POLDUR_CF, NULL AS CEDULT_NF, TCONTR.MAS_NF AS MAS_NF, TDIVISIO.PCPRSKTRY_CF as PRINCRSKTRY_CF, CASE WHEN TDIVISIO.RETAPPMOD_CT = 1 THEN 1 ELSE 0 
 END as MANRET_B, 0 as STREXP_B, 0 as FLDEXP_B, 1 as FACADMTYP_B FROM BFAC..TSECTION_DEL TSECTION_DEL LEFT JOIN BFAC..TCONTR TCONTR ON TSECTION_DEL.CTR_NF = TCONTR.CTR_NF AND 
 TSECTION_DEL.UWY_NF = TCONTR.UWY_NF AND TSECTION_DEL.UW_NT = TCONTR.UW_NT AND TSECTION_DEL.END_NT = TCONTR.END_NT INNER JOIN BREF..TSUBSID TSUBSID ON TSUBSID.SSD_CF = 
 TSECTION_DEL.SSD_CF LEFT JOIN BFAC..TDIVISIO TDIVISIO ON TDIVISIO.CTR_NF = TSECTION_DEL.CTR_NF AND TDIVISIO.UWY_NF = TSECTION_DEL.UWY_NF AND TDIVISIO.UW_NT = TSECTION_DEL.UW_NT 
 AND TDIVISIO.END_NT = TSECTION_DEL.END_NT AND TDIVISIO.DIV_NT = TSECTION_DEL.DIV_NT LEFT JOIN BFAC..TACCLIA TACCLIA ON TSECTION_DEL.CTR_NF = TACCLIA.CTR_NF AND 
 TSECTION_DEL.UWY_NF = TACCLIA.UWY_NF AND TSECTION_DEL.UW_NT = TACCLIA.UW_NT AND TSECTION_DEL.DIV_NT = TACCLIA.DIV_NT LEFT OUTER JOIN BFAC..TFAMLIA TFAMLIA ON TFAMLIA.CTR_NF = 
 TSECTION_DEL.CTR_NF AND TFAMLIA.UWY_NF = TSECTION_DEL.UWY_NF AND TFAMLIA.UW_NT = TSECTION_DEL.UW_NT AND TFAMLIA.END_NT = TSECTION_DEL.END_NT AND TFAMLIA.SEC_NF = 
 TSECTION_DEL.SEC_NF LEFT OUTER JOIN BREF..TSTASTAQUOT TSTASTAQUOT1 ON TFAMLIA.SSD_CF = TSTASTAQUOT1.SSD_CF AND TFAMLIA.UWY_NF - 1 = TSTASTAQUOT1.exc_y AND TFAMLIA.EGPCUR_CF = 
 TSTASTAQUOT1.CUR_CF LEFT OUTER JOIN BREF..TSTASTAQUOT TSTASTAQUOT2 ON TFAMLIA.SSD_CF = TSTASTAQUOT2.SSD_CF AND TFAMLIA.UWY_NF - 1 = TSTASTAQUOT2.exc_y AND TFAMLIA.PRTCUR_CF = 
 TSTASTAQUOT2.CUR_CF LEFT OUTER JOIN BFAC..TFAMCHG TFAMCHG ON TFAMCHG.CTR_NF = TSECTION_DEL.CTR_NF AND TFAMCHG.UWY_NF = TSECTION_DEL.UWY_NF AND TFAMCHG.UW_NT = 
 TSECTION_DEL.UW_NT AND TFAMCHG.END_NT = TSECTION_DEL.END_NT AND TFAMCHG.SEC_NF = TSECTION_DEL.SEC_NF LEFT OUTER JOIN BCLI..TCLIENT TCLIENT_CED ON TSECTION_DEL.CED_NF = 
 TCLIENT_CED.CLI_NF LEFT OUTER JOIN BCLI..TCLSTABI TCLSTABI_CED ON TSECTION_DEL.CED_NF = TCLSTABI_CED.CLI_NF LEFT OUTER JOIN BCLI..TCLINTSU TCLINTSU_CED ON (TCLIENT_CED.CLI_NF = 
 TCLINTSU_CED.CLI_NF AND TCLINTSU_CED.SORDNBR_NT IS NOT NULL AND TCLINTSU_CED.CLIINTSSD_CF <> 3) LEFT OUTER JOIN BFAC..TINSURED TINSURED ON TINSURED.IND_NF = TCONTR.PCPIND_NF LEFT
 OUTER JOIN BCLI..TCLIENT TCLIENT_IND ON TCLIENT_IND.CLI_NF = TINSURED.CLIIND_NF LEFT OUTER JOIN BCLI..TREPCRI TREPCRI_IND ON CASE WHEN TCLIENT_IND.CLI_NF = 0 THEN 999 ELSE 
 TCLIENT_IND.HINDNBR_NT END = TREPCRI_IND.HORDNBR_NT AND TREPCRI_IND.LAG_CF = "E" LEFT OUTER JOIN BCLI..TCLIADDR TCLIADDR_IND ON (TCLIADDR_IND.CLI_NF = TCLIENT_IND.CLI_NF AND 
 TCLIADDR_IND.ADDSUP_B = 0 AND TCLIADDR_IND.HEDOFFIND_B = 1) LEFT OUTER JOIN BREF..TOCC TOCC ON TSECTION_DEL.OCC_CF = TOCC.RSKNAT_CF LEFT OUTER JOIN BREF..TSOBBLOB TSOBBLOB ON 
 TSOBBLOB.SOB_CF = TSECTION_DEL.SOB_CF AND TSOBBLOB.LOB_CF = TSECTION_DEL.LOB_CF LEFT OUTER JOIN BFAC..TRFCROSSREF TRFCROSSREF ON (TRFCROSSREF.CTR_NF = TSECTION_DEL.CTR_NF AND 
 TRFCROSSREF.TRFACCSTS_CT IN ( 51, 98, 141, 61 ) AND TRFCROSSREF.TRFSTS_CT <> 14) LEFT OUTER JOIN BCLI..TCLIADDR TCLIADDR_CED ON (TSECTION_DEL.CED_NF = TCLIADDR_CED.CLI_NF AND 
 TCLIADDR_CED.ADDSUP_B = 0 AND TCLIADDR_CED.HEDOFFIND_B = 1) WHERE TSUBSID.PRDSIT_CF = @prdsitCf AND NOT EXISTS (SELECT 1 FROM BFAC..TSECTION TSECTION WHERE TSECTION.ctr_nf = 
 TSECTION_DEL.ctr_nf AND TSECTION.sec_nf = TSECTION_DEL.sec_nf AND TSECTION.Uwy_nf = TSECTION_DEL.uwy_nf AND TSECTION.uw_nt = TSECTION_DEL.uw_nt AND TSECTION.end_nt = 
 TSECTION_DEL.end_nt) UNION SELECT TCONTR.CTR_NF as CTR_NF, TCONTR.UWY_NF as UWY_NF, TSECTION.UW_NT as UW_NT, TCONTR.END_NT as END_NT, TSECTION.SEC_NF as SEC_NF, CASE WHEN 
 TCONTR.LSTUPD_D > TSECTION.LSTUPD_D THEN TCONTR.LSTUPD_D ELSE TSECTION.LSTUPD_D END as UWLSTUPD_D, TCONTR.SSD_CF as SSD_CF, TCONTR.ACCESB_CF as ACCESB_CF, TSECTION.NAT_CF as 
 NAT_CF, TCONTR.CTRSTS_CT as CTRSTS_CT, TCONTR.CTRTYP_CT as CTRTYP_CT, TSECTION.SECSTS_CT as SECSTS_CT, TSECTION.SECACCSTS_CT as SECACCSTS_CT, 1 as LSTEND_B, TCONTR.LSTUWY_B as 
 LSTUWY_B, TCLIENT_CED.CLISSD_CF as CLISSD_CF, TSECTION.ACCADMTYP_CT as ACCADMTYP_CT, TCONTR.ACCGRP_CF as ACCGRP_CF, null as ACCLIA_M, TCONTR.ADMGRP_CF as ADMGRP_CF, 
 TCONTR.ALLTRT_B as ALLTRT_B, TCLSTABI_CED.AMBCURRAT_CT as AMBCURRAT_CT, TSECTION.ANLCTY_CF as ANLCTY_CF, TSECTION.ASSFINANCE_CT as ASSFINANCE_CT, TCONTR.BOQ_NF as BOQ_NF, 
 TCONTR.CAT_B as CAT_B, TFAMSTS.CATCNDEXI_B as CATCNDEXI_B, TFAMCAT.CATRSKTYP_CT as CATRSKTYP_CT, isnull(TCONTR.CED_NF,0) as CED_NF, TCLIENT_CED.CLIACT_CF as CLIACT_CF, 
 TCLIENT_CED.CLICTY_CF as CLICTY_CF, TCLIENT_CED.CLINAT_CF as CLINAT_CF, TCLIENT_CED.CLISTS_CT as CLISTS_CT, TCLIENT_CED.CLISUPIND_B as CLISUPIND_B, TCLIENT_CED.CLITYP_CF as 
 CLITYP_CF, TSECTION.CLMATTTYP_CT as CLMATTTYP_CT, TSECTION.CLMCUTOFF_B as CLMCUTOFF_B, TSECTION.CLMRUNOFF_B as CLMRUNOFF_B, TCONTR.CNATYP_CT as CNATYP_CT, TCONTR.CTRACC_D as 
 CTRACC_D, TCONTR.CTRACCSTS_CT as CTRACCSTS_CT, CASE WHEN TCONTR.CTREXP_D IS NULL AND TCONTR.SCOEXP_D IS NULL THEN NULL ELSE DATEADD(dd, DATEDIFF(dd, "19000101", CASE WHEN 
 TCONTR.CTREXP_D IS NULL THEN DATEADD(dd, -1, TCONTR.SCOEXP_D) ELSE TCONTR.CTREXP_D END), "19000101") END AS CTREXP_D, TCONTR.SCOINC_D as CTRINC_D, null as CTROLDNBR_LM, null as 
 CTROLDNBR_LS, CASE WHEN TSECTION.NAT_CF in ("30","31","32","40","41") THEN "N" ELSE "P" END as CTRNAT_CT, TCONTR.CTRQUA_CF as CTRQUA_CF, TCONTR.CTRQUA10_CF as CTRQUA10_CF, 
 TCONTR.CTRQUA2_CF as CTRQUA2_CF, TCONTR.CTRQUA3_CF as CTRQUA3_CF, TCONTR.CTRQUA4_CF as CTRQUA4_CF, TCONTR.CTRQUA5_CF as CTRQUA5_CF, TCONTR.CTRQUA6_CF as CTRQUA6_CF, 
 TCONTR.CTRQUA7_CF as CTRQUA7_CF, TCONTR.CTRQUA8_CF as CTRQUA8_CF, TCONTR.CTRQUA9_CF as CTRQUA9_CF, TCONTR.CTRSTS_D as CTRSTS_D, TFAMLIA.CUTSHA_R as CUTSHA_R, null as DIV_NT, 
 null as DIVLOB_CF, TSECTION.EAREXP_B as EAREXP_B, TFAMLIA.EGPCUR_CF as EGPCUR_CF, TCONTR.ENDINC_D as ENDINC_D, isnull(TCONTR.ESTCRB_CT, "O") as ESTCRB_CT, TSECTION.ESTCTR_NF as
 ESTCTR_NF, TCONTR.FACACTSCT_CT as FACACTSCT_CT, CASE WHEN TCONTR.CTRTYP_CT = 1 AND (TGRP2.FACADMTYP_B = NULL or TGRP2.FACADMTYP_B = 2) THEN 0 WHEN TCONTR.CTRTYP_CT = 1 AND 
 TGRP2.FACADMTYP_B <> NULL THEN TGRP2.FACADMTYP_B WHEN TCONTR.SSD_CF = 13 AND TCONTR.CTRTYP_CT = 2 THEN 1 ELSE TCONTR.FACADMTYP_B END as FACADMTYP_CT, TFAMSTS.FLOCNDEXI_B as 
 FLOCNDEXI_B, TCONTR.FRSINC_D as FRSINC_D, TCONTR.FRSUWY_NF as FRSUWY_NF, TCONTR.GANPAYORD_NT as GANPAYORD_NT, TSECTION.GAR_CF as GAR_CF, TCONTR.GENPRMPAY_NF as GENPRMPAY_NF, 
 TBOQPRG_PRG.GRPSTS_CT as GRPSTS_CT, null as HINDNBR_NT, TCLIENT_CED.HLD_NF as HLD_NF, THOLDING_CED.HLDCTY_CF as HLDCTY_CF, null as HORDGRP_NT, TFAMLIA.INDAMT_M as INDAMT_M, null 
 as INDHLD_NF, CASE WHEN isnull(TCONTR.PRD_NF,0)=0 THEN 0 ELSE 1 END as INT_B, TCLSTABI_CED.ISICURRAT_CT as ISICURRAT_CT, TFAMLIA.LAYCAP_M as LAYCAP_M, TCONTR.LDISCO_B as 
 LDISCO_B, TFAMLIA.LIACUR_CF as LIACUR_CF, TSECTION.LIAEVT_B as LIAEVT_B, TSECTION.LIARSK_B as LIARSK_B, TCONTR.LIFTRTTYP_CF as LIFTRTTYP_CF, TSECTION.LOB_CF as LOB_CF, 
 TFAMCHG.LOSCOREXI_B as LOSCOREXI_B, TFAMCHG.LOSCTBEXI_B as LOSCTBEXI_B, TCONTR.LSTUWYRSK_B as LSTUWYRSK_B, TBOQPRG_PRG.MULPRG_B as MULPRG_B, CASE WHEN TSECTION.NAT_CF in 
 ("30","31","32","40","41") THEN "N" ELSE "P" END as NAT_B, TSECTION.OCC_CF as OCC_CF, isnull(isnull(TCONTR.ORGCED_NF, TCONTR.CED_NF),0) as ORGCED_NF, TSECTION.PCPCUR_CF as 
 PCPCUR_CF, TCONTR.PCPEXTREF_LL as PCPEXTREF_LL, null as PCPIND_NF, TCONTR.PCPLOB_CF as PCPLOB_CF, TSECTION.PCPRSKTRY_CF as PCPRSKTRY_CF, TCONTR.PCPTOP_CF as PCPTOP_CF, 
 TCONTR.PRD_NF as PRD_NF, null as PRDCOD_CT, TFAMCHG.PRFCOMEXI_B as PRFCOMEXI_B, TCONTR.PRG_NF as PRG_NF, TBOQPRG_PRG.PRGNATFAM_CT as PRGNATFAM_CT, TSECTION.PRMCUTOFF_B as
 PRMCUTOFF_B, TSECTION.PRMRUNOFF_B as PRMRUNOFF_B, TFAMLIA.PRTCOS_M as PRTCOS_M, TCONTR.REITYP_CF as REITYP_CF, TCONTR.REN_B as REN_B, TCONTR.RSKCOMPRM_B as RSKCOMPRM_B, null as 
 RSKNATFAM_CF, TFAMLIA.SCOGLOEGP_M as SCOGLOEGP_M, TBOQPRG_PRG.SCOINC_D as SCOINC_D, TFAMLIA.SCOLIA_M as SCOLIA_M, TFAMLIA.SCOLIALIM_M as SCOLIALIM_M, TFAMLIA.SCOORGEGP_M as 
 SCOORGEGP_M, TFAMLIA.SCOPML_M as SCOPML_M, TSECTION.SECACCSTS2_CT as SECACCSTS2_CT, TSECTION.SECCAN_D as SECCAN_D, TSECTION.SECINC_D as SECINC_D, TSECTION.SECQUA_CF as SECQUA_CF, 
 TSECTION.SECQUA10_CF as SECQUA10_CF, TSECTION.SECQUA2_CF as SECQUA2_CF, TSECTION.SECQUA3_CF as SECQUA3_CF, TSECTION.SECQUA4_CF as SECQUA4_CF, TSECTION.SECQUA5_CF as SECQUA5_CF, 
 TSECTION.SECQUA6_CF as SECQUA6_CF, TSECTION.SECQUA7_CF as SECQUA7_CF, TSECTION.SECQUA8_CF as SECQUA8_CF, TSECTION.SECQUA9_CF as SECQUA9_CF, TFAMLIA.SIGSHA_R as SIGSHA_R, 
 TSECTION.SOB_CF as SOB_CF, TCLINTSU_CED.SORDNBR_NT as SORDNBR_NT, TCLSTABI_CED.SPCURRAT_CT as SPCURRAT_CT, right(replicate("0", 2) + convert(varchar,TCONTR.ssd_cf), 2) + 
 "-" + right(replicate("0", 2) + convert(varchar,TCONTR.accesb_cf), 2) as SSD_ESB, TFAMSTS.STOCNDEXI_B as STOCNDEXI_B, TSECTION.SUBNAT_CF as SUBNAT_CF, CASE WHEN 
 TSECTION.LOB_CF in ("30","31") then "L" ELSE "T" END as TFL_IND, substring("             LIRMA        Joint Venture",charindex(rtrim(ltrim(convert(char,TCONTR.UMRACCADM_CT))),
 "0"+space(12)+"1"+space(12)+"2"+space(12)),13) as EDI_CALC, CASE WHEN TSECTION.STREXP_B=1 or TSECTION.earexp_b=1 or TSECTION.fldexp_b=1 THEN 1 ELSE 0 END as CAT_RISK_COVERED_CALC,
 CASE WHEN TCONTR.CTR_NF is not null and TCONTR.CTR_NF <> "        " THEN CASE WHEN TCONTR.FACADMTYP_B = 0 THEN "BS" ELSE "Specialties" END ELSE null END as SBS_ADMIN_CALC,
 null as GAL_CONSO_CALC, null as GAL_RETRO_CALC, TFAMLIA.CUTSHA_R * TFAMLIA.RIDSHA_R * 100 as SCOR_SHARE_ORG_CALC, null as GAL_CBI_CALC, null as GAL_JV_CALC, null as 
 GAL_FAC_IMPACT_CALC, null as GAL_NEIGHBORHOOD_CALC, null as GAL_OTHER_LOB_CALC, null as GAL_OTHER_PART_CALC, TFAMLIA.CUTSHA_R * 100 as SCOR_SHARE_CEDED_CALC, 
 TSECTION.RETPCT_R*100 as SEC_RETRO_RATIO_CALC, TFAMLIA.RIDSHA_R * 100 as CEDED_SHARE_CALC, CASE WHEN TCONTR.CED_NF <> 0 THEN 1 ELSE 0 END as IO_CLIENT_SCOR_CALC, 
 TFAMCHG.CTBGENFEE_R * 100 as COM_PC_EXPENSES_CALC, TFAMCHG.FIXCOM_R * 100 as COM_FIX_CALC, TFAMCHG.LOSCTB_R * 100 as COM_PC_LOSS_CALC, TFAMCHG.MAXCOM_R * 100 as 
 COM_VARIABLE_MAX_CALC, TFAMCHG.MAXRATCLP_R * 100 as LR_VARIABLE_MAX_CALC, TFAMCHG.MINCOM_R * 100 as COM_VARIABLE_MIN_CALC, TFAMCHG.MINRATCLP_R * 100 as LR_VARIABLE_MIN_CALC, 
 TFAMCHG.OVRCOM_R * 100 as COM_OVERRIDER_CALC, TFAMCHG.PRFCOM_R * 100 as COM_PC_PROFIT_CALC, TFAMCHG.PRVCOM_R * 100 as COM_VARIABLE_PROV_CALC, TFAMCOTP.PRMEFFLOA_R * 100 as 
 COM_VARIABLE_CALC, TFAMLIA.LIAAGRDED_M as AGG_DEDUCTIBLE_CALC, TSECTION.TOP_CF as TOP_CF, CASE WHEN TRFCROSSREF.CTR_NF is null then 0 else 1 END as TRFTRT_B, CASE WHEN 
 TCONTR.REITYP_CF = 1 THEN 1 ELSE CASE WHEN TCONTR.REITYP_CF in (null,2,3,4,5,7,10,12) THEN 2 ELSE CASE WHEN TCONTR.REITYP_CF = 6 THEN 3 ELSE CASE WHEN TCONTR.REITYP_CF = 8 
 THEN 4 ELSE CASE WHEN TCONTR.REITYP_CF = 9 THEN 5 ELSE CASE WHEN TCONTR.REITYP_CF = 15 THEN 6 ELSE CASE WHEN TCONTR.REITYP_CF = 16 THEN 7 ELSE CASE WHEN TCONTR.REITYP_CF = 17 
 THEN 8 ELSE CASE WHEN TCONTR.REITYP_CF = 18 THEN 9 ELSE CASE WHEN TCONTR.REITYP_CF = 19 THEN 10 ELSE CASE WHEN TCONTR.REITYP_CF = 20 THEN 20 END END END END END END END END END 
 END END as TYPREI_CF, null as ULT_NF, TSECTION.USGAAP_CT as USGAAP_CT, TSECTION.USRCRTCOD_CT as USRCRTCOD_CT, TSECTION.USRCRTVAL_LM as USRCRTVAL_LM, TCONTR.UWGRP_CF as UWGRP_CF, 
 TCONTR.UWORG_CF as UWORG_CF, TSECTION.WRKCAT_CT as WRKCAT_CT, TCLIADDR_CED.CLIADDSTA_CF as CLIADDSTA_CF, TCONTR.PCPSOB_CF as PCPSOB_CF, TCLIENT_CED.HORDNBR_NT AS HORDNBR_NT,
 NULL AS INDADDCTY_CF, NULL AS PCPRSKTRY_DIV_CF, TCONTR.PCPOCC_CF AS PCPOCC_CF, TCONTR.POLDUR_CF AS POLDUR_CF, THOLDING_CED.ULT_NF AS CEDULT_NF, NULL AS MAS_NF, 
 (case when TSECTION.PCPTER_B = 1 then TSECTION.PCPRSKTRY_CF else null end) as PRINCRSKTRY_CF, TCONTR.MANRET_B as MANRET_B, TSECTION.STREXP_B as STREXP_B, 
 TSECTION.FLDEXP_B as FLDEXP_B, TCONTR.FACADMTYP_B as FACADMTYP_B FROM BTRT..TCONTR TCONTR INNER JOIN BREF..TSUBSID TSUBSID ON TSUBSID.SSD_CF = TCONTR.SSD_CF LEFT JOIN 
 BTRT..TBOQPRG TBOQPRG_PRG ON TBOQPRG_PRG.GRP_NF = TCONTR.PRG_NF AND TBOQPRG_PRG.UWY_NF = TCONTR.UWY_NF INNER JOIN BTRT..TSECTION TSECTION ON TSECTION.CTR_NF = TCONTR.CTR_NF AND 
 TSECTION.UWY_NF = TCONTR.UWY_NF AND TSECTION.UW_NT = TCONTR.UW_NT AND TSECTION.END_NT = TCONTR.END_NT LEFT OUTER JOIN BTRT..TFAMCOTP TFAMCOTP ON TFAMCOTP.CTR_NF = TCONTR.CTR_NF 
 AND TFAMCOTP.UWY_NF = TCONTR.UWY_NF AND TFAMCOTP.UW_NT = TCONTR.UW_NT AND TFAMCOTP.END_NT = TCONTR.END_NT AND TFAMCOTP.SEC_NF = TSECTION.SEC_NF LEFT OUTER JOIN BTRT..TFAMSTS 
 TFAMSTS ON TFAMSTS.CTR_NF = TCONTR.CTR_NF AND TFAMSTS.UWY_NF = TCONTR.UWY_NF AND TFAMSTS.UW_NT = TCONTR.UW_NT AND TFAMSTS.END_NT = TCONTR.END_NT AND TFAMSTS.SEC_NF = 
 TSECTION.SEC_NF LEFT OUTER JOIN BTRT..TFAMLIA TFAMLIA ON TFAMLIA.CTR_NF = TCONTR.CTR_NF AND TFAMLIA.UWY_NF = TCONTR.UWY_NF AND TFAMLIA.UW_NT = TCONTR.UW_NT AND TFAMLIA.END_NT = 
 TCONTR.END_NT AND TFAMLIA.SEC_NF = TSECTION.SEC_NF LEFT OUTER JOIN BTRT..TFAMCHG TFAMCHG ON TFAMCHG.CTR_NF = TCONTR.CTR_NF AND TFAMCHG.UWY_NF = TCONTR.UWY_NF AND TFAMCHG.UW_NT = 
 TCONTR.UW_NT AND TFAMCHG.END_NT = TCONTR.END_NT AND TFAMCHG.SEC_NF = TSECTION.SEC_NF LEFT OUTER JOIN BTRT..TFAMCAT TFAMCAT ON TFAMCAT.CTR_NF = TCONTR.CTR_NF AND TFAMCAT.UWY_NF = 
 TCONTR.UWY_NF AND TFAMCAT.UW_NT = TCONTR.UW_NT AND TFAMCAT.END_NT = TCONTR.END_NT AND TFAMCAT.SEC_NF = TSECTION.SEC_NF LEFT OUTER JOIN BCLI..TCLIENT TCLIENT_CED ON TCONTR.CED_NF =
 TCLIENT_CED.CLI_NF LEFT OUTER JOIN BCLI..THOLDING THOLDING_CED ON TCLIENT_CED.HLD_NF = THOLDING_CED.HLD_NF LEFT OUTER JOIN BCLI..TCLSTABI TCLSTABI_CED ON TCONTR.CED_NF = 
 TCLSTABI_CED.CLI_NF LEFT OUTER JOIN BCLI..TCLINTSU TCLINTSU_CED ON (TCLIENT_CED.CLI_NF = TCLINTSU_CED.CLI_NF AND TCLINTSU_CED.SORDNBR_NT is not null AND 
 TCLINTSU_CED.CLIINTSSD_CF <> 3) LEFT OUTER JOIN BCLI..TCLIENT TCLIENT_PAY ON TCONTR.GENPRMPAY_NF = TCLIENT_PAY.CLI_NF LEFT OUTER JOIN BTRT..TRFCROSSREF TRFCROSSREF ON 
 (TRFCROSSREF.CTR_NF = TCONTR.CTR_NF and TRFCROSSREF.TRFACCSTS_CT in (51,98,141,61) and TRFCROSSREF.TRFSTS_CT <> 14 ) LEFT OUTER JOIN BCLI..TCLIADDR TCLIADDR_CED ON 
 (TCONTR.CED_NF = TCLIADDR_CED.CLI_NF AND TCLIADDR_CED.ADDSUP_B=0 AND TCLIADDR_CED.HEDOFFIND_B=1) LEFT JOIN BREF..TGRP2 TGRP2 on TCONTR.UWGRP_CF = TGRP2.GRP_CF WHERE 
 TSUBSID.PRDSIT_CF = @prdsitCf'
where SGTUWTAB_CF = 'TSEGUWASMSEC'

commit tran
print 'Commit Done'
go

select * from BEST..TSEGUWCOLUMN where SGTUWTAB_CF = 'TSEGUWASMSEC' and SGTUWCOL_CF in ('FACADMTYP_B')
select * from BEST..TSEGCRITERIA where SGTCRI_CF  in ('SBS_Indicator')
select * from BEST..TSEGUWTABLE where SGTUWTAB_CF = 'TSEGUWASMSEC'

go

