USE BEST
GO

CREATE TABLE #COUNTCHECK
(
	STEP int identity,
	SELECTCOUNT int,
	UPDATECOUNT int DEFAULT 0
)

SET NOCOUNT ON

-- ###############################################################################
-- Script           			: SEG_US5037_UPDATE_TSEGCRITERIA_TABLE.sql
-- Domain	          			: SEG
-- Author           			: SANDEEP
-- Date of creation				: 10/07/2025
-- ################################################################################

DECLARE @gCommit VARCHAR (01)
DECLARE @gTodayD DATETIME
SELECT @gCommit = 'O'
SELECT @gTodayD = GETDATE ()
DECLARE @startTime DATETIME, @endTime DATETIME
SELECT @startTime = getdate()

DECLARE @STEP int

BEGIN TRAN

PRINT 'DATA BEFORE UPDATE'
SELECT 'TSEGCRITERIA TABLE'
SELECT * FROM BEST..TSEGCRITERIA WHERE SGTUWCOL_CF='FACADMTYP_CT'
INSERT INTO #COUNTCHECK (SELECTCOUNT) VALUES ( @@ROWCOUNT )

SELECT 'TSEGUWCOLUMN TABLE'
SELECT * FROM BEST..TSEGUWCOLUMN WHERE SGTUWCOL_CF='FACADMTYP_CT'

INSERT INTO #COUNTCHECK (SELECTCOUNT) VALUES ( @@ROWCOUNT )

SELECT @STEP = 1

UPDATE BEST..TSEGCRITERIA
set SGTCRI_CF = 'SBS_INDICATOR', SGTCRI_LS = 'SBS indicator? (Y/N)'
, SGTCRITYP_CT = '3', SGTCRICTL_CT='1', SGTCRISUBCAT_NT=4, SGTCRIPAR_LS = NULL
where SGTUWCOL_CF='FACADMTYP_CT'

UPDATE #COUNTCHECK SET UPDATECOUNT = @@ROWCOUNT WHERE STEP = @STEP

SELECT @STEP = 2

UPDATE BEST..TSEGUWCOLUMN 
SET SGTUWTYP_CT='bit'
WHERE SGTUWCOL_CF='FACADMTYP_CT'

UPDATE #COUNTCHECK SET UPDATECOUNT = @@ROWCOUNT WHERE STEP = @STEP

SELECT SELECTCOUNT,UPDATECOUNT FROM #COUNTCHECK

SELECT * FROM #COUNTCHECK WHERE SELECTCOUNT != UPDATECOUNT
if @@rowcount != 0
BEGIN
	PRINT 'Counts does not match, Transaction will be rollbacked'
	ROLLBACK TRAN
	goto fin
END

PRINT 'AFTER UPDATE'
SELECT 'TSEGCRITERIA TABLE'
SELECT * FROM BEST..TSEGCRITERIA WHERE SGTUWCOL_CF='FACADMTYP_CT'

SELECT 'TSEGUWCOLUMN TABLE'
SELECT * FROM BEST..TSEGUWCOLUMN WHERE SGTUWCOL_CF='FACADMTYP_CT'


IF @gCommit = 'O'
    BEGIN
        COMMIT TRAN
        PRINT 'COMMIT SUCCESSFUL'
    END
ELSE
    BEGIN
        ROLLBACK TRAN
        PRINT 'ROLLBACK SUCCESSFUL'
    END

fin:

select @endTime = getdate()

select 'Script Time', datediff(ss, @startTime, @endTime), 'seconds'

SET NOCOUNT OFF

GO