--Script to add new profile function and TFUNCTION
--Changes made for SPIRA 110667
-- Author : Riyadh

-- Change function 919554, 919557


USE BREF
GO


IF EXISTS( select 1 from BREF..TPROFILFUNC where FUNC_CF = 919557 and APP_CF = 'EST' and PRF_CF in('DUS01') )
BEGIN
exec(" DELETE  from BREF..TPROFILFUNC where FUNC_CF = 919557  ")
END
go

IF EXISTS( select 1 from BREF..TPROFILFUNC where FUNC_CF = 919554 and APP_CF = 'EST' and PRF_CF in('PUBLIC') )
BEGIN
exec(" DELETE  from BREF..TPROFILFUNC where FUNC_CF = 919554  ")
END
go

IF EXISTS( select 1 from BREF..TFUNCTION where FUNC_CF = 919557 and APP_CF = 'EST'  )
BEGIN
exec(" DELETE  from BREF..TFUNCTION where FUNC_CF = 919557 and APP_CF = 'EST' " )
END
go

IF EXISTS( select 1 from BREF..TFUNCTION where FUNC_CF = 919554 and APP_CF = 'EST'  )
BEGIN
exec(" DELETE  from BREF..TFUNCTION where FUNC_CF = 919554 and APP_CF = 'EST' " )
END
go

INSERT INTO TPROFILFUNC (FUNC_CF, APP_CF, PRF_CF) VALUES (919557, 'EST', 'DUS01')
GO

INSERT INTO TPROFILFUNC (FUNC_CF, APP_CF, PRF_CF) VALUES (919554, 'EST', 'PUBLIC')
GO

INSERT INTO TFUNCTION (FUNC_CF, APP_CF, FUNC_LS, FUNC_LD, BATDEP_B, UPDATE_B, FNTYP_CT) VALUES (919557, 'EST', 'U Local Entity', 'Update Local Closing Entity',1, 1, 0)
go

INSERT INTO TFUNCTION (FUNC_CF, APP_CF, FUNC_LS, FUNC_LD, BATDEP_B, UPDATE_B, FNTYP_CT) VALUES (919554, 'EST', 'V Local Entity', 'Access to Local Closing Entity',0, 0, 0)
go



