/*
DESCRIPTION - Spira 82100 Enhacement for -Segment creation - Add "Ultimate Group Cedent" in Criteria drilldown menu
AUTHOR - Parth
DATE - 24/04/2020

*/
use BEST
GO

PRINT 'SELECT RECORDS THAT ALREADY EXISTS'
SELECT * FROM BEST..TSEGCRITERIA WHERE SGTCRI_CF = 'CLI_ULT_GROUP' AND SGTCRISUBCAT_NT = 1 AND SGTUWCOL_CF= 'CEDULT_NF'
SELECT * FROM BEST..TSEGUWCOLUMN WHERE SGTUWTAB_CF = 'TSEGUWASMSEC' AND SGTUWCOL_CF = 'CEDULT_NF'


BEGIN TRAN

PRINT 'DELETION IF RECORD EXISTS'

DELETE FROM BEST..TSEGCRITERIA where SGTCRI_CF = 'CLI_ULT_GROUP' AND SGTCRISUBCAT_NT = 1 AND SGTUWCOL_CF= 'CEDULT_NF' 
DELETE FROM  BEST..TSEGUWCOLUMN where SGTUWTAB_CF = 'TSEGUWASMSEC' AND SGTUWCOL_CF = 'CEDULT_NF'


PRINT 'INSERTION'

INSERT INTO BEST..TSEGUWCOLUMN ( SGTUWTAB_CF, SGTUWCOL_CF, SGTUWCOL_LS, SGTUWTYP_CT, SGTUWORDER_NB, SGTUWLEN_NB, SGTUWSCA_NB, SGTUWPRE_NB, CRE_D, CREUSR_CF, LSTUPD_D, LSTUPDUSR_CF ) 
        VALUES ( 'TSEGUWASMSEC', 'CEDULT_NF', 'ULTIMATE_GROUP_CEDENT', 'UHLD_NF                         ', 189, NULL, NULL, NULL, getdate(), 'UBEU', getdate(), 'UBEU'  )


INSERT
    INTO
        BEST..TSEGCRITERIA
        (
            SGTCRI_CF,
            SGTCRISUBCAT_NT,
            SGTUWCOL_CF,
            SGTCRI_LS,
            SGTCRITYP_CT,
            SGTCRICTL_CT,
            SGTCRIPAR_LS,
            CRE_D,
            CREUSR_CF,
            LSTUPD_D,
            LSTUPDUSR_CF,
            timestamp
        )
    VALUES
        (
            'CLI_ULT_GROUP',
            1,
            'CEDULT_NF',
            'Ultimate Group Cedent',
            '1',
            '1',
            NULL,
            GETDATE (),
            'UBEU',
            GETDATE (),
            'UBEU',
            NULL
        )
		
PRINT 'DATA AFTER INSERTION'
SELECT * FROM BEST..TSEGCRITERIA WHERE SGTCRI_CF = 'CLI_ULT_GROUP' AND SGTCRISUBCAT_NT = 1 AND SGTUWCOL_CF = 'CEDULT_NF'
SELECT * FROM BEST..TSEGUWCOLUMN WHERE SGTUWTAB_CF = 'TSEGUWASMSEC' AND SGTUWCOL_CF = 'CEDULT_NF'

COMMIT TRAN

go
        