USE BEST
Go

/*IFRS17 I17P*/
IF NOT EXISTS
      (SELECT 1
         FROM BEST..TI17REQ
        WHERE REQCOD_CT = 'AUTO')
   INSERT INTO BEST..TI17REQ (REQCOD_CT,REQCOD_LL) VALUES ('AUTO','Automatic Planification')
GO

