use BEST
go

/*==============================================================*/
/* Table: TCTREST                                               */
/*==============================================================*/

UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=2018
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=2017
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=2016
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=2015
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=2014
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=2013
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=2012
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=2011
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=2010
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=2009
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=2008
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=2007
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=2006
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=2005
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=2004
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=2003
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=2002
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=2001
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=2000
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1999
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1998
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1997
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1996
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1995
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1994
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1993
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1992
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1991
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1990
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1989
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1988
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1987
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1986
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1985
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1984
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1983
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1982
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1981
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1980
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1979
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1978
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1977
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1976
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1975
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1974
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1973
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1972
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1971
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1970
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1969
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1968
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1967
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1966
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1965
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1964
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1963
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1962
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1961
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1960
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1959
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1958
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1957
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1956
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1955
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1954
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1953
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1952
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1951
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1950
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1949
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1948
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1947
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1946
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1945
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1944
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1943
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1942
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1941
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1940
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1939
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1938
GO
UPDATE TCTREST SET CMT_NT = NULL WHERE CMT_NT = 0 and UWY_NF=1937
GO
