USE BEST 
go 
delete from dbo.TI17PERMFIL_H
go
insert into dbo.TI17PERMFIL_H (IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL, ACTION_D, ACTIONTYP_CT, CRE_D, CREUSR_CF)
select IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL, getdate(), "I", getdate(), suser_name() from dbo.TI17PERMFIL
go
delete from BTRAV..TI17PERMFIL_T
go
insert into BTRAV..TI17PERMFIL_T (IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL, ACTION_D, ACTIONTYP_CT, CRE_D, CREUSR_CF)
select IDF_CT, PERMFIL_CT, PATHPATTRN_LL, IO, PERM_LL, ACTION_D, ACTIONTYP_CT, CRE_D, CREUSR_CF from dbo.TI17PERMFIL_H
go
