USE BTEC
GO
set nocount on

-- ###############################################################################
-- Script           			: SPIRA_87988_ESFD3980.sql
-- Domain	          			: CLI
-- Author           			: Charles Socie
-- Date of creation				: 27/10/2020
-- ################################################################################

DECLARE @gCommit VARCHAR (01)
DECLARE @gCount INT
SELECT @gCommit = 'O'
select @gCount = 0

BEGIN TRAN
PRINT 'CHECK IF DATA ARE ALREADY IN DATA BASE'
select @gCount = count(*) from BTEC..TFILSUP where DOM_CF LIKE '%3980%'


IF @gCount = 0
    BEGIN
		INSERT INTO BTEC.dbo.TFILSUP(DOM_CF, NUM_NF, PRDSIT_CF)
		VALUES('3980I17G', 0, 'USA1')

		INSERT INTO BTEC.dbo.TFILSUP(DOM_CF, NUM_NF, PRDSIT_CF)
		VALUES('3980I17G', 0, 'FRA1')

		INSERT INTO BTEC.dbo.TFILSUP(DOM_CF, NUM_NF, PRDSIT_CF)
		VALUES('3980I17G', 0, 'SGP1')
		
		
		INSERT INTO BTEC.dbo.TFILSUP(DOM_CF, NUM_NF, PRDSIT_CF)
		VALUES('3980I17P', 0, 'USA1')

		INSERT INTO BTEC.dbo.TFILSUP(DOM_CF, NUM_NF, PRDSIT_CF)
		VALUES('3980I17P', 0, 'FRA1')

		INSERT INTO BTEC.dbo.TFILSUP(DOM_CF, NUM_NF, PRDSIT_CF)
		VALUES('3980I17P', 0, 'SGP1')
		
		
		INSERT INTO BTEC.dbo.TFILSUP(DOM_CF, NUM_NF, PRDSIT_CF)
		VALUES('3980I17L', 0, 'USA1')

		INSERT INTO BTEC.dbo.TFILSUP(DOM_CF, NUM_NF, PRDSIT_CF)
		VALUES('3980I17L', 0, 'FRA1')

		INSERT INTO BTEC.dbo.TFILSUP(DOM_CF, NUM_NF, PRDSIT_CF)
		VALUES('3980I17L', 0, 'SGP1')
        PRINT 'INSERT DATA INTO BTEC..TFILSUP'
    END
ELSE
    BEGIN
		delete  from BTEC..TFILSUP where DOM_CF = 'ESFD3980'
				INSERT INTO BTEC.dbo.TFILSUP(DOM_CF, NUM_NF, PRDSIT_CF)
		VALUES('3980I17G', 0, 'USA1')

		INSERT INTO BTEC.dbo.TFILSUP(DOM_CF, NUM_NF, PRDSIT_CF)
		VALUES('3980I17G', 0, 'FRA1')

		INSERT INTO BTEC.dbo.TFILSUP(DOM_CF, NUM_NF, PRDSIT_CF)
		VALUES('3980I17G', 0, 'SGP1')
		
		
		INSERT INTO BTEC.dbo.TFILSUP(DOM_CF, NUM_NF, PRDSIT_CF)
		VALUES('3980I17P', 0, 'USA1')

		INSERT INTO BTEC.dbo.TFILSUP(DOM_CF, NUM_NF, PRDSIT_CF)
		VALUES('3980I17P', 0, 'FRA1')

		INSERT INTO BTEC.dbo.TFILSUP(DOM_CF, NUM_NF, PRDSIT_CF)
		VALUES('3980I17P', 0, 'SGP1')
		
		
		INSERT INTO BTEC.dbo.TFILSUP(DOM_CF, NUM_NF, PRDSIT_CF)
		VALUES('3980I17L', 0, 'USA1')

		INSERT INTO BTEC.dbo.TFILSUP(DOM_CF, NUM_NF, PRDSIT_CF)
		VALUES('3980I17L', 0, 'FRA1')

		INSERT INTO BTEC.dbo.TFILSUP(DOM_CF, NUM_NF, PRDSIT_CF)
		VALUES('3980I17L', 0, 'SGP1')
        PRINT 'DELETE AND INSERT DATA INTO BTEC..TFILSUP'
    END

IF @gCommit = 'O'
    BEGIN
        COMMIT TRAN
        PRINT 'COMMIT SUCCESSFUL'
    END
ELSE
    BEGIN
        ROLLBACK TRAN
        PRINT 'ROLLBACK SUCCESSFUL'
    END

set nocount off

GO
