USE BTEC
GO
set nocount on

-- ###############################################################################
-- Script           			: SPIRA_82584_ESFD3820.sql
-- Domain	          			: CLI
-- Author           			: Charles Socie
-- Date of creation				: 15/04/2020
-- ################################################################################

DECLARE @gCommit VARCHAR (01)
DECLARE @gCount INT
SELECT @gCommit = 'O'
select @gCount = 0

BEGIN TRAN
PRINT 'CHECK IF DATA ARE ALREADY IN DATA BASE'
select @gCount = count(*) from BTEC..TFILSUP where DOM_CF LIKE '%3820%'


IF @gCount = 0
    BEGIN
		INSERT INTO BTEC.dbo.TFILSUP(DOM_CF, NUM_NF, PRDSIT_CF)
		VALUES('3820I17G', 0, 'USA1')

		INSERT INTO BTEC.dbo.TFILSUP(DOM_CF, NUM_NF, PRDSIT_CF)
		VALUES('3820I17G', 0, 'FRA1')

		INSERT INTO BTEC.dbo.TFILSUP(DOM_CF, NUM_NF, PRDSIT_CF)
		VALUES('3820I17G', 0, 'SGP1')
		
		
		INSERT INTO BTEC.dbo.TFILSUP(DOM_CF, NUM_NF, PRDSIT_CF)
		VALUES('3820I17P', 0, 'USA1')

		INSERT INTO BTEC.dbo.TFILSUP(DOM_CF, NUM_NF, PRDSIT_CF)
		VALUES('3820I17P', 0, 'FRA1')

		INSERT INTO BTEC.dbo.TFILSUP(DOM_CF, NUM_NF, PRDSIT_CF)
		VALUES('3820I17P', 0, 'SGP1')
		
		
		INSERT INTO BTEC.dbo.TFILSUP(DOM_CF, NUM_NF, PRDSIT_CF)
		VALUES('3820I17L', 0, 'USA1')

		INSERT INTO BTEC.dbo.TFILSUP(DOM_CF, NUM_NF, PRDSIT_CF)
		VALUES('3820I17L', 0, 'FRA1')

		INSERT INTO BTEC.dbo.TFILSUP(DOM_CF, NUM_NF, PRDSIT_CF)
		VALUES('3820I17L', 0, 'SGP1')
        PRINT 'INSERT DATA INTO BTEC..TFILSUP'
    END
ELSE
    BEGIN
		delete  from BTEC..TFILSUP where DOM_CF LIKE '%3820%'
		INSERT INTO BTEC.dbo.TFILSUP(DOM_CF, NUM_NF, PRDSIT_CF)
		VALUES('3820I17G', 0, 'USA1')

		INSERT INTO BTEC.dbo.TFILSUP(DOM_CF, NUM_NF, PRDSIT_CF)
		VALUES('3820I17G', 0, 'FRA1')

		INSERT INTO BTEC.dbo.TFILSUP(DOM_CF, NUM_NF, PRDSIT_CF)
		VALUES('3820I17G', 0, 'SGP1')
		
		
		INSERT INTO BTEC.dbo.TFILSUP(DOM_CF, NUM_NF, PRDSIT_CF)
		VALUES('3820I17P', 0, 'USA1')

		INSERT INTO BTEC.dbo.TFILSUP(DOM_CF, NUM_NF, PRDSIT_CF)
		VALUES('3820I17P', 0, 'FRA1')

		INSERT INTO BTEC.dbo.TFILSUP(DOM_CF, NUM_NF, PRDSIT_CF)
		VALUES('3820I17P', 0, 'SGP1')
		
		
		INSERT INTO BTEC.dbo.TFILSUP(DOM_CF, NUM_NF, PRDSIT_CF)
		VALUES('3820I17L', 0, 'USA1')

		INSERT INTO BTEC.dbo.TFILSUP(DOM_CF, NUM_NF, PRDSIT_CF)
		VALUES('3820I17L', 0, 'FRA1')

		INSERT INTO BTEC.dbo.TFILSUP(DOM_CF, NUM_NF, PRDSIT_CF)
		VALUES('3820I17L', 0, 'SGP1')
        PRINT 'DELETE AND INSERT DATA INTO BTEC..TFILSUP'
    END

IF @gCommit = 'O'
    BEGIN
        COMMIT TRAN
        PRINT 'COMMIT SUCCESSFUL'
    END
ELSE
    BEGIN
        ROLLBACK TRAN
        PRINT 'ROLLBACK SUCCESSFUL'
    END

set nocount off

GO
