update   BEST..TI17PERMFIL  set PATHPATTRN_LL = str_replace(PATHPATTRN_LL,"${PARM_POSX}","") 
 
 
 
select  "UPDATE  BEST..TI17PERMFIL SET PATHPATTRN_LL = '" +
		str_replace (PATHPATTRN_LL,".dat","${PARM_POSX}.dat") + 
		"' WHERE IDF_CT='" + IDF_CT + 
		"' AND PERMFIL_CT ='" + PERMFIL_CT + "'"
FROM BEST..TI17PERMFIL 
where PATHPATTRN_LL not like "%${PARM_PREV_ICLODAT_D}%" AND
 IDF_CT like  'I17[LP]%' and 
--IDF_CT  in (select distinct IDF_CT from BEST..TI17REQFNC where IDF_CT not like '%INI%' and (REQCOD_CT like 'I17[LP]%POS') ) and 
( 
    --PATHPATTRN_LL like "%_ESFD3780_I17[LP]_CSM_ACC_STD_CSM_LC_FTECLEDA_%"				or
    --PATHPATTRN_LL like "%_ESFD3750_I17[LP]_CSM_ALL_STD_PROF_BY_CTR_%"					or
    --PATHPATTRN_LL like "%_ESFD4010_I17[LP]_PAA_ALL_STD_PAA_ASSUM_%"					or
    --PATHPATTRN_LL like "%_ESFD4010_I17[LP]_PAA_ALL_STD_PAA_RETRO%"						or
    --PATHPATTRN_LL like "%_ESPD1800_I17[LP]_AET_RPO_I17_IADPERICASE_I17_MERGE_%"		or
    --PATHPATTRN_LL like "%_ESFD5020_IRDPERICASE0_I17[LP]_${TYPEINV}_%"					or
    --PATHPATTRN_LL like "%_ESFD3730_I17[LP]_SII_ALL_STD_FTECLEDSII_%"					or
    --PATHPATTRN_LL like "%_ESFD3730_I17[LP]_SII_ALL_STD_GTSII_RISKMARGIN${TYPEINV}_%"	or
    --PATHPATTRN_LL like "%_ESFD3630_I17[LP]_IEX_ALL_STD_GTSII_GLOBAL_CASHFLOW_%"		or
    --PATHPATTRN_LL like "%_ESFD3640_I17[LP]_IVR_CHR_STD_DAC_LKI_CASHFLOW_%"				or
    --PATHPATTRN_LL like "%_ESFD3760_I17[LP]_UOA_PRO_STD_FSEGPROF_${TYPEINV}_%"			

	-- pour le transfert RA SAP
	PATHPATTRN_LL like "%_ESFD3840_I17[LP]_GLT_MRG_STD_FTECLEDA_MVT_%.dat" or
	PATHPATTRN_LL like "%_ESFD3840_I17P_GLT_MRG_STD_FTECLEDR_MVT_%.dat" or
	PATHPATTRN_LL like "%_ESFD3730_I17[LP]_SII_ALL_STD_FTECLEDSII_% .dat" or

	-- à merger pour le Q+1
	PATHPATTRN_LL like "%_ESFD3760_I17[LP]_UOA_PRO_STD_FSEGPROF_%.dat" or
	PATHPATTRN_LL like "%_ESFD3620_I17[LP]_DSC_LKI_STD_GTSII_ESCOMPTE_%.dat" or
	PATHPATTRN_LL like "%_ESFD3620_I17[LP]_RAD_LKI_STD_GTSII_ESCOMPTE_%.dat" or
	PATHPATTRN_LL like "%_ESFD3630_I17[LP]_IEX_ALL_STD_GTSII_GLOBAL_CASHFLOW_%.dat" or
	PATHPATTRN_LL like "%_ESFD3650_I17[LP]_RAD_CKI_STD_GTSII_CASHFLOW_%.dat" or
	PATHPATTRN_LL like "%_ESFD1130_FSEGPATTERNDSCf17_I17[LP]_%.dat" or
	--PATHPATTRN_LL like "%_ESFD3770_CSM_LC_AMORT_PATTERN_EBS_%.dat" or
	PATHPATTRN_LL like "%_ESFD3770_CSM_LC_AMORT_PATTERN_EBS_%.dat" or
	PATHPATTRN_LL like "%_ESFD3630_I17[LP]_IEX_ALL_STD_GTSII_GLOBAL_CASHFLOW_%.dat" or
	PATHPATTRN_LL like "%_ESFD3630_I17[LP]_IEX_ALL_STD_GTSII_GLOBAL_CASHFLOW_%.dat" or
	PATHPATTRN_LL like "%_ESFD3770_CSM_LC_AMORT_PATTERN_EBS_%.dat" or
	PATHPATTRN_LL like "%_ESFD3640_I17[LP]_IVR_CHR_STD_DAC_LKI_CASHFLOW_%.dat" or
	PATHPATTRN_LL like "%_ESFD4020_DLCUMGTAAR_ITD_EBS_%.dat" or
	PATHPATTRN_LL like "%_ESFD3770_CSM_LC_AMORT_PATTERN_EBS_%.dat" or
	PATHPATTRN_LL like "%_ESFD3760_I17[LP]_UOA_PRO_STD_FSEGPROF_%.dat" or
	PATHPATTRN_LL like "%_ESFD3760_I17[LP]_UOA_PRO_STD_GTSII_CSM_CASHFLOW_%.dat" or
	PATHPATTRN_LL like "%_ESFD1130_FSEGPATTERNDSCf17_I17[LP]_%.dat" or
	PATHPATTRN_LL like "%_ESFD3770_CSM_LC_AMORT_PATTERN_EBS_%.dat" or
	PATHPATTRN_LL like "%_ESFD3870_I17[LP]_GLT_ALL_STD_FTECLEDA_${TYPEINV}_%.dat" or
	PATHPATTRN_LL like "%_ESFD3870_I17[LP]_GLT_ALL_STD_FTECLEDA_${TYPEINV}_%.dat"
) 
order by 1


