--use BTRAVI
--go
--drop table ESFD5010

--select * into BTRAVI..ESFD5010_SAVE from BEST..TI17PERMFIL 
--where PATHPATTRN_LL like "${DFILP}/${ENV_PREFIX}_ESCJ0660%" 
--and (IDF_CT like 'EBS%' or IDF_CT like 'I17%' )
--and IDF_CT not in ( 'EBS_ESCJ0660' ,'EBS_ESFD5010')
--order by PERMFIL_CT
--
update BEST..TI17PERMFIL
set PATHPATTRN_LL = case
	when PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESCJ0660_FCTRGRO0.dat'                  then '${DFILP}/${ENV_PREFIX}_ESFD5010_FCTRGRO0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat'
	when PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESCJ0660_FPLACEMT2.dat'                 then '${DFILP}/${ENV_PREFIX}_ESFD5010_FPLACEMT2_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat'
	when PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESCJ0660_CADVPERIESB0.dat'              then '${DFILP}/${ENV_PREFIX}_ESFD5010_CADVPERIESB0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat'
	when PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESCJ0660_FTVENTNP.dat'                  then '${DFILP}/${ENV_PREFIX}_ESFD5010_FTVENTNP_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat'
	--when PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESCJ0660_FTVENTNPANT.dat'                  then '${DFILP}/${ENV_PREFIX}_ESFD5010_FVENTNPANT_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat'
	when PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESCJ0660_FCTRGRO.dat'                   then '${DFILP}/${ENV_PREFIX}_ESFD5010_FCTRGRO_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat'
	when PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESCJ0660_FCTRULT.dat'                   then '${DFILP}/${ENV_PREFIX}_ESFD5010_FCTRULT_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat'
	when PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESCJ0660_FPLATXCUM0.dat'                then '${DFILP}/${ENV_PREFIX}_ESFD5010_FPLATXCUM0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat'
	when PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESCJ0660_FPLATXCUM.dat'                 then '${DFILP}/${ENV_PREFIX}_ESFD5010_FPLATXCUM_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat'
	when PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESCJ0660_IADPERIFCI.dat'                then '${DFILP}/${ENV_PREFIX}_ESFD5010_IADPERIFCI_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat'
	when PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESCJ0660_IADPERIFCT.dat'                then '${DFILP}/${ENV_PREFIX}_ESFD5010_IADPERIFCT_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat'
	when PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESCJ0660_IADPERIFR.dat'                 then '${DFILP}/${ENV_PREFIX}_ESFD5010_IADPERIFR_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat'
	when PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESCJ0660_IRDPERICASE0.dat'              then '${DFILP}/${ENV_PREFIX}_ESFD5010_IRDPERICASE0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat'
	when PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESCJ0660_FPLATXCUMALL0.dat'             then '${DFILP}/${ENV_PREFIX}_ESFD5010_FPLATXCUMALL0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat'
	when PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESCJ0660_FCTRGROLESII.dat'              then '${DFILP}/${ENV_PREFIX}_ESFD5010_FCTRGROLESII_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat'
	when PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESCJ0660_IADPERICASE_ENTIER0.dat'       then '${DFILP}/${ENV_PREFIX}_ESFD5010_IADPERICASE_ENTIER0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat'
	when PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESCJ0660_IADPERICASE0.dat'              then '${DFILP}/${ENV_PREFIX}_ESFD5010_IADPERICASE0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat'
	when PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESCJ0660_IADVPERICASE.dat'              then '${DFILP}/${ENV_PREFIX}_ESFD5010_IADVPERICASE_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat'
	when PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESCJ0660_OIRDVPERICASE.dat'             then '${DFILP}/${ENV_PREFIX}_ESFD5010_OIRDVPERICASE_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat'
	when PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESCJ0660_IADPERICASE.dat'               then '${DFILP}/${ENV_PREFIX}_ESFD5010_IADPERICASE_STD_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat'
	when PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESCJ0660_FPLCCOM.dat'                   then '${DFILP}/${ENV_PREFIX}_ESFD5010_FPLCCOM_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat'
	when PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESCJ0660_FCTRGRO1.dat'                  then '${DFILP}/${ENV_PREFIX}_ESFD5010_FCTRGRO1_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat'
	when PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESCJ0660_FPLC.dat'                      then '${DFILP}/${ENV_PREFIX}_ESFD5010_FPLC_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat'
	when PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESCJ0660_FCES.dat'                      then '${DFILP}/${ENV_PREFIX}_ESFD5010_FCES_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat'
	when PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESCJ0660_FCESSION0.dat'                 then '${DFILP}/${ENV_PREFIX}_ESFD5010_FCESSION0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat'
	when PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESCJ0660_CTRULT02.dat'                  then '${DFILP}/${ENV_PREFIX}_ESFD5010_CTRULT02_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat'
	when PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESCJ0660_FSSDACTR_TXT.dat'              then '${DFILP}/${ENV_PREFIX}_ESFD5010_FSSDACTR_TXT_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat'
	when PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESCJ0660_FPLACEMT0.dat'                 then '${DFILP}/${ENV_PREFIX}_ESFD5010_FPLACEMT0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat'
	when PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESCJ0660_FPLACEMT1.dat'                 then '${DFILP}/${ENV_PREFIX}_ESFD5010_FPLACEMT1_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat'
	when PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESCJ0660_IARVPERICASE0.dat'             then '${DFILP}/${ENV_PREFIX}_ESFD5010_IARVPERICASE0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat'
	when PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESCJ0660_IRDVPERICASE.dat'              then '${DFILP}/${ENV_PREFIX}_ESFD5010_IRDVPERICASE_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat'
	when PATHPATTRN_LL = '${DFILP}/${ENV_PREFIX}_ESCJ0660_CRVPERICASE0.dat'              then '${DFILP}/${ENV_PREFIX}_ESFD5010_CRVPERICASE0_EBS_${PARM_TYPEINV2}_${PARM_ICLODAT_D}.dat'
	else   PATHPATTRN_LL                                                                     
end
where PATHPATTRN_LL like "${DFILP}/${ENV_PREFIX}_ESCJ0660%" 
and (IDF_CT like 'EBS%' or IDF_CT like 'I17%' )
and IDF_CT not in ( 'EBS_ESCJ0660' ,'EBS_ESFD5010')

go


--select distinct s.PERMFIL_CT ,  s.PATHPATTRN_LL, p.PATHPATTRN_LL "NEW PATHPATTRN_LL" from BTRAVI..ESFD5010_SAVE s
--left outer join BEST..TI17PERMFIL p on s.IDF_CT = p.IDF_CT and s.PERMFIL_CT = p.PERMFIL_CT
