[properties]
root_delivery="/scor/scoromega/delivery/3F_DELIVERY/"
listComponentsFile="/scor/scoromega/delivery/3F_DELIVERY/OM2.DELIVERY/OM2MAINT.3F_DELIVERY_IN2.csv"
listCtrComponentsFile="/scor/scoromega/runnable/uti/scripts/3F_SpiraListCheck.csv"
branches=http://dcvprdsvn/refsvn/OMEGA-2/branches/3F_DEV/omega2-sql/global/
branches2=http://dcvprdsvn.eu.scor.local/refsvn/OMEGA-2/branches/3F_DEV/omega2-sql/global/
