[properties]
root_delivery="/scor/scoromega/delivery/3F_DEV/"
listComponentsFile="/scor/scoromega/delivery/OM2.DELIVERY/OM2.3F_DELIVERY_DEV.csv"
listCtrComponentsFile="/scor/scoromega/runnable/uti/scripts/3F_SpiraListCheck_DEV.csv"
branches=http://dcvprdsvn/refsvn/OMEGA-2/branches/3F_DEV/omega2-sql/global/
