[properties]
root_delivery="/scor/scoromega/delivery/3G_DELIVERY/"
listComponentsFile="/scor/scoromega/delivery/OM2.DELIVERY/OM2.3G_DELIVERY_CNV.csv"
listCtrComponentsFile="/scor/scoromega/runnable/uti/scripts/3G_SpiraListCheck.csv"
branches=http://dcvprdsvn/refsvn/OMEGA-2/branches/3G_DEV/omega2-sql/global/
branches2=http://dcvprdsvn.eu.scor.local/refsvn/OMEGA-2/branches/3G_DEV/omega2-sql/global/
