#!/bin/ksh
#=============================================================================
# nom de l'application          : Get data for automatic closing data files archiving
# nom du script SHELL           : ESARCH20.cmd
# revision                      : 
# date de creation              : 20/03/2026
# auteur                        : G.GRUDZINSKI
# references des specifications : US8835
#-----------------------------------------------------------------------------
# description
#  extraction 
# parameters: 
#		ESARCH20.env
#
#-----------------------------------------------------------------------------
# historiques des modifications
# Modifié le            Par                 Desc.
#---------------
#Creation	    : 
#Auteur         : G.GRUDZINSKI
#Date           : 20/03/2026
#Version        : 1.0
#Description    : 20/03/2026 :G.GRUDZINSKI US8835 : Automatic closing data files archiving
#===============================================================================
#set -x


# Call generic functions
. ${DUTI}/fctgen.cmd

#set +x


# Chain Initialization variables
CHAININIT $0 $1

IDF_CT="$2"


NJOB="ESFD9001"
# Launch applicative job ESCD9001
. ${DCMD}/ESFD9001.cmd "$IDF_CT"


# Launch applicative job ESARCH21
NJOB="ESARCH21"
${DCMD}/ESARCH21.cmd 2>&1 | ${TEE}

# Launch applicative job ESARCH22; the script is generated by ESARCH21 using ESARCHLIB.cmd
# which creates the name ending in _ESARCH12.cmd, so the file name below (ending in ESARCH12.cmd)
# is not a typo.
NJOB="ESARCH22"
${DFILT}/${NCHAIN}_${IB}_ZIP_ESARCH12.cmd 2>&1 | ${TEE}


CHAINEND

