#!/bin/ksh
#=============================================================================
# nom de l'application          : IRFS17 night closing
# nom du script SHELL           : ESFD3661.cmd
# revision                      : $Revision:   1.0  $
# date de creation              : 26\06\2019
# auteur                        : Antoine GRUNWALD
#-----------------------------------------------------------------------------
# description
#  IFRS17 REQ 11.5 : Forward discount and unwind discount calculation
#
#[01] US7841 HR 27/01/2026 EBS  Unwind for SII AoC - Cash flow calculation 
#-----------------------------------------------------------------------------
#=============================================================================

# Call generic functions
. ${DUTI}/fctgen.cmd
. ${DUTI}/fctjsb.cmd

# Job Initialisation
JOBINIT

ECHO_LOG "#========================================================================="
ECHO_LOG "#===> ICLODAT_D........................................................: ${PARM_ICLODAT_D}"
ECHO_LOG "#===> NORME_CF.........................................................: ${NORME_CF}"

ECHO_LOG "#===> ............ INPUT ................................................."
ECHO_LOG "#===> ESF_GTSII_GLOBAL_CASHFLOW_RAD....................................: ${ESF_GTSII_GLOBAL_CASHFLOW_RAD}"
ECHO_LOG "#===> ESF_GTSII_GLOBAL_CASHFLOW_RAD_PREV...............................: ${ESF_GTSII_GLOBAL_CASHFLOW_RAD_PREV}"
ECHO_LOG "#===> ESF_GTSII_ESCOMPTE_RAD...........................................: ${ESF_GTSII_ESCOMPTE_RAD}"
ECHO_LOG "#===> ESF_GTSII_ESCOMPTE_RAD_PREVCLODAT................................: ${ESF_GTSII_ESCOMPTE_RAD_PREVCLODAT}"
ECHO_LOG "#===> ESF_GTSII_GLOBAL_CASHFLOW........................................: ${ESF_GTSII_GLOBAL_CASHFLOW}"
ECHO_LOG "#===> ESF_GTSII_GLOBAL_CASHFLOW_PREV...................................: ${ESF_GTSII_GLOBAL_CASHFLOW_PREV}"
ECHO_LOG "#===> ESF_GTSII_ESCOMPTE...............................................: ${ESF_GTSII_ESCOMPTE}"
ECHO_LOG "#===> ESF_GTSII_ESCOMPTE_PREVCLODAT....................................: ${ESF_GTSII_ESCOMPTE_PREVCLODAT}"
ECHO_LOG "#===> ESF_FSEGPATTERNDSCf17............................................: ${ESF_FSEGPATTERNDSCf17}"
ECHO_LOG "#===> EPO_FCURSII......................................................: ${EPO_FCURSII}"
ECHO_LOG "#===> ESF_TRERETFACCTR.................................................: ${ESF_TRERETFACCTR}"
ECHO_LOG "#===> ESF_FPRSMAP_TXT..................................................: ${ESF_FPRSMAP_TXT}"

ECHO_LOG "#===> ............ OUTPUT ................................................."
ECHO_LOG "#===> ESF_GTSII_ESCOMPTE_FWD...........................................: ${ESF_GTSII_ESCOMPTE_FWD}"
ECHO_LOG "#========================================================================="

NSTEP=${NJOB}_1
#------------------------------------------------------------------------------

# inputs files
export ESTJ0001_RAD_ESCOMPTE="${ESF_GTSII_ESCOMPTE_RAD}"
export ESTJ0001_RAD_ESCOMPTE_PREV="${ESF_GTSII_ESCOMPTE_RAD_PREVCLODAT}"
export ESTJ0001_RAD_CASHFLOW="${ESF_GTSII_GLOBAL_CASHFLOW_RAD}"
export ESTJ0001_RAD_CASHFLOW_PREV="${ESF_GTSII_GLOBAL_CASHFLOW_RAD_PREV}"
export ESTJ0001_ESCOMPTE="${ESF_GTSII_ESCOMPTE}"
export ESTJ0001_ESCOMPTE_PREV="${ESF_GTSII_ESCOMPTE_PREVCLODAT}"
export ESTJ0001_CASHFLOW="${ESF_GTSII_GLOBAL_CASHFLOW}"
export ESTJ0001_CASHFLOW_PREV="${ESF_GTSII_GLOBAL_CASHFLOW_PREV}"
export ESTJ0001_CONTRACT_RATE_INDEX="${ESF_TRERETFACCTR}"
export ESTJ0001_CURRENCY="${EPO_FCURSII}"
export ESTJ0001_PATTERN="${ESF_FSEGPATTERNDSCf17}"
export ESTJ0001_GROUPING_LIST="${ESF_FPRSMAP_TXT}"

# tmp files
export ESTJ0001_CASHFLOW_MERGED="${DFILT}/${NJOB}_1_${IB}_MERGED_CASHFLOW.dat"
export ESTJ0001_FWD="${DFILT}/${NJOB}_1_${IB}_FWD_UNSORTED.dat"
export ESTJ0001_SORTED_CASHFLOW_ASSUM="${DFILT}/${NJOB}_1_${IB}_SORTED_CASHFLOW_ASSUM.dat"
export ESTJ0001_SORTED_CASHFLOW_RETRO_P="${DFILT}/${NJOB}_1_${IB}_SORTED_CASHFLOW_RETRO_P.dat"
export ESTJ0001_SORTED_CASHFLOW_RETRO_NP="${DFILT}/${NJOB}_1_${IB}_SORTED_CASHFLOW_RETRO_NP.dat"
export ESTJ0001_CASHFLOW_MERGED_WITH_GROUPING="${DFILT}/${NJOB}_1_${IB}_CASHFLOW_MERGED_WITH_GROUPING.dat"
export ESTJ0001_SORTED_CASHFLOW_WITH_GROUPING_ASSUM="${DFILT}/${NJOB}_1_${IB}_SORTED_CASHFLOW_WITH_GROUPING_ASSUM.dat"
export ESTJ0001_SORTED_CASHFLOW_WITH_GROUPING_RETRO="${DFILT}/${NJOB}_1_${IB}_SORTED_CASHFLOW_WITH_GROUPING_RETRO.dat"
export ESTJ0001_AGGREGATED_CASHFLOW_BY_GROUPING="${DFILT}/${NJOB}_1_${IB}_AGGREGATED_CASHFLOW_BY_GROUPING.dat"
export ESTJ0001_SORTED_FWD="${DFILT}/${NJOB}_1_${IB}_SORTED_FWD.dat"
export ESTJ0001_SUMMED_FWD="${DFILT}/${NJOB}_1_${IB}_SUMMED_FWD.dat"
export ESTJ0001_ESCOMPTE_MERGED="${DFILT}/${NJOB}_1_${IB}_MERGED_ESCOMPTE_UNSORTED.dat"
export ESTJ0001_SORTED_ASSUM_ESCOMPTE_MERGED="${DFILT}/${NJOB}_1_${IB}_MERGED_ESCOMPTE_SORTED_ASSUM.dat"
export ESTJ0001_SORTED_RETRO_ESCOMPTE_MERGED="${DFILT}/${NJOB}_1_${IB}_MERGED_ESCOMPTE_SORTED_RETRO.dat"
export ESTJ0001_SORTED_ASSUM_FWD="${DFILT}/${NJOB}_1_${IB}_SORTED_ASSUM_FWD.dat"
export ESTJ0001_SORTED_RETRO_FWD="${DFILT}/${NJOB}_1_${IB}_SORTED_RETRO_FWD.dat"
export ESTJ0001_FWD_LKI="${DFILT}/${NJOB}_1_${IB}_FWD_LKI.dat"

export ESTJ0001_SORTED_CONTRACT_RATE_INDEX_A="${DFILT}/${NJOB}_1_${IB}_SORTED_CONTRACT_RATE_INDEX_A.dat"
export ESTJ0001_SORTED_CONTRACT_RATE_INDEX_R="${DFILT}/${NJOB}_1_${IB}_SORTED_CONTRACT_RATE_INDEX_R.dat"
export ESTJ0001_SORTED_ASSUM_FWD_CTR="${DFILT}/${NJOB}_1_${IB}_SORTED_ASSUM_FWD_CTR.dat"
export ESTJ0001_SORTED_RETRO_P_FWD_CTR="${DFILT}/${NJOB}_1_${IB}_SORTED_RETRO_P_FWD_CTR.dat"
export ESTJ0001_SORTED_RETRO_NP_FWD_CTR="${DFILT}/${NJOB}_1_${IB}_SORTED_RETRO_NP_FWD_CTR.dat"
export ESTJ0001_CONTRACT_RATE_INDEX_KEY_RECOVERY="${DFILT}/${NJOB}_1_${IB}_CONTRACT_RATE_INDEX_KEY_RECOVERY.dat"
export ESTJ0001_SORTED_CONTRACT_ASSUM_RATE_INDEX_KEY_RECOVERY="${DFILT}/${NJOB}_1_${IB}_SORTED_CONTRACT_ASSUM_RATE_INDEX_KEY_RECOVERY.dat"
export ESTJ0001_SORTED_CONTRACT_RETRO_RATE_INDEX_KEY_RECOVERY="${DFILT}/${NJOB}_1_${IB}_SORTED_CONTRACT_RETRO_RATE_INDEX_KEY_RECOVERY.dat"

export ESTJ0001_CONTRACT_RATE_INDEX_RECOVERY_PARTIALLY_RECOVERED="${DFILT}/${NJOB}_1_${IB}_ESTJ0001_CONTRACT_RATE_INDEX_RECOVERY_PARTIALLY_RECOVERED.dat"
export ESTJ0001_SORTED_CONTRACT_RATE_INDEX_RECOVERY_PARTIALLY_RECOVERED_A="${DFILT}/${NJOB}_1_${IB}_ESTJ0001_SORTED_CONTRACT_RATE_INDEX_RECOVERY_PARTIALLY_RECOVERED_A.dat"
export ESTJ0001_SORTED_CONTRACT_RATE_INDEX_RECOVERY_PARTIALLY_RECOVERED_RP="${DFILT}/${NJOB}_1_${IB}_ESTJ0001_SORTED_CONTRACT_RATE_INDEX_RECOVERY_PARTIALLY_RECOVERED_RP.dat"
export ESTJ0001_SORTED_CONTRACT_RATE_INDEX_RECOVERY_PARTIALLY_RECOVERED_RNP="${DFILT}/${NJOB}_1_${IB}_ESTJ0001_SORTED_CONTRACT_RATE_INDEX_RECOVERY_PARTIALLY_RECOVERED_RNP.dat"
export ESTJ0001_CONTRACT_RATE_INDEX_RECOVERY_FULLY_RECOVERED="${DFILT}/${NJOB}_1_${IB}_ESTJ0001_CONTRACT_RATE_INDEX_RECOVERY_FULLY_RECOVERED.dat"
export ESTJ0001_SORTED_CONTRACT_RATE_INDEX_RECOVERY_FULLY_RECOVERED_A="${DFILT}/${NJOB}_1_${IB}_ESTJ0001_SORTED_CONTRACT_RATE_INDEX_RECOVERY_FULLY_RECOVERED_A.dat"
export ESTJ0001_SORTED_CONTRACT_RATE_INDEX_RECOVERY_FULLY_RECOVERED_RP="${DFILT}/${NJOB}_1_${IB}_ESTJ0001_SORTED_CONTRACT_RATE_INDEX_RECOVERY_FULLY_RECOVERED_RP.dat"
export ESTJ0001_SORTED_CONTRACT_RATE_INDEX_RECOVERY_FULLY_RECOVERED_RNP="${DFILT}/${NJOB}_1_${IB}_ESTJ0001_SORTED_CONTRACT_RATE_INDEX_RECOVERY_FULLY_RECOVERED_RNP.dat"

# outputs files
export ESTJ0001_FWD_FINAL="${ESF_GTSII_ESCOMPTE_FWD}"

# CMD variable
export SYNCSORT_CMD_ESTJ0001_MERGE_CASHFLOW=${DCMD}/ESTS0005.cmd
export SYNCSORT_CMD_ESTJ0001_SORT_CASHFLOW_BY_CTR_ID_FOR_FWD=${DCMD}/ESTS0038.cmd
export SYNCSORT_CMD_ESTJ0001_SORT_RATE_INDEX_BY_CTR_ID=${DCMD}/ESTS0048.cmd
export SYNCSORT_CMD_ESTJ0001_SORT_FINAL=${DCMD}/ESTS0010.cmd
export SYNCSORT_CMD_ESTJ0001_SORT_CASHFLOW_BY_CTR_ID_FOR_AGG=${DCMD}/ESTS0008.cmd
export SYNCSORT_CMD_ESTJ0001_SORT_CASHFLOW_BY_CTR_ID_FOR_LKI_RECOVERY=${DCMD}/ESTS0009.cmd
export SYNCSORT_CMD_ESTJ0001_SORT_RATE_INDEX_BY_CTR_ID_FOR_LKI_RECOVERY=${DCMD}/ESTS0049.cmd
export SYNCSORT_CMD_ESTJ0001_SORT_RATE_INDEX_EXTENDED_BY_CSUOE_A_FOR_RP=${DCMD}/ESTS0061.cmd
export SYNCSORT_CMD_ESTJ0001_SORT_RATE_INDEX_EXTENDED_BY_CSUOE_R_FOR_RP=${DCMD}/ESTS0062.cmd
export SYNCSORT_CMD_ESTJ0001_SORT_CASHFLOW_BY_CSUOE_ASSUM_FOR_RETRO_P=${DCMD}/ESTS0036.cmd

# Jar execution
JSB_CHAIN="estj0001"
JSB_PARAMS="cloDate=${PARM_ICLODAT_D} normcf=${NORME_CF} idfCt=${IDF_CT}"
# JSB_JAR_PATH="${DJAVA}/OMEGA-IFRS17-0.0.1-SNAPSHOT.jar"
EXECJSB

NSTEP=${NJOB}_2
#------------------------------------------------------------------------------
LIBEL="Erase temporary files"
RMFIL "${DFILT}/${NJOB}*${IB}*.dat"

JOBEND
