#!/bin/ksh
#==================================================================================
# nom de l'application          : SPIRA_98623_INIT 
# date de creation              : 16/09/2021
# auteur                        : Arnaud RUFFAULT
#-----------------------------------------------------------------------------

# Call generic functions
. ${DUTI}/fctgen.cmd

copyFile(){
	echo "============================================================"
	echo ""
	echo "FILE TO COPY:.......:${2}"
	echo "NEW FILE:...........:${1}"
	
			if [ -f $2 ]
			then
					cp -v $2 $1
					echo "==> OK" 
			else
				echo "==> KO : FILE TO COPY doesn't exists, copy is not possible" 
				echo "" 
			fi
	echo ""
	echo "============================================================" 
}

PARM_DATE1=$2
TYPEINV1=$3

echo "We fetch the input parameters"
echo "PARM_DATE1:.........:${2}"
echo "TYPEINV1:...........:${3}"

if [ "$PARM_DATE1" != "" ]
then
        PARM_ICLODAT_D=$PARM_DATE1
else
        PARM_ICLODAT_D=`egrep ' PARM_ICLODAT_D=' ${DFILP}/${ENV_PREFIX}_ESFJ0000_PARM_EBS.dat | cut -d"=" -f2 `
fi

if [ "$TYPEINV1" != "" ]
then
        TYPEINV=$TYPEINV1
else
        TYPEINV=`egrep ' TYPEINV=' ${DFILP}/${ENV_PREFIX}_ESFJ0000_PARM_EBS.dat | cut -d"=" -f2 `
fi

echo "=============================================="
echo "PARM_ICLODAT_D:.........:${PARM_ICLODAT_D}"
echo "TYPEINV:................:${TYPEINV}"




##EST_IADPERICASE_I4=${DFILP}/${ENV_PREFIX}_ESID0560_IADPERICASE_INV_${PARM_ICLODAT_D}.dat
##EST_IRDPERICASE0_I4=${DFILP}/${ENV_PREFIX}_ESID0060_IRDPERICASE0_INV_${PARM_ICLODAT_D}.dat
##EST_IRDVPERICASE_I4=${DFILP}/${ENV_PREFIX}_ESID0560_IRDVPERICASE_INV_${PARM_ICLODAT_D}.dat
##EST_OIRDVPERICASE_I4=${DFILP}/${ENV_PREFIX}_ESID0560_OIRDVPERICASE_INV_${PARM_ICLODAT_D}.dat
EST_IADVPERICASE_I4=${DFILP}/${ENV_PREFIX}_ESID1000_IADVPERICASE0_INV_${PARM_ICLODAT_D}.dat
EST_CADVPERIESB0_I4=${DFILP}/${ENV_PREFIX}_ESID0060_CADVPERIESB0_INV_${PARM_ICLODAT_D}.dat
EST_CRVPERICASE0_I4=${DFILP}/${ENV_PREFIX}_ESID0060_CRVPERICASE0_INV_${PARM_ICLODAT_D}.dat
EST_CTRULT02_I4=${DFILP}/${ENV_PREFIX}_ESID2000_CTRULT02_INV_${PARM_ICLODAT_D}.dat
EST_FCES_I4=${DFILP}/${ENV_PREFIX}_ESID2500_FCES_INV_${PARM_ICLODAT_D}.dat
EST_FCTRGRO0_I4=${DFILP}/${ENV_PREFIX}_ESEH1110_FCTRGRO0_INV_${PARM_ICLODAT_D}.dat
EST_FCTRGRO_I4=${DFILP}/${ENV_PREFIX}_ESID0560_FCTRGRO_INV_${PARM_ICLODAT_D}.dat
EST_FCTRGRO1_I4=${DFILP}/${ENV_PREFIX}_ESID2000_FCTRGRO1_INV_${PARM_ICLODAT_D}.dat
EST_FCTRGROLESII_I4=${DFILP}/${ENV_PREFIX}_ESPT0000_FCTRGROLESII.dat
EST_FCTRULT_I4=${DFILP}/${ENV_PREFIX}_ESID0560_FCTRULT_INV_${PARM_ICLODAT_D}.dat
EST_FPLACEMT0_I4=${DFILP}/${ENV_PREFIX}_ESEH1110_FPLACEMT0_INV_${PARM_ICLODAT_D}.dat
EST_FPLACEMT1_I4=${DFILP}/${ENV_PREFIX}_ESEH1110_FPLACEMT1_INV_${PARM_ICLODAT_D}.dat
EST_FPLACEMT2_I4=${DFILP}/${ENV_PREFIX}_ESEH1110_FPLACEMT2_INV_${PARM_ICLODAT_D}.dat
EST_FPLATXCUM0_I4=${DFILP}/${ENV_PREFIX}_ESID0060_FPLATXCUM0_INV_${PARM_ICLODAT_D}.dat
EST_FPLATXCUM_I4=${DFILP}/${ENV_PREFIX}_ESID0560_FPLATXCUM_INV_${PARM_ICLODAT_D}.dat
EST_FPLATXCUMALL0_I4=${DFILP}/${ENV_PREFIX}_ESID0060_FPLATXCUMALL0_INV_${PARM_ICLODAT_D}.dat
EST_FPLC_I4=${DFILP}/${ENV_PREFIX}_ESID2500_FPLC_INV_${PARM_ICLODAT_D}.dat
EST_FPLCCOM_I4=${DFILP}/${ENV_PREFIX}_ESID25000_FPLCCOM_INV_${PARM_ICLODAT_D}.dat
EST_FSSDACTR_TXT_I4=${DFILP}/${ENV_PREFIX}_ESCJ0060_FSSDACTR_TXT_INV_${PARM_ICLODAT_D}.dat
EST_FTVENTNP_I4=${DFILP}/${ENV_PREFIX}_ESID0060_FTVENTNP_INV_${PARM_ICLODAT_D}.dat
EST_IADPERIFCI_I4=${DFILP}/${ENV_PREFIX}_ESID0560_IADPERIFCI_INV_${PARM_ICLODAT_D}.dat
EST_IADPERIFCT_I4=${DFILP}/${ENV_PREFIX}_ESID0560_IADPERIFCT_INV_${PARM_ICLODAT_D}.dat
EST_IADPERIFR_I4=${DFILP}/${ENV_PREFIX}_ESID0560_IADPERIFR_INV_${PARM_ICLODAT_D}.dat
EST_IADPERICASE_ENTIER0_I4=${DFILP}/${ENV_PREFIX}_ESEH1100_IADPERICASE_ENTIER0_INV_${PARM_ICLODAT_D}.dat
EST_IADPERICASE0_I4=${DFILP}/${ENV_PREFIX}_ESEH1100_IADPERICASE0_INV_${PARM_ICLODAT_D}.dat
EST_IARVPERICASE0_I4=${DFILP}/${ENV_PREFIX}_ESID2030_IARVPERICASE0_INV_${PARM_ICLODAT_D}.dat
EST_FCESSION0_I4=${DFILP}/${ENV_PREFIX}_ESEH1110_FCESSION0_INV_${PARM_ICLODAT_D}.dat
##EST_IADPERICASE_5010=${DFILP}/${ENV_PREFIX}_ESFD5010_IADPERICASE_STD_EBS_INV_${PARM_ICLODAT_D}.dat
##EST_IRDPERICASE0_5010=${DFILP}/${ENV_PREFIX}_ESFD5010_IRDPERICASE0_EBS_INV_${PARM_ICLODAT_D}.dat
##EST_IRDVPERICASE_5010=${DFILP}/${ENV_PREFIX}_ESFD5010_IRDVPERICASE_EBS_INV_${PARM_ICLODAT_D}.dat
##EST_OIRDVPERICASE_5010=${DFILP}/${ENV_PREFIX}_ESFD5010_OIRDVPERICASE_EBS_INV_${PARM_ICLODAT_D}.dat
EST_IADVPERICASE_5010=${DFILP}/${ENV_PREFIX}_ESFD5010_IADVPERICASE_EBS_INV_${PARM_ICLODAT_D}.dat
EST_FSSDACTR_TXT_5010=${DFILP}/${ENV_PREFIX}_ESFD5010_FSSDACTR_TXT_EBS_INV_${PARM_ICLODAT_D}.dat
EST_CADVPERIESB0_5010=${DFILP}/${ENV_PREFIX}_ESFD5010_CADVPERIESB0_EBS_INV_${PARM_ICLODAT_D}.dat
EST_CRVPERICASE0_5010=${DFILP}/${ENV_PREFIX}_ESFD5010_CRVPERICASE0_EBS_INV_${PARM_ICLODAT_D}.dat
EST_CTRULT02_5010=${DFILP}/${ENV_PREFIX}_ESFD5010_CTRULT02_EBS_INV_${PARM_ICLODAT_D}.dat
EST_FCES_5010=${DFILP}/${ENV_PREFIX}_ESFD5010_FCES_EBS_INV_${PARM_ICLODAT_D}.dat
EST_FCTRGRO0_5010=${DFILP}/${ENV_PREFIX}_ESFD5010_FCTRGRO0_EBS_INV_${PARM_ICLODAT_D}.dat
EST_FCTRGRO_5010=${DFILP}/${ENV_PREFIX}_ESFD5010_FCTRGRO_EBS_INV_${PARM_ICLODAT_D}.dat
EST_FCTRGRO1_5010=${DFILP}/${ENV_PREFIX}_ESFD5010_FCTRGRO1_EBS_INV_${PARM_ICLODAT_D}.dat
EST_FCTRGROLESII_5010=${DFILP}/${ENV_PREFIX}_ESFD5010_FCTRGROLESII_EBS_INV_${PARM_ICLODAT_D}.dat
EST_FCTRULT_5010=${DFILP}/${ENV_PREFIX}_ESFD5010_FCTRULT_EBS_INV_${PARM_ICLODAT_D}.dat
EST_FPLACEMT0_5010=${DFILP}/${ENV_PREFIX}_ESFD5010_FPLACEMT0_EBS_INV_${PARM_ICLODAT_D}.dat
EST_FPLACEMT1_5010=${DFILP}/${ENV_PREFIX}_ESFD5010_FPLACEMT1_EBS_INV_${PARM_ICLODAT_D}.dat
EST_FPLACEMT2_5010=${DFILP}/${ENV_PREFIX}_ESFD5010_FPLACEMT2_EBS_INV_${PARM_ICLODAT_D}.dat
EST_FPLATXCUM0_5010=${DFILP}/${ENV_PREFIX}_ESFD5010_FPLATXCUM0_EBS_INV_${PARM_ICLODAT_D}.dat
EST_FPLATXCUM_5010=${DFILP}/${ENV_PREFIX}_ESFD5010_FPLATXCUM_EBS_INV_${PARM_ICLODAT_D}.dat
EST_FPLATXCUMALL0_5010=${DFILP}/${ENV_PREFIX}_ESFD5010_FPLATXCUMALL0_EBS_INV_${PARM_ICLODAT_D}.dat
EST_FPLC_5010=${DFILP}/${ENV_PREFIX}_ESFD5010_FPLC_EBS_INV_${PARM_ICLODAT_D}.dat
EST_FPLCCOM_5010=${DFILP}/${ENV_PREFIX}_ESFD5010_FPLCCOM_EBS_INV_${PARM_ICLODAT_D}.dat
EST_FTVENTNP_5010=${DFILP}/${ENV_PREFIX}_ESFD5010_FTVENTNP_EBS_INV_${PARM_ICLODAT_D}.dat
EST_FVENTNPANT_5010=${DFILP}/${ENV_PREFIX}_ESFD5010_FVENTNPANT_EBS_INV_${PARM_ICLODAT_D}.dat
EST_IADPERIFCI_5010=${DFILP}/${ENV_PREFIX}_ESFD5010_IADPERIFCI_EBS_INV_${PARM_ICLODAT_D}.dat
EST_IADPERIFCT_5010=${DFILP}/${ENV_PREFIX}_ESFD5010_IADPERIFCT_EBS_INV_${PARM_ICLODAT_D}.dat
EST_IADPERIFR_5010=${DFILP}/${ENV_PREFIX}_ESFD5010_IADPERIFR_EBS_INV_${PARM_ICLODAT_D}.dat
EST_IADPERICASE_ENTIER0_5010=${DFILP}/${ENV_PREFIX}_ESFD5010_IADPERICASE_ENTIER0_EBS_INV_${PARM_ICLODAT_D}.dat
EST_IADPERICASE0_5010=${DFILP}/${ENV_PREFIX}_ESFD5010_IADPERICASE0_EBS_INV_${PARM_ICLODAT_D}.dat
EST_IARVPERICASE0_5010=${DFILP}/${ENV_PREFIX}_ESFD5010_IARVPERICASE0_EBS_INV_${PARM_ICLODAT_D}.dat
EST_FCESSION0_5010=${DFILP}/${ENV_PREFIX}_ESFD5010_FCESSION0_EBS_INV_${PARM_ICLODAT_D}.dat


if [ "${TYPEINV}" = "POS"  ]
then 
		if [ "${PARM_ICLODAT_D}" != "" ]
		then
			echo "OK: run with PARM_ICLODAT_D=$PARM_ICLODAT_D TYPEINV=$TYPEINV" 
			echo "============================================================" 
			#copyFile "$[EST_IADPERICASE_5010}" "$[EST_IADPERICASE_I4}"
			#copyFile "$[EST_IRDPERICASE0_5010}" "$[EST_IRDPERICASE0_I4}"
			#copyFile "$[EST_IRDVPERICASE_5010}" "$[EST_IRDVPERICASE_I4}"
			#copyFile "$[EST_OIRDVPERICASE_5010}" "$[EST_OIRDVPERICASE_I4}"
			copyFile "${EST_IADVPERICASE_5010}" "${EST_IADVPERICASE_I4}"
			copyFile "${EST_FSSDACTR_TXT_5010}" "${EST_FSSDACTR_TXT_I4}"
			copyFile "${EST_CADVPERIESB0_5010}" "${EST_CADVPERIESB0_I4}"
			copyFile "${EST_CRVPERICASE0_5010}" "${EST_CRVPERICASE0_I4}"
			copyFile "${EST_CTRULT02_5010}" "${EST_CTRULT02_I4}"
			copyFile "${EST_FCES_5010}" "${EST_FCES_I4}"
			copyFile "${EST_FCTRGRO0_5010}" "${EST_FCTRGRO0_I4}"
			copyFile "${EST_FCTRGRO_5010}" "${EST_FCTRGRO_I4}"
			copyFile "${EST_FCTRGRO1_5010}" "${EST_FCTRGRO1_I4}"
			copyFile "${EST_FCTRGROLESII_5010}" "${EST_FCTRGROLESII_I4}"
			copyFile "${EST_FCTRULT_5010}" "${EST_FCTRULT_I4}"
			copyFile "${EST_FPLACEMT0_5010}" "${EST_FPLACEMT0_I4}"
			copyFile "${EST_FPLACEMT1_5010}" "${EST_FPLACEMT1_I4}"
			copyFile "${EST_FPLACEMT2_5010}" "${EST_FPLACEMT2_I4}"
			copyFile "${EST_FPLATXCUM0_5010}" "${EST_FPLATXCUM0_I4}"
			copyFile "${EST_FPLATXCUM_5010}" "${EST_FPLATXCUM_I4}"
			copyFile "${EST_FPLATXCUMALL0_5010}" "${EST_FPLATXCUMALL0_I4}"
			copyFile "${EST_FPLC_5010}" "${EST_FPLC_I4}"
			copyFile "${EST_FPLCCOM_5010}" "${EST_FPLCCOM_I4}"
			copyFile "${EST_FTVENTNP_5010}" "${EST_FTVENTNP_I4}"
			copyFile "${EST_FVENTNPANT_5010}" "${EST_FTVENTNP_I4}"
			copyFile "${EST_IADPERIFCI_5010}" "${EST_IADPERIFCI_I4}"
			copyFile "${EST_IADPERIFCT_5010}" "${EST_IADPERIFCT_I4}"
			copyFile "${EST_IADPERIFR_5010}" "${EST_IADPERIFR_I4}"
			copyFile "${EST_IADPERICASE_ENTIER0_5010}" "${EST_IADPERICASE_ENTIER0_I4}"
			copyFile "${EST_IADPERICASE0_5010}" "${EST_IADPERICASE0_I4}"
			copyFile "${EST_IARVPERICASE0_5010}" "${EST_IARVPERICASE0_I4}"
			copyFile "${EST_FCESSION0_5010}" "${EST_FCESSION0_I4}"
		else
        echo "error cannot use PARM_ICLODAT_D=$PARM_ICLODAT_D file=${DFILP}/${ENV_PREFIX}_ESFJ0000_PARM_EBS.dat  "  
        exit 11
	fi
fi

if [ "${TYPEINV}" = "INV"  ]
then 
		echo "TYPEINV = INV, no need to initialize the ESFD5010 INV files, the closing will do" 
fi

