#!/bin/ksh
#==================================================================================
# nom de l'application          : ESTIMATIONS 
# date de creation              : 21/12/2020
# auteur                        : Mr JYP
#-----------------------------------------------------------------------------
# [001] 21/12/2020 JYP: SPIRA 91991 rename files for I17P I17L
# [002] 26/01/2021 JYP: SPIRA 91991 init empty file for I17P I17L
#set -x

PARM_DATE1=$2
PARM_DATE2=$3

# Call generic functions
. ${DUTI}/fctgen.cmd

CHAININIT CNLD0030 $DENV/CNLD0030.env




if [ "$PARM_DATE1" != "" ]
then
        PARM_ICLODAT_D=$PARM_DATE1
else
        PARM_ICLODAT_D=`grep "PARM_ICLODAT_D=" $DFILP/${ENV_PREFIX}_ESFJ0000_PARM.dat | cut -d"=" -f2 `
fi

if [ "$PARM_DATE2" != "" ]
then
        PARM_PREV_ICLODAT_D=$PARM_DATE2
else
        PARM_PREV_ICLODAT_D=`grep "PARM_PREV_ICLODAT_D=" $DFILP/${ENV_PREFIX}_ESFJ0000_PARM.dat | cut -d"=" -f2 `
fi



if [ "${PARM_ICLODAT_D}" != "" -a "${PARM_PREV_ICLODAT_D}" != "" ]
then
        echo "OK: run with PARM_ICLODAT_D=$PARM_ICLODAT_D PARM_PREV_ICLODAT_D=$PARM_PREV_ICLODAT_D"  >> $FLOG
        echo "OK: run with PARM_ICLODAT_D=$PARM_ICLODAT_D PARM_PREV_ICLODAT_D=$PARM_PREV_ICLODAT_D" 
else
        echo "error cannot use PARM_ICLODAT_D=$PARM_ICLODAT_D PARM_PREV_ICLODAT_D=$PARM_PREV_ICLODAT_D file=${DFILP}/${ENV_PREFIX}_ESFJ0000_PARM.dat  "  >> $FLOG
        echo "error cannot use PARM_ICLODAT_D=$PARM_ICLODAT_D PARM_PREV_ICLODAT_D=$PARM_PREV_ICLODAT_D file=${DFILP}/${ENV_PREFIX}_ESFJ0000_PARM.dat  "  
        exit 11
fi



NJOB=${ENV_PREFIX}_ESID2210_90054

# Initialization of the Job
JOBINIT

echo "Starting $0 $1 $FLOG " 
echo "Starting $0 $1" >> $FLOG
date >> $FLOG


NSTEP=${NCHAIN}_${NJOB}_05
LIBEL="rename file  "


set -x


for NORME_CF in `echo "I17G" "I17P" "I17L"   `
do
 echo "Init $NORME_CF "
 echo "Init $NORME_CF " >> $FLOG


if [ ! -f ${DFILP}/${ENV_PREFIX}_ESFD0060_${NORME_CF}_FMARKET_${PARM_PREV_ICLODAT_D}.dat  ]
then
  if [ -f ${DFILP}/${ENV_PREFIX}_ESFD0060_FMARKET_${PARM_PREV_ICLODAT_D}.dat  ]
  then
       cp ${DFILP}/${ENV_PREFIX}_ESFD0060_FMARKET_${PARM_PREV_ICLODAT_D}.dat ${DFILP}/${ENV_PREFIX}_ESFD0060_${NORME_CF}_FMARKET_${PARM_PREV_ICLODAT_D}.dat 
  else 
       touch ${DFILP}/${ENV_PREFIX}_ESFD0060_${NORME_CF}_FMARKET_${PARM_PREV_ICLODAT_D}.dat
  fi
  
fi


done


for NORME_CF in `echo "I17P" "I17L"   `
do
 echo "Init $NORME_CF "
 echo "Init $NORME_CF " >> $FLOG
 
touch ${DFILP}/${ENV_PREFIX}_ESFD3620_${NORME_CF}_RAD_LKI_INI_GTSII_ESCOMPTE_${PARM_ICLODAT_D}.dat

# NO prev file should not block I17L/P
touch ${DFILP}/${ENV_PREFIX}_ESFD3770_I17P_CSM_AMR_STD_CSM_LC_AMORT_PATTERN_${PARM_PREV_ICLODAT_D}.dat
touch ${DFILP}/${ENV_PREFIX}_ESFD3760_I17P_UOA_PRO_STD_FSEGPROF_${PARM_PREV_ICLODAT_D}.dat
touch ${DFILP}/${ENV_PREFIX}_ESFD3760_I17P_UOA_PRO_STD_GTSII_CSM_CASHFLOW_${PARM_PREV_ICLODAT_D}.dat
#touch ${DFILP}/${ENV_PREFIX}_ESFD1130_FSEGPATTERNDSCf17_${NORME_CF}_${PARM_PREV_ICLODAT_D}.dat
touch ${DFILP}/${ENV_PREFIX}_ESFD3740_I17P_SII_GLT_STD_FTECLEDA_${PARM_PREV_ICLODAT_D}.dat
touch ${DFILP}/${PCH}ESFD0060_I17P____EXPRAT_${TYPEINV}_${PARM_PREV_ICLODAT_D}.dat
touch ${DFILP}/${ENV_PREFIX}_ESFD0060_I17P____RET_FEXPRAT_${PARM_PREV_ICLODAT_D}.dat
touch ${DFILP}/${PCH}ESFD0060_I17P____EXPRAT_${TYPEINV}_${PARM_PREV_ICLODAT_D}.dat
touch ${DFILP}/${ENV_PREFIX}_ESFD0060_I17P____RET_FEXPRAT_${PARM_PREV_ICLODAT_D}.dat
#touch ${DFILP}/${PCH}ESPD3610_GTSII_GLOBAL_CASHFLOW${TYPEINV0}_${PARM_PREV_ICLODAT_D}.dat
touch ${DFILP}/${PCH}ESFD3690_I17P_IRV_ALL_STD_DAC_LKI_CASHFLOW_${PARM_PREV_ICLODAT_D}.dat
touch ${DFILP}/${ENV_PREFIX}_ESFD3760_I17P_UOA_PRO_STD_FSEGPROF_${PARM_PREV_ICLODAT_D}.dat
touch ${DFILP}/${ENV_PREFIX}_ESFD3620_I17P_DSC_LKI_STD_GTSII_ESCOMPTE_${PARM_PREV_ICLODAT_D}.dat
touch ${DFILP}/${ENV_PREFIX}_ESFD3620_I17P_RAD_LKI_STD_GTSII_ESCOMPTE_${PARM_PREV_ICLODAT_D}.dat
touch ${DFILP}/${ENV_PREFIX}_ESFD3630_I17P_IEX_ALL_STD_GTSII_GLOBAL_CASHFLOW_${PARM_PREV_ICLODAT_D}.dat
touch ${DFILP}/${ENV_PREFIX}_ESFD3650_I17P_RAD_CKI_STD_GTSII_CASHFLOW_${PARM_PREV_ICLODAT_D}.dat
touch ${DFILP}/${ENV_PREFIX}_ESFD3770_I17L_CSM_AMR_STD_CSM_LC_AMORT_PATTERN_${PARM_PREV_ICLODAT_D}.dat
touch ${DFILP}/${ENV_PREFIX}_ESFD3760_I17L_UOA_PRO_STD_FSEGPROF_${PARM_PREV_ICLODAT_D}.dat
touch ${DFILP}/${ENV_PREFIX}_ESFD3760_I17L_UOA_PRO_STD_GTSII_CSM_CASHFLOW_${PARM_PREV_ICLODAT_D}.dat
#touch ${DFILP}/${ENV_PREFIX}_ESFD1130_FSEGPATTERNDSCf17_${NORME_CF}_${PARM_PREV_ICLODAT_D}.dat
touch ${DFILP}/${ENV_PREFIX}_ESFD3740_I17L_SII_GLT_STD_FTECLEDA_${PARM_PREV_ICLODAT_D}.dat
touch ${DFILP}/${PCH}ESFD0060_I17L____EXPRAT_${TYPEINV}_${PARM_PREV_ICLODAT_D}.dat
touch ${DFILP}/${ENV_PREFIX}_ESFD0060_I17L____RET_FEXPRAT_${PARM_PREV_ICLODAT_D}.dat
touch ${DFILP}/${PCH}ESFD0060_I17L____EXPRAT_${TYPEINV}_${PARM_PREV_ICLODAT_D}.dat
touch ${DFILP}/${ENV_PREFIX}_ESFD0060_I17L____RET_FEXPRAT_${PARM_PREV_ICLODAT_D}.dat
#touch ${DFILP}/${PCH}ESPD3610_GTSII_GLOBAL_CASHFLOW${TYPEINV0}_${PARM_PREV_ICLODAT_D}.dat
touch ${DFILP}/${PCH}ESFD3690_I17L_IRV_ALL_STD_DAC_LKI_CASHFLOW_${PARM_PREV_ICLODAT_D}.dat
touch ${DFILP}/${PCH}ESFD3630_I17L_IEX_ALL_STD_GTSII_GLOBAL_CASHFLOW_${PARM_PREV_ICLODAT_D}.dat
touch ${DFILP}/${PCH}ESFD3630_I17L_IEX_ALL_STD_GTSII_GLOBAL_CASHFLOW_${PARM_PREV_ICLODAT_D}.dat
touch ${DFILP}/${ENV_PREFIX}_ESFD3760_I17L_UOA_PRO_STD_FSEGPROF_${PARM_PREV_ICLODAT_D}.dat
touch ${DFILP}/${ENV_PREFIX}_ESFD3620_I17L_DSC_LKI_STD_GTSII_ESCOMPTE_${PARM_PREV_ICLODAT_D}.dat
touch ${DFILP}/${ENV_PREFIX}_ESFD3620_I17L_RAD_LKI_STD_GTSII_ESCOMPTE_${PARM_PREV_ICLODAT_D}.dat
touch ${DFILP}/${ENV_PREFIX}_ESFD3630_I17L_IEX_ALL_STD_GTSII_GLOBAL_CASHFLOW_${PARM_PREV_ICLODAT_D}.dat
touch ${DFILP}/${ENV_PREFIX}_ESFD3650_I17L_RAD_CKI_STD_GTSII_CASHFLOW_${PARM_PREV_ICLODAT_D}.dat


done
 

set +x

echo "End of script OK status $? " >> $FLOG
echo "End of script OK status $? " 

JOBEND


